samples/dotnet/api-azure-function/README.md
**Motivation and Context**
To make it easier for a developer to understand how the Azure Function integrates the Semantic Kernel.
**Description**
This PR adds a single image to the readme for the Azure Function that shows the basic flow of data from the caller via HTTP POST, to the Azure Function/Semantic Kernel, which in turn makes a HTTP POST request to Azure Open AI/Open AI
=> Updated diagram for azure function readme

samples/apps/auth-api-webapp-react/src/components/InteractWithGraph.tsx, samples/apps/auth-api-webapp-react/src/components/ServiceConfig.tsx, samples/apps/auth-api-webapp-react/src/components/TaskButton.tsx, samples/apps/auth-api-webapp-react/src/hooks/SemanticKernel.ts, samples/apps/book-creator-webapp-react/src/components/CreateBook.tsx, samples/apps/book-creator-webapp-react/src/components/CreateBookWithPlanner.tsx, samples/apps/book-creator-webapp-react/src/components/ServiceConfig.tsx, samples/apps/book-creator-webapp-react/src/components/TopicSelection.tsx, samples/apps/book-creator-webapp-react/src/hooks/SemanticKernel.ts, samples/apps/chat-summary-webapp-react/src/components/AISummary.tsx, samples/apps/chat-summary-webapp-react/src/components/ServiceConfig.tsx, samples/apps/chat-summary-webapp-react/src/hooks/SemanticKernel.ts
Currently the pop-up error messages from the sample apps do not correctly describe what actually went wrong. For example:
This PR adds details to the error messages. For example:
=> Improve Azure function error messages in sample apps

README.md
Add a couple of badges to the README. There are a few more we can add later.
=> Add nuget and license badges to README

README.md
Per discussion with @timlaverty and @evchaki, we want to communicate to the community that the Semantic Kernel is very early and will rapidly evolve. Also want to say that we invite the community to build the project together. 
Purpose is to show that we do not know everything and that we're open to feedback.
Line at the top of the README
=> Add line to README that project is alpha 

.vscode/launch.json, .vscode/tasks.json, dotnet/Directory.Packages.props
Quality of life changes for development in the repository using VSCode.
- Fixes the program and cwd paths in the launch.json file for the KernelSyntaxExamples project
- Adds comments and clarifies the arguments for the R# check and cleanup tasks in the tasks.json file
- Adds a new task to run the Semantic-Kernel tests with code coverage enabled and output the results in lcov format
- Removes some trailing whitespace in the Directory.Packages.props file
=> Update VSCode launch and task settings and add code coverage option

.conf/.pre-commit-config.yaml, .conf/flake8.cfg, DESIGN.md, DEV_SETUP.md, Makefile, semantic_kernel/ai/embeddings/embedding_index_base.py, semantic_kernel/memory/volatile_memory_store.py, semantic_kernel/orchestration/delegate_inference.py, semantic_kernel/orchestration/sk_context.py, semantic_kernel/semantic_functions/prompt_template_config.py, tests/chat.py
Adding a Design Doc with information on the status of the port, design directions, changes from the C# version, and work left to do.
Adding a Design Doc + some development setup instructions. Also adding in the configs I've been using to enforce code style and do linting.
NA
=> Python (experimental): Add design doc + some linter configs

README.md
The project is very early and we want to hear feedback from everyone. Adding a more visible note early in the README is important to boost collaboration and to improve SK.
Extend the note in the README with links inviting the community to work together.
=> Invite people to collaborate :-)

README.md
Updating links on main readme.
=> Update main README.md links to public docs site

dotnet/src/SemanticKernel.UnitTests/Memory/Collections/MinHeapTests.cs, dotnet/src/SemanticKernel.UnitTests/Reliability/DefaultHttpRetryHandlerTests.cs, dotnet/src/SemanticKernel/KernelBuilder.cs, dotnet/src/SemanticKernel/TemplateEngine/Blocks/VarBlock.cs
Fix typos and code style again, looks like these fixes got lost during recent merges.
=> Fix typos and code style

samples/apps/github-qna-webapp-react/README.md
Some links in the sample's readme are missing. And the trouble shooting section is no longer needed.
1. Add the correct links to the readme.
2. Remove the trouble shooting section in the readme.
=> Update readme links and trouble-shooting section

samples/dotnet/KernelHttpServer/Extensions.cs, samples/dotnet/KernelHttpServer/SemanticKernelEndpoint.cs, samples/dotnet/github-skills/GitHubSkill.cs, samples/dotnet/github-skills/GitHubSkillsExample.csproj
Prevent failures when the repository has a large file included (ie: an all inclusive changelog).
=> Sample4 hotfix

README.md
=> Add Discord widget to Readme

samples/apps/github-qna-webapp-react/README.md, samples/apps/github-qna-webapp-react/src/components/GitHubRepoSelection.tsx, samples/apps/github-qna-webapp-react/src/components/QnA.tsx, samples/dotnet/KernelHttpServer/Extensions.cs, samples/dotnet/KernelHttpServer/SemanticKernelEndpoint.cs, samples/dotnet/github-skills/GitHubSkill.cs, samples/skills/QASkill/GitHubMemoryQuery/config.json, samples/skills/QASkill/GitHubMemoryQuery/skprompt.txt, samples/skills/QASkill/MemoryQuery/skprompt.txt
This resolves several of the open feedback items in the current PR from memory-sample -> main
=> Several changes to resolve PR feedback

samples/apps/github-qna-webapp-react/README.md, samples/apps/github-qna-webapp-react/src/components/GitHubRepoSelection.tsx
It is not obvious to users that Sample 4 currently only processes markdown files.
1. Add a paragraph in the sample 4 readme that points out the app only processes markdown files.
2. Add a tooltip in the repo selection page that informs users only the files of the specified type will be processed.
=> Minor non-functional updates to sample 4

dotnet/src/SemanticKernel.UnitTests/Memory/VolatileMemoryStoreTests.cs, dotnet/src/SemanticKernel.UnitTests/Planning/SKContextExtensionsTests.cs, dotnet/src/SemanticKernel/AI/Embeddings/IEmbeddingWithMetadata.cs, dotnet/src/SemanticKernel/CoreSkills/TextMemorySkill.cs, dotnet/src/SemanticKernel/Memory/MemoryQueryResult.cs, dotnet/src/SemanticKernel/Memory/MemoryRecord.cs, dotnet/src/SemanticKernel/Memory/MemoryRecordMetadata.cs, dotnet/src/SemanticKernel/Memory/SemanticTextMemory.cs, dotnet/src/SemanticKernel/Planning/SKContextExtensions.cs, samples/dotnet/kernel-syntax-examples/Example14_Memory.cs
Updating the way metadata is serialized in memory.
Updating tests and examples.
=> Updating IEmbeddingWithMetadata to include GetSerializedMetadata();

refapp/SKWebApi/Skills/ChatSkill.cs
A couple changes to the kernel since the last rebase to main that affected the skill implementation:
1. The class CompleteRequestSettings was moved to another scope.
2. IsCriticalException() was change to internal.
3. MemoryQueryResult got another property called Metadata that encapsulated properties that previously lived directly under MemoryQueryResult.
Update the chat skill to align with the latest kernel changes.
=> Update chat skill to align with the latest kernel changes

samples/dotnet/github-skills/GitHubSkill.cs
When using a database backed memory store, there is typically a unique id constraint. The current code will supply the same id when there are multiple paragraphs that have been summarised for the same file. 
This PR appends a number to the end of each id to guarantee uniqueness.
=> Fix Github skill to better support DB backed memory stores

samples/apps/copilot-chat-app/SKWebApi/Skills/ChatSkill.cs
Format check is failing PRs due to two style issues in ChatSkill. This  change resolves those issues.
=> Minor styles fixes to ChatSkill

samples/apps/copilot-chat-app/WebApp/README.md, samples/apps/copilot-chat-app/WebApp/src/App.tsx, samples/apps/copilot-chat-app/WebApp/src/Constants.ts, samples/apps/copilot-chat-app/WebApp/src/libs/semantic-kernel/SemanticKernel.ts, samples/apps/copilot-chat-app/WebApp/src/libs/useChat.ts
Fixing environment variables to prefix required "REACT_APP" so the CRA tool knows to use it during the build process
=> Fixing env variables and README

samples/apps/copilot-chat-app/SKWebApi/README.md, samples/apps/copilot-chat-app/SKWebApi/appsettings.json
We want users to know how to properly configure and start the service.
Added contents to the README and changed appsettings,jspn to be less easily misused.
=> Fill README.md and update appsettings.json

samples/apps/copilot-chat-app/WebApp/src/components/views/BackendProbe.tsx, samples/apps/copilot-chat-app/WebApp/src/libs/semantic-kernel/SemanticKernel.ts
Using the URL object to assemble the request URL
=> Constructing Request URL with URL Type

README.md
Update README with latest syntax from new nuget
=> Sync README with nuget

.gitignore, README.md, samples/apps/auth-api-webapp-react/README.md, samples/apps/book-creator-webapp-react/README.md, samples/apps/chat-summary-webapp-react/README.md, samples/apps/copilot-chat-app/WebApp/README.md, samples/apps/github-qna-webapp-react/README.md, samples/dotnet/KernelHttpServer/README.md
Allows users to store secrets and other sensitive info locally and not checking it in by mistake
=> added *.development.config and *.development.json to gitignore

samples/apps/copilot-chat-app/SKWebApi/Config/ConfigExtensions.cs, samples/apps/copilot-chat-app/SKWebApi/SKWebApi.csproj, samples/apps/copilot-chat-app/SKWebApi/appsettings.json
We need a way to store secrets used by the server that works in Azure
Add KV support in configuration system
=> Support Azure Key Vault

dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Extensions/KernelOpenApiExtensions.cs
If the OpenAPI parameters descriptions are available, populating them in functions.
=> Populating OpenAPI parameter description

dotnet/src/SemanticKernel.IntegrationTests/CoreSkills/PlannerSkillTests.cs
Disabling an unreliable integration test in PlannerSkillTests.
=> Disabling a complex planner test that's frequently failing.

samples/dotnet/kernel-syntax-examples/Example24_Tokenizer.cs, samples/dotnet/kernel-syntax-examples/Program.cs
New syntax example for the GPT tokenizer.
=> Add GPT tokenizer example

README.md, dotnet/README.md, python/FEATURE_PARITY.md, samples/apps/copilot-chat-app/WebApp/README.md, samples/apps/copilot-chat-app/WebApp/src/libs/auth/AuthHelper.ts, samples/apps/copilot-chat-app/WebApp/src/libs/semantic-kernel/SemanticKernel.ts
=> Fix typos and improve docs

dotnet/README.md, samples/notebooks/dotnet/0-AI-settings.ipynb
1. Fix broken links
2. Some users find the C# notebook setup not useful or broken, mostly because VSCode doesn't handle input very well (e.g. the UI throws exceptions when it loses focus). I added some notes explaining how to edit the config manually if needed.
=> Fix links and improve C# setup notebook

samples/apps/copilot-chat-app/webapi/Storage/ChatMessageRepository.cs, samples/apps/copilot-chat-app/webapi/Storage/ChatSessionRepository.cs, samples/apps/copilot-chat-app/webapi/Storage/CosmosDbContext.cs
This reverts commit d67f027ccfe9e3bbefde49cc03daca801dc4aaa4 due to a break in Copilot Chat.
=> Revert "Configure CosmosDB SDK to serialize JSON with camel case (#456)"

samples/apps/copilot-chat-app/WebApp/src/Constants.ts
We can't use the copilot chat app with this scope included
Remove User.Read scope
=> Remove User.Read auth scope

README.md
1. Why is this change required?                 -> more consistancy
2. What problem does it solve?                 -> make it clear on the button that discord is used
3. What scenario does it contribute to?     -> visibility of discord
- changed name of button
+ the color to match it with the 'Kernel' color.
+ added discord logo
no code was provided
=> changed name_of_button+discord_logo+color

python/poetry.lock, python/pyproject.toml, python/requirements.txt
We don't need to specify asyncio in dependency lists because it is native to python.
- Remove asyncio from pyproject.toml and requirements.txt
=> Remove asyncio from dependency lists

samples/apps/copilot-chat-app/webapi/appsettings.json
Feedback was that it was difficult to visually parse the appsettings.json when preparing to deploy locally.
- Refactored comments into blocks for each section
- Added a "quickstart" at the top of the file.
=> Refactor comments in CopilotChat appsettings

dotnet/README.md, samples/notebooks/dotnet/00-getting-started.ipynb, samples/notebooks/dotnet/01-basic-loading-the-kernel.ipynb, samples/notebooks/dotnet/02-running-prompts-from-file.ipynb, samples/notebooks/dotnet/03-semantic-function-inline.ipynb, samples/notebooks/dotnet/04-context-variables-chat.ipynb, samples/notebooks/dotnet/05-using-the-planner.ipynb, samples/notebooks/dotnet/06-memory-and-embeddings.ipynb, samples/notebooks/dotnet/07-DALL-E-2.ipynb, samples/notebooks/dotnet/08-chatGPT-with-DALL-E-2.ipynb
Update READMEs and notebooks with latest nugets
=> Update READMEs and notebooks with latest nugets

.vscode/extensions.json
Adding the Semantic Kernel Tools as a recommended extension to our repository at Shannon's request.
When you open this repository in VS Code you will see this prompt
=> Add Semantic Kernel as recommended extension

samples/apps/copilot-chat-app/README.md, samples/apps/copilot-chat-app/webapi/appsettings.json
Aid developers with recent changes to the repo.
- Added troubleshooting section regarding configuration key changes
- Added troubleshooting section regarding chat completions
- Added links to create Azure Speech resource
=> CopilotChat: updated README with two more troubleshooting sections from recent updates

python/README.md
Updated broken link due to move and rename of the Feature Parity Matrix markdown file.
=> update link to new feature matrix in Python SK Readme

dotnet/src/SemanticKernel.Abstractions/Diagnostics/Verify.cs
Clean up the throw helper Verify to make it cheaper.
- Especially when these kinds of throw helpers are marked AggressiveInlining, the code that actually performs the throw should be separated out into a separate helper to keep the caller streamlined.
- The name validation routines were creating a new Regex on every call.  That's very expensive.  If these methods are called _a lot_, we should make the Regex be compiled, but I assume they're not actually invoked enough to make that worthwhile.
- The StartsWith helper was using InvariantCultureIgnoreCase; this is rarely the right thing, so I assume the intention was OrdinalIgnoreCase.
- ParametersUniqueness would create a HashSet even if there weren't any parameters. The input was an IEnumerable even though all inputs were lists, resulting …
=> Clean up Microsoft.SemanticKernel.Diagnostics.Verify

dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/OpenApi/OpenApiDocumentParser.cs, dotnet/src/SemanticKernel.UnitTests/Connectors/WebApi/Rest/RestApiOperationRunnerTests.cs, dotnet/src/SemanticKernel.UnitTests/TemplateEngine/PromptTemplateEngineTests.cs, dotnet/src/SemanticKernel/Connectors/WebApi/Rest/RestApiOperationRunner.cs, dotnet/src/SemanticKernel/Kernel.cs
Clean up the build.
There are several diagnostics triggering and are easily fixable.
=> Fix a few analyzer diagnostics

samples/dotnet/AIPluginsServer/AIPlugins.AzureFunctions.Extensions/KernelAIPluginRunner.cs, samples/dotnet/AIPluginsServer/AIPlugins.AzureFunctions.Extensions/KernelExtensions.cs, samples/dotnet/AIPluginsServer/AIPlugins.AzureFunctions.Generator/SemanticSkillGenerator.cs
This PR has two fixes to allow this app to work with OpenAPI skills.
The first fix prevents endless while loop, and the other one read http operation body as as string.
=> A few small fixes

samples/apps/copilot-chat-app/README.md
Markdown link is broken
- fixed markdown link
=> Fix md failure

.github/labeler.yml, .github/workflows/label.yml
This pull request adds a new workflow and configuration file for using the labeler action in GitHub Actions. The labeler action automatically applies labels to pull requests based on the paths of the modified files. This can help with triaging and categorizing pull requests, as well as triggering other workflows based on the labels. The configuration file defines several labels and the corresponding file patterns that match them, such as 'kernel', 'python', 'samples', and '.NET'. The workflow runs on the pull_request_target event, which allows it to access the repository token and label pull requests from forks.
- Add a new file .github/labeler.yml that defines the labels and the file patterns that match them       
- Add a new file .github/workflows/label.yml that defines the workflow …
=> Add labeler workflow and configuration for GitHub Actions

samples/notebooks/python/03-semantic-function-inline.ipynb
1. Why is this change required?  **There is a typographical error in the instruction document.**
2. What problem does it solve? **Avoid confusion for beginners of SK Python version.**
=> Documentation: the corrected text should be Python instead of C#.

python/pyproject.toml
=> New python SK release

dotnet/Directory.Packages.props
There is a security vulnerability in older versions of Newtonsoft.Json.
Upgrade Newtonsoft.Json to the latest version.
=> Upgrade Newtonsoft.Json to 13.0.3

samples/apps/copilot-chat-app/webapp/src/App.tsx, samples/apps/copilot-chat-app/webapp/src/components/chat/ChatRoom.tsx, samples/apps/copilot-chat-app/webapp/src/components/views/ChatView.tsx, samples/apps/copilot-chat-app/webapp/src/components/views/Login.tsx, samples/apps/copilot-chat-app/webapp/src/index.tsx
Fixes scrollbar issue on main view (would show a double scrollbar on zoom. now scroll only shows on chat history component and conversations as necessary)
=> Fix main view height overflow issue

.github/workflows/dotnet-integration-tests.yml
Integration tests have stopped running due to #596 
This updates the yml to properly include any projects of the form `*IntegrationTests.csproj`
There are failing tests due to changes recently that were not caught. Will fix those separately.
=> 🧪Re-enable Integration Tests

CONTRIBUTING.md
=> Fix documentation link CONTRIBUTING.md

samples/apps/copilot-chat-app/webapi/ServiceExtensions.cs
Hard to debug errors when there are leading or trailing spaces in configuration values.
Trim all configuration strings on startup.
=> Trim all configuration strings

samples/apps/copilot-chat-app/webapi/README.md
Corrected typo to create correct instructions for installation:  ../app/.. to ..//apps/..
=> Update Copilot Chat\webapi\ README.md

dotnet/src/Skills/Skills.Grpc/Protobuf/ProtoDocumentParser.cs, samples/dotnet/kernel-syntax-examples/Example31_GrpcSkills.cs, samples/dotnet/kernel-syntax-examples/Example32_GrpcSkills.cs, samples/dotnet/kernel-syntax-examples/Program.cs
Fix for the latest, partially successful, merge of gRPC feature branch with the main one.
=> Fix for the latest, partially successful, merge of gRPC feature branch with the main one.

python/pyproject.toml, python/semantic_kernel/connectors/ai/hugging_face/services/hf_text_completion.py, python/semantic_kernel/connectors/ai/hugging_face/services/hf_text_embedding.py, python/semantic_kernel/kernel.py, python/tests/integration/completions/e2e_text_completion.py, python/tests/integration/completions/test_azure_oai_chat_service.py, python/tests/integration/completions/test_azure_oai_text_service.py, python/tests/integration/completions/test_oai_chat_service.py, python/tests/integration/completions/test_oai_text_service.py, python/tests/integration/embeddings/test_oai_embedding_service.py
* Fix lint errors
* Bump version number
* Add retry loop to integration tests
* Enable all integration tests: some tests will fail if OpenAI/Azure are throttling.
=> Python: fixes and release

samples/apps/copilot-chat-app/webapi/Config/AzureCognitiveSearchOptions.cs, samples/apps/copilot-chat-app/webapi/Config/MemoriesStoreOptions.cs, samples/apps/copilot-chat-app/webapi/CopilotChatApi.csproj, samples/apps/copilot-chat-app/webapi/SemanticKernelExtensions.cs, samples/apps/copilot-chat-app/webapi/appsettings.json
Previous change introduced bug with configuration.
Changes ISemanticTextMemory from Singleton to Scoped.
=> CopilotChat: Add Azure Cog Search for Semantic Memory w/ IOptions fix

dotnet/Directory.Packages.props, dotnet/SK-dotnet.sln.DotSettings, dotnet/src/Skills/Skills.Grpc/Extensions/KernelGrpcExtensions.cs, dotnet/src/Skills/Skills.UnitTests/Grpc/Extensions/GrpcOperationExtensionsTests.cs, dotnet/src/Skills/Skills.UnitTests/Grpc/Protobuf/ProtoDocumentParserV30Tests.cs, samples/dotnet/kernel-syntax-examples/Example35_GrpcSkills.cs
* Upgrade Newtonsoft to v13 to address security issue.
* Some code style fixes
Note: this was already fixed once with https://github.com/microsoft/semantic-kernel/pull/623 and somehow it got reverted in https://github.com/microsoft/semantic-kernel/pull/814
=> Newtonsoft.Json CWE-755 - Improper Handling of Exceptional Conditions

samples/apps/copilot-chat-app/README.md, samples/apps/copilot-chat-app/webapi/Config/DocumentMemoryOptions.cs, samples/apps/copilot-chat-app/webapi/Controllers/DocumentImportController.cs, samples/apps/copilot-chat-app/webapi/CopilotChatApi.csproj, samples/apps/copilot-chat-app/webapi/SemanticKernelExtensions.cs, samples/apps/copilot-chat-app/webapi/appsettings.json
Document deduplication is causing hallucinations and fixing memory issues when not using ACS.
- Removed document duplication
- Enhanced semantic text memory creation to make sure volatile memory stores are set as singletons.
- Added troubleshooting section for when the authority/tenant is mismatched.
=> CopilotChat: Fix document upload and memory issues

samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk-existing-ai.bicep, samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk.bicep
To be fancy and for accessibility, we want to be able to speak to the Copilot Chat
Added Speech service to deployment template.
=> Add speech service for speech recognition to deployment templates

dotnet/src/Skills/Skills.MsGraph/OrganizationHierarchySkill.cs, dotnet/src/Skills/Skills.UnitTests/MsGraph/OrganizationHierarchySkillTests.cs
Expose GetMyDirectReportsEmailAsync function from
OrganizationHierarchySkill.
Add unit test for same.
=> Wire up direct reports email

dotnet/Directory.Packages.props, dotnet/src/SemanticKernel.UnitTests/Orchestration/ContextVariablesConverterTests.cs
This reverts commit 7573efbddfd668233cce5b9d163a862199f143d8.
=> Revert "Update System.Text.Json and enable transitive pinning (#938)"

dotnet/src/SemanticKernel/KernelBuilder.cs, dotnet/src/SemanticKernel/Services/AIServiceProvider.cs, dotnet/src/SemanticKernel/Services/NamedServiceProvider.cs, samples/apps/copilot-chat-app/webapi/SemanticKernelExtensions.cs, samples/dotnet/kernel-syntax-examples/Example35_DIContainer.cs, samples/dotnet/kernel-syntax-examples/KernelSyntaxExamples.csproj, samples/dotnet/kernel-syntax-examples/Program.cs
This PR adds a few examples showing the way SK SDK can be used by applications that use DI/IoC containers for bootstrapping.
=> A few examples of using SK SDK in DI/IoC container

dotnet/src/SemanticKernel/CoreSkills/TextMemorySkill.cs, samples/apps/copilot-chat-app/webapi/Skills/ChatSkill.cs, samples/dotnet/kernel-syntax-examples/Example15_MemorySkill.cs
WPF compatibility, see https://github.com/microsoft/semantic-kernel/issues/960
Refactor blocking code
=> Fix deadlock in TextMemory skill

dotnet/src/SemanticKernel/CoreSkills/FileIOSkill.cs
The unit test FileIOSkillTests.ItCannotWriteAsync is consistently failing across all docker-based dotnet builds. It's likely because the docker environment is running as root, and has super-user permissions to write over files marked as read-only.
Add explicit check for read-only property on a file in the FileIOSkill itself. If it does have the read-only flag, throw `UnauthorizedAccessException` as the OS would.
=> Update FileIOSkill to block writing to readonly files

dotnet/src/Connectors/Connectors.AI.OpenAI/Connectors.AI.OpenAI.csproj, dotnet/src/SemanticKernel.Abstractions/SemanticKernel.Abstractions.csproj, dotnet/src/SemanticKernel.MetaPackage/SemanticKernel.MetaPackage.csproj, dotnet/src/SemanticKernel/SemanticKernel.csproj
=> adding strongname signing properties

samples/apps/copilot-chat-app/webapp/src/components/open-api-plugins/PluginConnector.tsx, samples/apps/copilot-chat-app/webapp/src/redux/features/plugins/PluginsState.ts, samples/apps/copilot-chat-app/webapp/src/redux/features/plugins/pluginsSlice.ts
Update the jira plugin UI for copilot chat to be more accurate and descriptive
=> Update jira plugin UI for copilot chat

dotnet/src/SemanticKernel/Memory/Collections/Score.cs, samples/apps/copilot-chat-app/webapp/src/components/chat/ChatHistoryItem.tsx, samples/apps/copilot-chat-app/webapp/src/components/chat/ChatInput.tsx, samples/apps/copilot-chat-app/webapp/src/components/chat/ChatRoom.tsx, samples/apps/copilot-chat-app/webapp/src/components/chat/chat-list/ChatList.tsx, samples/apps/copilot-chat-app/webapp/src/components/utils/TextUtils.ts, samples/apps/copilot-chat-app/webapp/src/index.css
This PR updates styling around scroll bars and parses chat text to detect and render URLs as clickable links.
=> Rendering clickable URLs and fixing scrollbar styling

README.md
Changes to update main readme.md notice.
=> Update to Readme.MD Note

samples/apps/copilot-chat-app/webapp/src/redux/features/message-relay/signalRMiddleware.ts
Dispatch returns immediately even when the action is captured by the SignalR middleware.
Dispatch the action to next() in the pipeline before the async logic in the middleware to make sure the stores are updated.
=> Await signalR actions

samples/dotnet/KernelHttpServer/KernelHttpServer.csproj
=> Azure Functions RollForward

samples/apps/copilot-chat-app/webapi/Options/QdrantOptions.cs, samples/apps/copilot-chat-app/webapi/SemanticKernelExtensions.cs, samples/apps/copilot-chat-app/webapi/appsettings.json
CopilotChat needs to support a secure connection to Qdrant.
Added option for "api-key" header when connecting to Qdrant to support Qdrant Cloud instances.
=> CopilotChat: Qdrant Cloud support

dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAICompletionTests.cs
The test for using OpenAI chat completion for text completion is skipped while we investigate an issue with GitHub actions. This is a temporary measure to avoid failing the CI pipeline. The test will be re-enabled once the issue is resolved.
=> Skip OpenAI chat completion test

samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk-existing-azureopenai.bicep, samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk-existing-azureopenai.json, samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk-existing-openai.bicep, samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk-existing-openai.json, samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk-new.bicep, samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk-new.json
Disabling Qdrant while we secure the endpoint.
- Removed Qdrant deployment option from "Deploy to Azure" resources
=> CopilotChat: Remove qdrant from deploy to azure temporarily

samples/apps/copilot-chat-app/webapi/CopilotChat/Controllers/ChatController.cs
Fixes broken path to openapi skills in CopilotChat.
=> CopilotChat: Fixes broken path to openapi skills

dotnet/src/Connectors/Connectors.AI.OpenAI/OpenAIKernelBuilderExtensions.cs, samples/dotnet/kernel-syntax-examples/Example20_HuggingFace.cs
Fixing a few small potential issues related to AI services registration.
=> Fix for AI services registration

samples/apps/copilot-chat-app/webapi/appsettings.json
=> Typo fix in appsettings.json

samples/apps/copilot-chat-app/webapi/DeploymentTemplates/README.md, samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk-existing-azureopenai.json, samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk-existing-openai.json, samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk-new.json
When the last changes were made to main.bicep, the corresponding JSON ARM templates were not updated.
The "Deploy to Azure" buttons use the ARM templates and were thus still subject to the race condition in deployment fixed on Tuesday.
Automatically generate ARM templates from latest bicep code.
=> Update ARM templates to latest bicep

samples/dotnet/kernel-syntax-examples/Example12_SequentialPlanner.cs, samples/dotnet/kernel-syntax-examples/Example15_MemorySkill.cs, samples/dotnet/kernel-syntax-examples/Example23_OpenApiSkill_Github.cs, samples/dotnet/kernel-syntax-examples/Example40_DIContainer.cs, samples/dotnet/kernel-syntax-examples/RepoUtils/PlanExtensions.cs
Automatically applied formatting from dotnet format
=> KernelSyntaxExamples: dotnet format fixes

python/pyproject.toml
New version number for next SK Python release
=> Bump python release number - 0.2.9.dev

samples/dotnet/FileCompression/FileCompression.csproj, samples/dotnet/FileCompression/FileCompressionSkill.cs, samples/dotnet/KernelHttpServer/KernelHttpServer.csproj, samples/dotnet/KernelHttpServer/SemanticKernelFactory.cs, samples/dotnet/github-skills/GitHubSkill.cs, samples/dotnet/github-skills/GitHubSkills.csproj, samples/dotnet/graph-api-skills/MsGraphSkillsExample.csproj, samples/dotnet/graph-api-skills/Program.cs, samples/dotnet/kernel-extension-load-prompts-from-cloud/LoadPromptsFromCloud.csproj, samples/dotnet/openapi-skills/OpenApiSkillsExample.csproj, samples/dotnet/openapi-skills/Program.cs
Updating samples/dotnet projects to the latest SK NuGets.
All builds are clean -- no warnings or obsolete messages.
=> Update the samples/dotnet projects to SK NuGet v0.15

FEATURE_MATRIX.md, python/pyproject.toml
=> Bump SK python version from 0.2.9 to 0.3.0, update feature matrix

samples/apps/copilot-chat-app/deploy/main.json
main.bicep changes from https://github.com/microsoft/semantic-kernel/pull/1533 did not get built into main.json
- rebuild main.json from current main.bicep
=> CopilotChat: Update main.json to reflect changes in main.bicep

samples/apps/copilot-chat-app/deploy/deploy-webapp.ps1, samples/apps/copilot-chat-app/deploy/deploy-webapp.sh, samples/apps/copilot-chat-app/webapp/template.swa-cli.config.json
Fix issue with API key not propagating in SWA deploy
=> CopilotChat: Fix issue with API key not propagating in SWA deploy

samples/apps/auth-api-webapp-react/src/components/ServiceConfig.tsx, samples/apps/book-creator-webapp-react/src/components/ServiceConfig.tsx, samples/apps/chat-summary-webapp-react/src/components/ServiceConfig.tsx
Updated sample field labels to more accurately reflect Azure Open AI requirements. In response to this discussion: https://github.com/microsoft/semantic-kernel/discussions/1548
=> Updating sample app labels for azure open ai

COMMUNITY.md, README.md
=> added COMMUNITY.md

dotnet/samples/KernelSyntaxExamples/Example21_ChatGPTPlugins.cs, dotnet/src/Skills/Skills.OpenAPI/Extensions/KernelChatGptPluginExtensions.cs, dotnet/src/Skills/Skills.OpenAPI/Extensions/KernelOpenApiExtensions.cs, dotnet/src/Skills/Skills.OpenAPI/Extensions/OpenApiSkillExecutionParameters.cs, dotnet/src/Skills/Skills.OpenAPI/Model/RestApiOperationResponse.cs, dotnet/src/Skills/Skills.OpenAPI/RestApiOperationRunner.cs
This PR ensures that the User-Agent is consistently passed for all OpenAPI-related functionality, preventing rejections of HTTP requests by Klarna ChatGPT plugin. It also introduces a data contract for the RestApiOperation response, enabling reliable deserialization in SK consumer code.
=> OpenAPI fixes and improvements

FEATURE_MATRIX.md
* Add Chroma for Python
* Move up top Memory connectors with wider support
* Update Azure Search note
=> Update Memory Connectors feature matrix

dotnet/src/SemanticKernel/SkillDefinition/SKFunction.cs
The culture will never be null here so these fallbacks aren't ever used.
=> Remove some unnecessary null checks

java/semantickernel-api/src/main/java/com/microsoft/semantickernel/memory/DataEntryBase.java, java/semantickernel-core/src/main/java/com/microsoft/semantickernel/memory/VolatileMemoryStore.java, java/semantickernel-core/src/test/java/com/microsoft/semantickernel/connectors/memory/azurecognitivesearch/AzureCognitiveSearchMemoryTests.java, java/semantickernel-core/src/test/java/com/microsoft/semantickernel/memory/MemoryExceptionTests.java, java/semantickernel-core/src/test/java/com/microsoft/semantickernel/memory/MemoryRecordTests.java, java/semantickernel-core/src/test/java/com/microsoft/semantickernel/memory/VolatileMemoryStoreTests.java
No code changes, just apply formatting rules
=> Java: Apply formatting rules

java/api-test/api-usage-example/pom.xml, java/api-test/integration-tests/pom.xml, java/api-test/pom.xml, java/pom.xml, java/samples/pom.xml, java/samples/sample-code/pom.xml, java/samples/semantickernel-guice/pom.xml, java/semantickernel-api/pom.xml, java/semantickernel-bom/pom.xml, java/semantickernel-connectors-parent/pom.xml, java/semantickernel-connectors-parent/semantickernel-connectors/pom.xml, java/semantickernel-core-skills/pom.xml, java/semantickernel-core/pom.xml, java/semantickernel-extensions-parent/actionplanner-extension/pom.xml, java/semantickernel-extensions-parent/pom.xml, java/semantickernel-extensions-parent/sequentialplanner-extensions/pom.xml
Update Pom with settings needed for releasing
=> Java: Configure pom for releases

java/semantickernel-core/src/test/java/com/microsoft/semantickernel/syntaxexamples/Example12SequentialPlannerTest.java
Rename Example12SequentialPlanner to a test and add assertion
=> Java: Fix example12 test

dotnet/Directory.Packages.props
Upgrade duckdb to use strong named version
=> .Net: upgrade duckdb to strong named version

java/api-test/api-usage-example/pom.xml, java/api-test/integration-tests/pom.xml, java/api-test/pom.xml, java/pom.xml, java/samples/pom.xml, java/samples/sample-code/pom.xml, java/samples/semantickernel-guice/pom.xml, java/semantickernel-api/pom.xml, java/semantickernel-bom/pom.xml, java/semantickernel-connectors-parent/pom.xml, java/semantickernel-connectors-parent/semantickernel-connectors/pom.xml, java/semantickernel-core-skills/pom.xml, java/semantickernel-core/pom.xml, java/semantickernel-extensions-parent/pom.xml, java/semantickernel-extensions-parent/semantickernel-actionplanner-extension/pom.xml, java/semantickernel-extensions-parent/semantickernel-sequentialplanner-extension/pom.xml
=> Java: [maven-release-plugin] prepare release java-0.2.4-alpha

java/api-test/api-usage-example/pom.xml, java/api-test/integration-tests/pom.xml, java/api-test/pom.xml, java/pom.xml, java/samples/pom.xml, java/samples/sample-code/pom.xml, java/samples/semantickernel-guice/pom.xml, java/semantickernel-api/pom.xml, java/semantickernel-bom/pom.xml, java/semantickernel-connectors-parent/pom.xml, java/semantickernel-connectors-parent/semantickernel-connectors/pom.xml, java/semantickernel-core-skills/pom.xml, java/semantickernel-core/pom.xml, java/semantickernel-extensions-parent/pom.xml, java/semantickernel-extensions-parent/semantickernel-actionplanner-extension/pom.xml, java/semantickernel-extensions-parent/semantickernel-sequentialplanner-extension/pom.xml
=> Java: [maven-release-plugin] prepare for next development iteration

java/pom.xml, java/samples/pom.xml, java/samples/sample-code/pom.xml, java/semantickernel-api/pom.xml, java/semantickernel-connectors-parent/pom.xml, java/semantickernel-connectors-parent/semantickernel-connectors/pom.xml, java/semantickernel-core-skills/pom.xml, java/semantickernel-core/pom.xml, java/semantickernel-extensions-parent/pom.xml, java/semantickernel-extensions-parent/semantickernel-actionplanner-extension/pom.xml, java/semantickernel-extensions-parent/semantickernel-sequentialplanner-extension/pom.xml
Update pom.xml for Java JDK release.
=> Java: Add name and desc to pom.xml

java/api-test/api-usage-example/pom.xml, java/api-test/integration-tests/pom.xml, java/api-test/pom.xml, java/pom.xml, java/samples/pom.xml, java/samples/sample-code/pom.xml, java/samples/semantickernel-guice/pom.xml, java/semantickernel-api/pom.xml, java/semantickernel-bom/pom.xml, java/semantickernel-connectors-parent/pom.xml, java/semantickernel-connectors-parent/semantickernel-connectors/pom.xml, java/semantickernel-core-skills/pom.xml, java/semantickernel-core/pom.xml, java/semantickernel-extensions-parent/pom.xml, java/semantickernel-extensions-parent/semantickernel-actionplanner-extension/pom.xml, java/semantickernel-extensions-parent/semantickernel-sequentialplanner-extension/pom.xml
Release commit for CD to build.
=> Java: sk release branch

java/api-test/api-usage-example/pom.xml, java/api-test/integration-tests/pom.xml, java/api-test/pom.xml, java/pom.xml, java/samples/pom.xml, java/samples/sample-code/pom.xml, java/samples/semantickernel-guice/pom.xml, java/semantickernel-api/pom.xml, java/semantickernel-bom/pom.xml, java/semantickernel-connectors-parent/pom.xml, java/semantickernel-connectors-parent/semantickernel-connectors/pom.xml, java/semantickernel-core-skills/pom.xml, java/semantickernel-core/pom.xml, java/semantickernel-extensions-parent/pom.xml, java/semantickernel-extensions-parent/semantickernel-actionplanner-extension/pom.xml, java/semantickernel-extensions-parent/semantickernel-sequentialplanner-extension/pom.xml
Prepares the codebase for the next development cycle.
=> Java: Prepare for next dev cycle

.github/workflows/python-unit-tests.yml, python/poetry.lock, python/pyproject.toml, python/tests/integration/connectors/memory/test_azure_search.py
* Move Azure Search dependencies to own group
* Improve Azure Search integration tests: try to delete collections when tests fail
* Wait 1 sec after upsert to reduce random failures
=> Python: Azure Search installation and tests improvements

java/samples/sample-code/src/main/java/com/microsoft/semantickernel/Example_BlogAnnouncement.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/Example_PlanWithNativeFunctions.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/AbstractSkFunction.java, java/semantickernel-extensions-parent/semantickernel-actionplanner-extension/src/main/java/com/microsoft/semantickernel/planner/actionplanner/Plan.java
- Fix the planner overwriting the result even when it is being bound to a variable.
- Fix incorrect handling of default values for planner functions 
- Add example for blog post
=> Java: Fix a number of planner issues, add blog example

java/api-test/api-usage-example/pom.xml, java/api-test/integration-tests/pom.xml, java/api-test/pom.xml, java/pom.xml, java/samples/pom.xml, java/samples/sample-code/pom.xml, java/samples/semantickernel-guice/pom.xml, java/semantickernel-api/pom.xml, java/semantickernel-bom/pom.xml, java/semantickernel-connectors-parent/pom.xml, java/semantickernel-connectors-parent/semantickernel-connectors/pom.xml, java/semantickernel-core-skills/pom.xml, java/semantickernel-core/pom.xml, java/semantickernel-extensions-parent/pom.xml, java/semantickernel-extensions-parent/semantickernel-actionplanner-extension/pom.xml, java/semantickernel-extensions-parent/semantickernel-sequentialplanner-extension/pom.xml, java/semantickernel-gpt3-tokenizer/pom.xml
=> Java: Prepare development iteration

python/semantic_kernel/connectors/memory/azure_cognitive_search/azure_cognitive_search_memory_store.py, python/semantic_kernel/memory/memory_store_base.py, python/tests/integration/connectors/memory/test_azure_cognitive_search.py
* close search clients
* fix get_collections_async()
* remove code duplication
* removed unused get_collection_async() method
* add more integration tests
=> Python: Azure Cognitive Search bug fixes

java/semantickernel-core/src/main/java/com/microsoft/semantickernel/orchestration/DefaultCompletionSKFunction.java
If the user provides an incorrect model provide a slightly more useful error message
=> Java: Add a more detailed error message when the user uses the wrong completion model

java/README.md
Use -b to specify branch so command always works
Note, it's just a readme update. Checked these boxes but they're mostly n/a
=> Java: Update README.md - fix to git clone command

java/extensions/semantickernel-planners/src/main/java/com/microsoft/semantickernel/planner/actionplanner/Plan.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example03_Variables.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/AbstractSKContext.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/ContextVariables.java, java/semantickernel-core/src/main/java/com/microsoft/semantickernel/DefaultKernel.java, java/semantickernel-core/src/main/java/com/microsoft/semantickernel/orchestration/DefaultContextVariables.java, java/semantickernel-core/src/test/java/com/microsoft/semantickernel/syntaxexamples/Example03VariablesTest.java
- Allows users to set values in the ContextVariable builder
- Allows constructing a mutable ContextVariable
=> Java: Add more setting options to context variable builder

java/.mvn/wrapper/maven-wrapper.properties, java/connectors/semantickernel-connectors-ai-openai/pom.xml, java/connectors/semantickernel-connectors-memory-sqlite/pom.xml, java/pom.xml, java/samples/pom.xml, java/samples/sample-code/pom.xml, java/samples/semantickernel-guice/pom.xml, java/semantickernel-bom/pom.xml, java/semantickernel-core/pom.xml
Keep our security and stability baseline for dependencies as high as possible.
Maven POM changes mainly, removing a bunch of warnings and updating dependencies
=> Java: Update dependencies

java/connectors/semantickernel-connectors-ai-openai/src/main/java/com/microsoft/semantickernel/connectors/ai/openai/chatcompletion/OpenAIChatCompletion.java, java/plugins/semantickernel-plugin-core/src/main/java/com/microsoft/semantickernel/coreskills/ConversationSummarySkill.java, java/pom.xml, java/semantickernel-bom/pom.xml
=> Java: Bump to 1.0.0-beta.3 azure-ai-openai

.github/dependabot.yml, dotnet/Directory.Packages.props
Temporary locked `Moq` package version based on recent privacy issues:
https://github.com/moq/moq/issues/1372
=> .Net: Locked Moq package version (4.18.4)

java/pom.xml
=> Java: Add documentation in case that our deployment version changes

samples/dotnet/KernelHttpServer/KernelHttpServer.csproj, samples/dotnet/KernelHttpServer/SemanticKernelEndpoint.cs, samples/dotnet/graph-api-skills/MsGraphSkillsExample.csproj, samples/dotnet/graph-api-skills/Program.cs, samples/dotnet/openapi-skills/OpenApiSkillsExample.csproj, samples/dotnet/openapi-skills/Program.cs
Weekly OSS update.
Absorbed breaking changes around error handling.
=> Updated version of Microsoft.SemanticKernel.nuget in sample projects.

.github/workflows/python-integration-tests.yml
Fix python integration tests to start running correct test file.
=> Python: Fix Typo - Update python-integration-tests.yml

java/api-test/api-usage-example/pom.xml, java/api-test/integration-tests/pom.xml, java/api-test/pom.xml, java/connectors/semantickernel-connectors-ai-openai/pom.xml, java/connectors/semantickernel-connectors-memory-azurecognitivesearch/pom.xml, java/connectors/semantickernel-connectors-memory-sqlite/pom.xml, java/extensions/semantickernel-gpt3-tokenizer/pom.xml, java/extensions/semantickernel-planners/pom.xml, java/plugins/semantickernel-plugin-core/pom.xml, java/pom.xml, java/samples/pom.xml, java/samples/sample-code/pom.xml, java/samples/semantickernel-samples-guice/pom.xml, java/semantickernel-api/pom.xml, java/semantickernel-bom/pom.xml, java/semantickernel-core/pom.xml
=> Java: prepare release java-0.2.8-alpha

java/api-test/api-usage-example/pom.xml, java/api-test/integration-tests/pom.xml, java/api-test/pom.xml, java/connectors/semantickernel-connectors-ai-openai/pom.xml, java/connectors/semantickernel-connectors-memory-azurecognitivesearch/pom.xml, java/connectors/semantickernel-connectors-memory-sqlite/pom.xml, java/extensions/semantickernel-gpt3-tokenizer/pom.xml, java/extensions/semantickernel-planners/pom.xml, java/plugins/semantickernel-plugin-core/pom.xml, java/pom.xml, java/samples/pom.xml, java/samples/sample-code/pom.xml, java/samples/semantickernel-samples-guice/pom.xml, java/semantickernel-api/pom.xml, java/semantickernel-bom/pom.xml, java/semantickernel-core/pom.xml
=> Java: Prepare java dev iteration

python/pyproject.toml
Prep project file in preparation for the next release cycle
=> Python: Update pyproject.toml

node-api-dotnet/samples/NodeKernelSyntaxExamples/.gitignore, node-api-dotnet/samples/NodeKernelSyntaxExamples/Example01_SummarizeText.js, node-api-dotnet/samples/NodeKernelSyntaxExamples/NodeKernelSyntaxExamples.csproj, node-api-dotnet/samples/NodeKernelSyntaxExamples/README.md, node-api-dotnet/samples/NodeKernelSyntaxExamples/package.json
1. Why is this change required? Demonstrates how to call Semantic Kernel from Node
First node-api-dotnet example showing how to invoke a semantic function
=> First node-api-dotnet example showing how to invoke a semantic function

dotnet/src/Connectors/Connectors.Memory.AzureCognitiveSearch/AzureCognitiveSearchMemoryStore.cs
Fixes #2728
The change makes sure that RemoveBatchAsync method works correctly by providing a list of strings to AzureCognitiveSearch client instead of list of list of strings.
=> .Net: Fix the data format issue with RemoveBatchAsync method

python/semantic_kernel/connectors/memory/azure_cognitive_search/utils.py
Customer reported credentials passed into connector are ignored:
https://github.com/microsoft/semantic-kernel/issues/2701
Local variable declaration taking precedence over function parameters.
=> Python - Azure Cognitive Search Connector - Remove redeclaration

python/pyproject.toml
=> Python: Update pyproject.toml with version=0.3.12

dotnet/src/Extensions/Planning.StepwisePlanner/StepwisePlanner.cs
Update the StepwisePlanner class to pass the LoggerFactory to the PromptTemplateEngine constructor. This change improves logging and debugging capabilities within the PromptTemplateEngine.
Fixes #2774
=> .Net: [fix] Update StepwisePlanner to use LoggerFactory in PromptTemplateEngine

dotnet/src/Extensions/Planning.StepwisePlanner/ChatHistoryExtensions.cs, dotnet/src/Extensions/Planning.StepwisePlanner/StepwisePlanner.cs, dotnet/src/Extensions/Planning.StepwisePlanner/StepwisePlannerConfig.cs, dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatHistory.cs
Refactor chat history token calculation and clipping. Leaving the existing `ChatHistory` as-is to ensure a complete transcript is available. Extended class `ChatHistory` to support insert.
Fixes #2773
=> .Net: [fix] StepwisePlanner ChatHistory token calculation refactoring

dotnet/samples/KernelSyntaxExamples/Example57_FlowPlanner.cs, dotnet/samples/KernelSyntaxExamples/Program.cs, dotnet/src/Extensions/Planning.FlowPlanner/Abstractions/ChatSkill.cs, dotnet/src/Extensions/Planning.FlowPlanner/FlowExecutor/Constants.cs, dotnet/src/Extensions/Planning.FlowPlanner/FlowExecutor/ExecutionState.cs, dotnet/src/Extensions/Planning.FlowPlanner/FlowExecutor/FlowExecutor.cs, dotnet/src/Extensions/Planning.FlowPlanner/FlowExecutor/FlowStatusProvider.cs, dotnet/src/Extensions/Planning.FlowPlanner/FlowExecutor/ReActEngine.cs, dotnet/src/Extensions/Planning.FlowPlanner/FlowPlannerConfig.cs, dotnet/src/Extensions/Planning.FlowPlanner/FlowSerializer.cs, dotnet/src/Extensions/Planning.FlowPlanner/Model/CompletionType.cs, dotnet/src/Extensions/Planning.FlowPlanner/Model/Flow.cs, dotnet/src/Extensions/Planning.FlowPlanner/Model/FlowStep.cs, dotnet/src/Extensions/Planning.FlowPlanner/Skills/CheckStartStep/config.json, dotnet/src/Extensions/Planning.FlowPlanner/Skills/CheckStartStep/skprompt.txt, dotnet/src/Extensions/Planning.FlowPlanner/Skills/ReActEngine/gpt3/skprompt.txt, dotnet/src/IntegrationTests/Planning/FlowPlanner/FlowPlannerTests.cs
Follow up PR into feature branch for https://github.com/microsoft/semantic-kernel/issues/2164.
1. Merge from main
2. Address code style issues per latest rules
3. Support more step completion types
=> [Feature branch only] Merge from main and support more completion types

python/pyproject.toml
Update pip version in preparation for next package release
=> Python: Update pyproject.toml to version 0.3.13.dev

java/semantickernel-core/src/main/java/com/microsoft/semantickernel/memory/DefaultSemanticTextMemory.java
=> Java: Fix memory not updating if the record already exists

docs/decisions/0001-madr-architecture-decisions.md, docs/decisions/README.md
Fix broken link the ADR README
=> Fix broken link and update the description

dotnet/samples/NCalcPlugins/LanguageCalculatorPlugin.cs
Missing function reference
Added function reference + example succeeded
=> .Net Calculator fix, missing function

java/connectors/semantickernel-connectors-memory-postgresql/pom.xml, java/semantickernel-bom/pom.xml
=> Java: Resolve postgresql version

java/api-test/api-usage-example/pom.xml, java/api-test/integration-tests/pom.xml, java/api-test/pom.xml, java/connectors/semantickernel-connectors-ai-openai/pom.xml, java/connectors/semantickernel-connectors-memory-azurecognitivesearch/pom.xml, java/connectors/semantickernel-connectors-memory-jdbc/pom.xml, java/connectors/semantickernel-connectors-memory-postgresql/pom.xml, java/connectors/semantickernel-connectors-memory-sqlite/pom.xml, java/extensions/semantickernel-gpt3-tokenizer/pom.xml, java/extensions/semantickernel-planners/pom.xml, java/plugins/semantickernel-plugin-core/pom.xml, java/pom.xml, java/samples/pom.xml, java/samples/sample-code/pom.xml, java/samples/semantickernel-samples-guice/pom.xml, java/semantickernel-api/pom.xml, java/semantickernel-bom/pom.xml, java/semantickernel-core/pom.xml
=> Java: [maven-release-plugin] prepare release java-0.2.9-alpha

java/api-test/api-usage-example/pom.xml, java/api-test/integration-tests/pom.xml, java/api-test/pom.xml, java/connectors/semantickernel-connectors-ai-openai/pom.xml, java/connectors/semantickernel-connectors-memory-azurecognitivesearch/pom.xml, java/connectors/semantickernel-connectors-memory-jdbc/pom.xml, java/connectors/semantickernel-connectors-memory-postgresql/pom.xml, java/connectors/semantickernel-connectors-memory-sqlite/pom.xml, java/extensions/semantickernel-gpt3-tokenizer/pom.xml, java/extensions/semantickernel-planners/pom.xml, java/plugins/semantickernel-plugin-core/pom.xml, java/pom.xml, java/samples/pom.xml, java/samples/sample-code/pom.xml, java/samples/semantickernel-samples-guice/pom.xml, java/semantickernel-api/pom.xml, java/semantickernel-bom/pom.xml, java/semantickernel-core/pom.xml
=> Java sk dev

java/connectors/semantickernel-connectors-ai-openai/src/main/java/com/microsoft/semantickernel/connectors/ai/openai/chatcompletion/OpenAIChatCompletion.java, java/connectors/semantickernel-connectors-ai-openai/src/main/java/com/microsoft/semantickernel/connectors/ai/openai/textcompletion/OpenAITextCompletion.java, java/extensions/semantickernel-planners/src/main/java/com/microsoft/semantickernel/planner/stepwiseplanner/DefaultStepwisePlanner.java, java/pom.xml, java/semantickernel-core/src/main/java/com/microsoft/semantickernel/orchestration/NativeSKFunction.java
Allow setting streaming type
Improve exceptions on native function invocation
=> Java: Fix exception on stop sequence when using text completion

dotnet/src/SemanticKernel.Core/Planning/PlannerConfigBase.cs
To keep code clean
Remove unnecessary init
=> .Net: Update PlannerConfigBase.cs

dotnet/src/SemanticKernel.Core/SemanticFunctions/PromptTemplate.cs
Keep code clean
let `_params` to be `readonly` since nowhere updates it
=> .Net: Update PromptTemplate.cs

dotnet/src/Planners/Planners.Core/Action/ActionPlanner.cs, dotnet/src/Planners/Planners.Core/Action/ActionPlannerConfig.cs, dotnet/src/Planners/Planners.Core/Sequential/SequentialPlanner.cs, dotnet/src/Planners/Planners.Core/Sequential/SequentialPlannerConfig.cs, dotnet/src/Planners/Planners.Core/Stepwise/StepwisePlanner.cs, dotnet/src/Planners/Planners.Core/Stepwise/StepwisePlannerConfig.cs, dotnet/src/SemanticKernel.Core/Planning/PlannerConfigBase.cs
This change is part of the effort to make the core planners more consistent with each other. This makes working with the planners more predictable.
Fixes #2973
This pull request updates the max tokens configuration in the planners to use the value from the configuration object instead of a hard-coded value. Specifically, the ActionPlanner, SequentialPlanner, and StepwisePlanner classes have been updated to use the MaxTokens property from their respective configuration objects. Additionally, default values for MaxTokens have been added to the ActionPlannerConfig, SequentialPlannerConfig, and StepwisePlannerConfig classes.
- ActionPlanner.cs: Updated ExtensionData dictionary to use MaxTokens value from configuration object
- ActionPlannerConfig.cs: Added default value for MaxTokens property …
=> .Net: move maxtokens property to base config Update max tokens configuration in planners

dotnet/src/Functions/Functions.OpenAPI/Extensions/RestApiOperationExtensions.cs, dotnet/src/Functions/Functions.OpenAPI/RestApiOperationRunner.cs
do not need compare Boolean use **is** expression.
for example:
````
if (useParametersFromMetadata is true)
````
=> .Net: Simplify boolean comparison

dotnet/src/Connectors/Connectors.AI.OpenAI/AzureSdk/ChatModelResult.cs, dotnet/src/Connectors/Connectors.AI.OpenAI/AzureSdk/TextModelResult.cs, dotnet/src/Connectors/Connectors.Memory.Redis/RedisMemoryStore.cs
=> .Net: remove Duplicate word in a comment

dotnet/samples/KernelSyntaxExamples/Example57_FlowOrchestrator.cs, dotnet/src/Extensions/Experimental/Orchestration.Flow/Execution/Constants.cs, dotnet/src/Extensions/Experimental/Orchestration.Flow/Execution/FlowExecutor.cs, dotnet/src/Extensions/Experimental/Orchestration.Flow/Execution/ReActEngine.cs, dotnet/src/Extensions/Experimental/Orchestration.Flow/Extensions/ContextVariablesExtensions.cs, dotnet/src/Extensions/Experimental/Orchestration.Flow/Extensions/SKContextExtensions.cs, dotnet/src/Extensions/Experimental/Orchestration.Flow/FlowValidator.cs, dotnet/src/IntegrationTests/Orchestration/Flow/FlowOrchestratorTests.cs
Fix bugs which resulted transient failures of examples and integration tests
Adds control variables and extension methods to the Orchestration.Flow execution, improving its flexibility and functionality
Fix InvokeAction bug in ReAct engine
Added control variables to Orchestration.Flow execution
Added ExitLoopName and ContinueLoopName variables to Constants.cs
Added DefaultValue variable to Constants.cs
Added ControlVariables array to Constants.cs
Modified FlowExecutor.cs to handle ExitLoopName and ContinueLoopName variables
Added ContextVariablesExtensions.cs with IsPromptInput and IsContinueLoop extension methods
Updated SKContextExtensions.cs with changes to PromptInput and ContinueLoop methods
Updated FlowValidator.cs with new ValidatePassthroughVariables method
=> .Net: [Feature Branch][Orchestrator.Flow] bug fix and add control variables

dotnet/src/IntegrationTests/Planners/StepwisePlanner/StepwisePlannerTests.cs, dotnet/src/Planners/Planners.Core/Stepwise/StepwisePlanner.cs
Resolves: https://github.com/microsoft/semantic-kernel/issues/3085
This PR contains changes to handle complex result in StepwisePlanner action by adding type converter.
1. Added type converter in StepwisePlanner action result processing.
2. Enabled integration test for StepwisePlanner.
=> .Net: Fix for Stepwise Planner

dotnet/samples/KernelSyntaxExamples/Example14_SemanticMemory.cs, dotnet/samples/KernelSyntaxExamples/Example26_AADAuth.cs
This PR contains small changes to fix some Kernel syntax examples.
1. Fixed method signature in `Example14_SemanticMemory`.
2. Fixed authentication options in `Example26_AADAuth`.
=> .Net: Small fixes in examples

python/notebooks/01-basic-loading-the-kernel.ipynb
=> Python: fixed doc error in 01-basic-loading-the-kernel.ipynb

python/samples/kernel-syntax-examples/sequential_planner.py
To help learners understand `SequentialPlanner` more smooth.
Just modifying a string which may be involved from action_planner.py
=> Python: Fix wrong output sample of SequentialPlanner

java/samples/sample-code/README.md, java/samples/sample-code/pom.xml
Fix pom.xml file to reflect correct class path for example in sample-code README.
=> Java: Fix documentation to reflect correct enum value for OPEN_AI.

python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion.py, python/semantic_kernel/connectors/ai/open_ai/services/open_ai_text_completion.py, python/semantic_kernel/connectors/ai/open_ai/services/open_ai_text_embedding.py
=> Python: improve ai service usability for text/chat completion

dotnet/src/SemanticKernel.Abstractions/Functions/NullReadOnlyFunctionCollection.cs
=> .Net: Avoid list allocation in NullReadOnlyFunctionCollection

dotnet/README.md
This PR contains changes to update `dotnet/README.md` file to be aligned with recent SK version `1.0.0-beta2`.
=> .Net: Updated dotnet README to align with SK 1.0.0-beta2

java/connectors/semantickernel-connectors-ai-openai/src/main/java/com/microsoft/semantickernel/connectors/ai/openai/chatcompletion/OpenAIChatCompletion.java, java/connectors/semantickernel-connectors-ai-openai/src/main/java/com/microsoft/semantickernel/connectors/ai/openai/util/OpenAIClientProvider.java, java/pom.xml, java/samples/semantickernel-samples-guice/src/main/java/com/microsoft/semantickernel/guice/Config.java, java/semantickernel-bom/pom.xml
Update azure-core dependencies.
=> Java: Update azure-ai-openai and azure-core-http-netty version

java/README.md, java/connectors/semantickernel-connectors-memory-azurecognitivesearch/src/test/java/com/microsoft/semantickernel/connectors/memory/azurecognitivesearch/AzureCognitiveSearchMemoryTests.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/Example02_RunningPromptsFromFile.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/Example03_SemanticFunctionInline.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/KernelException.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/ContextVariables.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/WritableContextVariables.java, java/semantickernel-core/src/test/java/com/microsoft/semantickernel/orchestration/NativeSKFunctionTest.java
=> Java: Fix typos in Java

python/pyproject.toml
Update version for next pip package release
=> Python: Update pyproject.toml to 0.3.14.dev

.github/workflows/codeql-analysis.yml
Reverts microsoft/semantic-kernel#3257
=> Revert "Add Java to the CodeQL language matrix"

.github/workflows/codeql-analysis.yml
=> Java: Fix codeql build

.github/workflows/codeql-analysis.yml
=> Move to single quotes for codeql

.github/workflows/codeql-analysis.yml
=> Java: Use compile-jdk17 profile in Java codeql build

.github/workflows/codeql-analysis.yml
=> Setup java install for codeql

docs/decisions/0001-madr-architecture-decisions.md, docs/decisions/0002-java-folder-structure.md, docs/decisions/0003-support-multiple-native-function-args.md, docs/decisions/0004-error-handling.md, docs/decisions/0005-function-execution-handlers.md, docs/decisions/0006-open-api-dynamic-payload-and-namespaces.md, docs/decisions/0007-prompt-extract-template-engine.md, docs/decisions/0008-support-generic-llm-request-settings.md, docs/decisions/0009-support-multiple-named-args-in-template-function-calls.md, docs/decisions/0010-dotnet-project-structure.md, docs/decisions/0010-openai-function-calling.md, docs/decisions/0011-function-and-kernel-result-types.md, docs/decisions/0012-kernel-service-registration.md, docs/decisions/0013-memory-as-plugin.md, docs/decisions/0014-chat-completion-roles-in-prompt.md
Update status of all merged ADR's to accepted and add a contact
This will make it clearer to Python and Java squads which decisions are accepted and who to contact for more information
=> Update status of all merged ADR's to accepted and add a contact

java/connectors/semantickernel-connectors-memory-azurecognitivesearch/pom.xml, java/connectors/semantickernel-connectors-memory-azurecognitivesearch/src/main/java/com/microsoft/semantickernel/connectors/memory/azurecognitivesearch/AzureCognitiveSearchMemoryStore.java, java/connectors/semantickernel-connectors-memory-azurecognitivesearch/src/test/java/com/microsoft/semantickernel/connectors/memory/azurecognitivesearch/AzureCognitiveSearchMemoryTests.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/memory/MemoryStore.java
=> Java: allow customising the reading of memory records. Fixes #3060

java/semantickernel-api/src/main/java/com/microsoft/semantickernel/KernelException.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/SkillExecutor.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/extensions/KernelExtensions.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/PromptTemplateConfig.java, java/semantickernel-core/src/main/java/com/microsoft/semantickernel/DefaultKernel.java
=> Java: Fix logging config parsing errors. Fixes #3238

java/semantickernel-core/src/test/java/com/microsoft/semantickernel/DefaultKernelTest.java
=> Java: Fix broken DefaultKernelTest test

dotnet/nuget/nuget-package.props
Bump version to 1.0.0-beta4 for weekly release
=> .Net: Bump version to 1.0.0-beta4

java/PACKAGES.md, java/README.md
=> Java: add documentation for the various packages

.github/workflows/java-build.yml, .github/workflows/java-integration-tests.yml, java/PACKAGES.md, java/README.md
=> Java: Fix spell check jobs and enable Builds on java-development branch

java/PACKAGES.md
=> Java: Fix doc link

dotnet/nuget/nuget-package.props
Update version for release 1.0.0-beta5
=> .Net: Version 1.0.0-beta5

dotnet/nuget/nuget-package.props, dotnet/src/IntegrationTests/Connectors/Memory/MongoDB/MongoDBMemoryStoreTests.cs
=> .Net: Bump to version 1.0.0-beta6

java/api-test/api-usage-example/pom.xml, java/api-test/integration-tests/pom.xml, java/api-test/pom.xml, java/connectors/semantickernel-connectors-ai-openai/pom.xml, java/connectors/semantickernel-connectors-memory-azurecognitivesearch/pom.xml, java/connectors/semantickernel-connectors-memory-jdbc/pom.xml, java/connectors/semantickernel-connectors-memory-mysql/pom.xml, java/connectors/semantickernel-connectors-memory-postgresql/pom.xml, java/connectors/semantickernel-connectors-memory-sqlite/pom.xml, java/extensions/semantickernel-gpt3-tokenizer/pom.xml, java/extensions/semantickernel-planners/pom.xml, java/extensions/semantickernel-settings-loader/pom.xml, java/plugins/semantickernel-plugin-core/pom.xml, java/pom.xml, java/samples/pom.xml, java/samples/sample-code/pom.xml, java/samples/semantickernel-samples-guice/pom.xml, java/semantickernel-api/pom.xml, java/semantickernel-bom/pom.xml, java/semantickernel-core/pom.xml
=> Java: [maven-release-plugin] prepare release java-0.2.10-alpha

java/api-test/api-usage-example/pom.xml, java/api-test/integration-tests/pom.xml, java/api-test/pom.xml, java/connectors/semantickernel-connectors-ai-openai/pom.xml, java/connectors/semantickernel-connectors-memory-azurecognitivesearch/pom.xml, java/connectors/semantickernel-connectors-memory-jdbc/pom.xml, java/connectors/semantickernel-connectors-memory-mysql/pom.xml, java/connectors/semantickernel-connectors-memory-postgresql/pom.xml, java/connectors/semantickernel-connectors-memory-sqlite/pom.xml, java/extensions/semantickernel-gpt3-tokenizer/pom.xml, java/extensions/semantickernel-planners/pom.xml, java/extensions/semantickernel-settings-loader/pom.xml, java/plugins/semantickernel-plugin-core/pom.xml, java/pom.xml, java/samples/pom.xml, java/samples/sample-code/pom.xml, java/samples/semantickernel-samples-guice/pom.xml, java/semantickernel-api/pom.xml, java/semantickernel-bom/pom.xml, java/semantickernel-core/pom.xml
=> Java: prepare for next development iteration

java/api-test/api-usage-example/pom.xml, java/api-test/integration-tests/pom.xml, java/api-test/pom.xml, java/connectors/semantickernel-connectors-ai-openai/pom.xml, java/connectors/semantickernel-connectors-memory-azurecognitivesearch/pom.xml, java/connectors/semantickernel-connectors-memory-jdbc/pom.xml, java/connectors/semantickernel-connectors-memory-mysql/pom.xml, java/connectors/semantickernel-connectors-memory-postgresql/pom.xml, java/connectors/semantickernel-connectors-memory-sqlite/pom.xml, java/extensions/semantickernel-gpt3-tokenizer/pom.xml, java/extensions/semantickernel-planners/pom.xml, java/extensions/semantickernel-settings-loader/pom.xml, java/plugins/semantickernel-plugin-core/pom.xml, java/pom.xml, java/samples/pom.xml, java/samples/sample-code/pom.xml, java/samples/semantickernel-samples-guice/pom.xml, java/semantickernel-api/pom.xml, java/semantickernel-bom/pom.xml, java/semantickernel-core/pom.xml
=> Java: [maven-release-plugin] prepare release java-0.2.11-alpha

README.md, dotnet/README.md
A few small fixes to make it easier for those getting started with C#
* Fix api name in sample code that has changed
* Make it easier for users to install the right package
=> .Net: Small fixes for C# tutorial

dotnet/nuget/nuget-package.props
=> .Net release 1.0.0-beta7

dotnet/nuget/nuget-package.props
<Bump version number for release
=> .Net: Version 1.0.0-beta8

dotnet/src/SemanticKernel.UnitTests/TemplateEngine/Blocks/CodeBlockTests.cs, dotnet/src/SemanticKernel.UnitTests/TemplateEngine/Blocks/FunctionIdBlockTests.cs, dotnet/src/SemanticKernel.UnitTests/TemplateEngine/Blocks/NamedArgBlockTests.cs, dotnet/src/SemanticKernel.UnitTests/TemplateEngine/Blocks/TextBlockTests.cs, dotnet/src/SemanticKernel.UnitTests/TemplateEngine/Blocks/ValBlockTests.cs, dotnet/src/SemanticKernel.UnitTests/TemplateEngine/Blocks/VarBlockTests.cs, dotnet/src/SemanticKernel.UnitTests/TemplateEngine/CodeTokenizerTests.cs, dotnet/src/SemanticKernel.UnitTests/TemplateEngine/TemplateTokenizerTests.cs
=> .Net: Update kernel template engine unit test namespaces

dotnet/src/Connectors/Connectors.AI.OpenAI/OpenAIKernelBuilderExtensions.cs
=> .Net: Rename deploymentName to modelId

dotnet/samples/KernelSyntaxExamples/Example57_KernelHooks.cs, dotnet/samples/KernelSyntaxExamples/Example61_MultipleLLMs.cs, dotnet/samples/KernelSyntaxExamples/Example62_CustomAIServiceSelector.cs, dotnet/samples/KernelSyntaxExamples/Example64_MultiplePromptTemplates.cs, dotnet/src/Experimental/Assistants/Extensions/KernelFunctionExtensions.cs, dotnet/src/Extensions/TemplateEngine.Handlebars/HandlebarsPromptTemplate.cs, dotnet/src/Functions/Functions.OpenAPI/Extensions/RestApiOperationExtensions.cs, dotnet/src/Functions/Functions.UnitTests/Markdown/Functions/SKFunctionMarkdownTests.cs, dotnet/src/Functions/Functions.UnitTests/Yaml/Functions/SKFunctionYamlTests.cs, dotnet/src/IntegrationTests/Planners/HandlebarsPlanner/HandlebarsTemplateEngineExtensionsTests.cs, dotnet/src/IntegrationTests/Planners/PlanTests.cs, dotnet/src/IntegrationTests/Plugins/SamplePluginsTests.cs, dotnet/src/Planners/Planners.Core/Schema/SKFunctionMetadataExtensions.cs, dotnet/src/Planners/Planners.Core/Sequential/SequentialPlanParser.cs, dotnet/src/SemanticKernel.Abstractions/Events/FunctionInvokedEventArgs.cs, dotnet/src/SemanticKernel.Abstractions/Events/FunctionInvokingEventArgs.cs, dotnet/src/SemanticKernel.Abstractions/Events/SKEventArgs.cs, dotnet/src/SemanticKernel.Abstractions/Functions/ISKPluginExtensions.cs, dotnet/src/SemanticKernel.Abstractions/Services/IAIServiceSelector.cs, dotnet/src/SemanticKernel.Abstractions/Services/OrderedIAIServiceSelector.cs, dotnet/src/SemanticKernel.Core/Functions/SKFunctionFromMethod.cs, dotnet/src/SemanticKernel.Core/KernelExtensions.cs, dotnet/src/SemanticKernel.Core/Services/AIServiceSelectorBase.cs, dotnet/src/SemanticKernel.UnitTests/Functions/OrderedIAIServiceConfigurationProviderTests.cs, dotnet/src/SemanticKernel.UnitTests/Functions/SKPluginCollectionTests.cs, dotnet/src/SemanticKernel.UnitTests/Functions/SemanticFunctionTests.cs, dotnet/src/SemanticKernel.UnitTests/KernelTests.cs, dotnet/src/SemanticKernel.UnitTests/Planning/PlanTests.cs
Also a few straggling uses of "view"
=> .Net: Rename skFunction locals/parameters to function

.github/workflows/dotnet-build-and-test.yml, dotnet/SK-dotnet.sln, dotnet/samples/ApplicationInsightsExample/ApplicationInsightsExample.csproj, dotnet/samples/ApplicationInsightsExample/Program.cs, dotnet/samples/KernelSyntaxExamples/Example48_GroundednessChecks.cs, dotnet/samples/KernelSyntaxExamples/KernelSyntaxExamples.csproj, dotnet/src/IntegrationTests/IntegrationTests.csproj, dotnet/src/SemanticKernel.MetaPackage/SemanticKernel.MetaPackage.csproj
Action, sequential, stepwise planners, and flow orchestrator are temporarily excluded from the solution.
=> .Net: Temporarily excluding planners and flow orchestrator

python/semantic_kernel/__init__.py, python/semantic_kernel/utils/settings.py
=> Python: undo small changes in init and utils

dotnet/src/Experimental/Assistants/AssistantBuilder.cs, dotnet/src/SemanticKernel.Abstractions/Functions/KernelPluginCollection.cs
Addressing feedback from previous PR
=> .Net: Replace straggling Add usage with AddRange

python/pyproject.toml, python/semantic_kernel/connectors/ai/hugging_face/services/hf_text_embedding.py, python/semantic_kernel/connectors/ai/open_ai/services/open_ai_text_completion_base.py, python/tests/integration/completions/test_azure_oai_chat_service.py, python/tests/integration/completions/test_azure_oai_text_service.py, python/tests/integration/completions/test_conversation_summary_skill.py, python/tests/integration/embeddings/test_azure_oai_embedding_service.py, python/tests/integration/embeddings/test_hf_embedding_service.py, python/tests/integration/planning/sequential_planner/test_sequential_plan_parser.py, python/tests/integration/planning/sequential_planner/test_sequential_planner.py, python/tests/integration/planning/stepwise_planner/test_stepwise_planner.py
Integration tests were failing due to missing keyword args. Bumping python SK package to 0.4.0.dev due to major changes to OpenAI SDK 1.0 upgrade.
=> Python: Fix integration test keyword args. Bump python package version to 0.4.0.dev.

python/tests/integration/completions/test_hf_local_text_completions.py, python/tests/integration/completions/test_hf_local_text_summarization.py
Temp skip hugging face int tests until we can investigate stability.
=> Python: Temp skip hugging face int tests until we can investigate stability.

java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/SKFunction.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/skilldefinition/annotations/SKSample.java
=> Java: API for 04-DynamicRag sample

dotnet/src/InternalUtilities/planning/PlannerInstrumentation.cs, dotnet/src/Planners/Planners.Handlebars/Handlebars/HandlebarsPlanner.cs, dotnet/src/Planners/Planners.Handlebars/Planners.Handlebars.csproj
Instrument the Handlebars planner.
Use the PlannerInstrumention class to wrap the HandleBars planner for instrumentation.
Run using the telemetry sample in the repository:
=> .Net: Instrument the HandleBars planner

dotnet/samples/KernelSyntaxExamples/Example72_KernelStreaming.cs, dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAICompletionTests.cs, dotnet/src/SemanticKernel.Core/KernelExtensions.cs, dotnet/src/SemanticKernel.UnitTests/Functions/FunctionFromPromptTests.cs, dotnet/src/SemanticKernel.UnitTests/KernelTests.cs
=> .Net Kernel RunStreaming to InvokeStreaming + Small other Run to Invoke changes

dotnet/src/Connectors/Connectors.AI.OpenAI/AzureSdk/ClientBase.cs, dotnet/src/Connectors/Connectors.AI.OpenAI/ChatCompletion/ChatPromptParser.cs, dotnet/src/SemanticKernel.Core/Prompts/PromptNode.cs, dotnet/src/SemanticKernel.Core/Prompts/XmlPromptParser.cs, dotnet/src/SemanticKernel.Core/SemanticKernel.Core.csproj, dotnet/src/SemanticKernel.UnitTests/KernelTests.cs, dotnet/src/SemanticKernel.UnitTests/Prompt/XmlPromptParserTests.cs
Fixes https://github.com/microsoft/semantic-kernel/issues/3870
=> .Net: Make PromptNode and XmlPromptParser internal

python/semantic_kernel/connectors/ai/open_ai/services/azure_config_base.py, python/semantic_kernel/connectors/ai/open_ai/services/open_ai_config_base.py
During the reworking of the OpenAI classes for openai sdk v1, the user-agent telemetry was not ported over, readding that here.
=> Python: readded user agent telemetry to openai classes

dotnet/SK-dotnet.sln
I'm not sure why the .sln is written this way in the first place, but these files no longer exist.
=> .Net: Remove deleted files from .sln

dotnet/src/Functions/Functions.Markdown/KernelFunctionMarkdown.cs, dotnet/src/Functions/Functions.Markdown/MarkdownKernelExtensions.cs, dotnet/src/Functions/Functions.Yaml/KernelFunctionYaml.cs, dotnet/src/Functions/Functions.Yaml/PromptYamlKernelExtensions.cs
=> .Net: Remove CreateFunctionFromPromptXXXResource methods

java/semantickernel-api/src/main/java/com/microsoft/semantickernel/Kernel.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/FunctionResult.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/SKFunction.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/skilldefinition/annotations/SKSample.java
=> Java: API changes to support 05-MultiModal

dotnet/nuget/nuget-package.props
=> .Net: Release 1.0.0-rc2

dotnet/samples/KernelSyntaxExamples/Example08_RetryHandler.cs
Fixes https://github.com/microsoft/semantic-kernel/issues/3789
=> .Net: Add comment to Example08_RetryHandler

dotnet/src/InternalUtilities/src/System/InternalTypeConverter.cs, dotnet/src/InternalUtilities/src/System/TypeConverterFactory.cs, dotnet/src/SemanticKernel.Abstractions/Functions/FunctionResult.cs, dotnet/src/SemanticKernel.Core/PromptTemplate/KernelPromptTemplate.cs, dotnet/src/SemanticKernel.UnitTests/Utilities/InternalTypeConverterTests.cs
Code duplication for type conversion functionality has been removed.
=> .Net: Code duplication removed

java/semantickernel-bom/pom.xml
=> Java: Bump netty

java/api-test/api-usage-example/pom.xml, java/api-test/integration-tests/pom.xml, java/api-test/pom.xml, java/connectors/semantickernel-connectors-ai-openai/pom.xml, java/connectors/semantickernel-connectors-memory-azurecognitivesearch/pom.xml, java/connectors/semantickernel-connectors-memory-jdbc/pom.xml, java/connectors/semantickernel-connectors-memory-mysql/pom.xml, java/connectors/semantickernel-connectors-memory-postgresql/pom.xml, java/connectors/semantickernel-connectors-memory-sqlite/pom.xml, java/extensions/semantickernel-gpt3-tokenizer/pom.xml, java/extensions/semantickernel-planners/pom.xml, java/extensions/semantickernel-settings-loader/pom.xml, java/plugins/semantickernel-plugin-core/pom.xml, java/pom.xml, java/samples/pom.xml, java/samples/sample-code/pom.xml, java/samples/semantickernel-samples-guice/pom.xml, java/semantickernel-api/pom.xml, java/semantickernel-bom/pom.xml, java/semantickernel-core/pom.xml
=> Java: [maven-release-plugin] prepare release java-0.2.13-alpha

dotnet/src/SemanticKernel.Abstractions/Functions/KernelPlugin.cs, dotnet/src/SemanticKernel.Abstractions/Functions/KernelPluginExtensions.cs, dotnet/src/SemanticKernel.UnitTests/Functions/KernelPluginCollectionTests.cs, dotnet/src/SemanticKernel.UnitTests/Functions/KernelPluginTests.cs
Fixes https://github.com/microsoft/semantic-kernel/issues/4105
=> .Net: Add KernelPlugin.GetFunctionsMetadata

dotnet/src/Connectors/Connectors.OpenAI/ChatCompletion/OpenAIChatCompletionService.cs
Fixes https://github.com/microsoft/semantic-kernel/issues/4117
=> .Net: Fix stack overflow caused by erroneous recursion in OpenAIChatCompletionService

dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromMethod.cs, dotnet/src/SemanticKernel.UnitTests/Functions/KernelFunctionFromMethodTests2.cs
If a method wants to return additional metadata, it can do so via returning a FunctionResult, but it can only construct a FunctionResult if it has a reference to itself, which is currently only possible to get in a convoluted manner. This allows the method to take a KernelFunction argument that will be set to itself, just as it can take a Kernel, KernelArguments, etc, argument to have access to that information.
=> .Net: Allow KernelFunction argument to KernelFunctionFromMethod method

dotnet/src/SemanticKernel.Core/PromptTemplate/KernelPromptTemplate.cs
Use loops instead of more complicate LINQ queries, avoid intermediate lists and sets, etc.
=> .Net: Streamline KernelPromptTemplate.AddMissingInputVariables

dotnet/samples/KernelSyntaxExamples/Example26_AADAuth.cs, dotnet/samples/KernelSyntaxExamples/Example52_ApimAuth.cs, dotnet/src/Connectors/Connectors.OpenAI/ChatCompletion/AzureOpenAIChatCompletionService.cs, dotnet/src/Connectors/Connectors.OpenAI/OpenAIMemoryBuilderExtensions.cs, dotnet/src/Connectors/Connectors.OpenAI/OpenAIServiceCollectionExtensions.cs, dotnet/src/Connectors/Connectors.OpenAI/TextEmbedding/AzureOpenAITextEmbeddingGeneration.cs, dotnet/src/Connectors/Connectors.OpenAI/TextGeneration/AzureOpenAITextGenerationService.cs, dotnet/src/Connectors/Connectors.OpenAI/TextToImage/AzureOpenAITextToImageService.cs, dotnet/src/Connectors/Connectors.UnitTests/OpenAI/AIServicesOpenAIExtensionsTests.cs, dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAITextEmbeddingTests.cs
=> .Net: Make modelId optional for Azure AI services

dotnet/samples/KernelSyntaxExamples/Example57_KernelHooks.cs
All examples to be clear with comments for V1
Added comments...nothing crazy.
=> .Net KernelExample57 - Update comments

dotnet/samples/KernelSyntaxExamples/Example15_TextMemoryPlugin.cs, dotnet/src/Connectors/Connectors.HuggingFace/HuggingFaceKernelBuilderExtensions.cs, dotnet/src/Connectors/Connectors.HuggingFace/TextEmbedding/HuggingFaceTextEmbeddingGeneration.cs, dotnet/src/Connectors/Connectors.HuggingFace/TextEmbedding/HuggingFaceTextEmbeddingGenerationService.cs, dotnet/src/Connectors/Connectors.OpenAI/OpenAIMemoryBuilderExtensions.cs, dotnet/src/Connectors/Connectors.OpenAI/OpenAIServiceCollectionExtensions.cs, dotnet/src/Connectors/Connectors.OpenAI/TextEmbedding/AzureOpenAITextEmbeddingGenerationService.cs, dotnet/src/Connectors/Connectors.OpenAI/TextEmbedding/OpenAITextEmbeddingGenerationService.cs, dotnet/src/Connectors/Connectors.UnitTests/HuggingFace/TextEmbedding/HuggingFaceEmbeddingGenerationTests.cs, dotnet/src/Connectors/Connectors.UnitTests/Memory/Pinecone/PineconeMemoryBuilderExtensionsTests.cs, dotnet/src/Connectors/Connectors.UnitTests/Memory/Qdrant/QdrantMemoryBuilderExtensionsTests.cs, dotnet/src/Connectors/Connectors.UnitTests/Memory/Weaviate/WeaviateMemoryBuilderExtensionsTests.cs, dotnet/src/Connectors/Connectors.UnitTests/OpenAI/AIServicesOpenAIExtensionsTests.cs, dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAITextEmbeddingTests.cs, dotnet/src/Plugins/Plugins.Memory/MemoryBuilder.cs, dotnet/src/Plugins/Plugins.UnitTests/Memory/MemoryBuilderTests.cs, dotnet/src/SemanticKernel.Abstractions/AI/Embeddings/EmbeddingGenerationServiceExtensions.cs, dotnet/src/SemanticKernel.Abstractions/AI/Embeddings/IEmbeddingGenerationService.cs, dotnet/src/SemanticKernel.Abstractions/AI/Embeddings/ITextEmbeddingGenerationService.cs, dotnet/src/SemanticKernel.Core/Memory/SemanticTextMemory.cs
Consistent name for AIServices
=> .Net: Add service suffix IEmbeddingGenerationService

python/pyproject.toml
Bumping SK Python package version to 0.4.2.dev for upcoming release.
=> Python: Bump Python package version to 0.4.2.dev

dotnet/Directory.Packages.props
Customer reported issue when mixing down-stream version with SK: https://github.com/microsoft/semantic-kernel/issues/3803
Align to current stable version.
=> .Net - Update pgvector for Postgres memory connector

dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/AzureOpenAIWithDataChatMessageContent.cs, dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/AzureOpenAIWithDataStreamingChatMessageContent.cs, dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs, dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/OpenAIChatMessageContent.cs, dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/OpenAIStreamingChatMessageContent.cs, dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/OpenAIStreamingTextContent.cs, dotnet/src/Connectors/Connectors.OpenAI/ChatCompletionWithData/AzureOpenAIChatCompletionWithDataService.cs, dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatHistory.cs, dotnet/src/SemanticKernel.Abstractions/Contents/ChatMessageContent.cs, dotnet/src/SemanticKernel.Abstractions/Contents/ImageContent.cs, dotnet/src/SemanticKernel.Abstractions/Contents/KernelContent.cs, dotnet/src/SemanticKernel.Abstractions/Contents/StreamingChatMessageContent.cs, dotnet/src/SemanticKernel.Abstractions/Contents/StreamingKernelContent.cs, dotnet/src/SemanticKernel.Abstractions/Contents/StreamingTextContent.cs, dotnet/src/SemanticKernel.Abstractions/Contents/TextContent.cs, dotnet/src/SemanticKernel.Abstractions/Events/CancelKernelEventArgs.cs, dotnet/src/SemanticKernel.Abstractions/Events/KernelEventArgs.cs, dotnet/src/SemanticKernel.Abstractions/Functions/FunctionResult.cs, dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromPrompt.cs, dotnet/src/SemanticKernel.UnitTests/Functions/FunctionResultTests.cs
And then stop making copies each time we hand one out.
Fixes https://github.com/microsoft/semantic-kernel/issues/4233
=> .Net: Use IReadOnlyDictionary for metadata dictionaries

dotnet/samples/KernelSyntaxExamples/Getting_Started/Step3_Yaml_Prompt.cs, dotnet/samples/KernelSyntaxExamples/KernelSyntaxExamples.csproj, dotnet/samples/KernelSyntaxExamples/Resources/GenerateStory.yaml, dotnet/samples/KernelSyntaxExamples/Resources/GenerateStoryHandlebars.yaml
=> .Net: Update the sample to also demonstrate loading yaml resources

dotnet/samples/KernelSyntaxExamples/Getting_Started/Step5_Chat_Prompt.cs, dotnet/samples/KernelSyntaxExamples/Getting_Started/Step6_Responsible_AI.cs, dotnet/samples/KernelSyntaxExamples/Getting_Started/Step7_Pipelining.cs
=> .Net: Add getting started showing how to use hooks for responsible AI

dotnet/samples/KernelSyntaxExamples/Example58_ConfigureExecutionSettings.cs
=> .Net: Example 58 - remove chatModelId requirement

dotnet/samples/KernelSyntaxExamples/Getting_Started/Step1_Create_Kernel.cs, dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAIToolsTests.cs
=> .Net: Integration tests for OpenAI Tools

python/notebooks/00-getting-started.ipynb, python/notebooks/01-basic-loading-the-kernel.ipynb, python/notebooks/02-running-prompts-from-file.ipynb, python/notebooks/03-semantic-function-inline.ipynb, python/notebooks/04-context-variables-chat.ipynb, python/notebooks/05-using-the-planner.ipynb, python/notebooks/06-memory-and-embeddings.ipynb, python/notebooks/07-hugging-face-for-skills.ipynb, python/notebooks/08-native-function-inline.ipynb, python/notebooks/09-groundedness-checking.ipynb, python/notebooks/10-multiple-results-per-prompt.ipynb, python/notebooks/11-streaming-completions.ipynb, python/pyproject.toml
Bump python package for a release. Update notebook package refs to 0.4.3
Bumping for a release so that notebooks can reference the latest release that contains some fixes.
=> Python: Bump python package for a release. Update notebook package refs to 0.4.3.

.github/workflows/dotnet-build-and-test.yml, .vscode/settings.json, dotnet/samples/KernelSyntaxExamples/Example59_OpenAIFunctionCalling.cs, dotnet/samples/KernelSyntaxExamples/Getting_Started/Step2_Add_Plugins.cs, dotnet/samples/KernelSyntaxExamples/Getting_Started/Step4_Dependency_Injection.cs, dotnet/samples/KernelSyntaxExamples/Getting_Started/Step7_Observability.cs, dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAIToolsTests.cs, dotnet/src/IntegrationTests/Planners/Stepwise/FunctionCallingStepwisePlannerTests.cs, dotnet/src/IntegrationTests/testsettings.json
- Changing function calling integration tests to use OpenAI gpt-4 until issues with OAI function calling are resolved.
- Added description to some kernel functions using in tests to improve stability of function calling.
=> .Net: planner tests openai

dotnet/src/Connectors/Connectors.Memory.Chroma/README.md, dotnet/src/Connectors/Connectors.Memory.Kusto/README.md, dotnet/src/Connectors/Connectors.Memory.Milvus/README.md, dotnet/src/Connectors/Connectors.Memory.MongoDB/README.md, dotnet/src/Connectors/Connectors.Memory.Postgres/README.md, dotnet/src/Connectors/Connectors.Memory.Redis/README.md
All READMEs for the memory connectors are out-of-date. Related item: https://github.com/microsoft/semantic-kernel/issues/4251
Update the READMEs to show the latest usage patterns.
=> .Net: Update memory connector READMEs

dotnet/samples/KernelSyntaxExamples/Example17_ChatGPT.cs, dotnet/samples/KernelSyntaxExamples/Example33_StreamingChat.cs, dotnet/samples/KernelSyntaxExamples/Example44_MultiChatCompletion.cs
Fixed initialization of `AzureOpenAIChatCompletionService` in examples.
=> .Net: Small fixes for examples

dotnet/Directory.Packages.props, dotnet/README.md, dotnet/notebooks/00-getting-started.ipynb, dotnet/notebooks/01-basic-loading-the-kernel.ipynb, dotnet/notebooks/02-running-prompts-from-file.ipynb, dotnet/notebooks/03-semantic-function-inline.ipynb, dotnet/notebooks/04-kernel-arguments-chat.ipynb, dotnet/notebooks/05-using-the-planner.ipynb, dotnet/notebooks/06-memory-and-embeddings.ipynb, dotnet/notebooks/07-DALL-E-3.ipynb, dotnet/notebooks/08-chatGPT-with-DALL-E-3.ipynb, dotnet/notebooks/09-memory-with-chroma.ipynb, dotnet/notebooks/10-BingSearch-using-kernel.ipynb, dotnet/notebooks/README.md
=> .Net: Updated dotnet notebooks to use SK v1.0.1

dotnet/README.md
Resolves: https://github.com/microsoft/semantic-kernel/issues/4416
=> .Net: Updated dotnet README for SK v1.0

java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example06_TemplateLanguage.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/DefaultKernel.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/Kernel.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionFromPrompt.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelPromptTemplateFactory.java
=> Java: Fix execution of Example05_InlineFunctionDefinition

python/semantic_kernel/connectors/ai/open_ai/request_settings/open_ai_request_settings.py, python/tests/unit/ai/open_ai/test_openai_request_settings.py
=> Python: response format fix

java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example06_TemplateLanguage.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example08_RetryHandler.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionFromPrompt.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelPromptTemplateFactory.java
=> Java: Add retry example

python/semantic_kernel/connectors/ai/ai_service_client_base.py, python/semantic_kernel/connectors/ai/google_palm/services/gp_chat_completion.py, python/semantic_kernel/connectors/ai/google_palm/services/gp_text_completion.py, python/semantic_kernel/connectors/ai/google_palm/services/gp_text_embedding.py
Noticed that constr was depricated, removed and replaced with Annotated and StringConstraints
=> Python: constr removed and replaced by annotated stringconstraints

python/.cspell.json, python/.vscode/settings.json, python/semantic_kernel/connectors/ai/open_ai/const.py, python/semantic_kernel/connectors/ai/open_ai/request_settings/azure_chat_request_settings.py, python/semantic_kernel/connectors/ai/open_ai/request_settings/open_ai_request_settings.py, python/semantic_kernel/connectors/ai/open_ai/services/azure_chat_completion.py, python/semantic_kernel/connectors/ai/open_ai/services/open_ai_handler.py
As we button down the python version, making some improvements in the settings and with that come some updates.
- Moved cspell config from settings to .cspell.json file and added missing words.
- Some fixes in typing: final -> Final[str]
- Some other small fixes coming from turning on pyright.
=> Python: moved cspell to own settings, small fixes in typing

python/samples/kernel-syntax-examples/self-critique_rag.py
Some more advanced uses of OpenAI with SK!
=> Python: Add sample for rag self critique with AI Search

.github/workflows/dotnet-format.yml
Dependency resolution when targeting dotnet 7.0.  
- Target dotnet 8.0.
- Build /CI unaffected
=> .Net - Unblock main / Fix dotnet-format workflow

dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAIToolsTests.cs, dotnet/src/IntegrationTests/Planners/Stepwise/FunctionCallingStepwisePlannerTests.cs, dotnet/src/IntegrationTests/README.md
PR's cannot be merged
See https://github.com/microsoft/semantic-kernel/issues/4534
=> .Net: Skip failing stepwise planner integration test

python/notebooks/00-getting-started.ipynb, python/notebooks/01-basic-loading-the-kernel.ipynb, python/notebooks/02-running-prompts-from-file.ipynb, python/notebooks/03-semantic-function-inline.ipynb, python/notebooks/04-context-variables-chat.ipynb, python/notebooks/05-using-the-planner.ipynb, python/notebooks/06-memory-and-embeddings.ipynb, python/notebooks/07-hugging-face-for-skills.ipynb, python/notebooks/08-native-function-inline.ipynb, python/notebooks/09-groundedness-checking.ipynb, python/notebooks/10-multiple-results-per-prompt.ipynb, python/notebooks/11-streaming-completions.ipynb, python/pyproject.toml
Bumping pyproject.toml to version 0.4.5 for a release. Updating the package references in the Jupyter notebooks.
Pre-release code updates.
=> Python: Bump pyproject to 0.4.5 for release. Update notebooks to use this version

java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIChatCompletion.java, java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/ParsedPrompt.java, java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/XMLPromptParser.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example03_Arguments.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example26_AADAuth.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example27_PromptFunctionsUsingChatGPT.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/DefaultKernel.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/TextAIService.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/chatcompletion/ChatCompletionService.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/plugin/KernelFunctionFactory.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionFromPrompt.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/textcompletion/TextGenerationService.java
=> Java: add example Example27_PromptFunctionsUsingChatGPT

dotnet/nuget/nuget-package.props
=> .Net: Bumping - v1.1.0 release

dotnet/src/IntegrationTests/RedirectOutput.cs
Integration tests are failing sporadically with the following error. This change is a temporary fix while we investigate the root cause of these failures.
```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.InvalidOperationException: There is no currently active test.
at Xunit.Sdk.TestOutputHelper.GuardInitialized() in /_/src/xunit.execution/Sdk/Frameworks/TestOutputHelper.cs:line 52
at Xunit.Sdk.TestOutputHelper.QueueTestOutput(String output) in /_/src/xunit.execution/Sdk/Frameworks/TestOutputHelper.cs:line 67
at SemanticKernel.IntegrationTests.RedirectOutput.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /__w/semantic-kernel/semantic-kernel/dotnet/src/IntegrationTests/RedirectOutput. …
```
=> .Net: Catch InvalidOperationException in RedirectOutput.Log

java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example64_MultiplePromptTemplates.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/AggregatorPromptTemplateFactory.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/HandlebarsPromptTemplateFactory.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelPromptTemplateFactory.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/PromptTemplateConfig.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/PromptTemplateFactory.java
=> Java: Add Example64_MultiplePromptTemplates

java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example26_AADAuth.java
=> Java: add Example26_AADAuth

dotnet/nuget/nuget-package.props
update PackageValidationBaselineVersion to `1.1.0` in case of breaking changes compared to `1.1.0`
=> .Net: Update PackageValidationBaselineVersion

java/plugins/semantickernel-plugin-core/src/main/java/com/microsoft/semantickernel/plugins/TextPlugin.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example05_InlineFunctionDefinition.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example06_TemplateLanguage.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example08_RetryHandler.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example09_FunctionTypes.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example10_DescribeAllPluginsAndFunctions.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example13_ConversationSummaryPlugin.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example17_ChatGPT.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example26_AADAuth.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example27_PromptFunctionsUsingChatGPT.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example33_StreamingChat.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example55_TextChunker.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example56_TemplateMethodFunctionsWithMultipleArguments.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example58_ConfigureExecutionSettings.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example64_MultiplePromptTemplates.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/plugin/KernelFunctionFactory.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/plugin/KernelPluginFactory.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelPromptTemplateFactory.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/PromptTemplateConfig.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/templateengine/semantickernel/TemplateTokenizer.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/templateengine/semantickernel/blocks/CodeBlock.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/templateengine/semantickernel/blocks/NamedArgBlock.java
=> Java: Add Example55_TextChunker and Example56_TemplateMethodFunctionsWithMultipleArguments

java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIChatCompletion.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example33_Chat.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example42_KernelBuilder.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example67_KernelStreaming.java, java/samples/sk-v1/01-SimpleChat/src/test/java/SimpleChatTest.java, java/samples/sk-v1/02-PersonaChat/src/main/java/Main.java, java/samples/sk-v1/02-PersonaChat/src/test/java/PersonaChatTest.java, java/samples/sk-v1/03-SimpleRag/src/main/java/Main.java, java/samples/sk-v1/03-SimpleRag/src/test/java/SimpleRagTest.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/DefaultKernel.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/Kernel.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/StreamingKernelContent.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/chatcompletion/ChatCompletionService.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/chatcompletion/ChatMessageContent.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/chatcompletion/StreamingChatMessageContent.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/KernelFunction.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/KernelFunctionFromMethod.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/TextRequestContent.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/contextvariables/DefaultKernelArguments.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionFromPrompt.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/services/ParentAIServiceSelector.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/templateengine/semantickernel/blocks/CodeBlock.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/textcompletion/StreamingTextContent.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/textcompletion/TextContent.java
=> Java: Remove streaming feature

dotnet/samples/KernelSyntaxExamples/Getting_Started/Step1_Create_Kernel.cs
=> .Net: Add an example showing how to use the OpenAI response format property

python/notebooks/00-getting-started.ipynb, python/notebooks/01-basic-loading-the-kernel.ipynb, python/notebooks/02-running-prompts-from-file.ipynb, python/notebooks/03-semantic-function-inline.ipynb, python/notebooks/04-context-variables-chat.ipynb, python/notebooks/05-using-the-planner.ipynb, python/notebooks/06-memory-and-embeddings.ipynb, python/notebooks/07-hugging-face-for-plugins.ipynb, python/notebooks/08-native-function-inline.ipynb, python/notebooks/09-groundedness-checking.ipynb, python/notebooks/10-multiple-results-per-prompt.ipynb, python/notebooks/11-streaming-completions.ipynb, python/pyproject.toml
In preparation for a new release, need to bump pyproject and notebook versions to the next minor version.
Bump pyproject version to 0.4.6. Bump notebook sk versions to 0.4.6.
=> Python: Bump pyproject version to 0.4.6. Bump notebook sk versions to 0.4.6.

java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example69_MutableKernelPlugin.java
=> Java: Add Example69_MutableKernelPlugin

dotnet/nuget/nuget-package.props
Increasing Minor version since changes include new functionality.
=> .Net: Upgraded package version to 1.2.0

dotnet/samples/KernelSyntaxExamples/Example76_Filters.cs
Reverted example with filters for better example discoverability.
=> .Net: Reverted example with filters

dotnet/src/Connectors/Connectors.GoogleVertexAI.UnitTests/Core/GoogleAI/GoogleAIClientEmbeddingsGenerationTests.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI.UnitTests/Core/GoogleAI/GoogleAIEmbeddingRequestTests.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI/Core/GoogleAI/GoogleAIEmbeddingRequest.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI/Core/GoogleAI/GoogleAIEmbeddingResponse.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI/Core/GoogleAI/GoogleAIEmbeddingsClient.cs
Spit from PR https://github.com/microsoft/semantic-kernel/pull/4407
=> .Net GoogleAI Embeddings generation impl

python/notebooks/00-getting-started.ipynb, python/notebooks/01-basic-loading-the-kernel.ipynb, python/notebooks/02-running-prompts-from-file.ipynb, python/notebooks/03-semantic-function-inline.ipynb, python/notebooks/04-context-variables-chat.ipynb, python/notebooks/05-using-the-planner.ipynb, python/notebooks/06-memory-and-embeddings.ipynb, python/notebooks/07-hugging-face-for-plugins.ipynb, python/notebooks/08-native-function-inline.ipynb, python/notebooks/09-groundedness-checking.ipynb, python/notebooks/10-multiple-results-per-prompt.ipynb, python/notebooks/11-streaming-completions.ipynb, python/pyproject.toml
Bump pyproject version for release. Update notebook package versions.
Bump pyproject version for release. Update notebook package versions.
=> Python: bump pyproject version for release. Update notebook package versions.

dotnet/notebooks/00-getting-started.ipynb, dotnet/notebooks/README.md
Update sample readme to point to .NET 8.0 downloads
=> .Net: update link to .NET8.0 download

dotnet/notebooks/06-memory-and-embeddings.ipynb, dotnet/src/SemanticKernel.Abstractions/AI/XmlPromptParser.cs
It is nice to have clean text and instructions.
I just correct a couple of places where I see the issue with articles grammar which gives a confusion.
- [ X ] The code builds clean without any errors or warnings
- [ X ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ X ] All unit tests pass, and I have added new tests where possible
- [ X ] I didn't break anyone :smile:
=> .Net: Articles grammar correction

dotnet/src/Connectors/Connectors.GoogleVertexAI.UnitTests/Core/VertexAI/VertexAIClientEmbeddingsGenerationTests.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI.UnitTests/Core/VertexAI/VertexAIEmbeddingRequestTests.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI/Core/VertexAI/VertexAIEmbeddingRequest.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI/Core/VertexAI/VertexAIEmbeddingResponse.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI/Core/VertexAI/VertexAIEmbeddingsClient.cs
Spit from PR https://github.com/microsoft/semantic-kernel/pull/4407
=> .Net VertexAI Embeddings generation

dotnet/nuget/nuget-package.props
=> .Net: Update the baseline to 1.3.0

python/notebooks/00-getting-started.ipynb, python/notebooks/01-basic-loading-the-kernel.ipynb, python/notebooks/02-running-prompts-from-file.ipynb, python/notebooks/03-semantic-function-inline.ipynb, python/notebooks/04-context-variables-chat.ipynb, python/notebooks/05-using-the-planner.ipynb, python/notebooks/06-memory-and-embeddings.ipynb, python/notebooks/07-hugging-face-for-plugins.ipynb, python/notebooks/08-native-function-inline.ipynb, python/notebooks/09-groundedness-checking.ipynb, python/notebooks/10-multiple-results-per-prompt.ipynb, python/notebooks/11-streaming-completions.ipynb, python/pyproject.toml
Python: Bump python version to 0.5.0 for release. Update notebooks.
Python: Bump python version to 0.5.0 for release. Update notebooks.
=> Python: Bump python version to 0.5.0 for release. Update notebooks.

dotnet/src/IntegrationTests/Connectors/GoogleVertexAI/Gemini/GeminiChatCompletionTests.cs, dotnet/src/IntegrationTests/Connectors/GoogleVertexAI/Gemini/GeminiTextGenerationTests.cs, dotnet/src/IntegrationTests/IntegrationTests.csproj
Spit from PR https://github.com/microsoft/semantic-kernel/pull/4407
@RogerBarreto
=> .Net Gemini - chat & text integration tests

dotnet/Directory.Packages.props, dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs, dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/OpenAIFunctionToolCall.cs
=> .Net: Update azure.ai.openai to beta 13

dotnet/samples/KernelSyntaxExamples/Example80_GeminiTextGeneration.cs, dotnet/samples/KernelSyntaxExamples/Example81_GeminiChatCompletion.cs, dotnet/samples/KernelSyntaxExamples/KernelSyntaxExamples.csproj, dotnet/samples/KernelSyntaxExamples/README.md, dotnet/samples/KernelSyntaxExamples/TestConfiguration.cs
These examples are intended to show interested parties how gemini works right now. They will not necessarily reach the main branch in this form.
Spit from PR https://github.com/microsoft/semantic-kernel/pull/4407
@RogerBarreto
=> .Net Gemini - Added samples

python/notebooks/00-getting-started.ipynb, python/notebooks/01-basic-loading-the-kernel.ipynb, python/notebooks/02-running-prompts-from-file.ipynb, python/notebooks/03-semantic-function-inline.ipynb, python/notebooks/04-context-variables-chat.ipynb, python/notebooks/05-using-the-planner.ipynb, python/notebooks/06-memory-and-embeddings.ipynb, python/notebooks/07-hugging-face-for-plugins.ipynb, python/notebooks/08-native-function-inline.ipynb, python/notebooks/09-groundedness-checking.ipynb, python/notebooks/10-multiple-results-per-prompt.ipynb, python/notebooks/11-streaming-completions.ipynb, python/pyproject.toml
Bump python project version for release. Update notebooks.
Bump python project version for release. Update notebooks.
=> Python: Bump python project version for release. Update notebooks.

dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs
Resolves: https://github.com/microsoft/semantic-kernel/issues/4953
=> .Net: Added fix for null completion usage details

dotnet/nuget/nuget-package.props
=> .Net: Bump to version 1.3.1

java/pom.xml, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/FunctionInvocation.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionFromMethod.java, java/semantickernel-bom/pom.xml
=> Java: Version bumps

java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIChatCompletion.java, java/api-test/integration-tests/src/test/java/com/microsoft/semantickernel/syntaxexamples/Example01NativeFunctionsTest.java, java/api-test/integration-tests/src/test/java/com/microsoft/semantickernel/syntaxexamples/Example03_ArgumentsTest.java, java/plugins/semantickernel-plugin-core/src/main/java/com/microsoft/semantickernel/plugins/text/TextPlugin.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/plugins/TimePlugin.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example01_NativeFunctions.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example03_Arguments.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example13_ConversationSummaryPlugin.java, java/semantickernel-api/src/main/ignore/java/com/microsoft/semantickernel/DefaultKernel.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/FunctionInvocation.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/KernelFunction.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/ToolCallBehavior.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/plugin/KernelPluginFactory.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionFromMethod.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionFromPrompt.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/templateengine/handlebars/HandlebarsPromptTemplate.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/templateengine/semantickernel/blocks/FunctionIdBlock.java
=> Java: Complete rename from skill to plugin

java/aiservices/openai/pom.xml, java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/OpenAIRequestSettings.java, java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/OpenAiRequestSettings.java, java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIChatCompletion.java, java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/textcompletion/OpenAITextGenerationService.java, java/aiservices/openai/src/main/resources/com/microsoft/semantickernel/aiservices/openai/semantic-kernel-version.properties
=> Java: Add header to Java openai call

java/aiservices/openai/pom.xml, java/api-test/integration-tests/pom.xml, java/api-test/pom.xml, java/connectors/semantickernel-connectors-web-bing/pom.xml, java/plugins/semantickernel-plugin-core/pom.xml, java/pom.xml, java/samples/pom.xml, java/samples/sample-code/pom.xml, java/samples/sk-v1/01-SimpleChat/pom.xml, java/samples/sk-v1/02-PersonaChat/pom.xml, java/samples/sk-v1/03-SimpleRag/pom.xml, java/samples/sk-v1/04-DynamicRag/pom.xml, java/samples/sk-v1/05-MultiModal/pom.xml, java/samples/sk-v1/06-Assistants/pom.xml, java/samples/sk-v1/pom.xml, java/semantickernel-api/pom.xml, java/semantickernel-bom/pom.xml
=> Java: Tidy poms

python/semantic_kernel/connectors/memory/azure_cosmosdb/mongo_vcore_store_api.py
fix #4975 
check if the key timestamp exists before setting it as it's optional
=> Python: check if timestamp exists

java/connectors/semantickernel-connectors-memory-redis/pom.xml, java/connectors/semantickernel-connectors-memory-redis/src/main/java/com/microsoft/semantickernel/connectors/memory/redis/JsonMemoryRecord.java, java/connectors/semantickernel-connectors-memory-redis/src/main/java/com/microsoft/semantickernel/connectors/memory/redis/RedisMemoryStore.java, java/samples/semantickernel-spring-starter/pom.xml, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/SKException.java, java/semantickernel-bom/pom.xml
=> Java: Update redis and spring-starter versions

dotnet/nuget/nuget-package.props
=> .Net: Bump to version 1.4.0

java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIChatCompletion.java, java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIFunction.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example59_OpenAIFunctionCalling.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/KernelPluginCollection.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/chatcompletion/ChatCompletionService.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/chatcompletion/ChatHistory.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/hooks/KernelHooks.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/KernelFunction.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/KernelFunctionMetadata.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/ToolCallBehavior.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/InputParameter.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionFromMethod.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/templateengine/handlebars/HandlebarsPromptTemplate.java
=> Java: Apply linting fixes

dotnet/src/Connectors/Connectors.GoogleVertexAI.UnitTests/Extensions/GoogleAIServiceCollectionExtensionsTests.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI.UnitTests/Extensions/VertexAIServiceCollectionExtensionsTests.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI/ChatCompletion/GeminiChatCompletionServiceBase.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI/ChatCompletion/GoogleAIGeminiChatCompletionService.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI/ChatCompletion/VertexAIGeminiChatCompletionService.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI/Extensions/GoogleAIServiceCollectionExtensions.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI/Extensions/VertexAIServiceCollectionExtensions.cs
The text generation service interface was removed from the chat completion services. GeminiChatCompletionServiceBase was updated accordingly. Also, the related service registrations and unit tests were modified to reflect these changes.
.Net GoogleAI connector progress (Gemini) #4680
@RogerBarreto
=> .Net: Gemini - Remove text generation from chat completion services

dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAIToolsTests.cs, dotnet/src/IntegrationTests/Planners/Stepwise/FunctionCallingStepwisePlannerTests.cs
=> .Net: OpenAI is throttling requests. Temporarily disable these tests pending switch to using Azure OpenAI.

dotnet/src/IntegrationTests/README.md
=> .Net: Update the integration tests readme to include instructions for audio tests

python/samples/kernel-syntax-examples/azure_chat_gpt_api.py, python/semantic_kernel/functions/kernel_function.py, python/semantic_kernel/services/ai_service_selector.py
=> Python: fix for using complete_chat

dotnet/samples/KernelSyntaxExamples/Example85_GeminiTextGeneration.cs, dotnet/samples/KernelSyntaxExamples/Example86_GeminiChatCompletion.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI.UnitTests/Settings/GeminiPromptExecutionSettingsTests.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI/Settings/GeminiPromptExecutionSettings.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI/Settings/GeminiSafetySetting.cs
Adjust execution settings to changes in main brach.
Implemented mutability control in GeminiPromptExecutionSettings.
Gemini progress: https://github.com/microsoft/semantic-kernel/issues/4680
@RogerBarreto
=> .Net: Gemini - execution settings mutability control

dotnet/src/Connectors/Connectors.GoogleVertexAI/Core/Gemini/GeminiRequest.cs
Added support for ImageContent BinaryData.
.Net GoogleAI connector progress (Gemini) #4680
@RogerBarreto
=> .Net Gemini/vision binary data

dotnet/samples/KernelSyntaxExamples/Example83_ApiManifest.cs, dotnet/samples/KernelSyntaxExamples/Plugins/ApiManifestPlugins/CalendarPlugin/apimanifest.json, dotnet/samples/KernelSyntaxExamples/Plugins/ApiManifestPlugins/ContactsPlugin/apimanifest.json, dotnet/samples/KernelSyntaxExamples/Plugins/ApiManifestPlugins/DriveItemPlugin/apimanifest.json
These examples were previously blocked by issue #4991
- Adds three more API Manifest plugin examples.
=> .Net: More API Manifest plugin examples from Microsoft Graph

dotnet/src/SemanticKernel.UnitTests/Functions/KernelFunctionUnitTestStrategies.cs
=> .Net: Unit test showing some strategies to unit test kernel functions

java/pom.xml, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/plugins/web/WebSearchEnginePlugin.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example59_OpenAIFunctionCalling.java, java/samples/sample-code/src/main/resources/log4j2.xml, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/Kernel.java, java/semantickernel-bom/pom.xml
=> Java: Fix null check

docs/decisions/0031-feature-branch-strategy.md
While working on the gemini branch, I encountered with @RogerBarreto a problem which is the merge of the main branch to the feature branch. Its incorrect merge generates problems in the form of unreadable history and strange conflicts.
Added clear description to ADR how the main branch should be merged to the feature branch.
=> Update 0031-feature-branch-strategy - merging main

.github/workflows/python-integration-tests.yml, .github/workflows/python-test-coverage.yaml, .github/workflows/python-unit-tests.yml, python/poetry.toml, python/tests/unit/connectors/open_ai/services/test_azure_chat_completion.py
=> Python: updated python tests with cache and added coverage

.github/workflows/python-test-coverage.yaml
=> Python: Enhance py test coverage message

.github/workflows/python-test-coverage.yaml
small update to python test coverage workflow
=> Python: small update to python test coverage workflow

.github/workflows/python-test-coverage.yaml
remove final step of test coverage, causes errors
=> Python: remove final step of test coverage, causes errors

java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIChatCompletion.java, java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIChatMessageContent.java, java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIFunctionToolCall.java, java/api-test/integration-tests/src/test/java/com/microsoft/semantickernel/tests/ToolCallBehaviourTest.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example57_KernelHooks.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/KernelPluginCollection.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/contextvariables/converters/CharacterVariableContextVariableTypeConverter.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/implementation/templateengine/tokenizer/blocks/CodeBlock.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/FunctionInvocation.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/FunctionResult.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/ToolCallBehavior.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionArguments.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionFromMethod.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionFromPrompt.java
=> Java: add ToolCallBehaviour test

java/semantickernel-api/src/main/java/com/microsoft/semantickernel/templateengine/handlebars/HandlebarsPromptTemplate.java, java/semantickernel-api/src/test/java/com/microsoft/semantickernel/templateengine/handlebars/HandlebarsPromptTemplateTest.java
=> Java: Rudimentary HandleBarsPromptTemplateTest

python/samples/documentation_examples/README.md
=> Python: Fix broken link

python/.coveragerc, python/semantic_kernel/planners/action_planner/action_planner.py, python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py
Got a report of a bug in the action planner creation, fixed here.
=> Python: Fix action planner

python/.coveragerc, python/semantic_kernel/connectors/search_engine/bing_connector.py, python/semantic_kernel/connectors/search_engine/connector.py, python/semantic_kernel/connectors/search_engine/google_connector.py, python/semantic_kernel/core_plugins/web_search_engine_plugin.py, python/semantic_kernel/planners/action_planner/action_planner.py, python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py
Update the web search plugin for the new structures, where types can be passed, instead of str everywhere.
=> Python: Improve web search

.vscode/settings.json
=> Revert changes to settings.json

dotnet/samples/KernelSyntaxExamples/Example95_GeminiTextGeneration.cs, dotnet/samples/KernelSyntaxExamples/Example96_GeminiChatCompletion.cs, dotnet/samples/KernelSyntaxExamples/Example97_GeminiVision.cs, dotnet/samples/KernelSyntaxExamples/Example99_GeminiEmbeddingGeneration.cs
Added embedding generation sample.
Fixed samples numbering
example98 is reserved for function calling
#4680
@RogerBarreto
=> .Net: Gemini/embedding sample

dotnet/samples/KernelSyntaxExamples/Example86_ImageToText.cs, dotnet/samples/KernelSyntaxExamples/Example87_ChatHistorySerialization.cs
Example85 was used twice.
Fix samples numbering
=> .Net: Fix samples numbering

java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIChatCompletion.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example57_KernelHooks.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/hooks/KernelHook.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/hooks/KernelHooks.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/hooks/PostChatCompletionEvent.java
Fix：https://github.com/microsoft/semantic-kernel/issues/5314
After the Chat Completion, triggered an PostChatCompletionEvent.
=> Java: feat(): add PostChatCompletionEvent

java/api-test/integration-tests/src/test/java/com/microsoft/semantickernel/tests/KernelHooksTest.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example57_KernelHooks.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example58_ConfigureExecutionSettings.java, java/semantickernel-api/pom.xml, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/PromptExecutionSettings.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/plugin/KernelReturnParameterMetadata.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/InputVariable.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionFromPrompt.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionMetadata.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionYaml.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelParameterMetadata.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/OutputVariable.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/PromptTemplateConfig.java, java/semantickernel-api/src/test/java/com/microsoft/semantickernel/orchestration/PromptExecutionSettingsTest.java, java/semantickernel-api/src/test/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionFromMethodTest.java, java/semantickernel-api/src/test/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionYamlTest.java, java/semantickernel-api/src/test/java/com/microsoft/semantickernel/semanticfunctions/PromptTemplateConfigTest.java, java/semantickernel-api/src/test/java/com/microsoft/semantickernel/semanticfunctions/PromptTemplateFactoryTest.java, java/semantickernel-api/src/test/java/com/microsoft/semantickernel/services/AIServiceSelectorTest.java
=> Java: some unit tests for semanticfunctions and resulting code changes

.github/workflows/python-build-wheel.yml, .github/workflows/python-integration-tests.yml, .github/workflows/python-lint.yml, .github/workflows/python-unit-tests.yml, python/.conf/.pre-commit-config.yaml, python/poetry.lock, python/pyproject.toml, python/semantic_kernel/connectors/openapi/kernel_openapi.py, python/semantic_kernel/functions/kernel_function_from_method.py, python/semantic_kernel/kernel.py
Poetry groups are not the same as pip extras, so I removed the individual groups per service, replaced with the ones needed for unit tests and for integration tests (all).
Then added Extras, for each connector, as well as a `all` extra. Also added a notebooks extra, this can be used instead of the first cell in the notebooks as `pip install -U semantic-kernel[notebooks]` closing #4713 
Made all dependencies part of the main, tagged with optional.
Closes #5322
=> Python: Add extras and minor package updates

dotnet/nuget/nuget-package.props
=> .Net: Update to version 1.6.0

.github/workflows/python-test-coverage.yml, python/samples/documentation_examples/plugins/prompt_flow_helpers/perform_math/requirements.txt
replace py test coverage yml. remove unneeded requirements.txt file from sample plugin
replace py test coverage yml. remove unneeded requirements.txt file from sample plugin
=> Python: replace py test coverage yml. remove unneeded requirements.txt file from sample plugin

dotnet/samples/KernelSyntaxExamples/Example94_GeminiGetModelResult.cs, dotnet/samples/KernelSyntaxExamples/Example95_GeminiTextGeneration.cs, dotnet/samples/KernelSyntaxExamples/Example96_GeminiChatCompletion.cs, dotnet/samples/KernelSyntaxExamples/Example97_GeminiVision.cs, dotnet/samples/KernelSyntaxExamples/Example98_GeminiFunctionCalling.cs, dotnet/samples/KernelSyntaxExamples/Example99_GeminiEmbeddingGeneration.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI/Extensions/VertexAIKernelBuilderExtensions.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI/Extensions/VertexAIMemoryBuilderExtensions.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI/Extensions/VertexAIServiceCollectionExtensions.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI/Services/VertexAIGeminiChatCompletionService.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI/Services/VertexAIGeminiTextGenerationService.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI/Services/VertexAITextEmbeddingGenerationService.cs
A performance-oriented reminder line was added to the bearerKeyProvider method in multiple KernelSyntax example files. This line emphasizes the importance of maintaining speed in the delegate as it's called on every request.
@RogerBarreto
=> .Net Gemini comments adjustment

.vscode/settings.json, python/notebooks/00-getting-started.ipynb, python/notebooks/01-basic-loading-the-kernel.ipynb, python/notebooks/02-running-prompts-from-file.ipynb, python/notebooks/03-prompt-function-inline.ipynb, python/notebooks/04-kernel-arguments-chat.ipynb, python/notebooks/05-using-the-planner.ipynb, python/notebooks/06-memory-and-embeddings.ipynb, python/notebooks/07-hugging-face-for-plugins.ipynb, python/notebooks/08-native-function-inline.ipynb, python/notebooks/09-groundedness-checking.ipynb, python/notebooks/10-multiple-results-per-prompt.ipynb, python/notebooks/11-streaming-completions.ipynb, python/pyproject.toml
Bump python version to 0.9.2b1 for release.
Bump python version to 0.9.2b1 for release.
=> Python: Bump python version to 0.9.2b1 for release.

dotnet/samples/KernelSyntaxExamples/Example94_GeminiGetModelResult.cs, dotnet/samples/KernelSyntaxExamples/Example95_GeminiTextGeneration.cs, dotnet/samples/KernelSyntaxExamples/Example99_GeminiEmbeddingGeneration.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI/Core/ClientBase.cs, dotnet/src/Connectors/Connectors.GoogleVertexAI/Core/Gemini/Clients/GeminiChatCompletionClient.cs
Addresses PR comments from @stephentoub
=> .Net: Gemini/update1

dotnet/nuget/nuget-package.props
=> .Net: Bump to version 1.6.2

.vscode/settings.json
=> Update deprecated property values

dotnet/samples/KernelSyntaxExamples/Example76_Filters.cs, dotnet/samples/KernelSyntaxExamples/Example79_ChatCompletionAgent.cs
=> .Net: These two examples should be in the Examples namespace

java/semantickernel-api/pom.xml, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/implementation/EmbeddedResourceLoader.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/plugin/KernelPluginFactory.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionFromMethod.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/annotations/DefineKernelFunction.java, java/semantickernel-api/src/test/java/com/microsoft/semantickernel/plugin/KernelPluginFactoryTest.java, java/semantickernel-api/src/test/resources/Plugins/ExamplePlugins/ExampleFunction/config.json, java/semantickernel-api/src/test/resources/Plugins/ExamplePlugins/ExampleFunction/skprompt.txt
=> Java: Add KernelPluginFactoryTest

dotnet/nuget/nuget-package.props
=> .Net: Version 1.6.3

java/PACKAGES.md, java/README.md
=> Java: Update readme

java/semantickernel-api/src/main/java/com/microsoft/semantickernel/services/chatcompletion/ChatHistory.java
=> Java: Allow creating empty ChatHistory

dotnet/nuget/nuget-package.props
=> .Net: Baseline 1.6.3

dotnet/samples/KernelSyntaxExamples/Example14_SemanticMemory.cs
=> .Net: Update Example14_SemanticMemory.cs

dotnet/src/Connectors/Connectors.OpenAI/ChatCompletionWithData/AzureOpenAIChatCompletionWithDataConfig.cs, dotnet/src/Connectors/Connectors.OpenAI/ChatCompletionWithData/AzureOpenAIChatCompletionWithDataService.cs, dotnet/src/Connectors/Connectors.OpenAI/TextToImage/AzureOpenAITextToImageService.cs, dotnet/src/Connectors/Connectors.UnitTests/OpenAI/ChatCompletionWithData/AzureOpenAIChatCompletionWithDataTests.cs
=> .Net: Upgrade to completion API version 2024-02-01

dotnet/samples/KernelSyntaxExamples/Example98_GeminiFunctionCalling.cs, dotnet/src/Connectors/Connectors.Google.UnitTests/Core/Gemini/Clients/GeminiChatGenerationFunctionCallingTests.cs, dotnet/src/Connectors/Connectors.Google.UnitTests/Core/Gemini/Clients/GeminiChatStreamingFunctionCallingTests.cs, dotnet/src/Connectors/Connectors.Google.UnitTests/GeminiToolCallBehaviorTests.cs, dotnet/src/Connectors/Connectors.Google/GeminiPromptExecutionSettings.cs, dotnet/src/Connectors/Connectors.Google/GeminiToolCallBehavior.cs, dotnet/src/IntegrationTests/Connectors/GoogleVertexAI/Gemini/GeminiFunctionCallingTests.cs
=> .Net: Rename ToolCallBehavior class to GeminiToolCallBehavior

dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs, dotnet/src/Connectors/Connectors.OpenAI/OpenAIPromptExecutionSettings.cs, dotnet/src/Connectors/Connectors.UnitTests/OpenAI/ChatCompletion/OpenAIChatCompletionServiceTests.cs, dotnet/src/Connectors/Connectors.UnitTests/OpenAI/OpenAIPromptExecutionSettingsTests.cs, dotnet/src/SemanticKernel.UnitTests/Functions/KernelFunctionFromPromptTests.cs, dotnet/src/SemanticKernel.UnitTests/PromptTemplate/PromptTemplateConfigTests.cs
=> .Net: Remove default chat system prompt

dotnet/samples/KernelSyntaxExamples/KernelSyntaxExamples.csproj
Fixes the following build errors
=> .Net: Feature connectors Ollama build fix

docs/decisions/0036-semantic-kernel-release-versioning.md
=> Add some guidance on using version suffixes

java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/documentationexamples/AIServices.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/documentationexamples/ConfiguringPrompts.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/documentationexamples/FunctionsWithinPrompts.java
Updates to documentationexamples to add xml tags for referencing in Microsoft learn markdown
=> Java: use id instead of range in markdown

java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIChatCompletion.java, java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/XMLPromptParser.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/documentationexamples/SerializingPrompts.java, java/samples/semantickernel-spring-starter/pom.xml, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/contextvariables/ContextVariable.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/contextvariables/ContextVariableTypeConverter.java
=> Java: Tidy up and add Javadocs

java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/documentationexamples/ConfiguringPrompts.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/documentationexamples/Prompts.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/plugins/PromptFunctionConstants.java
=> Java: Fix some Doc fixes

java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/documentationexamples/Prompts.java
=> Java: Disable formatter on Prompts

python/notebooks/00-getting-started.ipynb, python/notebooks/01-basic-loading-the-kernel.ipynb, python/notebooks/02-running-prompts-from-file.ipynb, python/notebooks/03-prompt-function-inline.ipynb, python/notebooks/04-kernel-arguments-chat.ipynb, python/notebooks/05-using-the-planner.ipynb, python/notebooks/06-memory-and-embeddings.ipynb, python/notebooks/07-hugging-face-for-plugins.ipynb, python/notebooks/08-native-function-inline.ipynb, python/notebooks/09-groundedness-checking.ipynb, python/notebooks/10-multiple-results-per-prompt.ipynb, python/notebooks/11-streaming-completions.ipynb, python/pyproject.toml
Bump versions to 0.9.5b1 for release.
Bump versions to 0.9.5b1 for release.
=> Python: Bump versions to 0.9.5b1 for release.

dotnet/src/Functions/Functions.OpenApi.Extensions/Functions.OpenApi.Extensions.csproj
- `Microsoft.SemanticKernel.Plugins.OpenApi.Extensions` package contains kernel extensions for ApiManifest based plugins.
- Changes: https://github.com/microsoft/semantic-kernel/pulls?q=is%3Apr+author%3Azengin+is%3Aclosed+created%3A%3E2024-01-01+merged%3A%3C2024-04-02+
- Version suffix is `alpha` (in sync with `Microsoft.SemanticKernel.Plugins.OpenApi` package)
cc: @matthewbolanos @SergeyMenshykh @markwallace-microsoft
=> .Net: Publish Microsoft.SemanticKernel.Plugins.OpenApi.Extensions package

dotnet/samples/KernelSyntaxExamples/MistralAI/MistralAI_Chat_Prompt.cs, dotnet/samples/KernelSyntaxExamples/MistralAI/MistralAI_Function_Calling.cs
Adding a new function calling sample
=> .Net: Update MistralAI kernel syntax samples

python/.vscode/tasks.json, python/DEV_SETUP.md, python/README.md
This pull request primarily updates the `DEV_SETUP.md` and `README.md` files in the `python` directory. The changes focus on improving the setup instructions, updating the code snippets, and providing additional information on running tests, code coverage, and keeping the local repository up-to-date. 
Changes to setup instructions:
* [`python/DEV_SETUP.md`](diffhunk://#diff-22a026622159be328328c5bb6fef874e8aa799efb6ab8844d0c94ad051b08f3cR75-R90): Added instructions on how to use Python 3.11 with Poetry, how to install pre-commit hooks, and how to run tests using VSCode Tasks. [[1]](diffhunk://#diff-22a026622159be328328c5bb6fef874e8aa799efb6ab8844d0c94ad051b08f3cR75-R90) [[2]](diffhunk://#diff-22a026622159be328328c5bb6fef874e8aa799efb6ab8844d0c94ad051b08f3cR112-R114) …
=> Python: dev_setup and readme updates

java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIChatCompletion.java
=> Java: Add header for chat completion requests

dotnet/nuget/nuget-package.props
=> .Net: Bump version to 1.7.1

.github/workflows/python-integration-tests.yml
=> Python: remove path

java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIChatCompletion.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/InvocationContext.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/PromptExecutionSettings.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/ResponseFormat.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionFromPrompt.java
=> Java: Add support for response_format on chat completion

dotnet/samples/KernelSyntaxExamples/Example100_FunctionCallingPlannerWithPromptFunctions.cs, dotnet/samples/KernelSyntaxExamples/Example80_FunctionCallingPlannerWithRAG.cs, dotnet/src/Planners/Planners.OpenAI/Stepwise/FunctionCallingStepwisePlanner.cs
Also includes a fix so the planner handles errors in the final answer correctly.
Closes #4679
=> .Net: Add new kernel syntax sample which shows function calling planner with RAG

java/semantickernel-api/pom.xml, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/contextvariables/ContextVariableTypeConverter.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/contextvariables/converters/ChatHistoryVariableContextVariableTypeConverter.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/contextvariables/converters/CollectionVariableContextVariableTypeConverter.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/contextvariables/converters/PrimitiveVariableContextVariableTypeConverter.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/contextvariables/converters/StringVariableContextVariableTypeConverter.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/contextvariables/converters/TextContentVariableContextVariableTypeConverter.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/PromptExecutionSettings.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/templateengine/handlebars/HandlebarsPromptTemplate.java, java/semantickernel-bom/pom.xml
=> Java: Fix chat message parsing

COMMUNITY.md
Initial update to community office hours
=> community office hours

.editorconfig, dotnet/Directory.Packages.props, dotnet/src/Agents/Abstractions/ChatHistoryChannel.cs, dotnet/src/Connectors/Connectors.Memory.Pinecone/Model/PodType.cs
Fixes https://github.com/microsoft/semantic-kernel/issues/5835
=> .Net: Fix a few straggler warnings from recently updated analyzers

dotnet/Directory.Packages.props, dotnet/samples/KernelSyntaxExamples/Getting_Started/Step2_Add_Plugins.cs
=> .Net: Extend plugins sample to demonstrate the use of enums

.github/workflows/python-lint.yml
Adds mypy checks to the linters
Renamed lint to code quality checks
=> Python: add mypy to python lint checks

.github/workflows/python-lint.yml
=> Python: fix lint mypy

java/samples/booking-agent-m365/pom.xml, java/samples/booking-agent-m365/src/main/java/com/microsoft/semantickernel/BookingAgent.java, java/samples/booking-agent-m365/src/main/java/com/microsoft/semantickernel/BookingPlugin.java, java/samples/booking-agent-m365/src/main/resources/log4j2.xml, java/samples/pom.xml
=> Java: Add booking sample with M365 booking system

dotnet/samples/KernelSyntaxExamples/Example57_KernelHooks.cs, dotnet/samples/KernelSyntaxExamples/Getting_Started/Step7_Observability.cs, dotnet/src/SemanticKernel.Abstractions/Functions/KernelFunction.cs, dotnet/src/SemanticKernel.Abstractions/Kernel.cs, dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromPrompt.cs, dotnet/src/SemanticKernel.Core/Functions/PromptRenderingResult.cs, dotnet/src/SemanticKernel.UnitTests/Functions/FunctionFromMethodTests.cs, dotnet/src/SemanticKernel.UnitTests/Functions/KernelFunctionFromPromptTests.cs, dotnet/src/SemanticKernel.UnitTests/KernelTests.cs
Temporary reverted hooks while filters are experimental.
=> .Net: [Feature Branch] Reverted hooks

java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIChatCompletion.java, java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIFunction.java, java/api-test/integration-tests/src/test/java/com/microsoft/semantickernel/tests/RenderingTest.java, java/api-test/integration-tests/src/test/java/com/microsoft/semantickernel/tests/ToolCallBehaviourTest.java, java/samples/pom.xml, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/documentationexamples/ConfiguringPrompts.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example17_ChatGPT.java, java/samples/semantickernel-openapi-plugin/pom.xml, java/samples/semantickernel-openapi-plugin/src/main/java/com/microsoft/semantickernel/samples/openapi/OpenAPIHttpRequestPlugin.java, java/samples/semantickernel-openapi-plugin/src/main/java/com/microsoft/semantickernel/samples/openapi/SemanticKernelOpenAPIImporter.java, java/samples/semantickernel-openapi-plugin/src/test/java/ExampleAdoptiumImporter.java, java/samples/semantickernel-openapi-plugin/src/test/java/ExampleOpenAPIParent.java, java/samples/semantickernel-openapi-plugin/src/test/java/ExamplePetstoreImporter.java, java/samples/semantickernel-openapi-plugin/src/test/resources/adoptium.json, java/samples/semantickernel-openapi-plugin/src/test/resources/adoptium.yaml, java/samples/semantickernel-openapi-plugin/src/test/resources/petstore.yaml, java/semantickernel-api/pom.xml, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/hooks/KernelHook.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/hooks/KernelHooks.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/hooks/PreToolCallEvent.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/FunctionInvocation.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/plugin/KernelPluginFactory.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/InputVariable.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionFromMethod.java, java/semantickernel-api/src/test/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionFromMethodTest.java, java/semantickernel-api/src/test/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionYamlTest.java, java/semantickernel-api/src/test/java/com/microsoft/semantickernel/semanticfunctions/PromptTemplateConfigTest.java, java/semantickernel-api/src/test/java/com/microsoft/semantickernel/semanticfunctions/PromptTemplateFactoryTest.java, java/semantickernel-bom/pom.xml
=> Java: Add OpenApi plugin importer and upgrade tool calling to cover more usecases

java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/OpenAiService.java, java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/audio/OpenAiAudioToTextService.java, java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/audio/OpenAiTextToAudioService.java, java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIChatCompletion.java, java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/textcompletion/OpenAITextGenerationService.java, java/aiservices/openai/src/main/resources/META-INF/services/com.microsoft.semantickernel.services.audio.AudioToTextService$Builder, java/aiservices/openai/src/main/resources/META-INF/services/com.microsoft.semantickernel.services.audio.TextToAudioService$Builder, java/pom.xml, java/samples/booking-agent-m365/src/main/java/com/microsoft/semantickernel/BookingAgent.java, java/samples/booking-agent-m365/src/main/java/com/microsoft/semantickernel/BookingPlugin.java, java/samples/pom.xml, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example59_OpenAIFunctionCalling.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example82_Audio.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/contextvariables/ContextVariable.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/contextvariables/ContextVariableTypeConverter.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/contextvariables/ContextVariableTypes.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/hooks/PreToolCallEvent.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionArguments.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/services/audio/AudioContent.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/services/audio/AudioToTextExecutionSettings.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/services/audio/AudioToTextService.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/services/audio/TextToAudioExecutionSettings.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/services/audio/TextToAudioService.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/services/chatcompletion/ChatCompletionService.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/services/openai/OpenAiServiceBuilder.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/services/textcompletion/TextGenerationService.java, java/semantickernel-bom/pom.xml
=> Java: Add OpenAI Audio to/from Text services

dotnet/Directory.Packages.props, dotnet/samples/KernelSyntaxExamples/MistralAI/MistralAI_Chat_Prompt.cs, dotnet/samples/KernelSyntaxExamples/MistralAI/MistralAI_Function_Calling.cs, dotnet/samples/KernelSyntaxExamples/MistralAI/MistralAI_Streaming_Function_Calling.cs, dotnet/src/Connectors/Connectors.MistralAI.UnitTests/Client/MistralClientTests.cs, dotnet/src/Connectors/Connectors.MistralAI.UnitTests/TestData/chat_completions_streaming_function_call_response.txt, dotnet/src/Connectors/Connectors.MistralAI.UnitTests/TestData/chat_completions_streaming_function_called_response.txt, dotnet/src/Connectors/Connectors.MistralAI.UnitTests/TestData/function_call_response.json, dotnet/src/Connectors/Connectors.MistralAI/Client/MistralChatCompletionChoice.cs, dotnet/src/Connectors/Connectors.MistralAI/Client/MistralChatCompletionChunk.cs, dotnet/src/Connectors/Connectors.MistralAI/Client/MistralChatMessage.cs, dotnet/src/Connectors/Connectors.MistralAI/Client/MistralClient.cs, dotnet/src/Connectors/Connectors.MistralAI/Client/MistralFunction.cs, dotnet/src/Connectors/Connectors.MistralAI/Client/MistralParameters.cs, dotnet/src/Connectors/Connectors.MistralAI/Client/MistralToolCall.cs
=> .Net: Add basic support for streaming with function calling

dotnet/nuget/nuget-package.props
Bumping version number for a new release
=> .Net: Bump to version 1.8.0

dotnet/samples/KernelSyntaxExamples/Example55_TextChunker.cs, dotnet/samples/KernelSyntaxExamples/Example81_TextEmbedding.cs, dotnet/samples/KernelSyntaxExamples/KernelSyntaxExamples.csproj
Microsoft.ML.Tokenizers is our recommended library for tokenization with tiktoken.
=> .Net: Cleanup tokenizer examples

java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIChatCompletion.java, java/api-test/integration-tests/src/test/java/com/microsoft/semantickernel/tests/RenderingTest.java, java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example09_FunctionTypes.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionFromMethod.java
=> Java: Fix required tool call being requested multiple times

dotnet/nuget/nuget-package.props
=> .Net: Version 1.10.0

dotnet/samples/Concepts/Agents/MixedChat_Agents.cs, dotnet/samples/GettingStartedWithAgents/Step4_KernelFunctionStrategies.cs
[Step4_KernelFunctionStrategies](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/GettingStartedWithAgents/Step4_KernelFunctionStrategies.cs) was either:
1. Failing with null selection
2. Exceeding model token limit
3. Not performing the requested task
A couple things at play here:
1. The selection prompt was copied from AutoGen.  While it worked on `GPT-4`, it wasn't generating a reliable result for `GPT-3.5-Turbo`
2. The agent instructions were never tuned outsidre of `GPT-4`
3. No sensible default / fall-through (can't trust model 100%)
4. 4k token limit may be too low for history evaluation.  Tested with `gpt-35-turbo-16k`
> Note: When formal support for history manipulation comes on line, we should be able to optimize around last(n) messages.
=> .Net: Agents - Getting Started Step4 Improvement: Cross Model

java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIChatCompletion.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionFromMethod.java
=> Java: Fix null warnings

dotnet/src/Extensions/PromptTemplates.Liquid.UnitTests/LiquidTemplateTest.cs, dotnet/src/Extensions/PromptTemplates.Liquid/LiquidPromptTemplate.cs, dotnet/src/Functions/Functions.Prompty.UnitTests/PromptyTest.cs, dotnet/src/Functions/Functions.Prompty.UnitTests/TestData/chat.prompty, dotnet/src/Functions/Functions.Prompty.UnitTests/TestData/chatNoExecutionSettings.prompty, dotnet/src/Functions/Functions.Prompty/Extensions/PromptyKernelExtensions.cs
=> .Net:  fix #6033: Add more tests and comments

dotnet/samples/Concepts/Memory/SemanticTextMemory_Building.cs, dotnet/samples/Demos/TelemetryWithAppInsights/RepoUtils/RepoFiles.cs, dotnet/src/IntegrationTests/TestHelpers.cs, dotnet/src/InternalUtilities/samples/InternalUtilities/RepoFiles.cs, dotnet/src/SemanticKernel.Core/KernelExtensions.cs
Fixed integration tests by updating link to plugins folder based on changes in this PR: https://github.com/microsoft/semantic-kernel/pull/6116
=> .Net: Fixed integration tests

dotnet/nuget/nuget-package.props
=> .Net: Version 1.11.0

dotnet/samples/Concepts/Caching/SemanticCachingWithFilters.cs, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBConfig.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBMongoDB/AzureCosmosDBMongoDBMemoryStoreTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBMongoDB/AzureCosmosDBMongoDBMemoryStoreTestsFixture.cs
=> .Net: Improvements for Azure Cosmos DB for MongoDB connector

.vscode/settings.json, dotnet/samples/Concepts/README.md
=> .Net: Update Concepts README for new Prompt samples

python/pyproject.toml, python/samples/getting_started/00-getting-started.ipynb, python/samples/getting_started/01-basic-loading-the-kernel.ipynb, python/samples/getting_started/02-running-prompts-from-file.ipynb, python/samples/getting_started/03-prompt-function-inline.ipynb, python/samples/getting_started/04-kernel-arguments-chat.ipynb, python/samples/getting_started/05-using-the-planner.ipynb, python/samples/getting_started/06-memory-and-embeddings.ipynb, python/samples/getting_started/07-hugging-face-for-plugins.ipynb, python/samples/getting_started/08-native-function-inline.ipynb, python/samples/getting_started/09-groundedness-checking.ipynb, python/samples/getting_started/10-multiple-results-per-prompt.ipynb, python/samples/getting_started/11-streaming-completions.ipynb, python/samples/getting_started/third_party/weaviate-persistent-memory.ipynb
Bump Python version to 0.9.8b1 for a release.
Bump Python version to 0.9.8b1 for a release.
=> Python: Bump Python version to 0.9.8b1 for a release.

dotnet/src/Connectors/Connectors.OpenAI/CompatibilitySuppressions.xml, dotnet/src/Connectors/Connectors.OpenAI/OpenAIServiceCollectionExtensions.cs, dotnet/src/Connectors/Connectors.OpenAI/TextEmbedding/OpenAITextEmbeddingGenerationService.cs
Fixes: https://github.com/microsoft/semantic-kernel/issues/6182
=> .Net: Added dimensions property to OpenAI embedding service constructor

dotnet/nuget/nuget-package.props
Creating a patch release which includes the MongoDB fixes
=> .Net: Version 1.11.1

.github/workflows/java-integration-tests.yml, java/api-test/pom.xml, java/pom.xml
=> Java: Skip spotless on Java 8

dotnet/src/Connectors/Connectors.MistralAI/MistralAIPromptExecutionSettings.cs, dotnet/src/Connectors/Connectors.MistralAI/MistralAIToolCallBehavior.cs, dotnet/src/IntegrationTests/Connectors/MistralAI/ChatCompletion/MistralAIChatCompletionTests.cs
=> .Net: Add support for tool choice none and any

python/tests/unit/functions/test_kernel_function_from_method.py
the question arose whether a lambda function can work, it does, with the right syntax, added as a test.
=> Python: add test to show using a lambda func

dotnet/samples/Concepts/ChatPrompts/SafeChatPrompts.cs, dotnet/src/Extensions/Extensions.UnitTests/PromptTemplates/Handlebars/HandlebarsPromptTemplateTests.cs, dotnet/src/Extensions/PromptTemplates.Handlebars/CompatibilitySuppressions.xml, dotnet/src/Extensions/PromptTemplates.Handlebars/HandlebarsPromptTemplate.cs, dotnet/src/Extensions/PromptTemplates.Handlebars/HandlebarsPromptTemplateFactory.cs, dotnet/src/Extensions/PromptTemplates.Handlebars/Helpers/KernelHelpers/KernelFunctionHelpers.cs, dotnet/src/Extensions/PromptTemplates.Liquid.UnitTests/LiquidTemplateTest.cs, dotnet/src/Extensions/PromptTemplates.Liquid/LiquidPromptTemplate.cs, dotnet/src/Extensions/PromptTemplates.Liquid/LiquidPromptTemplateFactory.cs, dotnet/src/SemanticKernel.Abstractions/CompatibilitySuppressions.xml, dotnet/src/SemanticKernel.Abstractions/PromptTemplate/InputVariable.cs, dotnet/src/SemanticKernel.Abstractions/PromptTemplate/PromptTemplateConfig.cs, dotnet/src/SemanticKernel.Core/CompatibilitySuppressions.xml, dotnet/src/SemanticKernel.Core/PromptTemplate/KernelPromptTemplate.cs, dotnet/src/SemanticKernel.Core/PromptTemplate/KernelPromptTemplateFactory.cs, dotnet/src/SemanticKernel.UnitTests/PromptTemplate/KernelPromptTemplateTests.cs, python/tests/unit/functions/test_kernel_function_from_method.py
=> .Net: Rename to AllowDangerouslySetContent

dotnet/notebooks/00-getting-started.ipynb, dotnet/notebooks/01-basic-loading-the-kernel.ipynb, dotnet/notebooks/02-running-prompts-from-file.ipynb, dotnet/notebooks/03-semantic-function-inline.ipynb, dotnet/notebooks/04-kernel-arguments-chat.ipynb, dotnet/notebooks/05-using-the-planner.ipynb, dotnet/notebooks/06-memory-and-embeddings.ipynb, dotnet/notebooks/07-DALL-E-3.ipynb, dotnet/notebooks/08-chatGPT-with-DALL-E-3.ipynb, dotnet/notebooks/09-memory-with-chroma.ipynb, dotnet/notebooks/10-BingSearch-using-kernel.ipynb
Resolves: https://github.com/microsoft/semantic-kernel/issues/6247
Fixed path issues and updated `Microsoft.SemanticKernel` version to `1.11.1`.
=> .Net: Updated notebooks

java/samples/semantickernel-demos/booking-agent-m365/src/main/java/com/microsoft/semantickernel/BookingAgent.java, java/samples/semantickernel-demos/booking-agent-m365/src/main/java/com/microsoft/semantickernel/BookingPlugin.java, java/samples/semantickernel-demos/booking-agent-m365/src/main/resources/log4j2.xml
=> Java: Add customer information to reservations

python/pyproject.toml, python/samples/getting_started/00-getting-started.ipynb, python/samples/getting_started/01-basic-loading-the-kernel.ipynb, python/samples/getting_started/02-running-prompts-from-file.ipynb, python/samples/getting_started/03-prompt-function-inline.ipynb, python/samples/getting_started/04-kernel-arguments-chat.ipynb, python/samples/getting_started/05-using-the-planner.ipynb, python/samples/getting_started/06-memory-and-embeddings.ipynb, python/samples/getting_started/07-hugging-face-for-plugins.ipynb, python/samples/getting_started/08-native-function-inline.ipynb, python/samples/getting_started/09-groundedness-checking.ipynb, python/samples/getting_started/10-multiple-results-per-prompt.ipynb, python/samples/getting_started/11-streaming-completions.ipynb, python/samples/getting_started/third_party/weaviate-persistent-memory.ipynb
Bump python version to 0.9.9b1 for release.
Bump python version to 0.9.9b1 for release.
=> Python: Bump python version to 0.9.9b1 for release.

dotnet/nuget/nuget-package.props
=> .Net: Bump version to 1.12.0

dotnet/samples/Demos/TelemetryWithAppInsights/Program.cs, dotnet/samples/Demos/TelemetryWithAppInsights/README.md, dotnet/samples/Demos/TelemetryWithAppInsights/TelemetryWithAppInsights.csproj, dotnet/samples/Demos/TelemetryWithAppInsights/TestConfiguration.cs
=> .Net: Add MistralAI to the AppInsights sample

java/CHANGELOG.md, java/api-test/integration-tests/src/test/java/com/microsoft/semantickernel/tests/ToolCallBehaviourTest.java, java/api-test/integration-tests/src/test/resources/wiremock/mappings/deployments_gpt-35-turbo-2_chat_completions-12b6744e-443f-4fe7-82e2-55cc41195ff1.json, java/api-test/integration-tests/src/test/resources/wiremock/mappings/deployments_gpt-35-turbo-2_chat_completions-71b07779-49a8-44e5-a60b-ee5b0a3ad697.json, java/api-test/integration-tests/src/test/resources/wiremock/mappings/deployments_gpt-35-turbo_chat_completions-0c8046c5-74ad-4836-8aa9-09da60f367a2.json, java/api-test/integration-tests/src/test/resources/wiremock/mappings/deployments_text-davinci-003_completions-0215b128-4822-4368-ac3d-2f580a221f00.json, java/pom.xml, java/samples/semantickernel-demos/booking-agent-m365/src/main/java/com/microsoft/semantickernel/BookingPlugin.java
=> Java: Upgrade azure-ai-openai to 1.0.0-beta.8

java/CHANGELOG.md, java/semantickernel-bom/pom.xml
=> Java: Upgrade azure-identity to 1.12.1

python/pyproject.toml, python/samples/getting_started/00-getting-started.ipynb, python/samples/getting_started/01-basic-loading-the-kernel.ipynb, python/samples/getting_started/02-running-prompts-from-file.ipynb, python/samples/getting_started/03-prompt-function-inline.ipynb, python/samples/getting_started/04-kernel-arguments-chat.ipynb, python/samples/getting_started/05-using-the-planner.ipynb, python/samples/getting_started/06-memory-and-embeddings.ipynb, python/samples/getting_started/07-hugging-face-for-plugins.ipynb, python/samples/getting_started/08-native-function-inline.ipynb, python/samples/getting_started/09-groundedness-checking.ipynb, python/samples/getting_started/10-multiple-results-per-prompt.ipynb, python/samples/getting_started/11-streaming-completions.ipynb, python/samples/getting_started/third_party/weaviate-persistent-memory.ipynb
Python: Bump version to 1.0.0rc1.
Python: Bump version to 1.0.0rc1.
=> Python: Bump version to 1.0.0rc1.

dotnet/nuget/nuget-package.props
=> .Net: Bump version to 1.13.0

java/CHANGELOG.md, java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIChatCompletion.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/exceptions/SKCheckedException.java, java/semantickernel-api/src/main/java/com/microsoft/semantickernel/exceptions/SKException.java
=> Java: Fix #6325 and #6273

python/pyproject.toml, python/samples/getting_started/00-getting-started.ipynb, python/samples/getting_started/01-basic-loading-the-kernel.ipynb, python/samples/getting_started/02-running-prompts-from-file.ipynb, python/samples/getting_started/03-prompt-function-inline.ipynb, python/samples/getting_started/04-kernel-arguments-chat.ipynb, python/samples/getting_started/05-using-the-planner.ipynb, python/samples/getting_started/06-memory-and-embeddings.ipynb, python/samples/getting_started/07-hugging-face-for-plugins.ipynb, python/samples/getting_started/08-native-function-inline.ipynb, python/samples/getting_started/09-groundedness-checking.ipynb, python/samples/getting_started/10-multiple-results-per-prompt.ipynb, python/samples/getting_started/11-streaming-completions.ipynb, python/samples/getting_started/third_party/weaviate-persistent-memory.ipynb
Bump Python version to v1.0.0
Bump Python version to v1.0.0
=> Python: Bump Python version to v1.0.0

python/semantic_kernel/functions/kernel_function_decorator.py, python/tests/unit/core_plugins/test_text_memory_plugin.py, python/tests/unit/core_plugins/test_text_plugin.py, python/tests/unit/functions/test_kernel_function_decorators.py, python/tests/unit/functions/test_kernel_function_from_method.py
There was an issue when you create a function with multiple arguments, some with a default.
Improved the parsing of the function, using py3.10 specific features.
Closes #6311
=> Python: update for kernel function decorator defaults

python/pyproject.toml, python/samples/getting_started/00-getting-started.ipynb, python/samples/getting_started/01-basic-loading-the-kernel.ipynb, python/samples/getting_started/02-running-prompts-from-file.ipynb, python/samples/getting_started/03-prompt-function-inline.ipynb, python/samples/getting_started/04-kernel-arguments-chat.ipynb, python/samples/getting_started/05-using-the-planner.ipynb, python/samples/getting_started/06-memory-and-embeddings.ipynb, python/samples/getting_started/07-hugging-face-for-plugins.ipynb, python/samples/getting_started/08-native-function-inline.ipynb, python/samples/getting_started/09-groundedness-checking.ipynb, python/samples/getting_started/10-multiple-results-per-prompt.ipynb, python/samples/getting_started/11-streaming-completions.ipynb, python/samples/getting_started/third_party/weaviate-persistent-memory.ipynb
Bump Python version to 1.0.1 for a release.
Bump Python version to 1.0.1 for a release.
=> Python: Bump Python version to 1.0.1 for a release.

python/pyproject.toml, python/samples/getting_started/00-getting-started.ipynb, python/samples/getting_started/01-basic-loading-the-kernel.ipynb, python/samples/getting_started/02-running-prompts-from-file.ipynb, python/samples/getting_started/03-prompt-function-inline.ipynb, python/samples/getting_started/04-kernel-arguments-chat.ipynb, python/samples/getting_started/05-using-the-planner.ipynb, python/samples/getting_started/06-memory-and-embeddings.ipynb, python/samples/getting_started/07-hugging-face-for-plugins.ipynb, python/samples/getting_started/08-native-function-inline.ipynb, python/samples/getting_started/09-groundedness-checking.ipynb, python/samples/getting_started/10-multiple-results-per-prompt.ipynb, python/samples/getting_started/11-streaming-completions.ipynb, python/samples/getting_started/third_party/weaviate-persistent-memory.ipynb
Bump Python version to 1.0.3 for a release.
Bump Python version to 1.0.3 for a release.
=> Python: Bump Python version to 1.0.3 for a release.

python/tests/unit/connectors/hugging_face/test_hf_text_completions.py
Add unit tests for Hugging Face text completions.
=> Python: added hugging face unit test

.github/workflows/python-samples-tests.yml
Add a workflow, triggered by dispatch and schedule to test the samples.
=> Python: add samples workflow

python/DEV_SETUP.md
Poetry can sometimes be tricky to install for MacOS users. Including further instructions about how to get started, hopefully more quickly.
Including notes for MacOS users to install Poetry from their official installer as well as the possible need to create a `python` alias in the MacOS shell config.
=> Python: Improve DEV_SETUP.md Poetry install instructions for MacOS users.

python/semantic_kernel/connectors/search_engine/bing_connector.py
[PR 6278](https://github.com/microsoft/semantic-kernel/pull/6278) added support for Bing Custom Search, but had a bug introduced when merging a change to how settings worked. 
This PR fixes the bug in how settings are referenced.
=> Python: Fix Bing Connector Setting Usage

dotnet/nuget/nuget-package.props
=> .Net: Version 1.14.0

python/semantic_kernel/connectors/ai/open_ai/prompt_execution_settings/azure_chat_prompt_execution_settings.py
Fix for an issue where Azure AI search packages where needed for core behavior.
=> Python: import fix for azure ai search settings in chat

dotnet/nuget/nuget-package.props
=> .Net: Version 1.14.1

dotnet/samples/Concepts/FunctionCalling/OpenAI_FunctionCalling.cs
Found these issues while investigating #6634
=> .Net: Minor clean-up of sample

java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/implementation/OpenAIRequestSettings.java
=> Java: Add setting for UserAgent

dotnet/samples/Demos/CodeInterpreterPlugin/README.md, dotnet/src/Plugins/Plugins.Core/CodeInterpreter/SessionsPythonPlugin.cs
=> .Net Add version to CodeInterpreter API Calls

.github/workflows/python-lint.yml
=> Python: fix lint

python/samples/concepts/plugins/openai_plugin_azure_key_vault.py
=> Python: fix for backslash

python/pyproject.toml, python/samples/getting_started/00-getting-started.ipynb, python/samples/getting_started/01-basic-loading-the-kernel.ipynb, python/samples/getting_started/02-running-prompts-from-file.ipynb, python/samples/getting_started/03-prompt-function-inline.ipynb, python/samples/getting_started/04-kernel-arguments-chat.ipynb, python/samples/getting_started/05-using-the-planner.ipynb, python/samples/getting_started/06-memory-and-embeddings.ipynb, python/samples/getting_started/07-hugging-face-for-plugins.ipynb, python/samples/getting_started/08-native-function-inline.ipynb, python/samples/getting_started/09-groundedness-checking.ipynb, python/samples/getting_started/10-multiple-results-per-prompt.ipynb, python/samples/getting_started/11-streaming-completions.ipynb, python/samples/getting_started/third_party/weaviate-persistent-memory.ipynb
Bump Python version to 1.1.0 for a release.
Bump Python version to 1.1.0 for a release.
=> Python: Bump Python version to 1.1.0 for a release.

python/pyproject.toml, python/samples/getting_started/00-getting-started.ipynb, python/samples/getting_started/01-basic-loading-the-kernel.ipynb, python/samples/getting_started/02-running-prompts-from-file.ipynb, python/samples/getting_started/03-prompt-function-inline.ipynb, python/samples/getting_started/04-kernel-arguments-chat.ipynb, python/samples/getting_started/05-using-the-planner.ipynb, python/samples/getting_started/06-memory-and-embeddings.ipynb, python/samples/getting_started/07-hugging-face-for-plugins.ipynb, python/samples/getting_started/08-native-function-inline.ipynb, python/samples/getting_started/09-groundedness-checking.ipynb, python/samples/getting_started/10-multiple-results-per-prompt.ipynb, python/samples/getting_started/11-streaming-completions.ipynb, python/samples/getting_started/third_party/weaviate-persistent-memory.ipynb
Bump Python version to 1.1.1 for a release.
Bump Python version to 1.1.1 for a release.
=> Python: Bump Python version to 1.1.1 for a release.

dotnet/src/Connectors/Connectors.Google.UnitTests/Core/Gemini/Clients/GeminiChatGenerationTests.cs, dotnet/src/Connectors/Connectors.Google.UnitTests/Core/Gemini/Clients/GeminiChatStreamingTests.cs, dotnet/src/Connectors/Connectors.Google.UnitTests/Core/Gemini/Clients/GeminiCountingTokensTests.cs, dotnet/src/Connectors/Connectors.Google.UnitTests/Core/VertexAI/VertexAIClientEmbeddingsGenerationTests.cs, dotnet/src/Connectors/Connectors.Google.UnitTests/Extensions/VertexAIMemoryBuilderExtensionsTests.cs, dotnet/src/Connectors/Connectors.Google.UnitTests/Extensions/VertexAIServiceCollectionExtensionsTests.cs, dotnet/src/Connectors/Connectors.Google.UnitTests/Services/VertexAIGeminiChatCompletionServiceTests.cs, dotnet/src/Connectors/Connectors.Google.UnitTests/Services/VertexAITextEmbeddingGenerationServiceTests.cs, dotnet/src/Connectors/Connectors.Google/Connectors.Google.csproj, dotnet/src/Connectors/Connectors.Google/Core/ClientBase.cs, dotnet/src/Connectors/Connectors.Google/Core/Gemini/Clients/GeminiChatCompletionClient.cs, dotnet/src/Connectors/Connectors.Google/Core/Gemini/Clients/GeminiTokenCounterClient.cs, dotnet/src/Connectors/Connectors.Google/Core/VertexAI/VertexAIEmbeddingClient.cs, dotnet/src/Connectors/Connectors.Google/Extensions/VertexAIKernelBuilderExtensions.cs, dotnet/src/Connectors/Connectors.Google/Extensions/VertexAIMemoryBuilderExtensions.cs, dotnet/src/Connectors/Connectors.Google/Extensions/VertexAIServiceCollectionExtensions.cs, dotnet/src/Connectors/Connectors.Google/Services/VertexAIGeminiChatCompletionService.cs, dotnet/src/Connectors/Connectors.Google/Services/VertexAITextEmbeddingGenerationService.cs
=> .Net: Gemini Task -> ValueTask for BearerTokenProvider

python/DEV_SETUP.md
The DEV setup readme does not clearly outline which workspace and formatter to use in VSCode. And some instructions also show inconsistencies in the project folder structures. 
Update the README to make things more obvious and consistent.
=> Python: Update dev setup readme

dotnet/samples/Concepts/Optimization/FrugalGPT.cs, dotnet/samples/Concepts/README.md
This PR shows how to use FrugalGPT techniques to reduce cost and improve LLM-related task performance with Semantic Kernel filters.
More information about FrugalGPT: https://arxiv.org/abs/2305.05176
=> .Net: Examples with FrugalGPT techniques for LLM cost and performance improvements

dotnet/samples/GettingStartedWithAgents/README.md
Links in samples for GettingStartedWithAgents section should work
fixed broken link in sample for KernelFunctionStrategies
- [x ] The code builds clean without any errors or warnings
- [ x] I didn't break anyone :smile:
=> .Net: Adapted broken link to KernelFunctionStrategies

dotnet/src/Connectors/Connectors.HuggingFace/Core/HuggingFaceMessageApiClient.cs, dotnet/src/Connectors/Connectors.HuggingFace/Core/Models/ChatCompletionRequest.cs, dotnet/src/IntegrationTests/Connectors/HuggingFace/ChatCompletion/HuggingFaceChatCompletionTests.cs
`ModelId` cannot be changed in the prompt execution settings once they are frozen
Closes #6752
=> .Net: Fix for HuggingFaceChatCompletionService incorrect modification of model id

dotnet/samples/Demos/FunctionInvocationApproval/README.md
Fixes: https://github.com/microsoft/semantic-kernel/issues/6739
=> .Net: Added README to FunctionInvocationApproval demo app

java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/PromptExecutionSettings.java, java/semantickernel-api/src/test/java/com/microsoft/semantickernel/orchestration/PromptExecutionSettingsTest.java
Fixes: https://github.com/microsoft/semantic-kernel/issues/6028
=> Java: Fix #6028

python/pyproject.toml, python/samples/getting_started/00-getting-started.ipynb, python/samples/getting_started/01-basic-loading-the-kernel.ipynb, python/samples/getting_started/02-running-prompts-from-file.ipynb, python/samples/getting_started/03-prompt-function-inline.ipynb, python/samples/getting_started/04-kernel-arguments-chat.ipynb, python/samples/getting_started/05-using-the-planner.ipynb, python/samples/getting_started/06-memory-and-embeddings.ipynb, python/samples/getting_started/07-hugging-face-for-plugins.ipynb, python/samples/getting_started/08-native-function-inline.ipynb, python/samples/getting_started/09-groundedness-checking.ipynb, python/samples/getting_started/10-multiple-results-per-prompt.ipynb, python/samples/getting_started/11-streaming-completions.ipynb, python/samples/getting_started/third_party/weaviate-persistent-memory.ipynb
Bump Python version to 1.1.2 for a release.
Bump Python version to 1.1.2 for a release.
=> Python: Bump Python version to 1.1.2 for a release.

dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerClient.cs, dotnet/src/IntegrationTests/IntegrationTests.csproj
Added support for native JSON type if available.
Updated the `SqlServerClient` class to create a table using the JSON data type to store metadata
=> .Net: Dm/sqlserver/json

dotnet/src/Connectors/Connectors.OpenAIV2.UnitTests/Extensions/KernelBuilderExtensionsTests.cs, dotnet/src/Connectors/Connectors.OpenAIV2.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs, dotnet/src/Connectors/Connectors.OpenAIV2.UnitTests/Services/OpenAIAudioToTextServiceTests.cs, dotnet/src/Connectors/Connectors.OpenAIV2.UnitTests/Services/OpenAITextToAudioServiceTests.cs, dotnet/src/Connectors/Connectors.OpenAIV2.UnitTests/Services/OpenAITextToImageServiceTests.cs, dotnet/src/Connectors/Connectors.OpenAIV2/Extensions/OpenAIKernelBuilderExtensions.cs, dotnet/src/Connectors/Connectors.OpenAIV2/Extensions/OpenAIServiceCollectionExtensions.cs, dotnet/src/Connectors/Connectors.OpenAIV2/Services/OpenAIAudioToTextService.cs, dotnet/src/Connectors/Connectors.OpenAIV2/Services/OpenAITextEmbbedingGenerationService.cs, dotnet/src/Connectors/Connectors.OpenAIV2/Services/OpenAITextToAudioService.cs, dotnet/src/Connectors/Connectors.OpenAIV2/Services/OpenAITextToImageService.cs, dotnet/src/IntegrationTests/Agents/OpenAIAssistantAgentTests.cs, dotnet/src/IntegrationTestsV2/Connectors/OpenAI/OpenAITextToImageTests.cs
As a way to enforce the Non Breaking principle this PR remove all avoidable breaking changes from the V2 migration, including additions and small improvements identified.
=> .Net: OpenAI V2 - Reverting all avoidable Breaking Changes - Phase 08

dotnet/src/Connectors/Connectors.OpenAIV2.UnitTests/Services/OpenAIAudioToTextServiceTests.cs, dotnet/src/Connectors/Connectors.OpenAIV2.UnitTests/Services/OpenAIChatCompletionServiceTests.cs, dotnet/src/Connectors/Connectors.OpenAIV2.UnitTests/Services/OpenAITextToAudioServiceTests.cs, dotnet/src/Connectors/Connectors.OpenAIV2.UnitTests/Services/OpenAITextToImageServiceTests.cs, dotnet/src/Connectors/Connectors.OpenAIV2/Services/OpenAIAudioToTextService.cs, dotnet/src/Connectors/Connectors.OpenAIV2/Services/OpenAIChatCompletionService.cs, dotnet/src/Connectors/Connectors.OpenAIV2/Services/OpenAITextToAudioService.cs, dotnet/src/Connectors/Connectors.OpenAIV2/Services/OpenAITextToImageService.cs
Removing non existing V1 logging.
=> .Net: OpenAI V2 Removing LogActivity Extra Implementation

dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Services/AzureOpenAITextEmbeddingGenerationServiceTests.cs, dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Services/AzureOpenAITextToImageServiceTests.cs, dotnet/src/Connectors/Connectors.AzureOpenAI/Core/ClientCore.ChatCompletion.cs, dotnet/src/Connectors/Connectors.OpenAIV2/Core/ClientCore.ChatCompletion.cs
This PR aligns metadata names with those provided by the underlying Azure.AI.OpenAI library. Additionally, it adds a few unit tests to increase code coverage.
=> .Net: Align metadata names with underlying library ones

.github/workflows/python-test-coverage.yml, .github/workflows/python-unit-tests.yml
=> Python: File id fix

.github/workflows/python-test-coverage.yml
=> Python: filepath fix

.github/workflows/merge-gatekeeper.yml, .github/workflows/python-test-coverage.yml, python/semantic_kernel/connectors/ai/chat_completion_client_base.py, python/semantic_kernel/connectors/ai/text_completion_client_base.py, python/tests/unit/connectors/open_ai/services/test_open_ai_chat_completion_base.py, python/tests/unit/connectors/open_ai/services/test_openai_text_completion.py
small fix for the text streaming singular method
tests for both
small fix for test coverage
=> Python: added tests for singular and small fix to code coverage

python/mypy.ini, python/semantic_kernel/connectors/ai/azure_ai_inference/azure_ai_inference_prompt_execution_settings.py, python/semantic_kernel/connectors/ai/azure_ai_inference/services/azure_ai_inference_chat_completion.py, python/semantic_kernel/connectors/ai/azure_ai_inference/services/azure_ai_inference_text_embedding.py, python/semantic_kernel/connectors/ai/azure_ai_inference/services/utils.py, python/tests/unit/connectors/azure_ai_inference/conftest.py, python/tests/unit/connectors/azure_ai_inference/services/test_azure_ai_inference_chat_completion.py, python/tests/unit/connectors/azure_ai_inference/services/test_azure_ai_inference_text_embedding.py, python/tests/unit/connectors/azure_ai_inference/services/test_azure_ai_inference_utils.py
We have been working on improving code quality and increasing the test coverage. This PR focuses on the Azure AI Inference connector.
1. Improve test coverage.
2. Cleared all Mypy warnings.
=> Python: Azure AI Inference connector code quality improvement

dotnet/samples/Concepts/Concepts.csproj, dotnet/samples/Concepts/Plugins/CreatePluginFromOpenApiSpec_RepairService.cs, dotnet/samples/Concepts/README.md, dotnet/samples/Concepts/Resources/Plugins/RepairServicePlugin/repair-service.json, dotnet/src/Functions/Functions.OpenApi.Extensions/Extensions/ApiManifestKernelExtensions.cs, dotnet/src/Functions/Functions.OpenApi/Extensions/OpenApiKernelExtensions.cs, dotnet/src/Functions/Functions.OpenApi/OpenApiKernelPluginFactory.cs, dotnet/src/Functions/Functions.UnitTests/OpenApi/OpenApiKernelPluginFactoryTests.cs, dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAIAudioToTextTests.cs, dotnet/src/IntegrationTests/Plugins/OpenApi/OpenApiPluginsTests.cs, dotnet/src/IntegrationTests/Plugins/OpenApi/RepairServiceTests.cs
=> .Net: Create KernelPlugin from Open API without Kernel instance

dotnet/samples/Concepts/Memory/TextMemoryPlugin_MultipleMemoryStore.cs, dotnet/src/Connectors/Connectors.Memory.DuckDB/Database.cs, dotnet/src/Connectors/Connectors.Memory.DuckDB/DuckDBMemoryStore.cs, dotnet/src/Connectors/Connectors.UnitTests/Memory/DuckDB/DuckDBMemoryStoreTests.cs, dotnet/src/Functions/Functions.OpenApi/Model/RestApiInfo.cs, dotnet/src/Functions/Functions.OpenApi/Model/RestApiSpecification.cs, dotnet/src/Functions/Functions.OpenApi/OpenApi/IOpenApiDocumentParser.cs, dotnet/src/Functions/Functions.OpenApi/OpenApi/OpenApiDocumentParser.cs
=> .Net: Using OpenAPI description as default plugin description

dotnet/nuget/nuget-package.props
=> Version 1.16.0

python/pyproject.toml, python/samples/concepts/agents/README.md, python/samples/getting_started/00-getting-started.ipynb, python/samples/getting_started/01-basic-loading-the-kernel.ipynb, python/samples/getting_started/02-running-prompts-from-file.ipynb, python/samples/getting_started/03-prompt-function-inline.ipynb, python/samples/getting_started/04-kernel-arguments-chat.ipynb, python/samples/getting_started/05-using-the-planner.ipynb, python/samples/getting_started/06-memory-and-embeddings.ipynb, python/samples/getting_started/07-hugging-face-for-plugins.ipynb, python/samples/getting_started/08-native-function-inline.ipynb, python/samples/getting_started/09-groundedness-checking.ipynb, python/samples/getting_started/10-multiple-results-per-prompt.ipynb, python/samples/getting_started/11-streaming-completions.ipynb, python/samples/getting_started/third_party/weaviate-persistent-memory.ipynb
Bump Python version to 1.3.0 from 1.2.0 for a release.
Bump Python version to 1.3.0 from 1.2.0 for a release.
=> Python: Bump Python version to 1.3.0 from 1.2.0 for a release.

dotnet/src/SemanticKernel.Core/PromptTemplate/KernelPromptTemplate.cs
=> .Net: Remove log entry

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreCollectionCreateMapping.cs, dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreCollectionCreateMapping.cs, dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStoreCollectionCreateMapping.cs, dotnet/src/SemanticKernel.Abstractions/Data/IVectorStore.cs, dotnet/src/SemanticKernel.Abstractions/Data/RecordDefinition/DistanceFunction.cs, dotnet/src/SemanticKernel.Abstractions/Data/RecordDefinition/IndexKind.cs, dotnet/src/SemanticKernel.Abstractions/Data/RecordOptions/GetRecordOptions.cs, dotnet/src/SemanticKernel.Core/Data/KernelBuilderExtensions.cs, dotnet/src/SemanticKernel.Core/Data/ServiceCollectionExtensions.cs
Adding experimental attributes to artifacts that were missed before and fixing a few typos.
=> .Net: Add missing experimental attributes and fix typos.

.github/workflows/codeql-analysis.yml
=> Remove Java from CodeQL analysis

dotnet/nuget/nuget-package.props
=> Version 1.16.2

dotnet/Directory.Build.props, dotnet/nuget/nuget-package.props, dotnet/src/Connectors/Connectors.AzureOpenAI/Connectors.AzureOpenAI.csproj, dotnet/src/Connectors/Connectors.OpenAI/Connectors.OpenAI.csproj, dotnet/src/Extensions/PromptTemplates.Handlebars/PromptTemplates.Handlebars.csproj, dotnet/src/Functions/Functions.Yaml/Functions.Yaml.csproj, dotnet/src/SemanticKernel.Abstractions/SemanticKernel.Abstractions.csproj, dotnet/src/SemanticKernel.Core/SemanticKernel.Core.csproj, dotnet/src/SemanticKernel.MetaPackage/SemanticKernel.MetaPackage.csproj
Preparation work for release candidates.
=> .Net: Added release candidate suffix for production packages

python/semantic_kernel/data/vector_store_model_decorator.py, python/semantic_kernel/data/vector_store_model_definition.py, python/tests/unit/data/test_vector_store_record_definition.py
Small text changes and improved logic for key fields.
=> Python: updated docstring and check for 1 keyfield

python/pyproject.toml
Adds additional links for pypi to use after publishing.
=> Python: additional details for pypi

python/pyproject.toml, python/samples/getting_started/00-getting-started.ipynb, python/samples/getting_started/01-basic-loading-the-kernel.ipynb, python/samples/getting_started/02-running-prompts-from-file.ipynb, python/samples/getting_started/03-prompt-function-inline.ipynb, python/samples/getting_started/04-kernel-arguments-chat.ipynb, python/samples/getting_started/05-using-the-planner.ipynb, python/samples/getting_started/06-memory-and-embeddings.ipynb, python/samples/getting_started/07-hugging-face-for-plugins.ipynb, python/samples/getting_started/08-native-function-inline.ipynb, python/samples/getting_started/09-groundedness-checking.ipynb, python/samples/getting_started/10-multiple-results-per-prompt.ipynb, python/samples/getting_started/11-streaming-completions.ipynb, python/samples/getting_started/third_party/weaviate-persistent-memory.ipynb, python/samples/getting_started_with_agents/README.md
Bump Python version to 1.4.0 for a release.
Bump Python version to 1.4.0 for a release.
=> Python: Bump Python version to 1.4.0 for a release.

dotnet/src/Agents/OpenAI/AssistantThreadActions.cs, dotnet/src/Agents/OpenAI/OpenAIAssistantAgent.cs
Align with same pattern introduced in Python: https://github.com/microsoft/semantic-kernel/pull/7854
In response to customer input: https://github.com/microsoft/semantic-kernel/discussions/7601
=> .Net Agents - Identify assistant code-interpreter response with metadata

dotnet/Directory.Build.props, dotnet/nuget/nuget-package.props, dotnet/src/Connectors/Connectors.AzureOpenAI/Connectors.AzureOpenAI.csproj, dotnet/src/Connectors/Connectors.OpenAI/Connectors.OpenAI.csproj, dotnet/src/Extensions/PromptTemplates.Handlebars/PromptTemplates.Handlebars.csproj, dotnet/src/Functions/Functions.Yaml/Functions.Yaml.csproj, dotnet/src/SemanticKernel.Abstractions/SemanticKernel.Abstractions.csproj, dotnet/src/SemanticKernel.Core/SemanticKernel.Core.csproj, dotnet/src/SemanticKernel.MetaPackage/SemanticKernel.MetaPackage.csproj
Preparation work for future release.
=> .Net: [Feature branch] Added release candidate suffix for production packages

dotnet/src/Plugins/Plugins.Core/CodeInterpreter/SessionsPythonPlugin.cs, dotnet/src/Plugins/Plugins.Core/CodeInterpreter/SessionsRemoteFileMetadata.cs, dotnet/src/Plugins/Plugins.UnitTests/Core/SessionsPythonPluginTests.cs, dotnet/src/Plugins/Plugins.UnitTests/TestData/sessions_python_plugin_file_list.json, dotnet/src/Plugins/Plugins.UnitTests/TestData/sessions_python_plugin_file_upload.json
=> .Net: Bugfix - ACA Sessions - Code Interpreter Demo

python/pyproject.toml, python/samples/getting_started/00-getting-started.ipynb, python/samples/getting_started/01-basic-loading-the-kernel.ipynb, python/samples/getting_started/02-running-prompts-from-file.ipynb, python/samples/getting_started/03-prompt-function-inline.ipynb, python/samples/getting_started/04-kernel-arguments-chat.ipynb, python/samples/getting_started/05-using-the-planner.ipynb, python/samples/getting_started/06-memory-and-embeddings.ipynb, python/samples/getting_started/07-hugging-face-for-plugins.ipynb, python/samples/getting_started/08-native-function-inline.ipynb, python/samples/getting_started/09-groundedness-checking.ipynb, python/samples/getting_started/10-multiple-results-per-prompt.ipynb, python/samples/getting_started/11-streaming-completions.ipynb, python/samples/getting_started/third_party/weaviate-persistent-memory.ipynb
Bump Python version to 1.5.0 for a release.
Bump Python version to 1.5.0 for a release.
=> Python: Bump Python version to 1.5.0 for a release.

README.md
There are some Python related sections in the README that need improvement.
In the README, point to the Python code pivot for "getting started with Python." Add the Python API reference link instead of "coming soon."
=> Python: Fix some Python portions of README.

dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.ChatCompletion.cs, dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatCompletion_FunctionCallingTests.cs, dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAIChatCompletion_FunctionCallingTests.cs
This PR refactors the functionality of getting function calling configuration to minimize and simplify the review of the next PR, which introduces auto function choice behavior. This PR does not add any new functionality or bug fixes.
=> .Net: Prepare {Azure}OpenAI connectors for function call abstraction

dotnet/src/Connectors/Connectors.AzureAIInference/AssemblyInfo.cs, dotnet/src/Connectors/Connectors.AzureAIInference/Core/AddHeaderRequestPolicy.cs, dotnet/src/Connectors/Connectors.AzureAIInference/Core/ChatClientCore.cs, dotnet/src/Connectors/Connectors.AzureAIInference/Core/RequestFailedExceptionExtensions.cs, dotnet/src/Connectors/Connectors.AzureAIInference/Services/AzureAIInferenceChatCompletionService.cs, dotnet/src/Connectors/Connectors.AzureAIInference/Settings/AzureAIInferenceChatExecutionSettings.cs, dotnet/src/Connectors/Connectors.AzureAIInference/Settings/AzureAIInferencePromptExecutionSettings.cs, dotnet/src/IntegrationTests/Connectors/AzureAIInference/AzureAIInferenceChatCompletionServiceTests.cs, dotnet/src/IntegrationTests/IntegrationTests.csproj, dotnet/src/IntegrationTests/TestSettings/AzureAIInferenceConfiguration.cs
=> .Net: Azure AI Inference Connector - Chat Completion Phase 1

python/samples/concepts/filtering/auto_function_invoke_filters.py, python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py
We made an update to better handle the function result content when using the auto func invoke filter; however, if parallel func calls exist, they won't be handled properly in the current code.
This change combines the number of FunctionResultContent types returned during the handling of the auto func invoke filter and combines them as the items to one ChatMessageContent.
- The sample is also updated
The result of 3 parallel tool calls now looks correct:
```text
User:> What is the curent time, 9494+49494, and 333-33?  
Auto function invocation filter
Function: now
Request sequence: 0
Function sequence: 0
Number of function calls: 3
Auto function invocation filter
Function: Add
Request sequence: 0
Function sequence: 0
Number of function calls: 1
Altering the Math plugin
Auto function …
```
=> Python: Combine FunctionResultContent to one ChatMessageContent for Auto Func Invoke Filter

dotnet/src/SemanticKernel.Abstractions/Functions/KernelFunction.cs
=> .Net: Create a classifiable Kernel Function logger

python/pyproject.toml, python/samples/getting_started/00-getting-started.ipynb, python/samples/getting_started/01-basic-loading-the-kernel.ipynb, python/samples/getting_started/02-running-prompts-from-file.ipynb, python/samples/getting_started/03-prompt-function-inline.ipynb, python/samples/getting_started/04-kernel-arguments-chat.ipynb, python/samples/getting_started/05-using-the-planner.ipynb, python/samples/getting_started/06-memory-and-embeddings.ipynb, python/samples/getting_started/07-hugging-face-for-plugins.ipynb, python/samples/getting_started/08-native-function-inline.ipynb, python/samples/getting_started/09-groundedness-checking.ipynb, python/samples/getting_started/10-multiple-results-per-prompt.ipynb, python/samples/getting_started/11-streaming-completions.ipynb, python/samples/getting_started/third_party/weaviate-persistent-memory.ipynb
Bump Python project version to 1.5.1 for a release.
Bump Python project version to 1.5.1 for a release.
=> Python: Bump Python project version to 1.5.1 for a release.

python/samples/concepts/model_as_a_service/mmlu_model_eval.py
Module Imports: No comments needed here as the imports are self-explanatory.
setup_kernel Function: Comments describe the setup of the kernel and the addition of AI services and plugins.
load_mmlu_dataset Function: Comments explain the purpose of the function, its arguments, and return value, along with inline comments for clarity.
MMLUPlugin Class: Comments are added to the class and its method to describe their functionality and arguments.
main Function: Comments are added to describe the workflow, including loading datasets, setting up the kernel, evaluating samples, and calculating accuracies.
=> Python: Update mmlu_model_eval.py

dotnet/src/Connectors/Connectors.AzureAIInference.UnitTests/Extensions/AzureAIInferenceKernelBuilderExtensionsTests.cs, dotnet/src/Connectors/Connectors.AzureAIInference.UnitTests/Extensions/AzureAIInferenceServiceCollectionExtensionsTests.cs, dotnet/src/Connectors/Connectors.AzureAIInference.UnitTests/Services/AzureAIInferenceChatCompletionServiceTests.cs, dotnet/src/Connectors/Connectors.AzureAIInference/Extensions/AzureAIInferenceKernelBuilderExtensions.cs, dotnet/src/Connectors/Connectors.AzureAIInference/Extensions/AzureAIInferenceServiceCollectionExtensions.cs, dotnet/src/Connectors/Connectors.AzureAIInference/Services/AzureAIInferenceChatCompletionService.cs
First Phase of Adding Unit Tests.
- Resolve Partially #7958 
- Add Unit Tests + Coverage > 85%.
=> .Net: Azure MaaS Connector: UTs - Phase 3

dotnet/src/Connectors/Connectors.AzureAIInference.UnitTests/Settings/AzureAIInferencePromptExecutionSettingsTests.cs, dotnet/src/Connectors/Connectors.AzureAIInference/Core/ChatClientCore.cs, dotnet/src/Connectors/Connectors.AzureAIInference/Settings/AzureAIInferencePromptExecutionSettings.cs
First Phase of Adding Unit Tests.
- Resolve Partially #7958 
- Add Unit Tests + Coverage > 85%.
=> .Net: Azure MaaS Connector: UTs - Phase 4

dotnet/src/Connectors/Connectors.Memory.Sqlite/SqliteMemoryStore.cs
=> .Net: Delete unnecessary parameters

dotnet/samples/Concepts/ChatCompletion/AzureAIInference_ChatCompletion.cs, dotnet/samples/Concepts/ChatCompletion/AzureAIInference_ChatCompletionStreaming.cs, dotnet/samples/Concepts/ChatCompletion/Google_GeminiChatCompletion.cs, dotnet/samples/Concepts/ChatCompletion/Google_GeminiChatCompletionStreaming.cs, dotnet/samples/Concepts/ChatCompletion/OpenAI_ChatCompletion.cs, dotnet/samples/Concepts/ChatCompletion/OpenAI_ChatCompletionStreaming.cs, dotnet/samples/Concepts/Concepts.csproj, dotnet/samples/Demos/AIModelRouter/AIModelRouter.csproj, dotnet/samples/Demos/AIModelRouter/Program.cs, dotnet/src/InternalUtilities/samples/InternalUtilities/TestConfiguration.cs, dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatCompletionServiceExtensions.cs
First Phase of Adding Unit Tests.
- Resolve Partially #7958 
- Demo and Samples
=> .Net: Azure MaaS Connector: Samples

python/samples/concepts/memory/data_models.py, python/samples/concepts/memory/new_memory.py, python/samples/concepts/memory/pandas_memory.py, python/semantic_kernel/connectors/ai/open_ai/__init__.py, python/semantic_kernel/connectors/memory/azure_ai_search/azure_ai_search_collection.py, python/semantic_kernel/connectors/memory/qdrant/__init__.py, python/semantic_kernel/connectors/memory/qdrant/qdrant_collection.py, python/semantic_kernel/connectors/memory/redis/__init__.py, python/semantic_kernel/connectors/memory/redis/redis_collection.py, python/semantic_kernel/connectors/memory/volatile/__init__.py, python/semantic_kernel/data/__init__.py, python/semantic_kernel/data/vector_store_record_collection.py
Fixed some small things based on docs creation.
Added include_vectors param where appropriate.
Improved import structure
=> Python: improvements in memory connectors

python/pyproject.toml, python/samples/getting_started/00-getting-started.ipynb, python/samples/getting_started/01-basic-loading-the-kernel.ipynb, python/samples/getting_started/02-running-prompts-from-file.ipynb, python/samples/getting_started/03-prompt-function-inline.ipynb, python/samples/getting_started/04-kernel-arguments-chat.ipynb, python/samples/getting_started/05-using-the-planner.ipynb, python/samples/getting_started/06-memory-and-embeddings.ipynb, python/samples/getting_started/07-hugging-face-for-plugins.ipynb, python/samples/getting_started/08-native-function-inline.ipynb, python/samples/getting_started/09-groundedness-checking.ipynb, python/samples/getting_started/10-multiple-results-per-prompt.ipynb, python/samples/getting_started/11-streaming-completions.ipynb, python/samples/getting_started/third_party/weaviate-persistent-memory.ipynb
Bump Python project version to 1.6.0 for a release.
Bump Python project version to 1.6.0 for a release.
=> Python: Bump Python project version to 1.6.0 for a release.

README.md
=> double 'see' fix

python/pyproject.toml, python/samples/getting_started/00-getting-started.ipynb, python/samples/getting_started/01-basic-loading-the-kernel.ipynb, python/samples/getting_started/02-running-prompts-from-file.ipynb, python/samples/getting_started/03-prompt-function-inline.ipynb, python/samples/getting_started/04-kernel-arguments-chat.ipynb, python/samples/getting_started/05-using-the-planner.ipynb, python/samples/getting_started/06-memory-and-embeddings.ipynb, python/samples/getting_started/07-hugging-face-for-plugins.ipynb, python/samples/getting_started/08-native-function-inline.ipynb, python/samples/getting_started/09-groundedness-checking.ipynb, python/samples/getting_started/10-multiple-results-per-prompt.ipynb, python/samples/getting_started/11-streaming-completions.ipynb, python/samples/getting_started/third_party/weaviate-persistent-memory.ipynb
Bump Python project version to 1.7.0 for a release.
Bump Python project version to 1.7.0 for a release.
=> Python: Bump Python project version to 1.7.0 for a release.

python/pyproject.toml, python/samples/getting_started/00-getting-started.ipynb, python/samples/getting_started/01-basic-loading-the-kernel.ipynb, python/samples/getting_started/02-running-prompts-from-file.ipynb, python/samples/getting_started/03-prompt-function-inline.ipynb, python/samples/getting_started/04-kernel-arguments-chat.ipynb, python/samples/getting_started/05-using-the-planner.ipynb, python/samples/getting_started/06-memory-and-embeddings.ipynb, python/samples/getting_started/07-hugging-face-for-plugins.ipynb, python/samples/getting_started/08-native-function-inline.ipynb, python/samples/getting_started/09-groundedness-checking.ipynb, python/samples/getting_started/10-multiple-results-per-prompt.ipynb, python/samples/getting_started/11-streaming-completions.ipynb, python/samples/getting_started/third_party/weaviate-persistent-memory.ipynb
Bump Python version to 1.8.0 for a release.
Bump Python version to 1.8.0 for a release.
=> Python: Bump Python version to 1.8.0 for a release.

.github/workflows/python-integration-tests.yml, .github/workflows/python-unit-tests.yml
small fix for the integration tests after switching to uv.
=> Python: updated paths for integration tests

.github/workflows/python-integration-tests.yml
=> Python: fix ollama integration test

python/pyproject.toml
We did not have our license referenced in the pyproject.toml and therefore not in Pypi, this fixes that (fixes #8341)
Also added some classifiers.
=> Python: added license info to project

python/.pre-commit-config.yaml, python/LICENSE, python/Makefile, python/pyproject.toml, python/samples/getting_started/00-getting-started.ipynb, python/samples/getting_started/01-basic-loading-the-kernel.ipynb, python/samples/getting_started/02-running-prompts-from-file.ipynb, python/samples/getting_started/03-prompt-function-inline.ipynb, python/samples/getting_started/04-kernel-arguments-chat.ipynb, python/samples/getting_started/05-using-the-planner.ipynb, python/samples/getting_started/06-memory-and-embeddings.ipynb, python/samples/getting_started/07-hugging-face-for-plugins.ipynb, python/samples/getting_started/08-native-function-inline.ipynb, python/samples/getting_started/09-groundedness-checking.ipynb, python/samples/getting_started/10-multiple-results-per-prompt.ipynb, python/samples/getting_started/11-streaming-completions.ipynb, python/samples/getting_started/third_party/weaviate-persistent-memory.ipynb, python/semantic_kernel/__init__.py
Bumped the version to 1.8.1, slight updates in pyproject and make to build automatically.
=> Python: bump version to 1.8.1

.github/workflows/python-build.yml, python/pyproject.toml, python/semantic_kernel/__init__.py
Next to the reference to the python file, also added a license classifier
=> Python: add license to pyproject

dotnet/samples/Concepts/Search/BingTextSearchExample.cs, dotnet/samples/Concepts/Search/Bing_TextSearch.cs, dotnet/src/Connectors/Connectors.UnitTests/OpenAI/ChatCompletion/OpenAIChatCompletionServiceTests.cs, dotnet/src/InternalUtilities/samples/InternalUtilities/BaseTest.cs, dotnet/src/InternalUtilities/samples/InternalUtilities/TestConfiguration.cs, dotnet/src/Plugins/Plugins.UnitTests/TestData/bing_site_filter_devblogs_microsoft.com.json, dotnet/src/Plugins/Plugins.UnitTests/TestData/bing_what_is_the_semantic_kernel.json, dotnet/src/Plugins/Plugins.UnitTests/Web/Bing/BingTextSearchTests.cs, dotnet/src/Plugins/Plugins.Web/Bing/BingMetaTag.cs, dotnet/src/Plugins/Plugins.Web/Bing/BingOpenGraphImage.cs, dotnet/src/Plugins/Plugins.Web/Bing/BingSearchResponse.cs, dotnet/src/Plugins/Plugins.Web/Bing/BingTextSearch.cs, dotnet/src/Plugins/Plugins.Web/Bing/BingTextSearchOptions.cs, dotnet/src/Plugins/Plugins.Web/Bing/BingWebPage.cs
=> .Net: Update Bing Search to new Text Search Design

.github/_typos.toml, dotnet/samples/Concepts/Search/GoogleTextSearchExample.cs, dotnet/samples/Concepts/Search/Google_TextSearch.cs, dotnet/src/Plugins/Plugins.UnitTests/TestData/google_site_filter_devblogs_microsoft.com.json, dotnet/src/Plugins/Plugins.UnitTests/TestData/google_what_is_the_semantic_kernel.json, dotnet/src/Plugins/Plugins.UnitTests/Web/Google/GoogleTextSearchTests.cs, dotnet/src/Plugins/Plugins.Web/Google/GoogleTextSearch.cs, dotnet/src/Plugins/Plugins.Web/Google/GoogleTextSearchOptions.cs
=> .Net: Update Google Search to new Text Search Design

dotnet/samples/Concepts/RAG/Bing_RagWithTextSearch.cs, dotnet/samples/Concepts/Search/Bing_FunctionCallingWithTextSearch.cs, dotnet/src/Plugins/Plugins.UnitTests/Web/Bing/BingTextSearchTests.cs, dotnet/src/Plugins/Plugins.Web/Bing/BingTextSearch.cs
- Add text search concepts demonstrating RAG and Function Calling
- Fix exception message when an unknown filter is detected
=> .Net: Add text search concepts demonstrating RAG and Function Calling

dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Services/AzureOpenAIChatCompletionServiceTests.cs, dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/TestData/chat_completion_streaming_async_filter_response.txt, dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.ChatCompletion.cs, dotnet/src/Connectors/Connectors.OpenAI/Core/OpenAIStreamingChatMessageContent.cs
Resolve #8407
Add temporary bugfix for error described in below issues:
- #8407
- https://github.com/openai/openai-dotnet/issues/198
- Added UnitTest to ensure expected behavior.
=> .Net: OpenAI V2 Bugfix for Streaming Asynchronous Filter Results

dotnet/samples/Concepts/Search/Bing_FunctionCallingWithTextSearch.cs, dotnet/src/SemanticKernel.Core/Search/TextSearchExtensions.cs
=> .Net: Simplify how additional text search filter parameters are specified

dotnet/src/InternalUtilities/src/Schema/JsonSchemaGenerationContext.cs, dotnet/src/InternalUtilities/src/Schema/JsonSchemaMapper.cs
=> .Net: Fix formatting errors in the schema files

docs/decisions/00NN-vector-search-design.md, dotnet/src/SemanticKernel.Abstractions/Data/IVectorSearch.cs, dotnet/src/SemanticKernel.Abstractions/Data/RecordOptions/VectorSearchOptions.cs, dotnet/src/SemanticKernel.Abstractions/Data/VectorSearchExtensions.cs, dotnet/src/SemanticKernel.Abstractions/Data/VectorSearchFiltering/EqualityFilterClause.cs, dotnet/src/SemanticKernel.Abstractions/Data/VectorSearchFiltering/FilterClause.cs, dotnet/src/SemanticKernel.Abstractions/Data/VectorSearchFiltering/FilterClauseType.cs, dotnet/src/SemanticKernel.Abstractions/Data/VectorSearchFiltering/TagListContainsFilterClause.cs, dotnet/src/SemanticKernel.Abstractions/Data/VectorSearchFiltering/VectorSearchFilter.cs, dotnet/src/SemanticKernel.Abstractions/Data/VectorSearchQueries/VectorSearchQuery.cs, dotnet/src/SemanticKernel.Abstractions/Data/VectorSearchQueries/VectorSearchQueryType.cs, dotnet/src/SemanticKernel.Abstractions/Data/VectorSearchQueries/VectorizableTextSearchQuery.cs, dotnet/src/SemanticKernel.Abstractions/Data/VectorSearchQueries/VectorizedSearchQuery.cs, dotnet/src/SemanticKernel.Abstractions/Data/VectorSearchResult.cs
As part of the new vector store abstractions we need to add support for vector search.
Adding an ADR document and the interface used for vector search.
=> .Net: Add Vector Search ADR document and abstractions

.github/workflows/dotnet-build-and-test.yml
Adding a step to perform an Azure Login, this will be used by the integration tests to access Azure Cognitive Services
=> Add Azure Login action

.github/workflows/dotnet-build-and-test.yml
Give write permissions to id-token in the workflow
=> Give write permissions to id-token in the workflow

.github/workflows/dotnet-build-and-test.yml, dotnet/src/IntegrationTests/Agents/MixedAgentTests.cs
Update MixedAgentTests to use a token credential
=> .Net: Update MixedAgentTests to use a token credential

dotnet/src/Plugins/Plugins.UnitTests/Web/Bing/BingTextSearchTests.cs, dotnet/src/Plugins/Plugins.Web/Bing/BingTextSearch.cs
Add support for advanced search keywords, see: https://support.microsoft.com/en-us/topic/advanced-search-keywords-ea595928-5d63-4a0b-9c6b-0b769865e78a
=> .Net: Add support for advanced search keywords

python/semantic_kernel/__init__.py
Bump Python version to 1.8.3 from 1.8.2 for a release.
Bump Python version to 1.8.3 from 1.8.2 for a release.
=> Python: Bump Python version to 1.8.3 for a release.

docs/decisions/00NN-vector-search-design.md
We agreed some changes in naming with regards to filter clauses and classes so updating adr document to match.
- Change BasicVectorSearchFilter  to VectorSearchFilter
- Change Equality to EqualTo
- Change BasicVectorSearchFilter prop to Filter
=> Update adr document with filter changes.

dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Services/AzureOpenAIChatCompletionServiceTests.cs, dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/TestData/chat_completion_streaming_multiple_function_calls_test_async_filter_response.txt, dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.ChatCompletion.cs, dotnet/src/Connectors/Connectors.OpenAI/Core/OpenAIStreamingChatMessageContent.cs
Closes #8629 
Workaround BugFix for issue in OpenAI SDK:
- https://github.com/openai/openai-dotnet/issues/198
=> .Net: AzureOpenAI Connector - Bugfix AsyncFilter Null Reference Exception when using Function Calling.

python/semantic_kernel/connectors/ai/google/google_ai/services/utils.py, python/semantic_kernel/connectors/ai/google/vertex_ai/services/utils.py, python/tests/integration/completions/chat_completion_test_base.py, python/tests/integration/completions/test_chat_completion_with_function_calling.py
Address https://github.com/microsoft/semantic-kernel/issues/8110
1. Bug fix: parse function result to string
2. Integration tests added against complex type in function calling.
=> Python: Fix issues of Google AI/Vertex AI on handling classes in kernel functions

python/samples/concepts/auto_function_calling/parallel_function_calling.py
Customers are having questions about parallel function calling and whether the kernel will execute functions in parallel.
Add a sample to show that the kernel will execute functions in parallel when the model returns parallel function calls.
=> Python: Parallel function calling sample

.github/workflows/python-integration-tests.yml, python/semantic_kernel/connectors/ai/open_ai/const.py, python/semantic_kernel/connectors/ai/open_ai/services/azure_chat_completion.py, python/semantic_kernel/connectors/ai/open_ai/settings/azure_open_ai_settings.py, python/tests/integration/completions/chat_completion_test_base.py
Testing changes related to authenticating to Azure OpenAI via a Token credential instead of an API key.
Testing changes related to authenticating to Azure OpenAI via a Token credential instead of an API key.
=> Python: Support Azure Token Authentication

dotnet/src/IntegrationTests/Agents/ChatCompletionAgentTests.cs, dotnet/src/IntegrationTests/Agents/MixedAgentTests.cs, dotnet/src/InternalUtilities/connectors/AI/FunctionCalling/FunctionCallsProcessor.cs, dotnet/src/SemanticKernel.UnitTests/AI/FunctionChoiceBehaviors/FunctionChoiceBehaviorDeserializationTests.cs
Post-Bug Bash: Minor code enhancements and fixes:
- Integration tests added for Agents to use both function-calling models.
- Unit tests for function choice behavior deserialization fixed to test polymorphic deserialization.
- Warning logging is added if no function is provided
=> .Net: Minor code enhancements and fixes

python/semantic_kernel/core_plugins/sessions_python_tool/README.md
Fix a typo in a plugin README.
Fix a typo in a plugin README.
=> Python: Fix typo

.github/workflows/python-integration-tests.yml
Update integration test yaml to work with the federated credential.
Update integration test yaml to work with the federated credential.
=> Python: Update integration test yaml to work with the federated credential.

python/semantic_kernel/__init__.py
Python: Bump Python version to 1.9.0 for a release.
Python: Bump Python version to 1.9.0 for a release.
=> Python: Bump Python version to 1.9.0 for a release.

.github/workflows/python-integration-tests.yml
Fix integration test yaml and hard-code to integration environment for credential use
Fix integration test yaml and hard-code to integration environment for credential use
=> Python: Fix integration test yaml and hard-code to integration environment for credential use

.github/workflows/python-integration-tests.yml
Remove duplicate env key
Remove duplicate env key
=> Python: Remove duplicate env key

.github/workflows/python-integration-tests.yml
Python: Don't have a conditional on matrix value that doesn't exist.
Python: Don't have a conditional on matrix value that doesn't exist.
=> Python: Don't have a conditional on matrix value that doesn't exist.

dotnet/src/Connectors/Connectors.AzureCosmosDBMongoDB.UnitTests/AzureCosmosDBMongoDBVectorStoreRecordCollectionTests.cs, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreCollectionSearchMapping.cs, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreRecordCollection.cs, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreRecordCollectionOptions.cs, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreRecordMapper.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreRecordCollectionTests.cs
Related: https://github.com/microsoft/semantic-kernel/issues/6522
- Implemented `VectorizedSearchAsync` method in Azure CosmosDB for MongoDB connector.
=> .Net: Added vector search implementation for Azure CosmosDB for MongoDB

dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatCompletion_AutoFunctionChoiceBehaviorTests.cs, dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatCompletion_NoneFunctionChoiceBehaviorTests.cs, dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatCompletion_RequiredFunctionChoiceBehaviorTests.cs, dotnet/src/IntegrationTests/Planners/PlanTests.cs, dotnet/src/IntegrationTests/Planners/SequentialPlanner/SequentialPlanParserTests.cs, dotnet/src/IntegrationTests/Planners/SequentialPlanner/SequentialPlannerTests.cs, dotnet/src/IntegrationTests/Planners/StepwisePlanner/FunctionCallingStepwisePlannerTests.cs, dotnet/src/IntegrationTests/Planners/StepwisePlanner/StepwisePlannerTests.cs, dotnet/src/IntegrationTests/README.md
=> .Net: Update integration tests to use AzureCliCredential

python/semantic_kernel/connectors/ai/open_ai/services/azure_chat_completion.py
Fix azure api key check
Fix azure api key check
=> Python: Fix azure api key check

dotnet/samples/Concepts/PromptTemplates/ChatLoopWithPrompt.cs, dotnet/samples/Concepts/PromptTemplates/SafeChatPrompts.cs, dotnet/samples/Concepts/README.md
=> .Net: Create sample showing how to render ChatHistory to a prompt and invoke it

dotnet/samples/Concepts/Memory/VectorStore_VectorSearch_MultiVector.cs, dotnet/samples/Concepts/Memory/VectorStore_VectorSearch_Paging.cs, dotnet/src/SemanticKernel.Core/Data/VolatileVectorStoreRecordCollection.cs
- Adding a sample showing vector search with paging
- Adding a sample showing how vector search where multiple vectors exist in the same record.
- Fix exception message in the Volatile Vector store.
=> .Net: Vector search sample: Multi Vector and Paging

dotnet/src/Experimental/Process.Abstractions/KernelProcess.cs, dotnet/src/Experimental/Process.Abstractions/KernelProcessEdge.cs, dotnet/src/Experimental/Process.Abstractions/KernelProcessEvent.cs, dotnet/src/Experimental/Process.Abstractions/KernelProcessFunctionTarget.cs, dotnet/src/Experimental/Process.Abstractions/KernelProcessMessageChannel.cs, dotnet/src/Experimental/Process.Abstractions/KernelProcessState.cs, dotnet/src/Experimental/Process.Abstractions/KernelProcessStep.cs, dotnet/src/Experimental/Process.Abstractions/KernelProcessStepContext.cs, dotnet/src/Experimental/Process.Abstractions/KernelProcessStepState.cs
Adding the initial set of abstractions for SK processes.
=> .Net: bentho/process abstraction

dotnet/src/Connectors/Connectors.Memory.Weaviate/HttpV2/WeaviateVectorSearchRequest.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/HttpV2/WeaviateVectorSearchResponse.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/ModelV2/WeaviateVectorSearchData.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateConstants.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreCollectionSearchMapping.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreRecordCollection.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreRecordCollectionQueryBuilder.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreRecordMapper.cs, dotnet/src/Connectors/Connectors.Weaviate.UnitTests/WeaviateVectorStoreCollectionSearchMappingTests.cs, dotnet/src/Connectors/Connectors.Weaviate.UnitTests/WeaviateVectorStoreRecordCollectionQueryBuilderTests.cs, dotnet/src/Connectors/Connectors.Weaviate.UnitTests/WeaviateVectorStoreRecordCollectionTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/Weaviate/WeaviateHotel.cs, dotnet/src/IntegrationTests/Connectors/Memory/Weaviate/WeaviateVectorStoreRecordCollectionTests.cs
Related: https://github.com/microsoft/semantic-kernel/issues/6527
- Implemented `VectorizedSearchAsync` method in Weaviate connector.
=> .Net: [Feature Branch] Added vector search implementation for Weaviate

dotnet/src/Experimental/Process.Abstractions/KernelProcessFunctionTarget.cs, dotnet/src/Experimental/Process.Abstractions/Process.Abstractions.csproj, dotnet/src/Experimental/Process.Core/EndStep.cs, dotnet/src/Experimental/Process.Core/Extensions/ProcessTypeExtensions.cs, dotnet/src/Experimental/Process.Core/Internal/EndStep.cs, dotnet/src/Experimental/Process.Core/Process.Core.csproj, dotnet/src/Experimental/Process.Core/ProcessBuilder.cs, dotnet/src/Experimental/Process.Core/ProcessEdgeBuilder.cs, dotnet/src/Experimental/Process.Core/ProcessFunctionTargetBuilder.cs, dotnet/src/Experimental/Process.Core/ProcessStepBuilder.cs, dotnet/src/Experimental/Process.Core/ProcessStepEdgeBuilder.cs, dotnet/src/Experimental/Process.UnitTests/Process.UnitTests.csproj, dotnet/src/Experimental/Process.UnitTests/ProcessBuilderTests.cs, dotnet/src/Experimental/Process.UnitTests/ProcessEdgeBuilderTests.cs, dotnet/src/Experimental/Process.UnitTests/ProcessStepBuilderTests.cs, dotnet/src/Experimental/Process.UnitTests/ProcessStepEdgeBuilderTests.cs, dotnet/src/Experimental/Process.UnitTests/ProcessTypeExtensionsTests.cs
This PR adds the process builders which are used to simplify the process of defining the process linkage my utilizing the builder pattern. 
Note: There are more unit tests coming for this PR, publishing now to get feedback.
=> .Net: Adding process builders.

dotnet/src/Connectors/Connectors.AzureCosmosDBMongoDB.UnitTests/AzureCosmosDBMongoDBGenericDataModelMapperTests.cs, dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchGenericDataModelMapper.cs, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBConstants.cs, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBGenericDataModelMapper.cs, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreRecordCollection.cs, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreRecordMapper.cs, dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantGenericDataModelMapper.cs, dotnet/src/Connectors/Connectors.Memory.Redis/RedisHashSetGenericDataModelMapper.cs, dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonGenericDataModelMapper.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreFixture.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreRecordCollectionTests.cs, dotnet/src/InternalUtilities/src/Data/VectorStoreRecordPropertyReader.cs
Related: https://github.com/microsoft/semantic-kernel/issues/6522
- Implemented `AzureCosmosDBMongoDBGenericDataModelMapper` class.
=> .Net: Implemented generic data model support for Azure CosmosDB MongoDB connector

dotnet/samples/Concepts/ChatCompletion/OpenAI_FunctionCallingWithMemoryPlugin.cs
New sample to help answer question #8074
=> .Net: Sample showing how to use function calling to retrieve relevant information

dotnet/nuget/nuget-package.props
=> .Net: Bump to version 1.21.0

dotnet/src/Connectors/Connectors.AzureCosmosDBNoSQL.UnitTests/AzureCosmosDBNoSQLGenericDataModelMapperTests.cs, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/AzureCosmosDBNoSQLGenericDataModelMapper.cs, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/AzureCosmosDBNoSQLReadOnlyMemoryByteConverter.cs, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/AzureCosmosDBNoSQLVectorStoreRecordCollection.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBNoSQL/AzureCosmosDBNoSQLHotel.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBNoSQL/AzureCosmosDBNoSQLVectorStoreRecordCollectionTests.cs
Related: https://github.com/microsoft/semantic-kernel/issues/6522
- Implemented `AzureCosmosDBNoSQLGenericDataModelMapper` class.
=> .Net: Implemented generic data model support for Azure CosmosDB NoSQL connector

python/semantic_kernel/__init__.py
Bump Python version to 1.10.0 from 1.9.0 for a release.
Bump Python version to 1.10.0 from 1.9.0 for a release.
=> Python: Bump Python version to 1.10.0 from 1.9.0 for a release.

dotnet/src/IntegrationTests/Data/BaseTextSearchTests.cs, dotnet/src/IntegrationTests/Plugins/Web/Bing/BingTextSearchTests.cs, dotnet/src/IntegrationTests/Plugins/Web/Google/GoogleTextSearchTests.cs, dotnet/src/IntegrationTests/TestSettings/BingConfiguration.cs, dotnet/src/IntegrationTests/TestSettings/GoogleConfiguration.cs
=> .Net: Integration tests for Bing and Google text search

dotnet/src/Connectors/Connectors.AzureCosmosDBNoSQL.UnitTests/AzureCosmosDBNoSQLGenericDataModelMapperTests.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/HttpV2/WeaviateUpsertCollectionObjectBatchRequest.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateGenericDataModelMapper.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreRecordCollection.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreRecordCollectionOptions.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreRecordMapper.cs, dotnet/src/Connectors/Connectors.Weaviate.UnitTests/WeaviateGenericDataModelMapperTests.cs, dotnet/src/Connectors/Connectors.Weaviate.UnitTests/WeaviateVectorStoreRecordCollectionTests.cs, dotnet/src/Connectors/Connectors.Weaviate.UnitTests/WeaviateVectorStoreRecordMapperTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/Weaviate/WeaviateVectorStoreRecordCollectionTests.cs
Related: https://github.com/microsoft/semantic-kernel/issues/6527
- Implemented `WeaviateGenericDataModelMapper` class.
=> .Net: Implemented generic data model support for Weaviate connector

dotnet/src/Connectors/Connectors.Onnx/OnnxRuntimeGenAIChatCompletionService.cs
=> .Net: ONNX - Remove starting space at the beginning of first token

python/semantic_kernel/__init__.py
Bump python version to 1.10.1 for a release.
Bump python version to 1.10.1 for a release.
=> Python: Bump python version to 1.10.1 for a release.

dotnet/src/Experimental/Process.LocalRuntime/LocalProcessFactory.cs
=> .Net: Fix type, interrogate

dotnet/src/SemanticKernel.Core/Data/VolatileVectorStoreRecordCollection.cs
Refactored code in main.
Updating remaining code in branch to match.
=> .Net: Fix issues after vector split merge.

dotnet/samples/GettingStartedWithProcesses/README.md
Fixed url:s in documentation that lead to 404's
Url's were broken in the docs
Pointed them to the correct location
=> .Net: Update README.md

dotnet/samples/GettingStartedWithProcesses/README.md
Fixing broken links in Processes README file
=> .Net: Fixing broken link in processes readme file

dotnet/src/SemanticKernel.Abstractions/AI/TextToImage/TextToImageServiceExtensions.cs, dotnet/src/SemanticKernel.UnitTests/SemanticKernel.UnitTests.csproj
After merging the feature-aot branch with the main, the code stopped building, and a new AOT warning appeared. This PR fixes both the build error and the AOT warning.
=> .Net: Fix build errors and warnings after merge with the main branch

python/semantic_kernel/__init__.py
Bump Python version to 1.11.0 for a release.
Bump Python version to 1.11.0 for a release.
=> Python: Bump Python version to 1.11.0 for a release.

dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchTextSearchTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreFixture.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreRecordCollectionTests.cs, dotnet/src/IntegrationTests/Data/BaseTextSearchTests.cs, dotnet/src/IntegrationTests/Data/BaseVectorStoreTextSearchTests.cs, dotnet/src/IntegrationTests/Data/VolatileVectorStoreTextSearchTests.cs, dotnet/src/IntegrationTests/Plugins/Web/Bing/BingTextSearchTests.cs, dotnet/src/IntegrationTests/Plugins/Web/Google/GoogleTextSearchTests.cs, dotnet/src/IntegrationTests/README.md
=> .Net: Adapt Azure AI Search Connector to new Text Search Design

dotnet/Directory.Packages.props
=> .Net: Bump OllamaSharp to Strong Name signed package.

dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchTextSearchTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantTextSearchTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorStoreFixture.cs, dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorStoreRecordCollectionTests.cs
=> .Net: Update Qdrant Memory Connector to new Text Search Design

dotnet/nuget/nuget-package.props
=> .Net: Version 1.22.0

dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantTextSearchTests.cs, dotnet/src/IntegrationTests/Plugins/Web/Google/GoogleTextSearchTests.cs
=> .Net: Disable the Qdrant and Google text search integration tests

dotnet/src/IntegrationTests/Data/VolatileVectorStoreTextSearchTests.cs
=> Disable the VolatileVectorStoreTextSearchTests

dotnet/samples/Demos/VectorStoreRAG/DataLoader.cs, dotnet/samples/Demos/VectorStoreRAG/TextSnippet.cs, dotnet/samples/GettingStartedWithTextSearch/GettingStartedWithTextSearch.csproj, dotnet/samples/GettingStartedWithTextSearch/InMemoryVectorStoreCollectionFixture.cs, dotnet/samples/GettingStartedWithTextSearch/InMemoryVectorStoreFixture.cs, dotnet/samples/GettingStartedWithTextSearch/Step4_Search_With_VectorStore.cs, dotnet/samples/GettingStartedWithTextSearch/VolatileVectorStoreCollectionFixture.cs
Fixing up latest changes from main to match refactoring in branch.
=> .Net: Fixing up new projects merged from main.

dotnet/samples/Concepts/Memory/VectorStore_VectorSearch_MultiStore_AzureAISearch.cs, dotnet/samples/Concepts/Memory/VectorStore_VectorSearch_MultiStore_InMemory.cs, dotnet/samples/Concepts/Memory/VectorStore_VectorSearch_MultiStore_Qdrant.cs, dotnet/samples/Concepts/Memory/VectorStore_VectorSearch_MultiStore_Redis.cs, dotnet/samples/Concepts/Memory/VectorStore_VectorSearch_Simple.cs
- Fixing typos
- Switching to CLI auth method for a remaining test..
=> .Net: Address bugbash feedback for vector search samples.

dotnet/samples/Demos/StepwisePlannerMigration/README.md
Small update in README file to use new function calling model.
=> .Net: Updated stepwise planner migration examples to use new function calling model

dotnet/samples/GettingStarted/README.md, dotnet/samples/GettingStartedWithTextSearch/README.md, dotnet/samples/GettingStartedWithTextSearch/Step2_Search_For_RAG.cs, dotnet/src/SemanticKernel.Core/Data/TextSearch/VectorStoreTextSearch.cs
=> .Net: Update README with feedback from Bug Bash

dotnet/samples/Demos/VectorStoreRAG/DataLoader.cs, dotnet/samples/Demos/VectorStoreRAG/IDataLoader.cs, dotnet/samples/Demos/VectorStoreRAG/Options/RagConfig.cs, dotnet/samples/Demos/VectorStoreRAG/Program.cs, dotnet/samples/Demos/VectorStoreRAG/RAGChatService.cs, dotnet/samples/Demos/VectorStoreRAG/README.md, dotnet/samples/Demos/VectorStoreRAG/VectorStoreRAG.csproj, dotnet/samples/Demos/VectorStoreRAG/appsettings.json
Update the RAG Sample with feedback from the bug bash
=> .Net: Update the RAG Sample with feedback from the bug bash

dotnet/src/SemanticKernel.Core/Data/TextSearch/TextSearchKernelBuilderExtensions.cs, dotnet/src/SemanticKernel.Core/Data/TextSearch/TextSearchServiceCollectionExtensions.cs, dotnet/src/SemanticKernel.Core/Data/TextSearch/VectorStoreTextSearch.cs, dotnet/src/SemanticKernel.UnitTests/Data/TextSearchServiceCollectionExtensionsTests.cs
=> .Net: AddVectorStoreTextSearch support service ids for dependencies

dotnet/nuget/nuget-package.props, dotnet/src/Connectors/VectorData.Abstractions/VectorData.Abstractions.csproj
Update package versions for release.
=> .Net: Update SK and VectorData versions.

.github/workflows/dotnet-build-and-test.yml
=> Clean-up environment variables used by integration tests

dotnet/samples/GettingStartedWithProcesses/Events/CommonEvents.cs, dotnet/samples/GettingStartedWithProcesses/SharedSteps/ScriptedUserInputStep.cs, dotnet/samples/GettingStartedWithProcesses/Step01/Step01_Processes.cs, dotnet/samples/GettingStartedWithProcesses/Step02/Step02_AccountOpening.cs
Fixing processes sample 01 to emit exit event conditionally
=> .Net: Processes fixing sample 1 to emit exit event

dotnet/nuget/nuget-package.props
=> .Net: Version 1.24.0

dotnet/notebooks/00-getting-started.ipynb, dotnet/notebooks/01-basic-loading-the-kernel.ipynb, dotnet/notebooks/02-running-prompts-from-file.ipynb, dotnet/notebooks/03-semantic-function-inline.ipynb, dotnet/notebooks/04-kernel-arguments-chat.ipynb, dotnet/notebooks/05-using-the-planner.ipynb, dotnet/notebooks/06-memory-and-embeddings.ipynb, dotnet/notebooks/07-DALL-E-3.ipynb, dotnet/notebooks/08-chatGPT-with-DALL-E-3.ipynb, dotnet/notebooks/09-memory-with-chroma.ipynb, dotnet/notebooks/10-BingSearch-using-kernel.ipynb, dotnet/notebooks/config/settings.json.openai-example
=> .Net: Update .NET notebooks to use release 1.23.0

dotnet/samples/Concepts/ChatCompletion/OpenAI_StructuredOutputs.cs
Resolves: https://github.com/microsoft/semantic-kernel/issues/9102
=> .Net: Added example of Structured Outputs with Azure OpenAI

dotnet/samples/Concepts/ChatCompletion/AzureOpenAIWithData_ChatCompletion.cs
This PR contains a change with an example how to get citations from Azure OpenAI chat completion with data response.
=> .Net: Added an example how to get citations from chat with data response

python/semantic_kernel/agents/open_ai/open_ai_assistant_base.py, python/tests/unit/agents/test_open_ai_assistant_base.py
An agent terminal status was misspelled: canceled -> cancelled
Fixing the spelling.
=> Python: Fix cancelled typo

dotnet/src/Functions/Functions.OpenApi/OpenApiKernelPluginFactory.cs, dotnet/src/Functions/Functions.UnitTests/OpenApi/Extensions/OpenApiKernelExtensionsTests.cs, dotnet/src/Functions/Functions.UnitTests/OpenApi/OpenApiKernelPluginFactoryTests.cs, dotnet/src/IntegrationTests/Plugins/Web/Google/GoogleTextSearchTests.cs
=> .Net: Add the server urls to the additional properties

python/semantic_kernel/__init__.py
Bump Python version to 1.12.0 for a release.
Bump Python version to 1.12.0 for a release.
=> Python: Bump Python version to 1.12.0 for a release.

dotnet/src/Experimental/Process.UnitTests/Core/ProcessBuilderTests.cs, dotnet/src/Experimental/Process.UnitTests/Core/ProcessEdgeBuilderTests.cs, dotnet/src/Experimental/Process.UnitTests/Core/ProcessStepBuilderTests.cs, dotnet/src/Experimental/Process.UnitTests/Core/ProcessStepEdgeBuilderTests.cs, dotnet/src/Experimental/Process.UnitTests/Core/ProcessTypeExtensionsTests.cs, dotnet/src/Experimental/Process.UnitTests/Runtime.Local/LocalProcessTests.cs
Wanted to introduce additional _headroom_ for adding unit-tests as the _Process_ project structure becomes more complex.
- Isolated _Core_, _Shared_, and _Local Runtime_ tests.
**Namespaces:**
**Tests:**
=> .Net Processes - Updated unit-tests folder/file grouping

python/semantic_kernel/__init__.py
Increment Python version to 1.12.1 for a release.
Increment Python version to 1.12.1 for a release.
=> Python: Increment Python version to 1.12.1.

dotnet/Directory.Packages.props, dotnet/src/Connectors/Connectors.AzureAIInference.UnitTests/Core/ChatClientCoreTests.cs, dotnet/src/Connectors/Connectors.AzureAIInference/Core/ChatClientCore.cs, dotnet/src/Connectors/Connectors.AzureAIInference/Settings/AzureAIInferencePromptExecutionSettings.cs
=> .Net: Update Azure AI Inference to beta.2

dotnet/nuget/nuget-package.props
Version bump for 1.26.0 release
=> .Net: Version 1.26.0

.github/_typos.toml, dotnet/src/Agents/UnitTests/Core/History/MockHistoryGenerator.cs
Fixed typos that are blocking other PRs from merge due to Spell Checker.
=> .Net: Fixed typos

dotnet/samples/Concepts/FunctionCalling/FunctionCalling.cs, dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/RequiredFunctionChoiceBehavior.cs
Align the function calling documentation with the version to be published on the Learn portal and remove any unused code.
=> .Net: Function calling clean-up

dotnet/samples/GettingStartedWithVectorStores/GettingStartedWithVectorStores.csproj, dotnet/samples/GettingStartedWithVectorStores/Step3_Switch_VectorStore.cs, dotnet/samples/GettingStartedWithVectorStores/Step4_NonStringKey_VectorStore.cs, dotnet/samples/GettingStartedWithVectorStores/Step5_Use_GenericDataModel.cs, dotnet/samples/GettingStartedWithVectorStores/Step6_Use_CustomMapper.cs
#7606
- Add a non string key common code step
- Add a generic data model step
- Add a custom mapper step
=> .Net: Add more steps to getting started project.

dotnet/samples/Concepts/Resources/what-is-semantic-kernel.json, dotnet/src/InternalUtilities/src/Data/VectorStoreRecordMapping.cs, dotnet/src/SemanticKernel.Abstractions/Contents/ChatMessageContent.cs
A few typos in comments and samples
=> .Net: Fix typos

dotnet/samples/Demos/OnnxSimpleRAG/OnnxSimpleRAG.csproj, dotnet/samples/Demos/OnnxSimpleRAG/Program.cs
#9377
Update ONNX Rag sample to use vector store.
=> .Net: Update ONNX Rag sample to use vector store.

dotnet/nuget/nuget-package.props
Version bump for the 1.27.0 release
=> .Net: Version 1.27.0

dotnet/src/Connectors/Connectors.MistralAI.UnitTests/Client/MistralClientTests.cs, dotnet/src/Connectors/Connectors.MistralAI/Client/MistralClient.cs, dotnet/src/Connectors/Connectors.MistralAI/Connectors.MistralAI.csproj, dotnet/src/Connectors/Connectors.MistralAI/Services/MistralAIChatCompletionService.cs, dotnet/src/Connectors/Connectors.MistralAI/Services/MistralAITextEmbeddingGenerationService.cs
First step in updating the MistralAI connector to use the function calling processor
1. Some code clean up
2. Add the FunctionCallsProcessor
=> .Net: First step in moving to use function calling processor

.github/workflows/dotnet-ci.yml, .github/workflows/dotnet-integration-tests.yml
Breaking changes coming to the GitHub Actions product. [Details are posted in the GitHub Changelog](https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/). If you use the upload-artifact or download-artifact actions, be sure you have updated your workflows to v4
Closes #9563
=> Upgrade the upload-artifact or download-artifact actions

dotnet/nuget/nuget-package.props
=> .Net: Version 1.28.0

python/semantic_kernel/__init__.py
Bump Python version to 1.14.0 for a release.
Bump Python version to 1.14.0 for a release.
=> Python: Bump Python version to 1.14.0 for a release.

dotnet/src/Functions/Functions.UnitTests/OpenApi/Extensions/OpenApiKernelExtensionsTests.cs, dotnet/src/Functions/Functions.UnitTests/OpenApi/OpenApiKernelPluginFactoryTests.cs
=> .Net: Fix unit tests to check for security property

.github/workflows/dotnet-integration-tests-processes.yml
Adding workflow for automated integration testing of Processes across all supported runtimes.
=> Adding workflow for integration testing processes in all runtimes.

dotnet/src/Experimental/Process.Runtime.Dapr/Actors/ProcessActor.cs, dotnet/src/InternalUtilities/process/Runtime/ProcessEvent.cs
This PR fixes two issues our integration tests in the Dapr runtime. All tests pass after this change is applied.
=> .Net: Processes - Resolving issues with integrations test in Dapr runtime.

dotnet/src/Agents/OpenAI/Internal/AssistantThreadActions.cs
Fixes: https://github.com/microsoft/semantic-kernel/issues/9638
`System.ArgumentException: An item with the same key has already been added. ` - Duplicate key added when processing function result.
The processing loop for assistant streaming is selecting completed steps which is resulting in over-processing that violates the state-tracking.  This was due to leveraging the existing utiility method `GetRunStepsAsync`.   I removed this method in favor of inline invocation since the processing for Streaming and Non-Streaming have distinct considerations.  Also, as the SDK has evolved (paging removed), the utility method isn't adding much value.
> Note: Was able to reproduce reported issue by setting `ParallelToolCallsEnabled = false` on `OpenAIAssistant_Streaming` demo and verify fix. …
=> .Net Agents - Fix Function Call Handling for Streaming

dotnet/nuget/nuget-package.props
Bump version number to 1.29.0 for weekly release
=> .Net: Bump version to 1.29.0

python/samples/concepts/search/google_text_search_as_plugin.py, python/semantic_kernel/connectors/search/bing/bing_search.py, python/semantic_kernel/connectors/search/google/__init__.py, python/semantic_kernel/connectors/search/google/const.py, python/semantic_kernel/connectors/search/google/google_search.py, python/semantic_kernel/connectors/search/google/google_search_response.py, python/semantic_kernel/connectors/search/google/google_search_result.py, python/semantic_kernel/connectors/search/google/google_search_settings.py
This adds a new version of the Google Search implementation based on the new Text Search interfaces.
Easily create a plugin from the different search functions to perform RAG with online docs!
Closes #6834 
Creates a new folder under connectors.search for Google.
Adds GoogleSearch
Adds classes to capture the response.
Adds constants for the query parameters
Adds a sample showing how to use it with a filter.
=> Python: Introducing Google Search as a Text Search implementation

python/semantic_kernel/__init__.py
Bump py version to 1.15.0 for a release.
Bump py version to 1.15.0 for a release.
=> Python: Bump py version to 1.15.0 for a release.

python/samples/demos/README.md
Update the samples/demos readme.
Update the samples/demos readme.
=> Python: Update the samples/demos readme.

dotnet/samples/Concepts/ChatCompletion/AzureOpenAIWithData_ChatCompletion.cs
Related: https://github.com/microsoft/semantic-kernel/discussions/9728
Updated streaming example of Azure chat completion with data to show how to get citations in streaming mode.
=> .Net: Updated streaming example of Azure chat completion with data

dotnet/samples/Concepts/Filtering/TelemetryWithFilters.cs
Improved an example with telemetry in filters for streaming scenario to return streaming chunks from filter to operation's origin and logging the result at the same time.
=> .Net: Improved example with telemetry in filters for streaming scenario

dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordCollection.cs, dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorStoreFixture.cs, dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorStoreRecordCollectionTests.cs
#9799
Missed the mapping for enumerable strings for index creation, so needed to add it, and a proper check for unsupported types.
=> .Net: Fix bug where filtered tag field throws.

dotnet/src/Connectors/Connectors.Memory.Kusto/KustoMemoryStore.cs
A typo is causing the spell check in our pipeline to fail, thus block PRs.
Fix the typo.
=> .Net: Fix typo

.github/workflows/codeql-analysis.yml
CodeQL Action v2 will be deprecated on December 5th, 2024. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
=> Update codeql actions to v3

dotnet/nuget/nuget-package.props
=> .Net: Version 1.31.0

python/semantic_kernel/__init__.py
Bump Python version to 1.17.0 for a release.
Bump Python version to 1.17.0 for a release.
=> Python: Bump Python version to 1.17.0 for a release.

dotnet/nuget/nuget-package.props
Bump version number for a new release
=> .Net: Version 1.32.0

dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchHotel.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchTextSearchTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreFixture.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreRecordCollectionTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBMongoDB/AzureCosmosDBMongoDBHotel.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreFixture.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreRecordCollectionTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBNoSQL/AzureCosmosDBNoSQLVectorStoreTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/BaseVectorStoreTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/MongoDB/MongoDBHotel.cs, dotnet/src/IntegrationTests/Connectors/Memory/MongoDB/MongoDBVectorStoreFixture.cs, dotnet/src/IntegrationTests/Connectors/Memory/MongoDB/MongoDBVectorStoreRecordCollectionTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/MongoDB/MongoDBVectorStoreTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/Pinecone/PineconeVectorStoreTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorStoreTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisHashSetVectorStoreRecordCollectionTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisHotel.cs, dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisJsonVectorStoreRecordCollectionTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisVectorStoreFixture.cs, dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisVectorStoreTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/Sqlite/SqliteVectorStoreTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/Weaviate/WeaviateVectorStoreTests.cs, dotnet/src/IntegrationTests/testsettings.json
Resolves: https://github.com/microsoft/semantic-kernel/issues/6459
This PR adds a base class for vector store integration tests and updates all integration tests for concrete vector store to use common workflow.
=> .Net: Refactored integration tests for vector stores

dotnet/samples/Concepts/ChatCompletion/OpenAI_ChatCompletion.cs, dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Settings/AzureOpenAIPromptExecutionSettingsTests.cs, dotnet/src/Connectors/Connectors.AzureOpenAI/Core/AzureClientCore.ChatCompletion.cs, dotnet/src/Connectors/Connectors.OpenAI.UnitTests/Settings/OpenAIPromptExecutionSettingsTests.cs, dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.ChatCompletion.cs, dotnet/src/Connectors/Connectors.OpenAI/Settings/OpenAIPromptExecutionSettings.cs, python/semantic_kernel/connectors/ai/open_ai/prompt_execution_settings/open_ai_prompt_execution_settings.py
=> .Net: Add store and metadata properties to OpenAIPromptExecutionSettings

python/samples/concepts/chat_completion/simple_chatbot_store_metadata.py, python/semantic_kernel/connectors/ai/open_ai/prompt_execution_settings/open_ai_prompt_execution_settings.py
=> Python: Add store and metadata properties to OpenAIPromptExecutionSettings

.github/workflows/python-test-coverage-report.yml
The coverage report write job did not have the right permissions yet.
=> Python: add write token to report

python/semantic_kernel/connectors/memory/qdrant/qdrant_collection.py, python/tests/unit/connectors/memory/qdrant/test_qdrant.py
There was a small error in the filter creation logic, and improved test coverage for Qdrant.
=> Python: Qdrant - fix in filter and 100% test coverage

python/semantic_kernel/__init__.py
Bump Python version to 1.17.1 for a release.
Bump Python version to 1.17.1 for a release.
=> Python: Bump Python version to 1.17.1 for a release.

dotnet/src/Functions/Functions.OpenApi/RestApiOperationRunner.cs
Small refactoring of the `RestApiOperationRunner` class to simplify the review of the next PR related to the customization of operation response building.
=> .Net: RestApiOperationRunner refactoring

dotnet/nuget/nuget-package.props
=> .Net: Version 1.33.0

python/README.md
prompt_template_config needs PromptTemplateConfig type but req_settings is PromptExecutionSettings type which seems to be accepted better by prompt_execution_settings
=> Python: Update README.md

python/semantic_kernel/__init__.py
Bump Python version to 1.18.0 for a release.
Bump Python version to 1.18.0 for a release.
=> Python: Bump Python version to 1.18.0 for a release.

.github/_typos.toml
=> Do not exclude entire README from spell checking

dotnet/samples/LearnResources/Plugins/GitHub/GitHubPlugin.cs
=> .Net: Use UriKind.Relative

dotnet/samples/GettingStartedWithProcesses/Step00/Step00_Processes.cs
=> .Net: fix bug: Example Step00 of Process Framework is wrong

python/semantic_kernel/__init__.py
Bump Python version to 1.18.1 for a release.
Bump Python version to 1.18.1 for a release.
=> Python: Bump Python version to 1.18.1 for a release.

python/semantic_kernel/__init__.py
Bump Python version to 1.18.2 for a release.
Bump Python version to 1.18.2 for a release.
=> Python: Bump Python version to 1.18.2 for a release.

python/semantic_kernel/__init__.py
Bump Python version to 1.19.0 for a release.
Bump Python version to 1.19.0 for a release.
=> Python: Bump Python version to 1.19.0 for a release.

docs/decisions/0054-processes.md, dotnet/src/Connectors/Connectors.Ollama.UnitTests/Extensions/OllamaServiceCollectionExtensionsTests.cs, dotnet/src/Connectors/Connectors.Ollama/Extensions/OllamaServiceCollectionExtensions.cs
=> .Net: Adding Ollama extension for improved Aspire experience

docs/decisions/0054-processes.md, dotnet/nuget/nuget-package.props, dotnet/src/Connectors/VectorData.Abstractions/VectorData.Abstractions.csproj
=> .Net: Version 1.35.0

python/semantic_kernel/__init__.py
Bump Python version to 1.20.0 for a release.
Bump Python version to 1.20.0 for a release.
=> Python: Bump Python version to 1.20.0 for a release.

.github/workflows/label-needs-port.yml
=> updated ifs

.github/workflows/label-needs-port.yml
=> Fix needs port if

dotnet/samples/GettingStartedWithAgents/AzureAIAgent/Step02_AzureAIAgent_Chat.cs, dotnet/samples/GettingStartedWithAgents/AzureAIAgent/Step06_AzureAIAgent_Functions.cs, dotnet/src/Agents/AzureAI/Internal/AgentThreadActions.cs
Obseved the need to clean-up a couple azure agent samples
- Reconciled samples into same folder
- Removed extra sample history output (from testing)
- Removed call to `Console.WriteLine` in package (from testing)
=> .Net: Clean-up

dotnet/nuget/nuget-package.props
Patch release which includes bug fixes
=> .Net: Version bump for 1.36.1

dotnet/samples/Concepts/README.md
1. Why is this change required? Documentation is incorrect and a struggle for someone getting started
2. What problem does it solve? Someone new to the codebase would be confused by the documentation
3. What scenario does it contribute to? Someone new to the codebase would be confused by the documentation
ChatPromptSync does not exist.
=> .Net: Update GettingStarted Documentation

python/semantic_kernel/__init__.py
Bump Python version to 1.21.0 for a release.
Bump Python version to 1.21.0 for a release.
=> Python: Bump Python version to 1.21.0 for a release.

dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordCollection.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateConstants.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreCollectionSearchMapping.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreRecordCollection.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreRecordCollectionQueryBuilder.cs, dotnet/src/Connectors/Connectors.Weaviate.UnitTests/WeaviateVectorStoreCollectionSearchMappingTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantNamedVectorsKeywordVectorizedHybridSearchTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantSingleVectorKeywordVectorizedHybridSearchTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/Weaviate/WeaviateKeywordVectorizedHybridSearchTests.cs
#9399
- Add Qdrant keyword hybrid search
- Add Weaviate keyword hybrid search
- Add integrations tests for both.
=> .Net: Add qdrant and weaviate keyword hybrid search implementations and tests

dotnet/Directory.Packages.props, dotnet/src/Connectors/Connectors.AzureCosmosDBNoSQL.UnitTests/AzureCosmosDBNoSQLVectorStoreCollectionQueryBuilderTests.cs, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/AzureCosmosDBNoSQLVectorStoreCollectionQueryBuilder.cs, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/AzureCosmosDBNoSQLVectorStoreRecordCollection.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBNoSQL/AzureCosmosDBNoSQLConnectionStringSetConditionAttribute.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBNoSQL/AzureCosmosDBNoSQLKeywordVectorizedHybridSearchTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBNoSQL/AzureCosmosDBNoSQLVectorStoreFixture.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBNoSQL/AzureCosmosDBbNoSQLConnectionStringSetConditionAttribute.cs
#9399 
- Add an azure ComsosDB NoSQL hybrid search implementation using keywords
- Add integration tests and update unit tests.
- The required features to implement this is only available in preview versions of the SDK right now.
=> .Net: Add Azure CosmosDB NoSQL Hybrid Keyword Search

python/semantic_kernel/__init__.py
Bump Python version to 1.21.1 for a release.
Bump Python version to 1.21.1 for a release.
=> Python: Bump Python version to 1.21.1 for a release.

dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoDBVectorStoreCollectionCreateMapping.cs, dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoDBVectorStoreCollectionSearchMapping.cs, dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoDBVectorStoreRecordCollection.cs, dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoDBVectorStoreRecordCollectionOptions.cs, dotnet/src/IntegrationTests/Connectors/Memory/MongoDB/MongoDBKeywordVectorizedHybridSearchTests.cs, dotnet/src/InternalUtilities/connectors/Memory/MongoDB/MongoDBConstants.cs
#9399
- Add a MongoDB hybrid search implementation using keywords
- Add integration tests and update unit tests.
=> .Net: Add mongodb hybrid keyword search implementation

dotnet/src/Extensions/Extensions.UnitTests/PromptTemplates/Handlebars/HandlebarsPromptTemplateTests.cs, dotnet/src/Extensions/PromptTemplates.Handlebars/HandlebarsPromptTemplate.cs, dotnet/src/Extensions/PromptTemplates.Handlebars/HandlebarsPromptTemplateOptions.cs
=> .Net: Add option to disable automatic HTML decoding for Handlebars templates

dotnet/src/Extensions/PromptTemplates.Liquid/LiquidPromptTemplate.cs
=> .Net: Include developer role in parsing regex

dotnet/Directory.Packages.props, dotnet/samples/Concepts/ChatCompletion/HybridCompletion_Fallback.cs, dotnet/src/Connectors/Connectors.AzureAIInference.UnitTests/Services/AzureAIInferenceChatCompletionServiceTests.cs, dotnet/src/Connectors/Connectors.AzureAIInference/Settings/AzureAIInferencePromptExecutionSettings.cs, dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/AIFunctionKernelFunction.cs, dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatClientChatCompletionService.cs, dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatCompletionServiceChatClient.cs, dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatCompletionServiceExtensions.cs, dotnet/src/SemanticKernel.Abstractions/AI/Embeddings/EmbeddingGenerationServiceExtensions.cs, dotnet/src/SemanticKernel.Abstractions/AbstractionsJsonContext.cs, dotnet/src/SemanticKernel.Abstractions/Functions/KernelFunction.cs, dotnet/src/SemanticKernel.Abstractions/Functions/KernelFunctionSchemaModel.cs, dotnet/src/SemanticKernel.UnitTests/AI/ServiceConversionExtensionsTests.cs, dotnet/src/SemanticKernel.UnitTests/Functions/KernelPluginTests.cs
cc @RogerBarret0 @SergeyMenshykh
=> .Net: Update Microsoft.Extensions.AI packages to the latest version.

python/semantic_kernel/__init__.py
Bump Python version to 1.21.2 for a release.
Bump Python version to 1.21.2 for a release.
=> Python: Bump Python version to 1.21.2 for a release.

python/samples/concepts/reasoning/simple_reasoning.py, python/samples/concepts/reasoning/simple_reasoning_function_calling.py, python/semantic_kernel/filters/kernel_filters_extension.py
Small update to the reasoning samples, that leverages the latest updates to those api's.
Fixed typing issue in filters.
=> Python: updated reasoning samples

python/semantic_kernel/__init__.py
Bump Python version to 1.21.3 for a release.
Bump Python version to 1.21.3 for a release.
=> Python: Bump Python version to 1.21.3 for a release.

dotnet/nuget/nuget-package.props
=> Version 1.38.0

dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Services/AzureOpenAIChatCompletionServiceTests.cs, dotnet/src/Connectors/Connectors.AzureOpenAI/Core/AzureClientCore.ChatCompletion.cs, dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatCompletionStreamingTests.cs
=> .Net: Fix Usage Tokens in AzureOpenAI Connector - Added UT + IT's

dotnet/src/Agents/Abstractions/Definition/AgentDefinition.cs, dotnet/src/Agents/Abstractions/Definition/AgentToolDefinition.cs, dotnet/src/Agents/Abstractions/Definition/KernelAgentFactory.cs, dotnet/src/Agents/Abstractions/Definition/ModelConfiguration.cs, dotnet/src/Agents/Abstractions/Definition/ModelDefinition.cs, dotnet/src/Agents/AzureAI/Definition/AzureAIAgentFactory.cs, dotnet/src/Agents/Core/Definition/AggregatorKernelAgentFactory.cs, dotnet/src/Agents/Core/Definition/ChatCompletionAgentFactory.cs, dotnet/src/Agents/OpenAI/Definition/OpenAIAssistantAgentFactory.cs, dotnet/src/Agents/Yaml/AgentDefinitionYaml.cs, dotnet/src/Agents/Yaml/Agents.Yaml.csproj, dotnet/src/Agents/Yaml/Properties/AssemblyInfo.cs, dotnet/src/SemanticKernel.Abstractions/PromptTemplate/InputVariable.cs
Flag all declarative agent code as experimental
=> .Net: Feature declarative agents experimental

dotnet/src/Agents/Abstractions/Definition/AgentDefinition.cs, dotnet/src/Agents/Abstractions/Definition/AgentToolDefinition.cs, dotnet/src/Agents/Abstractions/Definition/ModelConfiguration.cs, dotnet/src/Agents/Abstractions/Definition/ModelDefinition.cs, dotnet/src/Agents/Abstractions/Extensions/AgentDefinitionExtensions.cs, dotnet/src/Agents/AzureAI/Extensions/AgentDefinitionExtensions.cs
Allow properties to be set to null values.
=> .Net: Simplify the model classes for the declarative agent definition

dotnet/samples/Concepts/Filtering/AzureOpenAI_DeploymentSwitch.cs
=> .Net: Use Contoso endpoints

dotnet/src/Agents/OpenAI/Agents.OpenAI.csproj
Adding missing preview suffix for Agent.OpenAI.
=> .Net: Adding preview package suffix to Agents.OpenAI.

python/semantic_kernel/__init__.py
Bump Python version to 1.22.0 for a release.
Bump Python version to 1.22.0 for a release.
=> Python: Bump Python version to 1.22.0 for a release.

dotnet/src/Agents/AzureAI/Extensions/AgentDefinitionExtensions.cs, dotnet/src/Agents/AzureAI/Extensions/AgentToolDefinitionExtensions.cs, dotnet/src/Agents/UnitTests/Yaml/AzureAIKernelAgentYamlTests.cs
Add support to deserialize all Azure AI tool types
=> .Net: Add support to deserialize all Azure AI tool types

dotnet/nuget/nuget-package.props, dotnet/src/Agents/Abstractions/Agents.Abstractions.csproj
=> .Net: Use preview suffix for Agents abstractions

python/semantic_kernel/__init__.py, python/semantic_kernel/connectors/ai/azure_ai_inference/services/azure_ai_inference_chat_completion.py, python/tests/unit/connectors/ai/hugging_face/test_hf_text_completions.py
Bump Python version to 1.22.1 for a release
Bump Python version to 1.22.1 for a release
=> Python: Bump Python version to 1.22.1 for a release

.github/workflows/python-build.yml
=> Trigger ado

.github/workflows/python-manual-release.yml
=> add manual release pipeline

.github/workflows/python-manual-release.yml
=> permission and env

.github/workflows/python-build.yml, .github/workflows/python-manual-release.yml
=> updated command

.github/workflows/python-build.yml, .github/workflows/python-manual-release.yml
=> fixed variables

python/semantic_kernel/__init__.py
Version bump to 1.23.0
And rc3
=> Python: bump version

python/pyproject.toml, python/uv.lock
fix #10848 
When importing anything from semantic_kernel.connectors.ai.openai it already needs websocket and aiortc, so moved those.
Kept the extra for now, while we build a more sustainable fix.
=> Python: fix for import without realtime extra

docs/decisions/0067-hybrid-search.md
Update Hybrid Search ADR with latest decisions and rename.
=> Update Hybrid Search ADR with latest decisions and rename.

python/pyproject.toml, python/samples/concepts/agents/azure_ai_agent/azure_ai_agent_azure_ai_search.py, python/samples/concepts/agents/azure_ai_agent/azure_ai_agent_file_manipulation.py, python/samples/concepts/agents/azure_ai_agent/azure_ai_agent_streaming.py, python/semantic_kernel/agents/azure_ai/agent_content_generation.py, python/semantic_kernel/agents/azure_ai/agent_thread_actions.py, python/semantic_kernel/contents/annotation_content.py, python/semantic_kernel/contents/streaming_annotation_content.py, python/tests/unit/agents/azure_ai_agent/test_agent_content_generation.py, python/tests/unit/agents/azure_ai_agent/test_agent_thread_actions.py, python/tests/unit/contents/test_annotation_content.py, python/tests/unit/contents/test_streaming_annotation_content.py, python/uv.lock
The Azure Python SDK made an underlying change to move away from `assistant_id` keyword arguments to now support `agent_id` keyword arguments. Additionally, they now support a `MessageTextUrlCitationAnnotation` and `MessageDeltaTextUrlCitationAnnotation` for annotations.
Update the `AzureAIAgent` to pass in `agent_id` in place of `assistant_id`, and bring in support for the new annotation types.
- Updates samples to simpler patterns where needed.
- Updates unit tests.
- Closes #10852
Validated that our [AzureAIAgent + Azure AI Search sample](https://github.com/microsoft/semantic-kernel/blob/main/python/samples/concepts/agents/azure_ai_agent/azure_ai_agent_azure_ai_search.py) works properly:
---
```markdown
1. **Extended Stay Suites** - All suites include full-sized kitchens stocked with …
```
=> Python: Support AzureAIAgent agent_id instead of assistant_id

python/semantic_kernel/__init__.py
Bump Python version to 1.24.0 for a release.
Bump Python version to 1.24.0 for a release.
=> Python: Bump Python version to 1.24.0 for a release.

python/semantic_kernel/__init__.py
Bump Python version to 1.24.1 and rc3 for a release
Bump Python version to 1.24.1 and rc3 for a release
=> Python: Bump Python version to 1.24.1 and rc3 for a release

dotnet/src/Connectors/VectorData.Abstractions/VectorStorage/IVectorStore.cs, dotnet/src/Connectors/VectorData.Abstractions/VectorStorage/IVectorStoreRecordCollection.cs
=> .Net: [TINY] Document the default thread-safety expectation for the MEVD abstractions

dotnet/src/Experimental/Process.UnitTests/Runtime.Local/LocalMapTests.cs, dotnet/src/Experimental/Process.UnitTests/Runtime.Local/LocalProxyTests.cs, dotnet/src/InternalUtilities/process/TestsShared/Kernels/KernelSetup.cs, dotnet/src/InternalUtilities/process/TestsShared/Services/CounterService.cs, dotnet/src/InternalUtilities/process/TestsShared/Services/ICounterService.cs, dotnet/src/InternalUtilities/process/TestsShared/Setup/KernelSetup.cs, dotnet/src/InternalUtilities/process/TestsShared/Steps/CommonSteps.cs
Fixing intermittent build failure caused by Process Local Unittest that used shared Counter Step
Fixes #11019
=> .Net: Processes UTs causing Build pipeline errors

dotnet/nuget/nuget-package.props
Version bump for 1.42.0 release
=> .Net: Version 1.42.0

dotnet/src/Connectors/Connectors.Memory.SqlServer/ExceptionWrapper.cs, dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerCommandBuilder.cs, dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerConstants.cs, dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerVectorStoreRecordCollection.cs, dotnet/src/VectorDataIntegrationTests/SqlServerIntegrationTests/CRUD/SqlServerBatchConformanceTests.cs, dotnet/src/VectorDataIntegrationTests/SqlServerIntegrationTests/SqlServerCommandBuilderTests.cs, dotnet/src/VectorDataIntegrationTests/VectorDataIntegrationTests/CRUD/BatchConformanceTests.cs
=> .Net MEVD: Split batches to account for the SQL Server 2100 parameter limit

.github/.linkspector.yml, README.md, docs/PLUGINS.md, docs/PROMPT_TEMPLATE_LANGUAGE.md, docs/decisions/0008-support-generic-llm-request-settings.md, dotnet/samples/Concepts/README.md, dotnet/samples/Demos/AIModelRouter/README.md, dotnet/samples/Demos/BookingRestaurant/README.md, dotnet/samples/Demos/TimePlugin/README.md, dotnet/samples/GettingStartedWithAgents/README.md
This PR fixes links that were found unreachable by `linkspector`:
https://github.com/microsoft/semantic-kernel/actions/runs/13954045797/job/39063140670?pr=11055
=> .Net: Fixed links

.github/workflows/codeql-analysis.yml, .github/workflows/dotnet-build-and-test.yml, .github/workflows/dotnet-ci.yml, .github/workflows/dotnet-format.yml, .github/workflows/dotnet-integration-tests.yml, .github/workflows/markdown-link-check.yml, .github/workflows/typos.yaml
=> Use checkout with persist-credentials: false

dotnet/samples/Concepts/ChatCompletion/AzureOpenAIWithData_ChatCompletion.cs, dotnet/samples/Concepts/ChatCompletion/ChatHistoryInFunctions.cs
=> .Net: Avoid using test.com is samples and tests

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/Connectors.Memory.AzureAISearch.csproj, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/Connectors.Memory.AzureCosmosDBMongoDB.csproj, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/Connectors.Memory.AzureCosmosDBNoSQL.csproj, dotnet/src/Connectors/Connectors.Memory.Chroma/Connectors.Memory.Chroma.csproj, dotnet/src/Connectors/Connectors.Memory.DuckDB/Connectors.Memory.DuckDB.csproj, dotnet/src/Connectors/Connectors.Memory.InMemory/Connectors.Memory.InMemory.csproj, dotnet/src/Connectors/Connectors.Memory.Kusto/Connectors.Memory.Kusto.csproj, dotnet/src/Connectors/Connectors.Memory.Milvus/Connectors.Memory.Milvus.csproj, dotnet/src/Connectors/Connectors.Memory.MongoDB/Connectors.Memory.MongoDB.csproj, dotnet/src/Connectors/Connectors.Memory.Pinecone/Connectors.Memory.Pinecone.csproj, dotnet/src/Connectors/Connectors.Memory.Postgres/Connectors.Memory.Postgres.csproj, dotnet/src/Connectors/Connectors.Memory.Postgres/PostgresVectorStoreDbClient.cs, dotnet/src/Connectors/Connectors.Memory.Qdrant/Connectors.Memory.Qdrant.csproj, dotnet/src/Connectors/Connectors.Memory.Qdrant/Http/ApiSchema/GetVectorsRequest.cs, dotnet/src/Connectors/Connectors.Memory.Redis/Connectors.Memory.Redis.csproj, dotnet/src/Connectors/Connectors.Memory.Redis/RedisFilterTranslator.cs, dotnet/src/Connectors/Connectors.Memory.SqlServer/Connectors.Memory.SqlServer.csproj, dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerCommandBuilder.cs, dotnet/src/Connectors/Connectors.Memory.Sqlite/Connectors.Memory.Sqlite.csproj, dotnet/src/Connectors/Connectors.Memory.Sqlite/SqliteVectorStoreCollectionCommandBuilder.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/Connectors.Memory.Weaviate.csproj, dotnet/src/Connectors/Connectors.OpenAI/Services/OpenAIFileService.cs, dotnet/src/InternalUtilities/src/Diagnostics/IsExternalInit.cs, dotnet/src/InternalUtilities/src/Diagnostics/UnreachableException.cs, dotnet/src/InternalUtilities/src/System/IndexRange.cs, dotnet/src/SemanticKernel.Abstractions/Services/EmptyServiceProvider.cs
Aligning with MEAI; this helps netfx users under net472 ([link](https://github.com/roji/semantic-kernel/pull/new/net462)).
=> .Net: Target net462 in all MEVD connectors

dotnet/src/Connectors/Connectors.Amazon.UnitTests/Services/BedrockTextEmbeddingGenerationServiceTests.cs
The given test was giving a false negative in environments where Bedrock Runtime was property configured and could be retrieved from the DI container. 
This change ensures this test only executes when the environment has no runtime configured to be recovered from the DI container.
=> .Net: Fix Amazon Bedrock UT

dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/KernelCore/KernelTests.cs, dotnet/src/Connectors/Connectors.OpenAI.UnitTests/KernelCore/KernelTests.cs
=> .Net: Fix unstable {Azure}OpenAI telemetry UT

dotnet/Directory.Packages.props, dotnet/src/Agents/Bedrock/BedrockAgent.cs
=> .Net: Fixing AWS package versions

.github/workflows/dotnet-integration-tests.yml, dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/AzureAIAgentFixture.cs, dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/InvokeConformance/InvokeTests.cs
Use AI Project which is set up for integration testing
=> .Net: Set the AzureAI:ConnectionString from secrets

python/.cspell.json, python/samples/concepts/agents/bedrock_agent/bedrock_agent_with_code_interpreter.py, python/samples/concepts/agents/bedrock_agent/bedrock_agent_with_code_interpreter_streaming.py, python/samples/concepts/agents/bedrock_agent/bedrock_agent_with_kernel_function.py, python/samples/concepts/agents/bedrock_agent/bedrock_agent_with_kernel_function_simple.py, python/samples/concepts/agents/bedrock_agent/bedrock_agent_with_kernel_function_streaming.py, python/samples/concepts/agents/bedrock_agent/bedrock_mixed_chat_agents.py, python/samples/concepts/agents/bedrock_agent/bedrock_mixed_chat_agents_streaming.py, python/semantic_kernel/agents/agent.py, python/semantic_kernel/agents/bedrock/bedrock_agent.py, python/semantic_kernel/agents/channels/chat_history_channel.py, python/tests/unit/agents/bedrock_agent/test_bedrock_agent_channel.py
All Unit tests are passing.
All Bedrock Agent integration tests are passing.
All Bedrock agent samples are running.
=> Python: Fix Bedrock agent

dotnet/samples/Demos/AgentFrameworkWithAspire/ChatWithAgent.ApiService/Controllers/AgentCompletionsController.cs
=> .Net: Update AgentCompletionsController Sample to use new invocation approach

python/semantic_kernel/__init__.py
=> Python: Bump Python version to 1.26.0 and RC to RC4 for a release.

python/samples/getting_started_with_agents/azure_ai_agent/step1_azure_ai_agent.py, python/samples/learn_resources/agent_docs/chat_agent.py
Following the latest updates for the Common Agent Invocation API feature, one AzureAIAgent sample was not configured properly.
Update the sample so the response doesn't show twice. Should print the agent name and then the response.
=> Python: Update AzureAIAgent sample

dotnet/samples/GettingStartedWithAgents/AzureAIAgent/Step08_AzureAIAgent_Declarative.cs, dotnet/samples/GettingStartedWithAgents/BedrockAgent/Step07_BedrockAgent_Declarative.cs, dotnet/samples/GettingStartedWithAgents/OpenAIAssistant/Step07_Assistant_Declarative.cs, dotnet/samples/GettingStartedWithAgents/Step08_Declarative.cs, dotnet/samples/GettingStartedWithAgents/Step09_MultiAgent_Declarative.cs, dotnet/src/Agents/UnitTests/Core/Factory/AggregatorKernelAgentFactoryTests.cs, dotnet/src/InternalUtilities/samples/AgentUtilities/BaseBedrockAgentTest.cs
Use the new `Agent.InvokeAsync` pattern.
=> .Net: Update the getting started samples to use the new Agent invoke API

dotnet/nuget/nuget-package.props
Publishing a new version of the Semantic Kernel to include new API's
=> .Net: Bump to version 1.44.0

dotnet/src/Plugins/Plugins.Core/CodeInterpreter/SessionsPythonPlugin.cs
Added missing KernelFunction attribute to DownloadFileAsync in SessionsPythonPlugin
=> .Net: Added missing KernelFunction attribute to DownloadFileAsync in SessionsPythonPlugin

dotnet/samples/GettingStartedWithAgents/README.md
Typo "Azure Open AI"→"Azure OpenAI"
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/GettingStartedWithAgents/README.md #PingMSFTDocs
=> .Net: Update README.md (Typo "Azure Open AI"→"Azure OpenAI")

dotnet/samples/GettingStartedWithAgents/AzureAIAgent/Step01_AzureAIAgent.cs
=> .Net: Switch from hardcoded model id

dotnet/src/Connectors/Connectors.Pinecone.UnitTests/PineconeClientTests.cs
=> .Net: Preb2 fix obsolete warnings

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreRecordCollection.cs, dotnet/src/VectorDataIntegrationTests/AzureAISearchIntegrationTests/AzureAISearchIntegrationTests.csproj, dotnet/src/VectorDataIntegrationTests/AzureAISearchIntegrationTests/CRUD/AzureAISearchBatchConformanceTests.cs, dotnet/src/VectorDataIntegrationTests/AzureAISearchIntegrationTests/CRUD/AzureAISearchRecordConformanceTests.cs, dotnet/src/VectorDataIntegrationTests/AzureAISearchIntegrationTests/Support/AzureAISearchSimpleModelFixture.cs, dotnet/src/VectorDataIntegrationTests/AzureAISearchIntegrationTests/Support/AzureAISearchTestEnvironment.cs, dotnet/src/VectorDataIntegrationTests/AzureAISearchIntegrationTests/Support/AzureAISearchTestStore.cs, dotnet/src/VectorDataIntegrationTests/AzureAISearchIntegrationTests/Support/AzureAISearchUrlRequiredAttribute.cs, dotnet/src/VectorDataIntegrationTests/CosmosMongoDBIntegrationTests/CRUD/CosmosMongoDBBatchConformanceTests.cs, dotnet/src/VectorDataIntegrationTests/CosmosMongoDBIntegrationTests/CRUD/CosmosMongoDBRecordConformanceTests.cs, dotnet/src/VectorDataIntegrationTests/CosmosMongoDBIntegrationTests/Support/CosmosMongoDBSimpleModelFixture.cs, dotnet/src/VectorDataIntegrationTests/MongoDBIntegrationTests/CRUD/MongoDBBatchConformanceTests.cs, dotnet/src/VectorDataIntegrationTests/MongoDBIntegrationTests/CRUD/MongoDBRecordConformanceTests.cs, dotnet/src/VectorDataIntegrationTests/MongoDBIntegrationTests/Support/MongoDBSimpleModelFixture.cs
contributes to https://github.com/microsoft/semantic-kernel/issues/10194
=> .Net MEVD: More conformance tests coverage

python/samples/concepts/README.md, python/samples/concepts/agents/azure_ai_agent/azure_ai_agent_structured_outputs.py
Add AzureAIAgent Structured Outputs sample
Add AzureAIAgent Structured Outputs sample
=> Python: Add AzureAIAgent Structured Outputs sample

dotnet/src/Agents/Abstractions/Agents.Abstractions.csproj, dotnet/src/Agents/Core/Agents.Core.csproj
Remove the Agent preview suffix
=> .Net: Remove the Agent preview suffix

dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantFilterTranslator.cs, dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreCollectionCreateMapping.cs, dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreCollectionSearchMapping.cs, dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordFieldMapping.cs, dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantVectorStoreRecordMapperTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorStoreFixture.cs, dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorStoreRecordCollectionTests.cs
#11086
Adding datetime & datetimeoffset support for CRUD operations with Qdrant.
Also supporting filtering with legacy filter options, to test end to end scenario.
LINQ based filtering to follow in separate PR.
=> .Net: Qdrant CRUD datetime support

dotnet/nuget/nuget-package.props
Version bump for release 1.45.0
=> .Net: Version 1.45.0

dotnet/samples/GettingStartedWithAgents/Step09_Declarative.cs, dotnet/samples/GettingStartedWithAgents/Step10_MultiAgent_Declarative.cs, dotnet/src/IntegrationTests/Agents/AzureAIAgentTests.cs, dotnet/src/IntegrationTests/Agents/ChatCompletionAgentTests.cs, dotnet/src/IntegrationTests/Agents/OpenAIAssistantAgentTests.cs, dotnet/src/IntegrationTests/IntegrationTests.csproj
Integration tests for declarative agents
=> .Net: Integration tests for declarative agents

dotnet/samples/GettingStartedWithAgents/OpenAIResponse/Step02_ConversationState.cs, dotnet/src/Agents/OpenAI/Extensions/ResponseItemExtensions.cs, dotnet/src/Agents/OpenAI/OpenAIResponseAgent.cs, dotnet/src/Agents/OpenAI/OpenAIResponseAgentThread.cs, dotnet/src/InternalUtilities/samples/AgentUtilities/BaseResponsesAgentTest.cs
1. `MergeArguments` was made internal so I have made a copy for now but I need to change this code so it can be shared in the main branch.
2. Also did some clean-up of the getting started samples.
=> .Net: Fixes required after latest update from main

python/samples/demos/document_generator/README.md, python/samples/demos/document_generator/agents/code_validation_agent.py, python/samples/demos/document_generator/agents/content_creation_agent.py, python/samples/demos/document_generator/agents/custom_agent_base.py, python/samples/demos/document_generator/agents/user_agent.py, python/samples/demos/document_generator/custom_selection_strategy.py
The current document generator demo is using old agent invocation API patterns. This PR updates the demo to use the latest API abstractions with SK's current group chat patterns.
Update the demo.
=> Python: Update Doc Gen demo based on latest agent invocation api pattern

dotnet/src/Plugins/Plugins.Core/FileIOPlugin.cs, dotnet/src/Plugins/Plugins.UnitTests/Core/FileIOPluginTests.cs
1. `AllowedFolders` - Provide control over which folders can be written to 
2. `DisableFileOverwrite` - Disable overwriting existing files
=> .Net: Updates to FileIOPlugin

dotnet/Directory.Packages.props, dotnet/samples/Concepts/ChatCompletion/AzureAIInference_ChatCompletion.cs, dotnet/samples/Concepts/ChatCompletion/AzureAIInference_ChatCompletionStreaming.cs, dotnet/samples/Concepts/ChatCompletion/HybridCompletion_Fallback.cs, dotnet/src/Connectors/Connectors.AzureAIInference.UnitTests/Extensions/AzureAIInferenceServiceCollectionExtensionsTests.cs, dotnet/src/Connectors/Connectors.AzureAIInference/Extensions/AzureAIInferenceServiceCollectionExtensions.cs, dotnet/src/Connectors/Connectors.AzureAIInference/Services/AzureAIInferenceChatCompletionService.cs, dotnet/src/InternalUtilities/src/Schema/KernelJsonSchemaBuilder.cs, dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/AIFunctionKernelFunction.cs, dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatClientChatCompletionService.cs, dotnet/src/SemanticKernel.Abstractions/AI/Embeddings/EmbeddingGenerationServiceExtensions.cs, dotnet/src/SemanticKernel.Abstractions/Functions/KernelFunction.cs, dotnet/src/SemanticKernel.UnitTests/AI/ChatCompletion/AIFunctionKernelFunctionTests.cs, dotnet/src/SemanticKernel.UnitTests/AI/ServiceConversionExtensionsTests.cs, dotnet/src/SemanticKernel.UnitTests/Functions/AIFunctionExtensionsTests.cs, dotnet/src/SemanticKernel.UnitTests/Functions/KernelFunctionFromMethodTests1.cs, dotnet/src/SemanticKernel.UnitTests/Functions/KernelPluginTests.cs
Upgrade for latest version of MEAI 9.4.0
=> .Net: Update Microsoft.Extensions.AI to 9.4.0-preview

dotnet/nuget/nuget-package.props
Version bump for release 1.46.0
=> .Net: Version 1.46.0

dotnet/Directory.Packages.props, dotnet/samples/Demos/ModelContextProtocolClientServer/MCPClient/Program.cs, dotnet/samples/Demos/ModelContextProtocolClientServer/MCPServer/Prompts/PromptDefinition.cs, dotnet/samples/Demos/ModelContextProtocolPlugin/Program.cs
Update, SK MCP samples to the latest MCP C# SDK.
=> .Net: Update SK MCP samples to the latest MCP C# SDK NuGet package

python/semantic_kernel/__init__.py
Updated the version of the package to 1.28
=> Python: version updated to 1.28.0

dotnet/src/Agents/Catalog/Template/CustomServiceAgent.cs
I fixed minor typos in the prompt to ensure clarity, which helps in better understanding and usage of the prompt. The underlying design remains unchanged, but the readability of the document is improved.
=> .Net: Fix minor typos

dotnet/src/Agents/Abstractions/Definition/AgentDefinition.cs, dotnet/src/Agents/Abstractions/Definition/AgentInput.cs, dotnet/src/Agents/Abstractions/Definition/AgentOutput.cs, dotnet/src/Agents/Abstractions/Definition/AgentToolDefinition.cs, dotnet/src/Agents/Abstractions/Definition/ModelDefinition.cs, dotnet/src/SemanticKernel.Abstractions/PromptTemplate/TemplateOptions.cs
Align with documentation created for the schema.
=> .Net: Update API documentation and add the type property

dotnet/nuget/nuget-package.props
=> .Net: Version 1.47.0

dotnet/samples/Concepts/Filtering/RetryWithFilters.cs
=> .Net: Adding Streaming Retry filter example

python/samples/concepts/agents/mixed_chat/mixed_chat_agents.py, python/samples/getting_started_with_agents/azure_ai_agent/step4_azure_ai_agent_code_interpreter.py
Updated the mixed_chat sample to use Azure AI Agents instead of assistant api and used the newest syntax for the chat completion agent
=> Python: updated mixed chat sample

dotnet/Directory.Packages.props
Update MCP samples to the latest MCP package.
=> .Net: Update to the latest MCP package

dotnet/Directory.Packages.props, dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Services/AzureOpenAIChatCompletionServiceTests.cs, dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Settings/AzureOpenAIPromptExecutionSettingsTests.cs, dotnet/src/Connectors/Connectors.AzureOpenAI/Core/AzureClientCore.ChatCompletion.cs, dotnet/src/Connectors/Connectors.AzureOpenAI/Settings/AzureOpenAIPromptExecutionSettings.cs, python/pyproject.toml, python/samples/concepts/agents/mixed_chat/mixed_chat_agents.py, python/samples/getting_started_with_agents/azure_ai_agent/step4_azure_ai_agent_code_interpreter.py, python/samples/getting_started_with_processes/README.md
=> .Net: Merging from main

dotnet/Directory.Packages.props, dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Services/AzureOpenAIChatCompletionServiceTests.cs, dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Settings/AzureOpenAIPromptExecutionSettingsTests.cs, dotnet/src/Connectors/Connectors.AzureOpenAI/Core/AzureClientCore.ChatCompletion.cs, dotnet/src/Connectors/Connectors.AzureOpenAI/Settings/AzureOpenAIPromptExecutionSettings.cs, python/pyproject.toml, python/samples/concepts/agents/mixed_chat/mixed_chat_agents.py, python/samples/getting_started_with_agents/azure_ai_agent/step4_azure_ai_agent_code_interpreter.py, python/samples/getting_started_with_processes/README.md
=> Python: Merging latest from main

dotnet/samples/Demos/ModelContextProtocolClientServer/README.md
Closes: https://github.com/microsoft/semantic-kernel/issues/11200
=> .Net: Add details about remote MCP SSE servers and authentication

dotnet/Directory.Packages.props, dotnet/samples/GettingStartedWithAgents/AzureAIAgent/Step08_AzureAIAgent_Declarative.cs, dotnet/samples/GettingStartedWithAgents/BedrockAgent/Step07_BedrockAgent_Declarative.cs, dotnet/samples/GettingStartedWithAgents/OpenAIAssistant/Step07_Assistant_Declarative.cs, dotnet/src/Agents/AzureAI/Definition/AzureAIAgentFactory.cs, dotnet/src/Agents/Bedrock/Definition/BedrockAgentFactory.cs, dotnet/src/Agents/OpenAI/Definition/OpenAIAssistantAgentFactory.cs, dotnet/src/Agents/UnitTests/AzureAI/Definition/AzureAIAgentFactoryTests.cs, dotnet/src/Agents/UnitTests/OpenAI/Definition/OpenAIAssistantAgentFactoryTests.cs, dotnet/src/Agents/UnitTests/Yaml/AgentYamlTests.cs, dotnet/src/Agents/UnitTests/Yaml/AzureAIKernelAgentYamlTests.cs, dotnet/src/Connectors/Connectors.MistralAI.UnitTests/MistralAIExtensionTests.cs, dotnet/src/Connectors/Connectors.MistralAI/MistralAIKernelBuilderExtensions.cs, dotnet/src/Connectors/Connectors.MistralAI/MistralAIServiceCollectionExtensions.cs, dotnet/src/InternalUtilities/samples/InternalUtilities/TestConfiguration.cs, python/semantic_kernel/kernel.py, python/semantic_kernel/reliability/kernel_reliability_extension.py, python/tests/conftest.py, python/tests/integration/kernel/test_kernel_integration.py, python/tests/unit/kernel/test_kernel.py
=> Python: Updating feature declarative processes with main latest updates

dotnet/samples/GettingStartedWithProcesses/GettingStartedWithProcesses.csproj, dotnet/samples/GettingStartedWithProcesses/Step04/Step04_AgentOrchestration.cs, dotnet/samples/GettingStartedWithProcesses/Step04/Steps/RenderMessageStep.cs, dotnet/src/Experimental/Process.Abstractions/KernelProcessAgentExecutor.cs, dotnet/src/Experimental/Process.Core/ProcessAgentBuilder.cs, dotnet/src/Experimental/Process.Core/ProcessBuilder.cs, dotnet/src/Experimental/Process.LocalRuntime/LocalKernelProcessContext.cs, dotnet/src/Experimental/Process.LocalRuntime/LocalKernelProcessFactory.cs, dotnet/src/Experimental/Process.LocalRuntime/LocalProcess.cs, dotnet/src/Experimental/Process.LocalRuntime/LocalStep.cs, dotnet/src/InternalUtilities/process/Abstractions/StepExtensions.cs
- adding agent step abstraction
- local runtime working
=> .Net: Agent Step in Processes

dotnet/samples/GettingStartedWithProcesses/Step04/Step04_AgentOrchestration.cs, dotnet/samples/GettingStartedWithProcesses/Step06/Step06_FoundryAgentProcess.cs, dotnet/src/Experimental/Process.Abstractions/KernelProcessAgentExecutor.cs, dotnet/src/Experimental/Process.Abstractions/KernelProcessAgentStep.cs, dotnet/src/Experimental/Process.Abstractions/KernelProcessDeclarativeConditionHandler.cs, dotnet/src/Experimental/Process.Abstractions/ProcessAgentActions.cs, dotnet/src/Experimental/Process.Core/ProcessAgentBuilder.cs, dotnet/src/Experimental/Process.Core/ProcessBuilder.cs, dotnet/src/Experimental/Process.Core/Workflow/WorkflowBuilder.cs, dotnet/src/Experimental/Process.LocalRuntime/LocalAgentStep.cs, dotnet/src/Experimental/Process.LocalRuntime/LocalProcess.cs, dotnet/src/Experimental/Process.LocalRuntime/LocalStep.cs
Som updates to enable foundry agents with conditions.
=> .Net: Feature process v2

dotnet/src/Connectors/Connectors.AzureCosmosDBMongoDB.UnitTests/AzureCosmosDBMongoDBVectorStoreCollectionSearchMappingTests.cs, dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchConstants.cs, dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchDynamicDataModelMapper.cs, dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchDynamicModelBuilder.cs, dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreRecordCollection.cs, dotnet/src/Connectors/Connectors.Memory.Postgres/PostgresVectorStoreRecordMapper.cs, dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonVectorStoreRecordCollection.cs, dotnet/src/Connectors/Connectors.MongoDB.UnitTests/MongoDBVectorStoreCollectionSearchMappingTests.cs, dotnet/src/Connectors/VectorData.Abstractions/ConnectorSupport/VectorStoreRecordModelBuilder.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreFixture.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreRecordCollectionTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreFixture.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreRecordCollectionTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBNoSQL/AzureCosmosDBNoSQLVectorStoreRecordCollectionTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBNoSQL/AzureCosmosDBNoSQLVectorStoreTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/MongoDB/MongoDBVectorStoreRecordCollectionTests.cs, dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisVectorStoreFixture.cs
Fix AzureAISearch tests and two small bugs.
Improve MongoDB tests with a small fix too.
Fix CosmosNoSQL integration tests
Fixes for postgres and mongodb
Fixes for redis
=> .Net: Fix Integration tests and a few small bugs.

python/semantic_kernel/__init__.py
Bump Python version to 1.29.0 for a release.
Bump Python version to 1.29.0 for a release.
=> Python: Bump Python version to 1.29.0 for a release.

dotnet/src/SemanticKernel.Core/Memory/TextRag/TextRagComponent.cs, dotnet/src/SemanticKernel.Core/Memory/TextRag/TextRagComponentOptions.cs, dotnet/src/SemanticKernel.UnitTests/Memory/TextRagComponentTests.cs
#10100
#10712
Adding a rag component for easily adding RAG to an agent.
=> .Net: Adding a rag component for easily adding RAG to an agent.

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchFilterTranslator.cs, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBFilterTranslator.cs, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/AzureCosmosDBNoSqlFilterTranslator.cs, dotnet/src/Connectors/Connectors.Memory.Common/SqlFilterTranslator.cs, dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoDBFilterTranslator.cs, dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeFilterTranslator.cs, dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantFilterTranslator.cs, dotnet/src/Connectors/Connectors.Memory.Redis/RedisFilterTranslator.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateFilterTranslator.cs, dotnet/src/Connectors/VectorData.Abstractions/ConnectorSupport/Filter/FilterTranslationPreprocessor.cs, dotnet/src/VectorDataIntegrationTests/CosmosMongoDBIntegrationTests/Filter/CosmosMongoBasicFilterTests.cs, dotnet/src/VectorDataIntegrationTests/CosmosMongoDBIntegrationTests/Filter/CosmosMongoBasicQueryTests.cs, dotnet/src/VectorDataIntegrationTests/MongoDBIntegrationTests/Filter/MongoDBBasicFilterTests.cs, dotnet/src/VectorDataIntegrationTests/MongoDBIntegrationTests/Filter/MongoDBBasicQueryTests.cs, dotnet/src/VectorDataIntegrationTests/PineconeIntegrationTests/Filter/PineconeBasicFilterTests.cs, dotnet/src/VectorDataIntegrationTests/PineconeIntegrationTests/Filter/PineconeBasicQueryTests.cs, dotnet/src/VectorDataIntegrationTests/RedisIntegrationTests/Filter/RedisBasicFilterTests.cs, dotnet/src/VectorDataIntegrationTests/RedisIntegrationTests/Filter/RedisBasicQueryTests.cs, dotnet/src/VectorDataIntegrationTests/VectorDataIntegrationTests/Filter/BasicFilterTests.cs, dotnet/src/VectorDataIntegrationTests/WeaviateIntegrationTests/Filter/WeaviateBasicFilterTests.cs, dotnet/src/VectorDataIntegrationTests/WeaviateIntegrationTests/Filter/WeaviateBasicQueryTests.cs
~This PR is based on top of #11750, review last commit only.~
Fixes #11665
=> .Net: Handle comparison with nullable value types in MEVD filter translators

dotnet/src/IntegrationTests/Connectors/Memory/MongoDB/MongoDBVectorStoreFixture.cs
When the mongodb container initialization fails, the disposal also failed, so fixing this issue.
=> .Net: Further improvement to MongoDB reliability.

dotnet/Directory.Packages.props, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreRecordCollection.cs, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/AzureCosmosDBNoSQLVectorStoreRecordCollection.cs, dotnet/src/Connectors/Connectors.Memory.InMemory/InMemoryVectorStoreRecordCollection.cs, dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoDBVectorStoreRecordCollection.cs, dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeVectorStoreRecordCollection.cs, dotnet/src/Connectors/Connectors.Memory.Postgres/PostgresVectorStoreRecordCollection.cs, dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordCollection.cs, dotnet/src/Connectors/Connectors.Memory.Redis/RedisHashSetVectorStoreRecordCollection.cs, dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonVectorStoreRecordCollection.cs, dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerVectorStoreRecordCollection.cs, dotnet/src/Connectors/Connectors.Memory.Sqlite/SqliteVectorStoreRecordCollection.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreRecordCollection.cs, dotnet/src/Connectors/VectorData.Abstractions/ConnectorSupport/VectorStoreRecordVectorPropertyModel.cs, dotnet/src/Connectors/VectorData.Abstractions/ConnectorSupport/VectorStoreRecordVectorPropertyModel{TInput}.cs, dotnet/src/SemanticKernel.UnitTests/AI/ServiceConversionExtensionsTests.cs
- Update package and changes needed
=> .Net: Update Microsoft.Extensions.AI 9.4.0 to 9.4.3

dotnet/samples/Concepts/Agents/ChatCompletion_Rag.cs, dotnet/samples/Concepts/README.md, dotnet/src/SemanticKernel.Core/Data/TextSearchBehavior/TextSearchBehavior.cs, dotnet/src/SemanticKernel.Core/Data/TextSearchBehavior/TextSearchBehaviorOptions.cs, dotnet/src/SemanticKernel.Core/Data/TextSearchStore/TextSearchStore.cs, dotnet/src/SemanticKernel.UnitTests/Data/TextSearchBehaviorTests.cs, dotnet/src/SemanticKernel.UnitTests/Data/TextSearchStoreTests.cs
#10100 
#10712
- Adds a sample that shows how to use the rag components with an agent
- Adds support for text only uploads
- Adds some bug fixes
- Adds additional tests
=> .Net: Add an agent RAG sample, add text only upload, bug fixes and more tests

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchCollectionOptions.cs, dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreOptions.cs, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/CosmosMongoCollectionOptions.cs, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/CosmosMongoVectorStoreOptions.cs, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/CosmosNoSqlCollectionOptions.cs, dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/CosmosNoSqlVectorStoreOptions.cs, dotnet/src/Connectors/Connectors.Memory.InMemory/InMemoryCollectionOptions.cs, dotnet/src/Connectors/Connectors.Memory.InMemory/InMemoryVectorStoreOptions.cs, dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoCollectionOptions.cs, dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoVectorStoreOptions.cs, dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeCollectionOptions.cs, dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeVectorStoreOptions.cs, dotnet/src/Connectors/Connectors.Memory.Postgres/PostgresCollectionOptions.cs, dotnet/src/Connectors/Connectors.Memory.Postgres/PostgresVectorStoreOptions.cs, dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantCollectionOptions.cs, dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreOptions.cs, dotnet/src/Connectors/Connectors.Memory.Redis/RedisHashSetCollectionOptions.cs, dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonCollectionOptions.cs, dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStoreOptions.cs, dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerCollectionOptions.cs, dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerVectorStoreOptions.cs, dotnet/src/Connectors/Connectors.Memory.Sqlite/SqliteCollectionOptions.cs, dotnet/src/Connectors/Connectors.Memory.Sqlite/SqliteVectorStoreOptions.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateCollectionOptions.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreOptions.cs, dotnet/src/Connectors/VectorData.Abstractions/VectorSearch/HybridSearchOptions.cs
Also HybridSearchOptions leftovers
Closes #11715
=> Make MEVD store/collection option bags mutable

dotnet/samples/Concepts/Agents/ChatCompletion_Mem0.cs, dotnet/samples/Concepts/README.md, dotnet/src/IntegrationTests/Memory/Mem0MemoryComponentTests.cs, dotnet/src/InternalUtilities/samples/InternalUtilities/TestConfiguration.cs, dotnet/src/SemanticKernel.Core/Memory/Mem0/Mem0Client.cs, dotnet/src/SemanticKernel.Core/Memory/Mem0/Mem0MemoryComponent.cs, dotnet/src/SemanticKernel.UnitTests/Memory/Mem0MemoryComponentTests.cs
- Add a sample to show how to use the mem0 component
- Fix some bugs and add more tests
- Removed the clear memory tool, since it is flakey and getting invoked when it shouldn't be.
- Can reintroduce later if we find a way to do this safely
=> Add mem0 sample, bug fixes and more tests.

dotnet/samples/Concepts/Agents/ChatCompletion_Mem0.cs, dotnet/src/IntegrationTests/Memory/Mem0BehaviorTests.cs, dotnet/src/SemanticKernel.Core/Memory/Mem0/Mem0Behavior.cs, dotnet/src/SemanticKernel.Core/Memory/Mem0/Mem0BehaviorOptions.cs, dotnet/src/SemanticKernel.UnitTests/Memory/Mem0BehaviorTests.cs
Naming changes as discussed.
Rename Mem0MemoryComponent to Mem0Behavior
=> Rename Mem0MemoryComponent to Mem0Behavior

dotnet/samples/Concepts/Agents/ChatCompletion_Rag.cs, dotnet/src/SemanticKernel.Core/Data/TextSearchStore/TextSearchStore.cs, dotnet/src/SemanticKernel.UnitTests/Data/TextSearchStoreTests.cs
MEVD can now generate embeddings internally, so no need to provide this on the TextSearchStore
- Removed embedding generation from the TextSearchStore
- Updated samples and tests
=> Update the TextSearchStore to use the built-in embedding generation provided by MEVD

dotnet/src/Plugins/Plugins.Core/Plugins.Core.csproj
Contributes to: https://github.com/microsoft/semantic-kernel/issues/10070
=> .Net: Graduate Plugins.Core package from 'alpha' to 'preview'  

dotnet/src/Connectors/Connectors.Memory.InMemory/InMemoryCollection.cs, dotnet/src/Connectors/Connectors.Memory.InMemory/InMemoryCollectionOptions.cs, dotnet/src/Connectors/Connectors.Memory.InMemory/InMemoryServiceCollectionExtensions.cs
=> .Net: Make InMemoryCollectionOptions non-generic

dotnet/src/Connectors/Connectors.AzureAISearch.UnitTests/AzureAISearchCollectionTests.cs, dotnet/src/Connectors/Connectors.AzureAISearch.UnitTests/AzureAISearchDynamicMapperTests.cs, dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchCollection.cs, dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchDynamicMapper.cs, dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchDynamicModelBuilder.cs, dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchMapper.cs, dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchModelBuilder.cs, dotnet/src/Connectors/Connectors.Memory.AzureAISearch/IAzureAISearchMapper.cs, dotnet/src/Connectors/Connectors.Memory.CosmosNoSql/CosmosNoSqlDynamicMapper.cs, dotnet/src/VectorDataIntegrationTests/AzureAISearchIntegrationTests/AzureAISearchEmbeddingGenerationTests.cs, dotnet/src/VectorDataIntegrationTests/AzureAISearchIntegrationTests/AzureAISearchEmbeddingTypeTests.cs, dotnet/src/VectorDataIntegrationTests/AzureAISearchIntegrationTests/CRUD/AzureAISearchDynamicDataModelConformanceTests.cs, dotnet/src/VectorDataIntegrationTests/AzureAISearchIntegrationTests/CRUD/AzureAISearchNoDataConformanceTests.cs, dotnet/src/VectorDataIntegrationTests/AzureAISearchIntegrationTests/CRUD/AzureAISearchNoVectorConformanceTests.cs, dotnet/src/VectorDataIntegrationTests/AzureAISearchIntegrationTests/Filter/AzureAISearchBasicFilterTests.cs, dotnet/src/VectorDataIntegrationTests/AzureAISearchIntegrationTests/Filter/AzureAISearchBasicQueryTests.cs, dotnet/src/VectorDataIntegrationTests/AzureAISearchIntegrationTests/HybridSearch/AzureAISearchKeywordVectorizedHybridSearchTests.cs, dotnet/src/VectorDataIntegrationTests/AzureAISearchIntegrationTests/Support/AzureAISearchDynamicDataModelFixture.cs, dotnet/src/VectorDataIntegrationTests/AzureAISearchIntegrationTests/Support/AzureAISearchTestEnvironment.cs, dotnet/src/VectorDataIntegrationTests/VectorDataIntegrationTests/EmbeddingGenerationTests.cs
#11941
- Add embedding generation for AzureAISearch
=> .Net: Add embedding generation for AzureAISearch

dotnet/src/IntegrationTests/Memory/WhiteboardBehaviorTests.cs, dotnet/src/SemanticKernel.Core/Memory/Whiteboard/WhiteboardBehavior.cs, dotnet/src/SemanticKernel.Core/Memory/Whiteboard/WhiteboardBehaviorOptions.cs, dotnet/src/SemanticKernel.UnitTests/Memory/WhiteboardBehaviorTests.cs
We need a component to continually track the most important information from a conversation.
- Add a whiteboard behavior
=> .Net: Add Whiteboard behavior

dotnet/src/Connectors/Connectors.MistralAI.UnitTests/MistralAIExtensionTests.cs, dotnet/src/Connectors/Connectors.MistralAI.UnitTests/Services/MistralAIEmbeddingGeneratorTests.cs, dotnet/src/Connectors/Connectors.MistralAI.UnitTests/Services/MistralAITextEmbeddingGenerationServiceTests.cs, dotnet/src/Connectors/Connectors.MistralAI/Extensions/MistralAIKernelBuilderExtensions.EmbeddingGenerator.cs, dotnet/src/Connectors/Connectors.MistralAI/Extensions/MistralAIKernelBuilderExtensions.cs, dotnet/src/Connectors/Connectors.MistralAI/Extensions/MistralAIServiceCollectionExtensions.EmbeddingGenerator.cs, dotnet/src/Connectors/Connectors.MistralAI/Extensions/MistralAIServiceCollectionExtensions.cs, dotnet/src/Connectors/Connectors.MistralAI/Services/MistralAIEmbeddingGenerator.cs, dotnet/src/Connectors/Connectors.MistralAI/Services/MistralAITextEmbeddingGenerationService.cs, dotnet/src/IntegrationTests/Connectors/MistralAI/TextEmbedding/MistralAIEmbeddingGeneratorTests.cs
=> .Net: Mistral AI - Add `IEmbeddingGenerator`  and obsolete  `ITextEmbeddingsGenerationService` - Phase 01

dotnet/samples/Concepts/Agents/ChatCompletion_Whiteboard.cs, dotnet/samples/Concepts/README.md, dotnet/src/IntegrationTests/Memory/WhiteboardBehaviorTests.cs, dotnet/src/SemanticKernel.Core/Memory/Whiteboard/WhiteboardBehavior.cs
Long running conversations can hit limits with regards to the context window size, so require truncation.
This can lead to loss of context, which a whiteboarding component can help address.
#10100
#10712
- Add a sample to show how to use the whiteboarding behavior.
=> .Net: Add whiteboard sample

dotnet/Directory.Packages.props, dotnet/samples/Concepts/Concepts.csproj, dotnet/samples/Concepts/Memory/AWSBedrock_EmbeddingGeneration.cs, dotnet/samples/Concepts/README.md, dotnet/src/Connectors/Connectors.Amazon.UnitTests/Extensions/BedrockKernelBuilderExtensionTests.cs, dotnet/src/Connectors/Connectors.Amazon.UnitTests/Extensions/BedrockServiceCollectionExtensionTests.cs, dotnet/src/Connectors/Connectors.Amazon.UnitTests/Services/BedrockTextEmbeddingGenerationServiceTests.cs, dotnet/src/Connectors/Connectors.Amazon/Bedrock/Extensions/BedrockKernelBuilderExtensions.cs, dotnet/src/Connectors/Connectors.Amazon/Bedrock/Extensions/BedrockServiceCollectionExtensions.DependencyInjection.cs, dotnet/src/Connectors/Connectors.Amazon/Bedrock/Extensions/BedrockServiceCollectionExtensions.cs, dotnet/src/Connectors/Connectors.Amazon/Bedrock/Services/BedrockTextEmbeddingGeneratorService.cs, dotnet/src/Connectors/Connectors.Amazon/Connectors.Amazon.csproj, dotnet/src/IntegrationTests/Connectors/Amazon/Bedrock/BedrockTextEmbeddingTests.cs, dotnet/src/IntegrationTests/IntegrationTests.csproj, dotnet/src/InternalUtilities/samples/InternalUtilities/TestConfiguration.cs
=> .Net: Amazon Bedrock - Add `IEmbeddingGenerator`  and obsolete  `ITextEmbeddingsGenerationService` - Phase 05

dotnet/samples/Concepts/Memory/Ollama_EmbeddingGeneration.cs, dotnet/src/Connectors/Connectors.Ollama.UnitTests/Extensions/OllamaKernelBuilderExtensionsTests.cs, dotnet/src/Connectors/Connectors.Ollama.UnitTests/Extensions/OllamaServiceCollectionExtensionsTests.cs, dotnet/src/Connectors/Connectors.Ollama/Extensions/OllamaKernelBuilderExtensions.cs, dotnet/src/Connectors/Connectors.Ollama/Extensions/OllamaServiceCollectionExtensions.DependencyInjection.cs, dotnet/src/Connectors/Connectors.Ollama/Extensions/OllamaServiceCollectionExtensions.cs, dotnet/src/IntegrationTests/Connectors/Ollama/OllamaTextEmbeddingTests.cs
=> .Net: Ollama - Add `IEmbeddingGenerator`  and obsolete  `ITextEmbeddingsGenerationService` - Phase 06

dotnet/samples/Concepts/Agents/ChatCompletion_Whiteboard.cs, dotnet/src/IntegrationTests/IntegrationTests.csproj, dotnet/src/IntegrationTests/Memory/WhiteboardBehaviorTests.cs, dotnet/src/SemanticKernel.Core/Data/TextSearchBehavior/TextSearchBehavior.cs, dotnet/src/SemanticKernel.Core/Data/TextSearchBehavior/TextSearchBehaviorOptions.cs, dotnet/src/SemanticKernel.Core/Memory/Mem0/Mem0Behavior.cs, dotnet/src/SemanticKernel.Core/Memory/Mem0/Mem0BehaviorOptions.cs, dotnet/src/SemanticKernel.Core/Memory/Whiteboard/WhiteboardBehavior.cs, dotnet/src/SemanticKernel.Core/Memory/Whiteboard/WhiteboardBehaviorOptions.cs, dotnet/src/SemanticKernel.UnitTests/Memory/Mem0BehaviorTests.cs, dotnet/src/SemanticKernel.UnitTests/Memory/WhiteboardBehaviorTests.cs
- #10100
- #10712
- Add AI suggested tweaks to prompts
- Make a few more prompts configurable
- Change Behavior to use IChatClient
=> .Net: Add AI suggested tweaks to prompts and use IChatClient

python/semantic_kernel/__init__.py
Bump Python version to 1.30.0 for a release.
Bump Python version to 1.30.0 for a release.
=> Python: Bump Python version to 1.30.0 for a release.

dotnet/src/Experimental/Process.Abstractions/IProcessStorageConnector.cs, dotnet/src/Experimental/Process.Abstractions/KernelProcessStep.cs, dotnet/src/Experimental/Process.Abstractions/Models/Storage/StorageParentData.cs, dotnet/src/Experimental/Process.Abstractions/Models/Storage/StorageProcessState.cs, dotnet/src/Experimental/Process.Abstractions/Models/Storage/StorageStepEdgesData.cs, dotnet/src/Experimental/Process.Abstractions/Models/Storage/StorageStepState.cs, dotnet/src/Experimental/Process.Abstractions/ProcessStorageManager.cs, dotnet/src/Experimental/Process.Core/ListenForTargetBuilder.cs, dotnet/src/Experimental/Process.Core/ProcessStepBuilder.cs, dotnet/src/Experimental/Process.LocalRuntime/LocalEdgeGroupProcessor.cs, dotnet/src/Experimental/Process.LocalRuntime/LocalKernelProcessContext.cs, dotnet/src/Experimental/Process.LocalRuntime/LocalKernelProcessFactory.cs, dotnet/src/Experimental/Process.LocalRuntime/LocalProcess.cs, dotnet/src/Experimental/Process.LocalRuntime/LocalStep.cs, dotnet/src/Experimental/Process.UnitTests/Runtime.Local/LocalProcessTests.cs, dotnet/src/InternalUtilities/process/Abstractions/KernelProcessStepEdgesExtension.cs, dotnet/src/InternalUtilities/process/TestsShared/Processes/CommonProcesses.cs, dotnet/src/InternalUtilities/process/TestsShared/Services/CounterService.cs, dotnet/src/InternalUtilities/process/TestsShared/Services/ICounterService.cs, dotnet/src/InternalUtilities/process/TestsShared/Services/JsonFileStorage.cs, dotnet/src/InternalUtilities/process/TestsShared/Services/MockStorage.cs, dotnet/src/InternalUtilities/process/TestsShared/Steps/CommonSteps.cs
- adding LocalKernelFactory with registered processes
=> .Net: Local Runtime improvements

dotnet/src/Experimental/Process.Abstractions/Models/Storage/StorageParentData.cs, dotnet/src/Experimental/Process.LocalRuntime/LocalProxy.cs, dotnet/src/Experimental/Process.LocalRuntime/LocalStep.cs, dotnet/src/Experimental/Process.UnitTests/Runtime.Local/LocalMapTests.cs, dotnet/src/Experimental/Process.UnitTests/Runtime.Local/LocalProcessTests.cs, dotnet/src/Experimental/Process.UnitTests/Runtime.Local/LocalProxyTests.cs, dotnet/src/InternalUtilities/process/TestsShared/Processes/CommonProcesses.cs
Fixing failing uts after previous check in
=> .Net: Fixing Local process Tests

python/samples/concepts/agents/chat_completion_agent/chat_completion_agent_message_callback.py, python/samples/concepts/agents/chat_completion_agent/chat_completion_agent_message_callback_streaming.py, python/samples/getting_started_with_agents/README.md, python/samples/getting_started_with_agents/multi_agent_orchestration/step4a_handoff_structured_inputs.py
The new multi-agent orchestration samples are missing from the getting started with agents README. Add them in with their descriptions. Also, remove two unused intermediate message callback lists from two samples that are no longer used.
Add samples to README. Clean up some samples.
=> Python: Add MultiAgent Orchestration to README.

dotnet/src/Connectors/Connectors.CosmosNoSql.UnitTests/CosmosNoSqlCollectionQueryBuilderTests.cs, dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchCollection.cs, dotnet/src/Connectors/Connectors.Memory.CosmosNoSql/CosmosNoSqlCollection.cs, dotnet/src/Connectors/Connectors.Memory.CosmosNoSql/CosmosNoSqlCollectionQueryBuilder.cs, dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoCollection.cs, dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantCollection.cs, dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateCollection.cs, dotnet/src/Connectors/VectorData.Abstractions/VectorSearch/IKeywordHybridSearchable.cs
=> .Net: Enable embedding generation for hybrid search

python/semantic_kernel/connectors/memory/azure_cosmos_db.py, python/semantic_kernel/connectors/memory/mongodb.py, python/tests/integration/memory/azure_cosmos_db/conftest.py, python/tests/integration/memory/azure_cosmos_db/test_azure_cosmos_db_no_sql.py, python/tests/unit/connectors/memory/azure_cosmos_db/conftest.py, python/tests/unit/connectors/memory/azure_cosmos_db/test_azure_cosmos_db_mongodb_collection.py, python/tests/unit/connectors/memory/azure_cosmos_db/test_azure_cosmos_db_no_sql_collection.py, python/tests/unit/connectors/memory/azure_cosmos_db/test_azure_cosmos_db_no_sql_store.py, python/tests/unit/connectors/memory/conftest.py
Updating the cosmos and mongodb integrations
=> Python: Update Cosmos and MongoDB

dotnet/samples/Concepts/Memory/VectorStoreFixtures/VectorStorePostgresContainerFixture.cs, dotnet/samples/Concepts/Memory/VectorStore_ConsumeFromMemoryStore_AzureAISearch.cs, dotnet/samples/Concepts/Memory/VectorStore_DataIngestion_MultiStore.cs, dotnet/samples/Concepts/Memory/VectorStore_DataIngestion_Simple.cs, dotnet/samples/Concepts/Memory/VectorStore_DynamicDataModel_Interop.cs, dotnet/samples/Concepts/Memory/VectorStore_HybridSearch_Simple_AzureAISearch.cs, dotnet/samples/Concepts/Memory/VectorStore_VectorSearch_MultiStore_AzureAISearch.cs, dotnet/samples/Concepts/Memory/VectorStore_VectorSearch_MultiStore_Common.cs, dotnet/samples/Concepts/Memory/VectorStore_VectorSearch_MultiStore_InMemory.cs, dotnet/samples/Concepts/Memory/VectorStore_VectorSearch_MultiStore_Postgres.cs, dotnet/samples/Concepts/Memory/VectorStore_VectorSearch_MultiStore_Qdrant.cs, dotnet/samples/Concepts/Memory/VectorStore_VectorSearch_MultiStore_Redis.cs, dotnet/samples/Concepts/Memory/VectorStore_VectorSearch_MultiVector.cs, dotnet/samples/Concepts/Memory/VectorStore_VectorSearch_Simple.cs, dotnet/samples/Concepts/Memory/VolatileVectorStore_LoadData.cs, dotnet/samples/GettingStartedWithVectorStores/Step4_Use_DynamicDataModel.cs, dotnet/samples/GettingStartedWithVectorStores/VectorStoresFixture.cs, dotnet/src/Connectors/VectorData.Abstractions/ProviderServices/PropertyModel.cs
=> .Net: Fix samples and a small usability issue.

dotnet/src/Agents/Runtime/Abstractions/Runtime.Abstractions.csproj, dotnet/src/Agents/Runtime/Core/Runtime.Core.csproj
Include `nuget-package.props`
Include is required.
=> .Net Agents - Fix agent runtime package publishing

python/samples/concepts/realtime/realtime_agent_with_function_calling_webrtc.py, python/samples/concepts/realtime/realtime_agent_with_function_calling_websocket.py, python/semantic_kernel/connectors/ai/open_ai/__init__.py, python/semantic_kernel/connectors/ai/open_ai/prompt_execution_settings/open_ai_realtime_execution_settings.py, python/semantic_kernel/connectors/ai/open_ai/services/_open_ai_realtime.py, python/semantic_kernel/connectors/ai/open_ai/services/azure_config_base.py, python/semantic_kernel/connectors/ai/open_ai/services/azure_realtime.py, python/semantic_kernel/connectors/ai/open_ai/services/open_ai_realtime.py
Added support for WebRTC for Azure OpenAI Realtime models.
=> Python: added WebRTC support for Azure OpenAI Realtime

python/semantic_kernel/connectors/memory/chroma.py, python/semantic_kernel/connectors/memory/pinecone.py, python/semantic_kernel/connectors/memory/postgres.py, python/tests/integration/memory/postgres/test_postgres_int.py, python/tests/unit/connectors/memory/test_chroma.py, python/tests/unit/connectors/memory/test_pinecone.py, python/tests/unit/connectors/memory/test_postgres_store.py
Updates for Chroma, Pinecone and Postgres
=> Python: Update Chroma, Pinecone, Postgres

python/semantic_kernel/agents/azure_ai/azure_ai_agent_settings.py
Some fields were missing from `AzureAIAgentSettings`, which caused errors during placeholder replacement in the declarative agent.
https://github.com/microsoft/semantic-kernel/blob/6efcc847c56d742a12dec871bd715319a599533c/python/semantic_kernel/agents/azure_ai/azure_ai_agent.py#L568-L575
- Add the missing fields to `AzureAIAgentSettings`.
=> Python: Add missing fields to `AzureAIAgentSettings`

python/semantic_kernel/connectors/memory/sql_server.py, python/tests/unit/connectors/memory/test_sql_server.py
=> Python: Update SQL

dotnet/src/Experimental/Process.Abstractions/KernelProcessFunctionTarget.cs, dotnet/src/Experimental/Process.Abstractions/Serialization/Model/Workflow.cs
Fixing issue with serialization in Dapr runtime due to missing [DataContract] attributes.
=> .Net: FIxing serialization issue in Dapr runtime.

python/samples/concepts/chat_history/store_chat_history_in_cosmosdb.py, python/samples/concepts/memory/complex_memory.py, python/samples/concepts/memory/memory_with_pandas.py, python/samples/concepts/memory/simple_memory.py, python/samples/concepts/rag/rag_with_vector_collection.py, python/tests/samples/test_concepts.py, python/tests/unit/connectors/memory/mongodb_atlas/test_mongodb_atlas_collection.py, python/tests/unit/connectors/memory/mongodb_atlas/test_mongodb_atlas_store.py, python/tests/unit/connectors/memory/weaviate/test_weaviate_collection.py, python/tests/unit/connectors/memory/weaviate/test_weaviate_store.py
Final update with last pieces and the samples
=> Python: samples and misc

python/tests/conftest.py, python/tests/integration/memory/azure_cosmos_db/test_azure_cosmos_db_no_sql.py, python/tests/integration/memory/postgres/test_postgres_int.py, python/tests/integration/memory/test_vector_store.py
Integration test fixes for the vector stores
=> Python: Int test fix

dotnet/samples/Concepts/Agents/ChatCompletion_ContextualFunctionSelection.cs, dotnet/src/SemanticKernel.Core/Functions/ContextualSelection/ContextualFunctionProvider.cs, dotnet/src/SemanticKernel.Core/Functions/ContextualSelection/FunctionStore.cs, dotnet/src/SemanticKernel.Core/Functions/ContextualSelection/FunctionStoreLoggingExtensions.cs, dotnet/src/SemanticKernel.UnitTests/Functions/ContextualSelection/ContextualFunctionProviderTests.cs, dotnet/src/SemanticKernel.UnitTests/Functions/ContextualSelection/FunctionStoreTests.cs
This PR adds logging functionality to the contextual function selection.
Contributes to: https://github.com/microsoft/semantic-kernel/issues/10074
=> .Net: Logging for contextual function selection

README.md
=> Added ChatHistoryAgentThread to multi-agent

python/semantic_kernel/__init__.py
Bump Python version to 1.32.2 for a release.
Bump Python version to 1.32.2 for a release.
=> Python: Bump Python version to 1.32.2 for a release.

python/semantic_kernel/__init__.py
Bump Python version to 1.33.0 for release
Bump Python version to 1.33.0 for release
=> Python: Bump Python version to 1.33.0 for release

dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAIChatCompletion_NonStreamingTests.cs
Fix flakey web search model test
=> .Net: Fix flakey web search model test

dotnet/nuget/nuget-package.props, dotnet/src/SemanticKernel.Core/CompatibilitySuppressions.xml
=> .Net: Version 1.56.0

python/semantic_kernel/__init__.py
Bump version to 1.34.0 for a release.
Bump version to 1.34.0 for a release.
=> Python: Bump version to 1.34.0 for a release

dotnet/Directory.Packages.props
=> .Net: Upgrade AzureAISearch SDK

dotnet/Directory.Packages.props
Upgrade SqliteVec and PgVector
=> .Net: Upgrade SqliteVec and PgVector

dotnet/Directory.Packages.props, dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Services/AzureOpenAIChatCompletionServiceTests.cs, dotnet/src/Connectors/Connectors.MistralAI.UnitTests/Services/MistralAIChatCompletionServiceTests.cs, dotnet/src/Connectors/Connectors.Ollama.UnitTests/Services/OllamaChatCompletionTests.cs, dotnet/src/Connectors/Connectors.OpenAI.UnitTests/Services/OpenAIChatCompletionServiceTests.cs, dotnet/src/IntegrationTests/Connectors/Amazon/Bedrock/BedrockTextGenerationTests.cs
- Update all Amazon Related packages.
- Extra bump on Analyzers
- Agent + Connector Codebase
IT passing.
=> .Net: Update Amazon packages

dotnet/Directory.Packages.props, dotnet/src/IntegrationTests/Connectors/Ollama/OllamaChatClientIntegrationTests.cs, dotnet/src/IntegrationTests/Connectors/Ollama/OllamaChatCompletion_FunctionCallingTests.cs, dotnet/src/SemanticKernel.Abstractions/AI/ChatClient/ChatMessageExtensions.cs
Update dependencies and small bugfix where ChatClient as CompletionServices were not updating the FunctionResultContent.FunctionName.
=> .Net: Update Connector Dependencies + BugFix

dotnet/nuget/nuget-package.props
=> .Net: Version 1.59.0

dotnet/samples/GettingStartedWithAgents/OpenAIResponse/Step04_OpenAIResponseAgent_Tools.cs, dotnet/src/Agents/OpenAI/Internal/ResponseCreationOptionsFactory.cs, dotnet/src/Agents/UnitTests/OpenAI/Internal/ResponseCreationOptionsFactoryTests.cs, dotnet/src/InternalUtilities/samples/AgentUtilities/BaseResponsesAgentTest.cs
=> .Net: Fix issue 12775

dotnet/Directory.Packages.props
Dependabot is timing out so manually patching package dependecies
=> .Net: Patch package dependencies

dotnet/nuget/nuget-package.props
=> .Net: Version 1.61.0

dotnet/samples/Demos/ProcessWithCloudEvents/ProcessWithCloudEvents.Utilities/Storage/CosmosDbContainerStorageConnector.cs, dotnet/src/Experimental/Process.Abstractions/IKernelProcessUserStateStore.cs, dotnet/src/Experimental/Process.Abstractions/IProcessStorageOperations.cs, dotnet/src/Experimental/Process.Abstractions/KernelProcessStepContext.cs, dotnet/src/Experimental/Process.Abstractions/Models/Storage/StorageProcessData.cs, dotnet/src/Experimental/Process.Abstractions/Models/Storage/StorageProcessExtensions.cs, dotnet/src/Experimental/Process.Abstractions/Models/Storage/StorageProcessState.cs, dotnet/src/Experimental/Process.Abstractions/ProcessStorageManager.cs, dotnet/src/Experimental/Process.LocalRuntime/LocalProcess.cs, dotnet/src/Experimental/Process.LocalRuntime/LocalStep.cs, dotnet/src/Experimental/Process.LocalRuntime/LocalUserStateStore.cs, dotnet/src/Experimental/Process.UnitTests/Runtime.Local/LocalProcessTests.cs, dotnet/src/InternalUtilities/process/Abstractions/StepExtensions.cs
- migrating fork relevant components to pipe process variable persistence
- piping shared variables to LocalStep in the meantime
- adding tests for validation
=> .Net: Checkpoint - Process Shared Variables

python/semantic_kernel/__init__.py
Bump Python version to 1.35.2 for a release
Bump Python version to 1.35.2 for a release
=> Python: Bump Python version to 1.35.2 for a release

.github/.linkspector.yml, python/DEV_SETUP.md
Exclude folders with documents containing unreachable links and remove files that were previously excluded because the links they contained have become reachable.
=> .Net: Exclude folders having docs with not reachable links

python/semantic_kernel/__init__.py
Bump Python version to 1.36.0 for a release.
Bump Python version to 1.36.0 for a release.
=> Python: Bump Python version to 1.36.0 for a release.

python/semantic_kernel/__init__.py
Bump Python version to 1.36.2 for a release
Bump Python version to 1.36.2 for a release
=> Python: Bump Python version to 1.36.2 for a release

python/semantic_kernel/__init__.py
Bump Python version to 1.37.0 for a release.
Bump Python version to 1.37.0 for a release.
=> Python: Bump Python version to 1.37.0 for a release.

python/samples/getting_started_with_agents/README.md
Current getting started with agents README links for AzureAIAgent are broken.
- Fixes #13129
=> Python: Fix AzureAIAgent readme links

dotnet/src/InternalUtilities/src/Diagnostics/ModelDiagnostics.cs
Some GenAI contents are not serialized correctly.
Fix serialization.
After the fix:
=> .Net: Fix Json serialization mistake in GenAI telemetry

dotnet/nuget/nuget-package.props
=> Version 1.66.0
