- .github/workflows/dotnet-ci.yml
- .github/workflows/dotnet-integration-tests.yml
- .github/workflows/dotnet-pr.yml
- .github/workflows/update-version.sh
- dotnet/nuget/nuget-package.props
- dotnet/src/SemanticKernel.Skills/Skills.Document/Skills.Document.csproj
- dotnet/src/SemanticKernel.Skills/Skills.Memory.Sqlite/Skills.Memory.Sqlite.csproj
- dotnet/src/SemanticKernel.Skills/Skills.MsGraph/Skills.MsGraph.csproj
- dotnet/src/SemanticKernel.Skills/Skills.Web/Skills.Web.csproj
- dotnet/src/SemanticKernel/SemanticKernel.csproj
- **PR Action**
- removing nuget version update and artifacts upload from the PR actions definition -- neither of these are used.
- **CI Action** 
- updating with versioning parameters, to load version from a central props file
- removing GitHub feed (NuGet) publishing, since NuGet packs are now available on NuGet.org feed
- NuGet packs from specific builds are still available in each CI build's artifacts
- **Integration Tests**
- running only on CI (not on PR) as PR tests do not work for repo non-owners
- **Update Version script**
- reading version from a central props file (specified in args from Actions)
- script no longer assumes default version of 1.0 if not found -- exits with failure code instead
- **.csproj files**
- removing build version specified in each file (they'll load from …
> Update GitHub Actions, PR, NuGet version process

- dotnet/src/SemanticKernel.Test/Orchestration/SKFunctionTests1.cs
- dotnet/src/SemanticKernel.Test/Orchestration/SKFunctionTests2.cs
- dotnet/src/SemanticKernel.Test/Orchestration/SKFunctionTests3.cs
- dotnet/src/SemanticKernel/AI/CompleteRequestSettings.cs
- dotnet/src/SemanticKernel/Kernel.cs
- dotnet/src/SemanticKernel/Orchestration/SKFunction.cs
SKFunction offers 2 ways to update semantic functions' request settings. The 2 APIs use different instances of `CompleteRequestSettings` instead of one, leading to situations where the settings are out of sync or settings requested by the user are ignored.
Remove the duplicate object and point the 2 APIs to the same settings instance.
> Fix bug in SKFunction: remove duplicate RequestSettings objects

- .gitignore
- samples/apps/auth-api-webapp-react/README.md
- samples/dotnet/graph-api-skills/README.md
- samples/dotnet/graph-api-skills/appsettings.json
Fixed a few issues in the graph-api-skils readme 
1. Why is this change required? Will help developers running the sample to avoid some pitfalls
3. What problem does it solve? Running the sample with just Azure Open API results in an error
4. What scenario does it contribute to? Developer onboarding
5. If it fixes an open issue, please link to the issue here.
1. Ignore `.yarn` folder and `.yarnrc.yml` files
2. Change graph-api-skils readme to fix some errors, add more detail on the app registration and fix the sample json
3. Comment out the OpenAI config in appsettings.json so that the sample won't always try to use it
> Fix a few minor issues in the graph-api-skills readme

- dotnet/src/IntegrationTest/AI/OpenAIEmbeddingTests.cs
- dotnet/src/SemanticKernel.Skills/Skills.Web/WebFileDownloadSkill.cs
- dotnet/src/SemanticKernel.Test/AI/OpenAI/Services/BackendConfigTests.cs
- dotnet/src/SemanticKernel/AI/OpenAI/Services/AzureTextEmbeddings.cs
- dotnet/src/SemanticKernel/AI/OpenAI/Services/BackendConfig.cs
- samples/dotnet/KernelHttpServer/Config/ApiKeyConfig.cs
- samples/dotnet/KernelHttpServer/Config/CompletionService.cs
- samples/dotnet/KernelHttpServer/Extensions.cs
- samples/dotnet/KernelHttpServer/Model/Ask.cs
- samples/dotnet/KernelHttpServer/Model/AskResult.cs
- samples/dotnet/KernelHttpServer/Model/Skill.cs
- samples/dotnet/KernelHttpServer/PingEndpoint.cs
- samples/dotnet/KernelHttpServer/Program.cs
- samples/dotnet/KernelHttpServer/SemanticKernelEndpoint.cs
- samples/dotnet/KernelHttpServer/SemanticKernelFactory.cs
- samples/dotnet/KernelHttpServer/TokenAuthenticationProvider.cs
- samples/dotnet/KernelHttpServer/Utils/RepoFiles.cs
- samples/dotnet/KernelHttpServer/Utils/YourAppException.cs
The Semantic Kernel naming convention of Skills and Functions can cause confusion with the naming of the Azure Function sample project.
1. Updated sample `KernelHttpServer` project namespaces to match the project name. 
1. Small adjustments to code style warnings (naming, unused namespaces, spacing).
> Correct namespaces in KernelHttpServer, Fixed code style warnings

- dotnet/Directory.Packages.props
- dotnet/src/SemanticKernel.Test/CoreSkills/PlannerSkillTests.cs
Roslyn and VS Threading analyzers provide automated and free recommendations about about C# best practices. The PR includes one of many easy misses during PR reviews, that the VS analyzer detected.
* Add [Roslyn analyzers](https://github.com/dotnet/roslyn-analyzers) to the build process
* Add [VS threading analyzers](https://github.com/Microsoft/vs-threading)
> Add Roslyn and VS Threading analyzers

- dotnet/src/IntegrationTest/testsettings.json
Integration tests are failing due to missing deployment name for AzureOpenAI.
Populating the DeploymentName field in the `AzureOpenAI` and `AzureOpenAIEmbeddings` test configurations.
> Fixing testsettings for integration tests

- .github/workflows/dotnet-integration-tests.yml
OpenAIEmbeddingTests are failing because:
_Microsoft.SemanticKernel.Diagnostics.ValidationException : EmptyValue: The Azure endpoint cannot be empty_
Updated intergration tests yaml ENV variables to provide endpoint and key for embeddings tests. The endpoint and key are the same as the completion tests, but this change leaves the flexibility to use a different endpoint in the future.
> Enpoint and ApiKey Required for Embedding Integration Tests

- .github/workflows/dotnet-integration-tests.yml
OpenAIEmbeddingTests were failing because the GitHub workflow could not find an endpoint or API key
Modified github workflows yaml to map the configuration names to the correct secrets.
Verified via GitHub actions against this branch.
> Fix Integration test OpenAIEmbeddingTests

- dotnet/src/SemanticKernel.Test/TemplateEngine/Blocks/CodeBlockTests.cs
- dotnet/src/SemanticKernel/AI/AIException.cs
- dotnet/src/SemanticKernel/Diagnostics/ValidationException.cs
- dotnet/src/SemanticKernel/KernelException.cs
- dotnet/src/SemanticKernel/Planning/PlanningException.cs
- dotnet/src/SemanticKernel/TemplateEngine/Blocks/CodeBlock.cs
- dotnet/src/SemanticKernel/TemplateEngine/TemplateException.cs
When a semantic function invokes a native function:
* if the native function fails, the failure should surface through the result (bug fix)
* if the native function doesn't exist, it should fail (change of behavior for better dev experience)
Bug report: https://github.com/microsoft/semantic-kernel/issues/47
* Fix `CodeBlock` to capture and manage errors correctly and provide a better dev experience.
> Bug fix: surface exceptions thrown by native functions

- dotnet/src/IntegrationTest/AI/OpenAIEmbeddingTests.cs
- samples/apps/auth-api-webapp-react/src/components/ServiceConfig.tsx
- samples/apps/auth-api-webapp-react/src/hooks/SemanticKernel.ts
- samples/apps/auth-api-webapp-react/src/model/KeyConfig.ts
- samples/apps/book-creator-webapp-react/src/components/ServiceConfig.tsx
- samples/apps/book-creator-webapp-react/src/components/TaskButton.tsx
- samples/apps/book-creator-webapp-react/src/hooks/SemanticKernel.ts
- samples/apps/book-creator-webapp-react/src/model/KeyConfig.ts
- samples/apps/chat-summary-webapp-react/src/components/ServiceConfig.tsx
- samples/apps/chat-summary-webapp-react/src/hooks/SemanticKernel.ts
- samples/apps/chat-summary-webapp-react/src/model/KeyConfig.ts
- samples/dotnet/KernelHttpServer/Config/AIService.cs
- samples/dotnet/KernelHttpServer/Config/ApiKeyConfig.cs
- samples/dotnet/KernelHttpServer/Config/BackendConfig.cs
- samples/dotnet/KernelHttpServer/Config/Constants.cs
- samples/dotnet/KernelHttpServer/Extensions.cs
- samples/dotnet/KernelHttpServer/Program.cs
- samples/dotnet/KernelHttpServer/SemanticKernelEndpoint.cs
- samples/dotnet/KernelHttpServer/SemanticKernelFactory.cs
This change modifies the expected headers at the KernelHttpServer and allows future samples to leverage memory/embedding capabilities via the KernelHttpServer.
* Introduces distinct headers for completion and embedding 
* Allows one to have completion endpoint on Azure OpenAI and embedding endpoint on OpenAI, for example
* Updates dependent app samples to use the new header convention
> Bring embeddings and memory to KernelHttpServer

- dotnet/src/SemanticKernel/Orchestration/Extensions/ContextVariablesExtensions.cs
1. Why is this change required? 
The plan arguments are already being set a few lines above this
2. What problem does it solve? 
Removes a duplicate and unnecessary line
3. What scenario does it contribute to?
Planner
4. If it fixes an open issue, please link to the issue here. 
Didn't make an issue
Remove a duplicate line in setting plan arguments in the UpdateWithPlanEntry().
The plan arguments are already set a few lines above this
> Fix setting plan arguments twice in UpdateWithPlanEntry

- dotnet/src/SemanticKernel.UnitTests/Memory/Collections/MinHeapTests.cs
- dotnet/src/SemanticKernel.UnitTests/Memory/Collections/TopNCollectionTests.cs
After test project refactoring some tests got lost due to change of project name. This PR adds them back to increase code coverage.
Added two missed unit-tests from this commit: https://github.com/microsoft/semantic-kernel/commit/d76de654f2533c16c1c32b31aa15c0bdbfba0c4f.
> Added lost unit tests after refactoring

- README.md
Adding notice to Python developers and link to python-preview branch:
> Add python-preview link to README

- samples/notebooks/dotnet/5-using-the-planner.ipynb
In Sample 5, I moved the text about the planner just after the planner output, as it feels like a better fit.
> [Docs] Sample 5: move the text about the planner just after the planner output

- dotnet/src/SemanticKernel.IntegrationTests/WebSkill/WebSkillTests.cs
Integration Tests have started to fail regularly.
This commit renames the method DownloadToFileAsync to DownloadToFile in the WebSkillTests class, to match the name of the method in the WebFileDownloadSkill class. This change fixes the `WebFileDownloadSkillFileTestAsync` integration test. No functional changes are made to the method or the test.
> Rename DownloadToFileAsync to DownloadToFile in WebSkillTests

- dotnet/SK-dotnet.sln
- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Skills.OpenAPI.csproj
The change adds a new Microsoft.SemanticKernel.Skills.OpenAPI project/package that is going to have all OpenAPI related
artifacts - classes (parser, model, runner, etc..) and json|yaml OpenAPI documents themselves.
This PR lays foundation for scenarios where new skills are onboarded with no-code approach just by copying OpenAPI/Swagger documents into a folder or loading them from remote location.
This is empty project that will be filled with OpenAPI related code, document.
- [] All unit tests pass, and I have added new tests where possible
> New Microsoft.SemanticKernel.Skills.OpenAPI project added

- python/semantic_kernel/orchestration/delegate_handlers.py
- python/semantic_kernel/orchestration/sk_function.py
1. Why is this change required? compatibility for python 3.9
2. What problem does it solve? if user use PromptTemplateEngine with skills inside, it does not work.
3. What scenario does it contribute to? PromptTemplateEngine will work
4. If it fixes an open issue, please link to the issue here.
#182 
detailed in #182 
similar concept with #169
> fix: delegate compatibility issue for python 3.9

- python/semantic_kernel/orchestration/delegate_inference.py
1. Why is this change required? `pytest .` raises error
2. What problem does it solve? pass all test
3. What scenario does it contribute to? `infer_delegate_type` will not raise error
4. If it fixes an open issue, please link to the issue here.
https://github.com/microsoft/semantic-kernel/issues/168
static function has no attribute __wrapped__ and this raises error.
use __func__ for this.
I think `wrapped = getattr(value, "__wrapped__", getattr(value, "__func__", None))` is reasonable for this issue.
```@staticmethod
def infer_delegate_type(function) -> DelegateTypes:
function_signature = signature(function)
awaitable = iscoroutinefunction(function)
for name, value in DelegateInference.__dict__.items():
if name.startswith("infer_") and hasattr(
>               value.__wrapped__, …
```
> fix: static functions has no attr __wrapped__

- README.md
- samples/notebooks/dotnet/1-basic-loading-the-kernel.ipynb
- samples/notebooks/dotnet/2-running-prompts-from-file.ipynb
- samples/notebooks/dotnet/3-semantic-function-inline.ipynb
- samples/notebooks/dotnet/4-context-variables-chat.ipynb
- samples/notebooks/dotnet/5-using-the-planner.ipynb
- samples/notebooks/dotnet/6-memory-and-embeddings.ipynb
Update README with new API.
Lock notebooks to 0.9 so we can release new APIs breaking notebooks.
> Update README and lock notebooks to 0.9

- python/semantic_kernel/core_skills/__init__.py
- python/semantic_kernel/core_skills/time_skill.py
- python/tests/test_time_skill.py
Port of the core TimeSkill
This PR adds the core TimeSkill with unit tests.
```
kernel = sk.create_kernel()
kernel.import_skill(TimeSkill(), "time")
```
```
sk_prompt = """
{{time.now}}
"""
```
> python: Porting TimeSkill

- samples/notebooks/dotnet/README.md
I was trying to run the Getting Started Notebook from step 3 on the [Setting up Semantic Kernel](https://learn.microsoft.com/en-us/semantic-kernel/get-started) documentation page. 
In the first cell, I got a nuget error:
`error NU1101: Unable to find package ...`
Incorporated a fix from https://stackoverflow.com/a/73961223/620501 into the troubleshooting section of the readme.
> add nuget sources troubleshooting

- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Extensions/KernelOpenApiExtensions.cs
- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Extensions/RestApiOperationExtensions.cs
- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Model/RestApiOperation.cs
- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Model/RestApiOperationParameter.cs
- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Model/RestApiOperationParameterType.cs
- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Model/RestApiOperationPayload.cs
- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Model/RestApiOperationPayloadProperty.cs
- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/OpenApi/OpenApiDocumentParser.cs
- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Rest/IRestApiOperationRunner.cs
- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Rest/RestApiOperationRunner.cs
- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Skills.OpenAPI.csproj
- dotnet/src/SemanticKernel.Skills/Skills.UnitTests/OpenAPI/OpenApiDocumentParserTests.cs
- dotnet/src/SemanticKernel.Skills/Skills.UnitTests/OpenAPI/TestSkills/ResourceSkillsProvider.cs
- dotnet/src/SemanticKernel.Skills/Skills.UnitTests/OpenAPI/TestSkills/v2_0/operation.json
- dotnet/src/SemanticKernel.Skills/Skills.UnitTests/Rest/RestApiOperationRunnerTests.cs
- dotnet/src/SemanticKernel.Skills/Skills.UnitTests/Skills.UnitTests.csproj
- samples/dotnet/kernel-syntax-examples/Example16_OpenApiSkill.cs
This change adds functionality that creates payload for PUT and POST operations out of metadata provided in OpenAPI document and arguments from SK context. This extends OpenAPI skills capabilities that are currently limited to GET operations. 
This PR changes/adds the following classes:
- OpenApiDocumentParser is extended to parse OpenAPI document body metadata and convert it into RestApiOperationPayload model.
- New RestApiOperationPayload class is added to represent REST API operation payload.
- RestApiOperation class is extended to include new Payload property. Parameters advertisement (SK pecificlogic) logic is moved out to the RestApiOperationExtensions class to keep the SK logic out of RestApiOperation domain.
- RestApiOperationRunner class is extended to create …
> Dynamic payload for OpenAPI skills CRU requests

- dotnet/src/SemanticKernel/Connectors/OpenAI/Tokenizers/Settings/EmbeddedResource.cs
- dotnet/src/SemanticKernel/Memory/Collections/ScoredValue.cs
- dotnet/src/SemanticKernel/SemanticKernel.csproj
- samples/dotnet/FileCompression/FileCompressionSkill.cs
- samples/dotnet/FileCompression/IFileCompressor.cs
- samples/dotnet/FileCompression/ZipFileCompressor.cs
SK nuget is not deploying the tokenizer data files (encoder.json and vocab.bpe) into the app build folder, only showing the files in the explorer. As a result the tokenizer doesn't work, throwing a FileNotFoundException.
* Updated csproj file so that the auto-generated nuspec file has `copyToOutput="true"`
* Improved the code to use the assembly location, supporting also the scenario where the tokenizer might be in a different assembly.
> Fix nuget, include tokenizer data files into the output dir

- samples/apps/copilot-chat-app/WebApp/src/libs/useChat.ts
Currently the frontend invokes the FunSkill Joke function which is just a placeholder.
Invoke the ChatSkill Chat function to actually get a response.
> Invoke chatSkill from frontend

- samples/apps/copilot-chat-app/SKWebApi/Program.cs
- samples/apps/copilot-chat-app/SKWebApi/appsettings.json
Enable CORS so that we can call the SKWebApi from frontends running on different ports/servers
Added CORS support for API and in appsettings.
> Add CORS to SKWebApi

- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Extensions/KernelOpenApiExtensions.cs
- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Extensions/RestApiOperationExtensions.cs
- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Model/RestApiOperationParameter.cs
- dotnet/src/SemanticKernel/Diagnostics/Verify.cs
- dotnet/src/SemanticKernel/IKernel.cs
- dotnet/src/SemanticKernel/Kernel.cs
- samples/dotnet/FileCompression/FileCompressionSkill.cs
- samples/dotnet/FileCompression/IFileCompressor.cs
- samples/dotnet/FileCompression/ZipFileCompressor.cs
The change is addressing comments regarding dashes in function parameter names and a few other minor comments. 
Taking into account that JSON standard allows dashes in property names and SK function parameters don't allow them, a solution was put in place to temporarily replace all dashes and other not supported by SK function symbols by underscore symbol - "_".
> Addressing comments

- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Model/RestApiOperationParameter.cs
- samples/dotnet/FileCompression/FileCompressionSkill.cs
- Removed non-existent namespace reference
- Fixed whitespace violation in RestApiOperationParameter.cs
> Build and style fixes in OpenAPI skill

- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Authentication/AuthenticateRequestAsyncCallback.cs
- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Extensions/KernelChatGptPluginExtensions.cs
- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Extensions/KernelOpenApiExtensions.cs
- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Rest/RestApiOperationRunner.cs
- dotnet/src/SemanticKernel.Skills/Skills.UnitTests/Rest/RestApiOperationRunnerTests.cs
Although the .NET coding conventions suggest using Func<> instead of defining a delegate type, it makes more sense to define a delegate for the auth callback due to the broad usage across the OpenAPI feature. If the signature of this callback needs to change in the future, we will be able to change it in just one place instead of many.
Define AuthenticateRequestAsyncCallback delegate type and replace all instances of Func<HttpRequestMessage, Task> authCallback with it.
> Use delegate type for authentication callback

- samples/apps/copilot-chat-app/SKWebApi/Program.cs
- samples/apps/copilot-chat-app/SKWebApi/appsettings.json
Make it more obvious that SKWebApi started as expected as show the user the health probe.
Bumped the logging level from "Warning" to "Information" in SKWebApi and added a health probe address logging message.
> Enable default logging in SKWeApi, add healthprobe url output.

- dotnet/src/SemanticKernel/Planning/KernelPlanningExtensions.cs
Fix the build
This commit adds a pragma directive to suppress the IDE0130 warning that suggests using the file name as the namespace for the KernelPlanningExtensions.cs file. This warning is not applicable for extension methods, as they need to be in the same namespace as the type they are extending. The commit also adds a using directive for the Microsoft.SemanticKernel.Planning namespace, which is needed for the extension methods.
> Add namespace warning suppression to KernelPlanningExtensions.cs

- samples/apps/copilot-chat-app/SKWebApi/Program.cs
- samples/apps/copilot-chat-app/SKWebApi/appsettings.json
Give the possibility to use HTTP so that people just trying out the service don't have to deal with cert issues (self-signed or otherwise)
Added flag to toggle HTTP / HTTPS
> Give the possibility to use HTTP

- samples/notebooks/dotnet/7-DALL-E-2.ipynb
- samples/notebooks/dotnet/8-chatGPT-with-DALL-E-2.ipynb
Some users are reporting errors with the new notebooks that use SkiaSharp, because the nuget version is not explicitly stated in the code.
Specify which version of SkiaSharp to use.
> Specify the version of SkiaSharp to use in the notebooks

- samples/apps/copilot-chat-app/README.md
- samples/apps/copilot-chat-app/WebApp/README.md
The markdown link checker is failing with some links in the CopilotChat READMEs.
Make sure all example links, such as contoso and env files", and annotated with ticks to avoid the link checker trying to validate them.
> Mark example links with ticks to avoid markdown link checking.

- dotnet/src/SemanticKernel.UnitTests/Planning/SKContextExtensionsTests.cs
- dotnet/src/SemanticKernel/CoreSkills/SemanticFunctionConstants.cs
- dotnet/src/SemanticKernel/Planning/SKContextPlanningExtensions.cs
Today, planner can create different plans for the same goal and function input. This is undesirable, as it'd be best to have consistent plan generation as temperature is 0. The reason for these difference, is because the use of ConcurrentDictionary would result in non-deterministic function manual ordering. This change adds sorting to local manual retrieval to ensure consistent plan generation. Additionally, issues have been raised showing DV3 being unable to use available functions without additional whitespace in the prompt, so adding that as well.
- Order the available functions by skill name and function name for better readability
- Add blank lines to the planning skill template for better formatting
- Add a pragma directive to suppress a warning for the namespace of the extension …
> Improve function availability and planning skill template

- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Extensions/KernelChatGptPluginExtensions.cs
- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Extensions/KernelOpenApiExtensions.cs
- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Extensions/RestApiOperationOpenAPIExtensions.cs
- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/OpenApi/OpenApiDocumentParser.cs
- dotnet/src/SemanticKernel.Skills/Skills.UnitTests/OpenAPI/OpenApiDocumentParserV20Tests.cs
- dotnet/src/SemanticKernel.Skills/Skills.UnitTests/OpenAPI/OpenApiDocumentParserV30Tests.cs
- dotnet/src/SemanticKernel.Skills/Skills.UnitTests/OpenAPI/OpenApiDocumentParserV31Tests.cs
- samples/dotnet/kernel-syntax-examples/Example21_ChatGPTPlugins.cs
- samples/dotnet/kernel-syntax-examples/Example22_OpenApiSkill.cs
* Extension methods: use the same namespace of the class being extended
* Fix typos
* Removed unused vars and params
* Use correct cancellation token
> Fix typos and code style

- python/DEV_SETUP.md
- python/LICENSE
- python/tests/integration/template_engine/test_prompt_template_e2e.py
- python/tests/unit/core_skills/test_file_io_skill.py
Some unit tests were broken on Windows. This fixes them to ensure cross-platform compatibility. 
I also added the LICENSE file to the python directory so it will be packaged up with pip.
- In `test_prompt_template_e2e`, needed to use os.path.join instead of concatenation strings for a path
- In `test_file_io_skill`, using delete=True on NamedTemporaryFiles doesn't work on Windows when the skill tries to open the file, so we have to delete it manually
- In `test_file_io_skill.test_cannot_write_async`, I wasn't getting a permission error because the file the skill created was created with 666 file permissions instead of 500 like its parent directory. Instead I create a file with the proper (or rather, improper) permissions.
> Fix Python unit tests for Windows

- dotnet/Directory.Packages.props
- dotnet/src/SemanticKernel/SemanticKernel.csproj
Maximizing compatibility with hosting apps, supporting the widest version range of dependency packages.
Reducing the SK core project's dependencies to the minimum needed set, and the minimum supported version for each. Explicitly using the [minversion, ) syntax, normally implicit, to make it clear that this is a deliberate min version, and not take automatically suggested updates.
Note: we may be able to remove 1 or 2 more with a few minor code changes.
> Reducing SK core to minimum viable dependency packages

- dotnet/src/SemanticKernel.IntegrationTests/Connectors/OpenAI/OpenAICompletionTests.cs
- dotnet/src/SemanticKernel/AI/AIException.cs
- dotnet/src/SemanticKernel/Connectors/OpenAI/AzureOpenAIClientAbstract.cs
- dotnet/src/SemanticKernel/Connectors/OpenAI/OpenAIClientAbstract.cs
- samples/apps/auth-api-webapp-react/src/components/YourInfo.tsx
- samples/apps/copilot-chat-app/webapi/Controllers/SemanticKernelController.cs
- samples/dotnet/KernelHttpServer/SemanticKernelEndpoint.cs
OpenAI when reaches quota limit gives a TooManyRequests Http Status which is unclear and many times lead to think it was related to Throttling instead of a hard quota limit error.
This change allow us to retrieve the detail of the exception regarding what was the underlyning error from the AI Provider.
To get more details on the error if that error is AIException, you now can get it using the `Detail` property
This change brings more clarity to the actual error when that happens for OpenAI and AzureOpenAI completion requests.
> Adding Detailed Message for AIException Scenarios

- dotnet/src/Connectors/Connectors.Memory.CosmosDB/CosmosMemoryStore.cs
GetAllAsync() in CosmosDB connector does not return all records.
This issue also impacts GetNearestMatchAsync() as it does not count all the records in the comparation.
Closes https://github.com/microsoft/semantic-kernel/issues/437
Updated `CosmosMemoryStore` to iterate over all batches of results from `GetItemQueryIterator`, not just the first batch of results.
> Fix cosmos memory store to return all results, not just the first batch

- samples/apps/copilot-chat-app/webapi/Storage/ChatMessageRepository.cs
- samples/apps/copilot-chat-app/webapi/Storage/ChatSessionRepository.cs
- samples/apps/copilot-chat-app/webapi/Storage/CosmosDbContext.cs
The CosmosDb SDK serializes entities into Json using the same property names. We would like it to serialize the entities to Json with the property names in camel case.
Configure the CosmosDb client to use camel case for serialization.
> Configure CosmosDB SDK to serialize JSON with camel case

- dotnet/src/Connectors/Connectors.AI.OpenAI/AzureSdk/ClientBase.cs
- dotnet/src/Connectors/Connectors.AI.OpenAI/ChatCompletion/AzureChatCompletion.cs
- dotnet/src/Connectors/Connectors.AI.OpenAI/ChatCompletion/OpenAIChatCompletion.cs
- dotnet/src/Connectors/Connectors.AI.OpenAI/KernelConfigOpenAIExtensions.cs
- samples/dotnet/kernel-syntax-examples/Example25_AADAuth.cs
- samples/dotnet/kernel-syntax-examples/Example26_SemanticFunctionsUsingChatGPT.cs
- samples/dotnet/kernel-syntax-examples/Program.cs
Chat models are (currently) less expensive and can be used like text completion models also for semantic functions and prompt completion.
Extend OpenAI chat clients to simulate text completion over the chat protocol. This behavior is enabled by default, but can also be disabled passing a boolean parameter when registering an AI service.
> Allow to use chat models for semantic functions

- dotnet/src/Connectors/Connectors.Memory.Sqlite/Connectors.Memory.Sqlite.csproj
- dotnet/src/Connectors/Connectors.Memory.Sqlite/Database.cs
- dotnet/src/Connectors/Connectors.Memory.Sqlite/SqliteExtensions.cs
- dotnet/src/SemanticKernel.IntegrationTests/RedirectOutput.cs
- dotnet/src/SemanticKernel.Skills/Skills.Web/WebFileDownloadSkill.cs
Converting the Connectors.Sqlite package to netstandard2.0. 
Added some extension methods to make up for the gap in overloads in the netstandard2.0 sqlite implementation.
Converted usings to single line syntax and removed the "async using" since this version does not implement IAsyncDisposable.
Also included:
- a single-line bug fix in WebSkill.DownloadToFileAsync() -- was using the destination stream length (always 0) instead of the source stream length.
- a nullable warning fix in integration tests that has been showing up in recent PRs.
> Sqlite to netstandard2.0 + bug fix in WebSkill.DownloadToFile

- samples/apps/copilot-chat-app/webapi/Storage/ChatMessageRepository.cs
- samples/apps/copilot-chat-app/webapi/Storage/ChatSessionRepository.cs
- samples/apps/copilot-chat-app/webapi/Storage/CosmosDbContext.cs
- samples/apps/copilot-chat-app/webapi/Storage/FileSystemContext.cs
- samples/apps/copilot-chat-app/webapi/Storage/IStorageContext.cs
- samples/apps/copilot-chat-app/webapi/Storage/VolatileContext.cs
1. A ComsoDb storage context exposing an IQueryable to repositories will not allow queries to be processed asynchronously, unless the repository takes dependency on Microsoft.Azure.Cosmos.Linq, which will violate the principles of the repository data access pattern and cause problems when using other storage context other than CosmosDb.
2. The CosmosDb SDK serializes entities into Json using the same property names that are pascal case. We would like it to serialize the entities to Json with the property names in camel case.
1. Create an API named QueryEntitiesAsync that accept a predicate for Linq query and have the storage contexts handle the internal.
2. Configure the CosmosDb client to use camel case for serialization.
> CopilotChat: Have storage context to handle query

- .devcontainer/devcontainer.json
Make it easier for newcomers to try out the sample apps and notebooks.
Add DevContainer configuration so users can get quickly get started using VS Code DevContainers or GitHub Codespaces. This DevContainer includes all tools and extensions necessary to begin testing sample apps and notebooks (e.g., dotnet, node, az function core tools).
> feat: add devcontainer.json so users can open in codespaces

- dotnet/SK-dotnet.sln
- dotnet/src/Connectors/Connectors.AI.OpenAI/Connectors.AI.OpenAI.csproj
- dotnet/src/Connectors/Connectors.Memory.CosmosDB/Connectors.Memory.CosmosDB.csproj
- dotnet/src/Connectors/Connectors.Memory.CosmosDB/CosmosMemoryRecord.cs
- dotnet/src/Connectors/Connectors.Memory.CosmosDB/CosmosMemoryStore.cs
- dotnet/src/Connectors/Connectors.Memory.Qdrant/Connectors.Memory.Qdrant.csproj
- dotnet/src/Connectors/Connectors.Memory.Sqlite/Connectors.Memory.Sqlite.csproj
- dotnet/src/Connectors/Connectors.Memory.Sqlite/SqliteExtensions.cs
- dotnet/src/SemanticKernel.Abstractions/SemanticKernel.Abstractions.csproj
- dotnet/src/SemanticKernel.MetaPackage/SemanticKernel.MetaPackage.csproj
- dotnet/src/SemanticKernel.Skills/Skills.Document/Skills.Document.csproj
- dotnet/src/SemanticKernel.Skills/Skills.MsGraph/Skills.MsGraph.csproj
- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Skills.OpenAPI.csproj
- dotnet/src/SemanticKernel.Skills/Skills.Web/Skills.Web.csproj
- dotnet/src/SemanticKernel/AI/Embeddings/EmbeddingReadOnlySpan.cs
- dotnet/src/SemanticKernel/SemanticKernel.csproj
Change **Microsoft.SemanticKernel** to be a metapackage that installs 2 packages:
* Microsoft.SemanticKernel.Core: core code (previously named Microsoft.SemanticKernel) + abstractions
* Microsoft.SemanticKernel.Connectors.AI.OpenAI: OpenAI clients, depending on Azure OpenAI SDK and Azure Core
Benefits:
* Users installing Microsoft.SemanticKernel have all the code like before to use OpenAI
* Users can install the core kernel without OpenAI if they need to, e.g. when working with other AI providers
* We can use the metapackage to include more useful dependencies if needed, without having to put all in the same package
> Introduce new meta package to install core packages

- samples/apps/copilot-chat-app/webapi/Config/ConfigExtensions.cs
- samples/apps/copilot-chat-app/webapi/Skills/ChatSkill.cs
- samples/apps/copilot-chat-app/webapi/appsettings.json
Chat completion (gpt-3.5-turbo/gpt-4) models are the future, let's optimize for those.
Updated CopilotChat to use Chat completions instead of Text completions.
> Update CopilotChat to use only Chat APIs for completions, by default.

- samples/skills/SummarizeSkill/Summarize/config.json
Right now this command would fail in Python
```
skills_directory = "../../skills/"
kernel.import_semantic_skill_from_directory(skills_directory, "SummarizeSkill")
```
This is because there is an extra comma specifically in the `Summarize` skill. This PR fixes that.
> Python: remove extra comma from summarize skill json

- .github/workflows/python-test.yml
- python/semantic_kernel/orchestration/sk_function.py
It's better to avoid nested classes in Python, so in SKFunction, I move RunThread out of the class. RunThread is needed because we need to wait for the result of an async function that's being run in an existing event loop, and subclassing Thread seems to be the best way to do that.
This also adds python-test.yml to the github workflows. 
- Move RunThread out of SKFunction since flat hierarchy is more desirable than nested hierarchy in python. 
- Tried using a local method instead, but to no avail
- I had to invoke `_invoke_semantic_async` with await or async.run, but that could only be done within a Thread because the jupyter notebook spawns an event loop. To wait for the result, you need to use `join()` but it doesn't return the result, so the local method needed an output parameter …
> Python: Making SKFunction.RunThread an outer class

- samples/apps/copilot-chat-app/webapi/Controllers/SemanticKernelController.cs
- samples/apps/copilot-chat-app/webapi/Skills/ChatSkill.cs
When the Completion config is invalid, we end up repeating the user's message back to them instead of showing an error.
- Added propagation of a failed SK invoke back to the top-level controller call.
- Enabled AI exception detail messages
> Add error propagation for invalid completion configuration

- samples/apps/copilot-chat-app/WebApp/src/components/chat/ChatInput.tsx
- samples/apps/copilot-chat-app/webapi/Controllers/SemanticKernelController.cs
Submitting empty chat messages confuses the AI.
- CopilotChat WebApp won't submit if there is not text to submit
- CopilotChat WebApi will successfully return nothing when nothing is submitted
> CopilotChat: Only allow submit when chat message is not empty

- dotnet/src/SemanticKernel.UnitTests/CoreSkills/MathSkillTests.cs
- dotnet/src/SemanticKernel/CoreSkills/MathSkill.cs
Make MathSkill's operations a bit more efficient and make them more debuggable
These methods were using `await Task.FromResult(...)`, which is usually an indication that the method isn't actually asynchronous but is trying to silence a warning about having an async method without any awaits.  The net result of this is we end up actually incurring the overhead of an extra task unnecessarily, and can instead just use Tasks directly rather than using async/await.  These two Add/Subtract methods are also identical other than for a +/-, so we can just loop them into a shared method and avoid the duplication.
I also changed the exceptions from ArgumentException to ArgumentOutOfRangeException (which derives from ArgumentException) and included the actual value in the exception; that should help …
> Tweak MathSkill to avoid unnecessary tasks

- dotnet/src/SemanticKernel.UnitTests/VectorOperations/VectorOperationTests.cs
- dotnet/src/SemanticKernel.UnitTests/VectorOperations/VectorSpanTests.cs
Fix some unit tests to validate what they intended to validate.
The validation is ensuring if an exception is thrown that it's of the right type, but it's not actually ensuring that an exception is thrown.
For the array-based validation, we can just use the Assert.Throws helper.
For the ref struct-based validation, we can't capture the ref structs into a lambda, but we can at least assert that the operation throws.
> Tweak VectorOperation/SpanTest exception validation

- dotnet/Directory.Build.props
- dotnet/nuget/nuget-package.props
- dotnet/src/Connectors/Connectors.Memory.Qdrant/Connectors.Memory.Qdrant.csproj
- dotnet/src/SemanticKernel.Skills/Skills.MsGraph/Skills.MsGraph.csproj
- dotnet/src/SemanticKernel.Skills/Skills.OpenAPI/Skills.OpenAPI.csproj
- dotnet/src/SemanticKernel/SemanticKernel.csproj
- samples/apps/copilot-chat-app/webapi/Config/ConfigExtensions.cs
- samples/apps/copilot-chat-app/webapi/Config/CosmosConfig.cs
- samples/apps/copilot-chat-app/webapi/Config/FileSystemConfig.cs
- samples/apps/copilot-chat-app/webapi/Config/QdrantConfig.cs
- samples/apps/copilot-chat-app/webapi/Config/ServiceConfig.cs
- samples/apps/copilot-chat-app/webapi/Controllers/SpeechTokenController.cs
- samples/apps/copilot-chat-app/webapi/Program.cs
- samples/apps/copilot-chat-app/webapi/Skills/ChatSkill.cs
- samples/apps/copilot-chat-app/webapi/Skills/PromptSettings.cs
- samples/apps/copilot-chat-app/webapi/Skills/SemanticChatMemory.cs
- samples/apps/copilot-chat-app/webapi/Storage/FileSystemContext.cs
* XML docs/intellisense is currently used only for the main nuget. This change enables the same for all nugets.
* Some codestyle fixes
* Bump version to 0.13 for the next release, and people using code from the repo - this makes it also easier testing new nugets locally, ahead of the next release
> Enable xml docs for all nugets

- dotnet/src/SemanticKernel/AI/Embeddings/EmbeddingReadOnlySpan.cs
- dotnet/src/SemanticKernel/AI/Embeddings/EmbeddingSpan.cs
- dotnet/src/SemanticKernel/AI/Embeddings/SupportedTypes.cs
- dotnet/src/SemanticKernel/AI/Embeddings/VectorOperations/CosineSimilarityOperation.cs
- dotnet/src/SemanticKernel/AI/Embeddings/VectorOperations/DivideOperation.cs
- dotnet/src/SemanticKernel/AI/Embeddings/VectorOperations/DotProductOperation.cs
- dotnet/src/SemanticKernel/AI/Embeddings/VectorOperations/MultiplyOperation.cs
Make it cheaper to create EmbeddingReadOnlySpan and EmbeddingSpan instances.
The EmbeddingReadOnlySpan and EmbeddingSpan type ctors call SupportedTypes.VerifyTypeSupported.  This method is passed a Type that it then looks up in an array using a linear search.  But there's only two types that are valid, float and double, and if more are added in the future, the number that are added will either be very limited or will have some other mechanism for determining validaty.  By instead making it generic and just doing the type comparison inline, for supported types we can enable the JIT to eliminate the entire check.
Note that this does add a public `IsSupported<T>` overload.  I'm not sure of the rules about that.  If that's an issue it can be made internal for now.  However, in general we'd …
> Clean up Embedding{ReadOnly}Span T validation

- .github/workflows/lint.yml
This will run the linter on pull requests when python files have changed.
- Skip linting if python files haven't changed, similar to this action https://github.com/microsoft/semantic-kernel/actions/workflows/python-test.yml
> Run linter for pull requests only if python files have changed

- dotnet/src/Connectors/Connectors.AI.OpenAI/Tokenizers/Settings/GPT3Settings.cs
- samples/dotnet/KernelHttpServer/SemanticKernelEndpoint.cs
Avoid creating new JsonSerializerOptions per operation.
They're deceptively expensive. For the default, there's no need to specify one at all. And for other non-default options, it's best to create a singleton and reuse it. (The cost is cheaper in .NET 7, but there's still cost.)
> Avoid constructing unnecessary JsonSerializerOptions

- dotnet/src/SemanticKernel.Skills/Skills.Document/FileSystem/LocalFileSystemConnector.cs
- dotnet/src/SemanticKernel/Memory/NullMemory.cs
- dotnet/src/SemanticKernel/Memory/VolatileMemoryStore.cs
- samples/apps/copilot-chat-app/webapi/Storage/FileSystemContext.cs
- samples/dotnet/github-skills/GitHubSkill.cs
Minor tweaks to use Tasks more efficiently or more compliantly in a few places.
- Task.FromResult on .NET Core does cache a Task for null, but not for the empty string, so change NullMemory to use its own cached empty string task.
- Other than for argument exceptions, Task-returning methods should return exceptions out via the returned task rather than throwing them, so add in some use of Task.FromException.
- Rather than await'ing a WhenAll that's the entirety of a method, we can just return its Task
- `await Task.FromResult` is an expensive nop, so remove such occurrences.
> Clean up a few uses of Tasks

- dotnet/src/SemanticKernel/AI/Embeddings/VectorOperations/CosineSimilarityOperation.cs
Accelerate the CosineSimilarityImplementation for floats and doubles using SIMD.
Employ `Vector<T>` to accelerate CosineSimilarityImplementation.  If the hardware supports acceleration, a vector's worth of data is processed at a time until there isn't a vector's worth remaining.  Then it falls back to the scalar path that's also used if hardware acceleration isn't available.  It's a fairly simplistic implementation that maintains a clean parallel with the scalar code and achieves a reasonable speedup.  As with anything that impacts the order in which floating-point operations are performed, this can impact the precise resulting answer.
On my machine:
```C#
private float[] _values1, _values2;
[Params(10, 100, 1_000, 10_000)]
public int Length { get; set; }
[Params(false, true)]
public bool …
```
> Vectorize CosineSimilarityImplementation with Vector<T>

- dotnet/src/SemanticKernel.UnitTests/CoreSkills/HttpSkillTests.cs
- dotnet/src/SemanticKernel/CoreSkills/HttpSkill.cs
Suggested changes to HttpSkill based on code reviewing its implementation.
- If no HttpClient is provided, use a shared HttpClientHandler singleton so that connections may be pooled under the covers.  Otherwise, every instantiation of the skill would create and teardown a connection for the request.  If there's only ever a single instance of the skill created, it's effectively equivalent.  In the future this could also be changed to use HttpClientFactory and allow it to manage singletons.
- Use GetStringAsync for the GetAsync function: this lets the implementation optimize the operation a bit more than what the consumer can do.
- Use a shared SendRequestAsync to deduplicate the Put/Post/DeleteAsync implementations.
- Use HttpCompletionOption.ResponseHeadersRead to allow the implementation …
> Tweak HttpSkill for improved performance

- dotnet/src/SemanticKernel.Abstractions/Text/StringExtensions.cs
- dotnet/src/SemanticKernel/Planning/FunctionFlowRunner.cs
- dotnet/src/SemanticKernel/SemanticFunctions/Partitioning/SemanticTextPartitioner.cs
SemanticTextPartitioner can be made a lot faster.
Without fundamentally changing the algorithm or approach, we can tweak how data is handled in order to significantly improve the performance of this type.
```C#
private static readonly string s_input = new HttpClient().GetStringAsync("https://www.gutenberg.org/cache/epub/3200/pg3200.txt").Result; // complete works of Mark Twain
private const int MaxTokensPerLine = 100;
private const int MaxTokensPerParagraph = 1024;
[Benchmark(Baseline = true)]
public List<string> Old()
{
List<string> lines = SemanticTextPartitioner_Old.SplitPlainTextLines(s_input, MaxTokensPerLine);
return SemanticTextPartitioner_Old.SplitPlainTextParagraphs(lines, MaxTokensPerParagraph);
}
[Benchmark]
public List<string> New()
{
List<string> lines = …
```
> Improve performance of SemanticTextPartitioner

- .editorconfig
- dotnet/src/Connectors/Connectors.AI.OpenAI/AzureSdk/AddHeaderRequestPolicy.cs
- dotnet/src/Connectors/Connectors.Memory.Qdrant/Http/ApiSchema/CreateCollectionRequest.cs
- dotnet/src/Connectors/Connectors.Memory.Qdrant/Http/ApiSchema/DeleteCollectionRequest.cs
- dotnet/src/Connectors/Connectors.Memory.Qdrant/Http/ApiSchema/DeleteVectorsRequest.cs
- dotnet/src/Connectors/Connectors.Memory.Qdrant/Http/ApiSchema/GetCollectionRequest.cs
- dotnet/src/Connectors/Connectors.Memory.Qdrant/Http/ApiSchema/GetVectorsRequest.cs
- dotnet/src/Connectors/Connectors.Memory.Qdrant/Http/ApiSchema/GetVectorsResponse.cs
- dotnet/src/Connectors/Connectors.Memory.Qdrant/Http/ApiSchema/ListCollectionsRequest.cs
- dotnet/src/Connectors/Connectors.Memory.Qdrant/Http/ApiSchema/ListCollectionsResponse.cs
- dotnet/src/Connectors/Connectors.Memory.Qdrant/Http/ApiSchema/SearchVectorsRequest.cs
- dotnet/src/Connectors/Connectors.Memory.Qdrant/Http/ApiSchema/SearchVectorsResponse.cs
- dotnet/src/Connectors/Connectors.Memory.Qdrant/Http/ApiSchema/UpsertVectorRequest.cs
- dotnet/src/Connectors/Connectors.Memory.Qdrant/Http/ApiSchema/UpsertVectorResponse.cs
- dotnet/src/SemanticKernel.IntegrationTests/Fakes/EmailSkillFake.cs
- dotnet/src/SemanticKernel.Skills/Skills.UnitTests/OpenAPI/TestSkills/ResourceSkillsProvider.cs
- dotnet/src/SemanticKernel.UnitTests/Connectors/WebApi/Rest/RestApiOperationRunnerTests.cs
- dotnet/src/SemanticKernel.UnitTests/Orchestration/SKContextTests.cs
- dotnet/src/SemanticKernel.UnitTests/Orchestration/SKFunctionTests3.cs
- dotnet/src/SemanticKernel.UnitTests/Services/ServiceConfigTests.cs
- samples/apps/copilot-chat-app/webapi/Config/AIServiceConfig.cs
- samples/apps/copilot-chat-app/webapi/Config/AzureSpeechConfig.cs
- samples/apps/copilot-chat-app/webapi/Skills/SemanticMemoryExtractor.cs
- samples/apps/copilot-chat-app/webapi/Storage/FileSystemContext.cs
- samples/dotnet/KernelHttpServer/Config/Constants.cs
- samples/dotnet/kernel-syntax-examples/Example23_ReadOnlyMemoryStore.cs
- samples/dotnet/kernel-syntax-examples/RepoUtils/Env.cs
- samples/dotnet/kernel-syntax-examples/Skills/EmailSkill.cs
Sealed types enables better perf. For internal/private types, there's no downside.
Stop suppressing the analyzer rule and fix all resulting warnings.
> Enable CA1852 ("Type '...' can be sealed...)

- samples/apps/copilot-chat-app/webapi/Auth/ApiKeyAuthenticationHandler .cs
A negation bug was introduced when making a change to the API key authenticator. Fixing it.
Negate the condition where the authenticator looks for an x-api-key header
> Fix: Check for absence, not presence of API key header

- .github/workflows/markdown-link-check.yml
Markdown workflow is broken and blockign PRs.
- Removed ref:main from checkout in markdown check workflow
> Allow markdown workflow to run against PR branches

- dotnet/src/Connectors/Connectors.AI.OpenAI/Connectors.AI.OpenAI.csproj
- dotnet/src/Connectors/Connectors.AI.OpenAI/Tokenizers/GPT3Tokenizer.cs
- dotnet/src/Connectors/Connectors.AI.OpenAI/Tokenizers/Settings/GPT3Settings.cs
Improve the performance of GPT3Tokenizer in both throughput and allocation.
This primarily focuses on the path once the BPE cache has already been sufficiently warmed up.  There's much more that can be done about the code path that warms it up, but I've only handled the low-hanging fruit there for now.  This can all also be significantly improved once the project moves to target .NET Core instead of netstandard2.0.
```C#
private string _input =
"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. " +
"Blandit cursus risus at ultrices mi. Elementum facilisis leo vel fringilla est ullamcorper eget. Pellentesque sit amet porttitor " +
"eget dolor morbi non arcu. Sed turpis tincidunt id aliquet. Sit amet luctus venenatis …
```
> Improve performance of GPT3Tokenizer

- samples/dotnet/KernelHttpServer/SemanticKernelEndpoint.cs
JsonSerializerOptions should be cached and reused.
We already had a cached one with appropriate settings.  Just needs to be used.
> Fix another extraneous JsonSerializerOptions instance

- samples/notebooks/python/04-context-variables-chat.ipynb
I fixed error `useAzureOpenAI = True` on `samples/notebooks/python/04-context-variables-chat.ipynb`
before:
after:
> fixed error notebboks pyhon 4 when useAzureOpenAI equals True

- dotnet/src/SemanticKernel/Memory/Collections/Score.cs
- dotnet/src/SemanticKernel/Memory/Collections/ScoredValue.cs
A bit of cleanup for the `Score` and `ScoredValue` types.
- Make them both readonly, removing the setters from properties
- Give Score a public ctor
- Make the Min static properties internal (it doesn't really make sense on ScoredValue, and it's strange to have a Min but no Max)
- Make ScoredValue's implicit operators for casting to T or double to instead be explicit; implicit operators shouldn't be lossy, but by definition throwing away half of the state is lossy
- Remove unnecessary null checks
I also opened https://github.com/microsoft/semantic-kernel/issues/616.
And, do we need `Score` at all?  It's really just giving a unit of measure to a `double`.  Could we delete it and just let `ScoredValue<T>` wrap `T` and a `double`?
> Tweak Score and ScoredValue

- dotnet/src/SemanticKernel.Abstractions/Orchestration/ISKFunction.cs
- dotnet/src/SemanticKernel.Abstractions/Orchestration/SKContext.cs
- dotnet/src/SemanticKernel/AI/Embeddings/EmbeddingReadOnlySpan.cs
- dotnet/src/SemanticKernel/AI/Embeddings/EmbeddingSpan.cs
- dotnet/src/SemanticKernel/Orchestration/Plan.cs
Minor cleanup.
These are unnecessary.  As I was reviewing through the code I happened to notice they were unused or had greater than required visibility.  Also removed a few unnecessary `public` visibility annotations from an interface (they were nops and were inconsistent with the rest of the interface), as well as a few initializers that were initializing to the default value and thus were duplicative.
> Remove a few unnecessary internal setters

- dotnet/src/SemanticKernel.UnitTests/Orchestration/PlanTests.cs
- dotnet/src/SemanticKernel/Orchestration/Plan.cs
Fix bug with plans that have single function as root and respect Plan State.
This commit adds a new unit test for the Plan class, which tests the ability to execute a plan with one step and a state variable. It also modifies the Plan.InvokeAsync method to use the plan's state as the default context variables, instead of an empty one. This allows the plan to pass state information to the function it invokes.
> Fix state handling for plan execution

- .vscode/tasks.json
Fix the VSCode tasks for integration tests.
This commit changes the tasks.json file to use the IntegrationTests.csproj file instead of the SemanticKernel.IntegrationTests.csproj file. This is because the SemanticKernel project has been renamed to IntegrationTests, and the tasks.json file needs to reflect this change. This affects the test coverage task, which runs the integration tests and generates a lcov report. The commit also updates the cwd option to point to the new project folder.
> Update tasks.json to use IntegrationTests.csproj

- dotnet/src/IntegrationTests/Planning/SequentialPlannerTests.cs
- dotnet/src/SemanticKernel/Planning/FunctionViewExtensions.cs
SequentialPlanner was not respecting default values for inputs.
This commit modifies the ToManualString extension method for FunctionView to include the default value of each parameter in the generated string. This makes the manual more informative and helpful for LLM to know the default behavior of a function. The default value is shown in parentheses after the parameter description.
> [SequentialPlanner] Add default values to function manual

- samples/apps/copilot-chat-app/webapi/Skills/PromptSettings.cs
The chat function generates the final prompt by populating it with multiple contexts. Each context is constrained by a token limit except the last one, which is chat history. The chat function will fill up the prompt with chat history to reach the token limit. 
A bug was discovered that the chat history context was not the last context.
Move chat history to the end of the prompt.
> Fix context generation order in chat skill

- dotnet/.editorconfig
- dotnet/src/Connectors/Connectors.UnitTests/.editorconfig
- dotnet/src/IntegrationTests/.editorconfig
- dotnet/src/SemanticKernel.UnitTests/.editorconfig
- dotnet/src/Skills/Skills.UnitTests/.editorconfig
This commit adds .editorconfig files to the test projects under the dotnet folder, to suppress the errors for CA2007 and VSTHRD111 rules. These rules are enforced for the SDK projects, but not necessary for the test projects. The .editorconfig files inherit the settings from the parent folder, and override the severity for the two rules to none. This prevents the IDE from changing the code on autosave, and avoids false positives in the code analysis. The commit also removes the redundant comment for VSTHRD111 in the dotnet/.editorconfig file.
> Add .editorconfig suppressions for test projects

- dotnet/src/IntegrationTests/Planning/SequentialPlanParserTests.cs
- dotnet/src/IntegrationTests/Planning/SequentialPlannerTests.cs
- dotnet/src/SemanticKernel.UnitTests/Orchestration/PlanTests.cs
- dotnet/src/SemanticKernel.UnitTests/Planning/SKContextExtensionsTests.cs
- dotnet/src/SemanticKernel.UnitTests/Planning/SequentialPlanParserTests.cs
- dotnet/src/SemanticKernel/Planning/FunctionViewExtensions.cs
- dotnet/src/SemanticKernel/Planning/Planners/PlannerConfig.cs
- dotnet/src/SemanticKernel/Planning/Planners/SemanticFunctionConstants.cs
- dotnet/src/SemanticKernel/Planning/Planners/SequentialPlanner.cs
- dotnet/src/SemanticKernel/Planning/SequentialPlanParser.cs
- samples/dotnet/kernel-syntax-examples/Example12_Planning.cs
- samples/skills/MiscSkill/ElementAtIndex/config.json
- samples/skills/MiscSkill/ElementAtIndex/skprompt.txt
Minor cleanup of planning components and examples.
This commit changes the way function manual strings are generated by the FunctionViewExtensions class. It adds indentation and line breaks to make the output more readable and consistent. It also fixes a typo in the default value string and adds a constant for the tab character.
This commit changes the ToPlanFromXml method to accept a goal string as a parameter, instead of parsing it from the xml string. This simplifies the xml format and avoids duplication of the goal in the plan string.
> Planning example improvements

- dotnet/src/SemanticKernel/Kernel.cs
Simplify/streamline ImportSkill
`ImportSkill(object skillInstance, string skillName, ILogger log)` uses Enumerable.Select to enumerate a MethodInfo[], then uses Enumerable.Where to filter out nulls, then populates a `List<ISKFunction>` with those results, then uses Enumerable.Select to get an enumerable of the names of those functions, then populates a HashSet with those names to ensure they're all unique, and then returns the list.  The sole consumer of this then immediately creates a `Dictionary<string, ISKFunction>` from that list.
We can avoid that `List<>` and that `HashSet<>` as well as three LINQ enumerables just by creating the dictionary directly.
> Remove intermediary collections from Kernel.ImportSkill

- dotnet/src/Connectors/Connectors.AI.OpenAI/CustomClient/OpenAIClientBase.cs
- dotnet/src/SemanticKernel.Abstractions/AI/Embeddings/Embedding.cs
- dotnet/src/SemanticKernel.Abstractions/Memory/IMemoryStore.cs
- dotnet/src/SemanticKernel.UnitTests/AI/Embeddings/EmbeddingTests.cs
- dotnet/src/SemanticKernel/Connectors/HuggingFace/TextEmbedding/HuggingFaceTextEmbeddingGeneration.cs
Clean up some `Embedding<T>` behaviors / perf issues.
- IsSupported was more expensive than it needs to be: if it's changed to just compare the types directly rather than searching a list, the JIT can turn the entire operation into a JIT-time constant.
- The explicit cast to `ReadOnlySpan<T>` was cloning the array. It doesn't need to do that.
- `default(Embedding<T>)` results in a struct that fails on a bunch of operations with NullReferenceExceptions if you try to use it.  We've learned from experience with `ImmutableArray<T>` this is suboptimal.  I've made it functional and behave equivalent to Empty... in fact, Empty is now just `default`.
> Some behavioral / perf fixes for Embedding<T>

- .vscode/tasks.json
- dotnet/src/Extensions/Extensions.UnitTests/Extensions.UnitTests.csproj
- dotnet/src/IntegrationTests/Planning/PlanTests.cs
- dotnet/src/SemanticKernel.UnitTests/Orchestration/ContextVariablesConverterTests.cs
- dotnet/src/SemanticKernel.UnitTests/Planning/PlanSerializationTests.cs
- dotnet/src/SemanticKernel/Orchestration/ContextVariablesConverter.cs
- dotnet/src/SemanticKernel/Planning/Plan.cs
The change improves the serialization and deserialization of Plan objects.
Allows deserialization of Plans without a context. Adds unit tests for the Plan and ContextVariables classes, which cover various scenarios and edge cases of serializing and deserializing plans and context variables.
Details:
- Updates the custom converter for the ContextVariables class, which serializes and deserializes the key-value pairs as an array of objects, instead of a dictionary. This improves the efficiency and readability of the JSON format.
- Add a new file PlanSerializationTests.cs to the SemanticKernel.UnitTests project, which contains unit tests for the Plan class. The tests verify that a plan can be serialized and deserialized correctly, and that the plan state is updated correctly after each step …
> Updates and tests for plan serialization and deserialization

- dotnet/src/SemanticKernel.UnitTests/Text/TextChunkerTests.cs
- dotnet/src/SemanticKernel/CoreSkills/ConversationSummarySkill.cs
- dotnet/src/SemanticKernel/Text/FunctionExtensions.cs
- dotnet/src/SemanticKernel/Text/TextChunker.cs
- samples/apps/copilot-chat-app/webapi/Controllers/DocumentImportController.cs
- samples/apps/github-qna-webapp-react/README.md
- samples/dotnet/github-skills/GitHubSkill.cs
To match changes in #450 
This pull request renames the SemanticTextPartitioner class to TextChunker, and updates all references to this class in the code and documentation. The TextChunker class is responsible for splitting text into smaller chunks based on tokens and paragraphs, which is useful for processing large texts or code files. The new name TextChunker reflects the functionality of the class more clearly and avoids confusion with the SemanticPartitioner class, which is a different concept that splits text into semantic segments based on embeddings.
Details:
- Rename SemanticTextPartitioner.cs to TextChunker.cs and update the class name and namespace accordingly. The TextChunker class is now in the Text namespace, which is more consistent with its purpose and the other classes in …
> Rename TextChunker from SemanticTextPartitioner

- dotnet/src/SemanticKernel.UnitTests/Planning/PlanTests.cs
- dotnet/src/SemanticKernel/Planning/Plan.cs
Fix issue with invoking plan with both string input and existing context.
This pull request refactors the Plan class to update the context variables with the input string when invoking a plan. This change allows the plan to use the input as part of the context for executing the plan steps. The pull request also adds a unit test to verify that the plan can execute with a given context and input.
Details:
- In Plan.cs, change the InvokeAsync method to create a new SKContext with empty variables if the context parameter is null, and then update the context variables with the input string.
- In PlanTests.cs, add a new test method called CanExecutePlanWithContextAsync that creates a mock context with some variables, memory, skills, and log, and then invokes a plan with the context and an input …
> [Fix] Modify Plan class to update context variables with input

- samples/apps/copilot-chat-app/webapi/Config/AIServiceOptions.cs
- samples/apps/copilot-chat-app/webapi/Config/RequiredOnPropertyValueAttribute.cs
- samples/apps/copilot-chat-app/webapi/appsettings.json
CopilotChat is failing when configured for OpenAI
- Added proper IsEmptyOrWhitespace check on AIService Endpoint validation.
> CopilotChat: Fix OpenAI configuration

- dotnet/src/SemanticKernel/Memory/Collections/MinHeap.cs
Fixes https://github.com/microsoft/semantic-kernel/issues/615.  Avoid exposing unnecessary public surface area.
.NET has a production-grade `PriorityQueue<>`, it's just not available for netstandard2.0.
> Make MinHeap internal

- dotnet/Directory.Build.targets
- dotnet/src/Connectors/Connectors.Memory.Sqlite/Connectors.Memory.Sqlite.csproj
- dotnet/src/Extensions/Planning.ActionPlanner/Planning.ActionPlanner.csproj
- dotnet/src/Extensions/Planning.SequentialPlanner/Planning.SequentialPlanner.csproj
- dotnet/src/SemanticKernel.Abstractions/SemanticKernel.Abstractions.csproj
- dotnet/src/SemanticKernel/SemanticKernel.csproj
- dotnet/src/SemanticKernel/settings.json
- dotnet/src/Skills/Skills.OpenAPI/Skills.OpenAPI.csproj
The current syntax for "InternalsVisibleTo" is ugly, opaque, and spans multiple lines. This change cleans it up and brings it into compliance with dotnet 5+ projects.
Creates a build target that transforms all single line:
`<InternalsVisibleTo Include="SemanticKernelConnectorsSqliteTests" PublicKey="$(StongNamePublicKey)"/>`
...into the full legacy format:
<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
<_Parameter1>%(InternalsVisibleTo.Identity), PublicKey="%(InternalsVisibleTo.PublicKey)</_Parameter1>
<_Parameter1_TypeName>System.String</_Parameter1_TypeName>
</AssemblyAttribute>
Note: the PublicKey attribute is included in preparation for strong name signing, but this change alone does not enable/require strong name signing. I'd like to remove most of …
> Adding InternalsVisibleTo target in csproj

- dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantMemoryStore.cs
Qdrant was failing in CopilotChat on first use when querying for vectors in collections that don't exist yet.
- Swallow 404s from Qdrant when querying for nearest match.
> Qdrant: don't throw on 404 when getting nearest match

- dotnet/src/SemanticKernel.UnitTests/Connectors/WebApi/Rest/RestApiOperationRunnerTests.cs
- samples/apps/copilot-chat-app/webapi/SemanticKernelExtensions.cs
Fix two analyzer warnings issued during the build.
> Fix two build warnings

- .github/labeler.yml
This commit simplifies the labeler rules for the kernel label by using the any and all operators instead of a list of patterns. This makes the rules more readable and easier to maintain and ensures `kernel` label is used as appropriate. The logic of the rules still exclude the SemanticKernel and SemanticKernel.Abstractions projects from the kernel label but will now include if only non-core kernel changes are made.
https://github.com/lemillermicrosoft/semantic-kernel/pull/7
https://github.com/lemillermicrosoft/semantic-kernel/pull/8
https://github.com/lemillermicrosoft/semantic-kernel/pull/9
> Simplify labeler rules for kernel label

- dotnet/src/Extensions/Extensions.UnitTests/Planning/SequentialPlanner/SequentialPlannerTests.cs
- dotnet/src/Extensions/Planning.SequentialPlanner/SequentialPlanner.cs
Added a check for empty goal in CreatePlanAsync method and threw a PlanningException with appropriate error code. Wrapped the plan parsing logic in a try-catch block and re-threw any exceptions as PlanningExceptions with a different error code. This improves the robustness and usability of the SequentialPlanner class.
> Validate goal and handle plan parsing errors in SequentialPlanner

- samples/notebooks/dotnet/06-memory-and-embeddings.ipynb
grammar changed from "Let's now revisit the our chat sample from the" to "Let's now revisit our chat sample from the"
> Why is this change required? 
_This change is required to fix the grammatical error in the sentence._
> What problem does it solve? 
_This change solves the problem of incorrect grammar in the sentence._
> What scenario does it contribute to? 
_This change contributes to the scenario where we want to have correct grammar in our chat sample._
> If it fixes an open issue, please link to the issue here. 
_Since this change does not fix an open issue, there is no link to provide._
I have made a change to the grammar in the sentence by removing the word ‘the’ which was causing the sentence to be grammatically incorrect. The overall approach I took was to identify the error in …
> Grammar Only Correction

- dotnet/src/SemanticKernel.Abstractions/AI/AIException.cs
The AIException constructor that takes an errorCode, a message, and a detail was incorrectly passing null as the detail parameter to the base constructor. This commit fixes this bug by passing the detail parameter correctly. This ensures that the detail information is preserved and available for error handling.
Bug Introduced: #701
Bug Hidden by: #596
> 🛠️Fix a bug in AIException constructor

- dotnet/src/SemanticKernel.UnitTests/AI/AIExceptionTests.cs
- dotnet/src/SemanticKernel.UnitTests/Diagnostics/ValidationExceptionTests.cs
- dotnet/src/SemanticKernel.UnitTests/KernelExceptionTests.cs
- dotnet/src/SemanticKernel.UnitTests/Memory/MemoryExceptionTests.cs
- dotnet/src/SemanticKernel.UnitTests/Planning/PlanningExceptionTests.cs
- dotnet/src/SemanticKernel.UnitTests/TemplateEngine/TemplateExceptionTests.cs
Fill unit test gaps.
Simple unit tests for the core exception types.
cc: @lemillermicrosoft
> Add unit tests for core exception types

- dotnet/src/SemanticKernel.Skills/Skills.Grpc/Extensions/GrpcOperationExtensions.cs
- dotnet/src/SemanticKernel.Skills/Skills.Grpc/Extensions/KernelGrpcExtensions.cs
- dotnet/src/SemanticKernel.Skills/Skills.Grpc/GrpcOperationRunner.cs
- dotnet/src/SemanticKernel.Skills/Skills.Grpc/Model/GrpcOperation.cs
- dotnet/src/SemanticKernel.Skills/Skills.Grpc/Skills.Grpc.csproj
- dotnet/src/SemanticKernel.Skills/Skills.UnitTests/Grpc/Extensions/GrpcOperationExtensionsTests.cs
- dotnet/src/SemanticKernel.Skills/Skills.UnitTests/Grpc/GrpcRunnerTests.cs
- dotnet/src/SemanticKernel/SemanticKernel.csproj
- samples/dotnet/kernel-syntax-examples/Example27_GrpcSkills.cs
- samples/dotnet/kernel-syntax-examples/KernelSyntaxExamples.csproj
- samples/dotnet/kernel-syntax-examples/Program.cs
This change adds functionality required for gRPC skills import to Kernel allowing SK SDK client code to register and use gRPC skills in SK SDK.
This change adds a few ImportGrpc* Kernel extension methods that can import gRPC skills from a folder or a file. Additionality, GrpcOperationRunner is changed to accept gRPC request message as JSON and return the gRPC method result as JSON as well.
> Import gRPC skills

- dotnet/src/SemanticKernel/Planning/KernelPlanExtensions.cs
Remove unnecessary overloads
These are all handled by the corresponding overload that takes an optional CancellationToken. Their presence also means the optionality of the tokens in the other overloads would never actually be used.
cc: @shawncal, @dluc
> Remove duplicative extension methods on KernelPlanExtensions

- samples/apps/copilot-chat-app/README.md
Missed adding instructions for setting Planner:AIService configuration settings.
Updated README to include Planner:AIService when setting configuration settings.
> CopilotChat: Add instructions for Planner:AIService in READMEs

- dotnet/src/Connectors/Connectors.Memory.AzureCognitiveSearch/AzureCognitiveSearchMemory.cs
- dotnet/src/Connectors/Connectors.Memory.AzureCognitiveSearch/AzureCognitiveSearchRecord.cs
* Checking if an index exists adds extra latency the first time an index is being used.
* Some indexing can be removed to reduce the quota used, and CPU usage on the service side.
* Create indexes/collections only on write only when an index doesn't exist.
* Remove some indexing from the record schema
> Improve ACS memory connector performance/cost

- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/DeploySK-Existing-AI.ps1
- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/DeploySK-Existing-AI.sh
- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/README.md
- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk-existing-ai.bicep
- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk.bicep
We can now have a distinct completion model for the planner. This aligns the deployment templates to that fact.
Add a new plannerModel parameter in the deployment templates and scripts
> Support distinct model for planner in deployment templates

- dotnet/src/Skills/Skills.OpenAPI/Extensions/KernelChatGptPluginExtensions.cs
- dotnet/src/Skills/Skills.OpenAPI/Extensions/KernelOpenApiExtensions.cs
- samples/dotnet/kernel-syntax-examples/Example22_OpenApiSkill_AzureKeyVault.cs
This PR adds two improvements:
- It extends all ImportOpenAPISkill* and ImportChatGptPluginSkill* methods to accept HTTP retry configuration.
- It improves HttpClient usage in OpenAPI skills by reusing the same instance for the same set of imported skills.
The first improvement will allow OpenAPI skill to be more resilient against unreliable REST API it tries to access. 
The second improvement will decrease number of HttpClient instances OpenAPI skills create. Instead of creating one instance of HttpClient per skill, one instance will be created per set of skills that are imported together by the same Import* method. This is the first step to decrease number of HttpClient created for OpenAPI skills and it's not the final one. Later, when agreed on a proper solution, the HttpClient could …
> Retry functionality for OpenAPI skills

- samples/apps/copilot-chat-app/webapi/appsettings.json
Default the planner to disabled since we just published a how-to video assuming the planner is not enabled.
> Default the planner to disabled since we just published a how-to video.

- dotnet/src/SemanticKernel.Abstractions/Connectors/WebApi/Rest/Model/RestApiOperation.cs
- dotnet/src/SemanticKernel.Abstractions/SemanticKernel.Abstractions.csproj
- dotnet/src/SemanticKernel.Utilities/Diagnostics/HttpStatusCodeType.cs
- dotnet/src/SemanticKernel/Orchestration/SKContextExtensions.cs
- dotnet/src/SemanticKernel/SemanticKernel.csproj
- dotnet/src/SemanticKernel/SkillDefinition/SKFunction.cs
This PR contains changes to remove `InternalsVisibleTo` dependencies between projects with business logic in entire solution. 
Now `InternalsVisibleTo` dependencies exist only for test projects.
Removed following `InternalsVisibleTo` dependencies in `SemanticKernel` and `SemanticKernel.Abstractions` projects:
1. `Microsoft.SemanticKernel.Connectors.AI.OpenAI`
2. `Microsoft.SemanticKernel.Planning.ActionPlanner`
3. `Microsoft.SemanticKernel.Planning.SequentialPlanner`
4. `Microsoft.SemanticKernel.Skills.OpenAPI`
5. `Microsoft.SemanticKernel.Connectors.Memory.CosmosDB`
> Remove InternalsVisibleTo dependencies in solution

- dotnet/src/Extensions/Extensions.UnitTests/Planning/SequentialPlanner/SequentialPlanParserTests.cs
- dotnet/src/Extensions/Planning.SequentialPlanner/SequentialPlanParser.cs
- dotnet/src/IntegrationTests/Planning/PlanTests.cs
- dotnet/src/IntegrationTests/Planning/SequentialPlanner/SequentialPlanParserTests.cs
- dotnet/src/IntegrationTests/Planning/SequentialPlanner/SequentialPlannerTests.cs
- dotnet/src/SemanticKernel.UnitTests/Planning/PlanSerializationTests.cs
- dotnet/src/SemanticKernel.UnitTests/Planning/PlanTests.cs
- dotnet/src/SemanticKernel/CoreSkills/TextMemorySkill.cs
- dotnet/src/SemanticKernel/Planning/Plan.cs
- samples/dotnet/kernel-syntax-examples/Example12_SequentialPlanner.cs
- samples/dotnet/kernel-syntax-examples/Example29_CustomPlanner.cs
- samples/dotnet/kernel-syntax-examples/Example31_CustomPlanner.cs
- samples/dotnet/kernel-syntax-examples/Program.cs
- samples/dotnet/kernel-syntax-examples/RepoUtils/PlanExtensions.cs
- samples/skills/QASkill/ContextQuery/skprompt.txt
The motivation of the PR is to demonstrate custom planning capabilities, specifically for the markup returned by `ContextQuery` function. 
In creating this example, some gaps were found in the Plan object and TextMemorySkill. This PR proposes some changes to those objects.
- Plan now updates its state with the result of each step, appending the result to the previous result if the step has more than one named output. This allows the plan to keep track of the context and the intermediate results of each step, and to pass them to the next step as input.
- A new example for using a custom planner to create and execute a plan using the Markup Skill, which can process XML markup created by the ContextQuery skill, which can generate natural language queries from a context. 
- A new example of …
> Plan,TextMemorySkill improvements and custom planner examples

- .vscode/tasks.json
This commit adds the --results-directory option to the dotnet test tasks in the .vscode/tasks.json file. This option specifies the directory where the test results and code coverage reports are stored. By setting this option, the test tasks can avoid cluttering the default TestResults folder in the solution root. The commit also adds a new test task that runs all the tests in the dotnet folder with code coverage enabled.
> 🧪Add results-directory option to dotnet test tasks

- dotnet/Directory.Packages.props
- dotnet/src/SemanticKernel.Abstractions/SemanticKernel.Abstractions.csproj
- dotnet/src/SemanticKernel/SemanticKernel.csproj
- dotnet/src/Skills/Skills.Grpc/Extensions/GrpcOperationExtensions.cs
- dotnet/src/Skills/Skills.Grpc/Extensions/KernelGrpcExtensions.cs
This PR addresses comments made in another PR to merge feature-grpc branch to the main one. It also contains a small improvement that prevents creation of HttpClient per each gRPC operation run and use only one HttpClient instance per set of skills imported together. Later, in scope of a different task, another improvement will be done to allow hosting apps to provide their instances of HttpClient, if needed.
> Addressing merge PR comments

- python/semantic_kernel/planning/__init__.py
python: fix the issue of `No module named 'semantic_kernel.planning'`.
Add __init__ file for the planning package.
> python: fix issue of No module named 'semantic_kernel.planning'

- samples/notebooks/dotnet/02-running-prompts-from-file.ipynb
the path to the glossary was incorrect.
fixed path to the glossary.
> fix path to glossary

- dotnet/src/SemanticKernel.Abstractions/Orchestration/ContextVariables.cs
- dotnet/src/SemanticKernel.UnitTests/Planning/PlanTests.cs
- dotnet/src/SemanticKernel/Planning/Plan.cs
This commit fixes a bug that allows users to pass a custom SKContext object to a plan invocation, which can override or augment the default context variables. This enables more flexibility and control over the plan execution and the output. The commit also adds a unit test to verify the functionality of the new feature.
> Add support for custom context in plan execution

- python/semantic_kernel/memory/memory_record.py
1. Why is this change required?
because calling the memory record's embedding property throws `RecursionError: maximum recursion depth exceeded`
3. What problem does it solve?
calling the memory record's embedding property throws `RecursionError: maximum recursion depth exceeded`
4. What scenario does it contribute to?
people calling the embedding attribute of a memory memory record
5. If it fixes an open issue, please link to the issue here.
NA
return the attribute instead of the property
> fix implementation to return embedding

- dotnet/src/SemanticKernel/SkillDefinition/SKFunction.cs
This PR adds function/method name into exception message that is thrown if a native function, marked with SKFunctionInputAttribute, doesn't have an input parameter of string type. The method name can be useful for debugging and troubleshooting.
> Method name is added to exception message.

- dotnet/src/Connectors/Connectors.AI.OpenAI/OpenAIKernelBuilderExtensions.cs
- dotnet/src/SemanticKernel.UnitTests/KernelTests.cs
- dotnet/src/SemanticKernel/KernelBuilder.cs
- samples/dotnet/kernel-syntax-examples/Example16_CustomLLM.cs
- samples/dotnet/kernel-syntax-examples/Example17_ChatGPT.cs
- samples/dotnet/kernel-syntax-examples/Example20_HuggingFace.cs
- samples/dotnet/kernel-syntax-examples/Example33_StreamingChat.cs
- samples/dotnet/kernel-syntax-examples/Example34_CustomChatModel.cs
This PR does following:
1. Fixes not compiling code that got broken after the merge with latest bits from the main branch.
2. Pasing the logger registered in kernel builder to all service registered by With* kernel extension methods.
3. Removes unnecessary logger parameter from signatures of all With* kernel extension methods.
> Improvements + fixes

- samples/apps/copilot-chat-app/webapi/Skills/ChatSkill.cs
- samples/apps/copilot-chat-app/webapi/Skills/CopilotChatPlanner.cs
The planner should not get called if there are no functions available to it.
CopilotChatPlanner now checks if there are functions available before attempting to create a plan. If there are no functions available it returns an empty plan without interacting with the AI.
> Copilotchat: Don't call the planner if there are no functions available

- dotnet/nuget/nuget-package.props
- dotnet/src/SemanticKernel.UnitTests/SkillDefinition/SkillCollectionTests.cs
- dotnet/src/SemanticKernel/SkillDefinition/SkillCollection.cs
* Functions stored in a skill can be replaced, fix regression introduced in the last release
* Bump version to 0.14
> Allow to replace functions (fix regression)

- dotnet/src/Skills/Skills.Web/Bing/BingConnector.cs
- dotnet/src/Skills/Skills.Web/Google/GoogleConnector.cs
Add string interpolation prefix so that {nameof(count)} is interpreted rather than treated as a literal.
> Fix variable name reporting in exception messages

- dotnet/src/SemanticKernel/SkillDefinition/SKFunction.cs
plan.InvokeAsync is failing with `Unable to cast object of type 'CustomFunctionAsync' to type 'System.Func`2[Microsoft.SemanticKernel.Orchestration.SKContext,System.Threading.Tasks.Task`1[Microsoft.SemanticKernel.Orchestration.SKContext]]'.`
Replaced CustomFunctionAsync delegate with Func base type.
> Fix issue with casting custom functions in plan.InvokeAsync

- samples/apps/copilot-chat-app/webapi/Config/PromptsConfig.cs
- samples/apps/copilot-chat-app/webapi/SemanticKernelExtensions.cs
- samples/apps/copilot-chat-app/webapi/Skills/PromptSettings.cs
- samples/apps/copilot-chat-app/webapi/prompts.json
CopilotChat is blowing out token limits.
- Reduced default token limit to 4096 to match gpt-3.5-turbo
- Elevated token limits to prompts.json so they can be adjusted along with other configuration values, like models.
> CopilotChat: Minor refactor of token limits and reduce to 4096 for gpt-3.5-turbo.

- samples/apps/copilot-chat-app/webapi/Skills/ChatSkill.cs
- samples/apps/copilot-chat-app/webapi/appsettings.json
Don't display full error messages in the frontend.
- Strip the full exception from the context returned to the WebApp, keeping the error description.
> CopilotChat: Slim down error messages in WebApp

- .github/workflows/lint.yml
Black wasn't running because it depended on paths-filter which was renamed in a previous commit.
> Fix linter not running

- dotnet/Directory.Packages.props
- dotnet/src/SemanticKernel.UnitTests/Orchestration/ContextVariablesConverterTests.cs
This commit updates the System.Text.Json package version to 7.0.0 and enables the CentralPackageTransitivePinningEnabled property in the Directory.Packages.props file. This property allows the central package management feature to pin the versions of transitive dependencies to the ones specified in the props file, avoiding potential conflicts or inconsistencies. This change improves the reliability and maintainability of the dotnet projects that use the Directory.Packages.props file.
The test ReadFromJsonThrowsWithInvalidJson was passing an invalid JSON string to the JsonSerializer.Deserialize method, which was expected to throw a JsonException. However, the method actually throws an ArgumentNullException in System.Text.Json 7.0.0 when the named property is missing. This commit fixes the …
> Update System.Text.Json and enable transitive pinning

- dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAICompletionTests.cs
This commit fixes the error handling for the OpenAI completion tests by using the correct error codes and messages from the AIException class. It also adds a pragma warning to disable xUnit1004 for the file, since some of the tests are used for manual verification.
> Fix error handling for OpenAI completion tests

- samples/apps/copilot-chat-app/webapi/Model/ChatSession.cs
The name CreatedOn is much more descriptive than Timestamp in the context of a chat session.
Rename Timestamp to CreateOn in ChatSession.
> Rename Timestamp to CreateOn in ChatSession

- samples/apps/copilot-chat-app/scripts/Start-Frontend.sh
- samples/apps/copilot-chat-app/scripts/Start.ps1
- samples/apps/copilot-chat-app/scripts/Start.sh
Copilot Chat "Start" scripts are failing if the path has a space in it.
Fix the path issue by changing directory at the beginning of the script. (Already doing this in the Start-Frontend and Start-Backend child scripts, but it was apparently overlooked in the parent script.) Also fix path to .env file in Start-Frontend.sh.
> Fix bug in Copilot Chat setup scripts

- python/tests/integration/completions/e2e_text_completion.py
This commit fixes a typo in the e2e_text_completion.py test file, where the word "signularity" was misspelled as "singularity". This could cause confusion or errors in the test output. The typo was corrected to "singularity" to match the intended meaning of the poem. No other changes were made to the test file or the functionality of the chatbot.
> Fix typo in poem generated by chatbot

- dotnet/Directory.Packages.props
- dotnet/src/Skills/Skills.Web/Skills.Web.csproj
Setting the PackageVersion in Directory.Packages.props to fix warning called out in https://github.com/microsoft/semantic-kernel/issues/913
> Fixing web skill package reference

- python/pyproject.toml
- python/tests/integration/completions/e2e_text_completion.py
* New version number for next SK Python release
* Change integration tests retry logic to progressively back off from 2 to 7 secs
> Bump python release number - 0.2.8.dev

- dotnet/src/Connectors/Connectors.UnitTests/Connectors.UnitTests.csproj
- dotnet/src/Extensions/Extensions.UnitTests/Extensions.UnitTests.csproj
- dotnet/src/IntegrationTests/IntegrationTests.csproj
- dotnet/src/SemanticKernel.UnitTests/SemanticKernel.UnitTests.csproj
- dotnet/src/SemanticKernel/Orchestration/ContextVariablesConverter.cs
- dotnet/src/Skills/Skills.UnitTests/Skills.UnitTests.csproj
Unit tests are currently targeting net6.0 and the UTs will only run on machines with net6.0 SDK installed. That is, if a machine has only net7.0 or net8.0, installed, the UT projects will build, but the tests will not run.
With this change, the UT projects self-identify as test projects with the tag:
`<IsTestProject>true</IsTestProject>`
...and we add the RollForward tag which ensures the UTs build for the highest installed version of the SDK:
`<RollForward>LatestMajor</RollForward>`
This ensures that the tests are runnable on any installation net6.0 or greater, including the new docker-based CI builds, each of which targets only a single SDK version.
> Adding UnitTest tags for dotnet 6,7,8 version support

- dotnet/Directory.Build.props
Build environments with only dotnet6.0 SDK installed are raising dozens of warnings:
"Mark assemblies as CLSCompliant"
This change marks all dotnet projects as CLSCompliant=false by default (at present, they are noncompliant anyway). If, in the future, we aim to make certain projects CLSCompliant, this can be overridden on a project-by-project basis.
> Add CLSCompliant=false to csproj files

- .editorconfig
- dotnet/Directory.Packages.props
- samples/apps/copilot-chat-app/webapi/Skills/ChatSkill.cs
Different versions of dotnet surface different warnings, making it difficult to standardize across environments.
This change brings in the latest netanalysers package (compatible with net6,7,8) and enables some warnings we'd like to start seeing at development time, regardless of environment.
Also fixes one "Count" warning raised by these rules.
> Add new dotnet analyzers

- dotnet/src/SemanticKernel/Memory/Collections/Score.cs
Fixing the warning:
/app/dotnet/src/SemanticKernel/Memory/Collections/Score.cs(49,17): warning CS8073: The result of the expression is always 'true' since a value of type 'Score' is never equal to 'null' of type 'Score?'
> Fix warning in Score.cs

- .github/workflows/update-version.sh
- dotnet/nuget/nuget-package.props
New SDKs raise warnings about our SDK including prerelease dependencies in a stable package.
_warning NU5104: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Azure.Search.Documents [11.5.0-beta.2, )" or update the version field in the nuspec._
Marking as "-pre" so that the builds know that we are a prerelease package too. This will not affect the names of the builds we ship, as those are overridden when packaging.
> Adding -pre tag to build version to address build warning

- samples/apps/copilot-chat-app/webapp/src/Constants.ts
Graph skill has SendEmail method, but CopilotChat didn't claim the appropriate scope.
Added 'Mail.Send' to graph scopes.
> CopilotChat: Enable Mail.Send in Microsoft Graph plugin

- dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantMemoryStore.cs
- dotnet/src/Connectors/Connectors.UnitTests/Memory/Qdrant/QdrantMemoryStoreTests.cs
Bug discovered over at #949 - this fixes the condition and updates the corresponding unit test
> Fix incorrect condition in QdrantMemoryStore.DeleteCollectionAsync

- samples/notebooks/python/04-context-variables-chat.ipynb
Fix an authentication issue with the fourth Python notebook, by coping from one of the others.
Fixes #1021 
Copy/paste from another notebook
> Fix authentication in notebook

- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk-existing-azureopenai.json
- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk-existing-openai.json
- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk-new.json
Although the source bicep file to deploy SK to Azure was updated to the latest appsettings.json format, the ARM templates it generates were not. The "Deploy to Azure" buttons use the ARM templates and currently deploy broken services.
Generated ARM json files with the following commands:
az bicep build -f sk-new.bicep
az bicep build -f sk-existing-azureopenai.bicep
az bicep build -f sk-existing-openai.bicep
> Bring ARM templates up to date with their bicep counterparts

- dotnet/src/SemanticKernel/SkillDefinition/ImportSemanticSkillFromDirectory.cs
Clean up an XML comment that was rendering poorly in IntelliSense.
Summaries should be kept short, typically just one sentence. Other details should be put into remarks. And if there's any kind of complicated formatting involved, the appropriate XML tags should be used so that docs and IntelliSense can render it well.
Note that there is a separate `<example></example>` tag which I've not used here, as Visual Studio only renders summaries/remarks in IntelliSense today and it seemed like the intent of whoever authored this was to include the example prominently.  If that doesn't need to be shown, it'd be better still to separate the example out into such tags.
Before
After
> Fix unweildy XML comment leading to poor IntelliSense

- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/README.md
- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/main.bicep
- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk-existing-azureopenai.json
- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk-existing-openai.json
- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk-new.json
Due to one of the many changes that came in recently, we get CORS problems when trying to access the Copilot Chat from the frontend when deployed using our templates.
- Change templates to properly deploy CORS.
- Add some documentation around CORS.
> Deploy CORS correctly

- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/DeploySK-Existing-AzureOpenAI.ps1
- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/DeploySK-Existing-AzureOpenAI.sh
- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/DeploySK-Existing-OpenAI.ps1
- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/DeploySK-Existing-OpenAI.sh
- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/DeploySK.ps1
- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/DeploySK.sh
- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk-existing-azureopenai.json
- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk-existing-openai.json
- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/sk-new.json
Qdrant deployed to Azure is not currently secured.
- Remove Qdrant from cloud deployment while securing work progresses
- Update payload package zipfile name.
> Remove Qdrant from webapi scripts and update default package zip filename

- samples/apps/copilot-chat-app/webapi/CopilotChat/Controllers/ChatController.cs
Chat is emitting 404 and we want more info.
Adjusted log level and added exception info.
> Improve chat controller logging

- README.md
- samples/apps/copilot-chat-app/README.md
Copilot Chat uses packages that can only be supported by Yarn v1.x. However, we have multiple reported cases where customers follow the instructions to install the wrong version of Yarn that causes errors in the Copilot Chat app. 
1. Update the Semantic Kernel top README to use classic Yarn installation link.
2. Add Troubleshooting guidance for Yarn 2.x+ in Copilot Chat README.
~- [ ] The code follows the .NET coding conventions (https://learn.microsoft.com/dotnet/csharp/fundamentals/coding-style/coding-conventions) verified with `dotnet format`~
~- [ ] All unit tests pass, and I have added new tests where possible~
> Fix Yarn link and add QnA in CopilotChat

- samples/apps/copilot-chat-app/webapi/CopilotChatWebApi.csproj
Adding CLSCompliantAttribute(false) to Copilot Chat Web API to squash the following build warning that only shows up on net6.0 builds:
`CSC : error CA1014: Mark assemblies with CLSCompliant [/app/samples/apps/copilot-chat-app/webapi/CopilotChatWebApi.csproj]`
> Add CLSCompliantAttribute(false) to Copilot Chat Web API

- samples/apps/copilot-chat-app/webapi/CopilotChat/Controllers/BotController.cs
BotController required IMemoryStore which is not available when using Azure Cognitive Search
- Swapped IMemoryStore for ISemanticTextMemory in BotController to support high-level memory solutions, like Az Cog Search.
- Added cancellation token support to bot controller
> CopilotChat: Replace IMemoryStore with ISemanticTextMemory in BotController

- samples/apps/copilot-chat-app/webapi/CopilotChat/Controllers/BotController.cs
- samples/apps/copilot-chat-app/webapi/CopilotChat/Storage/OptionalIMemoryStore.cs
- samples/apps/copilot-chat-app/webapi/SemanticKernelExtensions.cs
High level semantic memory implementations, such as Azure Cognitive Search, do not allow for providing embeddings when storing memories. We wrap the memory store in an optional memory store to allow controllers to pass dependency injection validation and potentially optimize for a lower-level memory implementation (e.g. Qdrant). Lower level memory implementations (i.e., IMemoryStore) allow for reusing embeddings, whereas high level memory implementation (i.e., ISemanticTextMemory) assume embeddings get recalculated on every write.
- Implemented OptionalIMemoryStore to allow for BotController to pass DI validation and decide on using IMemoryStore or ISemanticTextMemory when uploading a bot.
> CopilotChat: Low-level memory optimizations when uploading bot

- python/semantic_kernel/planning/basic_planner.py
In the Python `BasicPlanner` one of the examples has a 'translate' function, but doesn't quite reference it correctly in the JSON output.
The overall approach is to make the various parts of the few-shot example in the prompt self-consistent.
> Python: Correct function name

- samples/apps/copilot-chat-app/webapp/src/components/chat/ChatInput.tsx
- samples/apps/copilot-chat-app/webapp/src/libs/services/SpeechService.ts
Make SpeechService extend the BaseService class and use the AuthHelper class. This also fixes a bug where the speech service did not support the ApiKey auth.
> make seech service extend base service and use the auth helper

- samples/apps/copilot-chat-app/webapp/src/components/chat/ChatRoom.tsx
- samples/apps/copilot-chat-app/webapp/src/components/header/UserSettings.tsx
- samples/apps/copilot-chat-app/webapp/src/libs/useChat.ts
This PR contains changes to default to MSAL username (default value: email) if name is undefined on the account. This was causing the experience to break for personal accounts as most don't have "Name" attribute defined.
Fix for issue here: https://github.com/microsoft/semantic-kernel/issues/912
> Fallback to username (email) if name is not available on msal account info

- samples/apps/copilot-chat-app/webapp/src/libs/services/DocumentImportService.ts
DocumentImportService needs to extend BaseService to get all the auth / header handling implemented in the parent.
> Using BaseService as parent class for DocumentImportService

- samples/apps/copilot-chat-app/webapp/src/components/chat/chat-list/ChatList.tsx
- samples/apps/copilot-chat-app/webapp/src/libs/useChat.ts
- samples/apps/copilot-chat-app/webapp/src/redux/features/conversations/ChatState.ts
- samples/apps/copilot-chat-app/webapp/src/redux/features/conversations/conversationsSlice.ts
…tname, upload bot, etc.)
Having chatlist timestamp reflect time of last change affecting chat (i.e., time bot was uploaded, chat name change, etc.).
This value is computed in session only. If session is refreshed, chat list will be ordered timestamp of last message in each chat, with most recent message on top. 
Notice difference in timestamp of last message vs timestamp in chatlist (reflects time bot was uploaded)
> Having chatlist timestamp reflect time of last change

- samples/apps/copilot-chat-app/webapi/DeploymentTemplates/main.bicep
The deployment templates often fail because of race conditions leading to the app service to not be in a good state when we want to apply settings, executable or extensions to it.
Adjust "dependsOn" statements in bicep files
> Fix deployment race condition

- dotnet/src/SemanticKernel.UnitTests/SkillDefinition/SKFunctionTests2.cs
- dotnet/src/SemanticKernel.UnitTests/SkillDefinition/SKFunctionTests3.cs
- dotnet/src/SemanticKernel/SkillDefinition/SKFunction.cs
- samples/dotnet/github-skills/GitHubSkill.cs
- samples/dotnet/kernel-syntax-examples/Example22_OpenApiSkill_AzureKeyVault.cs
Simplify native function invocation and prepare for additional functionality.
The current approach involves exactly matching the target method against a fixed set of known signatures.  I've revised it to instead be a little more dynamic, such that it instead just looks for valid parameters (e.g. currently up to one string and up to one SKContext) and valid return types (e.g. void, string, context, and tasks of each of those), and any combination of those is valid.  This not only allows the implementation to be simplified and supports combinations that someone could reasonably expect to be valid (e.g. Func(context, string) rather than just Func(string, context)), but it also sets it up to easily allow for additional features to be added, e.g. parameters that match by name against context …
> Rewrite how native skill functions are invoked

- samples/apps/copilot-chat-app/webapp/src/components/chat/ChatRoom.tsx
- samples/apps/copilot-chat-app/webapp/src/components/chat/ChatWindow.tsx
- samples/apps/copilot-chat-app/webapp/src/components/chat/chat-list/ChatListItem.tsx
-webkit-fill-available is not widely supported across all browsers. It is a non-standard CSS value and doesn't work on Firefox (Mozilla) browsers. Changing this to a relative percentage to be more inclusive of all browsers.
Scrollbars are unaffected and clamps are unaffected as they have a default fallback in moz
Example in Firefox:
> Updating webkit values to relative percentage

- java/api-test/integration-tests/src/test/java/com/microsoft/semantickernel/e2e/AbstractKernelTest.java
- java/api-test/integration-tests/src/test/java/com/microsoft/semantickernel/e2e/TextEmbeddingsTest.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/Kernel.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/builders/BuildersSingleton.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/builders/SKBuilders.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/memory/MemoryRecord.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/memory/MemoryStore.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/memory/SemanticTextMemory.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/DefaultKernel.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/DefaultKernelBuilder.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/memory/DefaultSemanticTextMemory.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/memory/VolatileMemoryStore.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/skilldefinition/DefaultSkillCollection.java
- java/spotbugs-exclude.xml
Initial port of C# memory to Java. Includes VolatileMemoryStore, no others.  
Introduces semantickernel-api/src/main/java/com/microsoft/semantickernel/memory and 
implementation in semantickernel-core/src/main/java/com/microsoft/semantickernel/memory
e2e integration test provides a sample. See java/api-test/integration-tests/src/test/java/com/microsoft/semantickernel/e2e/TextEmbeddingsTest.java
> Basically working VolatileMemoryStore

- dotnet/src/Skills/Skills.MsGraph/CalendarSkill.cs
Rename memory to avoid confusion with internal terminology where 'memory' is associated with embeddings. 
- Renamed variable "memory" to "variables" in CalendarSkill
> Rename variable 'memory' to 'variables' in CalendarSkill

- dotnet/src/IntegrationTests/Security/TrustServiceTests.cs
- dotnet/src/SemanticKernel.Abstractions/Orchestration/ContextVariables.cs
- dotnet/src/SemanticKernel.Abstractions/Security/TrustAwareString.cs
- dotnet/src/SemanticKernel.UnitTests/Orchestration/ContextVariablesTests.cs
- dotnet/src/SemanticKernel.UnitTests/Security/TrustAwareStringTests.cs
- dotnet/src/SemanticKernel.UnitTests/Security/TrustServiceTests.cs
- dotnet/src/SemanticKernel.UnitTests/SkillDefinition/SKFunctionTests4.cs
- dotnet/src/SemanticKernel.UnitTests/TemplateEngine/Blocks/CodeBlockTests.cs
A few recommended tweaks after glancing at the new type.
- Remove the static Empty property.  Static Empty properties in .NET are expected to be singletons, whereas this was allocating a new one on every access.
- Renamed Trusted/Untrusted to be CreateTrusted/Untrusted.  Methods typically begin with verbs. (Separately I'm not sure what benefit these static methods provide over just using the ctor.)
- Sealed the type. Presumably we don't want to deal with the possibility of someone providing a custom TrustAwareString-derived type and passing that into the innards of the system, especially with it able to provide its own interface implementations (e.g. it could replace what equality means via the interface).
> A few minor suggested tweaks to TrustAwareString

- dotnet/src/Connectors/Connectors.AI.OpenAI/AzureSdk/ClientBase.cs
- dotnet/src/Connectors/Connectors.AI.OpenAI/ChatCompletion/AzureChatCompletion.cs
- dotnet/src/Connectors/Connectors.AI.OpenAI/ChatCompletion/OpenAIChatCompletion.cs
- dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/IChatCompletion.cs
- dotnet/src/SemanticKernel.Abstractions/IKernel.cs
- dotnet/src/SemanticKernel/Kernel.cs
- dotnet/src/SemanticKernel/SkillDefinition/InlineFunctionsDefinitionExtension.cs
- dotnet/src/SemanticKernel/SkillDefinition/SKFunction.cs
- samples/dotnet/kernel-syntax-examples/Example34_CustomChatModel.cs
Null is the typical / expected default value for optional strings in cases like this.
> Make optional strings default to null instead of empty

- dotnet/src/Connectors/Connectors.Memory.Qdrant/Http/ApiSchema/DeleteVectorsRequest.cs
- dotnet/src/Connectors/Connectors.Memory.Qdrant/Http/ApiSchema/UpsertVectorRequest.cs
- dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorDbClient.cs
In the Qdrant connector, during Upsert(), it checks whether the vector already exists in the db; if so, it calls `continue` and skips upserting. The expected behavior of Upsert() is Insert+Update, but currently only the insert is working updates are explicitly skipped.
Resolves https://github.com/microsoft/semantic-kernel/issues/1035
Also includes some minor cleanup on the internal request builder classes:
- DeleteRange
- UpsertRange
...allow you to create the Builder, add all operations, and Build() in a single statement, so you never have to hold an instance of the Builder as a var just to operate a loop.
> Qdrant: fix skipping upserts

- dotnet/src/Extensions/Planning.SequentialPlanner/SKContextSequentialPlannerExtensions.cs
- dotnet/src/IntegrationTests/Fakes/EmailSkillFake.cs
- dotnet/src/IntegrationTests/Security/TrustServiceTests.cs
- dotnet/src/SemanticKernel.Abstractions/Orchestration/ContextVariables.cs
- dotnet/src/SemanticKernel.Abstractions/Security/TrustAwareString.cs
- dotnet/src/SemanticKernel.UnitTests/Orchestration/ContextVariablesTests.cs
- dotnet/src/SemanticKernel.UnitTests/Planning/PlanSerializationTests.cs
- dotnet/src/SemanticKernel.UnitTests/Planning/PlanTests.cs
- dotnet/src/SemanticKernel.UnitTests/TemplateEngine/Blocks/CodeBlockTests.cs
- dotnet/src/SemanticKernel/Planning/Plan.cs
- dotnet/src/SemanticKernel/TemplateEngine/Blocks/VarBlock.cs
- dotnet/src/Skills/Skills.Document/DocumentSkill.cs
- dotnet/src/Skills/Skills.Grpc/Extensions/KernelGrpcExtensions.cs
- dotnet/src/Skills/Skills.MsGraph/CalendarSkill.cs
- dotnet/src/Skills/Skills.MsGraph/CloudDriveSkill.cs
- dotnet/src/Skills/Skills.MsGraph/EmailSkill.cs
- dotnet/src/Skills/Skills.MsGraph/TaskListSkill.cs
- dotnet/src/Skills/Skills.OpenAPI/Extensions/KernelOpenApiExtensions.cs
- dotnet/src/Skills/Skills.OpenAPI/JsonPathSkill.cs
- dotnet/src/Skills/Skills.UnitTests/MsGraph/TaskListSkillTests.cs
- dotnet/src/Skills/Skills.Web/WebFileDownloadSkill.cs
Make ContextVariables feel more like the dictionary it is.
ContextVariables waddles like a dictionary and quacks like a dictionary but for some reason isn't a dictionary.  This makes it one.  For now I added the rest of the IDictionary surface area explicitly such that it won't show up on the public surface area of ContextVariables, but we should revisit some members, like Count.  This also renames Get to TryGetValue, as that's the expected name in .NET for a method with its semantics, and it fixes the nullable behavior of the out param when it returns false.
It was also possible previously for someone to Set("input", null), in which case the Input property would return null even though the rest of the type is obviously trying to avoid that.  I changed Input to handle it.
> Make ContextVariables an actual dictionary

- samples/dotnet/KernelHttpServer/SemanticKernelFactory.cs
A change to the method signature of the kernel config extensions broke the KernelHttpServer and all sample projects that are dependent on it. 
This PR remediates and adds support for chat completion endpoints instead of text completion endpoints.
> Fix KernelHttpServer regression due to change in kernel signatures

- dotnet/Directory.Packages.props
- dotnet/src/Connectors/Connectors.Memory.CosmosDB/Connectors.Memory.CosmosDB.csproj
- dotnet/src/IntegrationTests/RedirectOutput.cs
- dotnet/src/IntegrationTests/XunitLogger.cs
- dotnet/src/SemanticKernel.Abstractions/SemanticKernel.Abstractions.csproj
- dotnet/src/Skills/Skills.UnitTests/XunitHelpers/XunitLogger.cs
Pick up bug fixes and features from these libraries in v7.
> Upgrade System.Text.Json and Microsoft.Extensions.Logging versions to 7.0

- samples/apps/github-qna-webapp-react/src/components/setup/ModelConfig.tsx
When using OpenAI in the GitHub Repo Q&A sample, an error occurs when a valid chat completions model is chosen from the dropdown list. Furthermore, selecting a text completions model passes validation but causes a bad request error when saving.
Fixed issue by updating the model validation function to test model selection against the chat completions endpoint rather than the text completions endpoint.
> GitHub Repo Q&A: Fixed issue that prevents choosing and saving an OpenAI completions model.

- .gitignore
- nuget.config
Otherwise, someone with multiple package sources defined gets dozens of warnings like the following when building the repo:
```
warning NU1507: There are 4 package sources defined in your configuration. When using central package management, please map your packa
ge sources with package source mapping (https://aka.ms/nuget-package-source-mapping) or specify a single package source. The following sources are defined: ...
```
> Add simple nuget.config to avoid lots of package management warnings

- dotnet/Directory.Packages.props
- dotnet/src/Connectors/Connectors.AI.HuggingFace/TextCompletion/TextCompletionResult.cs
- dotnet/src/Connectors/Connectors.Memory.CosmosDB/Connectors.Memory.CosmosDB.csproj
- dotnet/src/Connectors/Connectors.Memory.DuckDB/Connectors.Memory.DuckDB.csproj
- dotnet/src/Connectors/Connectors.Memory.Pinecone/Connectors.Memory.Pinecone.csproj
- dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeMemoryStore.cs
- dotnet/src/Connectors/Connectors.Memory.Postgres/Connectors.Memory.Postgres.csproj
- dotnet/src/Connectors/Connectors.Memory.Qdrant/Connectors.Memory.Qdrant.csproj
- dotnet/src/Connectors/Connectors.Memory.Sqlite/Connectors.Memory.Sqlite.csproj
- dotnet/src/Connectors/Connectors.UnitTests/Connectors.UnitTests.csproj
- dotnet/src/Connectors/Connectors.UnitTests/Memory/Pinecone/PineconeMemoryStoreTests.cs
- dotnet/src/Connectors/Connectors.UnitTests/Memory/Qdrant/QdrantMemoryStoreTests.cs
- dotnet/src/Extensions/Planning.ActionPlanner/ActionPlanResponse.cs
- dotnet/src/Extensions/Planning.ActionPlanner/EmbeddedResource.cs
- dotnet/src/Extensions/Planning.ActionPlanner/Planning.ActionPlanner.csproj
- dotnet/src/InternalUtilities/Linq/AsyncEnumerable.cs
- dotnet/src/InternalUtilities/Text/StringExtensions.cs
- dotnet/src/SemanticKernel.Abstractions/SemanticKernel.Abstractions.csproj
- dotnet/src/SemanticKernel/SemanticKernel.csproj
- samples/dotnet/kernel-syntax-examples/Example16_CustomLLM.cs
- samples/dotnet/kernel-syntax-examples/Example25_ReadOnlyMemoryStore.cs
We're using very little of the library and can easily achieve the same things without it. From the core libraries like abstractions, we shouldn't force all consumers to take the additional 1MB dependency. And from examples, we shouldn't force anyone copying/pasting to take the additional dependency
Also removed unnecessary InternalsVisibleTo that were also interfering with shared source in multiple assemblies.
> Remove System.Linq.Async dependency from SK

- dotnet/global.json
PRs are blocked since the dotnet SDK analyzers introduced a back-compat issue.
Brought in a global.json file to pin the SDK version until the next servicing release of dotnet SDK.
> Temporarily add global.json to pin the dotnet version to avoid dotnet-format failures

- .github/_typos.toml
- docs/GLOSSARY.md
- samples/apps/auth-api-webapp-react/src/components/InteractionButton.tsx
- samples/apps/copilot-chat-app/importdocument/sample-docs/ms10k.txt
- samples/apps/hugging-face-http-server/README.md
- samples/dotnet/kernel-syntax-examples/Example16_CustomLLM.cs
- samples/notebooks/python/06-memory-and-embeddings.ipynb
- samples/notebooks/python/07-hugging-face-for-skills.ipynb
> Fixing typos

- samples/dotnet/kernel-syntax-examples/Example12_SequentialPlanner.cs
- samples/dotnet/kernel-syntax-examples/Example31_CustomPlanner.cs
This pull request fixes a bug in the sequential planner example and improves the custom planner example by adding input reset and context update steps. These changes ensure that the input and context are consistent and up-to-date for each step of the plan execution.
- In the sequential planner example, add an input reset step after each plan step execution. This prevents the input from accumulating and interfering with the subsequent steps.
- In the custom planner example, update the context variables with the input before invoking the plan. This ensures that the context query skill can access the input as a variable and perform the appropriate queries.
> Fix input handling and context passing in planners

- .github/_typos.toml
This commit updates the .github/_typos.toml file to add some ignore rules for jupyter and msbuild files. These rules prevent false positives from cell id strings and package version numbers that are not actual typos. The commit also reorganizes the file to use type-specific sections instead of a default section.
> Update typos config for jupyter and msbuild files

- python/semantic_kernel/connectors/memory/weaviate/weaviate_memory_store.py
- python/tests/integration/connectors/memory/test_weaviate_memory_store.py
- python/tests/unit/skill_definition/test_functions_view.py
The addition of the field `additional metadata` to `MemoryRecord` was not propagated to the weaviate integration tests. This PR ensures that the fields are properly filled and aligned. 
- Added an entry for `"additional info"` to the memory record test fixtures for weaviate.
> Python: Fix weaviate integration tests

- dotnet/src/Skills/Skills.OpenAPI/Extensions/KernelOpenApiExtensions.cs
- dotnet/src/Skills/Skills.OpenAPI/OpenApi/OpenApiDocumentParser.cs
The OpenAPIDocumentParser class has been updated to make it kernel-agnostic and enable easy reuse in other components where the conversion functionality may not be needed or may be different.
**Disclaimer**: The conversion logic has not been changed, and the purpose of this pull request is solely to relocate the conversion logic from the parser class and not to enhance the logic itself.
> OpenAPIDocumentParser class clean-up.

- dotnet/src/SemanticKernel.UnitTests/CoreSkills/TimeSkillTests.cs
- dotnet/src/SemanticKernel/CoreSkills/TimeSkill.cs
The TimeSkill class was using the wrong format specifier for the day of the month, resulting in a two-digit year instead. This commit changes the format from "DD" to "dd", which correctly outputs the day as a number from 01 to 31. This fixes a potential confusion and inconsistency in the output of the TimeSkill methods.
> Fix day format in TimeSkill

- global.json
Removing this config file since newest dotnet sdk release 7.0.304 fixes the issues we were seeing with `dotnet-format`. 
Verifications locally:
Running `dotnet-format` on a .Net6.0 project: 
In greater SK `dotnet` solution:
> Removing global.json file that overrides dotnet sdk version

- dotnet/src/SemanticKernel/SkillDefinition/SKFunction.cs
These got messed up somehow.  It doesn't affect anything other than the naming reflecting reality.
> Fix order of bool args to GetParameterMarshalerDelegate

- dotnet/src/SemanticKernel.UnitTests/Planning/PlanTests.cs
- dotnet/src/SemanticKernel.UnitTests/Planning/PlanVariableExpansionTests.cs
- dotnet/src/SemanticKernel/Planning/Plan.cs
Fixes #1487 
This pull request adds support for expanding variables with a $ in them in plan parameters, such as JSON payloads. Previously, such variables would be replaced with an empty string or left as is, which could cause unexpected behavior or errors. This change allows the plan to use the values of the variables from the context or the plan state, and only leaves the variable as is if it is not found in either. This feature improves the flexibility and robustness of the plan execution and allows for more complex scenarios involving dynamic payloads.
Details:
- Add a unit test to verify that variables with a $ in them are expanded correctly in plan parameters
- Modify the PlanVariableExpansionTests to reflect the new behavior of leaving unknown variables as is instead of replacing …
> Fix variable expansion in plan steps

- dotnet/src/Extensions/Planning.ActionPlanner/ActionPlanner.cs
- samples/apps/copilot-chat-app/webapp/src/components/chat/plan-viewer/PlanViewer.tsx
This pull request fixes a bug in the ActionPlanner class where the plan parameters were not assigned correctly from the input parameters. It also updates some formatting
Fixes #997 
- Fix parameter assignment in ActionPlanner.CreatePlanFromParameters method
- Use plan.Parameters instead of plan.State to assign the input parameters to the plan object
- This fixes a bug where the plan state was overwritten by the input parameters, causing unexpected behavior and errors
> Fix parameter assignment in ActionPlanner

- python/semantic_kernel/core_skills/wait_skill.py
- python/tests/unit/core_skills/test_wait_skill.py
Pretty simple allows for waiting X seconds in a thread
> Python wait core skill

- samples/apps/copilot-chat-app/deploy/main.bicep
This fixes an [issue](https://github.com/microsoft/semantic-kernel/issues/1402) with uploading documents from the copilot chat sample app when Azure Cosmos DB resources are used.
The `chatmemorysources` Cosmos DB container referenced in the web API appsettings.json was missing from the bicep template and this caused the "resource not found" error.
> CopilotChat: add missing container

- docs/decisions/0003-support-multiple-native-function-args.md
1. Why is this change required? Move native functions closer to a normal C# experience.
ADR to record this decision: https://github.com/microsoft/semantic-kernel/pull/1195
> ADR to add support for multiple native function arguments of many types

- samples/apps/copilot-chat-app/webapp/src/Constants.ts
- samples/apps/copilot-chat-app/webapp/src/components/chat/plan-viewer/PlanStepCard.tsx
Fixing plan parameter filtering logic to show INPUT variables as along as the values are not empty.
> Fixing input values view logic

- dotnet/src/Skills/Skills.Grpc/Extensions/KernelGrpcExtensions.cs
The HTTP stack for Grpc skills aligned with other SK components enabling the following features: 
- using the internal SK HTTP client using provided configuration during Kernel building.
- accepting a custom/external HTTP client, giving hosting applications/client code the freedom to use their own instance.
> Http consistency: Grpc skills

- samples/apps/copilot-chat-app/deploy/deploy-webapi.ps1
- samples/apps/copilot-chat-app/deploy/deploy-webapp.ps1
Fixes missing "$" in deploy-webapp.ps1, causing a failure in CORS configuration.
> CopilotChat: deploy webapp typo fix

- .github/workflows/node-pr.yml
node-pr builds take a very long time -- often around 11 min
This runs all the sample app builds in parallel, completing in just under 4 minutes.
See successful run in branch here: 
https://github.com/microsoft/semantic-kernel/actions/runs/5330432422
> GitHub Actions: node-pr builds run in parallel

- dotnet/src/SemanticKernel/Planning/KernelPlanExtensions.cs
This commit adds two extension methods to the KernelPlanExtensions class that allow importing a plan into the kernel from either a Plan object or a JSON string. These methods simplify the process of registering custom functions based on plans and make it easier to integrate with external sources of plans. The methods use the kernel.RegisterCustomFunction method internally and return the corresponding function definition.
Resolves #1653
> Add methods to import plans into kernel

- dotnet/src/SemanticKernel.UnitTests/Planning/PlanSerializationTests.cs
- dotnet/src/SemanticKernel/Planning/Plan.cs
This commit adds a new parameter to the Plan.FromJson method that allows deserializing a plan without requiring the functions to be registered in the skill collection. This is useful for scenarios where the plan is only used for inspection or analysis, and not for execution. The default behavior is still to require the functions, and throw an exception if they are not found. The commit also adds unit tests for both cases, and updates the JSON serialization options to ignore default values.
Resolves #1631
> Add option to deserialize plan without requiring functions

- dotnet/src/SemanticKernel.Abstractions/AI/Embeddings/IEmbeddingGeneration.cs
This change is required for backward compatibility of the `Kernel.GetService` method, allowing it to return services registered as instances of classes that implement the `IEmbeddingGeneration<TValue, TEmbedding>` interface.
> Support of IEmbeddingGeneration<TValue, TEmbedding> interface by Kernel.GetService method

- dotnet/samples/KernelSyntaxExamples/Example12_SequentialPlanner.cs
- dotnet/src/Extensions/Extensions.UnitTests/Planning/SequentialPlanner/SequentialPlanParserTests.cs
- dotnet/src/Extensions/Planning.SequentialPlanner/SequentialPlanParser.cs
- dotnet/src/Extensions/Planning.SequentialPlanner/SequentialPlanner.cs
- dotnet/src/Extensions/Planning.SequentialPlanner/SequentialPlannerConfig.cs
- dotnet/src/Extensions/Planning.SequentialPlanner/skprompt.txt
- dotnet/src/IntegrationTests/Planning/SequentialPlanner/SequentialPlannerTests.cs
- dotnet/src/SemanticKernel.Abstractions/Planning/PlanningException.cs
This pull request improves the ability to create sequential plans by parsing the XML plan text and matching the function names and parameters with the registered plugin functions. It also improves the error handling and logging in the sequential planner by adding more specific error codes, messages, and exceptions for different scenarios. The main motivation for these changes is to make the plan creation more robust and flexible, and to avoid throwing exceptions when the plan XML is not well-formed or contains unknown functions. The new option, `AllowMissingFunctions`, can be set to true or false in the SequentialPlannerConfig class, and it determines whether the plan creation will fail or succeed when a function is missing in the skill library. The plan parsing logic has been improved to …
> Improve sequential plan parser with support for missing functions.

- java/semantickernel-core-skills/src/main/java/com/microsoft/semantickernel/coreskills/WaitSkill.java
- java/semantickernel-core-skills/src/test/java/com/microsoft/semantickernel/coreskills/WaitSkillTest.java
Based on the [wait_skill.py](https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/core_skills/wait_skill.py)
I implemented the WaitSkill by using Mono of Project Reactor.
> Java - Waitskill added

- dotnet/samples/KernelSyntaxExamples/Example12_SequentialPlanner.cs
- dotnet/src/Extensions/Extensions.UnitTests/Planning/SequentialPlanner/SequentialPlanParserTests.cs
- dotnet/src/Extensions/Planning.SequentialPlanner/SKContextSequentialPlannerExtensions.cs
- dotnet/src/Extensions/Planning.SequentialPlanner/SequentialPlanParser.cs
- dotnet/src/Extensions/Planning.SequentialPlanner/SequentialPlanner.cs
- dotnet/src/Extensions/Planning.SequentialPlanner/SequentialPlannerConfig.cs
- dotnet/src/Extensions/Planning.SequentialPlanner/skprompt.txt
- dotnet/src/IntegrationTests/Planning/SequentialPlanner/SequentialPlanParserTests.cs
- dotnet/src/IntegrationTests/Planning/SequentialPlanner/SequentialPlannerTests.cs
This change is part of a need to enable planners that can reference a large list of potential plugins that aren't loaded in a kernel instance. Additionally, consumers of planners need to be able to load plugins on demand when needed by a plan. The change includes some additional improvements to the sequential plan parser and prompt.
Part of #1728 
This pull request refactors and improves the sequential plan parser and config, simplifying the code, adding new features, and fixing some issues. The main changes are:
- Use the Azure Chat Completion Service instead of the Azure Text Completion Service for the sequential planner, and lower the relevancy threshold for creating a plan. This allows for more flexibility and creativity in generating plans, and improves the performance and accuracy …
> SequentialPlanner - Allow custom manual discovery and loading.

- dotnet/src/SemanticKernel.UnitTests/Text/TextChunkerTests.cs
- dotnet/src/SemanticKernel/Text/TextChunker.cs
TextChunker.BuildParagraph is unnecessarily recursive and can lead to stack overflows on large inputs.
Fixes https://github.com/microsoft/semantic-kernel/issues/1633
Also happens to make it more efficient with a few tweaks.
> Avoid recursion in TextChunker.BuildParagraph

- samples/dotnet/openapi-skills/OpenApiSkillsExample.csproj
- samples/dotnet/openapi-skills/Program.cs
- samples/dotnet/openapi-skills/appsettings.json
Fix for issue #1336 - When the token limit is exceeded, we unintentionally remove the system prompt from the chat history in order to remain under the token limit. Also addresses a couple other small issues with this sample.
- Remove chat history items beginning with index 1, so that the system prompt (index 0) remains in the chat history.
- Fix a naming mismatch in the configuration - the code looks for `TokenLimit` not `CompletionTokenLimit`
- Add `UserSecretsId` property to the csproj file so users won't need to run `dotnet user-secrets init` themselves.
> Fixes for OpenApiSkillsExample

- python/poetry.lock
- python/pyproject.toml
[Integration tests were failing](https://github.com/microsoft/semantic-kernel/actions/runs/5400873036) due to a problem importing torch. This might be a mismatch in torch and cuda dependencies.  Reverting torch to 2.0.0 led to successful integration tests here: https://github.com/mkarle/semantic-kernel/actions/runs/5405696396
- Locally, I reverted torch to 2.0.0 and integration tests succeeded
- Then, I upgraded torch back to 2.0.1 and integration tests still succeeded
- In my GitHub Actions, reverting to 2.0.0 succeeded: https://github.com/mkarle/semantic-kernel/actions/runs/5405599455
- Upgrading back to 2.0.1 failed again, however: https://github.com/mkarle/semantic-kernel/actions/runs/5405659136
- So now I've reverted back to 2.0.0 and they succeed: …
> Reverting torch to 2.0.0

- dotnet/src/SemanticKernel/SkillDefinition/SKFunctionExtensions.cs
This change fixes #1443. There is a code path in `SKFunctionExtensions.InvokeAsync` where we don't update the context with the input from the user.
Update the `input` context variable before invoking the SK function, to ensure the input gets passed through.
> Update input when invoking function with mutable context

- dotnet/src/SemanticKernel/SkillDefinition/SKFunctionExtensions.cs
- The defaults for `mutableContext` are `true` which make it super easy to fall into this trap. I slammed my head against the wall for a while until realizing that the SK InvokeAsync method wasn't properly utilizing the `input` parameter.
> Fix SKFunction.InvokeAsync to respect `input` when passed in explicitly.

- dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAICompletionTests.cs
- dotnet/src/SemanticKernel/SkillDefinition/InlineFunctionsDefinitionExtension.cs
- dotnet/src/SemanticKernel/SkillDefinition/SKFunction.cs
- samples/skills/FunSkill/Limerick/config.json
1. Why is this change required? Default values specified in a semantic function config.json are not being used when executing the semantic function
1. Add logic to use default values when executing a semantic function
2. Add a new extension method to allow execution of the text prompt
> Fix to use semantic function default values

- python/semantic_kernel/core_skills/file_io_skill.py
- python/semantic_kernel/core_skills/math_skill.py
- python/semantic_kernel/core_skills/text_skill.py
- python/semantic_kernel/core_skills/time_skill.py
- python/semantic_kernel/core_skills/wait_skill.py
Fix for #1730 
Some core skills include example code showing how to import the skill. Some of these examples, used an invalid syntax where arguments were in the reversed order, e.g. kernel.import_skill("wait", WaitSkill()); instead of the valid kernel.import_skill(WaitSkill(), "wait").
> Python: Correct syntax in core skill examples

- java/semantickernel-core-skills/pom.xml
- java/semantickernel-core-skills/src/main/java/com/microsoft/semantickernel/coreskills/HttpSkill.java
- java/semantickernel-core-skills/src/test/java/com/microsoft/semantickernel/coreskills/HttpSkillTest.java
Added HttpSkill for Java
Based on the [http_skill.py](https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/core_skills/http_skill.py)
I implemented the Http Skill by using Mono of Project Reactor.
And I implemented the Test code with Mock.
> Java: Http skill Added

- samples/notebooks/dotnet/config/Settings.cs
While trying to reuse the Settings class used in the C# notebooks to load the Kernel configuration, I saw the parameter to specify a file was not properly used.
Very simple changes as I just updated the code to use the function parameter instead of the Class variable Default 
It is in the notebook part so no build nor tests. Notebooks are still working.
> Fixed function parameter not being used for LoadFromFile

- python/semantic_kernel/memory/semantic_text_memory.py
1. Why is this change required? To fix the SemanticTextMemory functionality
2. What problem does it solve? #1815 
3. What scenario does it contribute to?  All  scenarios that intend on using RAG
4. If it fixes an open issue, please link to the issue here. #1815 
Simple decomposition of the list of embeddings returned via `generate_embeddings_async`
> Python: Fix for SemanticTextMemory Embedding issue

- .github/labeler.yml
Labeler actions on PRs are currently failing due to a broken match rule.
Add required quotation marks for match rule with leading asterisk (see [reference](https://github.com/actions/labeler#basic-examples)).
> Fix in labeler.yml

- .github/dependabot.yml
- dotnet/Directory.Packages.props
- dotnet/samples/KernelSyntaxExamples/KernelSyntaxExamples.csproj
- dotnet/src/Connectors/Connectors.Memory.Pinecone/Model/IndexDefinition.cs
- dotnet/src/Connectors/Connectors.Memory.Postgres/Connectors.Memory.Postgres.csproj
- dotnet/src/Connectors/Connectors.UnitTests/Connectors.UnitTests.csproj
- dotnet/src/IntegrationTests/IntegrationTests.csproj
- dotnet/src/IntegrationTests/RedirectOutput.cs
- dotnet/src/IntegrationTests/XunitLogger.cs
- dotnet/src/Skills/Skills.UnitTests/XunitHelpers/XunitLogger.cs
This pains me, as it's a technical step backwards.  But there are two problems today:
1) The .NET support policy today unfortunately applies not only to the .NET SDK and runtime but also to nuget packages released in the same wave, which means that if someone is relying on eg System.Text.Json and is running on .NET 6, having SK depend on System.Text.Json with a minimum version of 7.0 forces the consumer to also use the 7.0 version of System.Text.Json from the nuget, which then means that one assembly falls under the STS support policy instead of LTS support policy, which means that one assembly will have support end for it a few months earlier than it otherwise would.  I've raised this issue for further evaluation on the .NET side of things, but in the meantime, this lowers the version …
> Downgrade several 7.0.* packages to 6.0.*

- .github/dependabot.yml
Don't force major version upgrades to Microsoft.Bcl.* via dependabot
> Update dependabot.yml to ignore Microsoft.Bcl.* major versions as well

- samples/apps/copilot-chat-app/CopilotChat.sln
Copilot Chat's .net project builds, runs, works just fine when opened from the `CopilotChatWebApi.csproj` directly. Every time you open this project, however, VS kindly creates a new .sln for you and offers to save it.
This just creates a convenient .sln that one can open. This can also be used by dotnet format and build scripts. It contains just the one `CopilotChatWebApi` project right now, but it's placed in the copilot-chat folder so that additional projects (tests, extensions, etc.) could be added in the future.
> Adding CopilotChat.sln

- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/orchestration/DefaultCompletionSKFunction.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/templateengine/DefaultPromptTemplateEngine.java
- java/semantickernel-extensions-parent/sequentialplanner-extensions/src/main/java/com/microsoft/semantickernel/planner/sequentialplanner/DefaultSequentialPlannerSKContext.java
Fixes a concurrency bug, `Flux.flatMap` will return the first available result rather than keeping the results in order,  changed to concatMap
> Java: Fix reactor flatMap producing out of order results

- samples/notebooks/dotnet/06-memory-and-embeddings.ipynb
1. Why is this change required?
It's a simple bug fix to account for namespace updates
3. What problem does it solve?
The memory and embedding notebook still uses the previous skills namespace and thus breaks
5. What scenario does it contribute to?
Notebooks
7. If it fixes an open issue, please link to the issue here.
Just a line change
> .Net Notebook: Fixing new skills namespace in memory notebook

- .github/ISSUE_TEMPLATE/bug_report.md
Small PR that makes it more explicit which programming language the bug is associated with
Renames the desktop section to platform and replaces the explicit NuGet package suggestion with "Source":
> Make bug report more inclusive of programming languages other than dotnet

- dotnet/src/Extensions/Planning.SequentialPlanner/SequentialPlanner.cs
Setting SequentialPlanner's max tokens to 512 in cases where it's left null. Without this, plans are never completed and cannot be parsed.
Required to fix dotnet integration tests.
> .Net: Set default max tokens for SequentialPlanner

- java/semantickernel-bom/pom.xml
Added missing required attribute to the pom for publishing to Maven central
> Java: Add URL attribute to POM.xml for Java SDK

- python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion.py
- python/semantic_kernel/connectors/ai/open_ai/services/open_ai_text_completion.py
- python/tests/unit/ai/open_ai/services/test_azure_chat_completion.py
- python/tests/unit/ai/open_ai/services/test_azure_text_completion.py
The openai API expects that logit bias is always a set. Passing None will not be successful. 
- if logit-bias is None, pass {} to the openai request create call
> Python: Default logit-bias {} instead of None

- samples/notebooks/dotnet/05-using-the-planner.ipynb
I am testing the Samples. I was getting this error:
```
Error: Microsoft.SemanticKernel.Planning.PlanningException: Create plan error: Unable to create plan
---> Microsoft.SemanticKernel.Planning.PlanningException: Invalid plan: Failed to find function 'WriterSkill.Shakespeare' in skill 'WriterSkill'.
at Microsoft.SemanticKernel.Planning.Sequential.SequentialPlanParser.ToPlanFromXml(String xmlString, String goal, SKContext context, Boolean allowMissingFunctions)
at Microsoft.SemanticKernel.Planning.SequentialPlanner.CreatePlanAsync(String goal)
--- End of inner exception stack trace ---
at Microsoft.SemanticKernel.Planning.SequentialPlanner.CreatePlanAsync(String goal)
at Submission#10.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
at …
```
> Fix typo in Samples causing error: PlanningException: Create plan err

- python/tests/integration/connectors/memory/test_milvus.py
The milvus integration tests are failing on windows systems only - get calls seem to be timing out. The integration tests rely on milvus-lite, a local, lightweight milvus application for python. Milvus is not officially supported for windows, so this PR disables the tests for any windows platform.
See milvus requirements documentation at: https://github.com/milvus-io/milvus-lite/blob/main/README.md#requirements
- mark the milvus tests as _skip_ if the local platform is windows.
> Python: skip milvus tests if the platform is windows

- dotnet/Directory.Packages.props
- dotnet/src/Connectors/Connectors.AI.OpenAI/AzureSdk/ClientBase.cs
- dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/AuthorRole.cs
Utilize the latest version of the Azure.AI.OpenAI package. This provides support for the latest Azure OpenAI REST API versions (including function calling!) and fixes a minor regression.
Fixes #2089 
Update to Azure.AI.OpenAI version 1.0.0-beta.6 and fix minor regression.
> .Net: Update to Azure.AI.OpenAI version 1.0.0-beta.6

- java/samples/sample-code/src/main/java/com/microsoft/semantickernel/syntaxexamples/javaspecific/Java_Example01_ResourceLoading.java
- java/samples/sample-code/src/main/resources/Plugins/ExamplePlugins/ExampleFunctionRoot/config.json
- java/samples/sample-code/src/main/resources/Plugins/ExamplePlugins/ExampleFunctionRoot/skprompt.txt
- java/samples/sample-code/src/main/resources/com/microsoft/semantickernel/syntaxexamples/javaspecific/Plugins/ExamplePlugins/ExampleFunction/config.json
- java/samples/sample-code/src/main/resources/com/microsoft/semantickernel/syntaxexamples/javaspecific/Plugins/ExamplePlugins/ExampleFunction/skprompt.txt
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/SkillExecutor.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/extensions/KernelExtensions.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/DefaultKernel.java
Allow importing skills from the classpath using `getResourceAsStream` so that people can embed skills inside their jar
> Java: Allow functions to be loaded from the classpath

- .github/pull_request_template.md
fixes the link to the [Development scripts](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) section.
> Fix broken link in PR template

- dotnet/samples/KernelSyntaxExamples/Example07_BingAndGoogleSkills.cs
- dotnet/samples/KernelSyntaxExamples/Example15_MemorySkill.cs
- dotnet/samples/KernelSyntaxExamples/Example30_ChatWithPrompts.cs
- dotnet/src/IntegrationTests/TemplateLanguage/PromptTemplateEngineTests.cs
- dotnet/src/SemanticKernel.Abstractions/Orchestration/SKContext.cs
- dotnet/src/SemanticKernel.UnitTests/KernelTests.cs
- dotnet/src/SemanticKernel.UnitTests/SkillDefinition/SKContextTests.cs
- dotnet/src/SemanticKernel.UnitTests/SkillDefinition/SKFunctionTests2.cs
- dotnet/src/SemanticKernel.UnitTests/SkillDefinition/SKFunctionTests3.cs
- dotnet/src/SemanticKernel.UnitTests/TemplateEngine/Blocks/CodeBlockTests.cs
- dotnet/src/SemanticKernel.UnitTests/TemplateEngine/PromptTemplateEngineTests.cs
- dotnet/src/SemanticKernel/SkillDefinition/SKFunction.cs
- dotnet/src/Skills/Skills.Core/HttpSkill.cs
- dotnet/src/Skills/Skills.Core/TextMemorySkill.cs
- dotnet/src/Skills/Skills.Core/TextSkill.cs
- dotnet/src/Skills/Skills.Core/TimeSkill.cs
The SKContext[...] indexer is simply shorthand for SKContext.Variables[...]. With additional routes to doing the same thing, there's more confusion about which to use when. In this case, there's a great deal of confusion about the mutability of these variables and whether they can/should be changed within functions or between functions.
This PR starts to address the above issues by simplifying the SDK surface. The first step is to remove the "extra" route to accessing the same data, the indexer on SKContext. 
**This is a breaking change.** The mitigation is simply to update all uses of `context["MY_VALUE"]` to `context.Variables["MY_VALUE"]`
In the PRs that follow, the mutability issue will be addressed by making it clear which variables are input, how and where to set output, and which …
> .Net: Obsolete SKContext[...] indexer

- dotnet/build.cmd
We are already in the dotnet folder, no need to cd again, as there is no dotnet folder inside the dotnet folder! 
Found this while I was building a repo for the first time!
BTW any specific reason we are running tests when building a repo for the first time!?
> .Net: Update build.cmd

- java/connectors/semantickernel-connectors-memory-sqlite/src/main/java/com/microsoft/semantickernel/connectors/memory/sqlite/Database.java
- java/connectors/semantickernel-connectors-memory-sqlite/src/main/java/com/microsoft/semantickernel/connectors/memory/sqlite/SQLConnectorException.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/memory/MemoryRecordMetadata.java
PR #2130 was merged with a couple of outstanding issues. This PR addresses those issues. 
Added SQLConnectorException and fixed code to return Mono.error(new SQLConnectorException..) instead of just throwing a runtime exception
Fixed MemoryRecordMetadata for JSON serialization/deserialization, aligning property names with those in the .NET code.
> Java: dsgrieve/update sqlite connector

- java/connectors/semantickernel-connectors-ai-openai/src/main/java/com/microsoft/semantickernel/connectors/ai/openai/chatcompletion/OpenAIChatCompletion.java
- java/connectors/semantickernel-connectors-ai-openai/src/main/java/com/microsoft/semantickernel/connectors/ai/openai/textembeddings/OpenAITextEmbeddingGeneration.java
- java/connectors/semantickernel-connectors-memory-sqlite/src/main/java/com/microsoft/semantickernel/connectors/memory/sqlite/SqliteMemoryStore.java
- java/connectors/semantickernel-connectors-memory-sqlite/src/test/java/com/microsoft/semantickernel/connectors/memory/sqlite/SqliteMemoryStoreTest.java
- java/pom.xml
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/ai/embeddings/Embedding.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/ai/embeddings/EmbeddingGeneration.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/memory/MemoryRecord.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/memory/MemoryStore.java
- java/semantickernel-bom/pom.xml
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/ai/EmbeddingVector.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/ai/vectoroperations/CosineSimilarity.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/ai/vectoroperations/Divide.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/ai/vectoroperations/DotProduct.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/ai/vectoroperations/EuclideanLength.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/ai/vectoroperations/Multiply.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/ai/vectoroperations/Normalize.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/memory/DefaultSemanticTextMemory.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/memory/VolatileMemoryStore.java
- java/semantickernel-core/src/test/java/com/microsoft/semantickernel/connectors/ai/openai/chatcompletion/OpenAIChatCompletionTest.java
- java/semantickernel-core/src/test/java/com/microsoft/semantickernel/memory/MemoryRecordTests.java
- java/semantickernel-core/src/test/java/com/microsoft/semantickernel/memory/VolatileMemoryStoreTests.java
Embedding was declared `Embedding<? extends Number>` which leads to some unfortunate hacks to cast or convert the vector from List<? extends Number> to a List<Float> (typicall). An embedding vector does not need the precision of a double, so changing `List<? extends Number> vector` to `List<Float> vector` and getting rid of the generic type will make use of Embedding much easier. 
Basically, changed `Embedding<? extends Number>` to `Embedding` and `List<? extends Number> getVector()` to `List<Float> getVector()`. The most obvious impact of this is on EmbeddingVector and the vectoroperations API where double becomes float.
> Java: refactor Embedding to be float

- java/connectors/semantickernel-connectors-ai-openai/src/main/java/com/microsoft/semantickernel/connectors/ai/openai/chatcompletion/OpenAIChatCompletion.java
- java/connectors/semantickernel-connectors-ai-openai/src/main/java/com/microsoft/semantickernel/connectors/ai/openai/textembeddings/OpenAITextEmbeddingGeneration.java
- java/connectors/semantickernel-connectors-memory-sqlite/src/main/java/com/microsoft/semantickernel/connectors/memory/sqlite/SqliteMemoryStore.java
- java/connectors/semantickernel-connectors-memory-sqlite/src/test/java/com/microsoft/semantickernel/connectors/memory/sqlite/SqliteMemoryStoreTest.java
- java/pom.xml
- java/samples/semantickernel-guice/src/main/java/com/microsoft/semantickernel/guice/SemanticKernelModule.java
- java/samples/semantickernel-guice/src/test/java/com/microsoft/semantickernel/guice/GuiceEmbeddingExample.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/ai/embeddings/Embedding.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/ai/embeddings/EmbeddingGeneration.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/ai/embeddings/TextEmbeddingGeneration.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/builders/BuildersSingleton.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/builders/SKBuilders.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/memory/MemoryRecord.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/memory/MemoryStore.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/memory/SemanticTextMemory.java
- java/semantickernel-bom/pom.xml
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/ai/EmbeddingVector.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/ai/vectoroperations/CosineSimilarity.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/ai/vectoroperations/Divide.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/ai/vectoroperations/DotProduct.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/ai/vectoroperations/EuclideanLength.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/ai/vectoroperations/Multiply.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/ai/vectoroperations/Normalize.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/memory/DefaultSemanticTextMemory.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/memory/MemoryConfiguration.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/memory/VolatileMemoryStore.java
- java/semantickernel-core/src/test/java/com/microsoft/semantickernel/TextEmbeddingsTest.java
- java/semantickernel-core/src/test/java/com/microsoft/semantickernel/connectors/ai/openai/chatcompletion/OpenAIChatCompletionTest.java
- java/semantickernel-core/src/test/java/com/microsoft/semantickernel/memory/MemoryRecordTests.java
- java/semantickernel-core/src/test/java/com/microsoft/semantickernel/memory/VolatileMemoryStoreTests.java
Embedding was refactored to be a Float instead of a ? extends Number. EmbeddingGeneration was overlooked. 
Remove `? extends Number` from declaration of EmbeddingGeneration
> Java: EmbeddingGeneration does not need generic number type

- java/connectors/semantickernel-connectors-memory-sqlite/src/main/java/com/microsoft/semantickernel/connectors/memory/sqlite/SqliteMemoryStore.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/memory/MemoryStore.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/memory/DefaultSemanticTextMemory.java
- java/semantickernel-core/src/main/java/com/microsoft/semantickernel/memory/VolatileMemoryStore.java
- java/semantickernel-core/src/test/java/com/microsoft/semantickernel/memory/VolatileMemoryStoreTests.java
Embedding changed to be just Float. Some of the MemoryStore API had `? extends Number` for similarity which can now be a Float. 
Changed getNearestMatch and getNearestMatches API in MemoryStore which had `Tuple2<MemoryRecord, ? extends Number>` to use Float instead of `? extends Number`. This second value of the tuple is the similarity value for the match. The value is computed on the embedding which is now a vector of Float. 
Also, updated VolatileMemoryStore to make it properly async.
> Java: MemoryStore updates

- dotnet/samples/KernelSyntaxExamples/Example15_MemorySkill.cs
This fixes a small type in the Console output the RetrieveAsync method requests "info5" and console says "info1"
Fix typo:
> .Net: Small typo in example

- python/semantic_kernel/planning/basic_planner.py
- samples/notebooks/python/05-using-the-planner.ipynb
The Python Jupyter notebook for Planners need to be updated to include the latest planners (Sequential and Action)
The `BasicPlanner` implementation also needed to have a separate Plan class since we now have plan object model. These changes allow for people to still use the BasicPlanner if they want.
> Python: Update Planner Jupyter Notebook to feature latest planners

- python/semantic_kernel/skill_definition/constants.py
- python/semantic_kernel/skill_definition/read_only_skill_collection.py
- python/semantic_kernel/skill_definition/skill_collection.py
- python/tests/unit/test_serialization.py
All (unit) tests are passing.
This change reduces the number of user facing changes and aligns the type of 
ReadOnlySkillCollection with the usage in SK. There is only one type of
`SkillCollection` in SK, so it doesn't make sense to make `ReadOnlySkillCollection`
a generic. If, in the future, another SkillCollection type is added, then we might
want to change this to a generic type.
> Python: [BugFix] ReadOnlySkillCollection is not a Generic

- python/semantic_kernel/planning/plan.py
- python/tests/unit/planning/test_plan_execution.py
Initially called out and fixed by @joowon-dm-snu in https://github.com/microsoft/semantic-kernel/pull/2223
This PR closes [#2094](https://github.com/microsoft/semantic-kernel/issues/2094)
There was a bug in the Plan Object Model that propagates the name of the step parameter to the next step. It should be propagating the parameter's value
In addition to making the code change to fix the bug, also added a unit test that covers the changed code. 
Below image shows the before and after of the test with the fix.
> Python: Fix parameter propagation bug in Plan Object Model

- .github/workflows/python-integration-tests.yml
Python integration test check resolves the MSTEAM_WEBHOOK as "" when run for PRs. The secret is not needed in this scenario, but the value should be non ""
> Python: Fix integration test check for PRs

- python/poetry.lock
- python/pyproject.toml
- python/semantic_kernel/connectors/memory/azure_cognitive_search/azure_cognitive_search_memory_store.py
Reverts microsoft/semantic-kernel#2435
This PR caused a breaking change to the ACS memory store's get_nearest_matches method
> Python: Revert "Python: Update Azure Cognitive Search Class Change VectorSearchAlgorithmConfi…"

- python/tests/integration/fakes/writer_skill_fake.py
- python/tests/integration/planning/sequential_planner/test_sequential_planner.py
Fix failing integration tests introduced in #2474 (May be filing follow up issue on that)
- Update WriterSkillFake to include a context parameter for the end marker
- Update test_sequential_planner to use the new end marker parameter in WriterSkillFake
> Python: Update fake skill and planner test

- dotnet/src/SemanticKernel/SkillDefinition/NativeFunction.cs
Removing `FromSemanticConfig` from NativeFunction.cs has no business being there. That code now exists in SemanticFunction.cs. This is dead code.
> .Net: Removing `FromSemanticConfig` from NativeFunction.cs

- python/semantic_kernel/connectors/ai/chat_completion_client_base.py
- python/semantic_kernel/connectors/ai/google_palm/services/gp_chat_completion.py
- python/semantic_kernel/connectors/ai/google_palm/services/gp_text_completion.py
- python/semantic_kernel/connectors/ai/hugging_face/services/hf_text_completion.py
- python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion.py
- python/semantic_kernel/connectors/ai/open_ai/services/open_ai_text_completion.py
- python/semantic_kernel/connectors/ai/text_completion_client_base.py
Makes the `logger` parameter optional in `TextCompletionClientBase.complete_async`, `TextCompletionClientBase.complete_stream_async`, `ChatCompletionClientBase.complete_chat_async`, and `ChatCompletionClientBase.complete_chat_stream_async` to match the current usage across the project where it's not passed.
It also adds that `logger` optional parameter to the inheriting classes where needed to match the base class method signatures.
Resolves #2509
> Python: Add missing parameter `logger` on inheriting classes and makes it optional 

- dotnet/src/Connectors/Connectors.AI.HuggingFace/TextCompletion/HuggingFaceTextCompletion.cs
- dotnet/src/Connectors/Connectors.AI.HuggingFace/TextEmbedding/HuggingFaceTextEmbeddingGeneration.cs
- dotnet/src/Connectors/Connectors.AI.Oobabooga/TextCompletion/OobaboogaTextCompletion.cs
- dotnet/src/Connectors/Connectors.AI.OpenAI/AzureSdk/ChatStreamingResult.cs
- dotnet/src/Connectors/Connectors.AI.OpenAI/AzureSdk/ClientBase.cs
- dotnet/src/Connectors/Connectors.AI.OpenAI/ChatCompletionWithData/AzureChatCompletionWithData.cs
- dotnet/src/Connectors/Connectors.AI.OpenAI/CustomClient/OpenAIClientBase.cs
- dotnet/src/Connectors/Connectors.AI.OpenAI/ImageGeneration/AzureOpenAIImageGeneration.cs
- dotnet/src/Connectors/Connectors.AI.OpenAI/Tokenizers/Settings/GPT3Settings.cs
- dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorDbClient.cs
- dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateMemoryStore.cs
- dotnet/src/SemanticKernel.Abstractions/AI/AIException.cs
- dotnet/src/SemanticKernel/Kernel.cs
This PR is one of the follow-up PRs aimed at gradually replacing SK custom exceptions with SKException to provide a simple, consistent, and extensible exception model. You can find more details in the [ADR](https://github.com/microsoft/semantic-kernel/blob/main/docs/decisions/0004-error-handling.md) discussing error handling.
This PR replaces AIException with SKException for cases that are not related to HTTP request status, such as invalid configuration, wrong response content, not supported function type, etc.
> .Net: [Error handling] [Part8] Replacing AIException by SKException for non-HTTP related cases

- dotnet/src/Skills/Skills.OpenAPI/OpenApi/OpenApiDocumentParser.cs
- dotnet/src/Skills/Skills.UnitTests/OpenAPI/OpenApiDocumentParserV20Tests.cs
- dotnet/src/Skills/Skills.UnitTests/OpenAPI/OpenApiDocumentParserV30Tests.cs
- dotnet/src/Skills/Skills.UnitTests/OpenAPI/OpenApiDocumentParserV31Tests.cs
- dotnet/src/Skills/Skills.UnitTests/OpenAPI/TestSkills/documentV2_0.json
- dotnet/src/Skills/Skills.UnitTests/OpenAPI/TestSkills/documentV3_0.json
- dotnet/src/Skills/Skills.UnitTests/OpenAPI/TestSkills/documentV3_1.yaml
The code provides a fallback mechanism to allow the use of operation summary if no operation description is provided.
> .Net: [OpenAPI] Fallback to operation summary if no description provided

- .github/workflows/python-integration-tests.yml
- python/samples/kernel-syntax-examples/action_planner.py
PRs #2533 and #2555 updated the integration tests to trigger off of python changes only, but did not actually have the resulting jobs require the path filtering. This means that the tests never run. 
Add path-filter job as a requirement for subsequent jobs.
> Python: Integration tests 'needs' path filter job

- dotnet/src/SemanticKernel/Memory/SemanticTextMemory.cs
- samples/dotnet/KernelHttpServer/Plugins/GitHubPlugin.cs
Not returning relevant results: [GitHub Repo Q&A Bot Sample](https://github.com/microsoft/semantic-kernel/tree/main/samples/apps/github-qna-webapp-react)
Customer reported: https://github.com/microsoft/semantic-kernel/issues/2506
RCA: Mistmatch between container name being written to and being queried.
`https://api.github.com/repos/microsoft/semantic-kernel-main`
vs
`https://github.com/microsoft/semantic-kernel-main`
> .Net: Fix GitHub Repo Q&A Bot Sample

- dotnet/samples/ApplicationInsightsExample/ApplicationInsightsExample.csproj
After template engine extraction (https://github.com/microsoft/semantic-kernel/pull/2562), it's required to include template engine project when we reference SK Core package directly. Otherwise `NullPromptTemplateEngine` will be used by default and functionality won't work as expected.
This behavior should not be reproduced in case of using SK Core package from NuGet, because template engine project is included in NuGet MetaPackage by default.
This PR contains changes to include template engine project in AppInsights example project, as it looks like only this project is impacted.
Added `TemplateEngine.PromptTemplateEngine` reference to `ApplicationInsightsExample` project.
> .Net: Fixed AppInsights example project

- dotnet/samples/KernelSyntaxExamples/Example34_CustomChatModel.cs
- dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/IChatResult.cs
`IChatResult` interface misses the ModelResult abstraction
Resolves #1565
Closes #1565
Added missing abstraction.
> .Net: Add missing ModelResult abstraction in IChatResult interface

- dotnet/src/Connectors/Connectors.Memory.Redis/RedisMemoryStore.cs
fix #2682
The case of the error message has changed
https://github.com/RediSearch/RediSearch/commit/e1ad1b099a7da2091bd14485c863e5da646d6e60#diff-4d570566161a8f0ca29c7e12a31bc46b08fa89960ff034b711235bdd897efd6fR114
> .Net: Fix redis memory store index check

- dotnet/src/Connectors/Connectors.Memory.AzureCognitiveSearch/AzureCognitiveSearchMemoryStore.cs
- dotnet/src/SemanticKernel.Abstractions/Memory/IMemoryStore.cs
When using vector search with `VectorMetricType.Cosine`, Azure Cognitive Search search result score is expressed as Cosine Distance. The value `minRelevanceScore` passed to `IMemoryStore` is expressed as Cosine Similarity, so it's important to transform the values during the comparison and when returning results.
Formulas:
```csharp
double ScoreToCosineSimilarity(double score)
{
return 2 - 1 / score;
}
double CosineSimilarityToScore(double similarity)
{
return 1 / (2 - similarity);
}
```
> .Net: Use Cosine Distance for Azure Cognitive Search

- dotnet/Directory.Packages.props
Resolves: https://github.com/microsoft/semantic-kernel/issues/2646
As described in PR https://github.com/microsoft/semantic-kernel/pull/1799, we should keep .NET packages at version 6.0.*, to support package compatibility and allow to use Azure Functions in-process deployment model.
1. Downgraded `System.Diagnostics.DiagnosticSource` package version from 7.0.2 to 6.0.0.
2. Manually tested telemetry functionality and verified that metering logic works as expected.
> .Net: Downgrade System.Diagnostics.DiagnosticSource package

- dotnet/src/Skills/Skills.OpenAPI/RestApiOperationRunner.cs
- dotnet/src/Skills/Skills.UnitTests/Connectors/WebApi/Rest/RestApiOperationRunnerTests.cs
This change is necessary to enable the RestAPI functionality to skip optional payload parameters when no arguments are provided for them.
The logic of the `RestApiOperationRunner` class has been updated to ignore optional payload parameters when their arguments are not provided.
> .Net [RestAPI] Fix to skip optional payload parameters

- dotnet/src/Extensions/Extensions.UnitTests/Planning/SequentialPlanner/SequentialPlanParserTests.cs
- dotnet/src/IntegrationTests/Planning/PlanTests.cs
- dotnet/src/SemanticKernel/Planning/Plan.cs
Update the `Plan` class to handle cases where the function is null and improve the code readability by using the `is not` pattern.
Add a new test case `CanImportAndRunPlanAsync` to verify the ability to import and run a plan involving the email skill. 
Fixes #2758
> .Net: [fix] ImportPlan extension properly import plan object.

- .vscode/tasks.json
- dotnet/src/Extensions/Planning.SequentialPlanner/SequentialPlanner.cs
Fixes #2831
This commit adds a try-catch block to handle SKException when
converting planResultString to a Plan object using the
ToPlanFromXml method. It provides a more informative error message
including the goal and relevant functions in case of failure.
> .Net: Handle exceptions when creating plan from XML 

- dotnet/src/Extensions/Extensions.UnitTests/Planning/SequentialPlanner/SequentialPlanParserTests.cs
- dotnet/src/Extensions/Planning.SequentialPlanner/SequentialPlanParser.cs
- Added support for parsing partial XML by appending a closing tag if not present.
- Enabled plan creation with global functions by handling cases where skill name is not provided.
- Updated unit tests to cover these new scenarios.
Fixes #2502
> .Net: Add support for partial XML and global functions in plan parser

- dotnet/src/SemanticKernel/SkillDefinition/InlineFunctionsDefinitionExtension.cs
When `Kernel.InvokeSemanticFunctionAsync` is used, `max_tokens` is set to `256` by default. However if you call `Kernel.CreateSemanticFunction`, `max_tokens` is set to `null` by default so the model default value is used.
The reason we are setting `max_tokens` to 256 is because OpenAI text completion models have a default of 16. However OpenAI chat completion models have a default of infinity. So the current default makes sense for text completions but not for chat completions.
To fix this, the default value of `max_tokens` will always be set to `null`.
Enable informational logging and check for token usage logs e.g.,
```
Action: GetCompletionsAsync. Azure OpenAI Deployment Name: text-davinci-003.
Prompt tokens: 14. Completion tokens: 16. Total tokens: 30.
``` …
> .Net: Fix default value for max_tokens

- dotnet/src/Functions/Functions.OpenAPI/Builders/Query/QueryStringBuilder.cs
- dotnet/src/Functions/Functions.OpenAPI/Builders/Serialization/FormStyleParameterSerializer.cs
- dotnet/src/Functions/Functions.OpenAPI/Builders/Serialization/SpaceDelimitedStyleParameterSerializer.cs
- dotnet/src/Functions/Functions.OpenAPI/Extensions/RestApiOperationExtensions.cs
- dotnet/src/Functions/Functions.OpenAPI/Model/RestApiOperationParameter.cs
- dotnet/src/Functions/Functions.UnitTests/Connectors/WebApi/Rest/RestApiOperationTests.cs
- dotnet/src/Functions/Functions.UnitTests/OpenAPI/Builders/QueryStringBuilderTests.cs
- dotnet/src/Functions/Functions.UnitTests/OpenAPI/Builders/Serialization/FormStyleParametersSerializerTests.cs
- dotnet/src/Functions/Functions.UnitTests/OpenAPI/Builders/Serialization/SpaceDelimitedStyleParametersSerializerTests.cs
- dotnet/src/Functions/Functions.UnitTests/OpenAPI/OpenApiDocumentParserV30Tests.cs
- dotnet/src/Functions/Functions.UnitTests/OpenAPI/OpenApiDocumentParserV31Tests.cs
This change is required to support two ways of serializing array query string parameters of 'spaceDelimited' style:
A query string parameter per array item - p1=a&p1=b&p1=c.
A space-separated value per array item - p1=a%20b%20c.
Related issue - https://github.com/microsoft/semantic-kernel/issues/2745
- The `SpaceDelimitedStyleParametersSerializer` class has been added to perform `spaceDelimited` style parameter serialization. For more details about parameter styles, please refer to the [link](https://swagger.io/specification/v3/#parameter-object).
- The `QueryStringBuilder` class has been modified to use the `SpaceDelimitedStyleParametersSerializer` for the `spaceDelimited` style parameter serialization.
- The `RestApiOperationParameter.Explode` property was renamed to `Expand` based on …
> .Net: Openapi space delimited query string parameters

- dotnet/src/SemanticKernel/Functions/SKFunctionTextExtensions.cs
The existing `AggregatePartitionedResultsAsync` extension method doesn't expose common arguments used when invoking functions and makes an assumption on how to separate results.
Update the `AggregatePartitionedResultsAsync` method definition with additional arguments to both utilize and proxy through to `InvokeAsync`.
> .Net: Update AggregatePartitionedResultsAsync method definition with additional arguments

- dotnet/src/Functions/Functions.OpenAPI/Builders/Serialization/ArrayParameterValueSerializer.cs
- dotnet/src/Functions/Functions.OpenAPI/Builders/Serialization/FormStyleParameterSerializer.cs
- dotnet/src/Functions/Functions.OpenAPI/Builders/Serialization/SpaceDelimitedStyleParameterSerializer.cs
- dotnet/src/Functions/Functions.UnitTests/OpenAPI/Builders/Serialization/ArrayParameterSerializerTests.cs
The `FormStyleParameterSerializer` and `SpaceDelimitedStyleParameterSerializer` classes currently share similar serialization logic for array-type parameters. The upcoming PR introduces the `PipeDelimitedStyleParameterSerializer` class, which adds a similar but slightly different serialization functionality. To prevent code duplication, the common serialization logic is moved to the `ArrayParameterValueSerializer` class.
Related issue - https://github.com/microsoft/semantic-kernel/issues/2745
- The `ArrayParameterValueSerializer` class has been added to contain common serialization functionality for parameters of an array type.
- The `FormStyleParameterSerializer` and `SpaceDelimitedStyleParameterSerializer` classes have been modified to delegate array parameter serialization to the …
> .Net: [OpenAPI] Removing duplication in parameters serialization functionality

- dotnet/src/Connectors/Connectors.Memory.Chroma/Connectors.Memory.Chroma.csproj
- dotnet/src/Connectors/Connectors.Memory.DuckDB/Connectors.Memory.DuckDB.csproj
- dotnet/src/Connectors/Connectors.Memory.Milvus/Connectors.Memory.Milvus.csproj
- dotnet/src/Connectors/Connectors.Memory.Pinecone/Connectors.Memory.Pinecone.csproj
- dotnet/src/Connectors/Connectors.Memory.Postgres/Connectors.Memory.Postgres.csproj
- dotnet/src/Connectors/Connectors.Memory.Qdrant/Connectors.Memory.Qdrant.csproj
- dotnet/src/Connectors/Connectors.Memory.Redis/Connectors.Memory.Redis.csproj
- dotnet/src/Connectors/Connectors.Memory.Sqlite/Connectors.Memory.Sqlite.csproj
- dotnet/src/Connectors/Connectors.Memory.Weaviate/Connectors.Memory.Weaviate.csproj
- dotnet/src/Extensions/Planning.ActionPlanner/ActionPlanner.cs
- dotnet/src/Extensions/Planning.SequentialPlanner/SequentialPlanner.cs
- dotnet/src/Functions/Functions.OpenAPI/Extensions/KernelAIPluginExtensions.cs
- dotnet/src/Functions/Functions.UnitTests/OpenAPI/TestPlugins/documentV2_0.json
- dotnet/src/Functions/Functions.UnitTests/OpenAPI/TestPlugins/documentV3_0.json
- dotnet/src/Functions/Functions.UnitTests/OpenAPI/TestPlugins/documentV3_1.yaml
This pull request updates plugin names, descriptions, and parameters in the Semantic Kernel project. Specifically, it updates the descriptions for several connectors and planners to refer to Semantic Kernel plugins instead of skills, and renames the 'FunSkill' plugin to 'FunPlugin'. Additionally, it updates the 'executionParameters' parameter to 'functionExecutionParameters'.
- Updated descriptions for Chroma, DuckDB, Milvus, Pinecone, Postgres, Qdrant, Redis, SQLite, and Weaviate connectors to refer to Semantic Kernel plugins instead of skills
- Updated SequentialPlanner and ActionPlanner to exclude plugins instead of skills
- Renamed 'FunSkill' plugin to 'FunPlugin' in OpenAPI documents
- Renamed 'executionParameters' parameter to 'functionExecutionParameters' in OpenAPI documents
--- …
> .Net: Rename 'Skills' -> 'Plugins' - Part 8 Update plugin names, descriptions, and parameters

- dotnet/src/Extensions/Extensions.UnitTests/Planning/SequentialPlanner/SKContextExtensionsTests.cs
- dotnet/src/Extensions/Extensions.UnitTests/Planning/SequentialPlanner/SequentialPlanParserTests.cs
- dotnet/src/Extensions/Planning.SequentialPlanner/SKContextSequentialPlannerExtensions.cs
- dotnet/src/Extensions/Planning.SequentialPlanner/SequentialPlanParser.cs
- dotnet/src/Extensions/Planning.SequentialPlanner/SequentialPlanner.cs
- dotnet/src/Extensions/Planning.SequentialPlanner/SequentialPlannerConfig.cs
- dotnet/src/Extensions/Planning.StepwisePlanner/StepwisePlanner.cs
- dotnet/src/Extensions/Planning.StepwisePlanner/StepwisePlannerConfig.cs
- dotnet/src/IntegrationTests/Planning/SequentialPlanner/SequentialPlanParserTests.cs
- dotnet/src/SemanticKernel.Core/Planning/PlannerConfigBase.cs
Moved common properties and methods from SequentialPlannerConfig and StepwisePlannerConfig to the base class PlannerConfigBase. This change improves code organization and reduces redundancy. Additionally, added a new GetSkillFunction property to the PlannerConfigBase class, allowing for custom function lookup behavior. This change provides flexibility in how skill functions are retrieved and used within the planning process.
Resolves #2911
> .Net: Refactor PlannerConfig classes for better organization

- dotnet/src/Connectors/Connectors.AI.OpenAI/OpenAIRequestSettings.cs
This pull request refactors the OpenAIRequestSettings class in the Connectors.AI.OpenAI namespace. The changes include removing the JsonPropertyOrder attribute from several properties, removing the MaxTokens default value, and changing the default value for ResultsPerPrompt. Additionally, the DefaultTextMaxTokens property is now only used for text completions.
- Removed JsonPropertyOrder attribute from Temperature, TopP, PresencePenalty, FrequencyPenalty, StopSequences, ResultsPerPrompt, ChatSystemPrompt, and TokenSelectionBiases properties
- Removed default value for MaxTokens property
- Changed default value for ResultsPerPrompt property
- Updated DefaultTextMaxTokens property to only be used for text completions
---
*Powered by [Microsoft Semantic …
> .Net: Remove JsonPropertyOrder from OpenAIRequestSettings Refactor OpenAIRequestSettings class

- dotnet/samples/KernelSyntaxExamples/Example14_SemanticMemory.cs
- dotnet/samples/KernelSyntaxExamples/Example15_TextMemoryPlugin.cs
- dotnet/samples/KernelSyntaxExamples/Example23_OpenApiPlugin_Github.cs
- dotnet/samples/KernelSyntaxExamples/Example24_OpenApiPlugin_Jira.cs
- dotnet/samples/KernelSyntaxExamples/Example31_CustomPlanner.cs
- dotnet/samples/KernelSyntaxExamples/Example35_GrpcPlugins.cs
- dotnet/samples/KernelSyntaxExamples/Example48_GroundednessChecks.cs
- dotnet/samples/KernelSyntaxExamples/Example51_StepwisePlanner.cs
This pull request updates URLs, file paths, and plugin/skill names in several examples in the Semantic Kernel repository and the KernelSyntaxExamples code samples. Specifically, it updates the URL for the ChatPlugin in Example14_SemanticMemory.cs, updates the file path for the TextMemoryPlugin in Example15_TextMemoryPlugin.cs, updates the name of an example in Example23_OpenApiPlugin_Github.cs, updates the file path for the JiraPlugin in Example24_OpenApiPlugin_Jira.cs, and updates the file path for the JiraPlugin in Example31_CustomPlanner.cs. Additionally, the ContextQuery and BingSkill have been renamed to QAPlugin and BingPlugin, respectively, in the KernelSyntaxExamples code samples. The WebSearchEngineSkill has been renamed to WebSearchEnginePlugin, and the GroundingSkill has been …
> .Net: Rename skill -> plugin in examples Update URLs, file paths, and plugin/skill names in Semantic Kernel examples and KernelSyntaxExamples

- samples/apps/auth-api-webapp-react/README.md
- samples/apps/book-creator-webapp-react/README.md
- samples/apps/chat-summary-webapp-react/README.md
- samples/apps/github-qna-webapp-react/README.md
- samples/apps/hugging-face-http-server/README.md
- samples/dotnet/KernelHttpServer/README.md
- samples/dotnet/MsGraphPluginsExample/README.md
- samples/dotnet/OpenApiPluginsExample/README.md
- samples/python/kernel_http_server/README.md
Per https://github.com/microsoft/semantic-kernel/issues/2810, we will be deprecating the current web-based samples in favor of console apps in the dotnet and python samples folders.
Added a deprecation warning to the samples
> Add deprecation warnings to samples

- dotnet/src/SemanticKernel.Core/Functions/NativeFunction.cs
````
**SKFunctionAttribute? functionAttribute = method.GetCustomAttribute<SKFunctionAttribute>(inherit: true);**
string? description = method.GetCustomAttribute<DescriptionAttribute>(inherit: true)?.Description;
var result = new MethodDetails
{
Name = functionName!,
Description = description ?? string.Empty,
};
(result.Function, result.Parameters) = GetDelegateInfo(functionName!, pluginName, target, method);
logger?.LogTrace("Method '{0}' found", result.Name);
return result;
````
> .Net: remove local variable not used

- dotnet/samples/KernelSyntaxExamples/Example57_FunctionEventHandlers.cs
- dotnet/src/SemanticKernel.Core/Kernel.cs
- dotnet/src/SemanticKernel.UnitTests/KernelTests.cs
1. One Bug was identified in the Pre/Post Handler examples where the result was not showing properly.
2. Regression introduced where changes made during FunctionInvoked event were not reflecting in the result.
3. Added Unit Tests to unsure expected behavior with events.
- In `Example57_FunctionEventHandlers.cs`, the `Console.WriteLine` statements that print the function results have been updated to use the `GetValue<string>()` method. This change ensures that the function results are correctly converted to strings before being printed.
- In `Kernel.cs`, a mechanism has been introduced to reflect any changes made to the `SKContext` by invoked handlers in the original function result. This is achieved by creating a new `FunctionResult` instance with the updated `SKContext` and its result.
- …
> .Net: Bug + Regression Fix + Added UTs

- dotnet/samples/KernelSyntaxExamples/Example04_CombineLLMPromptsAndNativeCode.cs
- dotnet/samples/KernelSyntaxExamples/Example05_InlineFunctionDefinition.cs
- dotnet/samples/KernelSyntaxExamples/Example06_TemplateLanguage.cs
- dotnet/samples/KernelSyntaxExamples/Example07_BingAndGooglePlugins.cs
- dotnet/samples/KernelSyntaxExamples/Example08_RetryHandler.cs
- dotnet/samples/KernelSyntaxExamples/Example11_WebSearchQueries.cs
- dotnet/samples/KernelSyntaxExamples/Example15_TextMemoryPlugin.cs
- dotnet/samples/KernelSyntaxExamples/Example16_CustomLLM.cs
- dotnet/samples/KernelSyntaxExamples/Example20_HuggingFace.cs
- dotnet/samples/KernelSyntaxExamples/Example21_ChatGPTPlugins.cs
- dotnet/samples/KernelSyntaxExamples/Example22_OpenApiPlugin_AzureKeyVault.cs
- dotnet/samples/KernelSyntaxExamples/Example23_OpenApiPlugin_Github.cs
- dotnet/samples/KernelSyntaxExamples/Example27_SemanticFunctionsUsingChatGPT.cs
- dotnet/samples/KernelSyntaxExamples/Example35_GrpcPlugins.cs
- dotnet/samples/KernelSyntaxExamples/Example40_DIContainer.cs
- dotnet/samples/KernelSyntaxExamples/Example52_ApimAuth.cs
- dotnet/samples/KernelSyntaxExamples/Example54_AzureChatCompletionWithData.cs
- dotnet/samples/KernelSyntaxExamples/Example56_TemplateNativeFunctionsWithMultipleArguments.cs
- dotnet/samples/KernelSyntaxExamples/Example57_FunctionEventHandlers.cs
- dotnet/samples/NCalcPlugins/LanguageCalculatorPlugin.cs
- dotnet/src/IntegrationTests/Planners/StepwisePlanner/StepwisePlannerTests.cs
- dotnet/src/Plugins/Plugins.Core/ConversationSummaryPlugin.cs
- dotnet/src/Plugins/Plugins.Core/FileIOPlugin.cs
- dotnet/src/Plugins/Plugins.Core/HttpPlugin.cs
- dotnet/src/Plugins/Plugins.Core/MathPlugin.cs
- dotnet/src/Plugins/Plugins.Core/TextPlugin.cs
- dotnet/src/Plugins/Plugins.Core/TimePlugin.cs
- dotnet/src/Plugins/Plugins.Core/WaitPlugin.cs
- dotnet/src/Plugins/Plugins.Memory/TextMemoryPlugin.cs
- dotnet/src/SemanticKernel.Core/Kernel.cs
This PR contains changes to fix SK syntax examples after `KernelResult`/`FunctionResult` functionality was merged.
1. Fixed result output in SK syntax examples.
2. Updated XML documentation.
> .Net: Fixed examples and XML documentation

- dotnet/samples/KernelSyntaxExamples/Example09_FunctionTypes.cs
The Example09_FunctionTypes sample is fixed to return actual function value instead of `functionResult` type name.
> .Net Returning actual function result

- dotnet/src/IntegrationTests/Planners/SequentialPlanner/SequentialPlannerTests.cs
- dotnet/src/Planners/Planners.Core/Extensions/FunctionViewExtensions.cs
- samples/plugins/MiscPlugin/ElementAtIndex/config.json
- samples/skills/MiscSkill/ElementAtIndex/config.json
This pull request refactors the FunctionViewExtensions.cs file in the Planners.Core.Extensions namespace. The changes include modifying the formatting of the inputs section of the ToManualString method to improve readability.
- Modified the formatting of the inputs section of the ToManualString method in the FunctionViewExtensions.cs file to improve readability.
---
*Powered by [Microsoft Semantic Kernel](https://github.com/microsoft/semantic-kernel)*
Adjust the indentation of input parameters in the `FunctionViewExtensions` class to improve readability and maintain consistency in the codebase.
Before:
```text
MiscPlugin.ElementAtIndex:
description: Get an element from an array at a specified index
inputs:
- input: The input array
- index: The index of the element to retrieve
- count: The …
```
> .Net: Update indentation in FunctionViewExtensions

- dotnet/samples/KernelSyntaxExamples/Example40_DIContainer.cs
- dotnet/samples/KernelSyntaxExamples/Example56_TemplateNativeFunctionsWithMultipleArguments.cs
Fixes to the Kernel Syntax Samples
This pull request updates the AI text completion services used by the kernel to the latest versions and adds HTTP reliability. Specifically, the OpenAI text completion service is now used instead of the Azure chat completion service. Additionally, the BasicHttpRetryHandlerFactory is added as a dependency to the kernel. The changes also include updates to the example code to reflect these changes.
- Update Microsoft.SemanticKernel.AI.TextCompletion and Microsoft.SemanticKernel.Connectors.AI.OpenAI.TextCompletion dependencies
- Add Microsoft.SemanticKernel.Reliability.Basic dependency
- Update example code to use OpenAI text completion service and BasicHttpRetryHandlerFactory
---
*Powered by [Microsoft Semantic …
> .Net: Fixes to the Kernel Syntax Samples Update AI text completion services and add HTTP reliability

- python/semantic_kernel/planning/action_planner/__init__.py
- python/semantic_kernel/planning/action_planner/action_planner.py
- python/semantic_kernel/planning/action_planner/action_planner_config.py
- python/semantic_kernel/planning/action_planner/skprompt.txt
- python/tests/unit/planning/action_planner/test_action_planner.py
Allow ActionPlanner to exclude skills and functions when generating the plan. This is very useful and other planner types all have this functionality.
Solve #3072
- Add `ActionPlannerConfig` class for three settings:
- `excluded_skills`
- `excluded_functions`
- `max_tokens`
- Filter out available skills and functions in `ActionPlanner.list_of_functions` method.
- Rename class attribute "ActionPlanner._skill_name" to "ActionPlanner.RESTRICTED_SKILL_NAME" just like other planners and update its value to "ActionPlanner". The `this.*` skills defined in `skprompt.txt` must also be updated.
- Add the missing `__init__.py`: `semantic_kernel/planning/action_planner/__init__.py`
> Python: Allow action planner to exclude skills or functions

- dotnet/src/Connectors/Connectors.AI.OpenAI/AzureSdk/AzureOpenAIClientBase.cs
- dotnet/src/Connectors/Connectors.AI.OpenAI/AzureSdk/OpenAIClientBase.cs
- dotnet/src/Connectors/Connectors.AI.OpenAI/OpenAIKernelBuilderExtensions.cs
- dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAICompletionTests.cs
- dotnet/src/IntegrationTests/Planners/PlanTests.cs
- dotnet/src/IntegrationTests/Planners/SequentialPlanner/SequentialPlanParserTests.cs
- dotnet/src/IntegrationTests/Planners/SequentialPlanner/SequentialPlannerTests.cs
- dotnet/src/IntegrationTests/Planners/StepwisePlanner/StepwisePlannerTests.cs
SK has two mechanisms that should be used to enable/configure a retry policy for accessing REST APIs:
- A custom HTTP client supplied as an argument of all `KernelBuilder.With*Service` extension methods.
- A retry handler supplied through `KernelBuilder.WithHttpHandlerFactory`, `KernelBuilder.WithRetryPolly` or `KernelBuilder.WithRetryBasic' extension methods.
This PR disables default policy provided Azure SDK library to avoid "double" retries and use the one configured by SK consumer instead.
Related issue - https://github.com/microsoft/semantic-kernel/issues/2486
> .Net Fix for double retries

- dotnet/src/Connectors/Connectors.AI.Oobabooga/TextCompletion/OobaboogaTextCompletion.cs
- dotnet/src/Connectors/Connectors.AI.Oobabooga/TextCompletion/TextCompletionRequest.cs
- dotnet/src/Connectors/Connectors.AI.Oobabooga/TextCompletion/TextCompletionResponse.cs
- dotnet/src/Connectors/Connectors.AI.Oobabooga/TextCompletion/TextCompletionResult.cs
- dotnet/src/Connectors/Connectors.AI.Oobabooga/TextCompletion/TextCompletionStreamingResponse.cs
- dotnet/src/Connectors/Connectors.AI.Oobabooga/TextCompletion/TextCompletionStreamingResult.cs
- dotnet/src/Connectors/Connectors.UnitTests/Oobabooga/OobaboogaWebSocketTestServer.cs
- dotnet/src/Connectors/Connectors.UnitTests/Oobabooga/TextCompletion/OobaboogaTextCompletionTests.cs
- dotnet/src/IntegrationTests/Connectors/Oobabooga/OobaboogaTextCompletionTests.cs
Related: https://github.com/microsoft/semantic-kernel/issues/3153
This PR contains changes to deprecate Oobabooga functionality in favor of new separate NuGet package:
https://www.nuget.org/packages/MyIA.SemanticKernel.Connectors.AI.Oobabooga/
Marked types and tests as `Obsolete`.
> .Net: Deprecated Oobabooga functionality in favor of new NuGet package

- dotnet/src/SemanticKernel.Core/Functions/FunctionCollection.cs
- dotnet/src/SemanticKernel.Core/KernelBuilder.cs
The only reason FunctionCollection was accepting an ILoggerFactory was to log an error when GetFunction threw, in which case the caller is just as capable as deciding to log, and it's really the logic error of the caller that it tried to access a non-existent method using a method designed to throw in such a case. On top of all of that, it's not a thing in .NET world for a simple collection to do its own logging.
> .Net: Remove ILoggerFactory from FunctionCollection

- dotnet/src/SemanticKernel.Abstractions/AI/AIRequestSettings.cs
- dotnet/src/SemanticKernel.Abstractions/Events/FunctionInvokedEventArgs.cs
- dotnet/src/SemanticKernel.Abstractions/Orchestration/FunctionResult.cs
> .Net: Avoid a few unnecessary Dictionary allocations in Abstractions

- dotnet/src/Functions/Functions.OpenAPI/OpenApi/OpenApiDocumentParser.cs
- dotnet/src/Functions/Functions.Semantic/Extensions/KernelSemanticFunctionExtensions.cs
- dotnet/src/InternalUtilities/src/Text/Json.cs
- dotnet/src/SemanticKernel.Abstractions/Orchestration/ModelResult.cs
The implementation of this method is identical to that of Serialize.
Also, one of the uses of Serialize immediately converted it to UTF8 bytes. JsonSerializer actually has to do more work to produce a string, as it first generates UTF8 and then transcodes, so we may as well just skip the intermediate string.
> .Net: Delete duplicative Json.ToJson

- dotnet/src/Planners/Planners.Core.UnitTests/Sequential/SequentialPlannerTests.cs
- dotnet/src/Planners/Planners.Core.UnitTests/Stepwise/ParseResultTests.cs
- dotnet/src/SemanticKernel.Abstractions/IKernel.cs
- dotnet/src/SemanticKernel.Core/Kernel.cs
- dotnet/src/SemanticKernel.Core/KernelExtensions.cs
`IKernel` declares 7 overloads of `RunAsync`, and `Kernel` dutifully implements all 7, but 6 of them are one-liner convenience methods that just delegate to the 7th.  Rather than having all of these on the interface and making any implementer implement them all, 6 of them can just be extension methods.
`IKernel` also declares an `ImportFunctions` method, which is almost entirely reflection-based logic unrelated to the kernel instance: the only thing it actually needs from the kernel is to be able to add functions to its functions collection, and `RegisterCustomFunction` provides that. So `ImportFunctions` can also be made into an extension method, such that any `IKernel` implementation gets it for free, and the interface is less cluttered.
Also fixed the nullable annotation on Kernel's …
> .Net: Move several IKernel methods to a KernelExtensions class

- python/semantic_kernel/planning/stepwise_planner/stepwise_planner.py
- python/tests/unit/planning/stepwise_planner/test_stepwise_planner_parse_result.py
I changed the substring in string check to the proper method for python. 
- [X ] The code builds clean without any errors or warnings
- [ X] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ X] All unit tests pass, and I have added new tests where possible
- [ X] I didn't break anyone :smile:
> Python: strings don't have contains method in python

- .github/workflows/codeql-analysis.yml
Include CodeQL scanning of Java code
> Add Java to the CodeQL language matrix

- dotnet/src/Planners/Planners.Core.UnitTests/Sequential/SequentialPlannerTests.cs
- dotnet/src/SemanticKernel.Abstractions/IKernel.cs
- dotnet/src/SemanticKernel.Abstractions/Orchestration/FunctionRunnerExtensions.cs
- dotnet/src/SemanticKernel.Abstractions/Orchestration/IFunctionRunner.cs
- dotnet/src/SemanticKernel.Core/Kernel.cs
- dotnet/src/SemanticKernel.Core/KernelExtensions.cs
- dotnet/src/SemanticKernel.Core/Orchestration/FunctionRunner.cs
- dotnet/src/SemanticKernel.Core/Planning/Plan.cs
- dotnet/src/SemanticKernel.UnitTests/Planning/PlanSerializationTests.cs
- dotnet/src/SemanticKernel.UnitTests/Planning/PlanTests.cs
Plans now fully utilize Kernel.RunAsync thru FunctionRunner interface, this will allow Plan steps to trigger Pre/Post Hooks defined in the Kernel that the Plan was ran.
Option to override the RequestSettings in the Kernel.RunAsync call. 
This is was required while running Plan steps that by default will use the current Plan settings.
One more step towards using RunAsync as the main entry point + Pre/Post hooks phase 2.
Resolves Partially #2324 
- Kernel.RunAsync optionally accepts `AIRequestSettings`
- PlanSteps now run in the Kernel and can trigger Pre/Post Hooks 
> .Net: Plans using FunctionRunner + RequestSettings

- dotnet/Directory.Packages.props
- samples/dotnet/Directory.Packages.props
Dependabot created a couple of PRs to upgrade version of `Roslynator.*` packages from 4.3.0 to 4.6.1. (Example: https://github.com/microsoft/semantic-kernel/pull/3274)
With this change, build pipeline is failing for .NET 6 (Details: https://github.com/microsoft/semantic-kernel/actions/runs/6657643874/job/18092783710?pr=3274):
This is happening because greater versions of `Roslyn` packages require greater versions of .NET SDK or Visual Studio (which ships together with .NET SDK):
Link: https://github.com/dotnet/roslyn/blob/main/docs/wiki/NuGet-packages.md#versioning
This PR contains changes to lock version of `Roslynator` packages to 4.3.0.
> .Net: Locked version of Roslynator packages to 4.3.0

- .github/workflows/codeql-analysis.yml
- .github/workflows/java-build.yml
- .github/workflows/java-integration-tests.yml
> Java: Run Java builds on main, only if java has changed

- .github/workflows/markdown-link-check.yml
- .github/workflows/typos.yaml
Currently these checks only run on PR's to main which means that when we try to merge `java-development` to main we have to fix these issues. We need to catch these issues when code is merged to `java-development` so they can be fixed by the person who introduces the issue.
Enable markdown link and spell checks for PR's to the `java-development` branch.
> Run markdown link check and spell check on PR's to the java-development branch

- java/README.md
- java/samples/sample-code/README.md
Updated OpenAI invalid links in Java documentation from `https://openai.com/api/` to `https://openai.com/product/`.
> Java: Fixed invalid links in documentation

- dotnet/src/Experimental/Orchestration.Flow/Experimental.Orchestration.Flow.csproj
> .Net: Fix use of InternalsVisibleTo

- .editorconfig
All the Java code uses 4 spaces indentation and the .editorconfig mentions 2. So when you have an IDE basing the indentation on the .editorconfig file, it messes things up.
> Java - Changes the indentation from 2 to 4 spaces

- .gitignore
- java/extensions/semantickernel-planners/src/main/java/com/microsoft/semantickernel/planner/sequentialplanner/SequentialPlanParser.java
- java/extensions/semantickernel-planners/src/main/java/com/microsoft/semantickernel/planner/sequentialplanner/SequentialPlanner.java
- java/extensions/semantickernel-planners/src/main/java/com/microsoft/semantickernel/planner/sequentialplanner/SequentialPlannerRequestSettings.java
- java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example12_SequentialPlanner.java
- java/semantickernel-core/src/test/java/com/microsoft/semantickernel/planner/sequentialplanner/SequentialPlannerTest.java
This is to resolve #2855 -- when using the java `SequentialPlanner`, the planner will return a plan with missing skills. This enables a configuration setting to allow/disallow the missing functions. 
This PR adds
* The configuration setting to allow/disallow missing functions. I set the default to false (throw on a missing function), technically a breaking change from what was previously implemented. Given this branch is still prerelease, I decided that's the better default configuration, and the breaking change should be okay. 
* The logic in the plan parser; to throw when `allowMissingFunctions=true` and the plan has a missing function. 
* Unit tests for the SequentialPlanner that bring its tests to parity with the other Planner unit tests and test the desired behavior for this setting …
> Java: optionally allow/disallow missing functions in sequential planner

- java/extensions/semantickernel-settings-loader/src/main/java/com/microsoft/semantickernel/connectors/ai/openai/util/AbstractOpenAIClientSettings.java
- java/extensions/semantickernel-settings-loader/src/main/java/com/microsoft/semantickernel/connectors/ai/openai/util/AzureOpenAISettings.java
- java/extensions/semantickernel-settings-loader/src/main/java/com/microsoft/semantickernel/connectors/ai/openai/util/OpenAISettings.java
When writing external APIs that enhance the configuration, we need to have access to the settings. This PR turns all the constant settings to public.
AbstractOpenAIClientSettings.KEY_SUFFIX and OpenAISettings.OPEN_AI_ORGANIZATION_SUFFIX are already public, but the other settings are private, which makes it impossible to be used by external APIs.
External APIs need to have access to all the constant settings to enhance connection.
> Java - Changes constant settings visibility to public

- dotnet/samples/KernelSyntaxExamples/Example62_CustomAIServiceSelector.cs
- dotnet/samples/KernelSyntaxExamples/Program.cs
- dotnet/src/SemanticKernel.Abstractions/Functions/ISKFunction.cs
- dotnet/src/SemanticKernel.Abstractions/Orchestration/SKContext.cs
- dotnet/src/SemanticKernel.Abstractions/Services/IAIServiceSelector.cs
- dotnet/src/SemanticKernel.Abstractions/TemplateEngine/PromptTemplateConfig.cs
- dotnet/src/SemanticKernel.Core/Functions/DelegatingAIServiceSelector.cs
- dotnet/src/SemanticKernel.Core/Functions/InstrumentedSKFunction.cs
- dotnet/src/SemanticKernel.Core/Functions/NativeFunction.cs
- dotnet/src/SemanticKernel.Core/Functions/OrderedIAIServiceSelector.cs
- dotnet/src/SemanticKernel.Core/Functions/SemanticFunction.cs
- dotnet/src/SemanticKernel.Core/Planning/InstrumentedPlan.cs
- dotnet/src/SemanticKernel.Core/Planning/Plan.cs
- dotnet/src/SemanticKernel.UnitTests/Functions/OrderedIAIServiceConfigurationProviderTests.cs
If we need to pass additional information to `IAIServiceSelector` in future we want to avoid this being a breaking change.
Changing the signature to pass:
1. `SKContext` - This contains all information about the Kernel execution context
2. `ISKFunction` - This has been extended to provide access to the model settings 
Example `IAIServiceSelector` implementation.
```csharp
public class ByModelIdAIServiceSelector : IAIServiceSelector
{
private readonly string _openAIModelId;
public ByModelIdAIServiceSelector(string openAIModelId)
{
this._openAIModelId = openAIModelId;
}
public (T?, AIRequestSettings?) SelectAIService<T>(SKContext context, ISKFunction skfunction) where T : IAIService
{
foreach (var model in skfunction.ModelSettings)
{
if (model is OpenAIRequestSettings openAIModel)
{
if …
```
> .Net: Refactor IAIServiceSelector to allow for additional parameters in future

- dotnet/samples/KernelSyntaxExamples/Example22_OpenApiPlugin_AzureKeyVault.cs
- dotnet/samples/KernelSyntaxExamples/Example24_OpenApiPlugin_Jira.cs
- dotnet/src/Functions/Functions.OpenAPI/Extensions/KernelOpenApiPluginExtensions.cs
- dotnet/src/Functions/Functions.OpenAPI/Extensions/RestApiOperationExtensions.cs
- dotnet/src/Functions/Functions.OpenAPI/Model/RestApiOperation.cs
- dotnet/src/Functions/Functions.UnitTests/OpenAPI/Extensions/KernelOpenApiPluginExtensionsTests.cs
- dotnet/src/Functions/Functions.UnitTests/OpenAPI/Extensions/RestApiOperationExtensionsTests.cs
- dotnet/src/Functions/Functions.UnitTests/OpenAPI/OpenApiDocumentParserV20Tests.cs
- dotnet/src/Functions/Functions.UnitTests/OpenAPI/OpenApiDocumentParserV30Tests.cs
- dotnet/src/Functions/Functions.UnitTests/OpenAPI/OpenApiDocumentParserV31Tests.cs
- dotnet/src/Functions/Functions.UnitTests/OpenAPI/RestApiOperationTests.cs
The kernel will artificially add a parameter named `serverl-url` to the parameter view of an OpenAPI function when the function is registered to the kernel. The optional `server-url` parameter allows planners to dynamically provide an alternative server url to override the one that is registered with the plugin. The flexibility offered by this parameter can occasionally lead to confusion among planners, causing them to create plans that fail to execute.
Local plugins and OpenAPI plugins should be indifferent to the planners. We are removing this artificially created parameter to improve the performance of planners in creating valid function calls regardless of the function type.
We are aware that there are OpenAPI plugins that require `server-url` override, such as the Jira plugin and the …
> .Net: Remove the artificially created server-url parameter from OpenAPI function parameter view

- dotnet/src/Functions/Functions.OpenAPI/Extensions/KernelOpenApiPluginExtensions.cs
- dotnet/src/Functions/Functions.OpenAPI/Extensions/OpenApiFunctionExecutionParameters.cs
- dotnet/src/Functions/Functions.OpenAPI/OpenApi/IOpenApiDocumentParser.cs
- dotnet/src/Functions/Functions.OpenAPI/OpenApi/OpenApiDocumentParser.cs
When importing OpenAPI plugins, there can be operations not supported by SK, triggering an exception.
For instance, SK currently supports only "application/json" and "text/plain" media types, and `kernel.ImportOpenApiPluginFunctionsAsync` throws an exception when encountering an operation that uses "multipart/form-data" (`SKException($"Neither of the media types of {operationId} is supported.")`).
Add new option to `OpenApiFunctionExecutionParameters` allowing to exclude some operations, e.g. those that would otherwise cause an exception.
> .Net: Allow to exclude operations when importing and OpenAPI swagger

- dotnet/src/SemanticKernel.Core/Extensions/KernelSemanticFunctionExtensions.cs
- dotnet/src/SemanticKernel.Core/Kernel.cs
Start clean-up of the code which loads the basic template package
> .Net: Remove the code to load the BasicTemplateEngine by default

- dotnet/src/Connectors/Connectors.AI.OpenAI/AzureSdk/OpenAIFunction.cs
Happened to notice this while browsing.  This string.Join should just be a concat; doing so avoids an unnecessary array allocation.
> .Net: Fix an unnecessary string.Join

- dotnet/src/Experimental/Orchestration.Flow/FlowSerializer.cs
- dotnet/src/Functions/Functions.Grpc/GrpcOperationRunner.cs
- dotnet/src/Planners/Planners.Core/Action/ActionPlanner.cs
- dotnet/src/SemanticKernel.Core/Planning/Plan.cs
JsonSerializerOptions is unexpectedly expensive to create and throw away as it gets used as a cache for state gathered as part of the Serialize/Deserialize call.
> .Net: Avoid creating new JsonSerializerOptions per Serialize/Deserialize

- dotnet/samples/KernelSyntaxExamples/Example63_FlowOrchestrator.cs
- dotnet/src/Experimental/Orchestration.Flow/AssemblyInfo.cs
- dotnet/src/InternalUtilities/src/Diagnostics/ExperimentalAttribute.cs
The C# compiler now supports an ExperimentalAttribute. It ships in .NET 8, but the compiler respects any version of the attribute with the appropriate name and shape, including one built into an assembly as internal.  Anything marked as [Experimental] then triggers a warning at usage sites, forcing the usage to acknowledge the experimental nature of the thing being consumed by either being marked [Experimental] itself or by suppressing the warning via NoWarn or a pragma directive.
This commit adds a copy of the attribute as internal, and uses it on all of the Microsoft.SemanticKernel.Experimental.Orchestration.Flow assembly, as it's obviously intended to be experimental.  We can subsequentally mark anything as [Experimental] that isn't ready to be declared stable for the 1.0 release.
> .Net: Add internal copy of [Experimental]

- dotnet/src/Planners/Planners.Core/Extensions/ReadOnlyFunctionCollectionPlannerExtensions.cs
- dotnet/src/Planners/Planners.Core/PlannerConfigBase.cs
It's incredibly unusual for public API in .NET to use LINQ's IOrderedEnumerable, especially in an interface where doing so is forcing an implementation to use OrderBy.  These should just be IEnumerable.
> .Net: Remove IOrderedEnumerable from method signatures

- dotnet/src/Planners/Planners.Core/Stepwise/ChatHistoryExtensions.cs
1. It's public but has no public members. It shouldn't be public.
2. It allocates a bunch but doesn't actually need to allocate anything (at least when not passed a TokenCounter, which it currently never is).
> .Net: Fix a few issues with ChatHistoryExtensions

- python/notebooks/00-getting-started.ipynb
- python/notebooks/01-basic-loading-the-kernel.ipynb
- python/notebooks/02-running-prompts-from-file.ipynb
- python/notebooks/03-semantic-function-inline.ipynb
- python/notebooks/04-context-variables-chat.ipynb
- python/notebooks/05-using-the-planner.ipynb
- python/notebooks/06-memory-and-embeddings.ipynb
- python/notebooks/07-hugging-face-for-skills.ipynb
- python/notebooks/08-native-function-inline.ipynb
- python/notebooks/09-groundedness-checking.ipynb
- python/notebooks/10-multiple-results-per-prompt.ipynb
- python/notebooks/11-streaming-completions.ipynb
Python Notebooks were out of date
- Bump the version
- Use OpenAI default in all notebooks
> Python: Update Python notebooks to use release 0.3.15

- dotnet/src/Planners/Planners.Core/Extensions/ReadOnlyFunctionCollectionPlannerExtensions.cs
It's not being used concurrently. It can just be a List.
> .Net: Remove use of ConcurrentBag from planner extensions

- dotnet/src/Functions/Functions.Grpc/Extensions/KernelGrpcExtensions.cs
- dotnet/src/Functions/Functions.OpenAPI/Extensions/KernelOpenApiPluginExtensions.cs
- dotnet/src/Functions/Functions.UnitTests/OpenAPI/Extensions/KernelOpenApiPluginExtensionsTests.cs
Resolves #3541
Add CancellationToken parameter to ExecuteAsync methods in KernelGrpcExtensions and KernelOpenApiPluginExtensions. Update corresponding tests to check for CancellationToken usage.
> .Net: Add CancellationToken to ExecuteAsync methods

- dotnet/src/SemanticKernel.Abstractions/Functions/EventHandlerWrapperOfT.cs
It might go away entirely in the future, but for now there's no need for it to be public.
> .Net: Make EventHandlerWrapper internal

- dotnet/src/Connectors/Connectors.AI.OpenAI/ChatCompletionWithData/AzureOpenAIChatCompletionWithData.cs
- dotnet/src/Connectors/Connectors.AI.OpenAI/ChatCompletionWithData/ChatWithDataRequest.cs
- dotnet/src/Connectors/Connectors.AI.OpenAI/OpenAIPromptExecutionSettings.cs
This fixes two bugs 
- While using WithData apis if no stopsequence is provided a BadRequest happens.
- Resolves #3715
Fix for the above bugs.
> .Net BugFix #3715 Exception Streaming OpenAI Chat WithData (Example 54)

- dotnet/samples/KernelSyntaxExamples/Example48_GroundednessChecks.cs
- dotnet/samples/KernelSyntaxExamples/Example65_HandlebarsPlanner.cs
- dotnet/samples/TelemetryExample/Program.cs
- dotnet/src/IntegrationTests/Planners/Handlebars/HandlebarsPlannerTests.cs
- dotnet/src/Planners/Planners.Handlebars/Handlebars/HandlebarsPlan.cs
- dotnet/src/Planners/Planners.Handlebars/Handlebars/HandlebarsPlanner.cs
- dotnet/src/Planners/Planners.Handlebars/Handlebars/HandlebarsTemplateEngineExtensions.cs
…onstructors
This PR moves kernel to an execution-time parameter rather than during planner instantiation.
In HandlebarsPlanner
- Remove Kernel from the constructor
- Add the Kernel as a parameter for each of the methods
In HandlbarsPlan
- Remove Kernel from the constructors
- Add the Kernel as a parameter for each of the methods
> .Net: Handlebars Planner - Passing kernel in method signatures instead of constructors

- dotnet/src/SemanticKernel.Abstractions/Kernel.cs
- dotnet/src/SemanticKernel.Abstractions/Services/OrderedAIServiceSelector.cs
- dotnet/src/SemanticKernel.UnitTests/Functions/OrderedAIServiceConfigurationProviderTests.cs
Selecting by model id was broken
Use `Kernel.GetAllServices` when searching for a service by model id
> .Net: Fix ordered service selector

- dotnet/SK-dotnet.sln
- dotnet/src/InternalUtilities/planning/PlannerInstrumentation.cs
The static PlannerInstrumentation class embodies a pattern for instrumenting planners. Before we complete the transition from the action, sequential, and stepwise planners to the newer planners including the Handlebars planner and the OpenAI stepwise planner, we want to keep the `PlannerInstrumentation.cs` file thus allowing us to code the new planners against the instrumentation pattern.
Copy `PlannerInstrumentation.cs` to `dotnet/src/InternalUtilities/planning/`
> .Net: Copy PlannerInstrumentation.cs to InternalUtilities

- dotnet/src/InternalUtilities/src/System/TypeConverterFactory.cs
- dotnet/src/SemanticKernel.Abstractions/Functions/FunctionResult.cs
- dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromMethod.cs
SK has two places where type conversion functionality is required: the 'FunctionResult' and 'KernelFunctionFromMethod' classes. In both cases, the functionality for searching and instantiating type converters is the same, so it makes sense to have it in one place for reuse.
> .Net TypeConverterFactory utility class

- python/semantic_kernel/connectors/ai/open_ai/services/azure_chat_completion.py
Small fix, deployment_name is always needed, also when using base_url for openai.
> Python: fix deployment name parameter when using base_url

- dotnet/src/SemanticKernel.Abstractions/Functions/KernelFunction.cs
- dotnet/src/SemanticKernel.Abstractions/Services/OrderedAIServiceSelector.cs
Just saves some allocation overhead on service selection.
> .Net: Change internal ExecutionSettings to be a List rather than IEnumerable

- java/connectors/semantickernel-connectors-ai-openai/src/main/java/com/microsoft/semantickernel/connectors/ai/openai/chatcompletion/OpenAIChatCompletion.java
- java/semantickernel-core/src/test/java/com/microsoft/semantickernel/connectors/ai/openai/chatcompletion/OpenAIChatCompletionTest.java
- java/semantickernel-core/src/test/java/com/microsoft/semantickernel/syntaxexamples/Example17ChatGPTTest.java
This PR fixes #3735.
The issue was that the current implementation of the `createNewChat` in `OpenAIChatCompletion` class was using the `instructions` input parameter as a _user message_, instead of a _system message_.
I've added a new parameter to the `internalCreateNewChat` method called `userMessage` so that the behavior of `completeAsync` and `completeStreamAsync` methods stay the same.
Then updated the `internalCreateNewChat` method so that it only uses a hard coded system message when it was not provided. And correctly inserts `instructions` and `userMessage` parameters with correct roles in the newly created `ChatHistory`.
> Java: Make input parameter of createNewChat method a system message in ChatHistory

- dotnet/src/Functions/Functions.OpenAPI/Authentication/OAuthTokenResponse.cs
- dotnet/src/Functions/Functions.OpenAPI/Model/RestApiOperationPayload.cs
- dotnet/src/Functions/Functions.OpenAPI/OpenAI/OpenAIAuthenticationConfig.cs
Except from the `Microsoft.SemanticKernel.Connectors.Memory.Postgres.PostgresMemoryEntry` all the other remaining records were changed back to classes.
Resolves #3697
> .Net Removing remaining public facing records

- dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatHistory.cs
Because of the decision to include function call intermediate messages in the chat history, it's now common to need to remove ranges of elements in order to trim off those at the end.
> .Net: Add ChatHistory.RemoveRange

- dotnet/src/Extensions/Extensions.UnitTests/PromptTemplate/Handlebars/HandlebarsPromptTemplateTests.cs
- dotnet/src/Extensions/PromptTemplate.Handlebars/HandlebarsPromptTemplate.cs
- dotnet/src/Functions/Functions.UnitTests/Yaml/Functions/KernelFunctionYamlTests.cs
- dotnet/src/Functions/Functions.UnitTests/Yaml/PromptExecutionSettingsNodeDeserializerTests.cs
- dotnet/src/SemanticKernel.Abstractions/PromptTemplate/InputVariable.cs
- dotnet/src/SemanticKernel.Abstractions/PromptTemplate/OutputVariable.cs
- dotnet/src/SemanticKernel.Abstractions/PromptTemplate/PromptTemplateConfig.cs
- dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromPrompt.cs
- dotnet/src/SemanticKernel.UnitTests/PromptTemplate/PromptTemplateConfigTests.cs
- samples/plugins/FunPlugin/Joke/config.json
- samples/plugins/FunPlugin/Limerick/config.json
- samples/plugins/GroundingPlugin/ExciseEntities/config.json
- samples/plugins/GroundingPlugin/ExtractEntities/config.json
- samples/plugins/GroundingPlugin/ReferenceCheckEntities/config.json
- samples/plugins/MiscPlugin/Continue/config.json
- samples/plugins/MiscPlugin/ElementAtIndex/config.json
- samples/plugins/SummarizePlugin/Summarize/config.json
- samples/plugins/WriterPlugin/Brainstorm/config.json
- samples/plugins/WriterPlugin/NovelChapter/config.json
- samples/plugins/WriterPlugin/NovelChapterWithNotes/config.json
- samples/plugins/WriterPlugin/NovelOutline/config.json
- samples/plugins/WriterPlugin/ShortPoem/config.json
- samples/plugins/WriterPlugin/Translate/config.json
> .Net: input_parameters should be input_variables to match prompt serialization

- dotnet/samples/KernelSyntaxExamples/Example56_TemplateMethodFunctionsWithMultipleArguments.cs
- dotnet/samples/KernelSyntaxExamples/Example58_ConfigureExecutionSettings.cs
ServiceId is not required for Azure Open AI and is not used for examples 56 and 58 yet it is still required to run those examples.
Remove the necessity to have ServiceId defined in those tests.
> .Net: remove serviceId requirement for examples 56 and 58

- dotnet/src/SemanticKernel.Core/TemplateEngine/Blocks/CodeBlock.cs
- dotnet/src/SemanticKernel.UnitTests/TemplateEngine/Blocks/CodeBlockTests.cs
Prevent the mutation of the arguments collection, `KernelArguments`, by ensuring that the `KernelPromptTemplate` does not add resolved prompt variables back to the collection.
> .Net Preventing arguments collection

- dotnet/samples/KernelSyntaxExamples/Example18_DallE.cs
- dotnet/samples/KernelSyntaxExamples/Example26_AADAuth.cs
- dotnet/samples/KernelSyntaxExamples/Example30_ChatWithPrompts.cs
- dotnet/samples/KernelSyntaxExamples/Example59_OpenAIFunctionCalling.cs
- dotnet/src/Connectors/Connectors.UnitTests/OpenAI/AIServicesOpenAIExtensionsTests.cs
- dotnet/src/Functions/Functions.OpenAPI/Extensions/OpenApiKernelExtensions.cs
- dotnet/src/Planners/Planners.Handlebars/Handlebars/HandlebarsPlanner.cs
- dotnet/src/Planners/Planners.OpenAI/Stepwise/FunctionCallingStepwisePlanner.cs
- dotnet/src/SemanticKernel.Abstractions/Kernel.cs
- dotnet/src/SemanticKernel.Abstractions/Services/OrderedAIServiceSelector.cs
- dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromPrompt.cs
- dotnet/src/SemanticKernel.UnitTests/Functions/KernelBuilderTests.cs
- dotnet/src/SemanticKernel.UnitTests/Functions/OrderedAIServiceConfigurationProviderTests.cs
- Renames it to GetRequiredService
- Removes backstop for ILoggerFactory/IAIServiceSelector so that it's behavior is effectively the same as IServiceProvider.GetRequiredService. Once we can remove the workaround for the lack of GetKeyedServices working for any key, this will effectively just become a call to this.Services.Get{Required}KeyedService.
- Adds dedicated property for ServiceSelector that will default to the singleton instance
> .Net: Address API review feedback on Kernel.GetService

- dotnet/src/Connectors/Connectors.AI.OpenAI/AzureSdk/AzureOpenAIClientCore.cs
- dotnet/src/Connectors/Connectors.AI.OpenAI/AzureSdk/ClientCore.cs
- dotnet/src/Connectors/Connectors.AI.OpenAI/AzureSdk/OpenAIClientCore.cs
- dotnet/src/Connectors/Connectors.AI.OpenAI/CustomClient/OpenAITextToImageClientCore.cs
- dotnet/src/SemanticKernel.Core/PromptTemplate/KernelPromptTemplate.cs
- dotnet/src/SemanticKernel.Core/TemplateEngine/Blocks/CodeBlock.cs
These calls are all allocating even when logging at the particular log level is disabled. Guard them with IsEnabled checks to avoid that.
> .Net: Guard some LogXx calls to avoid overheads when not logging

- dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatCompletionServiceExtensions.cs
- dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatPromptParser.cs
- dotnet/src/SemanticKernel.Abstractions/AI/TextGeneration/TextGenerationExtensions.cs
- dotnet/src/SemanticKernel.Abstractions/AI/XmlPromptParser.cs
- dotnet/src/SemanticKernel.UnitTests/Prompt/XmlPromptParserTests.cs
We're currently paying _a lot_ to try to parse an XML prompt, in particular for the common case when it's not actually.
> .Net: Reduce overheads of XmlPromptParser.TryParse for non-XML

- python/semantic_kernel/orchestration/delegate_handlers.py
- python/semantic_kernel/orchestration/delegate_inference.py
- python/semantic_kernel/orchestration/delegate_types.py
- python/semantic_kernel/orchestration/sk_function.py
The `invoke_stream_async` method on a native `SKFunction` is not functional. The following sample code should work:
```python
import asyncio
import semantic_kernel as sk
from semantic_kernel.skill_definition import sk_function
class StreamNativeSkill:
@sk_function(name="stream")
async def stream(self, input: str) -> None: # This should also work: -> AsyncGenerator
for i in range(5):
await asyncio.sleep(1)
yield input + str(i)
async def main():
kernel = sk.Kernel()
skill = kernel.import_skill(StreamNativeSkill(), "stream_skill")
native_stream_func = skill["stream"]
async for chunk in native_stream_func.invoke_stream_async("HELLO!"):
print(chunk)
if __name__ == "__main__":
asyncio.run(main())
```
And should output:
```
HELLO!0
HELLO!1
HELLO!2
HELLO!3
HELLO!4
```
But now it only shows:
``` …
```
> Python: Fix SKFunction.invoke_stream_async

- dotnet/src/SemanticKernel.Core/PromptTemplate/KernelPromptTemplate.cs
- dotnet/src/SemanticKernel.Core/TemplateEngine/Blocks/CodeBlock.cs
- dotnet/src/SemanticKernel.Core/TemplateEngine/Blocks/NamedArgBlock.cs
- dotnet/src/SemanticKernel.UnitTests/Functions/KernelFunctionFromPromptTests.cs
- dotnet/src/SemanticKernel.UnitTests/PromptTemplate/KernelPromptTemplateTests.cs
A common usage pattern is to call `var function = KernelFunctionFactory.CreateFromPrompt((prompt)`. 
This PR fixes the issue whereby the function created from a prompt does not contain valid parameter metadata.
- When a `IPromptTemplate` instance is created for a prompt using the `semantic-kernel` template format, the template will be parsed and the associated `PromptTemplateConfig` will be updated with any missing arguments
- **Note: This is only supported when using the `semantic-kernel` template format**
> .Net: Populate prompt function variables from template

- dotnet/samples/KernelSyntaxExamples/Example57_KernelHooks.cs
- dotnet/src/SemanticKernel.Abstractions/Events/CancelKernelEventArgs.cs
- dotnet/src/SemanticKernel.Abstractions/Events/FunctionInvokedEventArgs.cs
- dotnet/src/SemanticKernel.Abstractions/Events/FunctionInvokingEventArgs.cs
- dotnet/src/SemanticKernel.Abstractions/Events/KernelEventArgs.cs
- dotnet/src/SemanticKernel.Abstractions/Events/PromptRenderedEventArgs.cs
- dotnet/src/SemanticKernel.Abstractions/Events/PromptRenderingEventArgs.cs
- dotnet/src/SemanticKernel.Abstractions/Kernel.cs
- dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromPrompt.cs
- dotnet/src/SemanticKernel.UnitTests/Events/FunctionInvokedEventArgsTests.cs
- dotnet/src/SemanticKernel.UnitTests/Functions/FunctionFromMethodTests.cs
- dotnet/src/SemanticKernel.UnitTests/KernelTests.cs
Resolves: https://github.com/microsoft/semantic-kernel/issues/3894
Moved event args classes from `Microsoft.SemanticKernel.Events` to root namespace `Microsoft.SemanticKernel`.
> .Net: Moved Microsoft.SemanticKernel.Events classes to Microsoft.SemanticKernel

- dotnet/src/Connectors/Connectors.Memory.Qdrant/Http/ApiSchema/DeleteVectorsResponse.cs
- dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorDbClient.cs
Currently, all delete requests to Qdrant throw an exception as QdrantResponse is not deserializable because it is abstract. This PR introduces a seperate "empty" response class DeleteVectorsResponse to fix that.
#2432
> .Net: Fix for #2432: Qdrant Vector Deletion

- python/notebooks/03-semantic-function-inline.ipynb
Fixes #4146
Add missing parenthesis in markdown in 03-semantic-function-inline notebook.
> Python: Add missing parenthesis in markdown in 03-semantic-function-inline notebook

- dotnet/src/Connectors/Connectors.OpenAI/OpenAIPromptExecutionSettings.cs
- dotnet/src/Connectors/Connectors.UnitTests/OpenAI/OpenAIPromptExecutionSettingsTests.cs
Correctly sets the default value for Temperature and TopP to 1 for OpenAI models
Closes #4235
> .Net: Fix default OpenAI execution settings values

- python/semantic_kernel/orchestration/sk_function.py
Resolves #4137. The issue was that if you try to re-run the sample joke in the 00-getting-started notebook, the subsequent call to the joke hangs.
There were issues when re-running asynchronous functions (`_invoke_semantic_async` and `_invoke_native_async`) due to improper handling of asyncio event loops in a multi-threaded env. Specifically, the code had an issue when an event loop was already running, leading to hanging or blocking behavior on subsequent runs.
The change replaced the old code Python's ThreadPoolExecutor, which simplifies thread management. It handles the creation, execution, and cleanup of threads more efficiently and safely.
The new `run_async_in_executor` method ensures that each async function runs in its own new event loop, avoiding conflicts with the main thread's …
> Python: Resolve hanging issue in Jupyter notebooks when re-running async functions

- dotnet/samples/KernelSyntaxExamples/Example09_FunctionTypes.cs
In our example named Example09_FunctionTypes there are a few KernelFunction examples that's relying on the special `input` parameter that is no longer supported. This PR fixes the example by specifying a value for the function parameter in the KernelArguments.
> .Net: Fixing issues with functions that take a parameter.

- dotnet/samples/KernelSyntaxExamples/Example72_AgentCollaboration.cs
`Example72_AgentCollaboration.RunAsPluginsAsync()` prefered to execute as a non-terminating loop since the instruction to the art-director emphasized finding a critique as the overall goal (as opposed to approving copy).
- Tuned prompt for art-director agent and verified with multiple runs.
- Added comment to that either example has an off-chance to not reach agreement
- Tracking further improvements: https://github.com/microsoft/semantic-kernel/issues/4313
> Note: `Example72_AgentCollaboration.RunAsPluginsAsync()` tends to be more iterative than `Example72_AgentCollaboration.RunCollaborationAsync()`
> .Net Better repeatability for Agent KernelExample #72 (Example72_AgentCollaboration)

- dotnet/src/Planners/Planners.Handlebars.UnitTests/Handlebars/KernelParameterMetadataExtensionsTests.cs
- dotnet/src/Planners/Planners.Handlebars/Handlebars/Extensions/KernelParameterMetadataExtensions.cs
The handlebars planner converts plugin parameter types to `HandlebarsParameterTypeMetadata` objects by recursively traversing the properties of the type. If the type is itself defined recursively, this causes stack overflow exception. This PR addresses this issue by checking if a given type has already been processed before processing it.
> .Net: Fixing issue that causes a stack overflow in handlebars planner.

- dotnet/src/Extensions/PromptTemplates.Handlebars/Helpers/KernelHelpers/KernelFunctionHelpers.cs
- dotnet/src/Extensions/PromptTemplates.Handlebars/PromptTemplates.Handlebars.csproj
Removed Connectors.OpenAI dependency from PromptTemplates.Handlebars project.
> .Net: Removed Connectors.OpenAI dependency from PromptTemplates.Handlebars project

- dotnet/src/Functions/Functions.UnitTests/OpenApi/RestApiOperationResponseConverterTests.cs
- dotnet/src/Planners/Planners.OpenAI/Planners.OpenAI.csproj
- dotnet/src/Planners/Planners.OpenAI/Stepwise/FunctionCallingStepwisePlanner.cs
- dotnet/src/SemanticKernel.Abstractions/Functions/RestApiOperationResponse.cs
- dotnet/src/SemanticKernel.Abstractions/Functions/RestApiOperationResponseConverter.cs
1. The `RestApiOperationResponse` class and its converter have been moved to the abstraction layer to prevent unnecessary coupling of other projects with the OpenApi one.  
2. The unnecessary coupling to the OpenApi project has been removed from the planners project.
> .Net: Decoupling form OpenApi

- python/semantic_kernel/planning/stepwise_planner/Skills/StepwiseStep/skprompt.txt
When using the `StepwisePlanner` planner along with core skills, for example `TextMemorySkill`, the LLMs tend to plans with function names stripped down to the name without the skill name. This makes the plan fail with an exception like:
`Error invoking action recall: (<ErrorCodes.UnknownError: -1>, "The function 'recall' was not found.", None)`
This error is because the completion returned by the planner prompt does not include the fully structured skill function name. Ex.: instead of returning `_GLOBAL_FUNCTIONS_.recall` it returns `recall` or `GLOBAL_FUNCTIONS.recall`.
This is somehow relates #3237
This change instructs the LLM to keep the skill function name unchanged in its response by adding an example that includes `_` in the name. This approach mimics how the `SequentialPlanner` …
> Python: Prevents LLMs from stripping complex function names

- dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs
- dotnet/src/Connectors/Connectors.OpenAI/OpenAIPromptExecutionSettings.cs
Closes https://github.com/microsoft/semantic-kernel/issues/3540
Closes https://github.com/microsoft/semantic-kernel/issues/3875
I'm not sure what type to use here, so for now I've kept it `object?` and marked it experimental.  If we're ok tying OpenAIPromptExecutionSettings to the Azure SDK, then it'd probably be best to make the property of type `ChatCompletionsResponseFormat?`. Otherwise, if we don't think it'll ever evolve to have more properties, we could make it of type `string?`, or we could add a custom SK type for it. `object?` isn't as user-friendly, but it keeps the doors open to supporting various things.
> .Net: Add OpenAIPromptExecutionSettings.ResponseFormat

- dotnet/samples/KernelSyntaxExamples/Example30_ChatWithPrompts.cs
The file names are incorrect in some comments
Fix names in comments
> .Net: Correct file names in comments

- python/tests/integration/planning/stepwise_planner/test_stepwise_planner.py
The `test_can_execute_stepwise_plan` integration test succeeds sometimes and fails others. Marking it with `xfail` until we can root-cause the issue. It's blocking PRs from completing successfully.
Underlying issue is #4466.
See above.
> Python: Mark flaky test with xfail until we can fix it.

- dotnet/samples/KernelSyntaxExamples/Example09_FunctionTypes.cs
Added KernelFunction attribute to method TaskInjectingCultureInfoOrIFormatProviderWithStringResult
Example09 throws KeyNotFoundException.
> .Net: Fixed KeyNotFoundExeption in Example09.

- dotnet/samples/KernelSyntaxExamples/Example59_OpenAIFunctionCalling.cs
- dotnet/src/Experimental/Agents.UnitTests/Extensions/KernelExtensionTests.cs
- dotnet/src/SemanticKernel.Core/KernelExtensions.cs
- dotnet/src/SemanticKernel.UnitTests/Functions/KernelExtensionsTests.cs
- dotnet/src/SemanticKernel.UnitTests/Functions/KernelFunctionFromPromptTests.cs
- dotnet/src/SemanticKernel.UnitTests/KernelTests.cs
- dotnet/src/SemanticKernel.UnitTests/PromptTemplate/KernelPromptTemplateTests.cs
- dotnet/src/SemanticKernel.UnitTests/TemplateEngine/Blocks/CodeBlockTests.cs
Following the same pattern used by FromType and FromObject
> .Net: Add missing XxFromFunctions members

- dotnet/src/Connectors/Connectors.OpenAI/OpenAIServiceCollectionExtensions.cs
Having an OpenAIClient in DI will become increasingly common with https://github.com/dotnet/aspire/pull/1475.
cc: @sebastienros
> .Net: Allow Add{Azure}OpenAI methods to resolve OpenAIClient from DI

- python/semantic_kernel/connectors/ai/ai_service_client_base.py
- python/semantic_kernel/connectors/ai/ollama/ollama_request_settings.py
- python/semantic_kernel/connectors/ai/ollama/services/ollama_chat_completion.py
- python/semantic_kernel/connectors/ai/ollama/services/ollama_text_completion.py
- python/semantic_kernel/connectors/ai/ollama/services/ollama_text_embedding.py
- python/semantic_kernel/connectors/ai/ollama/utils.py
- python/tests/unit/ai/ollama/services/test_ollama_chat_completion.py
- python/tests/unit/ai/ollama/services/test_ollama_test_completion.py
- python/tests/unit/ai/ollama/services/test_ollama_text_embedding.py
- python/tests/unit/ai/ollama/utils.py
Ollama is a great way to run several smaller models locally, this connector allows that to be used with SK.
Added services and request settings for Ollama.
> Python: added ollama connector

- dotnet/src/IntegrationTests/Fakes/ThrowingEmailPluginFake.cs
- dotnet/src/IntegrationTests/Planners/Stepwise/FunctionCallingStepwisePlannerTests.cs
Fix for failing integration test (resolves #4534)
When using certain OpenAI models such as `gpt-3.5-turbo-1106`, the model would sometimes opt to call `GetEmailAddressAsync` when it wasn't actually needed. This was causing a critical exception to be thrown (which was by design for a different test case, but in this case was being called unexpectedly and causing the test to fail.)
This change modifies the test scenarios to minimize the possibility of a critical exception being thrown by mistake. Now `WriteJokeAsync` throws the critical exception, so the other test cases (that involve writing/emailing poems) should not encounter it.
> .Net: [Fix] .Net: FunctionCallingStepwisePlannerTests.DoesNotThrowWhenPluginFunctionThrowsNonCriticalExceptionAsync is failing

- python/semantic_kernel/connectors/ai/open_ai/models/chat/azure_chat_with_data_response.py
- python/semantic_kernel/connectors/ai/open_ai/utils.py
A recent OYD service deployment changed the schema for the "tool" message containing citations, this cause the OYD response parsing to fail. 
Updated OYD response parser to accept both schemas for citations and pass gracefully on to the assistant message deltas if no tool message can be extracted.
> Python: Fix OYD tool message parsing

- dotnet/src/SemanticKernel.Core/KernelExtensions.cs
KernelExtensions.InvokePromptAsync<T>(...) doesn't include a CancellationToken parameter mistakenly as described in #4573 
Closes #4573 
As @stephentoub mentioned in #4573, adding just a `cancellationToken` causes a _binary breaking change_.
So, this method has two overloads, one with full optional parameters, and a second overload with no optional parameters at all.
> .Net: Add missing CancellationToken to InvokePromptAsync<T>. (#4573)

- dotnet/Directory.Packages.props
- dotnet/samples/KernelSyntaxExamples/Example08_RetryHandler.cs
- dotnet/samples/KernelSyntaxExamples/KernelSyntaxExamples.csproj
Removing Polly as it's no longer used and will nevertheless need to be updated by dependabot e.g. https://github.com/microsoft/semantic-kernel/pull/4614.
> .Net: Remove Polly as a dependency

- python/semantic_kernel/planning/plan.py
This PR fixes #4658 and fixes #2933.
The first one basically needed a None check before using `self._function` in the `Plan.describe` method.
The second one was incorrectly setting the values for variables for the next step in the plan. The solution for this was suggested by @amritpal-singh-98, thank you!
> Python: Fixes `Plan` using an empty function in describe and incorrectly setting context variables for next steps.

- dotnet/src/SemanticKernel.Abstractions/Events/CancelKernelEventArgs.cs
Closes #4650
Replace [Experimental("SKEXP0003")] by [Experimental("SKEXP0004")] above CancelKernelEventArgs type, to follow [documentation](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/docs/EXPERIMENTS.md)
> .Net: CancelKernelEventArgs is marked with SKEXP0003 Experimental Attribute instead of SKEXP0004

- python/semantic_kernel/connectors/ai/open_ai/exceptions/content_filter_ai_exception.py
- python/tests/unit/ai/open_ai/services/test_azure_chat_completion.py
When the RAI response doesn't contain a `code` the class `ContentFilterAIException` would fail to initialize because it was setting `""` as content_filter_code. This sets `"ResponsibleAIPolicyViolation"` instead in that case.
Fixes #4709
> Python: Sets a valid default content filter code to ResponsibleAIPolicyViolation

- dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs
- dotnet/src/Connectors/Connectors.OpenAI/OpenAIPromptExecutionSettings.cs
**Expected behavior**
Gen-AI app developers should be able to populate the user field per request.
This is important to support multi-user applications e.g. a Copilot or Bot that is hosted as a service and used by multiple users that log-in and interact with it. SK [Chat-Copilot](https://github.com/microsoft/chat-copilot) is a good example for that.
**Screenshots**
https://github.com/microsoft/semantic-kernel/blob/f959256229c7d0d821d1df5c8b112ced10ddd5ac/dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs#L717
https://github.com/microsoft/semantic-kernel/blob/f959256229c7d0d821d1df5c8b112ced10ddd5ac/dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs#L751
> .Net: Pass user field in SK C#

- python/semantic_kernel/connectors/ai/open_ai/request_settings/open_ai_request_settings.py
- python/semantic_kernel/connectors/ai/open_ai/semantic_functions/open_ai_chat_prompt_template.py
- python/semantic_kernel/semantic_functions/chat_prompt_template.py
- python/tests/unit/ai/open_ai/test_openai_request_settings.py
- python/tests/unit/plugin_definition/test_prompt_templates.py
Fixes #4711 and #4705 and addresses some inconsistencies in the way the chat_prompt_template is created, now has more control.
Added parse flags to chatPromptTemplate to allow the user to control is something is loaded into messages or not.
Added better docstrings and tests for this as well.
> Python: updates to chat_prompt and related

- dotnet/src/Connectors/Connectors.GoogleVertexAI.UnitTests/Core/Gemini/Common/GeminiClientChatGenerationTests.cs
- dotnet/src/Connectors/Connectors.GoogleVertexAI.UnitTests/Core/Gemini/Common/GeminiClientChatStreamingTests.cs
- dotnet/src/Connectors/Connectors.GoogleVertexAI/Core/Gemini/Common/GeminiChatCompletionClient.cs
~~Gemini chat client could handle only one system message. Exception was thrown if there were more than one system message.~~
Lacks of some tests, and ref to chathistory param.
~~Fixes handling multiple system messages. Added revelant unit tests.~~
Refactoring and new unit tests.
> .Net Gemini refactor chat system messages handling

- python/semantic_kernel/kernel.py
- python/tests/unit/planning/sequential_planner/test_sequential_planner.py
- python/tests/unit/planning/stepwise_planner/test_stepwise_planner_parse_result.py
Completes work item: #4846. The Kernel class was not following the Pydantic convention.
This PR updates the Kernel class to use the KernelBaseModel and Pydantic fields. All unit and integration tests passing.
> Python: Make the Kernel class Pydantic.

- dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs
Closes [#4719](https://github.com/microsoft/semantic-kernel/issues/4719)
**Issue**
- When setting the `execution_settings` from YAML or `config.txt`, the `response_format` field is not recognized, and thus the JSON mode cannot be activated.
**Root Cause**
- The issue arises because the `ResponseFormat` property, which is of type `object?`, stores values as `JsonElement` types when read from the aforementioned files.
- The `CreateChatCompletionOptions` method does not account for this and performs type checking directly against types such as `string`, leading to improper conditional branching.
- As a result, the `ChatCompletionsOptions`'s `ResponseFormat` value remains unassigned, preventing the activation of JSON mode.
This PR addresses the problem by adjusting the type checks to properly …
> .Net: Fix bug to allow activation of JSON mode through execution_settings

- python/semantic_kernel/kernel.py
- python/tests/unit/kernel_extensions/test_import_plugins.py
Fixes #4869. On a created semantic function, the plugins weren't getting set for use for the function.
Set the default plugins for the registered function, and add a unit test.
> Python: Set the default plugins on the semantic function. Add a unit test.

- dotnet/samples/KernelSyntaxExamples/Example75_AgentTools.cs
- dotnet/src/Experimental/Agents/Internal/ChatRun.cs
- dotnet/src/Experimental/Agents/Internal/ChatThread.cs
Observed agent messages not being provided in the expected order.  In practice they appear reversed, but could be anything depending on JSON data.
Changed run processing to return message-ids as `IAsyncEnumerable`, in the order they are generated.
In addition to addressing ordering issue, this also introduces the ability for the first message to be displayed as soon as it is produced (for multi-message runs)...even if the last message is added 30 seconds later.  (In the current version, message-ids are return only after all have been produced.)
Also explored both flavors of `Example75_AgentTools` as separate entry-points.
> .Net - Fix Agent Message Ordering for Multimessage Runs

- SECURITY.md
There were broken links in the `SECURITY.md` markdown file that returned 301s.  
This PR updates the links with the new, redirected/valid links.
> Fix broken links

- python/semantic_kernel/orchestration/kernel_function.py
Issue was raised that streaming when using chat but not a chat_prompt_template failed because it did not return after doing the branch for non-chat-prompt-template, this fixes that.
Fixes #4925
> Python: streaming fix for Python: SK 0.5.0 breaks streaming #4925

- .github/workflows/markdown-link-check-config.json
Reverting commit 70ac836339b09d972aef691b86b138883c092f38 that skipped the link check for all links starting from "https://www.microsoft.com/en-us/msrc/" since the issue has resolved itself, and the configuration is no longer necessary.
> Revert "Failed links are temporarily excluded from the link-checking action"

- python/semantic_kernel/connectors/openapi/kernel_openapi.py
- python/semantic_kernel/core_plugins/conversation_summary_plugin.py
- python/semantic_kernel/core_plugins/http_plugin.py
- python/semantic_kernel/planners/action_planner/action_planner.py
- python/tests/unit/functions/test_native_function.py
Some of the Annotated imports were not using typing_extention for py3.8
> Python: fix annotated missing sys.version

- dotnet/src/Plugins/Plugins.MsGraph/Connectors/CredentialManagers/LocalUserMSALCredentialManager.cs
- fixes #4962
Observed this while introducing API Manifest based plugins. The change allows logging in with both personal and work/school accounts.
> .Net: Support work and school accounts for Microsoft Graph Connector

- dotnet/src/Connectors/Connectors.GoogleVertexAI.UnitTests/Core/Gemini/GeminiPartTests.cs
- dotnet/src/Connectors/Connectors.GoogleVertexAI.UnitTests/Core/Gemini/GeminiRequestTests.cs
- dotnet/src/Connectors/Connectors.GoogleVertexAI/Core/Gemini/GeminiPart.cs
- dotnet/src/Connectors/Connectors.GoogleVertexAI/Core/Gemini/GeminiRequest.cs
This PR introduces limited support for ImageContent. At present, the support extends to only Uri files and is only available in VertexAI. The associated unit tests have been updated to reflect these changes.
@RogerBarreto
> .Net Added support for gemini-vision

- java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIChatCompletion.java
- java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example07_BingAndGooglePlugins.java
- java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example09_FunctionTypes.java
- java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example42_KernelBuilder.java
- java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example69_MutableKernelPlugin.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/Kernel.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/KernelPluginCollection.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionFromPrompt.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/templateengine/handlebars/HandlebarsPromptTemplate.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/templateengine/semantickernel/blocks/CodeBlock.java
Simplify the API
Use KernelFunctionCollection internally from Kernel. Add a couple of methods to Kernel to add/get a KernelPlugin
> Java: Remove KernelFunctionCollection from public API

- dotnet/src/Connectors/Connectors.GoogleVertexAI.UnitTests/Core/Gemini/Common/GeminiClientChatGenerationTests.cs
- dotnet/src/Connectors/Connectors.GoogleVertexAI/Core/Gemini/Common/GeminiChatCompletionClient.cs
Updated the exception types thrown by the GeminiChatCompletionClient and its corresponding unit tests. KernelException was replaced with InvalidOperationException.
@RogerBarreto
> .Net Gemini - Adjusted exceptions to comply with ADR

- dotnet/src/SemanticKernel.Abstractions/Functions/KernelJsonSchema.cs
-fixes #4991
- Sets the serialization depth to 128
- Changes can be tested on the branch linked in the issue description.
> .Net: Sets serialization depth to 128

- dotnet/src/Connectors/Connectors.UnitTests/OpenAI/ChatCompletion/AzureOpenAIChatCompletionServiceTests.cs
- dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAICompletionTests.cs
- dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatCompletionServiceExtensions.cs
- dotnet/src/SemanticKernel.UnitTests/Functions/KernelFunctionFromPromptTests.cs
Resolves: https://github.com/microsoft/semantic-kernel/issues/4377
Resolves: https://github.com/microsoft/semantic-kernel/issues/4510
When invoking prompt or function from kernel, chat system prompt is ignored, and prompt is sent to AI as system message instead of user message.
The example of code that didn't work:
```csharp
var settings = new OpenAIPromptExecutionSettings { ChatSystemPrompt = "Reply \"I don't know\" to every question." };
// Result contains the right answer instead of "I don't know", as it was defined in system prompt.
// That's because the question was set to system message instead of user message and ChatSystemPrompt property was ignored.
var result = await target.InvokePromptAsync("Where is the most famous fish market in Seattle, Washington, USA?", new(settings));
``` …
> .Net: Fixed usage of chat system prompt

- dotnet/src/Connectors/Connectors.OpenAI/AudioToText/OpenAIAudioToTextExecutionSettings.cs
- dotnet/src/Connectors/Connectors.OpenAI/TextToAudio/OpenAITextToAudioExecutionSettings.cs
- dotnet/src/Connectors/Connectors.UnitTests/OpenAI/AudioToText/AzureOpenAIAudioToTextServiceTests.cs
- dotnet/src/Connectors/Connectors.UnitTests/OpenAI/AudioToText/OpenAIAudioToTextExecutionSettingsTests.cs
- dotnet/src/Connectors/Connectors.UnitTests/OpenAI/TextToAudio/AzureOpenAITextToAudioServiceTests.cs
- dotnet/src/Connectors/Connectors.UnitTests/OpenAI/TextToAudio/OpenAITextToAudioExecutionSettingsTests.cs
- dotnet/src/Connectors/Connectors.UnitTests/OpenAI/TextToAudio/OpenAITextToAudioServiceTests.cs
- dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAITextToAudioTests.cs
Current audio interfaces have optional execution settings parameters in order to be able to use audio API through Kernel in the future, where execution settings are optional. But when using audio services directly, this is not user friendly, because when optional execution settings are not configured, services will throw an error. 
In case of text-to-audio service, required field is voice. This PR sets default value to `alloy` with the ability to overwrite.
For audio-to-text service, required field is filename. This PR sets default value to `file.mp3` with the ability to overwrite. 
With these changes execution settings are no longer required (they are optional) for text-to-audio and audio-to-text conversion.
> .Net: Improved Audio API by adding default setting values

- python/semantic_kernel/connectors/ai/open_ai/services/open_ai_text_completion_base.py
1. Why is this change required?
An error has occurred. This is the same issue as the following: Azure OpenAI API may not include logprobs.
The recent change only modified OpenAIChatCompletionBase. However, it turns out that this issue also occurs with OpenAITextCompletionBase. Therefore, I propose to make a similar fix.
https://github.com/microsoft/semantic-kernel/issues/4923
2. What problem does it solve?
Non-existent property lobprobs is referenced when using Azure OpenAI Text Completion.
3. What scenario does it contribute to?
When using Azure OpenAI TextCompletion
4. If it fixes an open issue, please link to the issue here.
https://github.com/microsoft/semantic-kernel/issues/5070
Azure OpenAI ChatCompletion does not return logprobs.(It seems that there are cases where it is returned, …
> Python: Support for cases where "logprobs" does not exist（OpenAITextCompletionBase）

- python/semantic_kernel/connectors/ai/open_ai/utils.py
- python/semantic_kernel/events/function_invoked_event_args.py
- python/semantic_kernel/events/function_invoking_event_args.py
- python/semantic_kernel/events/kernel_events_args.py
- python/semantic_kernel/planners/action_planner/action_planner.py
- python/semantic_kernel/planners/sequential_planner/sequential_planner_extensions.py
- python/semantic_kernel/planners/sequential_planner/sequential_planner_parser.py
- python/tests/unit/planners/sequential_planner/test_sequential_planner_extensions.py
After closing the large feature branch (#5077) there were a few leftover names that need to be updated to remove things like "FunctionView" (replaced with KernelFunctionMetadata). 
Updates are:
- Rename a few classes, methods and docstrings to remove references to FunctionView. Closes #4628
> Python: Remove the left over naming related to FunctionView

- dotnet/samples/KernelSyntaxExamples/Example82_OllamaTextEmbeddingGeneration.cs
- dotnet/src/Connectors/Connectors.Ollama/Core/IEndpointProvider.cs
- dotnet/src/Connectors/Connectors.Ollama/Core/IOllamaClient.cs
- dotnet/src/Connectors/Connectors.Ollama/Core/OllamaClient.cs
- dotnet/src/Connectors/Connectors.Ollama/Core/OllamaEmbeddingRequest.cs
- dotnet/src/Connectors/Connectors.Ollama/Core/OllamaEmbeddingResponse.cs
- dotnet/src/Connectors/Connectors.Ollama/Core/OllamaEndpointProvider.cs
- dotnet/src/Connectors/Connectors.Ollama/Extensions/OllamaServiceExtensions.cs
- dotnet/src/Connectors/Connectors.Ollama/TextEmbedding/OllamaTextEmbeddingGenerationService.cs
This PR adds Ollama text embedding support
Referenced existing implementation of OllamaTextGeneration service and OpenAITextEmbeddingGenerationService for implementation. I have also added a sample (Example82_OllamaTextEmbeddingGenerationService), Tested locally against ollama llama2:7b
- Examples may need to be re-numbered as 80, 81, 82 already exist in master
- I wasn't able to run all tests as I don't have OpenAI access
> .Net: Ollama connector text embedding support

- python/tests/unit/functions/test_kernel_function_from_prompt.py
adds a test to demonstrate multiple settings for a single prompt, should be tested for yaml based functions as well, closes #4552
> Python: test added for multiple settings in one prompt function

- java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIChatCompletion.java
- java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/textcompletion/OpenAITextGenerationService.java
- java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example06_TemplateLanguage.java
- java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example07_BingAndGooglePlugins.java
- java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example10_DescribeAllPluginsAndFunctions.java
- java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example13_ConversationSummaryPlugin.java
- java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example30_ChatWithPrompts.java
- java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example42_KernelBuilder.java
- java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example56_TemplateMethodFunctionsWithMultipleArguments.java
- java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example59_OpenAIFunctionCalling.java
- java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example60_AdvancedMethodFunctions.java
- java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example69_MutableKernelPlugin.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/Kernel.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/hooks/FunctionInvokedEvent.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/hooks/FunctionInvokingEvent.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/hooks/PromptRenderedEvent.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/hooks/PromptRenderingEvent.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/implementation/templateengine/tokenizer/blocks/CodeBlock.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/FunctionInvocation.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/orchestration/InvocationContext.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunction.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionArguments.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionFromMethod.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/KernelFunctionFromPrompt.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/semanticfunctions/PromptTemplateConfig.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/templateengine/handlebars/HandlebarsPromptTemplate.java
- Make constructors on classes that have builders protected
- Remove the addPlugin function from the kernel to make plugin set immutable, in favour of adding a copy method for creating a clone of a kernel that can have plugins added, i.e:
```
kernel = kernel.copy()
.withPlugin(timePlugin)
.build()
```
- Add sync invocation methods in addition to async
- Add warning if `FunctionInvocation` is used in an unusual manner that might indicate a bug
> Java: Implement a number of fixes from API review

- python/poetry.lock
- python/pyproject.toml
- python/semantic_kernel/connectors/ai/open_ai/contents/open_ai_chat_message_content.py
- python/semantic_kernel/contents/chat_history.py
- python/semantic_kernel/contents/chat_message_content.py
- python/semantic_kernel/planners/sequential_planner/sequential_planner_parser.py
Add defusedxml package
Change imports of ElementTree to use defusedxml, other parts of stdlib xml can still be used.
closes #4754
> Python: updated relevant parts from xml to defusedxml

- dotnet/src/Experimental/Agents/Extensions/OpenAIRestExtensions.cs
- Agent requests not containing `User-Agent` header.
- Short-circuit not present
Add `User-Agent` header and short-circuit.
> .Net - Fix Agent HTTP Request Header

- python/semantic_kernel/connectors/ai/open_ai/utils.py
- python/semantic_kernel/functions/kernel_function_decorator.py
- python/semantic_kernel/functions/kernel_function_from_method.py
- python/semantic_kernel/functions/kernel_function_from_prompt.py
- python/semantic_kernel/functions/kernel_parameter_metadata.py
- python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py
- python/semantic_kernel/prompt_template/input_variable.py
- python/semantic_kernel/prompt_template/prompt_template_config.py
- python/tests/unit/functions/test_kernel_function_decorators.py
- python/tests/unit/functions/test_kernel_function_from_method.py
- python/tests/unit/functions/test_kernel_parameter_metadata.py
- python/tests/unit/prompt_template/test_prompt_templates.py
- python/tests/unit/test_serialization.py
Added support for complex types (classes) for KernelFunctionFromMethod.
Implements #4635 
This PR adds a field to the KernelParameterMetadata class for type_object
When that field is filled and supplied by a KernelFunctionFromMethod decorator, it is used during invoke to cast the type.
It checks if it is a pydantic type and calls `model_validate_json` in that case, otherwise invokes it directly as a init (like with a str), this then also casts strs to ints for example.
> Python: Complex Type support for Method functions

- dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromPrompt.cs
> .Net:  Added ConfigureAwait(false) to asyncReference in InvokeStreamingCoreAsync

- dotnet/src/Connectors/Connectors.GoogleVertexAI.UnitTests/Core/Gemini/GeminiStreamResponseTests.cs
This commit includes the file GeminiStreamResponseTests.cs which tests the serialization and parsing functionalities of the GeminiResponse object using the GeminiStreamJsonParser. This ensures that all properties are populated correctly when serialized.
@RogerBarreto
> .Net: Gemini - Add GeminiStreamResponse unit test

- python/notebooks/00-getting-started.ipynb
- python/notebooks/01-basic-loading-the-kernel.ipynb
- python/notebooks/02-running-prompts-from-file.ipynb
- python/notebooks/03-prompt-function-inline.ipynb
- python/notebooks/04-kernel-arguments-chat.ipynb
- python/notebooks/05-using-the-planner.ipynb
- python/notebooks/06-memory-and-embeddings.ipynb
- python/notebooks/07-hugging-face-for-plugins.ipynb
- python/notebooks/08-native-function-inline.ipynb
- python/notebooks/09-groundedness-checking.ipynb
- python/notebooks/10-multiple-results-per-prompt.ipynb
- python/notebooks/11-streaming-completions.ipynb
- python/pyproject.toml
In preperation for a Python SDK beta release, bumping the pyproject.toml version to 0.9.0.beta1.
In preperation for a Python SDK beta release, bumping the pyproject.toml version to 0.9.0.beta1.
> Python: Bump pyproject.toml to 0.9.0.beta1 for beta release. Match notebooks.

- dotnet/src/Experimental/Agents/AgentBuilder.cs
.Net: [Agent] Fixed an issue with retrieving an existing OpenAI assistant given its ID, leading to creation of a duplicate assistant.
Upon retrieving an existing assistant, instantiate the Agent instance using the assistant details fetched from OpenAI REST API call.
> .Net: [Agent] Fixed an issue with retrieving an existing OpenAI assistant given its ID, leading to creation of a duplicate assistant.

- python/.coveragerc
- python/semantic_kernel/connectors/telemetry.py
Updates the name of the app info key to Semantic-Kernel-Version to match dotnet, closes #5038
> Python: updated telemetry key names

- .vscode/settings.json
- python/samples/kernel-syntax-examples/rag_with_text_memory_plugin.py
- python/semantic_kernel/kernel.py
- python/tests/unit/kernel/test_prompt_create_methods.py
The kernel.invoke_prompt was missing the function name and plugin name args and was failing.
This PR:
- Adds the required arguments. Closes #5313 
- Adds unit tests.
> Python: Add function name and plugin name to invoke prompt. Add unit tests.

- python/tests/unit/connectors/hugging_face/test_hf_local_text_completions.py
The Hugging Face tests sometimes failed, this combines the streaming and non-streaming tests, loading the model once, instead of twice.
> Python: combined stream and non-stream HF tests

- dotnet/src/Connectors/Connectors.GoogleVertexAI/Core/GoogleAI/GoogleAIEndpointProvider.cs
- dotnet/src/Connectors/Connectors.GoogleVertexAI/Core/VertexAI/VertexAIEndpointProvider.cs
The stream text generation endpoint in GoogleAIEndpointProvider and VertexAIEndpointProvider has been updated. The stream generation URL now includes the additional parameter 'alt=sse'. This ensures correct data formatting for Server-Sent Events.
@RogerBarreto 
#4680
> .Net Gemini enable SSE

- dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs
A KernelFunction can change when plug-ins are in the Kernel. Today, we build up the list of tools at the beginning of the auto-invocation loop but then don't update the list after a function has been invoked, which means those updates won't be reflected in subsequent calls made as part of the response to the LLM.  This PR updates the loop to regenerate the tool call information after each function invocation, in case they've been changed dynamically.
Fixes https://github.com/microsoft/semantic-kernel/issues/4785
> .Net: Respect Kernel plugin changes made during function auto-invocation

- dotnet/samples/KernelSyntaxExamples/Example18_DallE.cs
- dotnet/samples/KernelSyntaxExamples/README.md
- dotnet/src/Connectors/Connectors.OpenAI/TextToImage/AzureOpenAITextToImageService.cs
Small fix to use the correct configuration for the deployment name in the DALL-E example.
> .Net: Fix for DALL-E endpoint name in examples

- .github/workflows/close-inactive-issues.yml
> Add GH workflow to mark as stale and then close inactive issues

- python/semantic_kernel/prompt_template/__init__.py
adds a __init__ file to the prompt_template folder which exposes the most important classes from the files.
fixes #5172
> Python: add missing init from prompt_template folder

- dotnet/samples/KernelSyntaxExamples/Example14_SemanticMemory.cs
- dotnet/src/Connectors/Connectors.GoogleVertexAI.UnitTests/Extensions/GoogleAIMemoryBuilderExtensionsTests.cs
- dotnet/src/Connectors/Connectors.GoogleVertexAI.UnitTests/Extensions/VertexAIMemoryBuilderExtensionsTests.cs
- dotnet/src/Connectors/Connectors.GoogleVertexAI/Extensions/GoogleAIMemoryBuilderExtensions.cs
- dotnet/src/Connectors/Connectors.GoogleVertexAI/Extensions/VertexAIMemoryBuilderExtensions.cs
Memory builder extensions.
@RogerBarreto
> .Net: GoogleVertexAI - memory builder

- dotnet/Directory.Packages.props
Downgrading version of JsonSchema.Net.Generation package to resolve dependency conflict with dotnet-interactive.
We recently upgraded the version of JsonSchema.Net.Generation from major version 3 to 4 and this has caused a collision with dotnet-interactive which ships with JsonSchema.Net version 5.0.0. The PR drops the major version back down to resolve this dependency collision.
> .Net: Downgrading version of JsonSchema.Net.Generation package to resolve dependency conflict

- python/notebooks/05-using-the-planner.ipynb
- python/semantic_kernel/kernel.py
- python/semantic_kernel/planners/basic_planner.py
- python/semantic_kernel/planners/plan.py
- python/semantic_kernel/planners/sequential_planner/sequential_planner.py
- python/semantic_kernel/planners/sequential_planner/sequential_planner_parser.py
- python/semantic_kernel/planners/stepwise_planner/Plugins/StepwiseStep/skprompt.txt
- python/semantic_kernel/planners/stepwise_planner/__init__.py
- python/semantic_kernel/planners/stepwise_planner/stepwise_planner.py
- python/tests/integration/planning/sequential_planner/test_sequential_plan_parser.py
- python/tests/unit/planners/sequential_planner/test_sequential_planner.py
- python/tests/unit/planners/sequential_planner/test_sequential_planner_parser.py
- samples/plugins/WriterPlugin/Brainstorm/skprompt.txt
Based on #5474 went into the `using-the-planner` notebook and made sure it works with the latest code.
Moved all the planners to use '-' in line with the current work on new templates and planners, once that is in several extension classes can be changed.
Encountered several small bugs left over from changes over the last months.
Got through the whole notebook with results.
> Python: planner love

- dotnet/samples/KernelSyntaxExamples/Example72_AgentCollaboration.cs
- dotnet/samples/KernelSyntaxExamples/KernelSyntaxExamples.csproj
- dotnet/src/Experimental/Agents/IChatMessage.cs
- dotnet/src/Experimental/Agents/Internal/Agent.cs
Noticed that agent examples failing due to resourcing and configuration delta.  As part of this discovered agent as plugin regression from community contribution.
- Include agent templates as embedded resources
- Switch from `TestConfiguration.AzureOpenAI.DeploymentName` to `TestConfiguration.AzureOpenAI.ChatDeploymentName` in `Example72_AgentCollaboration`
- Remove `fileIds` from `Agent.AskAsync` (not utilized and resulting in failed run creation) - https://github.com/microsoft/semantic-kernel/pull/5110
- Eliminated user-message duplication
- Added comments to `ChatMessageType`
> .Net - Fix agent function invocation and examples

- dotnet/src/Connectors/Connectors.GoogleVertexAI/Extensions/GeminiKernelFunctionMetadataExtensions.cs
- dotnet/src/Connectors/Connectors.GoogleVertexAI/Extensions/GeminiPluginCollectionExtensions.cs
The namespace has been updated in the GeminiKernelFunctionMetadataExtensions.cs and GeminiPluginCollectionExtensions.cs files. The namespace was amended from 'Microsoft.SemanticKernel' to 'Microsoft.SemanticKernel.Connectors.GoogleVertexAI'..
> .Net: Update namespace in Gemini connector files

- dotnet/src/Connectors/Connectors.GoogleVertexAI.UnitTests/Extensions/GeminiPluginCollectionExtensionsTests.cs
Changed the assertion methods used in GeminiPluginCollectionExtensionsTests. Instead of checking if the functions are the same, the test now asserts that the actual function is not null and that its name is equal to the expected function's name. This change makes the tests pass after cloning function was introduced to kernel.
> .Net: Update test assertions in GeminiPluginCollectionExtensionsTests

- dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs
Fixes https://github.com/microsoft/semantic-kernel/issues/5310
> .Net: Disable Azure SDK network timeout when a custom HttpClient is supplied

- python/.conf/.pre-commit-config.yaml
- python/samples/kernel-syntax-examples/chat_gpt_api.py
> Python: updated openai chat sample

- python/tests/unit/prompt_template/test_handlebars_prompt_template.py
> Python: add additional handlebars test, to make sure built-in helpers run

- python/notebooks/05-using-the-planner.ipynb
Link was expired in the jupiter notebook
Path was changed from planning to planners and the link was not updated.
https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/**planning**/sequential_planner/Plugins/SequentialPlanning/skprompt.txt
https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/**planners**/sequential_planner/Plugins/SequentialPlanning/skprompt.txt
> Python: fixed the broken link

- python/semantic_kernel/prompt_template/utils/handlebars_system_helpers.py
- python/semantic_kernel/prompt_template/utils/jinja2_system_helpers.py
- python/tests/unit/prompt_template/test_handlebars_prompt_template.py
- python/tests/unit/prompt_template/test_jinja2_prompt_template.py
Jinja2 has a lot of built-in global functions, filters, and test methods. There's no need to have the overlap between those built-ins and the custom helpers we had defined.
This PR:
- Removes the overlap custom methods we had added so that one can use the built-in jinja2 filters, tests, and others.
- Add some unit tests to exercise those built-ins, mainly to show how they can be used.
- Introduces a `messages` custom helper function for handlebars and jinja2 which pretty prints the current chat_history.
> Python: Remove jinja2 built in helpers from custom helpers. Introduce messages custom func helper.

- java/api-test/integration-tests/src/test/java/com/microsoft/semantickernel/tests/ImportingMultiplePluginsTest.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/KernelPluginCollection.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/plugin/KernelPluginFactory.java
> Java: Fix importing multiple plugin functions

- dotnet/src/Functions/Functions.OpenApi/Extensions/RestApiOperationResponseExtensions.cs
- dotnet/src/Functions/Functions.UnitTests/OpenApi/RestApiOperationResponseTests.cs
Fix issue opened here https://github.com/microsoft/semantic-kernel/issues/5636
Change strict string comparison to `BeginsWith` check.
> .Net: Broaden Response ContentType Checking Logic

- dotnet/samples/KernelSyntaxExamples/Example70_Agents.cs
- dotnet/src/Experimental/Agents/Internal/Agent.cs
- dotnet/src/IntegrationTests/Connectors/Memory/Milvus/MilvusFixture.cs
Azure Open AI version of semantic kernel always creating OpenAIChatCompletionService internally.  This only affects the use of prompt-functions as plug-ins, not broader agent behavior.
- Create AzureOpenAIChatCompletion service based on context definition.
- Updated prompt-funciton agent test to run in AOAI mode
- Verified test execution
> .Net - Fixed creation of Kernel for Azure Open AI case.

- python/samples/kernel-syntax-examples/rag_with_text_memory_plugin.py
- python/semantic_kernel/memory/semantic_text_memory.py
- python/semantic_kernel/services/ai_service_selector.py
I noticed that when running a piece without any execution settings, it errored out, while it should use 'default' service with the default settings for that service, that is now fixed. 
Small updates to the rag example.
Added TODO: to replace the embedding_generator service in SemanticTextMemory with Kernel and the same service_selector pattern as for KernelFunctions.
> Python: small fix for running prompt without any execution settings

- dotnet/src/Connectors/Connectors.MistralAI.UnitTests/Client/MistralClientTests.cs
- dotnet/src/Connectors/Connectors.MistralAI.UnitTests/Connectors.MistralAI.UnitTests.csproj
- dotnet/src/Connectors/Connectors.MistralAI.UnitTests/TestData/function_call_response.json
- dotnet/src/Connectors/Connectors.MistralAI/AssemblyInfo.cs
- dotnet/src/Connectors/Connectors.MistralAI/Client/ChatCompletionRequest.cs
- dotnet/src/Connectors/Connectors.MistralAI/Client/MistralChatChoice.cs
- dotnet/src/Connectors/Connectors.MistralAI/Client/MistralChatMessage.cs
- dotnet/src/Connectors/Connectors.MistralAI/Client/MistralClient.cs
- dotnet/src/Connectors/Connectors.MistralAI/Client/MistralFunction.cs
- dotnet/src/Connectors/Connectors.MistralAI/Client/MistralParameters.cs
- dotnet/src/Connectors/Connectors.MistralAI/Client/MistralPropertyType.cs
- dotnet/src/Connectors/Connectors.MistralAI/Client/MistralTool.cs
- dotnet/src/Connectors/Connectors.MistralAI/Client/MistralToolCall.cs
- dotnet/src/Connectors/Connectors.MistralAI/Connectors.MistralAI.csproj
- dotnet/src/Connectors/Connectors.MistralAI/Extensions/MistralAIPluginCollectionExtensions.cs
- dotnet/src/Connectors/Connectors.MistralAI/MistralAIPromptExecutionSettings.cs
- dotnet/src/Connectors/Connectors.MistralAI/MistralAIToolCallBehavior.cs
- dotnet/src/IntegrationTests/Connectors/MistralAI/ChatCompletion/MistralAIChatCompletionTests.cs
Adds support for function calling for non-streaming chat completion requests only.
> .Net: MistralAI Function calling for chat completion requests

- python/semantic_kernel/connectors/ai/open_ai/contents/open_ai_chat_message_content.py
- python/semantic_kernel/contents/chat_history.py
- python/tests/unit/contents/test_chat_history.py
Noticed a small issue when ChatHistory is created with different types of messages, and then serialized.
This fixed that and adds a test for that case.
> Python: small fix for CH serialization

- python/semantic_kernel/events/function_invoked_event_args.py
This is a single-line fix to a Python docstring to get it to conform to Sphinx standards and convention used [elsewhere](https://github.com/microsoft/semantic-kernel/blob/290f44d593daa21f5a4f88eb5bb4e49468ebb608/python/semantic_kernel/planners/plan.py#L137) in the project.
(My team owns the reference docs generation process for this and other libraries. We forced a build the other day from our side for test purposes and noticed it stumbled over this line. Feel free to ping me if any questions.)
See changes, it's a one-liner :grin:
I ashamedly admit I have done *none* of the below; hopefully this is a gimme, apologies if it creates noise.
> Python: Small docstring fix

- python/samples/kernel-syntax-examples/openapi_example/openapi_client.py
Add missing await to openapi client
Add missing await to openapi client
> Python: Add missing await to openapi client

- python/semantic_kernel/functions/kernel_function_decorator.py
- python/tests/unit/functions/test_kernel_function_decorators.py
Small change to allow a kernel function decorator without name and description, to be defined without brackets.
> Python: updated decorator to allow no brackets

- .github/workflows/dotnet-build-and-test.yml
- .github/workflows/dotnet-ci.yml
- .github/workflows/dotnet-format.yml
- .github/workflows/dotnet-integration-tests.yml
- dotnet/src/SemanticKernel.Abstractions/Kernel.cs
This is about which SDK is used, not which target framework is used. .NET 7 is EOL in May. .NET 6 is EOL in Nov.
> .Net: Focus CI on .NET 8 SDK

- dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromMethod.cs
- dotnet/src/SemanticKernel.UnitTests/Functions/KernelFunctionFromMethodTests1.cs
Fixes https://github.com/microsoft/semantic-kernel/issues/5587
Easiest to review with whitespace disabled: https://github.com/microsoft/semantic-kernel/pull/5821/files?w=1
> .Net: Fix handling of generic return types in CreateFromMethod

- python/samples/kernel-syntax-examples/openai_function_calling_stepwise_planner.py
- python/semantic_kernel/planners/function_calling_stepwise_planner/function_calling_stepwise_planner.py
- python/tests/unit/planners/function_calling_stepwise_planner/test_unit_function_calling_stepwise_planner.py
A recent feature was added to dotnet to allow for a chat_history object to be passed into invoke. This only allows the user to affect the `chatHistoryForSteps`, but doesn't account for generating a plan with provided context (via the chat history). 
This PR allows the user to pass in optional kernel arguments or kwargs (that get turned into kernel arguments). If the user then overrides the prompt template/step prompt.txt, they can utilize any new arguments that are supplied. 
- Closes #5824
> Python: Allow args to pass to func calling stepwise planner

- dotnet/src/Agents/Abstractions/AgentChannel.cs
- dotnet/src/Agents/Abstractions/ChatHistoryChannel.cs
- dotnet/src/Agents/Abstractions/Internal/BroadcastQueue.cs
- dotnet/src/Agents/UnitTests/AgentChannelTests.cs
- dotnet/src/Agents/UnitTests/Internal/BroadcastQueueTests.cs
`IEnumerable` can be cumbersome if not required.  Identified a usage that is improved by `IReadOnlyList` (as the usage of `IEnumerable` was extraneous.)
Been on the look-out for tuning these signatures...this one slipped through.
> .Net - Agents IReadonlyList instead of IEnumerable (Step #ANY)

- dotnet/samples/KernelSyntaxExamples/Example70_Agents.cs
- dotnet/samples/KernelSyntaxExamples/Plugins/MenuPlugin.cs
- dotnet/src/Experimental/Agents/Internal/ChatRun.cs
Simply code and eliminate assumption causing side-effects.
Updating to work well with the complex type support that exists in KernelFunction
> .Net - Fix Experimental Agent Type Handling for Tool Calling

- python/semantic_kernel/connectors/ai/embeddings/embedding_generator_base.py
- python/semantic_kernel/connectors/ai/google_palm/services/gp_text_embedding.py
- python/semantic_kernel/connectors/ai/hugging_face/services/hf_text_embedding.py
- python/semantic_kernel/connectors/ai/ollama/services/ollama_text_embedding.py
- python/semantic_kernel/core_plugins/text_memory_plugin.py
- python/semantic_kernel/memory/semantic_text_memory.py
- python/semantic_kernel/memory/semantic_text_memory_base.py
Added kwargs handling throughout embeddings connectors and as a additional field for the TextMemoryPlugin.
> Python: added kwargs to embedding and text memory

- dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoDBMemoryStore.cs
- dotnet/src/Connectors/Connectors.UnitTests/Memory/MongoDB/MongoDBMemoryStoreTests.cs
> .Net: Fix ignoring non-default search index name

- java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIChatCompletion.java
- java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example59_OpenAIFunctionCalling.java
Make Example59_OpenAIFunctionCalling mirror .NET as much as possible. Want parity with .NET and Python for MSFT Build in May, 2024. 
Changed the example code to match .NET. 
Fixed some issues in OpenAIChatCompletion to make it work with manual function calling.
> Java: Align Example59_OpenAIFunctionCalling with .NET

- dotnet/samples/KernelSyntaxExamples/Getting_Started/Step2_Add_Plugins.cs
> .Net: Update sample to show how to use enum[] with function calling

- .github/workflows/python-integration-tests.yml
- .github/workflows/python-lint.yml
- .github/workflows/python-test-coverage.yml
- .github/workflows/python-unit-tests.yml
- python/poetry.lock
- python/pyproject.toml
This PR drops support for python 3.8 and 3.9.
Python 3.8 will go out of support in October 2024 and people should not be building on top of that now.
Python 3.10 introduces the new style of typing and for KernelFunctionFromMethod that is a crucial feature and maintaining that with backward compatibility is a lot of work and limits us, hence we will also drop support for 3.9.
Closes #5628
Changed pyproject to reflect this
Changed CICD to only run on 3.10, 3.11 and 3.12.
> Python: drop support for python before 3.10

- dotnet/src/Connectors/Connectors.Onnx.UnitTests/BertOnnxOptionsTests.cs
- dotnet/src/IntegrationTests/Connectors/Onnx/BertOnnxTextEmbeddingGenerationServiceTests.cs
- dotnet/src/IntegrationTests/IntegrationTests.csproj
In one of my PRs I received HTTP 503 error during CI run in Onnx unit tests. It appeared that some of the tests perform actual requests to Hugging Face to download model files. It would be better to keep all unit tests isolated and lightweight, while keep the tests that require additional requests to perform as integration tests.
> .Net: Moved Onnx tests to integration tests

- python/.env.example
- python/semantic_kernel/connectors/memory/astradb/astra_client.py
- python/tests/integration/connectors/memory/test_astradb.py
This PR enriches the HTTP requests to the Astra DB Data API (occurring in the AstraClient) with a User-Agent header specifying the identity of the caller (specifically, "semantic_kernel"). While not mandatory, this is good practice with Astra DB and helps collecting aggregate usage data on the API side.
Using the `importlib.metadata` library the package version is extracted (in a fail-safe way) and used, if present, to enrich the caller information (variable `ASTRA_CALLER_IDENTITY`, later set as the user-agent header for all HTTP requests to the Data API).
> Python: (Astra DB) Include caller identity as user-agent when issuing HTTP request to Astra DB's Data API

- docs/decisions/0037-audio-naming.md
- python/semantic_kernel/connectors/ai/hugging_face/hf_prompt_execution_settings.py
- python/tests/integration/completions/test_hf_local_text_completions.py
- python/tests/unit/functions/test_kernel_function_decorators.py
Even though the completion itself does not callout, loading the model is a HTTP call, hence moving the Hugging Face tests to Integration tests.
Plus small fix to make them run.
> Python: move Hugging Face tests to integration

- java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIChatCompletion.java
- java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/XMLPromptParser.java
- java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/textcompletion/OpenAITextGenerationService.java
- java/api-test/integration-tests/src/test/java/com/microsoft/semantickernel/tests/RenderingTest.java
- java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/Example17_ChatGPT.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/implementation/templateengine/tokenizer/blocks/CodeBlock.java
- java/semantickernel-api/src/main/java/com/microsoft/semantickernel/templateengine/handlebars/HandlebarsPromptTemplate.java
> Java: Ensure xml is unescaped before sending to LLM

- dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAIToolsTests.cs
The ConnectorAgnosticFunctionCallingModelClassesCanPassFunctionExceptionToConnectorAsync integration test has been disabled because it continues to fail, even though it was configured with system instructions on how to handle errors.
> .Net: Flaky integration test disabled.

- dotnet/SK-dotnet.sln.DotSettings
Cannot run KernelSyntax examples on Apple Mx series, because the solution is configured to use X64
Change solution settings, changing "X64" to "Automatic"
> .Net: Use automatic platform detection for unit tests

- dotnet/samples/KernelSyntaxExamples/Example70_Agents.cs
- dotnet/samples/KernelSyntaxExamples/Plugins/MenuPlugin.cs
- dotnet/src/Experimental/Agents/IAgentThread.cs
- dotnet/src/Experimental/Agents/Internal/ChatRun.cs
- dotnet/src/Experimental/Agents/Internal/ChatThread.cs
A well justified customer request to allow `KernelArguments` to be injected into the assistant function calling.
Defined an _opt-in_ pattern that passes the already provided `KernelArguments` to the run (`ChatRun`).
> .Net - Enhance _OLD_ Agents Package for Function Calling Arguments

- dotnet/src/SemanticKernel.Abstractions/Filters/Function/FunctionFilterContext.cs
- dotnet/src/SemanticKernel.Abstractions/Filters/Function/FunctionInvokedContext.cs
- dotnet/src/SemanticKernel.Abstractions/Filters/Function/FunctionInvokingContext.cs
- dotnet/src/SemanticKernel.Abstractions/Filters/Prompt/PromptFilterContext.cs
- dotnet/src/SemanticKernel.Abstractions/Filters/Prompt/PromptRenderedContext.cs
- dotnet/src/SemanticKernel.Abstractions/Filters/Prompt/PromptRenderingContext.cs
Marked unused filter context classes as `Obsolete`.
> .Net: Deprecated unused filter context classes

- dotnet/README.md
- dotnet/src/Experimental/Orchestration.Flow.IntegrationTests/README.md
- dotnet/src/IntegrationTests/README.md
- java/README.md
- java/samples/sample-code/README.md
- java/samples/sample-code/src/main/java/com/microsoft/semantickernel/samples/Example00_GettingStarted.java
- python/DEV_SETUP.md
- python/README.md
- python/samples/documentation_examples/README.md
`https://openai.com/product` is failing `Check .md links` workflow.
Revise links.
https://github.com/microsoft/semantic-kernel/actions/workflows/markdown-link-check.yml
Whitespace edits peformed by VS Code
> Java: Python: Docs: Fix broken link

- dotnet/samples/Concepts/Concepts.csproj
- dotnet/samples/Concepts/Prompty/PromptyFunction.cs
- dotnet/src/Functions/Functions.Prompty.UnitTests/PromptyTest.cs
- dotnet/src/Functions/Functions.Prompty/Extensions/PromptyKernelExtensions.cs
`PromptyKernelExtensions.CreateFunctionFromPrompty`
The second parameter is a file path to a prompty file. This should be changed to the prompty text. Doing this will allow developers to be responsible for loading the prompty file e.g. could be a file or an embedded resource or a database record...
> .Net: Refactor PromptyKernelExtensions.CreateFunctionFromPrompty

- dotnet/src/Extensions/PromptTemplates.Liquid.UnitTests/LiquidTemplateFactoryTest.cs
- dotnet/src/Extensions/PromptTemplates.Liquid/LiquidPromptTemplate.cs
- dotnet/src/Extensions/PromptTemplates.Liquid/LiquidPromptTemplateFactory.cs
- dotnet/src/Functions/Functions.Prompty.UnitTests/PromptyTest.cs
- dotnet/src/Functions/Functions.Prompty/Core/PromptyModelParameters.cs
- dotnet/src/Functions/Functions.Prompty/Core/PromptyYaml.cs
- dotnet/src/Functions/Functions.Prompty/Extensions/PromptyKernelExtensions.cs
- Liquid template parsing should happen during construction, not on each render
- Liquid prompt template construction should fail for invalid templates
- Default inputs should be evaluated once at Liquid template construction time
- RenderAsync should capture any exceptions into returned Task
- Role regex used in parsing rendered messages should be Compiled
- LiquidPromptTemplateFactory should do arg validation and accomodate a PromptTemplateConfig whose TemplateFormat is null
- Use XML comments instead of normal comments to describe properties in internal DOM
- Remove unnecessary empty primary constructor
- Use a regex to parse the components of a prompty template in order to a) more strictly validate contents but more importantly b) avoid losing part of the template when the separator …
> .Net: Clean up some things in LiquidPromptTemplate and PromptyKernelExtensions

- dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromPrompt.cs
- dotnet/src/SemanticKernel.Core/KernelExtensions.cs
> .Net: Tweak temp function names created by Kernel.InvokePrompt{Streaming}Async

- dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBMemoryRecordMetadata.cs
- dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBMemoryStore.cs
1. Fixing the wrong sequence in the constructor of `MemoryRecordMetadata`
2. The cursor is disposed to early, resulting the `SearchAsync` failed.
- [x ] The code builds clean without any errors or warnings
- [ x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x ] All unit tests pass, and I have added new tests where possible
- [ x] I didn't break anyone :smile:
> .Net: Fixing minor defects: Disposing cursor too early also wrong sequence on constructor

- python/semantic_kernel/services/ai_service_selector.py
- python/tests/unit/functions/test_kernel_function_from_prompt.py
The `ai_service_selector` was not properly grabbing a registered service if it didn't match the first registered `service_id`. It's possible that there may be multiple prompt execution settings registered as part of a kernel function; however, only one Chat/Text completion service could be registered, and it may not be the first service id present in the dictionary. If it isn't, we shouldn't be throwing a service not found exception.
 
This PR fixes the behavior, and allows us to try to find other registered services based on the present service IDs. 
- Closes #5977 
- Adds a unit test to cover this behavior.
> Python: Check for other services registered before throwing service not found.

- dotnet/samples/Concepts/Filtering/RetryWithFilters.cs
- dotnet/samples/Concepts/README.md
Based on: https://github.com/microsoft/semantic-kernel/discussions/6105
This example shows how to perform retry with filter and switch to another model as a fallback.
> .Net: Example of retry logic using Filters

- python/semantic_kernel/prompt_template/jinja2_prompt_template.py
The `Jinja2PromptTemplate` allows users to integrate `Jinja2` as `Prompt engine` within a `semantic-kernel` structure LLM application. Nevertheless, `Jinja2PromptTemplate` directly takes **sandbox-less** `jinja2.Environment` as `Jinja2 Environment`, allowing attackers to escape and call arbitrary `__builtins__` methods such as `os.Popen`, resulting possible RCE or further exploitations.
This PR fixes this by implementing a SandboxedEnvironment to prevent users from being able to run malicious code.
- All tests passing.
> Python: Use a Jinja2 sandboxed env to prevent running unsafe code.

- dotnet/samples/Concepts/Filtering/PIIDetection.cs
- dotnet/samples/Concepts/Filtering/PIIDetectionWithFilters.cs
- dotnet/samples/Concepts/README.md
This example shows how to implement Personal Identifiable Information (PII) detection logic with Filters using Microsoft Presidio service: https://github.com/microsoft/presidio.
Example contains two filters:
First filter is responsible for PII detection in prompt by using Presidio Text Analyzer. If PII is detected, then the prompt won't be sent to LLM and custom result will be returned after function invocation.
Example output:
```
Prompt: John Smith has a card 1111 2222 3333 4444
Entity type: CREDIT_CARD. Score: 1
Entity type: PERSON. Score: 0.85
Exception: Prompt contains PII information. Operation is canceled.
```
Second filter is responsible for PII detection in prompt and updating the prompt by following specified rules before sending it to LLM. This filter uses Presidio Text …
> .Net: Example of prompt PII detection logic with Filters and Microsoft Presidio

- python/semantic_kernel/functions/kernel_function_decorator.py
- python/tests/unit/functions/test_kernel_function_decorators.py
Updated kernel_function decorator, that better handles new typing styles in py 3.10+.
Replaces #5613 
Uses newer inspect methods to figure out the annotations, works only for the new style introduced in py 3.10+
> Python: new kernel function decorator

- python/samples/concepts/plugins/openai_plugin_azure_key_vault.py
- python/samples/concepts/plugins/openapi/openapi_client.py
- python/samples/concepts/resources/open_ai_plugins/akv-openai.json
- python/semantic_kernel/connectors/openapi_plugin/openapi_function_execution_parameters.py
- python/semantic_kernel/connectors/openapi_plugin/openapi_manager.py
- python/tests/unit/connectors/openapi/test_sk_openapi.py
- python/tests/unit/functions/test_kernel_plugins.py
- python/tests/unit/kernel/test_kernel.py
A custom client was used to get the openapi spec but it wasn't passed down into the openapi runner.
Pass the custom client into the open api runner if desired. Fix param parsing and samples.
> Python: allow openapi runner to use a custom client

- dotnet/src/SemanticKernel.Abstractions/Kernel.cs
- dotnet/src/SemanticKernel.UnitTests/Filters/FilterBaseTest.cs
- dotnet/src/SemanticKernel.UnitTests/Filters/KernelFilterTests.cs
Based on: https://github.com/microsoft/semantic-kernel/discussions/6240
Since filters are cloned when they are registered through DI container, in the same way they should be cloned when registered through Kernel properties (i.e. `kernel.FunctionInvocationFilters`).
> .Net: Fix filters cloning when registered via Kernel properties

- dotnet/src/Connectors/Connectors.MistralAI/Client/MistralClient.cs
- dotnet/src/Connectors/Connectors.MistralAI/Client/MistralUsage.cs
- dotnet/src/Connectors/Connectors.MistralAI/Connectors.MistralAI.csproj
- dotnet/src/Connectors/Connectors.MistralAI/Extensions/MistralAIPluginCollectionExtensions.cs
- dotnet/src/IntegrationTests/Connectors/MistralAI/ChatCompletion/MistralAIChatCompletionTests.cs
- dotnet/src/IntegrationTests/Connectors/MistralAI/TextEmbedding/MistralAITextEmbeddingTests.cs
> .Net: Code clean-up

- dotnet/src/SemanticKernel.Abstractions/Functions/KernelFunction.cs
- dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromMethod.cs
- dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromPrompt.cs
- dotnet/src/SemanticKernel.UnitTests/Functions/KernelPluginTests.cs
It currently fails to call ToString (throws a JSON serialization exception). Change KernelFunction.ToString to just print out the name.
> .Net: Fix KernelFunctionFromMethod.ToString

- python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py
When a function that was called using tool calling fails, it shouldn't drop the whole flow, this fixes that.
Fix #6260 
Creates a function result content item with the failing function and the error message, allowing the model to figure out if it wants to recall with different params.
> Python: handle failing tool call gracefully

- dotnet/samples/Demos/TelemetryWithAppInsights/Program.cs
- dotnet/src/Connectors/Connectors.Google/Core/Gemini/Clients/GeminiChatCompletionClient.cs
- dotnet/src/Connectors/Connectors.HuggingFace/Core/HuggingFaceClient.cs
- dotnet/src/Connectors/Connectors.HuggingFace/Core/HuggingFaceMessageApiClient.cs
- dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs
- dotnet/src/InternalUtilities/src/Diagnostics/ModelDiagnostics.cs
Previously when an AI client starts a model diagnostics activity, it passes in an execution setting that is not parsed to a setting that is specific to the client. This creates an issue where the some of the settings cannot be read by the diagnostics module.
Pass in the parsed setting to the diagnostics module. The diagnostics module will the serialize the object and deserialize it to `PromptExecutionSettings` to get the extension data.
> .Net: fixed extension data in Model diagnostics

- dotnet/src/Connectors/Connectors.Google/Core/Gemini/Clients/GeminiChatCompletionClient.cs
- dotnet/src/Connectors/Connectors.HuggingFace/Core/HuggingFaceClient.cs
- dotnet/src/Connectors/Connectors.HuggingFace/Core/HuggingFaceMessageApiClient.cs
- dotnet/src/Connectors/Connectors.MistralAI/Client/MistralClient.cs
- dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs
Replicates the ModelDiagnostics stuff to the MistralAI chat completion service implementation.
I still need to test it. Best I can say now is it compiles :)
cc: @markwallace-microsoft, @TaoChenOSU
> .Net: Add activities to MistralClient

- python/samples/concepts/logging/setup_logging.py
- python/semantic_kernel/utils/experimental_decorator.py
- python/tests/conftest.py
- python/tests/unit/functions/test_kernel_experimental_decorator.py
- python/tests/unit/functions/test_kernel_function_decorators.py
- python/tests/unit/kernel/test_kernel.py
There may be classes or functions inside of SK Python that should be deemed as experimental. Currently in Python there is no out-of-the-box way to get the decorator.
As there is a name clash with using `experimental` as the decorator name, we are introducing two decorators: one `experimental_class` and one `experimental_function`. The note that "This {function | class} is experimental and may change in the future" is included in the docstring and a bool `is_experimental` on the class is added.
> Python: Create an experimental class and function decorator.

- dotnet/src/Connectors/Connectors.Google/Core/Gemini/Clients/GeminiChatCompletionClient.cs
- dotnet/src/Connectors/Connectors.HuggingFace/Core/HuggingFaceMessageApiClient.cs
- dotnet/src/Connectors/Connectors.MistralAI/Client/MistralClient.cs
- dotnet/src/Connectors/Connectors.MistralAI/MistralAIKernelBuilderExtensions.cs
- dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs
- The logger factory wasn't being forwarded to the chat completion service instance
- The class wasn't logging tokens like the other connectors
Also made the others consistent in verbiage, metrics namespace, etc.
> .Net: Fix MistralAI logging

- dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs
- dotnet/src/InternalUtilities/src/Diagnostics/ModelDiagnostics.cs
Tool call information is currently not included in the model diagnostics when using the streaming APIs.
1. Record OpenAI tool call information in model diagnostics for the streaming API.
2. If there is no tool call information, do not record an empty entry.
> .Net: Include streaming tool call information in model diagnostics

- dotnet/src/Plugins/Plugins.Core/TextPlugin.cs
On .NET Framework, a null CultureInfo triggers an ArgumentNullException.
> .Net: Fix ArgumentNullException from TextPlugin.Uppercase/Lowercase on .NET Framework

- dotnet/src/InternalUtilities/src/Http/HttpClientProvider.cs
On older .NET Frameworks, CheckCertificateRevocationList may not be supported.
https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.checkcertificaterevocationlist?view=net-8.0#exceptions
> .Net: Fix PlatformNotSupportedException from HttpClientProvider

- python/semantic_kernel/functions/kernel_plugin.py
The docs tool is breaking because two methods share the same signatures and the beginnings of the docstring. 
Try to differentiate the docstrings by a char to see if it fixes the docs generation.
> Python: Try to fix a doc building issue.

- python/semantic_kernel/functions/kernel_plugin.py
Separate set and __setitem__ doc strings
Separate set and __setitem__ doc strings
> Python: Separate set and __setitem__ strings

- python/samples/concepts/plugins/openai_function_calling_with_custom_plugin.py
- python/semantic_kernel/functions/kernel_plugin.py
- python/semantic_kernel/planners/function_calling_stepwise_planner/function_calling_stepwise_planner.py
- python/semantic_kernel/prompt_template/utils/jinja2_system_helpers.py
- python/semantic_kernel/schema/kernel_json_schema_builder.py
- python/tests/integration/planning/function_calling_stepwise_planner/test_int_function_calling_stepwise_planner.py
The FC stepwise planner was breaking when trying to process the function call result because if a filter is not configured, then the context will be None. We need to only try to extract the FC result if the context is not none, otherwise it will already be present in the chat history.
Check that the FC result context is not None, if so, then extract the FC result, otherwise proceed as the FC result is in the chat history. Fixes #6350.
- Removes some extranous logging from json schema addition.
> Python: Fix FC stepwise planner.

- java/aiservices/openai/src/main/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAIChatCompletion.java
- java/aiservices/openai/src/test/java/com/microsoft/semantickernel/aiservices/openai/chatcompletion/OpenAiChatCompletionTest.java
- java/aiservices/openai/src/test/resources/com/microsoft/semantickernel/aiservices/openai/chatcompletion/chatCompletion.txt
- java/api-test/integration-tests/src/test/java/com/microsoft/semantickernel/tests/ToolCallBehaviourTest.java
- java/samples/semantickernel-concepts/semantickernel-syntax-examples/src/main/java/com/microsoft/semantickernel/samples/syntaxexamples/functions/Example59_OpenAIFunctionCalling.java
> Java: Add example of a multi turnaround chat with tool calls. Fixes bug with serializing tool call arguments

- python/semantic_kernel/functions/kernel_plugin.py
Fix docstrings so the docs tool can pass.
Fix docstrings so the docs tool can pass.
> Python: Fix doc strings

- python/samples/concepts/search/bing_plugin_examples.py
- python/samples/learn_resources/serializing_prompts.py
- python/semantic_kernel/connectors/ai/open_ai/const.py
- python/tests/unit/core_plugins/test_http_plugin.py
- python/tests/unit/core_plugins/test_math_plugin.py
- python/tests/unit/core_plugins/test_sessions_python_plugin.py
- python/tests/unit/core_plugins/test_text_memory_plugin.py
- python/tests/unit/core_plugins/test_text_plugin.py
- python/tests/unit/core_plugins/test_time_plugin.py
- python/tests/unit/kernel/test_kernel.py
- python/tests/unit/kernel/test_register_functions.py
Refactoring some of the code following [this advice](https://github.com/microsoft/semantic-kernel/pull/6371#discussion_r1611138252) from the maintainers.
Look up kernel functions and plugins with the `get_function` and `get_plugin` method. Removed the unused `DEFAULT_CHAT_SYSTEM_PROMPT`
> Python: Refactoring. Use get_function and get_plugin.

- python/semantic_kernel/connectors/memory/azure_cognitive_search/azure_cognitive_search_memory_store.py
The ACS admin key isn't required as the user can pass in either azure credentials or token credentials. Right now there is an assert on the api_key not being null that is blocking. 
Remove the assert on the api_key. Closes #6369
> Python: Remove assert on non-required api_key

- python/semantic_kernel/connectors/ai/function_call_behavior.py
- python/semantic_kernel/connectors/ai/ollama/services/ollama_chat_completion.py
- python/semantic_kernel/connectors/ai/ollama/services/ollama_text_completion.py
- python/semantic_kernel/connectors/ai/open_ai/services/azure_chat_completion.py
- python/semantic_kernel/connectors/ai/open_ai/services/azure_text_completion.py
- python/semantic_kernel/connectors/ai/open_ai/services/azure_text_embedding.py
- python/semantic_kernel/connectors/ai/prompt_execution_settings.py
- python/semantic_kernel/connectors/memory/azure_cognitive_search/azure_cognitive_search_memory_store.py
- python/semantic_kernel/connectors/memory/qdrant/qdrant_memory_store.py
- python/semantic_kernel/contents/chat_message_content.py
- python/semantic_kernel/contents/function_result_content.py
- python/semantic_kernel/contents/streaming_chat_message_content.py
- python/semantic_kernel/contents/streaming_text_content.py
- python/semantic_kernel/contents/text_content.py
- python/semantic_kernel/core_plugins/text_plugin.py
- python/semantic_kernel/core_plugins/time_plugin.py
- python/semantic_kernel/planners/function_calling_stepwise_planner/function_calling_stepwise_planner.py
- python/semantic_kernel/services/ai_service_client_base.py
- python/semantic_kernel/services/ai_service_selector.py
- python/semantic_kernel/template_engine/blocks/code_block.py
- python/semantic_kernel/template_engine/blocks/function_id_block.py
- python/semantic_kernel/template_engine/blocks/named_arg_block.py
- python/semantic_kernel/template_engine/blocks/var_block.py
- python/semantic_kernel/template_engine/code_tokenizer.py
> Python: Fix typos.

- python/samples/concepts/auto_function_calling/chat_gpt_api_function_calling.py
- python/samples/concepts/plugins/openai_function_calling_with_custom_plugin.py
> Python: Fix typo

- python/semantic_kernel/prompt_template/input_variable.py
- python/semantic_kernel/prompt_template/prompt_template_config.py
Fix doc string for allow_dangerously_set_content
Fix doc string for allow_dangerously_set_content
> Python: Fix doc string for allow_dangerously_set_content

- dotnet/src/Connectors/Connectors.MistralAI.UnitTests/Client/MistralClientTests.cs
- dotnet/src/Connectors/Connectors.MistralAI/Client/MistralClient.cs
- dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs
- dotnet/src/Connectors/Connectors.UnitTests/OpenAI/FunctionCalling/AutoFunctionInvocationFilterTests.cs
Fixes: https://github.com/microsoft/semantic-kernel/issues/6404
Today, the SK chat completion streaming API does not return the result of a function executed before termination, whereas the non-streaming version does return the result. This PR resolves this issue by returning the result of a function executed before termination was requested.
> .Net: Return result of the function executed before termination for streaming API

- docs/decisions/0010-dotnet-project-structure.md
- dotnet/samples/Demos/BookingRestaurant/README.md
- dotnet/samples/Demos/TimePlugin/README.md
1. This change is required to ensure all documentation links are up-to-date.
2. It solves the problem of users encountering broken or outdated links.
3. It contributes to the scenario of maintaining accurate and helpful documentation for users.
4. N/A
Updated several obsolete links in the documentation to point to the current and correct URLs. This ensures users have access to the most recent and relevant information.
> .Net: Update obsolete links

- dotnet/Directory.Packages.props
- dotnet/samples/Concepts/ChatCompletion/OpenAI_ChatCompletionWithVision.cs
- dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs
Fixes: https://github.com/microsoft/semantic-kernel/issues/6443
This is temporary fix before new updates to `ImageContent` class will be in place: https://github.com/microsoft/semantic-kernel/pull/6319
cc: @RogerBarreto
> .Net: Fixed ImageContent usage in OpenAI connector

- python/semantic_kernel/prompt_template/jinja2_prompt_template.py
- python/semantic_kernel/prompt_template/utils/template_function_helpers.py
- python/tests/unit/prompt_template/test_jinja2_prompt_template.py
- python/tests/unit/prompt_template/test_template_helper.py
Jinja2 templates now use async functions instead of nested ones!
With full testing
> Python: implement async support for templates

- python/samples/__init__.py
- python/samples/learn_resources/__init__.py
- python/samples/learn_resources/configuring_prompts.py
- python/samples/learn_resources/creating_functions.py
- python/samples/learn_resources/plugin.py
- python/samples/learn_resources/templates.py
- python/samples/learn_resources/using_the_kernel.py
- python/tests/integration/completions/test_azure_oai_text_service.py
Several of the imports in the learn files were showing as unable to resolve after the service configuration was moved to a different directory.
Creating the `__init__.py` in the directory where the importable files live. Adjusting code to reflect this. Imports now resolve.
> Python: Adjust the learn file imports based on a previous refactor.

- python/samples/concepts/auto_function_calling/chat_gpt_api_function_calling.py
- python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py
- python/tests/integration/completions/test_azure_oai_chat_service_extensions.py
If auto_invoke was False and the function used streaming, the max func attempts were being set to 0 which Python's range function doesn't like. The chat gpt auto function calling example was also broken due to wrong checks on the returned result for FunctionCallResult objects.
Fixing handling streaming tool calls when auto invoke is false and fixing the chat gpt auto function calling concept example.
> Python: Handle streaming tool call attempts. Fix func calling concept example.

- dotnet/docs/TELEMETRY.md
Upon reviewing the Microsoft Learn documentation update, it has come to our attention that the TELEMETRY.md file contains outdated recommendations regarding the setup of `ILoggerFactory`.
1. Ensure the documentation contains the latest recommendations and improve clarity.
> .Net: Update TELEMETRY.md to include the latest recommended pattern for ILoggerFactory

- .github/workflows/python-integration-tests.yml
We have tests that cover our samples -- notebooks, learn and concepts; however, they aren't getting triggered in the pipeline. They would need to run manually, which may not always be the case, and thus would allow for us to check-in changes that may break these.
Run the `/tests/samples` directory as integration tests now. This will give us the peace of mind that we have coverage as code is checked in via pull requests.
> Python: Run samples as integration tests.

- dotnet/src/Extensions/PromptTemplates.Handlebars/Helpers/KernelHelpers/KernelFunctionHelpers.cs
- dotnet/src/Functions/Functions.OpenApi/Extensions/RestApiOperationResponseExtensions.cs
- dotnet/src/Functions/Functions.OpenApi/RestApiOperationRunner.cs
- dotnet/src/Functions/Functions.UnitTests/OpenApi/RestApiOperationRunnerTests.cs
- dotnet/src/SemanticKernel.Abstractions/Functions/RestApiOperationResponse.cs
> .Net: Handle empty response with no content type in RestApiOperationRunner

- .github/workflows/python-integration-tests.yml
Need to fix some platform (Windows) specific integration test issues. Will re-create this PR to turn on tests when done.
> Python: Revert change to run samples as tests in CI

- dotnet/src/InternalUtilities/src/Diagnostics/ModelDiagnostics.cs
> .Net: Avoid null ref in ModelDiagnostics.SetCompletionResponse

- python/semantic_kernel/connectors/memory/azure_cognitive_search/azure_ai_search_settings.py
- python/semantic_kernel/connectors/memory/azure_cognitive_search/azure_cognitive_search_memory_store.py
We have a regression that makes the AI Search Setting's API key required.
Make the AI Search setting a non-required attribute. Fixes #6697
> Python: Azure AI Search api key should not be required.

- dotnet/src/Experimental/Orchestration.Flow.IntegrationTests/README.md
- dotnet/src/Experimental/Orchestration.Flow.IntegrationTests/testsettings.json
- dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAICompletionTests.cs
- dotnet/src/IntegrationTests/README.md
- dotnet/src/IntegrationTests/prompts/GenerateStory.yaml
- dotnet/src/IntegrationTests/prompts/GenerateStoryHandlebars.yaml
- dotnet/src/IntegrationTests/testsettings.json
Azure OpenAI deprecated `text-davinci-003` model, which is used in our integration tests. This PR replaces `text-davinci-003` through the code with `gpt-3.5-turbo-instruct` and improves some prompts to be compatible with new model.
> .Net: Replaced text-davinci-003 with gpt-3.5-turbo-instruct

- dotnet/src/Connectors/Connectors.Memory.Sqlite/Database.cs
- dotnet/src/Connectors/Connectors.Memory.Sqlite/SqliteMemoryStore.cs
1. Instead of executing two SQL queries, a single query can do the same thing.
2. Performance improvement
Previously the **InternalUpsertAsync** method was executing two sql query by calling two individual methods - First **UpdateAsync** and then second **InsertOrIgnoreAsync**.
The new method uses the INSERT OR REPLACE statement to either update an existing row or insert a new one based on the unique collection and key combination
> .Net: instead running two queries now a single query can do the same thing

- python/semantic_kernel/utils/experimental_decorator.py
Closes https://github.com/microsoft/semantic-kernel/issues/6707 
- Introduce `TypeVar` `T` bounded to `type` to ensure the decorator maintains the class type.
- Modify the `experimental_class` decorator to use the bounded `TypeVar` for accurate type hinting.
> Python: fix: Preserve class type in `experimental_class` decorator to avoid type inference issues

- python/samples/concepts/README.md
- python/samples/concepts/setup/ALL_SETTINGS.md
- python/samples/concepts/setup/README.md
- python/samples/concepts/setup/openai_env_setup.py
- python/semantic_kernel/connectors/memory/postgres/postgres_settings.py
Clarify the names and uses of the environment variables and pydantic settings.
> Python: Env sample

- dotnet/src/Connectors/Connectors.UnitTests/Memory/VectorStoreRecordPropertyReaderTests.cs
- dotnet/src/InternalUtilities/src/Schema/VectorStoreRecordPropertyReader.cs
- dotnet/src/SemanticKernel.UnitTests/Utilities/VectorStoreRecordPropertyReaderTests.cs
The property enumerator helps to read property information from a model used with any of the vector stores.
This property information is used to map from the storage model to the user data model.
Adding unit tests for this property enumerator, and marking it with the exclude from code coverage attribute, since
the file is located in the Internal Utilities folder and therefore is included in all projects, but it will not be unit tested in each, just in the one centralized location.
> .Net: Adding unit tests for property enumerator and excluding from code coverage since it's in InternalUtilities.

- dotnet/Directory.Packages.props
This pull request updates the package versions of DuckDB.NET.Data and DuckDB.NET.Data.Full from 0.10.x to 1.0.0
> .Net: Update DuckDB.NET.Data and DuckDB.NET.Data.Full package versions to 1.0.0

- python/samples/concepts/README.md
- python/samples/concepts/service_selector/custom_service_selector.py
- python/tests/samples/test_concepts.py
> Python: custom service selector sample

- dotnet/src/Plugins/Plugins.Core/PromptFunctionConstants.cs
Fixing ConversationSummaryPlugin's ActionItems response by improving underlying prompt
1. Why is this change required?
This change is required in order to fix reported [issue: 4843](https://github.com/microsoft/semantic-kernel/issues/4843)
The change improves the prompt behind the "GetConversationActionItems" function of "ConversationSummaryPlugin", in order to get expected/correct results.  
2. What problem does it solve?
The "GetConversationActionItems" doesn't return expected result. It even did not return as expected by the MS Learning path samples. Upon checking the issues, I found [Issue 4843](https://github.com/microsoft/semantic-kernel/issues/4843) already opened against it, so I tried to find the root cause of this behavior and fix it.
The change improves the prompt behind the …
> .Net: Fixing ConversationSummaryPlugin's ActionItems response by improving underlying prompt

- dotnet/src/SemanticKernel.Abstractions/Contents/ChatMessageContent.cs
- dotnet/src/SemanticKernel.UnitTests/Contents/ChatMessageContentTests.cs
This is a follow-up fix for the `ChatMessageContent.Content` property setter, similar to the one that was done to the `StreamingChatMessageContent.Content` property when addressing the PR comment: https://github.com/microsoft/semantic-kernel/pull/6449#discussion_r1633235050.
This change updates the text of the first text item regardless of the value being set. This helps avoid inconsistency that occurs when text content already exists in the items collection, null is set via the Content property, and the setter does nothing, while the getter returns the text message content:
```csharp
var items = new ChatMessageContentItemCollection
{
new TextContent("Hi AI."),
};
var chatMessage = new ChatMessageContent(AuthorRole.User, items: items);
chatMessage.Content = null; // The property setter …
```
> .Net: Align the behavior of the ChatMessageContent.Content property setter with streaming counterpart

- python/semantic_kernel/connectors/ai/open_ai/const.py
- python/semantic_kernel/connectors/ai/open_ai/services/azure_config_base.py
- python/semantic_kernel/connectors/ai/open_ai/services/open_ai_config_base.py
- python/semantic_kernel/connectors/memory/azure_cognitive_search/utils.py
- python/semantic_kernel/connectors/openapi_plugin/openapi_runner.py
- python/semantic_kernel/connectors/telemetry.py
- python/semantic_kernel/const.py
- python/semantic_kernel/core_plugins/sessions_python_tool/sessions_python_plugin.py
- python/tests/unit/connectors/google_palm/services/test_palm_chat_completion.py
- python/tests/unit/connectors/google_palm/services/test_palm_text_completion.py
- python/tests/unit/connectors/google_palm/services/test_palm_text_embedding.py
- python/tests/unit/connectors/open_ai/services/test_azure_chat_completion.py
- python/tests/unit/connectors/open_ai/services/test_azure_text_completion.py
- python/tests/unit/connectors/open_ai/services/test_azure_text_embedding.py
- python/tests/unit/connectors/open_ai/services/test_openai_chat_completion.py
- python/tests/unit/connectors/open_ai/services/test_openai_text_completion.py
- python/tests/unit/core_plugins/test_sessions_python_plugin.py
- python/tests/unit/functions/test_kernel_plugins.py
- python/tests/unit/telemetry/test_user_agent.py
Updates to the User-Agent are required so that we can align with all three SK languages. Examples:
User agent
- semantic-kernel-csharp/1.1.1 [existing user agent]
- semantic-kernel-java/1.1.1 [existing user agent]
- semantic-kernel-python/1.1.1 [existing user agent]
semantic-kernel-version header
- csharp/1.1.1 
- java/1.1.1
- python/1.1.1
Updates to the user agent to reflect the desired changes/standardization across all SK languages. Adding unit tests.
- Closes #6827 
- Moves the `USER_AGENT` const from its previous home in the openai const file to a more generic const file.
- Updates unit tests to be able to run properly when a valid `.env` file exists in the current working directory. The unit tests patch the env vars and our current implementation of Pydantic Settings loads the …
> Python: Updates to user agent. Add unit tests.
