dotnet/SK-dotnet.sln
dotnet/src/Connectors/Connectors.Memory.Qdrant/Connectors.Memory.Qdrant.csproj
dotnet/src/Connectors/Connectors.Memory.Redis/Connectors.Memory.Redis.csproj
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/.editorconfig
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/Connectors.Qdrant.UnitTests.csproj
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantMemoryBuilderExtensionsTests.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantMemoryStoreTests.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantMemoryStoreTests2.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantMemoryStoreTests3.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantVectorDbClientTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/.editorconfig
dotnet/src/Connectors/Connectors.Redis.UnitTests/Connectors.Redis.UnitTests.csproj
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisMemoryStoreTests.cs
dotnet/src/Connectors/Connectors.UnitTests/Connectors.UnitTests.csproj

Currently all unit tests for connectors are in a single project which references all the different connector implementation projects.  Since all the implementation projects reference the same shared InternalUtilities classes, we end up with conflicts in the unit test project, since the same classes are coming from multiple projects.
Moving the Qdrant and Redis unit tests into their own projects.
Will move more as we add additional connector implementations using our new design.

.Net: Split redis and qdrant memory connector unit test projects from main unit test project.

---

dotnet/Directory.Packages.props
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorRecordStore.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/Connectors.Memory.Qdrant.csproj
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantRecordMapperType.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorRecordStore.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorRecordStoreOptions.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordMapper.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordMapperOptions.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorRecordStore.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorRecordStoreTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorRecordStoreTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorStoreCollectionFixture.cs
dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorStoreFixture.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisVectorRecordStoreTests.cs
dotnet/src/IntegrationTests/IntegrationTests.csproj
dotnet/src/InternalUtilities/src/Data/VectorStoreErrorHandler.cs
dotnet/src/InternalUtilities/src/Data/VectorStoreRecordPropertyReader.cs
dotnet/src/SemanticKernel.Abstractions/Memory/IVectorRecordStore.cs
dotnet/src/SemanticKernel.UnitTests/Data/VectorStoreRecordPropertyReaderTests.cs

As part of the evolution of memory connectors, we need to support custom data models and remove opinionated behaviors, so adding a new record store implementation for qdrant.
Adding an implementation for IVectorRecordStore for qdrant with support for:
Custom mappers
Generic data models
Annotating data models via attributes or via definition objects.
Also improving some styling in the AzureAISearch implementation.
See #6525

.Net: Add qdrant vector record store implementation

---

dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs
dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAICompletionTests.cs

`StreamingChatMessageContent.AuthorRole` always `null`
Logic already exists to capture role, but it was not being passed to each and every instance of StreamingChatMessageContent.  Other properties, such as `ModelId` are included with each and every instance.
Updated integration test.
Issue: https://github.com/microsoft/semantic-kernel/issues/6952

.Net Fix - Include role definition for each StreamingChatMessageContent

---

dotnet/Directory.Packages.props
dotnet/src/Connectors/Connectors.Memory.Kusto/KustoMemoryStore.cs
dotnet/src/Connectors/Connectors.UnitTests/Memory/Kusto/KustoMemoryStoreTests.cs

This PR includes the following changes
1. Bump version of `Microsoft.Azure.Kusto.Data` to version 12.2.2
2. Switch from obsolete `NormalizeTableName` to recommended `NormalizeName`
Background on this second change:
- The default behavior of `NormalizeTableName` is to only add brackets if they seem needed, while `NormalizeName` always does. 
- Unless you rely on the exact kql generated it shouldn't matter, if you want to force the old behavior add `NormalizationMode.Classic`
- The normalization of plenty of identifier kinds has been unified, so you no longer need most of the specialized methods

.Net: Bump Microsoft.Azure.Kusto.Data

---

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorRecordStore.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorRecordStore.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordMapper.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorRecordStore.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStoreRecordMapper.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantVectorStoreRecordMapperTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisVectorStoreRecordMapperTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorRecordStoreTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorRecordStoreTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisVectorRecordStoreTests.cs
dotnet/src/SemanticKernel.Abstractions/Memory/IVectorStoreRecordMapper.cs
dotnet/src/SemanticKernel.Abstractions/Memory/StorageToDataModelMapperOptions.cs

As part of adding new vector stores for redis and qdrant, these include mappers from data models to storage models and back, that require unit testing.
The mapper interface also uses an options parameter which was reused from the IVectorRecordStore.GetAsync method, but really should have been a dedicated options object from the start.
- Added unit tests for the redis and qdrant data model mappers.
- Added a dedicated options model for the mapper.

.Net: VectorStore: Add unit tests for mappers and adding dedicated options for mapper.

---

dotnet/src/Connectors/Connectors.AzureAISearch.UnitTests/AzureAISearchVectorRecordStoreTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisVectorRecordStoreTests.cs
dotnet/src/InternalUtilities/src/Data/VectorStoreRecordPropertyReader.cs

As part of updating the design of the memory connectors to allow custom schemas, adding unit tests
for AzureAISearch and Redis Vector Record Stores.
Add unit tests for AzureAISearch and Redis Vector Record Stores.

.Net: Add unit tests for AzureAISearch and Redis Vector Record Stores.

---

dotnet/src/SemanticKernel.Abstractions/Contents/ChatMessageContent.cs
dotnet/src/SemanticKernel.Abstractions/Contents/StreamingChatMessageContent.cs
dotnet/src/SemanticKernel.UnitTests/Contents/ChatMessageContentTests.cs
dotnet/src/SemanticKernel.UnitTests/Contents/StreamingChatMessageContentTests.cs

Assist caller in avoiding an improper assignmemt of:
- `ChatMessageContent.AuthorRole`
- `StreamingChatMessageContent.AuthorRole`
Inadvertent assignment of an empty string (or whitespace) to `ChatMessageContant.AuthorName ` results in an `HttpOperationException` when using the message as input to `IChatCompletionService`.
While it may be ideal for caller to take care to _not_ assign such a value, intercepting this state at the earliest possible moment reduces debugging confusion. 
> Stronger validation may not be appropriate as it may be model specific.

.Net - Convert message `AuthorName` whitespace or empty string assignment to `null`

---

dotnet/src/Connectors/Connectors.Memory.Qdrant/Connectors.Memory.Qdrant.csproj
dotnet/src/Connectors/Connectors.Memory.Qdrant/MockableQdrantClient.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorRecordStore.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorRecordStore.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantVectorRecordStoreTests.cs

As part of updating the design of the memory connectors to allow custom schemas, adding unit tests
for Qdrant Vector Record Store.
Add unit tests for Qdrant Vector Record Store.

.Net: VectorStore: Adding unit tests for the Qdrant vector record store.

---

dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Extensions/AzureOpenAIServiceCollectionExtensionsTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Extensions/AzureOpenAIServiceKernelBuilderExtensionsTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Extensions/ChatHistoryExtensionsTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Core/ClientCore.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Extensions/AzureOpenAIServiceCollectionExtensions.cs
dotnet/src/IntegrationTestsV2/Connectors/AzureOpenAI/AzureOpenAIChatCompletionTests.cs
dotnet/src/IntegrationTestsV2/Connectors/AzureOpenAI/AzureOpenAIChatCompletion_FunctionCallingTests.cs
dotnet/src/IntegrationTestsV2/Connectors/AzureOpenAI/AzureOpenAIChatCompletion_NonStreamingTests.cs
dotnet/src/IntegrationTestsV2/Connectors/AzureOpenAI/AzureOpenAIChatCompletion_StreamingTests.cs
dotnet/src/IntegrationTestsV2/IntegrationTestsV2.csproj
dotnet/src/IntegrationTestsV2/TestHelpers.cs
dotnet/src/IntegrationTestsV2/TestSettings/AzureOpenAIConfiguration.cs

This PR is the next step in a series of follow-up PRs to migrate the AzureOpenAIChatCompletion service to the Azure AI SDK v2. It adds extension methods for the service collection and kernel builder to create and register the AzureOpenAIChatCompletionService. Additionally, it includes integration tests for the service.

.Net: Extension methods & integration tests for AzureOpenAIChatCompletionService v2

---

python/samples/concepts/auto_function_calling/nexus_raven.py
python/semantic_kernel/contents/chat_history.py
python/semantic_kernel/contents/chat_message_content.py
python/semantic_kernel/contents/function_result_content.py
python/semantic_kernel/core_plugins/math_plugin.py
python/semantic_kernel/functions/kernel_function_from_prompt.py
python/semantic_kernel/kernel.py

This introduces a sample that uses function calling with a local model, Nexus Raven V2, in this case using the API, but the same model can be loaded using the Hugging Face Connection, the class here is highly adapted and specific to Nexus including parsing the returned function call value, into FunctionCallContent and then running that.
It then returns one or more ChatMessageContents with the function call content and function result content which can then be shared with a OpenAI call.
Error handling improvements:
* [`python/semantic_kernel/contents/chat_history.py`](diffhunk://#diff-b57a30f97fec1a91bbf6f7d15584473a8f0cf409797bdcd90d8c80bedc670892L266-R267): Improved error logging when parsing prompts as XML fails.
* [`python/semantic_kernel/contents/function_result_content.py`](diffhunk:/ …

Python: slight improvements in kernel and function result content, sample of local function calling with Nexus Raven

---

dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Extensions/AzureOpenAIServiceCollectionExtensionsTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Extensions/AzureOpenAIServiceKernelBuilderExtensionsTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Connectors.AzureOpenAI.csproj
dotnet/src/Connectors/Connectors.AzureOpenAI/Services/AzureOpenAITextEmbeddingGenerationService.cs

This PR prepares the AzureOpenAITextEmbeddingGenerationService for migration to the new Azure AI SDK v2. The AzureOpenAITextEmbeddingGenerationService is copied to the Connectors.AzureOpenAI project as is and excluded from compilation to simplify code review of the next PR, which will refactor it to use the new Azure SDK. The next PR will also add unit/integration tests, along with service collection and kernel builder extension methods.
The AzureOpenAITextEmbeddingGenerationService class was copied as is to the Connectors.AzureOpenAI project. The class build action was set to none to exclude it temporarily from the compilation process until it gets refactored to the new SDK.

.Net: Copy AzureOpenAITextEmbeddingGenerationService to Connectors.AzureOpenAI project

---

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorRecordStore.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorRecordStore.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorRecordStore.cs
dotnet/src/InternalUtilities/src/Data/VectorStoreErrorHandler.cs
dotnet/src/SemanticKernel.Abstractions/Memory/VectorStoreException.cs
dotnet/src/SemanticKernel.Abstractions/Memory/VectorStoreOperationException.cs
dotnet/src/SemanticKernel.Abstractions/Memory/VectorStoreRecordMappingException.cs

As part of the new vector store implementation, we need to add additional metadata to exceptions to share information about the operation that failed.
Changing the way in which the metadata is stored to strongly typed properties.

.Net: VectorStore: Add strongly typed properties for vector store exception metadata.

---

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorRecordStore.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorRecordStoreOptions.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordMapper.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorRecordStore.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorRecordStoreOptions.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreFixture.cs
dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorStoreFixture.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisVectorStoreFixture.cs
dotnet/src/InternalUtilities/src/Data/VectorStoreRecordPropertyReader.cs
dotnet/src/SemanticKernel.Abstractions/Memory/RecordAttributes/VectorStoreRecordDataAttribute.cs
dotnet/src/SemanticKernel.Abstractions/Memory/RecordAttributes/VectorStoreRecordKeyAttribute.cs
dotnet/src/SemanticKernel.Abstractions/Memory/RecordAttributes/VectorStoreRecordVectorAttribute.cs
dotnet/src/SemanticKernel.Abstractions/Memory/RecordDefinition/VectorStoreRecordProperty.cs
dotnet/src/SemanticKernel.UnitTests/Data/VectorStoreRecordPropertyReaderTests.cs

As part of the new vector store implementation, we need to allow developers to provide their own names or json serialization options for storage properties.
Adding support for this to AzureAISearch, Redis and Qdrant implementations in the following way:
AzureAISearch: via JsonPropertyName attributes or JsonSerializerOptions.
Redis: via JsonPropertyName attributes or JsonSerializerOptions.
Qdrant: via StoragePropertyName on VectorRecord definitions.

.Net: VectorStore: Add custom serialization options / naming support.

---

dotnet/src/SemanticKernel.Abstractions/Kernel.cs

.Net: update Kernel.cs

---

dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Core/AzureOpenAIChatMessageContentTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Core/AzureOpenAIChatMessageContent.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Services/AzureOpenAIChatCompletionService.cs

This PR fixes a small issue that would occur if the LLM started calling tools that are not functions. Additionally, it renames the `openAIClient` parameter of the `AzureOpenAIChatCompletionService` class constructor to `azureOpenAIClient` to keep the name consistent with its type. It also renames the `AzureOpenAIChatMessageContent.GetOpenAIFunctionToolCalls` method to `GetFunctionToolCalls` because the old one is not relevant anymore. The last two changes are breaking changes and it will be decided in the scope of the https://github.com/microsoft/semantic-kernel/issues/7053 issue whether to keep them or roll them back.

.Net: Tidying up AzureOpenAIChatCompletionService

---

dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Connectors.AzureOpenAI.UnitTests.csproj
dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Services/AzureOpenAITextToImageServiceTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Connectors.AzureOpenAI.csproj
dotnet/src/Connectors/Connectors.AzureOpenAI/Core/ClientCore.TextToImage.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Services/AzureOpenAITextToImageService.cs
dotnet/src/Connectors/Connectors.OpenAIV2/Services/OpenAIAudioToTextService.cs

This PR copies the `OpenAITextToImageService` class and related code, including unit tests, from the `Connectors.OpenAIV2` project to the `Connectors.AzureOpenAI` project. The copied classes have no functional changes; they have only been renamed to have the `Azure` prefix and placed into the corresponding `Microsoft.SemanticKernel.Connectors.AzureOpenAI` namespace. All the classes are temporarily excluded from the compilation process. This is done to simplify the code review of follow-up PR(s) that will include functional changes.
A few small fixes, unrelated to the main purpose of the PR, were made to the XML documentation comments and logging in the `OpenAIAudioToTextService` and `OpenAITextToImageService` classes.

.Net: Copy OpenAITextToImageService related code to AzureOpenAI project

---

dotnet/src/Connectors/Connectors.Memory.Milvus/MilvusMemoryStore.cs
dotnet/src/IntegrationTests/Connectors/Memory/Milvus/MilvusMemoryStoreTests.cs
python/poetry.lock

The `metricType` parameter in the `SearchAsync` method of the Milvus connector is incorrect.
It will always use the `SimilarityMetricType.Ip` for searching.
The current code hard-codes the milvus search metric type to `SimilarityMetricType.Ip`, which causes the issue where even if the Metric type is specified as `SimilarityMetricType.Cosine` when creating the `MilvusMemoryStore`, `SimilarityMetricType.IP` is still used during the search.
Issue:  [#7062](https://github.com/microsoft/semantic-kernel/issues/7062)

.Net: Fix milvus search metric type bug.

---

dotnet/Directory.Packages.props
dotnet/samples/Concepts/ChatCompletion/Google_GeminiChatCompletion.cs
dotnet/samples/Concepts/ChatCompletion/Google_GeminiChatCompletionStreaming.cs
dotnet/samples/Concepts/ChatCompletion/Google_GeminiVision.cs
dotnet/src/Connectors/Connectors.Google.UnitTests/Core/Gemini/Clients/GeminiChatGenerationTests.cs
dotnet/src/Connectors/Connectors.Google.UnitTests/Core/Gemini/Clients/GeminiChatStreamingTests.cs
dotnet/src/Connectors/Connectors.Google.UnitTests/Core/Gemini/GeminiRequestTests.cs
dotnet/src/Connectors/Connectors.Google/Core/Gemini/Clients/GeminiChatCompletionClient.cs
dotnet/src/Connectors/Connectors.Google/Core/Gemini/Models/GeminiRequest.cs
dotnet/src/IntegrationTests/Connectors/Google/Gemini/GeminiChatCompletionTests.cs
dotnet/src/IntegrationTests/testsettings.json

Finaly Google Gemini API is supporting system messages.
Added support one or multiple system messages.
Removed messages order limitation because google API not permitting this anymore.
(so Agents framework and handlebars planner now should work with Gemini! yeah!)
@RogerBarreto

.Net: Gemini added support of system messages and removed messages order limitation

---

dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Connectors.AzureOpenAI.UnitTests.csproj
dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Services/AzureOpenAITextToImageServiceTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/TestData/text-to-image-response.txt
dotnet/src/Connectors/Connectors.AzureOpenAI/Connectors.AzureOpenAI.csproj
dotnet/src/Connectors/Connectors.AzureOpenAI/Core/ClientCore.ChatCompletion.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Core/ClientCore.Embeddings.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Core/ClientCore.TextToImage.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Core/ClientCore.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Services/AzureOpenAITextEmbeddingGenerationService.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Services/AzureOpenAITextToImageService.cs

This PR migrates `AzureOpenAITextToImageService` to Azure.AI.OpenAI v2:  
1. It updates the previously added `AzureOpenAITextToImageService` to use `AzureOpenAIClient`.  
2. It replaces all constructors in the `AzureOpenAITextToImageService` with the relevant ones from the original `AzureOpenAITextToImageService`.  
3. It adds the `serviceVersion` parameter to the `ClientCore.GetAzureOpenAIClientOptions` methods, allowing the specification of the service API version.  
4. It updates XML documentation comments in a few classes to indicate their relevance to Azure OpenAI services.  
5. It adds unit tests for the `AzureOpenAITextToImageService` class.

.Net: Migrate AzureOpenAITextToImageService to Azure.AI.OpenAI v2

---

dotnet/src/Connectors/Connectors.AzureOpenAI/Connectors.AzureOpenAI.csproj
dotnet/src/Connectors/Connectors.AzureOpenAI/Core/ClientCore.TextToAudio.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Services/AzureOpenAITextToAudioService.cs

This PR copies the existing `AzureOpenAITextToAudioService` class from the `Connectors.OpenAI` project and `ClientCore.TextToAudio` class from `Connectors.OpenAIV2` to the `Connectors.AzureOpenAI` project. 
The copied classes have no functional changes; they have only been renamed to include the Azure prefix and placed into the corresponding Microsoft.SemanticKernel.Connectors.AzureOpenAI namespace. All the classes are temporarily excluded from the compilation process. This is done to simplify the code review of follow-up PR(s) that will include functional changes.

.Net: Copy AzureOpenAITextToAudioService related code to AzureOpenAI project

---

dotnet/samples/Concepts/Memory/TextMemoryPlugin_RecallJsonSerializationWithOptions.cs
dotnet/samples/Concepts/README.md
dotnet/src/Plugins/Plugins.Memory/TextMemoryPlugin.cs

When `TextMemoryPlugin` gets back multiple results from the memory store during recall, it uses json serialization to
turn these multiple results into a single string.
In some cases, this may cause unintended side-affects, e.g. when non-latin script is present in the results, `JsonSerializer` automatically escapes these characters.
Adding support for passing custom `JsonSerializerOptions` into the `TextMemoryPlugin` to customize the serialization behavior.
See #6593
Added optional `JsonSerializerOptions` to the `TextMemoryPlugin` constructor.
Added example to demonstrate this scenario.

.Net: Allow custom serialization options to be passed to TextMemoryPlugin.

---

docs/decisions/0046-kernel-content-graduation.md
dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Extensions/AzureOpenAIKernelBuilderExtensionsTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Extensions/AzureOpenAIKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Extensions/AzureOpenAIServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Services/AzureOpenAIChatCompletionService.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Services/AzureOpenAITextEmbeddingGenerationService.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Services/AzureOpenAITextToAudioService.cs
dotnet/src/Connectors/Connectors.OpenAIV2/Extensions/OpenAIKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.OpenAIV2/Extensions/OpenAIServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.OpenAIV2/Services/OpenAIAudioToTextService.cs
dotnet/src/Connectors/Connectors.OpenAIV2/Services/OpenAIFileService.cs
dotnet/src/Connectors/Connectors.OpenAIV2/Services/OpenAITextEmbbedingGenerationService.cs
dotnet/src/Connectors/Connectors.OpenAIV2/Services/OpenAITextToAudioService.cs

A few cosmetic improvements were identified while migrating {Azure}OpenAI services to Azure.AI.OpenAI SDK v2. This PR implements those improvements.

.Net: Clean-up

---

dotnet/src/Connectors/Connectors.AzureOpenAI/Connectors.AzureOpenAI.csproj
dotnet/src/Connectors/Connectors.AzureOpenAI/Core/ClientCore.AudioToText.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Services/AzureOpenAIAudioToTextService.cs

This PR copies existing AzureOpenAIAudioToTextService-related classes to the new Connectors.AzureOpenAI project as they are, with only the namespaces changed. The classes are temporarily excluded from the compilation process and will be included again in a follow-up PR. This is done to simplify the review process of the next PR.

.Net: Prepare AzureOpenAIAudioToTextService for migration to the Azure.AI.OpenAI SDK V2

---

docs/decisions/0046-kernel-content-graduation.md

All builds failing due to spellcheck violation: **serializeable** => **serializable**
Changed three instances of **serializeable** to **serializable**

ADR Bug - Fixed typo in ADR

---

dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Extensions/AzureOpenAIServiceCollectionExtensionsTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Extensions/AzureOpenAIServiceKernelBuilderExtensionsTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Services/AzureOpenAITextToAudioServiceTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Connectors.AzureOpenAI.csproj
dotnet/src/Connectors/Connectors.AzureOpenAI/Core/ClientCore.TextToAudio.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Extensions/AzureOpenAIKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Extensions/AzureOpenAIServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Services/AzureOpenAITextToAudioService.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Settings/AzureOpenAITextToAudioExecutionSettings.cs
dotnet/src/IntegrationTestsV2/Connectors/AzureOpenAI/AzureOpenAITextToAudioTests.cs

This PR migrates AzureOpenAITextToAudioService to Azure.AI.OpenAI SDK v2.
1. The new `AzureOpenAITextToAudioExecutionSettings` class is added to represent prompt execution settings for `AzureOpenAITextToAudioService`. Both `AzureOpenAITextToAudioService` classes that SK has today use the same prompt execution settings class - [OpenAITextToAudioExecutionSettings](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.OpenAI/TextToAudio/OpenAITextToAudioExecutionSettings.cs). This is a breaking change that is tracked in the issue - https://github.com/microsoft/semantic-kernel/issues/7053, and it will be decided later whether to proceed with the change or roll it back.
2. The `ClientCore.TextToAudio.cs` class is refactored to use the new …

.Net: Migrate AzureOpenAITextToAudioService to Azure.AI.OpenAI SDK v2

---

docs/decisions/0046-kernel-content-graduation.md
dotnet/src/SemanticKernel.Core/Data/VolatileVectorRecordStore.cs
dotnet/src/SemanticKernel.Core/Data/VolatileVectorRecordStoreOptions.cs
dotnet/src/SemanticKernel.UnitTests/Data/VolatileVectorRecordStoreTests.cs

We need an in memory implementation of new vector store design, so allow simple usage of the pattern without needing to have an external database.
This adds an In Memory / Volatile VectorRecordStore implementation and unit tests.

.Net: Adding volatile vector record store implementation.

---

dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Extensions/AzureOpenAIKernelBuilderExtensionsTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Extensions/AzureOpenAIServiceCollectionExtensionsTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Services/AzureOpenAIAudioToTextServiceTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Settings/AzureOpenAIAudioToTextExecutionSettingsTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Settings/AzureOpenAIPromptExecutionSettingsTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Settings/AzureOpenAITextToAudioExecutionSettingsTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Connectors.AzureOpenAI.csproj
dotnet/src/Connectors/Connectors.AzureOpenAI/Core/ClientCore.AudioToText.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Extensions/AzureOpenAIKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Extensions/AzureOpenAIServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Services/AzureOpenAIAudioToTextService.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Settings/AzureOpenAIAudioToTextExecutionSettings.cs
dotnet/src/IntegrationTestsV2/Connectors/AzureOpenAI/AzureOpenAIAudioToTextTests.cs

This PR migrates the `AzureOpenAIAudioToTextService` to Azure.AI.OpenAI SDK v2.
1. The existing `OpenAIAudioToTextExecutionSettings` class is copied to the new `Connectors.AzureOpenAI` project and renamed to `AzureOpenAIAudioToTextExecutionSettings` to represent prompt execution settings for the `AzureOpenAIAudioToTextService`.
2. The `OpenAIAudioToTextExecutionSettings.ResponseFormat` property type has changed from string to the `AudioTranscriptionFormat` enum, which is a breaking change that is tracked in the issue - https://github.com/microsoft/semantic-kernel/issues/70533.
3. The `ClientCore.AudioToText.cs` class is refactored to use the new `AzureOpenAIAudioToTextExecutionSettings` class and to handle the new type of `OpenAIAudioToTextExecutionSettings.ResponseFormat` property.
4. …

.Net: Migrate AzureOpenAIAudioToTextService to Azure.AI.OpenAI SDK v2

---

dotnet/src/Connectors/Connectors.OpenAIV2.UnitTests/Settings/OpenAIAudioToTextExecutionSettingsTests.cs
dotnet/src/Connectors/Connectors.OpenAIV2/Core/ClientCore.AudioToText.cs
dotnet/src/Connectors/Connectors.OpenAIV2/Settings/OpenAIAudioToTextExecutionSettings.cs

- Updates Execution Settings for `ResponseFormat` from `string` to `enum`.
- Updates the Unit Tests to validate.

.Net: OpenAI V2 - Audio to Text - Response Format as Enum conversion for format

---

python/mypy.ini
python/semantic_kernel/connectors/search_engine/bing_connector.py
python/semantic_kernel/connectors/search_engine/bing_connector_settings.py
python/semantic_kernel/connectors/search_engine/google_connector.py
python/semantic_kernel/connectors/search_engine/google_search_settings.py
python/semantic_kernel/connectors/utils/document_loader.py
python/tests/conftest.py
python/tests/unit/connectors/search_engine/test_bing_search_connector.py
python/tests/unit/connectors/search_engine/test_google_search_connector.py
python/tests/unit/connectors/utils/test_document_loader.py

We have mypy enabled on parts of the code base, but not all. The goal is to enable it across the entire SK python code. As part of this, we've broken up the work to tackle different sections. Additionally, we're working to improve the code coverage for these sections of code.
This PR:
- turns on mypy for the connector utils and the search connectors (Bing and Google). Small Code adjustments were made per mypy.
- other refactoring to make the code cleaner like using https AsyncClient, and better error handling around the API call.
- introduces Google Search settings for the connector.
- adds more unit test coverage for the document loader util and the Bing/Google search connectors. There is 100% code coverage.
- closes #7136

Python: Enable mypy for connector utils and search connectors. Improve code quality.

---

python/pyproject.toml
python/samples/getting_started/00-getting-started.ipynb
python/samples/getting_started/01-basic-loading-the-kernel.ipynb
python/samples/getting_started/02-running-prompts-from-file.ipynb
python/samples/getting_started/03-prompt-function-inline.ipynb
python/samples/getting_started/04-kernel-arguments-chat.ipynb
python/samples/getting_started/05-using-the-planner.ipynb
python/samples/getting_started/06-memory-and-embeddings.ipynb
python/samples/getting_started/07-hugging-face-for-plugins.ipynb
python/samples/getting_started/08-native-function-inline.ipynb
python/samples/getting_started/09-groundedness-checking.ipynb
python/samples/getting_started/10-multiple-results-per-prompt.ipynb
python/samples/getting_started/11-streaming-completions.ipynb
python/samples/getting_started/third_party/weaviate-persistent-memory.ipynb

Bump Python project version to 1.2.0 for a release.
Bump Python project version to 1.2.0 for a release.

Python: Bump Python project version to 1.2.0 for a release.

---

python/mypy.ini
python/semantic_kernel/connectors/ai/hugging_face/services/hf_text_completion.py
python/semantic_kernel/connectors/ai/hugging_face/services/hf_text_embedding.py
python/tests/unit/connectors/hugging_face/test_hf_text_completions.py
python/tests/unit/connectors/hugging_face/test_hf_text_embedding.py

We have mypy enabled on parts of the code base, but not all. The goal is to enable it across the entire SK python code. As part of this, we've broken up the work to tackle different sections. Additionally, we're working to improve the unit test code coverage for these sections of code.
This PR:
- turns on mypy for the HuggingFace connector
- adds more unit test coverage for the text completion and embeddings connector to achieve >95% code coverage.
- closes #7133

Python: Enable mypy for the HuggingFace connectors. Increase unit test code coverage.

---

dotnet/Directory.Packages.props
dotnet/src/Connectors/Connectors.AzureAISearch.UnitTests/AzureAISearchVectorRecordStoreTests.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorRecordStore.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorRecordStoreOptions.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorRecordStore.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorRecordStoreOptions.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorRecordStore.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorRecordStoreOptions.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantVectorRecordStoreTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisVectorRecordStoreTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorRecordStoreTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorRecordStoreTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisVectorRecordStoreTests.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordOptions/DeleteRecordOptions.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordOptions/GetRecordOptions.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordOptions/UpsertRecordOptions.cs
dotnet/src/SemanticKernel.Core/Data/VolatileVectorRecordStore.cs
dotnet/src/SemanticKernel.Core/Data/VolatileVectorRecordStoreOptions.cs
dotnet/src/SemanticKernel.UnitTests/Data/VolatileVectorRecordStoreTests.cs

As part of the new vector store design, we have decided to follow a pattern where each vector record store instance is tied to a single collection and we will have a separate factory interface for getting instances by collection name.
- Removing optional collection names from all options classes.
- Adding mandatory collection name to vector record store constructors.

.Net: Switching all vector record store instances to be tied to a single collection

---

.github/workflows/python-test-coverage.yml
.github/workflows/python-unit-tests.yml
python/semantic_kernel/contents/chat_message_content.py
python/semantic_kernel/contents/function_call_content.py
python/semantic_kernel/contents/function_result_content.py
python/semantic_kernel/contents/streaming_chat_message_content.py
python/semantic_kernel/contents/text_content.py
python/tests/integration/completions/test_chat_completions.py
python/tests/integration/completions/test_text_completion.py
python/tests/unit/contents/test_chat_message_content.py
python/tests/unit/contents/test_function_call.py
python/tests/unit/contents/test_function_result_content.py
python/tests/unit/contents/test_streaming_chat_message_content.py
python/tests/unit/kernel/test_kernel.py

Fix #6932
Added ability to supply function_name and plugin_name as well as name (name keeps precedence)
Added ability to supply arguments as a dict, instead of string.
Also ups the test coverage for the contents folder.

Python: allow more options for FunctionCallContent constructor

---

.github/workflows/python-test-coverage.yml
.github/workflows/python-unit-tests.yml
python/semantic_kernel/connectors/ai/prompt_execution_settings.py
python/tests/unit/connectors/test_prompt_execution_settings.py

Adds unit test run only for ubuntu for python 3.13, should not fail full job when it does fail.
Slight improvement of filename handling for the coverage.

Python: add experimental unit tests for python 3.13

---

dotnet/samples/Concepts/Agents/ComplexChat_NestedShopper.cs
dotnet/samples/Concepts/Agents/MixedChat_Agents.cs
dotnet/samples/Concepts/Agents/OpenAIAssistant_ChartMaker.cs
dotnet/samples/Concepts/Agents/OpenAIAssistant_CodeInterpreter.cs
dotnet/samples/Concepts/Agents/OpenAIAssistant_FileManipulation.cs
dotnet/samples/Concepts/Agents/OpenAIAssistant_Retrieval.cs
dotnet/samples/GettingStartedWithAgents/Step1_Agent.cs
dotnet/samples/GettingStartedWithAgents/Step2_Plugins.cs
dotnet/samples/GettingStartedWithAgents/Step3_Chat.cs
dotnet/samples/GettingStartedWithAgents/Step4_KernelFunctionStrategies.cs
dotnet/samples/GettingStartedWithAgents/Step5_JsonResult.cs
dotnet/samples/GettingStartedWithAgents/Step6_DependencyInjection.cs
dotnet/samples/GettingStartedWithAgents/Step7_Logging.cs
dotnet/samples/GettingStartedWithAgents/Step8_OpenAIAssistant.cs

Noticed some inconsistencies and opportunities for clarity.
- Removed usage of `var`
- Replaced incorrect comment for history creation for Step1 & Step2 _(GettingStartedWithAgents)_
- Appending result content to history for Step1 & Step2 _(GettingStartedWithAgents)_
- Replaced incorrect comment for thread creation for Step8 _(GettingStartedWithAgents)_

.Net Agent - Cosmetic Sample Updates

---

python/semantic_kernel/connectors/ai/chat_completion_client_base.py
python/semantic_kernel/connectors/ai/embeddings/embedding_generator_base.py
python/semantic_kernel/connectors/ai/hugging_face/services/hf_text_embedding.py
python/semantic_kernel/connectors/ai/open_ai/services/open_ai_handler.py
python/semantic_kernel/connectors/ai/open_ai/services/open_ai_text_embedding_base.py
python/semantic_kernel/connectors/ai/text_completion_client_base.py
python/tests/unit/connectors/open_ai/services/test_openai_text_embedding.py

Adds singular get_..._content methods to all services, initially implemented by calling the multi version and passing back the first result, it therefore does not check on the number of responses parameter, just provides the interface.
Also add `generate_raw_embeddings` to Embedding Base to allow models to return different types, while keeping generate_embeddings to return a numpy array.
Fixes #6926

Python: added singular get methods

---

.github/workflows/python-test-coverage.yml

Python: remove continue on error on steps

---

dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Services/AzureOpenAIAudioToTextServiceTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Core/ClientCore.AudioToText.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Settings/AzureOpenAIAudioToTextExecutionSettings.cs
dotnet/src/Connectors/Connectors.OpenAIV2.UnitTests/Services/OpenAIAudioToTextServiceTests.cs
dotnet/src/Connectors/Connectors.OpenAIV2/Core/ClientCore.AudioToText.cs
dotnet/src/Connectors/Connectors.OpenAIV2/Settings/OpenAIAudioToTextExecutionSettings.cs

The new Azure.AI.OpenAI V2 introduced timestamp granularities for the audio-to-text API. This PR removes the first attempt to expose the settings in execution settings for the service. The setting will be introduced later after the migration is over in scope in this task: https://github.com/microsoft/semantic-kernel/issues/7213.

.Net: Remove time stamp granularities 

---

docs/decisions/0046-kernel-content-graduation.md
dotnet/Directory.Packages.props
dotnet/src/Connectors/Connectors.Ollama.UnitTests/Connectors.Ollama.UnitTests.csproj
dotnet/src/Connectors/Connectors.Ollama/Core/ServiceBase.cs
dotnet/src/Connectors/Connectors.Ollama/Extensions/OllamaKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Ollama/Extensions/OllamaServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.Ollama/OllamaMetadata.cs
dotnet/src/Connectors/Connectors.Ollama/OllamaPromptExecutionSettings.cs
dotnet/src/Connectors/Connectors.Ollama/Services/OllamaChatCompletionService.cs
dotnet/src/Connectors/Connectors.Ollama/Services/OllamaTextEmbeddingGenerationService.cs
dotnet/src/Connectors/Connectors.Ollama/Services/OllamaTextGenerationService.cs
dotnet/src/IntegrationTests/Connectors/Ollama/OllamaCompletionTests.cs
dotnet/src/IntegrationTests/Connectors/Ollama/OllamaTextEmbeddingTests.cs
dotnet/src/IntegrationTests/Connectors/Ollama/OllamaTextGenerationTests.cs
dotnet/src/IntegrationTests/IntegrationTests.csproj
dotnet/src/IntegrationTests/TestSettings/OllamaConfiguration.cs

- Integration Tests added
- Metadata generated with new client result data
- Adjustments in parameter names, following SK convention.

.Net: Ollama Connector : Added metadata, integration tests + more adjustments

---

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorRecordStore.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordMapper.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorRecordStoreTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreFixture.cs
dotnet/src/InternalUtilities/src/Data/VectorStoreRecordPropertyReader.cs
dotnet/src/SemanticKernel.UnitTests/Data/VectorStoreRecordPropertyReaderTests.cs

Supporting complex types is difficult in Azure AI Search for create via the abstraction, so for now, removing support for it, until someone requests it.
This means doing type checking on data fields, so adding better support for enumerable types like Arrays, List<T>, IEnumerable<T>, etc.

.Net: Improve support for enumerable types and remove complex object support from azure ai search.

---

docs/decisions/0045-updated-vector-store-design.md
dotnet/src/Connectors/Connectors.AzureAISearch.UnitTests/AzureAISearchVectorStoreRecordCollectionTests.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchRecordMapperType.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreRecordCollectionOptions.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantRecordMapperType.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordCollectionOptions.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisRecordMapperType.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStoreRecordCollectionOptions.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantVectorStoreRecordCollectionTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreFixture.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisVectorStoreRecordCollectionTests.cs
dotnet/src/SemanticKernel.Abstractions/Data/IVectorStoreRecordCollection.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordOptions/DeleteRecordOptions.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordOptions/GetRecordOptions.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordOptions/UpsertRecordOptions.cs
dotnet/src/SemanticKernel.Core/Data/VolatileVectorStoreRecordCollection.cs
dotnet/src/SemanticKernel.Core/Data/VolatileVectorStoreRecordCollectionOptions.cs
dotnet/src/SemanticKernel.UnitTests/Data/VolatileVectorStoreRecordCollectionTests.cs

After long discussion we decided to move to a model whereby we have a VectorStore that can provide VectorStoreRecordCollection instances.  All record and collection specific operations will reside on VectorStoreRecordCollection and all cross collection operations will reside on VectorStore.
This change renames VectorRecordStore to VectorStoreRecordCollection as agreed.
The required collection operations will be moved to VectorStoreRecordCollection in a separate pr.

.Net: Rename VectorRecordStore to VetorStoreRecordCollection

---

.github/workflows/python-test-coverage.yml
dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeMemoryStore.cs
dotnet/src/Connectors/Connectors.UnitTests/Memory/Pinecone/PineconeMemoryStoreTests.cs

To optimize the code by reducing the number of HTTP requests needed to remove a list of keys from a namespace. Instead of multiple HTTP calls, a single HTTP call will now handle the removal.
Previously, RemoveBatchFromNamespaceAsync executed multiple HTTP calls to remove keys. This optimized code reduces the overhead by executing a single HTTP request to remove the list of keys.

.Net: Pinecone RemoveBatchFromNamespaceAsync method performance optimization

---

dotnet/src/Connectors/Connectors.Memory.DuckDB/Database.cs
dotnet/src/Connectors/Connectors.Memory.DuckDB/DuckDBMemoryStore.cs

To optimize performance by reducing the number of database calls during batch deletions in DuckDBMemoryStore.
The updated **RemoveBatchAsync** method now executes a single SQL DELETE query to remove multiple keys at once, replacing the previous approach of executing individual delete queries for each key.

.Net: DuckDBMemoryStore RemoveBatchAsync method performance improvement

---

dotnet/src/Connectors/Connectors.AzureAISearch.UnitTests/AzureAISearchVectorStoreRecordCollectionTests.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/MockableQdrantClient.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantVectorStoreRecordCollectionTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisVectorStoreRecordCollectionTests.cs
dotnet/src/SemanticKernel.Abstractions/Data/IVectorStoreRecordCollection.cs
dotnet/src/SemanticKernel.Core/Data/VolatileVectorStoreRecordCollection.cs
dotnet/src/SemanticKernel.UnitTests/Data/VolatileVectorStoreRecordCollectionTests.cs

As part of the memory connector redesign we have fixed on a design where we have a VectorStore that produces VectorStoreRecordCollection instances.  These are tied to a collection and will expose single collection operations.
This PR adds some of the single collection operations to the VectorStoreRecordCollection, namely:
1. CollectionExists
2. DeleteCollection
As well as exposing the name of the collection.

.Net: Adding collectionName, exists and delete to collection interface

---

dotnet/src/Connectors/Connectors.AzureAISearch.UnitTests/AzureAISearchVectorStoreCollectionCreateMappingTests.cs
dotnet/src/Connectors/Connectors.AzureAISearch.UnitTests/AzureAISearchVectorStoreRecordCollectionTests.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreCollectionCreateMapping.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreRecordCollection.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreFixture.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreRecordCollectionTests.cs
dotnet/src/InternalUtilities/src/Data/VectorStoreRecordPropertyReader.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordAttributes/VectorStoreRecordDataAttribute.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordAttributes/VectorStoreRecordVectorAttribute.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordDefinition/DistanceFunction.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordDefinition/IndexKind.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordDefinition/VectorStoreRecordDataProperty.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordDefinition/VectorStoreRecordVectorProperty.cs
dotnet/src/SemanticKernel.UnitTests/Data/VectorStoreRecordPropertyReaderTests.cs

This PR adds:
- The ability to create Azure AI Search collections
- Additional properties to the attributes and record definitions to support vector configuration and index creation.
- Code to parse and map those new properties
I'll update the IVectorStoreRecordCollection interface with the CreateCollection and CreateCollectionIfNotExists methods once I've added create to more implementations, to avoid having one very large pr.

.Net: Adding Azure AI Search CollectionCreate

---

.github/_typos.toml
dotnet/src/Connectors/Connectors.AzureOpenAI/Core/ClientCore.ChatCompletion.cs
dotnet/src/Connectors/Connectors.OpenAIV2/Core/ClientCore.ChatCompletion.cs
dotnet/src/IntegrationTestsV2/Connectors/AzureOpenAI/AzureOpenAIChatCompletion_FunctionCallingTests.cs
dotnet/src/IntegrationTestsV2/Connectors/OpenAI/OpenAIChatCompletion_FunctionCallingTests.cs
dotnet/src/IntegrationTestsV2/TestData/serializedChatHistoryV1_15_1.json

This PR adds a few integration tests to ensure that the chat history, filled by existing {Azure}OpenAI chat completion connectors and serialized, is backward-compatible with the migrated {Azure}OpenAI chat completion connectors, so it can be deserialized and used as is.
Additionally, this PR fixes the issue caused by using the wrong constructor of the `AssistantChatMessage` class. A corresponding integration test is added to test this scenario.
Closes: https://github.com/microsoft/semantic-kernel/issues/7055

.Net: Chat history serialization test + bug fix

---

dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStoreCollectionCreateMapping.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisVectorStoreCollectionCreateMappingTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisVectorStoreFixture.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisVectorStoreRecordCollectionTests.cs

This PR contains:
- The ability to create Redis collections

.Net: Add redis collection create support.

---

dotnet/src/SemanticKernel.Abstractions/Data/IVectorStoreRecordCollection.cs
dotnet/src/SemanticKernel.Core/Data/VolatileVectorStoreRecordCollection.cs
dotnet/src/SemanticKernel.UnitTests/Data/VolatileVectorStoreRecordCollectionTests.cs

This PR contains:
- The ability to create Volatile collections
- Updating the abstraction to include the new methods.
With this pr, all implementations now support create.

.Net: Add CreateCollection to Volatile vectorstore and abstraction

---

dotnet/src/SemanticKernel.Abstractions/Data/IVectorStore.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordAttributes/VectorStoreRecordDataAttribute.cs
dotnet/src/SemanticKernel.Core/Data/VolatileVectorStore.cs
dotnet/src/SemanticKernel.UnitTests/Data/VolatileVectorStoreTests.cs

This PR adds:
- The new IVectorStore interface that can serve collection instances and list collection names.
- An in memory (Volatile) implementation of the new interface.

.Net: Add IVectorStore interface and Volatile implementation

---

python/samples/concepts/auto_function_calling/chat_gpt_api_function_calling.py
python/semantic_kernel/functions/kernel_function_decorator.py
python/semantic_kernel/functions/kernel_function_from_method.py
python/tests/conftest.py
python/tests/unit/functions/test_kernel_function_decorators.py
python/tests/unit/functions/test_kernel_function_from_method.py
python/tests/unit/kernel/test_kernel.py
python/tests/unit/planners/function_calling_stepwise_planner/test_function_calling_stepwise_planner.py
python/tests/unit/planners/test_planner_extensions.py

The current kernel function decorator class parses function params, but had a miss related to how the underlying param's type is parsed if not using Annotations. 
This PR properly handles the type_object for params that don't using typing.Annotations.
- Adds unit tests to exercise the code.
- Adds more kernel.py unit tests for near 100% test coverage.
- Adds some planner tests to improve the test coverage.
- Closes #7300

Python: fix for kernel function type_object when not using Annotations. Add more unit tests.

---

dotnet/src/Connectors/Connectors.AzureAISearch.UnitTests/AzureAISearchVectorStoreTests.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreOptions.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/IAzureAISearchVectorStoreRecordCollectionFactory.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreTests.cs

This pr adds
- A IVectorStore implementation for AzureAISearch

.Net: Adding VectorStore for Azure AI Search.

---

dotnet/src/Connectors/Connectors.Memory.Redis/IRedisVectorStoreRecordCollectionFactory.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStoreOptions.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisVectorStoreTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisVectorStoreTests.cs
dotnet/src/SemanticKernel.Abstractions/Data/IVectorStoreRecordCollection.cs

This pr adds:
- An IVectorStore implementation for Redis

.Net: Adding VectorStore for Redis.

---

dotnet/samples/Concepts/Agents/ComplexChat_NestedShopper.cs
dotnet/samples/Concepts/Agents/Legacy_AgentCharts.cs
dotnet/samples/Concepts/Agents/Legacy_AgentTools.cs
dotnet/samples/Concepts/Agents/OpenAIAssistant_FileManipulation.cs
dotnet/samples/Concepts/Agents/OpenAIAssistant_FileService.cs
dotnet/samples/Concepts/Agents/OpenAIAssistant_Retrieval.cs
dotnet/samples/Concepts/Concepts.csproj
dotnet/src/Experimental/Agents/Experimental.Agents.csproj
dotnet/src/Experimental/Agents/Extensions/OpenAIRestExtensions.cs

This PR migrates the remaining samples related to agents to the new {Azure}OpenAI services.
The agent samples will be updated again by this PR - https://github.com/microsoft/semantic-kernel/pull/7126 to use {Azure}OpenAI SDKs for operations with files and not use the deprecated file service. CC: @crickman

.Net: Migrate remaining samples to new {Azure}OpenAI services

---

dotnet/src/Connectors/Connectors.Memory.Qdrant/IQdrantVectorStoreRecordCollectionFactory.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreOptions.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordMapper.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantVectorStoreRecordMapperTests.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantVectorStoreTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorStoreTests.cs

This pr adds:
- An IVectorStore implementation for Qdrant
- Fix a bug in the mapping where using the json parser to create the caller object model needs json property names in order to correctly deserialize the json object.

.Net: Adding a VectorStore implementation for Qdrant

---

python/semantic_kernel/connectors/ai/azure_ai_inference/services/azure_ai_inference_base.py
python/semantic_kernel/connectors/ai/azure_ai_inference/services/azure_ai_inference_chat_completion.py
python/semantic_kernel/connectors/ai/azure_ai_inference/services/azure_ai_inference_text_embedding.py
python/semantic_kernel/connectors/telemetry.py
python/tests/unit/connectors/azure_ai_inference/services/test_azure_ai_inference_chat_completion.py
python/tests/unit/connectors/azure_ai_inference/services/test_azure_ai_inference_text_embedding.py
python/tests/unit/telemetry/test_user_agent.py

All Microsoft tools/SDKs that internally use the Azure AI Inference SDK are required to set a unique application ID, which will be part of the "use-agent" HTTP request header. This will allow teams to track usage from that tool/SDK, using service-side telemetry dashboards.
Semantic Kernel's application ID is registered as "semantic-kernel-python/{version}" according to this [list](https://microsoft.sharepoint.com/:x:/t/AzureMLExperiences-AgentsandCommonInferenceSDKteam/EUVgsgpFtdRLnkhxrdtJ1MIBDMl3wVfoza4c13MI_K6ywg?e=MEpwyo&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Ctaochen%40microsoft.com&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI0OS8yNDA2MjcyNDgwNyJ9).
Add "semantic-kernel-python/{version}" as the application ID where we use the Azure AI Inference SDK.

Python: Add application ID for Azure AI Inference

---

.pre-commit-config.yaml
python/poetry.lock
python/pyproject.toml

Based on #7274, bumping ruff to 0.5.2. Required a manual PR as the pre-commit.yaml file needs an update.
Based on #7274, bumping ruff to 0.5.2. Required a manual PR as the pre-commit.yaml file needs an update.

Python: Bump ruff from 0.5.1 to 0.5.2

---

dotnet/src/SemanticKernel.Core/Data/VolatileVectorStore.cs
dotnet/src/SemanticKernel.Core/Data/VolatileVectorStoreRecordCollection.cs
dotnet/src/SemanticKernel.UnitTests/Data/VolatileVectorStoreRecordCollectionTests.cs

The VolatileVectorStore uses a ConcurrentDictionary of ConcurrentDictionary instances to store records. Each collection can contain different types of records.  It's not possible to cast the entire sub dictionary to the right generic type, so switching to casing on a per record basis.
Fixing bug where casting at the dictionary level was causing a null reference exception.

.Net: Fix casting bug in VolatileVectorStore

---

dotnet/src/Functions/Functions.OpenApi/OpenApiKernelPluginFactory.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/OpenApiKernelPluginFactoryTests.cs

.Net: Handle missing operation id in OpenApi spec

---

dotnet/src/Connectors/Connectors.AzureAISearch.UnitTests/AzureAISearchKernelBuilderExtensionsTests.cs
dotnet/src/Connectors/Connectors.AzureAISearch.UnitTests/AzureAISearchServiceCollectionExtensionsTests.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantKernelBuilderExtensionsTests.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantServiceCollectionExtensionsTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisKernelBuilderExtensionsTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisServiceCollectionExtensionsTests.cs
dotnet/src/SemanticKernel.Core/Data/KernelBuilderExtensions.cs
dotnet/src/SemanticKernel.Core/Data/ServiceCollectionExtensions.cs
dotnet/src/SemanticKernel.UnitTests/Data/KernelBuilderExtensionsTests.cs
dotnet/src/SemanticKernel.UnitTests/Data/ServiceCollectionExtensionsTests.cs

As part of the memory connector redesign, we are adding new VectorStore classes.  These should be easy to add to service collections both on the Kernel or outside.
Adding KernelBuilder and ServiceCollection extension methods to register VectorStore instances for each of the VectorStore implementations, and adding unit tests for these as well.

.Net: Add basic KernelBuilder and ServiceCollection extensions for registering VectorStores.

---

dotnet/samples/Demos/ContentSafety/ContentSafety.csproj
dotnet/samples/Demos/StepwisePlannerMigration/Controllers/AutoFunctionCallingController.cs
dotnet/samples/Demos/StepwisePlannerMigration/Controllers/StepwisePlannerController.cs
dotnet/samples/Demos/StepwisePlannerMigration/Extensions/ConfigurationExtensions.cs
dotnet/samples/Demos/StepwisePlannerMigration/Plugins/TimePlugin.cs
dotnet/samples/Demos/StepwisePlannerMigration/Program.cs
dotnet/samples/Demos/StepwisePlannerMigration/Services/PlanProvider.cs
dotnet/samples/Demos/StepwisePlannerMigration/StepwisePlannerMigration.csproj
dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Settings/AzureOpenAIPromptExecutionSettingsTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Core/ClientCore.AudioToText.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Core/ClientCore.ChatCompletion.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Core/ClientCore.TextToAudio.cs
dotnet/src/Connectors/Connectors.OpenAIV2.UnitTests/Settings/OpenAIPromptExecutionSettingsTests.cs
dotnet/src/Connectors/Connectors.OpenAIV2/Core/ClientCore.AudioToText.cs
dotnet/src/Connectors/Connectors.OpenAIV2/Core/ClientCore.TextToAudio.cs
dotnet/src/Connectors/Connectors.OpenAIV2/Settings/OpenAIAudioToTextExecutionSettings.cs
dotnet/src/Connectors/Connectors.OpenAIV2/Settings/OpenAIPromptExecutionSettings.cs
dotnet/src/Connectors/Connectors.OpenAIV2/Settings/OpenAITextToAudioExecutionSettings.cs
dotnet/src/IntegrationTestsV2/Connectors/AzureOpenAI/AzureOpenAIChatCompletion_FunctionCallingTests.cs
dotnet/src/IntegrationTestsV2/Connectors/AzureOpenAI/AzureOpenAITextEmbeddingTests.cs
dotnet/src/IntegrationTestsV2/Connectors/OpenAI/OpenAIChatCompletion_FunctionCallingTests.cs
dotnet/src/IntegrationTestsV2/TestHelpers.cs

Resolve #7111 
As part of this update all the previous enforeced/default settings from OpenAI and AzureOpenAI connectors are now optional, not sending any non-defined information to the server side API, leaving the underlying API to resolve its default value.
As a small add up to this PR I also added fixes to our Integration Tests when executing against Parallel Function Calling capable models.

.Net: OpenAI V2 Optional Settings

---

dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerClient.cs

Moved to use Latin1_General_100_BIN2 which is more compatible and updaed
Updated the collation in the "create table" statement
- [ x I didn't break anyone :smile:

.Net: using a more modern and compatible collation

---

dotnet/src/Connectors/Connectors.AzureAISearch.UnitTests/AzureAISearchVectorStoreCollectionCreateMappingTests.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreCollectionCreateMapping.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStoreCollectionCreateMapping.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantVectorStoreRecordCollectionTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisJsonVectorStoreRecordCollectionTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisVectorStoreCollectionCreateMappingTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisJsonVectorStoreRecordCollectionTests.cs

For some connectors users can use `JsonPropertyName` to indicate that a different name should be used in storage than on the model.  In other cases users can use `StoragePropertyName` in the definition.  We need to use this information when creating indexes / collections to name the properties in storage correctly, otherwise there will be a mismatch when reading/writing.
1. Updating create logic to use the right storage or json property names everywhere.
2. Adding tests to specifically cover these scenarios.

.Net: Fix collection create field naming bug and add tests to cover scenario.

---

dotnet/src/Connectors/Connectors.Memory.Redis/RedisHashSetVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisHashSetVectorStoreRecordCollectionOptions.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisHashSetVectorStoreRecordMapper.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisStorageType.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStoreOptions.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisHashSetVectorStoreRecordCollectionTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisHashSetVectorStoreRecordMapperTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisVectorStoreTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisHashSetVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisVectorStoreFixture.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisVectorStoreTests.cs

Redis supports two modes when storing vectors, one with hash sets and one with JSON.
Both the commands used and the way in which data is communicated to redis is diferent between the two modes, so we have a different collection implementation and a different mapper implementation.
This PR adds support for also using the HashSets mode in Redis, in addition to the JSON mode that is already supported, with unit tests and integration tests.

.Net: Add support for redis hashsets.

---

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.UnitTests/Memory/Pinecone/PineconeKernelBuilderExtensionsTests.cs
dotnet/src/Connectors/Connectors.UnitTests/Memory/Pinecone/PineconeServiceCollectionExtensionsTests.cs

Adding DI extensions for the new Pinecone VectorStore implementation.
Reordering the parameters for all VectorStore DI extensions so that ServiceId is last.  This reduces the risk of ambiguous method signatures where we have to have multiple method overloads, since options is now before the serviceId, meaning that any optional string parameters to construct a client will not clash with the optional serviceId.

.Net: VectorStore: Add DI extensions for Pinecone and reorder params for others.

---

dotnet/samples/Concepts/Memory/VectorStore_DataIngestion.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantVectorStoreRecordMapperTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisJsonVectorStoreRecordMapperTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreFixture.cs
dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorStoreFixture.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisVectorStoreFixture.cs
dotnet/src/InternalUtilities/src/Data/VectorStoreRecordPropertyReader.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordAttributes/VectorStoreRecordDataAttribute.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordDefinition/VectorStoreRecordDataProperty.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordDefinition/VectorStoreRecordKeyProperty.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordDefinition/VectorStoreRecordProperty.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordDefinition/VectorStoreRecordVectorProperty.cs
dotnet/src/SemanticKernel.UnitTests/Data/VectorStoreRecordPropertyReaderTests.cs

We decided to delay the automatic embedding generation until later, so any attributes related to embedding generation are not required for the time being, but can be added back easily later.
Removed HasEmbedding and EmbeddingPropertyName from record definition and attributes.
Fixed a small bug with definition cloning.

.Net: Removing embedding generation attributes and fixing cloning bug.

---

dotnet/samples/Concepts/Memory/VectorStoreFixtures/VectorStoreQdrantContainerFixture.cs
dotnet/samples/Concepts/Memory/VectorStoreFixtures/VectorStoreRedisContainerFixture.cs
dotnet/samples/Concepts/Memory/VectorStore_DataIngestion.cs

Addressing feedback on data ingestion sample from bugbash.  See: [#7475](https://github.com/microsoft/semantic-kernel/issues/7475)
Removing .Result that slipped in accidentally.
Only starting docker containers if test requires it.
Remove parallel foreach in favour of whenall.
Add example without dependency injection.

.Net: Add a few improvements to data ingestion sample.

---

dotnet/src/Connectors/Connectors.AzureAISearch.UnitTests/AzureAISearchVectorStoreRecordCollectionTests.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonVectorStoreRecordMapper.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisJsonVectorStoreRecordCollectionTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisJsonVectorStoreRecordMapperTests.cs

Both Redis and AzureAISearch uses Json as its serialization mechanism, however in various places, the field names in storage need to be used by the rest of the code.
E.g. to determine the names of properties when creating an index
- Adding tests to ensure all scenarios are covered
- Fix bugs where there are gaps

.Net: Fix bug where JsonSerializerOptions is not consistently used.

---

dotnet/samples/Concepts/Memory/VectorStore_DataIngestion.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/IAzureAISearchVectorStoreRecordCollectionFactory.cs
dotnet/src/Connectors/Connectors.Memory.Pinecone/IPineconeVectorStoreRecordCollectionFactory.cs
dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/IQdrantVectorStoreRecordCollectionFactory.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.Redis/IRedisVectorStoreRecordCollectionFactory.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStore.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Pinecone/PineconeVectorStoreTests.cs
dotnet/src/SemanticKernel.Abstractions/Data/IVectorStore.cs
dotnet/src/SemanticKernel.Abstractions/Data/IVectorStoreRecordCollection.cs
dotnet/src/SemanticKernel.Core/Data/VolatileVectorStore.cs
dotnet/src/SemanticKernel.Core/Data/VolatileVectorStoreRecordCollection.cs
dotnet/src/SemanticKernel.Core/Data/VolatileVectorStoreRecordCollectionOptions.cs
dotnet/src/SemanticKernel.UnitTests/Data/VolatileVectorStoreRecordCollectionTests.cs
dotnet/src/SemanticKernel.UnitTests/Data/VolatileVectorStoreTests.cs

Addressing feedback on Volatile VectorStore key types from bugbash.  See:
[#7468](https://github.com/microsoft/semantic-kernel/issues/7468)
- Adding support for any key type to VolatileVectorStore.
- Updated VolatileVectorStore unit tests to test with multiple types of keys.
- This also caused a knock-on effect of requiring keys to not be nullable, which is a good constraint to have regardless.

.Net: Add support for any key type to the VolatileVectorStore.

---

python/semantic_kernel/contents/function_result_content.py
python/tests/unit/contents/test_chat_history.py
python/tests/unit/contents/test_function_result_content.py

Fix #7340
This adds a serializer to the FunctionResultContent for the result field.
Before SK 1.2 all results where stored as string using `str(value)`, after that was changed to Any, to allow more complex types to be stored with full details.
This changes things back to that behavior for serialization by adding a pydantic field_serializer for that field which uses the same method (`str(value)`). Further this allows one to subclass FunctionResultContent and overwrite the built-in serializer with your own.

Python: serialize the result as string, consistent with behavior before 1.2

---

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreCollectionCreateMapping.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeVectorStoreCollectionCreateMapping.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreCollectionCreateMapping.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStoreCollectionCreateMapping.cs
dotnet/src/InternalUtilities/src/Data/VectorStoreRecordPropertyReader.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordDefinition/VectorStoreRecordProperty.cs
dotnet/src/SemanticKernel.UnitTests/Data/VectorStoreRecordPropertyReaderTests.cs

The writability of properties on VectorStoreRecordProperty wasn't great and the naming of the data model property name wasn't appropriately differentiated from the storage property name.
See issue for more info:
[#7469](https://github.com/microsoft/semantic-kernel/issues/7469)
- Make properties read-only or init only.
- Rename PropertyName to DataModelPropertyName to better differentiate it from the StoragePropertyName

.Net: Restricting property writability and renaming data model name property on VectorStoreRecordProperty

---

python/samples/concepts/memory/new_memory.py
python/semantic_kernel/connectors/memory/redis/redis_store.py
python/semantic_kernel/connectors/memory/volatile/volatile_collection.py
python/semantic_kernel/connectors/memory/volatile/volatile_store.py
python/tests/unit/connectors/memory/test_volatile.py

Adds volatile store and collection using the new model.

Python: Volatile memory store

---

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeVectorStoreRecordMapper.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordMapper.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisHashSetVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonVectorStoreRecordCollection.cs
dotnet/src/InternalUtilities/src/Data/VectorStoreRecordPropertyReader.cs
dotnet/src/SemanticKernel.UnitTests/Data/VectorStoreRecordPropertyReaderTests.cs

As per https://github.com/dotnet/runtime/issues/27939#issuecomment-531420515, small formatting improvements to use PascalCase for tuple return variables. In this case, the usage of such variables will be similar to C# property naming conventions (e.g. `properties.KeyProperty` instead of `properties.keyProperty`)

.Net: [Feature branch] Small formatting improvements

---

dotnet/samples/Concepts/Memory/VectorStoreFixtures/VectorStoreQdrantContainerFixture.cs
dotnet/samples/Concepts/Memory/VectorStore_DataIngestion_CustomMapper.cs
dotnet/samples/Concepts/Memory/VectorStore_DataIngestion_MultiStore.cs
dotnet/samples/Concepts/Memory/VectorStore_DataIngestion_Simple.cs
dotnet/samples/Concepts/README.md

Adding two more examples for the VectorStore functionality:
- A super simple example, showing just the most basic of functionality, that's easier to get started with.
- An example which shows how to use a custom mapper for a case where your storage model and data model doesn't match or you need to optimize mapping.

.Net: VectorStore: Adding a simple example a custom mapper example.

---

python/semantic_kernel/connectors/memory/azure_ai_search/utils.py
python/semantic_kernel/connectors/memory/redis/utils.py
python/semantic_kernel/data/vector_store_record_fields.py

is full text searchable option for vector store data record fields.

Python: added is_full_text_searchable option

---

dotnet/src/SemanticKernel.Abstractions/Data/RecordAttributes/VectorStoreRecordDataAttribute.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordAttributes/VectorStoreRecordKeyAttribute.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordAttributes/VectorStoreRecordVectorAttribute.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordDefinition/DistanceFunction.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordDefinition/IndexKind.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordDefinition/VectorStoreRecordDataProperty.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordDefinition/VectorStoreRecordDefinition.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordDefinition/VectorStoreRecordKeyProperty.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordDefinition/VectorStoreRecordProperty.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordDefinition/VectorStoreRecordVectorProperty.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordOptions/DeleteRecordOptions.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordOptions/GetRecordOptions.cs
dotnet/src/SemanticKernel.Abstractions/Data/RecordOptions/UpsertRecordOptions.cs

A few improvements to the VectorStore xml docs based on suggestions from the team.

.Net: Adding improvements to xml docs based on suggestions from team.

---

dotnet/samples/Concepts/Agents/ChatCompletion_FunctionTermination.cs

The `ChatCompletion_FunctionTermination` sample is intended to use `IAutoFunctionInvocationFilter` but it isn't.
Update to build a `Kernel` that includes service-injection of  `IAutoFunctionInvocationFilter`

.Net Agents - Fix `ChatCompletion_FunctionTermination` to actually use `IAutoFunctionInvocationFilter` (as intended)

---

dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisVectorStoreFixture.cs

Integration tests for redis are intermittently failing with connection errors, so increasing the connection timeout.
Increase connection timeout for redis integration tests.

.Net: Increase connection timeout for redis integration tests.

---

dotnet/src/Connectors/Connectors.AzureAISearch.UnitTests/AzureAISearchServiceCollectionExtensionsTests.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantServiceCollectionExtensionsTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisServiceCollectionExtensionsTests.cs
dotnet/src/Connectors/Connectors.UnitTests/Memory/Pinecone/PineconeServiceCollectionExtensionsTests.cs
dotnet/src/SemanticKernel.Core/Data/KernelBuilderExtensions.cs
dotnet/src/SemanticKernel.Core/Data/ServiceCollectionExtensions.cs
dotnet/src/SemanticKernel.UnitTests/Data/ServiceCollectionExtensionsTests.cs

The DI extensions for other connectors are in the `Microsoft.SemanticKernel` namespace, so moving the VectorStore ones as well.
Moving the dependency injection framework extensions into the `Microsoft.SemanticKernel` namespace.

.Net: Moving VectorStore DI extensions to core namespace.

---

dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisHashSetVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisJsonVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisVectorStoreTests.cs

The idea is to run integration tests as part of the merge pipeline for database connectors using docker containers where possible.  This is working well in the build server for redis on windows, but failing intermittently with connection errors on ubuntu.
Disabling these tests as part of the build run for now, to avoid blocking the merge queue.

.Net: Disable redis integration tests since they are intermittently failing on ubuntu

---

docs/decisions/0051-dotnet-azure-model-as-a-service.md

.Net ADR Describing the strategy and patterns to follow on this new Connector.
Resolve #7957
- #7957

.Net: Azure AI Inference - ADR

---

.github/workflows/dotnet-build-and-test.yml

Code coverage enabled for the `Microsoft.SemanticKernel.Connectors.AzureOpenAI` assembly

.Net: Enable code coverage for OpenAi connectors

---

dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/FunctionChoice.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/FunctionChoiceBehavior.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/FunctionChoiceBehaviorConfiguration.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/FunctionChoiceBehaviorConfigurationContext.cs
dotnet/src/SemanticKernel.UnitTests/AI/FunctionChoiceBehaviors/FunctionChoiceTests.cs

This is the first PR that introduces an MVP model for the new function calling abstraction. 
The new function calling abstraction functionality has already been implemented in this https://github.com/microsoft/semantic-kernel/pull/6083/files. To simplify the code review, the PR will be split into a series of small, easy-to-review ones that will be merged into a separate feature-function-calling-abstraction branch.
This PR introduces a few model classes that allow configuring function calling behavior:
- `FunctionChoiceBehavior` - an abstract class that will be used as a base class for all the choice behavior classes that will be added later in separate PRs. It is intended to be used by AI connectors that will call its `GetConfiguration` method to obtain configuration corresponding to a …

.Net: Function calling mvp model

---

dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.cs

.Net: OpenAI V2 - Small fix

---

python/samples/concepts/filtering/auto_function_invoke_filters.py
python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py
python/semantic_kernel/kernel.py

Our auto function invoke filter does not have the correct behavior. Currently, it will return the straight chat completion results which contain the function call content, instead of the function result content. 
This PR fixes this by adding the function result content to the chat history, and if the auto function invoke filter has the context as terminated then it will return the last item of the chat history (function result content) otherwise it will be the completions (in the event that the function isn't run for some reason).
- It also fixes the `auto_function_invoke_filters` sample to show the FunctionResultContent if it exists.
- Aligns to the same behavior as in dotnet.
- Fixes #8020

Python: Update auto invoke function filter handling for proper functionality for OpenAI models.

---

dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.ChatCompletion.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatCompletion_AutoFunctionChoiceBehaviorTests.cs
dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAIChatCompletion_AutoFunctionChoiceBehaviorTests.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/AutoFunctionChoiceBehavior.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/FunctionChoice.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/FunctionChoiceBehavior.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/FunctionChoiceBehaviorConfiguration.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/FunctionChoiceBehaviorConfigurationContext.cs
dotnet/src/SemanticKernel.Abstractions/AI/PromptExecutionSettings.cs
dotnet/src/SemanticKernel.UnitTests/AI/FunctionChoiceBehaviors/AutoFunctionChoiceBehaviorTests.cs
dotnet/src/SemanticKernel.UnitTests/AI/FunctionChoiceBehaviors/FunctionChoiceBehaviorTests.cs
dotnet/src/SemanticKernel.UnitTests/AI/PromptExecutionSettingsTests.cs

This PR adds a new `AutoFunctionChoiceBehavior` class that contains information about functions to advertise to LLM, whether to auto-invoke them or not, and the Auto choice instructing LLM to consider calling one or many advertised functions. Additionally, it adds the new `FunctionChoiceBehavior` property to the `PromptExecutionSettings` class, which will be used by all AI connectors to configure function choice behavior in a connector agnostic way.

.Net: Auto function choice behavior

---

dotnet/src/Connectors/Connectors.MistralAI.UnitTests/Client/MistralClientTests.cs
dotnet/src/Connectors/Connectors.MistralAI.UnitTests/MistralTestBase.cs
dotnet/src/Connectors/Connectors.MistralAI.UnitTests/Services/MistralAIChatCompletionServiceTests.cs
dotnet/src/Connectors/Connectors.MistralAI.UnitTests/TestData/chat_completions_function_call_response.json
dotnet/src/Connectors/Connectors.MistralAI.UnitTests/TestData/chat_completions_streaming_function_call_response.txt
dotnet/src/Connectors/Connectors.MistralAI/Client/MistralClient.cs
dotnet/src/IntegrationTests/Connectors/MistralAI/ChatCompletion/MistralAIChatCompletionTests.cs

Today, MistralAI connector don't allow auto-function invocation filters to update/mutate chat history. The mutation can be useful to reduce the number of tokens sent to LLM by removing no longer needed function-calling messages from the chat history.
Closes: https://github.com/microsoft/semantic-kernel/issues/7590.
This PR updates the `MistralClient` class to generate a list of messages to send to the LLM based on the latest chat history for every function-calling loop iteration, rather than separately updating the list of LLM messages and chat history.

.Net: Allow chat history mutation from auto-function invocation filters in MistralAI connector

---

dotnet/src/Functions/Functions.Prompty.UnitTests/PromptyTest.cs
dotnet/src/Functions/Functions.Prompty.UnitTests/TestData/chatJsonObject.prompty
dotnet/src/Functions/Functions.Prompty/Core/PromptyModelParameters.cs
dotnet/src/Functions/Functions.Prompty/Core/PromptyResponseFormat.cs
dotnet/src/Functions/Functions.Prompty/KernelFunctionPrompty.cs

Fixing these issues:
- https://github.com/microsoft/semantic-kernel/issues/8148
- https://github.com/microsoft/semantic-kernel/issues/8154
-->
- Fixing yaml schema around prompty response_type (more details in the original reported issues)
- Adding tests for regression

.Net: Fix Prompty Issue of parsing ResponseFormat (issue #8148, #8154)

---

dotnet/src/Connectors/Connectors.AzureAIInference/Settings/AzureAIInferencePromptExecutionSettings.cs
dotnet/src/IntegrationTests/Connectors/AzureAIInference/AzureAIInferenceChatCompletionServiceTests.cs

Adding Missing Integration Tests.
- Resolve Partially #7958 
- Add Integration Tests.

.Net: Azure MaaS Connector: Integration Tests

---

dotnet/src/Functions/Functions.Prompty.UnitTests/TestData/chatJsonObject.prompty

Settings are nullable in the Execution Settings V2 moving forward, the top_p is not by default 1.0 if not set, setting the value in the yml to comply with the test.

.Net: OpenAI V2 - Prompty UT Fix

---

python/samples/concepts/agents/mixed_chat_reset.py
python/semantic_kernel/agents/channels/agent_channel.py
python/semantic_kernel/agents/channels/chat_history_channel.py
python/semantic_kernel/agents/channels/open_ai_assistant_channel.py
python/semantic_kernel/agents/group_chat/agent_chat.py
python/tests/unit/agents/test_agent_chat.py
python/tests/unit/agents/test_chat_history_channel.py
python/tests/unit/agents/test_open_ai_assistant_channel.py

There have been requests from customers to be able to reset an agent channel during the middle of an agent convo/interaction. 
This PR introduces functionality to be able to reset the various types of SK agent channels. 
- Adds a sample showing how the reset affects the agent interactions.
- Adds unit tests to exercise the new code.
- Closes #8275

Python: Introduce agent chat reset functionality. Add unit tests and a sample.

---

dotnet/samples/Concepts/ChatCompletion/Ollama_ChatCompletion.cs
dotnet/samples/Concepts/ChatCompletion/Ollama_ChatCompletionStreaming.cs
dotnet/samples/Concepts/Concepts.csproj
dotnet/samples/Concepts/Memory/Ollama_EmbeddingGeneration.cs
dotnet/samples/Concepts/TextGeneration/Ollama_TextGeneration.cs
dotnet/samples/Concepts/TextGeneration/Ollama_TextGenerationStreaming.cs
dotnet/samples/Demos/AIModelRouter/AIModelRouter.csproj
dotnet/samples/Demos/AIModelRouter/CustomRouter.cs
dotnet/samples/Demos/AIModelRouter/Program.cs
dotnet/samples/Demos/AIModelRouter/SelectedServiceFilter.cs
dotnet/src/Connectors/Connectors.Ollama/Extensions/OllamaKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Ollama/Extensions/OllamaServiceCollectionExtensions.cs
dotnet/src/InternalUtilities/samples/InternalUtilities/TestConfiguration.cs

Adding missing samples using the new Ollama Connector.
- Embedding generation
- Text Generation
- Chat Completion
- AIModelRouting Demo with Ollama Connector

.Net: Ollama - Adding Missing Samples

---

docs/decisions/0051-entity-framework-as-connector.md

Resolves: https://github.com/microsoft/semantic-kernel/issues/7317
This ADR contains an information about implementing Entity Framework memory connector, which potentially could work with multiple databases at the same time and its current limitations.

ADR for Entity Framework memory connector

---

.pre-commit-config.yaml
python/poetry.lock
python/pyproject.toml

Per dependabot, ruff 0.6.1 is available.
Upgrading from ruff 0.5.7 -> 0.6.1. This requires a manual PR to update our pre-commit config.

Python: Upgrade ruff to 0.6.1

---

dotnet/SK-dotnet.sln.DotSettings
dotnet/src/Connectors/Connectors.Oobabooga/README.md
dotnet/src/IntegrationTests/README.md

Removing reference as the original Oobabooga Connector repo is outdated and don't provide support for any stable Semantic Kernel version.

.Net: Remove Oobabooga Legacy reference

---

dotnet/samples/Concepts/TextGeneration/Ollama_TextGeneration.cs

Small fix identified during bugbash.

.Net: Ollama Concept Test Fix

---

dotnet/src/SemanticKernel.Abstractions/Functions/KernelFunction.cs
python/samples/demos/telemetry_with_application_insights/README.md
python/samples/demos/telemetry_with_application_insights/main.py
python/semantic_kernel/functions/kernel_function.py
python/semantic_kernel/functions/kernel_function_log_messages.py

We very recently added instrumentation to kernel functions: https://github.com/microsoft/semantic-kernel/pull/8280. That PR added logs and traces for observing a kernel function. This PR adds metrics and modifies the telemetry sample app to show how to export metric instruments to Application Insights.
1. Kernel function now produces metrics data for observability.
2. Add code to export metric instruments to the telemetry sample.
3. Add Google AI as a second service to the telemetry sample to show case nested spans.
4. Mics optimizations.

Python: Add metrics instrumentation

---

dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Services/AzureOpenAIChatCompletionServiceTests.cs
dotnet/src/Connectors/Connectors.OpenAI.UnitTests/Services/OpenAIChatCompletionServiceTests.cs
dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.ChatCompletion.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatCompletion_RequiredFunctionChoiceBehaviorTests.cs
dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAIChatCompletion_RequiredFunctionChoiceBehaviorTests.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/FunctionChoiceBehavior.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/FunctionChoiceBehaviorConfigurationContext.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/FunctionChoiceBehaviorFunctionsSelectorContext.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/RequiredFunctionChoiceBehavior.cs
dotnet/src/SemanticKernel.Abstractions/AI/PromptExecutionSettings.cs
dotnet/src/SemanticKernel.UnitTests/AI/FunctionChoiceBehaviors/FunctionChoiceBehaviorTests.cs
dotnet/src/SemanticKernel.UnitTests/AI/FunctionChoiceBehaviors/NoneFunctionChoiceBehaviorTests.cs
dotnet/src/SemanticKernel.UnitTests/AI/FunctionChoiceBehaviors/RequiredFunctionChoiceBehaviorTests.cs

This PR adds a new `RequiredFunctionChoiceBehavior` class that is used by AI connectors to get a list of the functions to advertise to the AI model and force it to call one or more functions. Additionally, it provides information on whether the functions should be auto-invoked and accepts a function selector callback to stop advertising functions if the AI model prompt has already been answered.

.Net: Required function choice behavior

---

dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.ChatCompletion.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/AutoFunctionChoiceBehavior.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/FunctionChoiceBehavior.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/NoneFunctionChoiceBehavior.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/RequiredFunctionChoiceBehavior.cs

While working on the new function choice behavior functionality, a few inefficiencies were identified during development and PR reviews. This PR is one of a few follow-up ones that will remove those inefficiencies.
This PR extracts and reuses common code for function selection and mapping function choice behavior to the underlying Azure SDK model.

.Net Extract and reuse common code for function calling

---

dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Settings/AzureOpenAIPromptExecutionSettingsTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Settings/OpenAIPromptExecutionSettingsTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Settings/AzureOpenAIPromptExecutionSettings.cs
dotnet/src/Connectors/Connectors.OpenAI/Settings/OpenAIPromptExecutionSettings.cs
dotnet/src/Functions/Functions.UnitTests/Functions.UnitTests.csproj
dotnet/src/Functions/Functions.UnitTests/Markdown/Functions/KernelFunctionMarkdownTests.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/AutoFunctionChoiceBehavior.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/FunctionChoiceBehavior.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/NoneFunctionChoiceBehavior.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/RequiredFunctionChoiceBehavior.cs
dotnet/src/SemanticKernel.Abstractions/AI/PromptExecutionSettings.cs
dotnet/src/SemanticKernel.UnitTests/AI/FunctionChoiceBehaviors/AutoFunctionChoiceBehaviorTests.cs
dotnet/src/SemanticKernel.UnitTests/AI/FunctionChoiceBehaviors/FunctionChoiceBehaviorDeserializationTests.cs
dotnet/src/SemanticKernel.UnitTests/AI/FunctionChoiceBehaviors/FunctionChoiceBehaviorTests.cs
dotnet/src/SemanticKernel.UnitTests/AI/FunctionChoiceBehaviors/NoneFunctionChoiceBehaviorTests.cs
dotnet/src/SemanticKernel.UnitTests/AI/FunctionChoiceBehaviors/RequiredFunctionChoiceBehaviorTests.cs
dotnet/src/SemanticKernel.UnitTests/PromptTemplate/PromptTemplateConfigTests.cs

The only way to configure function choice behavior at the moment is via the code. However, it would be good to configure the behavior in SK prompts as well. This PR adds support for function choice behavior in JSON prompts.
This PR extends all existing `auto`, `none`, and `required` function choice behavior classes to be JSON serialization-friendly so they can easily be deserialized during JSON prompt loading.
Support for YAML prompts will be added in the next PR.

.Net: Function choice behavior in JSON prompts

---

python/.pre-commit-config.yaml
python/semantic_kernel/functions/kernel_arguments.py
python/semantic_kernel/kernel.py
python/tests/unit/functions/test_kernel_arguments.py

In `invoke_prompt(...)` and `invoke_prompt_async(...)`, the `arguments` parameter is tested to see if it's empty before proceeding. The type of the `arguments` parameter is `KernelArgument`, which derives from a `dict` type, with an additional field for execution settings. When `arguments` contains only the execution settings, it will be considered as an empty dictionary. This will result in the `arguments` parameter being overridden completely, invalidating all execution settings passed to the APIs.
To reproduce (assuming we have a plugin/function that will return the weather):
```
result = await kernel.invoke_prompt(
"What is the weather like in my location?",
arguments=KernelArguments(
settings={
service_id: PromptExecutionSettings(
service_id=service_id, …
```

Python: Fix KernelArgument bug in invoke_prompt functions

---

python/.vscode/tasks.json
python/semantic_kernel/contents/chat_message_content.py
python/tests/unit/contents/test_chat_message_content.py

Turns out we had a mistake in the way CMC discriminates content types, this PR fixes that
Adds discriminator field to the item in the list rather then the list itself
Adds additional tests

Python: fix discrimator field for CMC

---

dotnet/SK-dotnet.sln
dotnet/src/InternalUtilities/connectors/AI/AiConnectorsInternalUtilities.props
dotnet/src/InternalUtilities/connectors/AI/FunctionCallsProcessor.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/FunctionChoiceBehaviorConfiguration.cs
dotnet/src/SemanticKernel.UnitTests/SemanticKernel.UnitTests.csproj
dotnet/src/SemanticKernel.UnitTests/Utilities/AIConnectors/FunctionCallsProcessorTests.cs

Today, each AI connector that works with an AI model having function calling capabilities has to implement the same function calling functionality: iterating over function calls, looking up the function, invoking the auto-invocation filter, invoking the function, and putting the function invocation result into the chat history.
This PR encapsulates the function-calling functionality into the `FunctionCallsProcessor` class, which will be reused by AI connectors for function calling. The class has two methods:     
1. `GetConfiguration`: retrieves function-calling-related configuration that each AI connector will use to get a list of functions to advertise to the AI model, the function choice the AI model should use, whether to auto-invoke functions or not, etc.  
2. …

.Net: AI function calls processor

---

docs/decisions/0052-python-ai-connector-new-abstract-methods.md

This ADR documents a proposal to introduce four new abstract methods in `ChatCompletionClientBase` and `TextCompletionClientBase` to optimize code and further streamline the process of adding new AI connectors.

Python: ADR for new AI connector abstract methods

---

dotnet/src/Connectors/Connectors.AzureOpenAI/Extensions/AzureOpenAIKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Services/AzureOpenAITextToAudioService.cs
dotnet/src/IntegrationTests/Agents/ChatCompletionAgentTests.cs
dotnet/src/IntegrationTests/Agents/OpenAIAssistantAgentTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIAudioToTextTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatCompletionFunctionCallingTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatCompletionNonStreamingTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatCompletionStreamingTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatCompletionTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAITextEmbeddingTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAITextToAudioTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAITextToImageTests.cs
dotnet/src/IntegrationTests/Planners/Handlebars/HandlebarsPlannerTests.cs
dotnet/src/IntegrationTests/PromptTests.cs
dotnet/src/IntegrationTests/README.md
dotnet/src/IntegrationTests/TestSettings/AzureOpenAIConfiguration.cs
dotnet/src/IntegrationTests/testsettings.json

Switch to using DefaultAzureCredential and get all tests passing locally
See: #6966

.Net: Switch from API keys to DefaultAzureCredential

---

dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Services/AzureOpenAIChatCompletionServiceTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Core/AzureClientCore.ChatCompletion.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Core/AzureClientCore.cs
dotnet/src/Connectors/Connectors.OpenAI.UnitTests/Services/OpenAIChatCompletionServiceTests.cs
dotnet/src/Connectors/Connectors.OpenAI/Connectors.OpenAI.csproj
dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.ChatCompletion.cs
dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.cs
dotnet/src/InternalUtilities/connectors/AI/AiConnectorsInternalUtilities.props
dotnet/src/InternalUtilities/connectors/AI/FunctionCallsProcessor.cs
dotnet/src/SemanticKernel.UnitTests/Utilities/AIConnectors/FunctionCallsProcessorTests.cs

Having the `FunctionCallsProcessor` class responsible for function calling it makes sense to replace function calling code some SK AI connectors have. This PR updates {Azure}OpenAI connectors to delegate function calling to the processor.
Both `OpenAIChatCompletionService` and `AzureOpenAIChatCompletionService` are refactored to use the `FunctionCallsProcessor` to obtain function calling configuration and process functions calls.
Closes: https://github.com/microsoft/semantic-kernel/issues/6744

.Net: Use function calls processor in {Azure}OpenAI connectors

---

dotnet/SK-dotnet.sln
dotnet/src/Connectors/Connectors.AzureOpenAI/Core/AzureClientCore.cs
dotnet/src/Connectors/Connectors.OpenAI/Connectors.OpenAI.csproj
dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.ChatCompletion.cs
dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.cs
dotnet/src/InternalUtilities/connectors/AI/AiConnectorsInternalUtilities.props
dotnet/src/InternalUtilities/connectors/AI/FunctionCalling/FunctionCallingUtilities.props
dotnet/src/InternalUtilities/connectors/AI/FunctionCalling/FunctionCallsProcessor.cs
dotnet/src/SemanticKernel.UnitTests/SemanticKernel.UnitTests.csproj
dotnet/src/SemanticKernel.UnitTests/Utilities/AIConnectors/FunctionCallsProcessorTests.cs

The `FunctionCallsProcess` is one of potentially many AI utility classes that AI connectors may use. However, the function calling functionality may not be relevant to all AI connectors and should not be imported by the connectors. This PR moves the function calling utils to a dedicated folder so it can be imported separately by AI connectors with function calling capabilities.

.Net: Change function calling utils location

---

dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.ChatCompletion.cs
dotnet/src/InternalUtilities/connectors/AI/FunctionCalling/FunctionCallsProcessor.cs
dotnet/src/SemanticKernel.UnitTests/Utilities/AIConnectors/FunctionCallsProcessorTests.cs

Both the function calls processor and AI connectors need to convert function results, which can be of any type, into a string that AI can understand. This PR makes the `FunctionCallsProcessor.ProcessFunctionResult` method public to avoid duplication and let both the processor and AI connectors use the same serialization function. It also removes unnecessary code that was moved to the function calls processor but not deleted from the connector.

.Net: Share method for processing function invocation results

---

dotnet/src/Extensions/Extensions.UnitTests/PromptTemplates/Handlebars/Helpers/KernelFunctionHelpersTests.cs
dotnet/src/Extensions/PromptTemplates.Handlebars/Helpers/KernelHelpers/KernelFunctionHelpers.cs

This change makes it easier to debug issues with parameter passing using positional arguments in Handlebars templates by matching the behavior of hash arguments when a null InputVariable is passed.
Previously, the IsExpectedParameterType method would throw when it tried to check the type of a null object
Passing a null parameter would previous cause a null reference exception for positional arguments. It would throw a KernelException for hash arguments. Change behavior of positional arguments to throw a KernelException to match behavior.
Adds tests for both cases as well as the positive test case where a argument is passed properly

.Net: Handle null parameter values in Handlebars positional arguments

---

dotnet/src/Connectors/Connectors.AzureAISearch.UnitTests/AzureAISearchVectorStoreCollectionSearchMappingTests.cs
dotnet/src/Connectors/Connectors.AzureAISearch.UnitTests/AzureAISearchVectorStoreRecordCollectionTests.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreCollectionSearchMapping.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreRecordCollection.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreFixture.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreRecordCollectionTests.cs

As part of the work on vector storage we have to add vector search capabilities for each implementation.
1. Adding vector search for Azure AI Search.
2. Note that for now, the search interface is implemented directly by the collection, but in future it should be part of the collection interface. I'm doing it this way so that each implementation can be added one by one, and once all have been implemented, we can make the switch.

.Net: Add vector search implementation for azure ai search

---

dotnet/Directory.Packages.props
dotnet/src/Connectors/Connectors.Memory.Qdrant/MockableQdrantClient.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreCollectionSearchMapping.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantVectorStoreCollectionSearchMappingTests.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorStoreRecordCollectionTests.cs

As part of the work on vector storage we have to add vector search capabilities for each implementation.
1. Adding vector search for Qdrant.
2. Note that for now, the search interface is implemented directly by the collection, but in future it should be part of the collection interface. I'm doing it this way so that each implementation can be added one by one, and once all have been implemented, we can make the switch.

.Net: Add qdrant vector search implementation.

---

dotnet/src/IntegrationTests/Agents/ChatCompletionAgentTests.cs
dotnet/src/IntegrationTests/Agents/MixedAgentTests.cs
dotnet/src/IntegrationTests/Agents/OpenAIAssistantAgentTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIAudioToTextTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatCompletionFunctionCallingTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatCompletionNonStreamingTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatCompletionStreamingTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatCompletionTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAITextEmbeddingTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAITextToAudioTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAITextToImageTests.cs
dotnet/src/IntegrationTests/Planners/Handlebars/HandlebarsPlannerTests.cs
dotnet/src/IntegrationTests/PromptTests.cs

`DefaultAzureCredential` attempts multiple strategies but we can start by just relying on Azure Cli login.

.Net: Switch to using AzureCliCredential

---

python/samples/README.md
python/samples/demos/README.md

The Python samples folder is a lacking an overall README file covering what each samples folder does.
Adds a samples README as well as a demos folder README.

Python: Add a samples README and a demos README.

---

dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatCompletion_RequiredFunctionChoiceBehaviorTests.cs
dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAIChatCompletion_RequiredFunctionChoiceBehaviorTests.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/FunctionChoiceBehavior.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/RequiredFunctionChoiceBehavior.cs
dotnet/src/SemanticKernel.Abstractions/AI/PromptExecutionSettings.cs
dotnet/src/SemanticKernel.UnitTests/AI/FunctionChoiceBehaviors/FunctionChoiceBehaviorTests.cs
dotnet/src/SemanticKernel.UnitTests/AI/FunctionChoiceBehaviors/RequiredFunctionChoiceBehaviorTests.cs

To fully finalize the new function-calling model, we need a mechanism to prevent endless invocation of **required** functions by AI models. Until this mechanism is in place, and to expedite the release of the new function-calling model, it makes sense to align its behavior with that of the current model. Specifically, required functions should be advertised only in the initial request to the model and not in subsequent requests, to prevent endless function calls by the model.
This PR modifies the `RequiredFunctionChoiceBehavior` class to advertise functions only in the first request to the model and not in subsequent requests of the same interaction with AI connector.

.Net: Advertise required functions in the first request to AI model only

---

dotnet/src/Connectors/Connectors.AzureCosmosDBMongoDB.UnitTests/AzureCosmosDBMongoDBKernelBuilderExtensionsTests.cs
dotnet/src/Connectors/Connectors.AzureCosmosDBMongoDB.UnitTests/AzureCosmosDBMongoDBServiceCollectionExtensionsTests.cs
dotnet/src/Connectors/Connectors.AzureCosmosDBNoSQL.UnitTests/AzureCosmosDBNoSQLKernelBuilderExtensionsTests.cs
dotnet/src/Connectors/Connectors.AzureCosmosDBNoSQL.UnitTests/AzureCosmosDBNoSQLServiceCollectionExtensionsTests.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/AzureCosmosDBNoSQLServiceCollectionExtensions.cs

Set a default user agent string of semantic kernel for Azure Cosmos DB NoSQL and MongoDB.
#7580

.Net: Add SK user agent string for Azure Cosmos DB NoSQL and MongoDB.

---

dotnet/src/IntegrationTests/Connectors/Memory/Weaviate/WeaviateVectorStoreRecordCollectionTests.cs

Weaviate integration tests started to fail, temporarily disabling them during the investigation to unblock pipelines in other PRs.

.Net: Temporarily disable Weaviate integration tests

---

docs/decisions/0052-python-ai-connector-new-abstract-methods.md
python/.cspell.json
python/mypy.ini
python/semantic_kernel/connectors/ai/anthropic/services/anthropic_chat_completion.py
python/semantic_kernel/connectors/ai/azure_ai_inference/services/azure_ai_inference_chat_completion.py
python/semantic_kernel/connectors/ai/chat_completion_client_base.py
python/semantic_kernel/connectors/ai/function_calling_utils.py
python/semantic_kernel/connectors/ai/google/google_ai/services/google_ai_chat_completion.py
python/semantic_kernel/connectors/ai/google/google_ai/services/google_ai_text_completion.py
python/semantic_kernel/connectors/ai/google/google_ai/services/utils.py
python/semantic_kernel/connectors/ai/google/vertex_ai/services/utils.py
python/semantic_kernel/connectors/ai/google/vertex_ai/services/vertex_ai_chat_completion.py
python/semantic_kernel/connectors/ai/google/vertex_ai/services/vertex_ai_text_completion.py
python/semantic_kernel/connectors/ai/hugging_face/services/hf_text_completion.py
python/semantic_kernel/connectors/ai/mistral_ai/services/mistral_ai_chat_completion.py
python/semantic_kernel/connectors/ai/ollama/services/ollama_chat_completion.py
python/semantic_kernel/connectors/ai/ollama/services/ollama_text_completion.py
python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py
python/semantic_kernel/connectors/ai/open_ai/services/open_ai_text_completion_base.py
python/semantic_kernel/connectors/ai/text_completion_client_base.py
python/semantic_kernel/utils/telemetry/model_diagnostics/decorators.py
python/tests/unit/connectors/ollama/services/test_ollama_chat_completion.py
python/tests/unit/connectors/open_ai/services/test_azure_chat_completion.py
python/tests/unit/connectors/open_ai/services/test_open_ai_chat_completion_base.py
python/tests/unit/utils/model_diagnostics/conftest.py
python/tests/unit/utils/model_diagnostics/test_trace_chat_completion.py
python/tests/unit/utils/model_diagnostics/test_trace_text_completion.py

This PR implements: https://github.com/microsoft/semantic-kernel/blob/main/docs/decisions/0052-python-ai-connector-new-abstract-methods.md (PR: https://github.com/microsoft/semantic-kernel/pull/8430).
1. Add abstract methods `_inner_get_chat_message_content` and `_inner_get_streaming_chat_message_content` to `ChatCompletionClientBase`.
2. Implement the abstractions in all chat completion connectors.
3. Add abstract methods `_inner_get_text_contents` and `_inner_get_streaming_text_contents` to `TextCompletionClientBase`.
4. Implement the abstractions in all text completion connectors.
5. Remove text completion APIs from `OllamaChatCompletion` (breaking changes).
> No breaking changes on other connectors except Ollama, and public APIs stay the same.

Python: New AI Connector abstract methods

---

dotnet/src/Connectors/Connectors.AzureAISearch.UnitTests/AzureAISearchGenericDataModelMapperTests.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchGenericDataModelMapper.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreRecordCollection.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreFixture.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreRecordCollectionTests.cs
dotnet/src/SemanticKernel.Abstractions/Data/VectorStoreGenericDataModel.cs

For cases where a developer is defining a schema using configuration, it's useful to have a generic data model that can be used with any data source.  A separate definition can be supplied in this case, that defines the schema, and this can look different to the data model.
- Adding a generic data model for any vector store records
- Adding a mapping for Azure AI Search that uses the definition to map from the database record to the generic data model.
#8536

.Net: VectorStore: Adding a generic data model and related azure ai search mapper.

---

dotnet/src/Agents/Core/History/ChatHistorySummarizationReducer.cs

This PR fixes the incorrect spelling of **"summarization"** in `DefaultSummarizationPrompt` of `ChatHistorySummarizationReducer` class
Fixes #8545

.Net: Fix typo for DefaultSummarizationPrompt

---

python/samples/concepts/auto_function_calling/azure_python_code_interpreter_function_calling.py
python/semantic_kernel/connectors/ai/open_ai/services/azure_chat_completion.py
python/semantic_kernel/connectors/ai/open_ai/services/azure_text_completion.py
python/semantic_kernel/core_plugins/sessions_python_tool/README.md
python/semantic_kernel/core_plugins/sessions_python_tool/sessions_python_plugin.py
python/tests/conftest.py
python/tests/unit/connectors/open_ai/services/test_azure_chat_completion.py
python/tests/unit/connectors/open_ai/services/test_azure_text_completion.py
python/tests/unit/connectors/open_ai/services/test_azure_text_embedding.py
python/tests/unit/core_plugins/test_sessions_python_plugin.py

Move the sessions plugin to use the default token provider, which can be overridden by the user as needed.
Move the sessions plugin to use the default token provider, which can be overridden by the user as needed.

Python: Support Sessions plugin auth token

---

python/samples/getting_started_with_agents/step2_plugins.py
python/samples/getting_started_with_agents/step7_assistant.py
python/semantic_kernel/agents/open_ai/open_ai_assistant_base.py
python/tests/unit/agents/test_open_ai_assistant_base.py

We weren't properly handling the available FunctionResultContent in an OpenAI assistant if multiple tool calls were included in the chat history. 
Fix this issue by making sure we use the `function call contents` list as the source of truth (the model is expecting that we return the tool call ids that were sent). We then use these function call content ids to grab the corresponding function result content from the chat history and this is sent back to the model.
- Fixes #8701

Python: Fix openai assistant function calling bug

---

dotnet/src/Connectors/Connectors.Memory.Redis/RedisHashSetGenericDataModelMapper.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisHashSetVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisHashSetVectorStoreRecordMapper.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonGenericDataModelMapper.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStoreRecordFieldMapping.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisHashSetGenericDataModelMapperTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisHashSetVectorStoreMappingTestHelpers.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisHashSetVectorStoreRecordMapperTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisJsonGenericDataModelMapperTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisHashSetVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisJsonVectorStoreRecordCollectionTests.cs

In some cases users may not want to define their own data model, e.g. where the database schema is driven from configuration.
To support this we allow a generic data model which uses object dictionaries for most of the fields, but this requires custom mapping, since each field from storage has to be mapped specifically into the right dictionary.
- Adding support to Redis for using a generic data model where schema is determined from the record definition.
- Adding unit tests / integration tests
- Refactoring some of the existing unit tests to reuse test code.

.Net: Adding generic data model support for Redis

---

dotnet/src/Connectors/Connectors.AzureAISearch.UnitTests/AzureAISearchGenericDataModelMapperTests.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchGenericDataModelMapper.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantGenericDataModelMapper.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordFieldMapping.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordMapper.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantGenericDataModelMapperTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorStoreRecordCollectionTests.cs

To allow use of the vector store abstractions without needing to define your own data type, we are adding a generic data type and mappers that can work with it.
- Separate field mapping functions into a separate class for Qdrant, so that it can be reused across mappers.
- Adding a mapper for the generic data type for Qdrant
- Adding some small improvements to Azure AI Search's mapper.

.Net: Adding Qdrant generic data model mapper.

---

dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordFieldMapping.cs

Qdrant supports UInt8, Float16 and Float32, but the SDK only supports Float32, so removing Float64 from supported list and keeping only Float32.
See https://qdrant.tech/documentation/concepts/vectors/
#8623

.Net: Remove float64 from supported vectors for Qdrant.

---

dotnet/src/Connectors/Connectors.AzureAISearch.UnitTests/AzureAISearchVectorStoreRecordCollectionTests.cs

After merging the latest changes from main, we have a moq warning about not finding a constructor for a type.
There is an internal parameterless constructor though.
Suppressing the warning, since tests still work as expected.

.Net: Suppress moq warning after taking package updates.

---

README.md

The link no longer works and fails the PR link check job.

Remove dead link to Maven Central

---

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisHashSetVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStoreCollectionCreateMapping.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStoreCollectionSearchMapping.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisVectorStoreCollectionSearchMappingTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisHashSetVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisJsonVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisVectorStoreFixture.cs
dotnet/src/SemanticKernel.Core/Data/VolatileVectorStoreRecordCollection.cs

Redis supports float64 for vector storage, and the Redis connectors were supporting this as well, but not for search.
- Adding float64 support for Redis vector search with tests.
- Changed from suing name to fullname for outputting the vector type name since name doesn't include the generic type.
#8846

.Net: Add float64 support for redis vector search.

---

dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatCompletion_AutoFunctionChoiceBehaviorTests.cs
dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAIChatCompletion_FunctionCallingTests.cs

Two integration tests keep failing during PR runs. This PR disables them to unblock other PRs while the root cause of the failure is being investigated.

.Net: Disable failing integration tests

---

python/semantic_kernel/connectors/ai/open_ai/prompt_execution_settings/azure_chat_prompt_execution_settings.py
python/tests/unit/connectors/open_ai/test_openai_request_settings.py

Azure AI Search data source supports 4 types of authentication but semantic kernel only supports `ApiKey`api key.
This PR adds support to the other authentication options as defined in its [docs](https://learn.microsoft.com/en-us/azure/ai-services/openai/references/azure-search?tabs=python#parameters), which are
- system_assigned_managed_identity
- user_assigned_managed_identity
- access_token

Python: support all auth options for azure ai search

---

dotnet/src/Connectors/Connectors.AzureCosmosDBMongoDB.UnitTests/AzureCosmosDBMongoDBHotelModel.cs
dotnet/src/Connectors/Connectors.AzureCosmosDBMongoDB.UnitTests/AzureCosmosDBMongoDBVectorStoreCollectionSearchMappingTests.cs
dotnet/src/Connectors/Connectors.AzureCosmosDBMongoDB.UnitTests/AzureCosmosDBMongoDBVectorStoreRecordCollectionTests.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreCollectionCreateMapping.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreCollectionSearchMapping.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreRecordCollectionOptions.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreRecordMapper.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreFixture.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreRecordCollectionTests.cs

- Added support for `Filter` parameter using `$eq` filter operator in vector search.
- Added support for `Offset` parameter in vector search. Since `Offset` doesn't exist in Azure CosmosDB MongoDB vector search API, it's currently implemented locally by fetching `Limit + Offset` items and returning last `Limit` items.

.Net: [Feature branch] Added support for Filter and Offset parameters in Azure CosmosDB MongoDB vector search

---

dotnet/samples/Concepts/ChatCompletion/Ollama_ChatCompletion.cs
dotnet/samples/Concepts/ChatCompletion/Ollama_ChatCompletionStreaming.cs
dotnet/src/Connectors/Connectors.Ollama.UnitTests/Services/OllamaChatCompletionTests.cs
dotnet/src/Connectors/Connectors.Ollama/Services/OllamaChatCompletionService.cs

As other connectors are providing a `FinishReason = "STOP"` metadata in the last `StreamingChatMessageContent` message, I adjusted the `GetStreamingChatMessageContentsAsync()` method in the `OllamaChatCompletionService` to provide the expected metadata.
The `ChatResponseStream` message from the **OllamaSharp** package provides a `Done` property, which indicates if the stream is finished. This property is used to determine when to set the metadata with `FinishReason = "STOP"`.

.Net: Add Examples to retrieve FinishReason/DoneReason and other details with the Ollama connector

---

dotnet/src/Connectors/Connectors.Memory.Redis/RedisHashSetVectorStoreRecordCollectionOptions.cs

The prefix setting automatically prefixes the collection name onto the record ids on upsert / read.
Using a prefix is required for records to be added to an index.
Users can have this setting off and pass in their own prefix directly or have it on and get the collection name prefixed
The plan was to set this to true by default because it'll just work for users, instead of them having to do something special, and they can switch this off if they want to do their own thing. It's true by default for the JSON implementation but this was missed for the Hashset implementation.
- Changing this setting to true by default to match the JSON Connector.

.Net: Switch redis hashset vectorstore prefix default to true

---

dotnet/samples/Concepts/Agents/OpenAIAssistant_Streaming.cs
dotnet/src/Agents/OpenAI/Internal/AssistantThreadActions.cs
dotnet/src/Agents/OpenAI/OpenAIAssistantAgent.cs

Customer input identified that `messages` parameter may not always be required by the caller.
Fixes: https://github.com/microsoft/semantic-kernel/issues/8857
Providing the complete messages is a convenience and shouldn't be required.

.Net Agents - Make `messages` parameter optional for `OpenAIAssistantAgent.InvokeStreamingAsync`

---

dotnet/samples/GettingStartedWithAgents/Step04_KernelFunctionStrategies.cs
dotnet/src/Agents/Core/AgentGroupChat.cs
dotnet/src/Agents/Core/Chat/KernelFunctionSelectionStrategy.cs
dotnet/src/Agents/Core/Chat/KernelFunctionTerminationStrategy.cs
dotnet/src/Agents/Core/ChatHistoryKernelAgent.cs
dotnet/src/Agents/Core/History/ChatHistoryReducerExtensions.cs
dotnet/src/Agents/Core/Internal/ChatMessageForPrompt.cs

Refine handling of history for `KernelFunctionSelectionStrategy` and `KernelFunctionTerminationStrategy` based on customer input.
Fixes: https://github.com/microsoft/semantic-kernel/issues/8898
Fixes: https://github.com/microsoft/semantic-kernel/issues/8914
```
Determine which participant takes the next turn in a conversation based on the the most recent participant.
State only the name of the participant to take the next turn.
No participant should take more than one turn in a row.
Choose only from these participants:
- ArtDirector
- CopyWriter
Always follow these rules when selecting the next participant:
- After CopyWriter, it is ArtDirector's turn.
- After ArtDirector, it is CopyWriter's turn.
History:
[
{
"Role": "user",
"Content": "concept: maps made out of egg cartons."
},
{ …
```

.Net Agents - Update KernelFunction Based Strategies for `AgentGroupChat`

---

.github/_typos.toml
dotnet/samples/Concepts/Memory/VectorStoreExtensions.cs
dotnet/samples/Concepts/Memory/VolatileVectorStore_LoadData.cs
dotnet/samples/Concepts/Resources/what-is-semantic-kernel.json
dotnet/samples/Concepts/Search/VectorStore_TextSearch.cs
dotnet/src/SemanticKernel.UnitTests/Data/VectorStoreTextSearchTests.cs

1. Add `VectorizedSearchWrapper` to help test `VectorStoreTextSearch`
2. Add unit tests for `VectorStoreTextSearch`

.Net: Add VectorStoreTextSearch concepts and unit tests

---

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisHashSetVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonVectorStoreRecordCollection.cs
dotnet/src/InternalUtilities/src/Data/VectorStoreRecordPropertyReader.cs
dotnet/src/SemanticKernel.UnitTests/Data/VectorStoreRecordPropertyReaderTests.cs

If someone uses the generic data model, they need to also supply a record definition, otherwise we don't know how to map the data from storage to the generic data model.
Also, if someone uses the generic data model and they use a key type other than the ones we support out of the box, they need to provide a custom mapper to do that key mapping.
- This PR adds checks for this with helpful messaging to a shared class.
- Adds the validation calls to all connectors that support the generic data model.

.Net: Share generic data model validations and use everywhere.

---

dotnet/src/Experimental/Process.Abstractions/KernelProcess.cs
dotnet/src/Experimental/Process.Abstractions/KernelProcessStep.cs
dotnet/src/Experimental/Process.Abstractions/KernelProcessStepInfo.cs
dotnet/src/Experimental/Process.Abstractions/KernelProcessStepState.cs

Refactored `KernelProcessStep` to simplify things by braking the inheritance from `KernelProcessStepBase`. `KernelProcessStepBase` has been changed to `KernelProcessStepInfo` and now keeps track of metadata about a step without being in the inheritance chain.

.Net: Refactored step inheritance to make this less confusing.

---

python/semantic_kernel/connectors/ai/open_ai/services/azure_text_completion.py
python/semantic_kernel/connectors/ai/open_ai/services/azure_text_embedding.py
python/tests/unit/connectors/open_ai/services/test_azure_text_completion.py
python/tests/unit/connectors/open_ai/services/test_azure_text_embedding.py

While working on #8951 I found that interacting with an Azure OpenAI instance I had an API key for, but my identity didn't have IAM access to the API for, that I was getting a permission error:
```
semantic_kernel.exceptions.service_exceptions.ServiceResponseException: ("<class 'semantic_kernel.connectors.ai.open_ai.services.azure_text_embedding.AzureTextEmbedding'> service failed to generate embeddings", AuthenticationError("Error code: 401 - {'error': {'code': 'PermissionDenied', 'message': 'Principal does not have access to API/Operation.'}}"))
```
I found that this was because, though my API key was set in the environment, the codepath only recognized an explicitly passed in API key when deciding whether to issue an AD token while initializing an AzureTextEmbedding instance.
This PR …

Python: Azure OpenAI setting fix: Don't fetch AD token if API is present in environment variable.

---

dotnet/src/SemanticKernel.UnitTests/Utilities/KernelJsonSchemaBuilderTests.cs

Make sure the `KernelJsonSchemaBuilder` can build schemas for types having public properties of `object` or/and `KernelJsonSchema` types that have default values in the constructor. This test verifies that the fix https://github.com/microsoft/semantic-kernel/pull/8988 works and prevents future regressions of this scenario.

.Net: Unit test for KernelJsonSchemaBuilder

---

dotnet/src/SemanticKernel.Abstractions/Data/TextSearch/ITextSearchResultMapper.cs
dotnet/src/SemanticKernel.Abstractions/Data/TextSearch/ITextSearchStringMapper.cs
dotnet/src/SemanticKernel.Core/Data/TextSearch/VectorStoreTextSearch.cs

Related to #6725 
Implementation of `ITextSearchStringMapper` in core where we can just pass a lambda

.Net: Add delegates for the string and result mappers

---

dotnet/src/Connectors/Connectors.AzureAISearch.UnitTests/AzureAISearchKernelBuilderExtensionsTests.cs
dotnet/src/Connectors/Connectors.AzureAISearch.UnitTests/AzureAISearchServiceCollectionExtensionsTests.cs
dotnet/src/Connectors/Connectors.AzureCosmosDBMongoDB.UnitTests/AzureCosmosDBMongoDBKernelBuilderExtensionsTests.cs
dotnet/src/Connectors/Connectors.AzureCosmosDBMongoDB.UnitTests/AzureCosmosDBMongoDBServiceCollectionExtensionsTests.cs
dotnet/src/Connectors/Connectors.AzureCosmosDBNoSQL.UnitTests/AzureCosmosDBNoSQLKernelBuilderExtensionsTests.cs
dotnet/src/Connectors/Connectors.AzureCosmosDBNoSQL.UnitTests/AzureCosmosDBNoSQLServiceCollectionExtensionsTests.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/AzureCosmosDBNoSQLKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/AzureCosmosDBNoSQLServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantKernelBuilderExtensionsTests.cs
dotnet/src/Connectors/Connectors.Qdrant.UnitTests/QdrantServiceCollectionExtensionsTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisKernelBuilderExtensionsTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisServiceCollectionExtensionsTests.cs
dotnet/src/Connectors/Connectors.UnitTests/Memory/Pinecone/PineconeKernelBuilderExtensionsTests.cs
dotnet/src/Connectors/Connectors.UnitTests/Memory/Pinecone/PineconeServiceCollectionExtensionsTests.cs
dotnet/src/Connectors/Connectors.Weaviate.UnitTests/WeaviateKernelBuilderExtensionsTests.cs
dotnet/src/Connectors/Connectors.Weaviate.UnitTests/WeaviateServiceCollectionExtensionsTests.cs

If someone wants to consume just the IVectorizedSearch interface from DI it's useful to have helpers to allow easy registration of collections for these.
#8974
- Adding a DI helper for each collection type to register the collection interface and all search interfaces on it.

.Net: Add DI registration helpers for collections and search

---

dotnet/samples/Concepts/ChatCompletion/OpenAI_ChatCompletionStreaming.cs
dotnet/src/Connectors/Connectors.OpenAI.UnitTests/Services/OpenAIChatCompletionServiceTests.cs
dotnet/src/Connectors/Connectors.OpenAI.UnitTests/TestData/chat_completion_streaming_test_response.txt
dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.ChatCompletion.cs

Currently we have metadata for non-streaming results, and to be consistent, the same should be available for streaming for the final chunk.
- Resolves #6826

.Net: Adding usage metadata to OpenAI Streaming Chunks

---

python/pyproject.toml

After introducing entra auth as an option for AzureChatCompletion and AzureAI Inference, we need to make sure that the azure-identity library is installed by default as a dependency.
install azure-identity as a default dependency so that AzureChatCompletion doesn't break.

Python: Azure identity needs to be a default dependency

---

dotnet/samples/Concepts/Memory/VectorStore_GenericDataModel_Interop.cs
dotnet/samples/Concepts/README.md

The generic data model can be used instead of a custom data model when using the vector store implementations.
 
#8986
Adding a sample to show how to use the generic data model to upsert data and retrieve using custom and vice versa, to show the flexibility of the generic data model and how it is interchangeable and interoperable with a custom data model.

.Net: Add generic data model sample

---

python/semantic_kernel/contents/streaming_content_mixin.py

Exceptions are expected to happen when merging the item lists from two chat streaming contents. When all attempts fail, the new item will simply be added to the end of the list.
The `WARN` log level is too high for this event.
1. Reduce the log level of the event to `DEBUG`.
2. Add an additional log message for the event when all attempts have failed.

Python: Improve exception log message in streaming content merge item list

---

python/samples/concepts/agents/assistant_agent_file_manipulation_streaming.py
python/semantic_kernel/agents/open_ai/assistant_content_generation.py
python/semantic_kernel/agents/open_ai/open_ai_assistant_base.py
python/tests/unit/agents/test_open_ai_assistant_base.py
python/uv.lock

In the recent release of OpenAI Assistant streaming responses, there was a gap related to not exposing code interpreter output, when available.
This PR closes that gap, and adds the ability to yield messages that contain code input/output. A new concept sample was added to show this.
- Unit test coverage also added.

Python: Include streaming code output for OpenAI Assistants

---

docs/decisions/0055-dotnet-azureopenai-stable-version-strategy.md

This week (01-10-2024) OpenAI and Azure OpenAI released their first stable version and we need to bring some options ahead of us regarding how to move forward with the versioning strategy for the next releases of `OpenAI` and `AzureOpenAI` connectors which will also set the path moving forward with other connectors and providers versioning strategies.
This ADR brings different options how we can move forward thinking on the impact on the users and also how to keep a clear message on our strategy.
Currently, Azure Open AI GA package against what we were expecting choose remove many of the features previously available in preview packages from their first GA version.
This also requires us to rethink how we are going to proceed with our strategy for the following versions of our connectors. …

.Net: ADR - Connectors Versioning Strategy for Underlying SDKs

---

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreRecordCollection.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchTextSearchTests.cs
dotnet/src/IntegrationTests/TestSettings/Memory/AzureAISearchSetup.psm1

AzureAISearch has two ways of accessing search results.
- Switching to IAsyncEnumerable interface to improve performance.
- Switch to AzureOpenAI for integration test embeddings to remove need for key management.
- Fix small bug in powershell module to create azure ai search test infra
#9077

.Net: Use AsynEnumerable search interface for azure ai search.

---

dotnet/samples/GettingStartedWithProcesses/Step01/Step01_Processes.cs
dotnet/samples/GettingStartedWithProcesses/Step02/Step02_AccountOpening.cs
dotnet/src/Experimental/Process.Abstractions/KernelProcessEvent.cs
dotnet/src/Experimental/Process.Abstractions/KernelProcessEventVisibility.cs
dotnet/src/Experimental/Process.Abstractions/KernelProcessFunctionTarget.cs
dotnet/src/Experimental/Process.Core/Internal/EndStep.cs
dotnet/src/Experimental/Process.Core/ProcessBuilder.cs
dotnet/src/Experimental/Process.Core/ProcessFunctionTargetBuilder.cs
dotnet/src/Experimental/Process.Core/ProcessStepBuilder.cs
dotnet/src/Experimental/Process.Core/ProcessStepEdgeBuilder.cs
dotnet/src/Experimental/Process.LocalRuntime/LocalEvent.cs
dotnet/src/Experimental/Process.LocalRuntime/LocalKernelProcessContext.cs
dotnet/src/Experimental/Process.LocalRuntime/LocalMessage.cs
dotnet/src/Experimental/Process.LocalRuntime/LocalMessageFactory.cs
dotnet/src/Experimental/Process.LocalRuntime/LocalProcess.cs
dotnet/src/Experimental/Process.LocalRuntime/LocalStep.cs
dotnet/src/Experimental/Process.UnitTests/ProcessBuilderTests.cs
dotnet/src/Experimental/Process.UnitTests/ProcessStepBuilderTests.cs
dotnet/src/IntegrationTests/IntegrationTests.csproj
dotnet/src/IntegrationTests/Processes/ProcessTests.cs

This PR adds the concept of visibility to events within a process. There are two options, `Internal` which keeps the event within the process it's fired in, and `Public` which allows the event to bubble out of the process to parent processes or external systems. Events default to `Internal`. This allows a parent process to receive events that originate from within a sub-process.
Processes now expose targets for their external events. When a processes defines a route for an external event by calling `processBuilder.OnExternalEvent(...)...`, the target for this event can now be retrieved by calling `process.GetTargetForExternalEvent(...)`. This allows a parent process to route a step event to the specified entry event of the sub-process.
The `*KernelProcessContext` now exposes  a …

.NET: Processes support for sub-processes

---

dotnet/samples/Concepts/Search/VectorStore_TextSearch.cs
dotnet/src/SemanticKernel.Abstractions/Data/TextSearch/TextSearchResultLinkAttribute.cs
dotnet/src/SemanticKernel.Abstractions/Data/TextSearch/TextSearchResultNameAttribute.cs
dotnet/src/SemanticKernel.Abstractions/Data/TextSearch/TextSearchResultPropertyReader.cs
dotnet/src/SemanticKernel.Abstractions/Data/TextSearch/TextSearchResultValueAttribute.cs
dotnet/src/SemanticKernel.Core/Data/TextSearch/TextSearchResultPropertyReader.cs
dotnet/src/SemanticKernel.Core/Data/TextSearch/VectorStoreTextSearch.cs

Add attributes to add to a model which can be converted to a TextSearchResult.
This allows a `VectorStoreTextSearch` to be created without the need to provide mappers.

.Net: Add attributes to add to a model which can be converted to a TextSearchResult

---

dotnet/src/Experimental/Process.LocalRuntime/LocalStep.cs
dotnet/src/IntegrationTests/Processes/ProcessCycleTests.cs

There is a regression that is causing problems when a step is invoked multiple times. The issue stems from the initial inputs for a given Kernel Function being shallow cloned rather than deep cloned when initializing the input channels.
- Fixed issue by deep cloning the initial channel inputs when initializing the channel inputs.
- Added integration tests to verify the fix.

.Net: Process - Fixing issue with steps being invoked multiple times.

---

dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Services/AzureOpenAIChatCompletionServiceTests.cs
dotnet/src/Connectors/Connectors.OpenAI.UnitTests/Services/OpenAIChatCompletionServiceTests.cs
dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.ChatCompletion.cs

Resolves: https://github.com/microsoft/semantic-kernel/issues/8072
Resolves: https://github.com/microsoft/semantic-kernel/issues/8488
Azure Chat Completion with data service returns `400 (Bad Request) Invalid chat message detected: message content must be string` response when assistant message in chat history doesn't contain `content` property or when this property is an array of content items. This case is applicable for function calling, where AI model returns set of tools to call instead of message content.
This PR contains a change to set `content` property as an empty string only for cases when content doesn't exist (`null`).

.Net: Use empty string instead of null content in assistant message in Azure/OpenAI connectors

---

dotnet/src/Experimental/Process.LocalRuntime/LocalProcess.cs
dotnet/src/IntegrationTests/Processes/ProcessTests.cs

Fixing subprocesses bug where subprocess has getting triggered multiple times if having more than one external input event trigger.
Adding UTs to validate

.Net: Fixing subprocess triggered by multiple inputs unexpected behavior bug 

---

dotnet/Directory.Packages.props

System.Text.Json Version 8.0.4 is [flagged as vulnerable](https://github.com/advisories/GHSA-8g4q-xg66-9fp4) and needs to be updated.

.Net: Net: Bump System.Text.Json away from vulnerable package 8.0.4

---

dotnet/src/SemanticKernel.Abstractions/Data/VectorStoreGenericDataModel.cs

Some databases allow us to generate keys on the server, so when doing an upsert, a key doesn't have to be specified on the record.
This means that the key on the record should be nullable to enable this functionliaty.
- Removing the notnull constraint from the generic data model to support this scenario.

Remove notnull constraint from generic data model

---

dotnet/samples/GettingStartedWithProcesses/SharedSteps/ScriptedUserInputStep.cs
dotnet/samples/GettingStartedWithProcesses/Step01/Step01_Processes.cs
dotnet/samples/GettingStartedWithProcesses/Step02/Step02_AccountOpening.cs
dotnet/samples/GettingStartedWithProcesses/Step03/Step03_FoodPreparation.cs
dotnet/src/InternalUtilities/samples/InternalUtilities/BaseTest.cs

Noticed some tiny stuff I wanted to make available for review, separate from the _Agent_ sample.
- `LocalKernelProcessContext` is `IDisposable` - Update to incorporate `using` statement to ensure disposal (best practice)
- `Console.Write` not resulting any output (`TextWriter.Write(char value) is an empty virtual method that requires override...or in this case interception - https://github.com/microsoft/referencesource/blob/master/mscorlib/system/io/textwriter.cs#L193.)
- Simplify `ScriptedUserInputStep` abstraction.  State is never null and can be treated as such with a minor tweak.  (Null check in the sample could be misleading - it gave me momentary pause)
- Removed redundant `CreateKernelWithChatCompletion` method where present (already in base class)
- Simplified …

.Net: Processes - Sample Pattern Adjustments

---

dotnet/samples/GettingStartedWithProcesses/Step02/Step02_AccountOpening.cs
dotnet/samples/GettingStartedWithProcesses/Step03/Processes/FishAndChipsProcess.cs
dotnet/src/Experimental/Process.Core/ProcessEdgeBuilder.cs
dotnet/src/Experimental/Process.Core/ProcessStepEdgeBuilder.cs
dotnet/src/Experimental/Process.UnitTests/KernelProcessStateTests.cs
dotnet/src/Experimental/Process.UnitTests/ProcessBuilderTests.cs
dotnet/src/Experimental/Process.UnitTests/ProcessEdgeBuilderTests.cs
dotnet/src/Experimental/Process.UnitTests/ProcessStepBuilderTests.cs
dotnet/src/Experimental/Process.UnitTests/ProcessStepEdgeBuilderTests.cs
dotnet/src/Experimental/Process.UnitTests/ProcessTypeExtensionsTests.cs

Broadcasting the same event along multiple edges will likely be a common pattern (Estefanía and I both have utilized this pattern early).  A small tweak reduces the vebosity for this pattern.
- Returning a cloned `ProcessStepEdgeBuilder` when invoking `ProcessStepEdgeBuilderSendEventTo`
- Added unit-test
- Normalized unit-tests namespaces
- Worst cases there's a tiny bit of additional memory pressure on GC for the final un-used builder: One object with two object references that can be addressed in gen-0 collection.

.Net Processes - Fluent edge building

---

dotnet/src/Experimental/Process.Core/ProcessStepBuilder.cs
dotnet/src/Experimental/Process.LocalRuntime/LocalStep.cs
dotnet/src/Experimental/Process.UnitTests/ProcessStepBuilderTests.cs

Introduce support for `.OnError` with parity to `.OnResult`
- Developer shouldn't need to guess at naming convention for error handling.
- Passing full exception, not just message.
> I'd really like to see ability to define process-level error handling
> I like the `OnError` approach, but there are still a lot of cases where the _Process_ just stops w/o any information...this doesn't affect those cases and I'm not actively looking (I have seen quite a few actionable messages, however, which is great!)

.Net Processes - Expose OnError Event Handling

---

dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/AzureCosmosDBNoSQLVectorStoreRecordCollection.cs

Default index kind and distance function should be used when this information is not specified by the user in vector store record definition.

.Net: Added default index kind and distance function for Azure CosmosDB NoSQL connector

---

dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBConstants.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreCollectionCreateMapping.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreCollectionSearchMapping.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreRecordCollection.cs

Default index kind and distance function should be used when this information is not specified by the user in vector store record definition.

.Net: Added default index kind and distance function for Azure CosmosDB MongoDB connector

---

.github/workflows/dotnet-build-and-test.yml
dotnet/src/IntegrationTests/Plugins/Web/Google/GoogleTextSearchTests.cs

- `GoogleTextSearchTests` are currently disabled, removing the code which disables them.
- Adding the configuration to run integration tests using Google Web Search.

.Net: Enable the GoogleTextSearchTests

---

dotnet/docs/EXPERIMENTS.md
dotnet/src/Connectors/Connectors.UnitTests/Connectors.UnitTests.csproj
dotnet/src/InternalUtilities/src/Schema/KernelJsonSchemaBuilder.cs
dotnet/src/SemanticKernel.Abstractions/Contents/FunctionCallContentBuilder.cs
dotnet/src/SemanticKernel.Abstractions/Functions/KernelParameterMetadata.cs
dotnet/src/SemanticKernel.Abstractions/Functions/KernelReturnParameterMetadata.cs
dotnet/src/SemanticKernel.Abstractions/PromptTemplate/PromptTemplateConfig.cs
dotnet/src/SemanticKernel.Abstractions/SemanticKernel.Abstractions.csproj
dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFactory.cs
dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromMethod.cs
dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromPrompt.cs
dotnet/src/SemanticKernel.Core/Functions/KernelPluginFactory.cs
dotnet/src/SemanticKernel.Core/KernelExtensions.cs
dotnet/src/SemanticKernel.Core/SemanticKernel.Core.csproj
dotnet/src/SemanticKernel.UnitTests/SemanticKernel.UnitTests.csproj

This PR adds a new experimental category and annotates all new Native-AOT API with the Experimental attribute.

.Net: Mark new Native-AOT API as experimental

---

dotnet/src/Connectors/Connectors.AzureCosmosDBMongoDB.UnitTests/AzureCosmosDBMongoDBHotelModel.cs
dotnet/src/Connectors/Connectors.AzureCosmosDBMongoDB.UnitTests/AzureCosmosDBMongoDBVectorStoreRecordCollectionTests.cs
dotnet/src/Connectors/Connectors.AzureCosmosDBNoSQL.UnitTests/AzureCosmosDBNoSQLHotel.cs
dotnet/src/Connectors/Connectors.AzureCosmosDBNoSQL.UnitTests/AzureCosmosDBNoSQLVectorStoreRecordCollectionTests.cs
dotnet/src/Connectors/Connectors.Weaviate.UnitTests/WeaviateHotel.cs
dotnet/src/Connectors/VectorData.Abstractions/RecordAttributes/VectorStoreRecordVectorAttribute.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreFixture.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBNoSQL/AzureCosmosDBNoSQLHotel.cs
dotnet/src/IntegrationTests/Connectors/Memory/Pinecone/PineconeAllTypes.cs
dotnet/src/IntegrationTests/Connectors/Memory/Pinecone/PineconeHotel.cs
dotnet/src/IntegrationTests/Connectors/Memory/Pinecone/PineconeVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorStoreFixture.cs
dotnet/src/IntegrationTests/Connectors/Memory/Weaviate/WeaviateHotel.cs
dotnet/src/SemanticKernel.UnitTests/Data/VectorStoreRecordPropertyReaderTests.cs

There are connectors, where `IndexKind` is not required (e.g. it's not supported yet or there is only one index kind). This PR contains a change to add overload to `VectorStoreRecordVectorAttribute` which doesn't require `IndexKind` parameter and re-order parameters in existing constructor to keep `IndexKind` parameter as last one.

.Net: Re-ordered parameters in VectorStoreRecordVectorAttribute

---

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/Connectors.Memory.AzureAISearch.csproj
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/Connectors.Memory.AzureCosmosDBMongoDB.csproj
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/Connectors.Memory.AzureCosmosDBNoSQL.csproj
dotnet/src/Connectors/Connectors.Memory.InMemory/Connectors.Memory.InMemory.csproj
dotnet/src/Connectors/Connectors.Memory.Pinecone/Connectors.Memory.Pinecone.csproj
dotnet/src/Connectors/Connectors.Memory.Qdrant/Connectors.Memory.Qdrant.csproj
dotnet/src/Connectors/Connectors.Memory.Redis/Connectors.Memory.Redis.csproj
dotnet/src/Connectors/Connectors.Memory.Weaviate/Connectors.Memory.Weaviate.csproj

.Net: Change version suffix for memory connectors which implement IVectorStore

---

.github/workflows/dotnet-build-and-test.yml
dotnet/src/IntegrationTests/Data/InMemoryVectorStoreTextSearchTests.cs

`InMemoryTextSearchTests` are currently disabled, removing the code which disables them.

.Net: Enable the InMemoryTextSearchTests

---

dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Services/AzureOpenAIChatCompletionServiceTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/TestData/chat_completion_streaming_single_function_call_empty_assistance_response.txt
dotnet/src/Connectors/Connectors.OpenAI.UnitTests/Connectors.OpenAI.UnitTests.csproj
dotnet/src/Connectors/Connectors.OpenAI.UnitTests/Core/OpenAIFunctionToolCallTests.cs
dotnet/src/Connectors/Connectors.OpenAI.UnitTests/Services/OpenAIChatCompletionServiceTests.cs
dotnet/src/Connectors/Connectors.OpenAI.UnitTests/TestData/chat_completion_streaming_single_function_call_empty_assistance_response.txt
dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.ChatCompletion.cs
dotnet/src/Connectors/Connectors.OpenAI/Core/OpenAIFunctionToolCall.cs

**1. Why is this change required?**
This change is required to prevent null pointer exceptions caused by invalid or empty function argument updates, which could lead to system crashes or unexpected behavior during runtime.
**2. What problem does it solve?**
It addresses the issue where the `FunctionArgumentsUpdate` was not being properly validated, causing the Semantic Kernel to throw a `System.ArgumentNullException`. This update ensures proper validation of function arguments before processing.
**3. What scenario does it contribute to?**
It improves the stability and reliability of tool call functions, particularly when interacting with external services like OpenAI, ensuring that memory operations are only executed on valid and non-empty inputs.
This PR resolves #9212.
- Enhanced the …

.Net: Fix: Enhance Function Argument Validation to Prevent Null Argument Exceptions in Tool Calls.

---

dotnet/src/Agents/OpenAI/Internal/AssistantThreadActions.cs
dotnet/src/IntegrationTests/Agents/MixedAgentTests.cs
dotnet/src/IntegrationTests/Agents/OpenAIAssistantAgentTests.cs

Fixes: https://github.com/microsoft/semantic-kernel/issues/9245
Assistant incorrectly assigning `Tool` role to function-call _and_ function-result.  Function-call should be `Assistant`.
Added validation in integration tests.

.Net Agents - Fixed Assistant Function-Call Message Role

---

dotnet/samples/GettingStartedWithProcesses/README.md
dotnet/samples/GettingStartedWithProcesses/Step03/Processes/FishAndChipsProcess.cs
dotnet/samples/GettingStartedWithProcesses/Step03/Processes/FishSandwichProcess.cs
dotnet/samples/GettingStartedWithProcesses/Step03/Processes/FriedFishProcess.cs
dotnet/samples/GettingStartedWithProcesses/Step03/Processes/PotatoFriesProcess.cs
dotnet/samples/GettingStartedWithProcesses/Step03/Processes/SingleFoodItemProcess.cs
dotnet/samples/GettingStartedWithProcesses/Step03/Step03a_FoodPreparation.cs
dotnet/samples/GettingStartedWithProcesses/Step03/Step03b_FoodOrdering.cs

- Fixing Processes Food Samples links to respective diagrams + adding some steps specific names
- Reorganizing Process Food Samples in 2 files -> allows to build concepts in more detail later: more samples to be added in another PR in the near future

.Net: Fixing Processes food samples diagram links + step name fix

---

dotnet/samples/GettingStartedWithProcesses/README.md
dotnet/samples/GettingStartedWithProcesses/Step03/Processes/FriedFishProcess.cs
dotnet/samples/GettingStartedWithProcesses/Step03/Processes/PotatoFriesProcess.cs
dotnet/samples/GettingStartedWithProcesses/Step03/Step03a_FoodPreparation.cs
dotnet/samples/GettingStartedWithProcesses/Step03/Steps/CutFoodWithSharpeningStep.cs
dotnet/samples/GettingStartedWithProcesses/Step03/Steps/FryFoodStep.cs
dotnet/samples/GettingStartedWithProcesses/Step03/Steps/GatherIngredientsStep.cs

Adding Stateful Food Preparation Samples
- refactoring existing gatherIngredients step
- adding stateful gatherIngredients step
- adding stateful cutFoodStep with knifeSharpening  to showcase state persistance and use across functions in same step
- adding samples making use of different processes - state resets - and the same process multiple times - last state gets reused

.Net: Processes - Stateful food preparation samples

---

python/semantic_kernel/functions/kernel_function.py

- This is fixing an issue with the default opentelemery metric in KernelFunction. This issue is with SemanticKernel version >= 1.8
causing 
`TypeError: cannot pickle '_thread.RLock' object`
when importing SemanticKernel
- This is blocking us from updating to the latest SemanticKernel version.
It is difficult to reproduce outside my application code. But is seems to be the same issue mentioned in 
#9057 and #9012 
changing to a Field with a default factory solve the issue.
- Updating the default metrics value to use a Field with a default_factory

Python: Fix issue with default opentelemetry metric in pydantic base model

---

dotnet/nuget/nuget-package.props
dotnet/src/Connectors/VectorData.Abstractions/VectorData.Abstractions.csproj

The vectordata.abstractions.dll had the same version number as the other SK dlls, which is incorrect.
It should have a version number matching it's nuget version number.
- Setting the version number of the vectordata.abstractions.dll to 9.0.0.0
- Updating the vectordata.abstractions nuget version to today's date.
- Upping the SK version to 1.24.1

.Net: Set dll version number for vectordata.abstractions.

---

dotnet/src/Connectors/Connectors.AzureCosmosDBNoSQL.UnitTests/AzureCosmosDBNoSQLVectorStoreCollectionQueryBuilderTests.cs
dotnet/src/Connectors/Connectors.AzureCosmosDBNoSQL.UnitTests/AzureCosmosDBNoSQLVectorStoreRecordCollectionTests.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/AzureCosmosDBNoSQLVectorStoreCollectionQueryBuilder.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/AzureCosmosDBNoSQLVectorStoreRecordCollection.cs

If `VectorSearchOptions.Skip` value is zero, in current implementation we are sending `LIMIT 3 OFFSET 0` to CosmosDB NoSQL. It appeared that using `SELECT TOP 3` instead of `LIMIT 3` works more efficiently. This PR contains a change to use `SELECT TOP` instead of `LIMIT/OFFSET` where `OFFSET` value is zero. However, `LIMIT/OFFSET` is still used when `OFFSET` is greater than zero, because `OFFSET` can't be used with `TOP` parameter, it can be used only with `LIMIT`.
This PR also contains a small fix for cases when collection is created with `IndexingMode.None`.

.Net: Improved vector search query in Azure CosmosDB NoSQL connector

---

dotnet/samples/GettingStartedWithProcesses/Step04/SchemaGenerator.cs
dotnet/src/Connectors/VectorData.Abstractions/VectorStorage/IVectorStore.cs
dotnet/src/SemanticKernel.AotTests/SemanticKernel.AotTests.csproj
dotnet/src/SemanticKernel.Core/Data/ServiceCollectionExtensions.cs
dotnet/src/SemanticKernel.Core/Data/TextSearch/TextSearchExtensions.cs
dotnet/src/SemanticKernel.Core/Data/TextSearch/TextSearchKernelBuilderExtensions.cs
dotnet/src/SemanticKernel.Core/Data/TextSearch/TextSearchResultPropertyReader.cs
dotnet/src/SemanticKernel.Core/Data/TextSearch/TextSearchServiceCollectionExtensions.cs
dotnet/src/SemanticKernel.Core/Data/TextSearch/VectorStoreTextSearch.cs
dotnet/src/SemanticKernel.Core/Data/VolatileVectorStore.cs
dotnet/src/SemanticKernel.Core/Data/VolatileVectorStoreCollectionSearchMapping.cs
dotnet/src/SemanticKernel.Core/Data/VolatileVectorStoreExtensions.cs
dotnet/src/SemanticKernel.Core/Data/VolatileVectorStoreRecordCollection.cs
dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromMethod.cs
dotnet/src/SemanticKernel.Core/Functions/KernelFunctionMetadataFactory.cs
dotnet/src/SemanticKernel.Core/Functions/KernelPluginFactory.cs
dotnet/src/SemanticKernel.UnitTests/Data/TextSearchExtensionsTests.cs
dotnet/src/SemanticKernel.UnitTests/Functions/KernelFunctionFromMethodTests1.cs
dotnet/src/SemanticKernel.UnitTests/Functions/KernelFunctionMetadataFactoryTests.cs
dotnet/src/SemanticKernel.UnitTests/Functions/KernelPluginFactoryTests.cs
dotnet/src/SemanticKernel.UnitTests/SemanticKernel.UnitTests.csproj

This PR adds AOT compatibility to the newly introduced text search API and to the new kernel function factory methods.  
1. Removes a few no longer relevant `DynamicallyAccessedMembers` annotations for the `TRecord` generic parameter of the vector store API.  
2. Adds new AOT-compatible overloads to the new text search functionality and annotates the existing overload as not AOT-compatible.  
3. Adds new AOT-compatible overloads to the kernel function factory methods and annotates the existing overload as not AOT-compatible.  
4. Annotates the `Type` parameter of `TextSearchResultPropertyReader` with the `[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties)]` attribute to inform the AOT trimmer not to trim the public properties of the type the class works with. The …

.Net: Make new API of Core package AOT compatible

---

python/semantic_kernel/agents/open_ai/assistant_content_generation.py
python/semantic_kernel/agents/open_ai/open_ai_assistant_base.py
python/semantic_kernel/contents/binary_content.py
python/tests/unit/agents/test_open_ai_assistant_base.py

The streaming function call content, function result content, or code interpreter output was not being streamed back to the caller chunk by chunk.
This PR enabled yielding the proper chunks to the caller based on handling the `thread.run.step.delta` event.
- Fixes #9352 
- Adds test coverage
- Fixes a separate mypy issue related to BinaryContent

Python: Return streaming tool call output to the caller

---

dotnet/src/Experimental/Process.Runtime.Dapr/Actors/ProcessActor.cs
dotnet/src/Experimental/Process.Runtime.Dapr/Actors/StepActor.cs

The PR ensures that the Ids of steps within a Process are scoped to the processes when run within the Dapr runtime. This is required for running multiple instances of the same processes concurently since the actors are "universal" within the Dapr runtime and are identified only by their Id and Type.

.Net: Scoping step Ids to a process.

---

python/samples/concepts/agents/assistant_agent_file_manipulation_streaming.py
python/semantic_kernel/agents/open_ai/azure_assistant_agent.py
python/semantic_kernel/agents/open_ai/open_ai_assistant_agent.py
python/tests/unit/agents/test_azure_assistant_agent.py
python/tests/unit/agents/test_open_ai_assistant_agent.py

Today, when creating an OpenAI Assistant Agent, one can specify vector store file names or code interpreter files names (paths to files) that will be uploaded and used. If one wants to include a file ID that was already uploaded, this isn't possible.
This PR allows for users to specify file IDs that were already uploaded.
- Closes #9159

Python: Allow caller to specify file ids that already exist when creating assistant

---

dotnet/src/Functions/Functions.OpenApi/OpenApi/OpenApiDocumentParser.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/OpenApiDocumentParserV20Tests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/OpenApiDocumentParserV30Tests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/OpenApiDocumentParserV31Tests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/TestPlugins/documentV2_0.json
dotnet/src/Functions/Functions.UnitTests/OpenApi/TestPlugins/documentV3_0.json
dotnet/src/Functions/Functions.UnitTests/OpenApi/TestPlugins/documentV3_1.yaml

This PR fixes the issue of mapping the `required` flag in the OpenAPI document to the `IsRequired` property of the `RestApiOperationPayloadProperty` model class, which manifested for descendants of the root payload properties.

.Net: Fix mapping issue of the required payload properties

---

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/AzureCosmosDBNoSQLVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoDBVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.Sqlite/SqliteVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStore.cs

If someone supplies a factory for constructing vector store record collections, this means that they may want to
use a decorator that changes the key type of the default record collection implementation.
This means that we shouldn't restrict the key types unless someone is using the default implementation.
- Remove check for key types for the case where someone supplied a record collection factory.

.Net: VectorStore: Allow any key when using a custom collection factory

---

dotnet/src/Experimental/Process.LocalRuntime/LocalProcess.cs

When using  `async`/`await`, there is no guarantee that the method will actually run asynchronously. The internal implementation is free to return using a completely synchronous path.
Add `Task.Yield()` when starting `LocalProcess` to encourage the use of a separate sychronization context from the current one.
- https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.yield?view=net-8.0
- https://finchett.com/understanding-task-yield/
- https://www.webdevtutor.net/blog/c-sharp-taskyield-example

.Net Processes - Facilitate Parallel Execution of LocalProcess

---

dotnet/Directory.Packages.props
dotnet/src/Experimental/Process.LocalRuntime/LocalKernelProcessContext.cs
dotnet/src/Experimental/Process.LocalRuntime/LocalProcess.cs
dotnet/src/Experimental/Process.LocalRuntime/LocalStep.cs
dotnet/src/Experimental/Process.Runtime.Dapr/Actors/ProcessActor.cs
dotnet/src/Experimental/Process.Runtime.Dapr/Actors/StepActor.cs
dotnet/src/Experimental/Process.UnitTests/Runtime.Local/LocalProcessTests.cs
dotnet/src/InternalUtilities/process/Abstractions/ExceptionExtensions.cs
dotnet/src/InternalUtilities/process/Abstractions/StepExtensions.cs

Throwing and logging exceptions in the runtime is a little verbose.  It also creates quite a few conditional arcs for test coverage (or lack there-of).  Utility method streamlines this pattern and eliminates all but one conditional arc.
```c#
throw new KernelException("message").Log(this._logger);
```
Note:  Considered this pattern, opted on favoring the _never-null_ object as the root of the extention method.
```c#
throw this._logger.LogException(new KernelException("message"));
```
- Introduced shared exception extension to streamline logging and minimize conditional arcs.
- Switched to `LogError` override that accepts the exception object.
- Initialize logger based on `Kernel.LoggingFactory` (was previously always null)
- Opportunistically added parameter names to usage of `Verify`
- …

.Net Processes - Update Runtime Exception Handling / Logging

---

python/semantic_kernel/connectors/ai/open_ai/prompt_execution_settings/open_ai_prompt_execution_settings.py
python/semantic_kernel/connectors/ai/open_ai/services/open_ai_handler.py
python/tests/unit/connectors/ai/open_ai/services/test_azure_chat_completion.py
python/tests/unit/connectors/ai/open_ai/services/test_open_ai_chat_completion_base.py

OpenAI / Azure OpenAI released the ability to specify the `parallel_tool_calls` = True | False boolean attribute on the prompt execution settings in July. This was never brought into SK Python.
Further, there appears to be a pesky bug related to function calling where enabling parallel tool calls can cause 500s. The only way to get around this is to disable parallel function calling. This has been both tested on the Azure Chat Completion and OpenAI Chat Completion code and works well -- the chat history shows the synchronous function calls if multiple tool calls are required.
Add the `parallel_tool_calls` attribute on the OpenAIChatPromptExecutionExecution settings, which are also used by the AzureChatCompletionClass.
- Closes #9478
- Adds unit tests for this prompt execution setting

Python: Add parallel_tool_calls attribute to OpenAI chat prompt execution settings

---

dotnet/samples/Concepts/Filtering/FunctionInvocationFiltering.cs
dotnet/samples/Concepts/Filtering/TelemetryWithFilters.cs
dotnet/src/Connectors/Connectors.MistralAI.UnitTests/Client/MistralClientTests.cs
dotnet/src/Connectors/Connectors.MistralAI/Client/MistralClient.cs
dotnet/src/Connectors/Connectors.OpenAI.UnitTests/Core/AutoFunctionInvocationFilterTests.cs
dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.ChatCompletion.cs
dotnet/src/InternalUtilities/connectors/AI/FunctionCalling/FunctionCallsProcessor.cs
dotnet/src/SemanticKernel.Abstractions/Filters/AutoFunctionInvocation/AutoFunctionInvocationContext.cs
dotnet/src/SemanticKernel.Abstractions/Filters/Function/FunctionInvocationContext.cs
dotnet/src/SemanticKernel.Abstractions/Filters/Prompt/PromptRenderContext.cs
dotnet/src/SemanticKernel.Abstractions/Functions/KernelFunction.cs
dotnet/src/SemanticKernel.Abstractions/Kernel.cs
dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromPrompt.cs
dotnet/src/SemanticKernel.UnitTests/Filters/FunctionInvocationFilterTests.cs
dotnet/src/SemanticKernel.UnitTests/Filters/PromptRenderFilterTests.cs
dotnet/src/SemanticKernel.UnitTests/Utilities/AIConnectors/FunctionCallsProcessorTests.cs

Resolves: https://github.com/microsoft/semantic-kernel/issues/7336
This PR adds a boolean flag to identify whether a filter is invoked within streaming or non-streaming mode. This provides an ability to use the same filter for both scenarios and access filter context data in easier way based on used mode.

.Net: Added a streaming flag to filter context models

---

dotnet/samples/Concepts/FunctionCalling/FunctionCalling.cs
dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Services/AzureOpenAIChatCompletionServiceTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Core/AzureClientCore.ChatCompletion.cs
dotnet/src/Connectors/Connectors.OpenAI.UnitTests/Services/OpenAIChatCompletionServiceTests.cs
dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.ChatCompletion.cs
dotnet/src/Functions/Functions.UnitTests/Yaml/PromptExecutionSettingsTypeConverterTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatCompletion_AutoFunctionChoiceBehaviorTests.cs
dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAIChatCompletion_AutoFunctionChoiceBehaviorTests.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/FunctionChoiceBehaviorOptions.cs
dotnet/src/SemanticKernel.UnitTests/AI/FunctionChoiceBehaviors/FunctionChoiceBehaviorDeserializationTests.cs

This PR adds the `FunctionChoiceBehaviorOptions.AllowParallelCalls` option and updates {Azure} OpenAI AI connectors to support it. This option instructs the AI model to generate multiple function calls in a single response when set to true.
_"This is especially useful if executing the given functions takes a long time. For example, the model may call functions to get the weather in three different locations at the same time, which will result in a message with three function calls in the tool_calls array."_ **Source** - [Configuring parallel function calling](https://platform.openai.com/docs/guides/function-calling/configuring-parallel-function-calling)
Closes: https://github.com/microsoft/semantic-kernel/issues/6636

.Net: Parallel function calls option

---

dotnet/src/Experimental/Process.Core/ProcessStepBuilder.cs
dotnet/src/Experimental/Process.LocalRuntime/LocalProcess.cs
dotnet/src/Experimental/Process.Runtime.Dapr/Actors/ProcessActor.cs
dotnet/src/Experimental/Process.Runtime.Dapr/Actors/StepActor.cs
dotnet/src/Experimental/Process.Runtime.Dapr/DaprStepInfo.cs

This PR addresses an issue when running a nested process in the Dapr runtime. After this changes, the Dapr runtime fully supports nested processes with the ability to pass events in both directions.

.Net Processes: Fixing an issue with nested processes in Dapr runtime.

---

dotnet/SK-dotnet.sln
dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.cs
dotnet/src/InternalUtilities/connectors/AI/FunctionCalling/FunctionCallsProcessor.cs
dotnet/src/InternalUtilities/connectors/AI/FunctionCalling/FunctionCallsProcessorLoggerExtensions.cs
dotnet/src/SemanticKernel.Abstractions/Functions/KernelFunction.cs
dotnet/src/SemanticKernel.Abstractions/Functions/KernelFunctionLogMessages.cs
dotnet/src/SemanticKernel.UnitTests/Functions/KernelFunctionLogMessagesTests.cs

This PR improves the existing logging functionality in both `FunctionCallsProcessor` and `KernelFunction` by logging additional contextual information, such as function details, function choice behavior configuration, and function call details, to simplify troubleshooting.

.Net: Improve logging for function calls processor and kernel function

---

dotnet/src/Connectors/Connectors.OpenAI.UnitTests/Services/OpenAIChatCompletionServiceTests.cs
dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.ChatCompletion.cs

Resolves: https://github.com/microsoft/semantic-kernel/issues/9416
When C# type is passed as a response format to OpenAI chat completion service, we use the type name as [JSON schema name](https://platform.openai.com/docs/api-reference/chat/create#chat-create-response_format). When the type is generic, its name will contain characters that are not allowed in JSON schema name according to OpenAI API. This PR fixes the issue by replacing invalid characters with empty string.

.Net: Fixed JSON schema name in Structured Outputs for generic types

---

dotnet/samples/Concepts/Filtering/MaxTokensWithFilters.cs
dotnet/samples/Concepts/README.md

This change is required to properly print exception details when logging an error message, which helps debugging.
Fixes printing of debugging information used [here](https://github.com/microsoft/semantic-kernel/blob/db45cfa7cf1b0f00aa3b1414e4d018ba816b8960/python/semantic_kernel/processes/local_runtime/local_process.py#L189) where the exception details were ignored due to the usage of bad syntax.

Python: Fixes displaying of error message to properly show the exception details

---

dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStore.cs
dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorStoreTests.cs

We allow users to provide a setting to indicate whether they are using a collection which has named vectors or not when using Qdrant.
#9520
- Fixing a bug where the has named vectors setting wasn't passed from the vector store to the collection in GetCollection.

.Net: Fix bug where has named vectors wasn't passed to record collection in GetCollection.

---

dotnet/src/Functions/Functions.OpenApi/OpenApiKernelPluginFactory.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/Extensions/OpenApiKernelExtensionsTests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/OpenApiKernelPluginFactoryTests.cs

Request for additional metadata for OpenAPI Kernel functions
Closes #9496 
Include the operation path in the `KernelFunction.Metadata`

.Net: Include the operation path in the KernelFunction.Metadata

---

dotnet/src/Connectors/Connectors.Google.UnitTests/Core/Gemini/Clients/GeminiChatGenerationTests.cs
dotnet/src/Connectors/Connectors.Google.UnitTests/Core/Gemini/GeminiRequestTests.cs
dotnet/src/Connectors/Connectors.Google.UnitTests/GeminiPromptExecutionSettingsTests.cs
dotnet/src/Connectors/Connectors.Google/Core/Gemini/Models/GeminiRequest.cs
dotnet/src/Connectors/Connectors.Google/GeminiPromptExecutionSettings.cs

**Why is this change required?**
This change is required to enhance the functionality of audio processing in the Semantic Kernel by allowing the inclusion of timestamps in audio responses.
**What problem does it solve?**
It resolves the limitation of missing audio timestamp support in the `GeminiPromptExecutionSettings`, which has been a significant blocker for developers trying to utilize audio prompts effectively.
**What scenario does it contribute to?**
This contribution is particularly useful for applications that require precise audio response management, enabling better synchronization and analysis of audio data in real-time scenarios.
If it fixes an open issue, please link to the issue here.
#9500
This contribution adds a new feature that allows audio responses to include …

.Net: Add AudioTimestamp Property to GeminiPromptExecutionSettings

---

dotnet/src/Functions/Functions.OpenApi/Model/RestApiOperation.cs
dotnet/src/Functions/Functions.OpenApi/OpenApiKernelPluginFactory.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/Extensions/OpenApiKernelExtensionsTests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/OpenApiKernelPluginFactoryTests.cs

Update for #9496 to include the `RestApiOperation` in the `KernelFunction.MetaData`
This will help us avoid having to add all `RestApiOperation` properties individually to metadata.

.Net: Include the operation in the KernelFunction.Metadata

---

dotnet/src/Functions/Functions.OpenApi/Model/RestApiInfo.cs
dotnet/src/Functions/Functions.OpenApi/Model/RestApiOperation.cs
dotnet/src/Functions/Functions.OpenApi/Model/RestApiOperationExpectedResponse.cs
dotnet/src/Functions/Functions.OpenApi/Model/RestApiOperationParameter.cs
dotnet/src/Functions/Functions.OpenApi/Model/RestApiOperationParameterLocation.cs
dotnet/src/Functions/Functions.OpenApi/Model/RestApiOperationParameterStyle.cs
dotnet/src/Functions/Functions.OpenApi/Model/RestApiOperationPayload.cs
dotnet/src/Functions/Functions.OpenApi/Model/RestApiOperationPayloadProperty.cs
dotnet/src/Functions/Functions.OpenApi/Model/RestApiOperationServer.cs
dotnet/src/Functions/Functions.OpenApi/Model/RestApiOperationServerVariable.cs

Taking into account that the OpenAPI model classes have become exposed through the `KernelFunction.Metadata` property and that there could be requests to change their public API surface, it makes sense to label them as experimental to communicate the potential changes to the consumers of the classes.
Related task: https://github.com/microsoft/semantic-kernel/issues/6884

.Net: Make OpenApi model classes experimental

---

dotnet/src/Agents/OpenAI/Internal/AssistantThreadActions.cs
dotnet/src/Agents/OpenAI/RunPollingOptions.cs

Assistant polling not propertly responding to terminal error conditions.
Fixes: https://github.com/microsoft/semantic-kernel/issues/9579
- Added explicit check for cancelling state: Invoke, InvokeStreaming, & Polling loops
- Discriminate on different exception modes when polling
- Ensure stale run state isn't evaluated in polling loop
- Remove initial polling delay

.Net Agents - Fix polling cycle to properly evaluate failure mode on exception

---

dotnet/src/SemanticKernel.Abstractions/Contents/FunctionCallContentBuilder.cs
dotnet/src/SemanticKernel.UnitTests/Contents/FunctionCallBuilder/FunctionCallContentBuilderTests.cs

Closes #9567 
The fix handles the case where a streaming update contains an empty string for the function name. I haven't been able to reproduce the scenario where this happens and I have asked the issue creator for more information. The function name has a max size of 64 chars and when I use that the function isn't split over multiple streaming responses.
Referencing the approach shown here: https://community.openai.com/t/functions-calling-with-streaming/305742

.Net: Don't allow function name/id to be overwritten with an empty string

---

docs/decisions/0054-processes.md

The `markdown-link-check` tool fails - [32656031279](https://github.com/microsoft/semantic-kernel/actions/runs/11723502773/job/32656031279?pr=9595) trying to access the broken link - [web.stanford.edu](https://web.stanford.edu/~rezab/classes/cme323/S15/notes/lec8.pdf)
This PR comments out the link until the working one is found.

Comment out broken link

---

python/samples/concepts/README.md
python/samples/concepts/chat_history/serialize_chat_history.py
python/semantic_kernel/contents/kernel_content.py
python/tests/unit/contents/test_chat_history.py

There's been an error for a while where serializing the chat history leads to the following error:
```
PydanticSerializationError(Error serializing to JSON: TypeError: 'MockValSer' object 
cannot be converted to 'SchemaSerializer')}
```
This is due to the fact that we're trying to do a model dump of an object that we don't have a Pydantic model for as the `inner_content` type is `Any`. Most, if not all, of the `inner_content` info is already included in our `ChatMessageContent`, therefore we're excluding this attribute from serialization. 
Note: if you require the information in this `inner_content` attribute, you will be responsible for grabbing the content before serializing the chat history, as it won't be included.
This PR excludes the `inner_content` from the `model_dump()`, …

Python: Exclude the KernelContent's inner_content as it breaks serializing the model

---

dotnet/Directory.Packages.props

Reverting to 0.4.0 as the strategy to upgrade to 0.5.0 is not ready yet, the resource management of the new version adds some extra complexity to the caller that needs to be better addressed in a future PR.

.Net: Reverting Onnx from 0.5.0 to 0.4.0

---

python/.cspell.json
python/samples/concepts/memory/new_memory.py
python/semantic_kernel/connectors/memory/azure_ai_search/azure_ai_search_collection.py
python/semantic_kernel/connectors/memory/in_memory/in_memory_collection.py
python/semantic_kernel/connectors/memory/qdrant/qdrant_collection.py
python/semantic_kernel/data/vector_search/vector_search.py
python/semantic_kernel/data/vector_storage/vector_store_record_collection.py
python/semantic_kernel/utils/list_handler.py
python/tests/unit/connectors/memory/in_memory/test_in_memory.py
python/tests/unit/connectors/memory/qdrant/test_qdrant.py

Adds the vector search functions to the existing QdrantCollection.
Currently only support VectorizedSearch.

Python: introducing Vector Search for Qdrant Collection

---

dotnet/src/Functions/Functions.OpenApi/AssemblyInfo.cs
dotnet/src/Functions/Functions.OpenApi/Extensions/OpenApiFunctionExecutionParameters.cs
dotnet/src/Functions/Functions.OpenApi/Functions.OpenApi.csproj
dotnet/src/Functions/Functions.OpenApi/HttpResponseContentReader.cs
dotnet/src/Functions/Functions.OpenApi/HttpResponseContentReaderContext.cs
dotnet/src/Functions/Functions.OpenApi/OpenApi/OpenApiDocumentParser.cs
dotnet/src/Functions/Functions.OpenApi/OpenApi/OpenApiDocumentParserOptions.cs
dotnet/src/Functions/Functions.OpenApi/OpenApi/OperationSelectionPredicateContext.cs

Promote Functions.OpenApi package to preview. Closes: https://github.com/microsoft/semantic-kernel/issues/9636

.Net: Promote OpenAPI package to preview

---

python/samples/concepts/memory/new_memory.py
python/semantic_kernel/connectors/memory/azure_cosmos_db/__init__.py
python/semantic_kernel/connectors/memory/azure_cosmos_db/azure_cosmos_db_no_sql_base.py
python/semantic_kernel/connectors/memory/azure_cosmos_db/azure_cosmos_db_no_sql_collection.py
python/semantic_kernel/connectors/memory/azure_cosmos_db/azure_cosmos_db_no_sql_settings.py
python/semantic_kernel/connectors/memory/azure_cosmos_db/utils.py
python/tests/unit/connectors/memory/azure_cosmos_db/test_azure_cosmos_db_no_sql_collection.py

Adds the search functions for Cosmos DB NoSQL.
Closes #6835 
Adds the search pieces and turns out the upsert cannot work cross partition key with execute batch, so refactored to using gather(upsert).

Python: Introducing search for CosmosDB NoSQL Collections

---

dotnet/src/Functions/Functions.OpenApi/OpenApi/OpenApiDocumentParser.cs
dotnet/src/Functions/Functions.UnitTests/Functions.UnitTests.csproj
dotnet/src/Functions/Functions.UnitTests/OpenApi/OpenApiKernelPluginFactoryTests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/TestPlugins/multipart-form-data.json

Closes #8971 
Operations with unsupported content types should be ignored rather than causing the import to fail.

.Net: ImportPluginFromOpenApiAsync will ignore operations with unsupported content types

---

dotnet/src/Connectors/Connectors.Google/Core/ClientBase.cs
dotnet/src/Connectors/Connectors.Google/Core/Gemini/Clients/GeminiChatCompletionClient.cs
dotnet/src/Connectors/Connectors.HuggingFace/Core/HuggingFaceClient.cs
dotnet/src/Connectors/Connectors.HuggingFace/Core/HuggingFaceMessageApiClient.cs
dotnet/src/Connectors/Connectors.Memory.Chroma/ChromaClient.cs
dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeClient.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorDbClient.cs
dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateMemoryStore.cs
dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.MistralAI/Client/MistralClient.cs
dotnet/src/Connectors/Connectors.OpenAI/Services/OpenAIFileService.cs
dotnet/src/Functions/Functions.OpenApi/DocumentLoader.cs
dotnet/src/Functions/Functions.OpenApi/RestApiOperationRunner.cs
dotnet/src/InternalUtilities/src/Http/HttpContentExtensions.cs
dotnet/src/Plugins/Plugins.Core/HttpPlugin.cs
dotnet/src/Plugins/Plugins.Web/Bing/BingConnector.cs
dotnet/src/Plugins/Plugins.Web/Bing/BingTextSearch.cs
dotnet/src/Plugins/Plugins.Web/WebFileDownloadPlugin.cs

Signed-off-by: Vincent Biret <vibiret@microsoft.com>

.Net: fix: forwards cancellation token to outbound connections to free up resources upon cancellation

---

dotnet/src/Experimental/Orchestration.Flow/Execution/FlowExecutor.cs
dotnet/src/Planners/Planners.OpenAI/Stepwise/FunctionCallingStepwisePlanner.cs

This pull request adds conditions to avoid awaiting a delay task if the delays is zero ms to reduce unnecessary allocs/context switching/etc...

.Net: chore: avoid awaiting delay if its zero

---

dotnet/src/SemanticKernel.UnitTests/Functions/KernelFunctionFromPromptTests.cs

.Net: Add unit test to confirm 429 exception handling

---

python/pyproject.toml
python/uv.lock

The current pydantic pinned syntax is `"pydantic ~= 2.0<2.10",`; however on package publish, Pypi throws a 400. The correct syntax should be: `"pydantic >=2.0,<2.10",`
Updates pyproject.toml syntax for pinned pydantic version.

Python: Fix syntax for pinned pydantic package.

---

dotnet/samples/GettingStartedWithProcesses/Step04/Step04_AgentOrchestration.cs

Update sample `Step04_AgentOrchestration` to correctly specify the name of the function parameter.
Fixes: https://github.com/microsoft/semantic-kernel/issues/9778
Sample specified parameter name `exception` but the actual name had been refactored to `error`.

.Net Processes - Sync parameter name for error handler

---

dotnet/Directory.Packages.props

It's an anti-pattern, blocking developers from upgrading.
https://github.com/microsoft/semantic-kernel/issues/9802

.Net: Stop setting upper bound on nuget references

---

dotnet/src/Connectors/Connectors.AzureOpenAI.UnitTests/Services/AzureOpenAIChatCompletionServiceTests.cs
dotnet/src/Connectors/Connectors.AzureOpenAI/Core/AzureClientCore.cs

Add new version `2024-09-01-preview` option available in Azure.AI.OpenAI 2.0.0-beta.2

.Net: Add new 2024-09-01-preview version

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_graduation.md
.github/ISSUE_TEMPLATE/feature_request.md

Automatically sets the new category type for github issues from the template.
As described in this post.
- https://github.com/orgs/community/discussions/139933

Adding issue type support for template

---

python/Makefile

Small fix in the makefile for when uv is not installed.

Python: small makefile update for python

---

dotnet/Directory.Packages.props
dotnet/src/Functions/Functions.OpenApi.Extensions/Extensions/ApiManifestKernelExtensions.cs
dotnet/src/Functions/Functions.OpenApi.Extensions/Extensions/CopilotAgentPluginKernelExtensions.cs
dotnet/src/Functions/Functions.OpenApi/Extensions/RestApiOperationExtensions.cs
dotnet/src/Functions/Functions.OpenApi/Model/RestApiParameter.cs
dotnet/src/Functions/Functions.OpenApi/Model/RestApiParameterType.cs
dotnet/src/Functions/Functions.OpenApi/Model/RestApiPayloadProperty.cs
dotnet/src/Functions/Functions.OpenApi/OpenApi/OpenApiDocumentParser.cs
dotnet/src/Functions/Functions.OpenApi/OpenApiKernelPluginFactory.cs
dotnet/src/Functions/Functions.OpenApi/RestApiOperationRunner.cs
dotnet/src/Functions/Functions.OpenApi/Serialization/FormStyleParameterSerializer.cs
dotnet/src/Functions/Functions.OpenApi/Serialization/OpenApiTypeConverter.cs
dotnet/src/Functions/Functions.OpenApi/Serialization/PipeDelimitedStyleParameterSerializer.cs
dotnet/src/Functions/Functions.OpenApi/Serialization/SimpleStyleParameterSerializer.cs
dotnet/src/Functions/Functions.OpenApi/Serialization/SpaceDelimitedStyleParameterSerializer.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/Extensions/OpenApiSchemaExtensionsTests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/Extensions/RestApiOperationExtensionsTests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/OpenApiDocumentParserV20Tests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/OpenApiDocumentParserV30Tests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/OpenApiDocumentParserV31Tests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/RestApiOperationRunnerTests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/RestApiOperationTests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/Serialization/FormStyleParametersSerializerTests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/Serialization/OpenApiTypeConverterTests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/Serialization/PipeDelimitedStyleParametersSerializerTests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/Serialization/SimpleStyleParametersSerializerTests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/Serialization/SpaceDelimitedStyleParametersSerializerTests.cs

Currently, SK OpenAPI functionality uses the OpenApi.NET v1.6 SDK to parse OpenAPI documents. The library version supports only OpenAPI v2 - v3.0.1 versions but does not support OpenAPI v3.1. The OpenApi.NET v2 SDK has added support for OpenAPI v3.1 together with some public API changes that caused several breaking changes on SK OpenAPI functionality.
This PR adapts SK OpenAPI functionality to the new OpenApi.NET v2 SDK public API surface.
[.Net: [OpenAPI.Net V2] Refactor OpenAPI functionality to use new content readers](https://github.com/microsoft/semantic-kernel/issues/9857)
[.Net: [OpenAPI.Net V2] Refactor ApiManifest and CopilotAgentPlugin functionality to use new content readers](https://github.com/microsoft/semantic-kernel/issues/9859)
[.Net: [OpenAPI.Net V2] Remove temp. solution …

.Net: Update to OpenApi.NET V2 - Part1

---

python/pyproject.toml
python/samples/concepts/filtering/auto_function_invoke_filters.py
python/samples/concepts/filtering/function_invocation_filters.py
python/samples/concepts/filtering/function_invocation_filters_stream.py
python/semantic_kernel/connectors/ai/__init__.py
python/semantic_kernel/contents/chat_message_content.py
python/semantic_kernel/exceptions/__init__.py
python/semantic_kernel/exceptions/filter_exceptions.py
python/semantic_kernel/filters/__init__.py
python/semantic_kernel/filters/auto_function_invocation/auto_function_invocation_context.py
python/semantic_kernel/filters/filter_context_base.py
python/semantic_kernel/filters/filter_types.py
python/semantic_kernel/filters/functions/function_invocation_context.py
python/semantic_kernel/filters/kernel_filters_extension.py
python/semantic_kernel/filters/prompts/prompt_render_context.py
python/tests/integration/audio_to_text/audio_to_text_test_base.py
python/tests/integration/audio_to_text/test_audio_to_text.py
python/tests/integration/completions/chat_completion_test_base.py
python/tests/integration/completions/test_text_completion.py
python/tests/integration/embeddings/test_embedding_service_base.py
python/tests/unit/agents/test_termination_strategy.py
python/tests/unit/connectors/ai/open_ai/test_openai_request_settings.py
python/tests/unit/kernel/test_kernel_filter_extension.py
python/tests/unit/schema/test_schema_builder.py

This PR graduates the filters.
This includes some updates to the docstrings.
And adds a specific Exception for errors during adding or removing of filters.
Closes #9838 
Fixes #9641

Python: graduate filters, add exception during addition and some cleanup

---

dotnet/src/Connectors/Connectors.Google.UnitTests/Core/Gemini/Clients/GeminiChatGenerationTests.cs
dotnet/src/Connectors/Connectors.Google.UnitTests/Core/Gemini/GeminiRequestTests.cs
dotnet/src/Connectors/Connectors.Google.UnitTests/GeminiPromptExecutionSettingsTests.cs
dotnet/src/Connectors/Connectors.Google/Core/Gemini/Models/GeminiRequest.cs
dotnet/src/Connectors/Connectors.Google/GeminiPromptExecutionSettings.cs

**Why is this change required?**
The absence of the `responseMimeType` property in .NET prevented users from leveraging structured output formats available in the Gemini API, causing unintended behavior in scenarios requiring JSON or controlled output.
**What problem does it solve?**
Adds flexibility for developers by enabling control over MIME type responses, particularly for JSON data parsing and classification tasks.
**What scenario does it contribute to?**
- Requests with structured response needs, such as JSON objects or controlled classification outputs.
- Seamless migration and parity with the Python SDK's `responseMimeType` support.
Fixes #9863 
This PR adds support for the optional `responseMimeType` parameter to the `GeminiPromptExecutionSettings` class, allowing for better …

.Net: Add responseMimeType Parameter to GeminiPromptExecutionSettings for Enhanced Output Control.

---

.github/workflows/python-integration-tests.yml
python/tests/integration/audio_to_text/audio_to_text_test_base.py
python/tests/integration/audio_to_text/test_audio_to_text.py
python/tests/integration/completions/chat_completion_test_base.py
python/tests/integration/completions/test_text_completion.py
python/tests/integration/embeddings/test_embedding_service_base.py
python/tests/integration/text_to_audio/test_text_to_audio.py
python/tests/integration/text_to_audio/text_to_audio_test_base.py
python/tests/utils.py

Our integration tests should encompass all test cases unless a case is explicitly marked as skipped or expected to fail (xfail). Currently, our setup permits test cases to be skipped if the required environment variables are not configured. While this approach is beneficial for local testing—since not all developers have access to all necessary resources - it presents challenges in our pipeline. In this environment, changes to environment variables can lead to test cases being skipped without notice, potentially allowing issues to go undetected until a specific connector is reported as problematic.
The `is_service_setup_for_testing` now also reads the `raise_if_not_set` argument from an environment variable (`INTEGRATION_TEST_SERVICE_SETUP_EXCEPTION`). When …

Python: Raise exceptions when services are not set up in integration test workflow

---

dotnet/src/Connectors/Connectors.Memory.Redis/RedisHashSetVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStoreCollectionCreateMapping.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStoreCollectionSearchMapping.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisHashSetVectorStoreRecordCollectionTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisJsonVectorStoreRecordCollectionTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisVectorStoreCollectionSearchMappingTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisHashSetVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisJsonVectorStoreRecordCollectionTests.cs

.Net: Fix bug where redis score was mapped from wrong score field.

---

dotnet/samples/Concepts/ChatCompletion/OpenAI_StructuredOutputs.cs
dotnet/src/Connectors/Connectors.OpenAI.UnitTests/Helpers/OpenAIChatResponseFormatBuilderTests.cs
dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.ChatCompletion.cs
dotnet/src/Connectors/Connectors.OpenAI/Helpers/OpenAIChatResponseFormatBuilder.cs

Resolves: https://github.com/microsoft/semantic-kernel/issues/9897
This PR addresses remaining comments from previous PR related to Structured Outputs: https://github.com/microsoft/semantic-kernel/pull/9873.

.Net: Small improvements in Structured Outputs

---

python/pyproject.toml
python/semantic_kernel/connectors/ai/azure_ai_inference/services/utils.py
python/semantic_kernel/connectors/ai/bedrock/services/model_provider/utils.py
python/semantic_kernel/connectors/ai/chat_completion_client_base.py
python/semantic_kernel/connectors/ai/ollama/services/ollama_chat_completion.py
python/semantic_kernel/connectors/ai/ollama/services/ollama_text_completion.py
python/semantic_kernel/connectors/ai/ollama/services/utils.py
python/semantic_kernel/contents/function_call_content.py
python/tests/integration/completions/chat_completion_test_base.py
python/tests/integration/completions/test_chat_completion_with_function_calling.py
python/tests/unit/connectors/ai/ollama/services/test_ollama_chat_completion.py
python/uv.lock

Ollama has enabled streaming tool calling, and so we add that too!
See release notes: https://github.com/ollama/ollama/releases/tag/v0.4.6
Also encountered a bug when passing generic PromptExecutionSettings to all ChatCompletions with Function calling enabled, the _verify_function_choice_settings often check if something is a type of PES matching the service, that is not the case and throws even though it should work (for instance when using a yaml based function), this fixes that as well by casting in the public methods of chat completion base.

Python: enable ollama streaming tool calls

---

python/semantic_kernel/core_plugins/sessions_python_tool/sessions_python_plugin.py

The Python sessions plugin (ACA) includes a `status` now in their result once code is executed. This looks to have been added recently as we weren't including it in the original return string. This PR adds that.
Add the `status` key value to the return string.
- Fixes Python bug for #9902

Python: Include the sessions plugin status key in return value

---

.github/workflows/python-test-coverage-report.yml
.github/workflows/python-test-coverage.yml

The Python test coverage workflow needs to post comments of coverage results on PRs, which requires the proper permissions. By default, PRs from forks don't have the required permissions if the workflow is triggered by the `pull_request` event. 
However, one can use the `pull_request_target` event as the trigger and check out the code from the PR for test coverage. This approach posts various security risks as it gives the code from the PR full access to the repository secrets.
It's recommended to use a two-stage approach for this kind of scenarios: https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
In this PR, 
1. a new workflow is created named `python-test-coverage-report`. This workflow is given the proper permissions to post the coverage report in the PR …

Python: Secure Python test coverage workflow

---

.github/workflows/python-test-coverage-report.yml
.github/workflows/python-test-coverage.yml

The test coverage workflow needs the PR number to post comments to PRs. However, the `workflow_run` context doesn't contain the PR number thus we need to save it.
Save the PR number in a file and upload it as artifact for the second workflow to use.

Python: Add PR number to test coverage workflow

---

.github/workflows/python-test-coverage-report.yml

`set-env` command is disabled in our workflow.
Use `$GITHUB_ENV` instead.

Python: Fix set-env not allow in workflow

---

dotnet/src/Functions/Functions.OpenApi/OpenApi/OpenApiDocumentParser.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/OpenApiDocumentParserV20Tests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/OpenApiDocumentParserV30Tests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/OpenApiDocumentParserV31Tests.cs

.Net: fix: includes path item path parameters to OpenAPI document parsing

---

python/semantic_kernel/connectors/ai/anthropic/services/anthropic_chat_completion.py
python/semantic_kernel/connectors/ai/anthropic/services/utils.py
python/tests/integration/completions/chat_completion_test_base.py
python/tests/unit/connectors/ai/anthropic/conftest.py
python/tests/unit/connectors/ai/anthropic/services/test_anthropic_chat_completion.py

When using the Anthropic connector with function calling, it's possible that the model will request multiple functions in a single request. This is referred to as [`parallel tool use`](https://docs.anthropic.com/en/docs/build-with-claude/tool-use#disabling-parallel-tool-use) by Anthropic.
When the model requests multiple functions, it expects the tool results to be included in a single user message to be passed back to the model. Right now, the Anthropic connector parses the tool results into multiple user messages, which causes the model to throw an error.
This is a possible regression introduced by this PR: https://github.com/microsoft/semantic-kernel/pull/9938
1. Fix the Anthropic connector to handle parallel tool calls.
2. Add unit tests to ensure that future changes don't break this …

Python: Fix Anthropic parallel tool call

---

python/pyproject.toml
python/tests/integration/completions/chat_completion_test_base.py
python/tests/integration/completions/test_chat_completion_with_image_input_text_output.py
python/tests/integration/completions/test_chat_completions.py
python/tests/integration/completions/test_text_completion.py
python/tests/unit/connectors/ai/onnx/services/test_onnx_chat_completion.py
python/tests/unit/connectors/ai/onnx/services/test_onnx_text_completion.py
python/tests/unit/connectors/ai/onnx/services/test_onnx_utils.py
python/tests/unit/connectors/ai/onnx/test_onnx_prompt_execution_settings.py
python/uv.lock

Closes : #9979
enabled test cases for mac os
upgraded uv.lock file
Using version 0.4.0 did not provide a pip package for MacOS, which forced us to disabled Unit Tests on MacOs
With version 0.5.0 available we can enable the unit Tests for MacOS.
Using Version 0.5.0 will enable following features for users :
1. Phi3.5 and Phi3.5 MoE
2. MacOS Support without Building the Code from Source
3. LoRa Adapter Swapping

Python: Upgrade Minimum Onnx Version to enable MacOS Unit Tests

---

.github/workflows/markdown-link-check.yml
dotnet/src/Connectors/Connectors.Memory.Chroma/README.md

Changed the runner image to explicitly 22.04 ubuntu because 24.04 doesn't work for link inspect.

use ubuntu 22 for link check

---

python/semantic_kernel/connectors/memory/azure_cosmosdb/azure_cosmosdb_settings.py

fix #10026
This PR removes the alias as pydantic requires the usage of the alias when initializing the class not the original name which prevents this code from working.
```py
cosmosdb_settings = AzureCosmosDBSettings.create(
env_file_path=env_file_path,
connection_string=cosmos_connstr,
)
```

Python: Fix pydantic alias issue

---

dotnet/src/Functions/Functions.OpenApi/RestApiOperationRunner.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/RestApiOperationRunnerTests.cs

.Net: fix: expected empty response in rest APIs

---

dotnet/src/Agents/OpenAI/Extensions/KernelFunctionExtensions.cs
dotnet/src/Agents/UnitTests/OpenAI/Extensions/KernelFunctionExtensionsTests.cs

I have implemented support for DateTime parameters in the .NET tools for the Assistants API. The approach ensures compatibility while maintaining the overall design principles of the semantic-kernel.
This contribution reflects my dedication to making the semantic-kernel more versatile and my enthusiasm for contributing meaningful improvements to open-source projects.
Contribution Checklist
The code builds cleanly without errors or warnings.
All unit tests pass.

.Net: Support DateTime parameters in tools for Assistants API #9940

---

python/semantic_kernel/data/vector_storage/vector_store_record_collection.py

While reviewing the docs, noticed some illogical behavior, this fixes that.

Python: change order used to check variants in (de)ser steps

---

dotnet/src/Connectors/Connectors.HuggingFace/HuggingFacePromptExecutionSettings.cs
dotnet/src/Connectors/Connectors.Ollama/Settings/OllamaPromptExecutionSettings.cs
dotnet/src/Connectors/Connectors.OpenAI/Settings/OpenAIAudioToTextExecutionSettings.cs
dotnet/src/Connectors/Connectors.OpenAI/Settings/OpenAITextToAudioExecutionSettings.cs

This PR addresses a deserialization issue in the `Ollama` and `ONNX` connectors where execution settings fail to handle non-string properties (e.g., "temperature") during JSON parsing.
**Impact:**
- Ensures compatibility with templates containing non-string numeric properties.
- Aligns behavior with `OpenAIPromptExecutionSettings`, which already includes the necessary attribute.
- [Y] The code builds clean without any errors or warnings
- [Y] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [Y] All unit tests pass, and I have added new tests where possible
- [Y] I …

.Net: Add JsonNumberHandling Attribute to Execution Settings in Ollama, ONNX, and Other Connectors

---

dotnet/samples/Demos/HomeAutomation/HomeAutomation.csproj
dotnet/samples/Demos/HomeAutomation/Options/AzureOpenAIOptions.cs
dotnet/samples/Demos/HomeAutomation/Options/OpenAIOptions.cs
dotnet/samples/Demos/HomeAutomation/Program.cs

Fixed the secret section name.
Fixing https://github.com/microsoft/semantic-kernel/issues/10049
Fix the secret section name to `AzureOpenAI`, described in README.
- [NA] All unit tests pass, and I have added new tests where possible

.Net: HomeAutomation AzureOpenAI Configuration Fix

---

dotnet/samples/Concepts/Plugins/OpenApiPlugin_RestApiOperationResponseFactory.cs
dotnet/samples/Concepts/README.md
dotnet/src/Functions/Functions.Grpc/Functions.Grpc.csproj
dotnet/src/Functions/Functions.Markdown/Functions.Markdown.csproj
dotnet/src/Functions/Functions.OpenApi/Extensions/OpenApiFunctionExecutionParameters.cs
dotnet/src/Functions/Functions.OpenApi/OpenApiKernelPluginFactory.cs
dotnet/src/Functions/Functions.OpenApi/RestApiOperationResponseFactory.cs
dotnet/src/Functions/Functions.OpenApi/RestApiOperationResponseFactoryContext.cs
dotnet/src/Functions/Functions.OpenApi/RestApiOperationRunner.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/OpenApiKernelPluginFactoryTests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/RestApiOperationRunnerTests.cs
dotnet/src/SemanticKernel.Abstractions/Functions/RestApiOperationResponse.cs

Currently, it's impossible to access the HTTP response and response content headers returned by a REST API requested from OpenAPI plugins.  
This PR adds `RestApiOperationResponseFactory`, which can be used to customize the responses of OpenAPI plugins before returning them to the caller. The customization may include modifying the original response by adding response headers, changing the response content, adjusting the schema, or providing a completely new response.
Closes: https://github.com/microsoft/semantic-kernel/issues/9986

.Net: Add factory for customizing OpenAPI plugins responses

---

python/semantic_kernel/agents/open_ai/assistant_content_generation.py
python/tests/unit/agents/test_open_ai_assistant_base.py

The (Azure)OpenAIAssistant content generation for function call content was specifying the tool role instead of an assistant role. This was causing an issue in the `.to_dict()` method in `chat_message_content` because a `TOOL` role should only have `FunctionResultContent`. 
This PR fixes the AuthorRole to be ASSISTANT instead of TOOL for function call content, which matches how it's handled in the chat completion case.
- Adds a specific unit test for test coverage (previous test coverage was indirect and didn't catch this)
- Closes #10075

Python: Agent content generation for function call content should be assistant role

---

python/.vscode/settings.json
python/DEV_SETUP.md
python/samples/concepts/agents/assistant_agent_retrieval.py
python/semantic_kernel/agents/open_ai/azure_assistant_agent.py
python/tests/unit/agents/test_azure_assistant_agent.py

The AzureAssistantAgent retrieval path was not handling the optional ad_token. The agent constructor was handling it, to a degree, but there were improvements to make and a helper function to introduce so that we remove some code duplication.
This PR:
- Cleans up the code used to create the azure settings for an azure assistant agent by introducing a helper function to streamline the logic
- Allows the AzureAssistantAgent.retrieve() method to use an ad_token, if desired.
- Adds unit tests for the new logic. Other unit tests are still passing after the refactor.

Python: Improve azure assistant agent settings and retrieval operations.

---

python/tests/integration/completions/test_chat_completion_with_function_calling.py
python/tests/integration/completions/test_chat_completion_with_image_input_text_output.py

This pull request includes updates to the test cases in the `python/tests/integration/completions/test_chat_completion_with_function_calling.py` and `python/tests/integration/completions/test_chat_completion_with_image_input_text_output.py` files. The changes primarily address the handling of Google AI API issues by adding markers to the tests.
* [`python/tests/integration/completions/test_chat_completion_with_function_calling.py`](diffhunk://#diff-530ae449ac82bcd42280dcf440a135e38acc53a5362940fdbb64edfdc4300abcL506-R512): Added `xfail` markers to multiple test cases to handle temporary failures due to Google AI API issues related to function calling not being enabled for models/gemini-1.5-flash. [[1]](diffhunk://#diff-530ae449ac82bcd42280dcf440a135e38acc53a5362940fdbb64edfdc4300abcL506-R5 …

Python: Temporarily xFail some google ai integration tests to unblock

---

python/.vscode/settings.json
python/DEV_SETUP.md
python/semantic_kernel/contents/function_call_content.py
python/tests/unit/contents/test_function_call_content.py

This PR includes changes to improve the handling of JSON parsing when it fails to be parsed as it is in function call arguments by adding a regular expression for preprocessing JSON strings to remove single quotes only when they are not escaped.
Enhancements to JSON parsing:
* [`python/semantic_kernel/contents/function_call_content.py`](diffhunk://#diff-1f5f27eade7117045bc9e62d66ebef5c93047142cdb4fd0115b0ff8eadf2f69cL152-R164): Modified `parse_arguments` method to preprocess JSON strings by replacing single quotes with double quotes, except for escaped single quotes. Added a debug log for invalid JSON.
Test file updates:
* [`python/tests/unit/contents/test_function_call_content.py`](diffhunk://#diff-6e891b3044d5bf5caa7abc97a44ef11ce291aba01fa8032ab1104773f4545c9dR135-R148): Added new …

Python: Fix function call content argument parsing

---

python/semantic_kernel/connectors/ai/open_ai/const.py
python/uv.lock

The current DEFAULT_AZURE_API_VERSION is stale at 2024-06-01. The [latest GA API VERSION](https://learn.microsoft.com/en-us/azure/ai-services/openai/api-version-deprecation#latest-ga-api-release) is 2024-10-21.
This PR upgrades the DEFAULT_AZURE_API_VERSION to be the latest GA 2024-10-21. This default version is used if an api_version is not supplied to the AzureChatCompletion constructor.
- Closes #10117

Python: Upgrade AOAI api version to latest GA: 2024-10-21

---

python/samples/concepts/agents/assistant_agent_retrieval.py
python/semantic_kernel/agents/open_ai/azure_assistant_agent.py
python/semantic_kernel/agents/open_ai/open_ai_assistant_agent.py
python/tests/unit/agents/test_azure_assistant_agent.py
python/tests/unit/agents/test_open_ai_assistant_agent.py

The assistant retrieval methods for OpenAI and AzureOpenAI didn't propagate the api_key or client, if specified. For AzureOpenAI, it's also important to propagate more settings info.
This PR:
- improves the handling for retrieving an agent by making sure we pass along specified keyword arguments
- adds unit tests to ensure the new functionality works as expected

Python: Improve agent retrieval by passing necessary kwargs. Add unit tests.

---

dotnet/src/SemanticKernel.AotTests/JsonSerializerContexts/CustomResultJsonSerializerContext.cs
dotnet/src/SemanticKernel.AotTests/Plugins/CustomResult.cs
dotnet/src/SemanticKernel.AotTests/Program.cs
dotnet/src/SemanticKernel.AotTests/SemanticKernel.AotTests.csproj
dotnet/src/SemanticKernel.AotTests/UnitTests/Search/MockTextSearch.cs
dotnet/src/SemanticKernel.AotTests/UnitTests/Search/TextSearchExtensionsTests.cs
dotnet/src/SemanticKernel.AotTests/UnitTests/Search/VectorStoreTextSearchTests.cs
dotnet/src/SemanticKernel.Core/Data/TextSearch/TextSearchExtensions.cs

.Net: Add unit tests for Text Search AOT enhancements

---

dotnet/src/IntegrationTests/Connectors/Memory/BaseVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/InMemory/CommonInMemoryVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Postgres/CommonPostgresVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Postgres/PostgresVectorStoreFixture.cs
dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/CommonQdrantVectorStoreRecordCollectionTests.cs

Adds tests for verifying the scores as mentioned in #10103
Only adding tests for passing connectors right now.
Adding a common base test class with integration tests for checking the returned vector scores.
Adding subclasses for InMemory, Qdrant and Postgres, since these are passing end to end.

.Net: Add shared integration tests for checking vector search scores

---

python/semantic_kernel/agents/open_ai/open_ai_assistant_base.py

The assistant agent class was storing top_p and temp, but never sending it during agent creation.
Send the top_p and temp params if configured while creating an assistant agent.
- Closes #10162

Python: Configure top_p and temp for assistant agents if configured

---

python/semantic_kernel/utils/telemetry/model_diagnostics/decorators.py
python/semantic_kernel/utils/telemetry/model_diagnostics/gen_ai_attributes.py
python/tests/unit/utils/model_diagnostics/test_trace_chat_completion.py
python/tests/unit/utils/model_diagnostics/test_trace_streaming_chat_completion.py
python/tests/unit/utils/model_diagnostics/test_trace_streaming_text_completion.py
python/tests/unit/utils/model_diagnostics/test_trace_text_completion.py

The gen_ai semantic convention has gone through some updates since we started generating telemetry for gen_ai operations. We would like to align with the latest conventions, and most importantly allow our users to visualize the gen_ai traces on the Azure AI Foundry Tracing UI, which relies on the gen_ai conventions.
1. Updates the gen_ai telemetry module to align with the latest gen_ai convention so that all AI connectors generate telemetry data that can be visualized on Azure AI Foundry.
2. Unit tests for the update.
> Note that this is a breaking change as this feature is still experimental. Anyone who is relying on the previous gen_ai conventions should also update.

Python: Update gen_ai traces and logs

---

dotnet/src/Connectors/Connectors.OpenAI.UnitTests/Core/OpenAIFunctionToolCallTests.cs
dotnet/src/Connectors/Connectors.OpenAI/Core/OpenAIFunctionToolCall.cs
python/semantic_kernel/__init__.py

In the OpenAIFunctionToolCallTests.cs file, a new test method, TrackStreamingToolingUpdateWithEmptyIdNameDoesNotThrowException, has been added. This method tests that the TrackStreamingToolingUpdate method does not throw an exception when id and name are empty. In the OpenAIFunctionToolCall.cs file, two conditional judgments in the TrackStreamingToolingUpdate method have been modified:
* Replace if (update. ToolCallId is string id) to if (!string. IsNullOrWhiteSpace(update. ToolCallId)), make sure that the ToolCallId is neither empty nor full of whitespace.
* Replace if (update. FunctionName is string name) to if (!string. IsNullOrWhiteSpace(update. FunctionName)), making sure that FunctionName is neither empty nor full of whitespace.

.Net: Fixed the condition judgment of the TrackStreamingToolingUpdate method

---

dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeVectorStoreCollectionCreateMapping.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStoreCollectionCreateMapping.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisVectorStoreCollectionSearchMapping.cs
dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreCollectionCreateMapping.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisVectorStoreCollectionCreateMappingTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisVectorStoreCollectionSearchMappingTests.cs
dotnet/src/Connectors/Connectors.Weaviate.UnitTests/WeaviateVectorStoreCollectionCreateMappingTests.cs
dotnet/src/Connectors/VectorData.Abstractions/RecordDefinition/DistanceFunction.cs
dotnet/src/IntegrationTests/Connectors/Memory/BaseVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Pinecone/CommonPineconeVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/CommonRedisHashsetVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/CommonRedisJsonVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Weaviate/CommonWeaviateVectorStoreRecordCollectionTests.cs

#10103
- Adding integration tests for Pinecone, Weaviate and Redis.
- Changing EuclideanDistance to EuclideanSquaredDistance for Redis and Pinecone
- Changing DotProductSimilarity to NegativeDotProduct for Weaviate

.Net: Fixing distance functions for Pinecone, Weaviate and Redis and adding integration tests for score testing for these.

---

dotnet/src/Connectors/Connectors.Memory.Redis/README.md
python/.pre-commit-config.yaml
python/semantic_kernel/connectors/memory/redis/README.md
python/uv.lock

fix of uv version in pre-commit, fix for redis link

.Net: Python: fix pre-commit version

---

python/.pre-commit-config.yaml
python/semantic_kernel/agents/open_ai/open_ai_assistant_base.py
python/tests/unit/agents/test_open_ai_assistant_base.py
python/uv.lock

At times, when the (Azure) OpenAI Assistant Agent makes a tool call, that tool call's creation timestamp is coming after the message creation timestamp (the message creation being the text that the assistant responds with). Currently in our code, if we have a tool call (`FunctionCallContent`), we first yield that, and then we make a call to get completed steps, to then yield more content like `FunctionResultContent` and `TextContent`. There will be two steps (or more, depending upon the number of tool calls).
Right now we sort the completed steps in this way:
```python
completed_steps_to_process: list[RunStep] = sorted(
[s for s in steps if s.completed_at is not None and s.id not in processed_step_ids],
key=lambda s: s.created_at,
)
```
When there are no failures, it's because the tool …

Python: Update sort step method for assistant invoke.

---

dotnet/src/Connectors/Connectors.Ollama.UnitTests/Settings/OllamaPromptExecutionSettingsTests.cs
dotnet/src/Connectors/Connectors.Ollama/Services/OllamaTextGenerationService.cs
dotnet/src/Connectors/Connectors.Ollama/Settings/OllamaPromptExecutionSettings.cs

`OllamaPromptExecutionSettings` does not have property `NumPredict` that allows to limit maximum allowed tokens to generate
Proposed change just add missing field to the `OllamaPromptExecutionSettings` and make sure it will be used also within CreateRequest of `OllamaTextGenerationService`
related issue: #10226

.Net: OllamaPromptExecutionSettings doesn't have NumPredict property

---

dotnet/samples/Concepts/ChatCompletion/MistralAI_ChatCompletion.cs
dotnet/samples/Concepts/README.md
dotnet/src/Connectors/Connectors.MistralAI/Client/ImageUrlChunk.cs
dotnet/src/Connectors/Connectors.MistralAI/Client/MistralClient.cs
dotnet/src/IntegrationTests/Connectors/MistralAI/ChatCompletion/MistralAIChatCompletionTests.cs
dotnet/src/InternalUtilities/samples/InternalUtilities/TestConfiguration.cs

.Net: Add support for Base64 encoded images in MistralAI

---

python/Makefile

Today, If a user runs `make install`, and the uv installation is not found, the current flow is to return `exit 1` to force the user to restart their shell. 
These changes update the Makefile to better handle the case where uv is not installed. The Makefile now uses a “second make invocation” approach with a CONTINUE variable to avoid re-installing uv in the newly spawned shell. If `uv` isn’t found, it installs `uv`, then executes a new shell which immediately calls `make install CONTINUE=1`, allowing the rest of the steps to continue in an environment that now has `uv` on the PATH.
This PR:
- Updates the make file to provide cleaner logic on handling the `make install` when `uv` isn't present.
- Closes #9067

Python: improve Makefile uv installation logic

---

python/.vscode/tasks.json
python/semantic_kernel/agents/group_chat/broadcast_queue.py
python/semantic_kernel/connectors/ai/open_ai/prompt_execution_settings/open_ai_prompt_execution_settings.py
python/semantic_kernel/connectors/ai/prompt_execution_settings.py
python/semantic_kernel/connectors/memory/qdrant/qdrant_settings.py
python/semantic_kernel/connectors/memory/weaviate/weaviate_settings.py
python/semantic_kernel/contents/utils/data_uri.py
python/semantic_kernel/data/filter_clauses/any_tags_equal_to_filter_clause.py
python/semantic_kernel/data/filter_clauses/equal_to_filter_clause.py
python/semantic_kernel/data/filter_clauses/filter_clause_base.py
python/semantic_kernel/data/record_definition/vector_store_model_decorator.py
python/semantic_kernel/data/text_search/text_search.py
python/semantic_kernel/data/text_search/utils.py
python/semantic_kernel/data/text_search/vector_store_text_search.py
python/semantic_kernel/data/vector_storage/vector_store_record_collection.py
python/semantic_kernel/functions/kernel_function_from_prompt.py
python/semantic_kernel/processes/local_runtime/local_step.py
python/semantic_kernel/template_engine/blocks/function_id_block.py
python/tests/unit/data/test_vector_store_model_decorator.py
python/uv.lock

Based on insights from the graphrag team, several bug fixes related to data and model validators.
For all cases of model_validator in before mode, there is no guarantee that the data passed is a dict,
especially when a model is used as a field in another model, then a string is passed to the before validator.
So in those cases we check before doing logic, otherwise just pass it on and let Pydantic handle the invalid data.
Some small logic fixes in the vector store model decorator:
- updated docstring with the right exceptions
- additional checks on attributes
- additional checks on VectorFields with tests

Python: bug fixes from graphrag insights

---

dotnet/src/InternalUtilities/connectors/AI/FunctionCalling/FunctionCallsProcessor.cs
dotnet/src/SemanticKernel.UnitTests/Utilities/AIConnectors/FunctionCallsProcessorTests.cs

Every time an AI model calls a function, and that call fails for whatever reason - hallucinated name, invalid arguments, etc. SK sends the failure details back to the model to allow it to correct (auto-recovery) itself and call the function one more time with the valid name, arguments, etc.
Having tested this auto-recovery mechanism with a few modern {Azure}OpenAI models, it appeared that it does not work for the `Gpt-4(0314, 0613)` and `Gpt-4o(2024-08-06)` models. To make it work for the `Gpt-4o(2024-08-06)` model, the default error message needs to be extended either with the `Correct yourself` instruction, function name, or both. This solution is not enough to make the `Gpt-4(0314, 0613)` model's auto-recovery work, and as shown in the table below, the only way found so far to make it …

.Net: Improve auto-recovery for Azure{OpenAI} models

---

python/semantic_kernel/functions/kernel_function_extension.py
python/semantic_kernel/functions/kernel_plugin.py
python/tests/unit/kernel/test_kernel.py

This PR addresses an issue in the `KernelPlugin.from_directory()` method where classes without any `@kernel_function` decorated methods are still being initialized during plugin loading.
The fix makes sure that only classes with at least one `@kernel_function` decorated method are instantiated and included as plugins. Classes without `@kernel_function` methods are now skipped entirely.
This PR:
- Updates the `from_python_file` to inspect each class for `@kernel_function` decorated methods before instantiation.
- Updates the `add_plugin` method `plugin_name` to make sure it is indeed a string, per the type hint.
- Adds a unit test to exercise the new behavior
- Closes #10280

Python: Improve handling for kernel plugin from file.

---

dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatPromptParser.cs
dotnet/src/SemanticKernel.UnitTests/Prompt/ChatPromptParserTests.cs

See [Issue #10278](https://github.com/microsoft/semantic-kernel/issues/10278
)
**`ChatPromptParser.cs` :**
Remove method `IsValidChildNodes` and its call in `IsValidChatMessage` : A chat message is valid as long as it has a role attribute. Messages with no text child or multiple text children are now valid
**`ChatPromptParserTests` :** 
- Changed 3rd invalid example since the former one is now valid
- Added tests for :  Message with multiple text nodes, mixed XML content and empty XML node
Remark : The expected behavior for mixed XML content is unclear so I kept it as it was : the content of the message node ends up in a `TextContent` if and only if the message has no valid text or image child node. 
So for instance, if the prompt has a message that is a mixed XML with content and a child …

.Net: issue-10278 : Change ChatPromptParser to enable 0-n text part instead of single value

---

python/semantic_kernel/contents/function_result_content.py
python/semantic_kernel/contents/utils/hashing.py
python/semantic_kernel/processes/process_step_builder.py
python/tests/unit/contents/test_function_result_content.py
python/tests/unit/processes/test_process_step_builder.py

Two topics in this PR:
- A request to be able to pass in Enums to the Python process `on_function_result`, instead of just strings.
- There were some custom types (Pydantic models) that were unable to hash during an agent group chat. One could mark the model `frozen` so that it is hashable; however, we should add better handling in our code, in case a dev doesn't want to do that. 
This PR:
- checks if the function name in `on_function_result` in our process framework is an enum, if so, convert to a string.
- improves the parsing of the `result` in `FunctionResultContent` so that it can be included in the hash function during an agent group chat. Adding tests to handle multiple different scenarios.
- Closes #10299 
- Closes #10305

Python: Allow enums to be passed in to on_function_result. Improve handling FRC result so it can be hashed.

---

python/samples/concepts/agents/chat_completion_history_reducer.py
python/samples/concepts/chat_completion/simple_chatbot_with_summary_history_reducer.py
python/samples/concepts/chat_completion/simple_chatbot_with_summary_history_reducer_keep_func_content.py
python/samples/concepts/structured_outputs/json_structured_outputs.py
python/samples/getting_started_with_agents/step10_assistant_tool_file_search.py
python/samples/getting_started_with_agents/step1_agent.py
python/samples/getting_started_with_agents/step2_plugins.py
python/samples/getting_started_with_agents/step3_chat.py
python/samples/getting_started_with_agents/step4_kernel_function_strategies.py
python/samples/getting_started_with_agents/step5_json_result.py
python/samples/getting_started_with_agents/step6_logging.py
python/samples/getting_started_with_agents/step7_assistant.py
python/samples/getting_started_with_agents/step8_assistant_vision.py
python/samples/getting_started_with_agents/step9_assistant_tool_code_interpreter.py
python/semantic_kernel/agents/agent.py
python/semantic_kernel/agents/channels/chat_history_channel.py
python/semantic_kernel/agents/chat_completion/chat_completion_agent.py
python/semantic_kernel/agents/group_chat/agent_chat.py
python/semantic_kernel/agents/group_chat/agent_group_chat.py
python/semantic_kernel/agents/strategies/__init__.py
python/semantic_kernel/contents/__init__.py
python/semantic_kernel/contents/chat_history.py
python/semantic_kernel/contents/history_reducer/chat_history_reducer.py
python/semantic_kernel/contents/history_reducer/chat_history_reducer_utils.py
python/semantic_kernel/contents/history_reducer/chat_history_summarization_reducer.py
python/semantic_kernel/contents/history_reducer/chat_history_truncation_reducer.py
python/tests/unit/agents/test_agent.py
python/tests/unit/contents/test_chat_history_summarization_reducer.py

When passing the same object to `agent.reduce_history` as is present in the `history_reducer` attribute of the agent that the function doesn't accurately behave. This fixes that.
Also updates the sample to be a bit more concise.
Also fixes the way the single_dispatch is setup in ChatHistory.
Also ensures system/developer messages are not reduced away as that might impact performance.
The `reduce_history` method was removed from the agent base class, in favor of having the caller manage the change history and reduction as needed. The `reduce_history` was added to the agent group chat, as the chat history is managed internally as agents are invoked.

Python: improve agent samples and chat history handling

---

python/semantic_kernel/contents/chat_message_content.py
python/semantic_kernel/contents/streaming_chat_message_content.py
python/tests/unit/contents/test_chat_message_content.py
python/tests/unit/contents/test_streaming_chat_message_content.py

We have some content types that can't be hashed as-is. This PR makes sure that if there are unhashable types, that we turn them into hashable types. Add unit tests to exercise the scenarios.

Python: Improve hashing of cmc and scmc items. Add tests.

---

dotnet/src/Agents/Core/ChatHistoryChannel.cs
dotnet/src/Agents/UnitTests/Core/ChatHistoryChannelTests.cs

Ensure `ChatCompletionAgent` only accepts content types / patterns allowed by chat-completion service.
The sample [Concepts/Agents/MixedChat_Images](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/Concepts/Agents/MixedChat_Images.cs) fails (connector assertion) when passing a message generated by `OpenAIAssistantAgent` to `ChatCompletionAgent` that contains only `FileReferenceContent`.
> This sample historically worked, but there may have been an internal logic update for the connector as part of a maintenance task.  I didn't bother to do the forensics, as the fact that it fails now is sufficient data to address the bug.

.NET - Introduce ChatCompletionAgent `Allow-List` of supported content

---

python/samples/concepts/README.md
python/samples/concepts/agents/mixed_chat_images.py
python/semantic_kernel/agents/channels/chat_history_channel.py
python/tests/unit/agents/test_chat_history_channel.py

During a group chat, any file reference content created by an assistant agent, doesn't need to be communicated to a chat completion agent. Filter these types out and only include other types, like text, if available.
This PR:
- Adds a mixed chat image sample to have an assistant agent generate an image, along with text, and call the chat completion agent successfully with only the allowed types (like text).
- Adds a unit test to exercise the same behavior.
- Closes #10317

Python: intro allowed content types in chat history channel receive. Add mixed chat image sample.

---

python/semantic_kernel/processes/process_edge_builder.py
python/tests/unit/processes/test_process_edge_builder.py

See #10340 
Implement a similar approach as is done in `process_step_edge_builder.py`, which supports function_name when building the target function.
(well, we're still passing/xpass/xfail the same as main is)

Python: [python] Bug fix 10340

---

dotnet/samples/Concepts/ChatCompletion/ChatHistoryReducers/ChatHistoryReducerTests.cs
dotnet/src/IntegrationTests/Connectors/Google/Gemini/GeminiChatCompletionTests.cs
dotnet/src/IntegrationTests/Connectors/Google/TestsBase.cs
dotnet/src/SemanticKernel.Core/AI/ChatCompletion/ChatHistoryReducerExtensions.cs
dotnet/src/SemanticKernel.Core/AI/ChatCompletion/ChatHistorySummarizationReducer.cs
dotnet/src/SemanticKernel.Core/AI/ChatCompletion/ChatHistoryTruncationReducer.cs
dotnet/src/SemanticKernel.UnitTests/AI/ChatCompletion/ChatHistorySummarizationReducerTests.cs
dotnet/src/SemanticKernel.UnitTests/AI/ChatCompletion/ChatHistoryTruncationReducerTests.cs
dotnet/src/SemanticKernel.UnitTests/AI/ChatCompletion/MockChatHistoryGenerator.cs

Related: https://github.com/microsoft/semantic-kernel/issues/10102
This PR contains changes to the chat history reducer implementations to avoid redaction of system messages if they exist in chat history. It's important to keep system messages in the chat history so the model can follow initial instructions independently from history redaction.

.Net: Updated chat history reducers to include system message

---

.github/workflows/label-needs-port.yml

This adds a workflow for when issues or PR's are assigned the labels: `needs_port_to_dotnet` or `needs_port_to_python`
The workflow then creates a new issues linking to the original PR/Issue to make it easier to keep track of work across languages.

add workflow to create issue from needs port

---

.github/workflows/python-integration-tests.yml

Ollama integration tests are very unstable. It often fails to pull models from the Ollama server. This causes our pipeline to fail and blocks PRs.
Skip the Ollama integration tests temporarily to unblock PRs.

Python: Skip Ollama integration tests temporarily to unblock PRs

---

dotnet/samples/Concepts/Plugins/CopilotAgentBasedPlugins.cs
dotnet/samples/Concepts/Resources/Plugins/ApiManifestPlugins/MessagesPlugin/apimanifest.json
dotnet/samples/Concepts/Resources/Plugins/CopilotAgentPlugins/AstronomyPlugin/messages-openapi.yml
dotnet/samples/Concepts/Resources/Plugins/CopilotAgentPlugins/MessagesPlugin/messages-apiplugin.json
dotnet/samples/Concepts/Resources/Plugins/CopilotAgentPlugins/MessagesPlugin/messages-openapi.yml
dotnet/samples/Concepts/Resources/Plugins/CopilotAgentPlugins/README.md
dotnet/src/Functions/Functions.UnitTests/OpenApi/Extensions/CopilotAgentPluginKernelExtensionsTests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/TestPlugins/messages-apiplugin.json
dotnet/src/Functions/Functions.UnitTests/OpenApi/TestPlugins/messages-openapi.yml

this PR replaces message creation by send messages in CAP and API manifest samples and tests as requested by our dear PM @fabianwilliams

.Net: replaces message creation by send messages in CAP and API manifest samples and tests

---

dotnet/src/Connectors/Connectors.Google.UnitTests/Core/Gemini/GeminiRequestTests.cs
dotnet/src/Connectors/Connectors.Google/Core/Gemini/Models/GeminiRequest.cs
dotnet/src/IntegrationTests/Connectors/Google/Gemini/GeminiChatCompletionTests.cs

**Why is this change required?**  
Adds to the multi-modal capabilities of Gemini.
This change exposes the [audio capabilities](https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/audio-understanding) of Gemini to perform tasks that involve understanding the contents of the included audio.
*No open issues are linked to this change.*
---
---
---
1. Audio capabilities [documentation](https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/audio-understanding)

.Net Add Audio content capabilities to Gemini

---

dotnet/samples/GettingStartedWithAgents/OpenAIAssistant/Step05_AssistantTool_Function.cs
dotnet/src/Agents/OpenAI/Extensions/KernelFunctionExtensions.cs
dotnet/src/Agents/OpenAI/Internal/AssistantThreadActions.cs
dotnet/src/Agents/OpenAI/OpenAIAssistantAgent.cs
dotnet/src/Agents/UnitTests/OpenAI/OpenAIAssistantAgentTests.cs

Same issue that was fixed here https://github.com/microsoft/semantic-kernel/pull/10413 but this time the fix is for OpenAI Assistants.

.Net: Avoid sending duplicate function tools when creating a thread

---

python/samples/concepts/processes/cycles_with_fan_in.py
python/samples/demos/process_with_dapr/fastapi_app.py
python/samples/demos/process_with_dapr/process/process.py
python/samples/demos/process_with_dapr/process/steps.py
python/semantic_kernel/processes/dapr_runtime/actors/process_actor.py
python/semantic_kernel/processes/dapr_runtime/actors/step_actor.py
python/semantic_kernel/processes/dapr_runtime/dapr_actor_registration.py
python/semantic_kernel/processes/kernel_process/kernel_process.py
python/semantic_kernel/processes/local_runtime/local_kernel_process_context.py
python/semantic_kernel/processes/local_runtime/local_process.py
python/semantic_kernel/processes/local_runtime/local_step.py
python/semantic_kernel/processes/process_builder.py
python/tests/unit/processes/dapr_runtime/test_process_actor.py
python/tests/unit/processes/dapr_runtime/test_step_actor.py
python/tests/unit/processes/local_runtime/test_local_kernel_process_context.py
python/tests/unit/processes/local_runtime/test_local_process.py

In the current Python process framework, in runtimes like Dapr, there is no easy way to pass complex (unserializable) dependencies to a step -- this includes things like a ChatCompletion service or an agent of type ChatCompletionAgent.
Similar to how the kernel dependency was propagated to the step_actor or process_actor, we're introducing the ability to specify a factory callback that will be called as the step is instantiated. The factory is created, if specified via the optional kwarg when adding a step to the process builder like:
```python
myBStep = process.add_step(step_type=BStep, factory_function=bstep_factory)
```
The `bstep_factory` looks like (along with its corresponding step)
```python
async def bstep_factory():
"""Creates a BStep instance with ephemeral references like …
```

Python: Allow for factory callbacks in the process framework

---

python/samples/concepts/filtering/auto_function_invoke_filters.py
python/samples/getting_started/05-using-the-planner.ipynb

We had two places in code that showed how to perform a plugin import using old code - `kernel.import_plugin...`.
Removes old old comments, replacing it with the current `kernel.add_plugin(...)`.

Python: Remove old references of plugin import

---

python/pyproject.toml
python/semantic_kernel/connectors/ai/open_ai/prompt_execution_settings/open_ai_prompt_execution_settings.py
python/tests/unit/connectors/ai/open_ai/services/test_azure_chat_completion.py
python/tests/unit/connectors/ai/open_ai/services/test_openai_chat_completion_base.py
python/uv.lock

We noticed that the openai package dependency spec was off and did not update that when present to the newest version, fixed now.
Also we mistakenly had a default value for parallel_tool_calls in our prompt executions settings, as with other settings we do not maintain a default value if the API has a default and in this case having that parameter when calling a reasoning model threw an error, fixed here.

Python: set openai package to newer version and removed default value of parallel tool calls

---

python/samples/concepts/agents/assistant_agent/assistant_agent_file_manipulation.py
python/samples/concepts/agents/assistant_agent/assistant_agent_file_manipulation_streaming.py
python/samples/concepts/agents/mixed_chat/mixed_chat_files.py
python/samples/learn_resources/agent_docs/assistant_code.py

The code sample located [here](https://learn.microsoft.com/en-us/semantic-kernel/frameworks/agent/examples/example-assistant-code?pivots=programming-language-python) had an issue loading the resource csv files right out of the box. Additionally, the formatted output could use some help.
Now the output is formatted nicely like:
---
To provide a column chart of the top 10 countries by population with values at the top of each column, I'll need to examine the contents of the uploaded files. Let's first take a look at the data in these files to understand their structure and content.
```python
import pandas as pd
file_1_path = '/mnt/data/assistant-T1tWYT1f5Y8JFRuYtxgjck'
file_2_path = '/mnt/data/assistant-LUgpebvSh4PTrFdEkVEXMi'
try:
data_1 = pd.read_csv(file_1_path)
except Exception as e: …
```

Python: Fix csv file paths for learn site sample. Improve streaming output formatting with code present

---

dotnet/samples/GettingStartedWithAgents/Step04_KernelFunctionStrategies.cs
dotnet/src/Connectors/Connectors.Memory.Postgres/PostgresVectorStoreCollectionSqlBuilder.cs
dotnet/src/IntegrationTests/Connectors/Memory/Postgres/PostgresVectorStoreRecordCollectionTests.cs

Fixes #10521
- Wrap index name in double quotes to handle special characters in collection names
- Add integration test to verify fix.
- Fix unrelated flaky integration test

.Net: Fix bug where special chars in collection name fails index creation.

---

python/semantic_kernel/contents/utils/hashing.py
python/tests/unit/contents/test_hashing_utils.py

We encountered an issue where our hashing utility (`make_hashable(...)`) could enter an infinite recursion loop whenever it encountered cyclical references. This was particularly evident with Pydantic models that reference each other (or themselves), or with dictionaries/lists that recursively include a reference to an already-seen object. In such scenarios, the function continued to expand and re-expand the same objects indefinitely, triggering a RecursionError.
We introduced a visited dictionary in `make_hashable`. Before diving deeper into any object -- whether it’s a dict, a list, a set, a tuple, or a Pydantic model -- we record its id() in visited. The very next time we see that same object ID, we immediately return its already-computed placeholder or final representation, …

Python: Fix Infinite Recursion in Hashing Logic by Tracking Visited Objects

---

python/samples/concepts/agents/assistant_agent/README.md
python/samples/getting_started_with_agents/azure_ai_agent/README.md
python/samples/getting_started_with_agents/openai_assistant/README.md

Clarify in READMEs which Assistant api versions should be used. Assistants are still in preview and require the use of `-preview` api versions. Include this in our READMEs to help make sure users/devs understand which api versions they should be targeting.
Update the README for Assistants and add a README to the samples/concepts/agents/assistant_agent directory.
- Closes #10231

Python: Clarify in READMEs which Assistant api versions should be used.

---

python/semantic_kernel/connectors/search_engine/google_connector.py

The `GoogleSearchSettings` used for the `GoogleConnector` class use `search_api_key` instead of `api_key`. 
Fix the input argument, `search_api_key`, for the `GoogleConnector` class.

Python: update GoogleConnector settings arg to search_api_key from api_key

---

python/Makefile

The current make install-uv logic wasn't accounting for installing uv into a virtual env if it is available.
This PR makes an update to install uv into the virtual env if it is available/active. Tested on a new venv, and it correctly installs the latest uv version (0.6.1 at the time of this writing) and uses it.

Python: Update install-uv target to install uv into active virtual env if available

---

dotnet/samples/GettingStartedWithAgents/Step07_Telemetry.cs
dotnet/src/Agents/AzureAI/AzureAIChannel.cs
dotnet/src/Agents/OpenAI/OpenAIAssistantChannel.cs

This PR contains changes to add traces for case when `OpenAIAssistantAgent` or `AzureAIAgent` are invoked not directly, but through the `AgentGroupChat`.

.Net: Added traces for OpenAI Assistant and Azure AI channels

---

dotnet/samples/GettingStartedWithAgents/Step04_KernelFunctionStrategies.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.InMemory/InMemoryVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Postgres/PostgresVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisHashSetVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Sqlite/SqliteVectorStoreRecordCollection.cs

We should have common code for retrieving the vector property for search, from the schema.
Updating remaining implementations that do not yet use the common code.

Refactor remaining vector store collections to use common getvector method.

---

python/semantic_kernel/processes/kernel_process/kernel_process_event.py
python/semantic_kernel/processes/local_runtime/local_process.py
python/tests/unit/processes/kernel_process/test_kernel_process_event.py
python/tests/unit/processes/local_runtime/test_local_process.py

Resolves #10642 -- failure of `KernelProcessEventVisibility.Public` events to propagate.
First, `KernelProcessEvent` was configured to use enum values -- though throughout the code, `KernelProcessEvent.visibility` is compared as an enum.
Second, when handling events emitted by a KernelProcessStep, any `Public` visibility events are/were passed through `LocalStep.scoped_event` (which modifies the event's namespace) *before* queueing up any matching edges on the source step. This change to the event namespace effectively prevents the event from propagating (since I don't know how we'd 'listen' for events on the local process handle from within the function that builds that very process...)
Allowing `visibility` on `KernelProcessEvent` to be an enum, combined with an exchange in the order of …

Python: resolving #10642 - public events fail to propagate

---

python/semantic_kernel/agents/azure_ai/agent_content_generation.py
python/semantic_kernel/agents/azure_ai/agent_thread_actions.py
python/semantic_kernel/utils/feature_stage_decorator.py
python/uv.lock

The new feature decorator was impacting Pylance and child classes weren't properly resolving methods due to the decorator's return type handling.
Update the decorator so it handles the return types properly.

Python: improve feature decorator return type so it doesn't affect Pylance

---

python/samples/concepts/memory/complex_memory.py
python/semantic_kernel/connectors/memory/chroma/__init__.py
python/semantic_kernel/connectors/memory/chroma/chroma.py
python/semantic_kernel/data/record_definition/vector_store_model_definition.py
python/tests/integration/memory/vector_stores/test_vector_store.py
python/tests/integration/memory/vector_stores/vector_store_test_base.py
python/tests/unit/connectors/memory/chroma/test_chroma.py

Adds ChromaStore and ChromaConnector
Closes: #9926

Python: Introducing the Chroma Connector with the new vector store design

---

python/tests/integration/agents/bedrock_agent/test_bedrock_agent_integration.py
python/tests/integration/memory/vector_stores/azure_cosmos_db/test_azure_cosmos_db_no_sql.py
python/tests/integration/memory/vector_stores/test_vector_store.py
python/tests/integration/memory/vector_stores/vector_store_test_base.py

Moved the import and creation of the store into methods that get called when accessed only.

Python: lazy create stores in integration tests

---

dotnet/src/Connectors/Connectors.Memory.Pinecone/IPineconeMemoryStore.cs
dotnet/src/Connectors/Connectors.Memory.Postgres/IPostgresVectorStoreDbClient.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/IQdrantVectorDbClient.cs
dotnet/src/Connectors/VectorData.Abstractions/VectorStorage/IVectorStoreRecordCollection.cs
dotnet/src/Experimental/Process.Abstractions/IKernelExternalProcessMessageChannel.cs
dotnet/src/Experimental/Process.Abstractions/IKernelProcessMessageChannel.cs
dotnet/src/InternalUtilities/src/Diagnostics/ActivityExtensions.cs
dotnet/src/Plugins/Plugins.Document/FileSystem/IFileSystemConnector.cs
dotnet/src/Plugins/Plugins.Document/IDocumentConnector.cs
dotnet/src/SemanticKernel.Abstractions/AI/TextToImage/ITextToImageService.cs
dotnet/src/SemanticKernel.Abstractions/Data/TextSearch/ITextSearch.cs
dotnet/src/SemanticKernel.Abstractions/Memory/ISemanticTextMemory.cs
dotnet/src/SemanticKernel.Core/TemplateEngine/Blocks/ICodeRendering.cs
dotnet/src/SemanticKernel.Core/TemplateEngine/Blocks/ITextRendering.cs

In order to be able to build the dotnet code with version 9 SDK, there were some problems with the following file
`/workspaces/semantic-kernel/dotnet/src/InternalUtilities/src/Diagnostics/ActivityExtensions.cs`. This had a BOM encoding problem which was causing `dotnet format` to fail. As seen in this Issue [https://github.com/dotnet/sdk/issues/46780](https://github.com/dotnet/sdk/issues/46780).
I fixed the encoding and formatting issues ready for version 9. Most of the formatting issues are around removing the access modifiers on interface members
This relates to #10715

.Net: dotnet format issues with SDK 9.0

---

dotnet/Directory.Packages.props
dotnet/SK-dotnet.sln
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.ApiService/ChatWithAgent.ApiService.csproj
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.ApiService/Extensions/WebApplicationBuilderExtensions.cs
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.ApiService/Program.cs
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.AppHost/ChatWithAgent.AppHost.csproj
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.AppHost/Extensions/DistributedApplicationBuilderExtensions.cs
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.AppHost/Extensions/ResourceBuilderExtensions.cs
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.AppHost/Program.cs
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.AppHost/appsettings.json
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.Configuration/AzureOpenAIChatConfig.cs
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.Configuration/ChatWithAgent.Configuration.csproj
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.Configuration/HostConfig.cs

This PR reads Azure OpenAI related configuration: deployment, model, and version from a config file instead of using hardcoded values. Additionally, it adds a configuration property that points to an AI chat service for the agent to use. At the moment, only the Azure OpenAI service is supported, but other services like OpenAI will be added in one of the next PRs.  
It also copies some values from the host configuration to environment variables so that the Agent API service can access them. This allows us to keep the host/deployment configuration in one place - the host rather than having the same config in two projects: the host and the API service. The host uses it for deployment and provisioning of Azure resources, while the service uses it to access the provisioned resources.  
Next …

.Net: Make AzureOpenAI service/model deployment configurable

---

dotnet/src/Connectors/Connectors.Ollama.UnitTests/Extensions/OllamaKernelBuilderExtensionsTests.cs
dotnet/src/Connectors/Connectors.Ollama.UnitTests/Extensions/OllamaServiceCollectionExtensionsTests.cs
dotnet/src/Connectors/Connectors.Ollama/Extensions/OllamaKernelBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Ollama/Extensions/OllamaServiceCollectionExtensions.cs
dotnet/src/Connectors/Connectors.Ollama/Services/OllamaTextGenerationService.cs
dotnet/src/IntegrationTests/Agents/BedrockAgentTests.cs
dotnet/src/IntegrationTests/TestSettings/BedrockAgentConfiguration.cs

.Net: Add missing Ollama Connector Aspire Friendly Extensions

---

dotnet/src/Connectors/Connectors.AzureCosmosDBMongoDB.UnitTests/AzureCosmosDBMongoDBVectorStoreRecordCollectionTests.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/AzureCosmosDBNoSQLVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.InMemory/InMemoryVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoDBVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Postgres/PostgresVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisHashSetVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Sqlite/SqliteVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreRecordCollectionQueryBuilder.cs
dotnet/src/Connectors/Connectors.MongoDB.UnitTests/MongoDBVectorStoreRecordCollectionTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisJsonVectorStoreRecordCollectionTests.cs
dotnet/src/Connectors/VectorData.Abstractions/VectorSearch/HybridSearchOptions.cs
dotnet/src/Connectors/VectorData.Abstractions/VectorSearch/IKeywordHybridSearch.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchKeywordVectorizedHybridSearchTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureCosmosDBNoSQL/AzureCosmosDBNoSQLKeywordVectorizedHybridSearchTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/BaseKeywordVectorizedHybridSearchTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/MongoDB/MongoDBKeywordVectorizedHybridSearchTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantNamedVectorsKeywordVectorizedHybridSearchTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantSingleVectorKeywordVectorizedHybridSearchTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Weaviate/WeaviateKeywordVectorizedHybridSearchTests.cs
dotnet/src/InternalUtilities/src/Data/VectorStoreRecordPropertyReader.cs
dotnet/src/SemanticKernel.UnitTests/Data/VectorStoreRecordPropertyReaderTests.cs

Renames hybrid search to agreed naming
Switch validation to expect a single vector property if one is not named.

.Net: Rename hybrid search and expect single vector property.

---

dotnet/SK-dotnet.sln
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.ApiService/Config/AgentConfig.cs
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.ApiService/Config/AppConfig.cs
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.ApiService/Config/ServiceConfig.cs
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.ApiService/Extensions/WebApplicationBuilderExtensions.cs
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.ApiService/Program.cs
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.ApiService/appsettings.json
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.AppHost/Extensions/ResourceBuilderExtensions.cs
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.AppHost/Program.cs
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.AppHost/appsettings.json
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.Configuration/HostConfig.cs
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.Configuration/OpenAIChatConfig.cs
dotnet/samples/Demos/Hosting/Agent/ChatWithAgent.Web/Components/Pages/Chat.razor
dotnet/samples/Demos/Hosting/Agent/README.md

This PR reads the agent and OpenAI related configuration: name, description, instructions, model name from a config file instead of using hardcoded values.
Next steps include:  
- Add support for {Azure}OpenAI embeddings model
Note: This PR targets the `feature-agents-hosting` feature branch.    
Contributes to: https://github.com/microsoft/semantic-kernel/issues/10149

.Net: Read the agent and OpenAI model prosp from configuration

---

python/samples/concepts/caching/semantic_caching.py
python/samples/concepts/embedding/text_embedding_generation.py
python/samples/concepts/setup/chat_completion_services.py
python/samples/concepts/setup/text_completion_services.py
python/samples/concepts/setup/text_embedding_services.py
python/samples/concepts/text_completion/text_completion.py
python/samples/concepts/text_completion/text_completion_streaming.py
python/semantic_kernel/connectors/ai/azure_ai_inference/services/azure_ai_inference_text_embedding.py
python/semantic_kernel/connectors/ai/bedrock/services/bedrock_text_embedding.py
python/semantic_kernel/connectors/ai/embedding_generator_base.py
python/semantic_kernel/connectors/ai/embeddings/embedding_generator_base.py
python/semantic_kernel/connectors/ai/google/google_ai/services/google_ai_text_embedding.py
python/semantic_kernel/connectors/ai/google/vertex_ai/services/vertex_ai_text_embedding.py
python/semantic_kernel/connectors/ai/hugging_face/services/hf_text_embedding.py
python/semantic_kernel/connectors/ai/mistral_ai/__init__.py
python/semantic_kernel/connectors/ai/mistral_ai/services/mistral_ai_text_embedding.py
python/semantic_kernel/connectors/ai/ollama/services/ollama_text_embedding.py
python/semantic_kernel/connectors/ai/open_ai/services/open_ai_text_embedding_base.py
python/semantic_kernel/data/text_search/vector_store_text_search.py
python/semantic_kernel/kernel.py
python/semantic_kernel/memory/semantic_text_memory.py
python/tests/integration/embeddings/test_embedding_service.py
python/tests/integration/embeddings/test_embedding_service_base.py
python/tests/integration/embeddings/test_embedding_service_with_memory.py
python/tests/samples/test_concepts.py
python/tests/unit/connectors/ai/open_ai/services/test_azure_text_embedding.py
python/tests/unit/core_plugins/test_text_memory_plugin.py
python/uv.lock

Closing https://github.com/microsoft/semantic-kernel/issues/9963
1. Add text embedding and text completion samples.
2. Move the embedding generator base to a `semantic_kernel.connectors.ai`.

Python: Add embedding and text completion samples

---

python/semantic_kernel/connectors/ai/google/google_ai/services/google_ai_chat_completion.py
python/semantic_kernel/connectors/ai/google/google_ai/services/utils.py
python/semantic_kernel/connectors/ai/google/shared_utils.py
python/semantic_kernel/connectors/ai/google/vertex_ai/services/vertex_ai_chat_completion.py
python/tests/unit/connectors/ai/google/test_shared_utils.py

Closing #10597 
1. Collapse consecutive tool call messages into a single tool message with multiple function result items before sending the chat history to the API.
2. Add unit test.

Python: Fix issues of Gemini parallel function call

---

dotnet/src/Agents/Abstractions/Agents.Abstractions.csproj
dotnet/src/Agents/Abstractions/Definition/AgentDefinition.cs
dotnet/src/Agents/Abstractions/Definition/AgentMetadata.cs
dotnet/src/Agents/AzureAI/Definition/AzureAIAgentFactory.cs
dotnet/src/Agents/UnitTests/Yaml/AgentDefinitionYamlTests.cs
dotnet/src/Agents/UnitTests/Yaml/AzureAIKernelAgentYamlTests.cs
dotnet/src/Agents/UnitTests/Yaml/KernelAgentYamlTests.cs
dotnet/src/Agents/Yaml/AgentDefinitionYaml.cs
dotnet/src/Agents/Yaml/AgentMetadataTypeConverter.cs

Update AgentDefinition to match the latest schema changes from the declarative agent work group

.Net: Update AgentDefinition to match the latest schema changes

---

dotnet/src/Agents/Abstractions/Definition/AgentDefinition.cs
dotnet/src/Agents/Abstractions/Definition/AgentInput.cs
dotnet/src/Agents/Abstractions/Definition/AgentOutput.cs
dotnet/src/Agents/Abstractions/Extensions/AgentDefinitionExtensions.cs
dotnet/src/Agents/UnitTests/Core/Extensions/AgentDefinitionExtensionsTests.cs
dotnet/src/Agents/UnitTests/Yaml/KernelAgentYamlTests.cs
dotnet/src/Agents/Yaml/AgentDefinitionYaml.cs

Update to AgentDefinition.Inputs to match latest spec changes

.Net: Update to AgentDefinition.Inputs to match latest spec changes

---

python/samples/concepts/setup/chat_completion_services.py
python/semantic_kernel/connectors/ai/bedrock/services/bedrock_chat_completion.py
python/semantic_kernel/connectors/ai/bedrock/services/model_provider/utils.py
python/semantic_kernel/connectors/ai/google/shared_utils.py
python/tests/integration/completions/chat_completion_test_base.py

Closes #10619 
Bedrock updated its rules on tool names. Previously, Bedrock disallowed "-" in tool names, which is the default plugin name and function name separator in SK. The solution was to use "_" as the separator. However, this introduced a bug where the translation between the SK fully qualified function names and the Bedrock tool names would fail if the function name had an underscore.
Bedrock now allows "-" in tool names, so we can remove the custom logic and just use the default.
Gemini also has rules on how tools are named. It doesn't recommend using "-". The solution was to use "_" just like Bedrock. To address the bug mentioned above, the solution is to use double underscores.
1. Remove Bedrock custom fully qualified function names.
2. Use double underscores for Gemini fully …

Python: Remove custom separator in Bedrock tool call fully qualified name

---

dotnet/src/SemanticKernel.Abstractions/Contents/ChatMessageContent.cs

This PR removes the `EditorBrowsable(EditorBrowsableState.Never)` attribute from the `ChatMessageContent.Content` property because it is confusing and can be handy to set text content with a one-liner: `cmc.Content = "some content"`.

.Net: Remove EditorBrowsable(EditorBrowsableState.Never) from ChatMessageContent.Content property

---

python/samples/demos/process_with_dapr/process/steps.py
python/semantic_kernel/processes/dapr_runtime/actors/step_actor.py
python/uv.lock

In the current Dapr step activation code, we know what state (if it exists) is to be activated, but we're forcing the step to perform that operation. We can perform the validation internally to remove the burden from the dev to have to do this (making it less error prone). 
Perform model validation internally, removing the need to do it from each step.

Python: During Dapr step activation, perform model validate internally

---

.github/workflows/dotnet-format.yml
dotnet/src/Experimental/Process.Abstractions/IKernelExternalProcessMessageChannel.cs

In sdk9, there is a bug fix to one of the analyzers: [https://github.com/dotnet/msbuild/issues/11426](https://github.com/dotnet/msbuild/issues/11426). This causes the code base to fail in the `dotnet format` stage when built on sdk9.
This PR fixes the file that has been changed this week and adds a configuration into the build to format using sdk9.0 so that the build fails if more are introduced.
This relates to #10716 and was previously fixed in #10741

.Net: Changes to support .NET9 formatting

---

dotnet/src/Connectors/VectorData.Abstractions/RecordDefinition/VectorStoreRecordKeyProperty.cs

…Property
The Definition Property classes support easy cloning with modifications via a pattern like this:
```csharp
var clonedProp = new VectorStoreRecordVectorProperty(oldprop) { Dimensions = 100 };
```
Updating VectorStoreRecordKeyProperty, so that the new property on it also gets cloned by default.

.Net: Small fix to support cloning for new property on VectorStoreRecordKeyProperty

---

python/.cspell.json
python/pyproject.toml
python/samples/concepts/memory/complex_memory.py
python/samples/concepts/memory/simple_memory.py
python/semantic_kernel/connectors/memory/faiss.py
python/semantic_kernel/connectors/memory/in_memory/in_memory_collection.py
python/semantic_kernel/data/vector_storage/vector_store.py
python/tests/conftest.py
python/tests/unit/connectors/memory/faiss/test_faiss.py
python/uv.lock

This PR adds a FaissVectorStore and FaissCollection
Faiss is a really fast similarity search engine, which runs in memory.
You can also use GPU's with it, but you will have to build the package yourself.
Closes #4130
TODO:

Python: Introducing the Faiss Connector

---

dotnet/src/VectorDataIntegrationTests/RedisIntegrationTests/Filter/RedisBasicFilterTests.cs

Bool is not supported for filtering on Redis
Change three more Redis filtering tests on bools to expect InvalidOperationException

.Net: Change three more Redis filtering tests on bools to expect InvalidOperationException

---

dotnet/samples/GettingStartedWithAgents/BedrockAgent/Step01_BedrockAgent.cs
dotnet/samples/GettingStartedWithAgents/BedrockAgent/Step02_BedrockAgent_CodeInterpreter.cs
dotnet/samples/GettingStartedWithAgents/BedrockAgent/Step03_BedrockAgent_Functions.cs
dotnet/samples/GettingStartedWithAgents/BedrockAgent/Step04_BedrockAgent_Trace.cs
dotnet/samples/GettingStartedWithAgents/BedrockAgent/Step05_BedrockAgent_FileSearch.cs
dotnet/samples/GettingStartedWithAgents/BedrockAgent/Step06_BedrockAgent_AgentChat.cs
dotnet/src/Agents/Bedrock/BedrockAgent.cs
dotnet/src/IntegrationTests/Agents/BedrockAgentTests.cs
dotnet/src/InternalUtilities/samples/AgentUtilities/BaseBedrockAgentTest.cs

Following the construction pattern of the other agent types where clients are required to construct the agents. This change makes the Bedrock agent clients required and public.
Makes the Bedrock agent clients required at construction time and public.

.Net: Make Bedrock agent clients required and public

---

dotnet/src/Connectors/Connectors.Amazon.UnitTests/Extensions/BedrockKernelBuilderExtensionTests.cs
dotnet/src/Connectors/Connectors.Amazon/Bedrock/Core/BedrockServiceFactory.cs

…fix from model id
If present, removes the "us.", "eu.", or "apac." preceding the model id when selecting the correct model service for the given model.
1. Why is this change required? This is to allow the use of cross-region inference models in the Amazon Bedrock connector.
2. What problem does it solve? This fixes a bug in `BedrockServiceFactory.cs` in which the cross-regional identifier in a model was getting treated as an LLM provider.
3. What scenario does it contribute to? Use of cross-regional inference models in Amazon Bedrock, namely Claude 3.7 Sonnet from a us-west-2 data center.
4. If it fixes an open issue, please link to the issue here. 
* #10738 
* #10047 
This is a minimal-change quick fix for enabling cross-regional models in Amazon Bedrock. It looks for one of the three …

.Net: scrub preceding cross region identifier in Amazon Bedrock model IDs

---

python/semantic_kernel/agents/open_ai/assistant_content_generation.py
python/semantic_kernel/agents/open_ai/assistant_thread_actions.py

The OpenAI assistant code is using an import from the AzureAIAgent related code, and when not installing the `azure` extras, this causes an import error.
Use OpenAI assistant specific thread action code.
- Closes #10942

Python: Use openai assistant methods not azure ai

---

python/semantic_kernel/connectors/memory/pinecone/_pinecone.py
python/semantic_kernel/connectors/memory/pinecone/pinecone_settings.py
python/semantic_kernel/data/vector_storage/vector_store_record_collection.py
python/tests/unit/connectors/memory/pinecone/test_pinecone.py
python/tests/unit/data/test_vector_search_base.py
python/tests/unit/data/test_vector_store_record_collection.py
python/uv.lock

Pinecone offers integrated embeddings, expended the way you can set up for that
Made some fixes in the DeSer process of the vector stores to deal with non-returned vectors.
Now (finally) uses local_embeddings field to allow the field to be present but not used.

Python: small fix for Pinecone integrated embeddings

---

dotnet/src/Experimental/Process.UnitTests/Runtime.Local/LocalMapTests.cs
dotnet/src/Experimental/Process.UnitTests/Runtime.Local/LocalProxyTests.cs
dotnet/src/InternalUtilities/process/TestsShared/Steps/CommonSteps.cs

By default, xUnit runs tests in parallel. What we were  doing so far was having a static, mutable counter that some tests were setting to 0, while other could use in the meantime (increment or read and assert).
I've changed it to use a static dictionary of counters, where the name of the step is the key. So each step has it's own counter.
fixes #11001

.Net: don't use a mutable static counter for tests that can run in parallel

---

dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerCommandBuilder.cs
dotnet/src/VectorDataIntegrationTests/SqlServerIntegrationTests/SqlServerCommandBuilderTests.cs

.Net MEVD: Fix String mapping for SQL Server connector

---

dotnet/src/Functions/Functions.OpenApi/Extensions/OpenApiFunctionExecutionParameters.cs
dotnet/src/Functions/Functions.OpenApi/RestApiOperationResponseFactory.cs
dotnet/src/Functions/Functions.OpenApi/RestApiOperationResponseFactoryContext.cs
dotnet/src/SemanticKernel.Abstractions/Functions/RestApiOperationResponse.cs

Some OpenAPI APIs have been available for a while and can be considered stable.

.Net: Make a few OpenAPI APIs non-experimental

---

dotnet/Directory.Packages.props
dotnet/samples/Concepts/ChatCompletion/HybridCompletion_Fallback.cs
dotnet/samples/Concepts/Concepts.csproj
dotnet/samples/Concepts/Plugins/CreatePluginFromOpenApiSpec_Github.cs
dotnet/samples/Demos/AIModelRouter/AIModelRouter.csproj
dotnet/samples/Demos/CopilotAgentPlugins/CopilotAgentPluginsDemoSample/CopilotAgentPluginsDemoSample.csproj
dotnet/samples/Demos/OllamaFunctionCalling/OllamaFunctionCalling.csproj
dotnet/src/Connectors/Connectors.Ollama.UnitTests/Connectors.Ollama.UnitTests.csproj
dotnet/src/Connectors/Connectors.Ollama.UnitTests/Services/OllamaChatCompletionTests.cs
dotnet/src/Connectors/Connectors.Ollama/Connectors.Ollama.csproj
dotnet/src/IntegrationTests/IntegrationTests.csproj
dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatClientChatCompletionService.cs
dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatCompletionServiceChatClient.cs
dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatCompletionServiceExtensions.cs
dotnet/src/SemanticKernel.UnitTests/AI/ServiceConversionExtensionsTests.cs

A good review would be much appreciated, including considering the higher-level implications of the MEAI-side change for SK (I know very little about SK outside of MEVD!). See specific comments below.

.Net: Sync to MEAI 9.3.0-preview.1.25114.11

---

dotnet/src/Connectors/Connectors.Memory.SqlServer/ExceptionWrapper.cs
dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerVectorStoreRecordCollection.cs
dotnet/src/VectorDataIntegrationTests/SqlServerIntegrationTests/SqlServerVectorStoreTests.cs
dotnet/src/VectorDataIntegrationTests/SqlServerIntegrationTests/Support/SqlServerTestStore.cs

By accepting a connection string rather than a connection itself we can allow the store to be thread safe and we don't need to worry about the lifetime of provided connection.
It's a breaking change, but we really want to steer the users to do the right thing, so the sooner we release it, the better.

.Net MEVD: SqlServerVectorStore should accept a connection string to be thread safe

---

dotnet/src/Connectors/Connectors.Memory.Postgres/AssemblyInfo.cs
dotnet/src/Connectors/Connectors.Memory.Postgres/Connectors.Memory.Postgres.csproj
dotnet/src/Connectors/Connectors.Memory.Postgres/IPostgresDbClient.cs
dotnet/src/Connectors/Connectors.Memory.Postgres/PostgresDbClient.cs
dotnet/src/Connectors/Connectors.Memory.Postgres/PostgresMemoryBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Memory.Postgres/PostgresMemoryEntry.cs
dotnet/src/Connectors/Connectors.Memory.Postgres/PostgresMemoryStore.cs
dotnet/src/Connectors/Connectors.Memory.Postgres/PostgresVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.SqlServer/AssemblyInfo.cs
dotnet/src/Connectors/Connectors.Memory.SqlServer/Connectors.Memory.SqlServer.csproj
dotnet/src/Connectors/Connectors.Memory.SqlServer/ISqlServerClient.cs
dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerClient.cs
dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerMemoryBuilderExtensions.cs
dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerMemoryEntry.cs
dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerMemoryStore.cs

As we add vector store implementations to our connectors, we are moving them to preview and limiting experimental only to the memory store implementation.
- Update Postgres connector from alpha to preview and limit experimental to memorystore only
- Update SqlServer connector from alpha to preview and limit experimental to memorystore only

.Net: Switch postgres and sqlserver to preview, and move experimental to only memory store artifacts.

---

dotnet/src/Connectors/Connectors.Ollama.UnitTests/Services/OllamaChatCompletionTests.cs

These were removed in a previous PR as OllamaSharp changed its API and the previous code no longer compiled. This fixes the code and puts it back.

.Net: Fix and put back Ollama tool asserts

---

dotnet/src/VectorDataIntegrationTests/VectorDataIntegrationTests/CRUD/BatchConformanceTests.cs

While trying to repo #10979 I've realized that we don't have a test for such scenario. So here it is.

.Net MEVD: add new test that ensures that UpsertBatchAsync can insert and update records from the same batch

---

dotnet/src/Connectors/Connectors.Onnx.UnitTests/Connectors.Onnx.UnitTests.csproj
dotnet/src/Connectors/Connectors.Onnx/Connectors.Onnx.csproj
dotnet/src/SemanticKernel.UnitTests/Utilities/ExceptionConverterTests.cs

For quite a while the SYSLIB1222, are present in the solution.
This PR suppress them and another new JSON001 warning.

.Net: Remove old warnings

---

python/tests/unit/connectors/ai/ollama/services/test_utils.py
python/tests/unit/processes/dapr_runtime/test_dapr_actor_registration.py

Improve overall unit test coverage.
- adding unit tests for ollama services utils
- adding unit tests for dapr_actor_registration

Python: Unit tests for ollama services utils and dapr_actor_registration

---

python/samples/getting_started_with_agents/azure_ai_agent/step7_azure_ai_agent_retrieval.py
python/tests/unit/agents/azure_ai_agent/test_agent_content_generation.py

The current AzureAIAgent retrieval sample uses the old `assistant_id` kwarg to retrieve the agent. We need to fix this to use the new `agent_id` kwarg in AzureAIAgent retrieval sample
Fix the kwarg to use `agent_id`.

Python: Fix agent_id kwarg in AzureAIAgent retrieval sample

---

python/semantic_kernel/connectors/ai/open_ai/services/azure_realtime.py

In creating the `AzureRealtimeWebsocket` object, one can use an api key as part of `AzureOpenAISettings`. This api_key is not getting passed to the `AzureOpenAIConfigBase`.
Pass the api key to the config base.
- Closes #11003

Python: Pass api_key to azure config base init

---

python/semantic_kernel/functions/kernel_function.py
python/semantic_kernel/functions/kernel_function_from_method.py
python/semantic_kernel/functions/kernel_parameter_metadata.py
python/tests/unit/functions/test_kernel_function_from_method.py
python/tests/unit/functions/test_kernel_function_from_prompt.py

When trying to do a model dump for `KernelFunction` models, they are failing with a message related to: 
```
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'type'>
```
There are some class-level attributes that cannot be properly serialized.
Exclude dumping certain model attributes from the model dump, which allows the main KernelFunction metadata and its underlying parameters to be serialized.
- Closes #11078 
- Adds unit tests to ensure we have coverage and can dump Pydantic models.

Python: Exclude certain fields from KernelFunction model dump

---

dotnet/src/Connectors/Connectors.AzureOpenAI/Connectors.AzureOpenAI.csproj
dotnet/src/Connectors/Connectors.OpenAI/Connectors.OpenAI.csproj
dotnet/src/SemanticKernel.Core/SemanticKernel.Core.csproj

Removing AllowUnsafeBlocks from the project file as this is no more needed in the current code base. This change ensures the project is safer by disallowing the use of unsafe code blocks.

.Net: Remove AllowUnsafeBlocks

---

dotnet/src/Connectors/Connectors.Google.UnitTests/Core/Gemini/Clients/GeminiChatGenerationTests.cs
dotnet/src/Connectors/Connectors.Google.UnitTests/Core/Gemini/Clients/GeminiCountingTokensTests.cs
dotnet/src/Connectors/Connectors.Google.UnitTests/Core/VertexAI/VertexAIClientEmbeddingsGenerationTests.cs
dotnet/src/Connectors/Connectors.Google/Core/Gemini/Clients/GeminiChatCompletionClient.cs
dotnet/src/Connectors/Connectors.Google/Core/Gemini/Clients/GeminiTokenCounterClient.cs
dotnet/src/Connectors/Connectors.Google/Core/VertexAI/VertexAIEmbeddingClient.cs
dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeClient.cs
dotnet/src/Connectors/Connectors.Pinecone.UnitTests/PineconeClientTests.cs
dotnet/src/InternalUtilities/src/Diagnostics/Verify.cs

This change adds security validation tests for URL injection attempts in various client constructors across the Google and Pinecone connectors. It helps prevent potential security vulnerabilities where malicious URLs could be injected through location or environment parameters.
Added URL injection validation tests for:
- `GeminiChatCompletionClient`
- `GeminiTokenCounterClient`
- `VertexAIEmbeddingClient`
- `PineconeClient`
Each test suite includes:
1. Validation against common URL injection patterns (e.g., malicious protocols, script injection)
2. Verification of valid hostname/environment patterns
3. Consistent testing approach using xUnit Theory tests
The tests ensure that:
- Malicious URL attempts are caught and throw `ArgumentException`
- Valid location/environment names are accepted …

.Net: Update AI Clients to defend against URL injection attacks

---

dotnet/src/Agents/Abstractions/AgentResponseItem.cs
dotnet/src/Agents/AzureAI/AzureAIAgentThread.cs
dotnet/src/Agents/Core/ChatHistoryAgentThread.cs
dotnet/src/Agents/OpenAI/OpenAIAssistantAgentThread.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/InvokeConformance/AzureAIAgentInvokeTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/InvokeConformance/ChatCompletionAgentInvokeTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/InvokeConformance/InvokeTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/InvokeConformance/OpenAIAssistantAgentInvokeTests.cs

- Move invoke tests to subfolder
- Add implicit cast operator from response item to message
- Mark GetMessagesAsync as experimental for each Thread implementation

.Net: Common agent api review feedback 2

---

dotnet/src/Agents/Abstractions/AgentInvokeOptions.cs
dotnet/src/Agents/Abstractions/AgentThread.cs
dotnet/src/Agents/AzureAI/AzureAIAgentThread.cs
dotnet/src/Agents/Core/ChatHistoryAgentThread.cs
dotnet/src/Agents/OpenAI/OpenAIAssistantAgentThread.cs

Responses doesn't support an explicit create and will create a thread on invoke automatically so create is a no-op and there is no id available on create.
Remove returned id from AgentThread.Create to support responses

.Net: Remove returned id from AgentThread.Create to support responses

---

dotnet/src/Agents/UnitTests/Core/AgentThreadTests.cs
dotnet/src/Agents/UnitTests/Core/ChatHistoryAgentThreadTests.cs
dotnet/src/Agents/UnitTests/OpenAI/OpenAIAssistantAgentThreadTests.cs

- Add unit tests for AgentThread and ChatHistoryAgentThread
- Add unit tests for the OpenAIAssistantAgentThread

.Net: Add unit tests for AgentThread and ChatHistoryAgentThread

---

dotnet/src/Agents/Abstractions/Agent.cs
dotnet/src/Agents/Abstractions/AgentThread.cs
dotnet/src/Agents/AzureAI/AzureAIAgentThread.cs
dotnet/src/Agents/Core/ChatHistoryAgentThread.cs
dotnet/src/Agents/OpenAI/OpenAIAssistantAgentThread.cs
dotnet/src/Agents/UnitTests/Core/AgentThreadTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/AgentFixture.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/AgentThreadConformance/AgentThreadTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/AgentThreadConformance/ChatCompletionAgentThreadTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/AzureAIAgentFixture.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/ChatCompletionAgentFixture.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/OpenAIAssistantAgentFixture.cs

Some Agents don't support a direct create operation, and threads are created automatically on first invocation.
Make AgentThread.Create protected and expose on concrete implementations where possible

.Net: Make AgentThread.Create protected and expose on concrete implementations where possible

---

dotnet/src/Agents/Abstractions/AgentThread.cs
dotnet/src/Agents/AzureAI/AzureAIAgentThread.cs
dotnet/src/Agents/Core/ChatHistoryAgentThread.cs
dotnet/src/Agents/OpenAI/OpenAIAssistantAgentThread.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/AzureAIAgentFixture.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/OpenAIAssistantAgentFixture.cs

Add more options to getmessages for each agentthread and improve xml docs.

.Net: Add more options to getmessages for each agentthread and improve xml docs.

---

dotnet/samples/GettingStartedWithAgents/AzureAIAgent/Step01_AzureAIAgent.cs
dotnet/samples/GettingStartedWithAgents/AzureAIAgent/Step02_AzureAIAgent_Plugins.cs
dotnet/samples/GettingStartedWithAgents/AzureAIAgent/Step04_AzureAIAgent_CodeInterpreter.cs
dotnet/samples/GettingStartedWithAgents/AzureAIAgent/Step05_AzureAIAgent_FileSearch.cs
dotnet/samples/GettingStartedWithAgents/AzureAIAgent/Step06_AzureAIAgent_OpenAPI.cs
dotnet/samples/GettingStartedWithAgents/AzureAIAgent/Step07_AzureAIAgent_Functions.cs
dotnet/samples/GettingStartedWithAgents/OpenAIAssistant/Step01_Assistant.cs
dotnet/samples/GettingStartedWithAgents/OpenAIAssistant/Step02_Assistant_Plugins.cs
dotnet/samples/GettingStartedWithAgents/OpenAIAssistant/Step03_Assistant_Vision.cs
dotnet/samples/GettingStartedWithAgents/OpenAIAssistant/Step04_AssistantTool_CodeInterpreter.cs
dotnet/samples/GettingStartedWithAgents/OpenAIAssistant/Step05_AssistantTool_FileSearch.cs
dotnet/samples/GettingStartedWithAgents/OpenAIAssistant/Step06_AssistantTool_Function.cs
dotnet/samples/GettingStartedWithAgents/Step01_Agent.cs
dotnet/samples/GettingStartedWithAgents/Step02_Plugins.cs
dotnet/src/Agents/Abstractions/Agent.cs
dotnet/src/Agents/AzureAI/AzureAIAgent.cs
dotnet/src/Agents/Bedrock/BedrockAgent.cs
dotnet/src/Agents/Bedrock/BedrockAgentThread.cs
dotnet/src/Agents/Core/ChatCompletionAgent.cs
dotnet/src/Agents/OpenAI/OpenAIAssistantAgent.cs
dotnet/src/Agents/OpenAI/OpenAIAssistantAgentThread.cs
dotnet/src/Agents/UnitTests/OpenAI/OpenAIAssistantAgentThreadTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/BedrockAgentFixture.cs

- Update ChatCompletion, AzureAI and Assistant samples to new invocation and thread pattern.
- Update AssistantAgentThread to support an additional set of creation options.

.Net: Update ChatCompletion, AzureAI and Assistant samples to new invocation and thread pattern.

---

dotnet/Directory.Packages.props
dotnet/samples/Demos/AgentFrameworkWithAspire/ChatWithAgent.ApiService/ChatWithAgent.ApiService.csproj
dotnet/samples/Demos/AgentFrameworkWithAspire/ChatWithAgent.Web/ChatWithAgent.Web.csproj

This PR changes Aspire projects to references SK dependencies as project references instead of NuGet packages.
**Note**: This PR targets the `feature-agents-hosting` feature branch.    
**Contributes** to: https://github.com/microsoft/semantic-kernel/issues/10149

.Net: Reference SK projects

---

dotnet/samples/Demos/AgentFrameworkWithAspire/ChatWithAgent.ApiService/Program.cs
dotnet/samples/Demos/AgentFrameworkWithAspire/ChatWithAgent.ApiService/appsettings.json

This PR enables SK telemetry: logs, traces, and metrics using OpenTelemetry.Extensions.Hosting API.
**Note**: This PR targets the `feature-agents-hosting` feature branch.    
**Contributes** to: https://github.com/microsoft/semantic-kernel/issues/10149

.Net: Enable SK telemetry

---

dotnet/src/Agents/Abstractions/Agent.cs
dotnet/src/Agents/Abstractions/AgentThread.cs
dotnet/src/Agents/AzureAI/AzureAIAgent.cs
dotnet/src/Agents/Core/ChatCompletionAgent.cs
dotnet/src/Agents/OpenAI/OpenAIAssistantAgent.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/AgentThreadConformance/AgentThreadTests.cs

OnNewMessage is really a way for agents to communicate with threads, so we don't want this to be publicly exposed.
Change OnNewMessage to be internal.

.Net: Change OnNewMessage to be internal.

---

.github/.linkspector.yml

Enable link checking for hybrid search document because one of the links in it is now available, and exclude the Python development setup document because one of its links has become unavailable.

.Net: Disable link chekc

---

python/semantic_kernel/__init__.py
python/semantic_kernel/agents/__init__.py
python/semantic_kernel/agents/__init__.pyi

Consolidated agent imports initially caused issues by eagerly loading all submodules, which forced users to install every optional dependency -- even if only one agent was needed. This PR introduces a lazy-loading mechanism via `__getattr__` in the top-level `__init__.py` to defer imports until actually accessed. Additionally, a corresponding` __init__.pyi` type stub file is provided to restore full IDE autocompletion and type hints without compromising runtime behavior.
Lazy load agent dependencies.

Python: lazy-loading mechanism for agent dependencies

---

dotnet/samples/Demos/ModelContextProtocolPlugin/Program.cs
dotnet/src/Connectors/Connectors.OpenAI.UnitTests/Core/ClientCoreTests.cs
dotnet/src/Connectors/Connectors.OpenAI/Core/ClientCore.ChatCompletion.cs
dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/AIFunctionKernelFunction.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/FunctionChoiceBehaviorOptions.cs

This PR fixes the issue where the schema of parameters of `AIFunction` was not mapped to the schema of parameters of `KernelFunction`. As a result, the types of parameters of kernel functions were not advertised to the LLM, leading to the LLM calling the function with arguments of incorrect types. For example, the LLM called the list_commits function and provided the string value "4" as an argument for the `perPage` parameter of the number type.
This PR also adds the `RetainArgumentTypes` function choice behavior option, which allows preserving the type of function arguments provided by the LLM for a function call, as opposed to converting the arguments to strings and losing the type information. Without this option, the `AIFunctionKernelFunction` invokes `AIFunction` with string …

.Net: Function parameters/arguments type handling fixes

---

dotnet/src/Agents/Abstractions/Agent.cs
dotnet/src/Agents/Abstractions/AgentThread.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/InvokeConformance/BedrockAgentInvokeTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/InvokeConformance/InvokeTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/InvokeStreamingConformance/InvokeStreamingTests.cs

We were relying on the thread being created when we added messages to it the first time, but in some cases no messages will be added, since the agent could be invoked with no messages.
Fix bug where invoking with no message throws for some agents.

.Net: Fix bug where invoking with no message throws for some agents.

---

python/semantic_kernel/agents/open_ai/assistant_thread_actions.py
python/semantic_kernel/agents/open_ai/open_ai_assistant_agent.py

The current OpenAI assistant get_response and invoke methods don't add the current thread_id to the CMC's metadata, therefore during a `thread.on_new_message(...)` call, the assistant's message will get added again.
Add the `thread_id` to the metadata so we don't add the assistant's response again.
**Todo**: add agent integration tests and check messages so we have coverage for this.

Python: Add thread_id to assistant message to avoid duplication

---

dotnet/src/IntegrationTests/Data/BaseTextSearchTests.cs
dotnet/src/IntegrationTests/Plugins/Web/Tavily/TavilyTextSearchTests.cs
dotnet/src/IntegrationTests/TestSettings/TavilyConfiguration.cs
dotnet/src/Plugins/Plugins.UnitTests/Web/Tavily/TavilyTextSearchTests.cs
dotnet/src/Plugins/Plugins.Web/Tavily/TavilyTextSearch.cs
dotnet/src/Plugins/Plugins.Web/Tavily/TavilyTextSearchOptions.cs

.Net: Tavily image search and integration tests

---

dotnet/samples/Demos/AgentFrameworkWithAspire/ChatWithAgent.ApiService/Controllers/AgentCompletionsController.cs
dotnet/samples/GettingStartedWithAgents/AzureAIAgent/Step01_AzureAIAgent.cs
dotnet/samples/GettingStartedWithAgents/OpenAIAssistant/Step01_Assistant.cs
dotnet/samples/GettingStartedWithAgents/Step01_Agent.cs
dotnet/src/Agents/Abstractions/Agent.cs
dotnet/src/Agents/UnitTests/AgentTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/InvokeConformance/InvokeTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/InvokeStreamingConformance/InvokeStreamingTests.cs

Most invocations take a user message as input, so supporting just passing the string is useful.
Some agents support invoking the agent without any message, so adding explicit support for this is useful.
Add invoke overloads for string and no message.

.Net: Add invoke overloads for string and no message.

---

python/pyproject.toml
python/samples/concepts/README.md
python/samples/concepts/agents/azure_ai_agent/azure_ai_agent_streaming_chat_history_callback.py
python/samples/concepts/agents/openai_assistant/README.md
python/samples/concepts/agents/openai_assistant/openai_assistant_streaming_chat_history_callback.py
python/samples/getting_started_with_agents/azure_ai_agent/README.md
python/semantic_kernel/agents/agent.py
python/semantic_kernel/agents/autogen/autogen_conversable_agent.py
python/semantic_kernel/agents/azure_ai/agent_thread_actions.py
python/semantic_kernel/agents/azure_ai/azure_ai_agent.py
python/semantic_kernel/agents/bedrock/bedrock_agent.py
python/semantic_kernel/agents/chat_completion/chat_completion_agent.py
python/semantic_kernel/agents/open_ai/open_ai_assistant_agent.py
python/tests/unit/agents/azure_ai_agent/test_azure_ai_agent.py
python/tests/unit/agents/chat_completion/test_chat_completion_agent.py
python/tests/unit/agents/openai_assistant/test_open_ai_assistant_agent.py
python/uv.lock

After this week's release of the common agent invocation API, there are some things that we can do as further improvements.
This PR includes updates for:
- Right now we force any agent invocation to provide some type of input, whether a str, a CMC, or a list of str | CMC. At times, there could be a reason, based on using an existing thread or just providing instructions to the agent, that one doesn't need to provide a message to invoke the agent. Updating to make messages optional. Updating the ABC contracts as well.
- For `invoke_stream` calls on agents, there's no need to call `thread.on_new_message` that contains a streaming chunks -- once we move to support memory, this is where the "hook" will be. Removing this call.
- The `get_messages(...)` methods on the …

Python: Common agent invocation API updates

---

dotnet/src/Agents/Abstractions/Agent.cs
dotnet/src/Agents/Core/ChatCompletionAgent.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/InvokeConformance/AzureAIAgentInvokeTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/InvokeConformance/BedrockAgentInvokeTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/InvokeConformance/ChatCompletionAgentInvokeTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/InvokeConformance/InvokeTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/InvokeConformance/OpenAIAssistantAgentInvokeTests.cs

See code comments for further detail.
Add fix to ChatCompletionAgent for function call termination bug

.Net: Add fix to ChatCompletionAgent for function call termination bug

---

python/samples/demos/call_automation/readme.md

The current README for the "call_automation" demo is lacking some important details to be successful at running the demo.
Improve the README around the ordering of the steps and details provided to make it easier for users to run the demo.

Python: Improve call_automation demo README

---

dotnet/src/Connectors/Connectors.Memory.InMemory/InMemoryVectorStoreRecordCollection.cs

When deleting a collection, both `_internalCollections` and `_internalCollectionTypes` must be updated, as they are both used during collection creation.
Note: maintaining two separate dictionaries introduces the risk of temporary inconsistency under concurrency, which can lead to exceptions. Consider synchronizing updates or refactoring to use a single source of truth.
Fix bug causing `Microsoft.Extensions.VectorData.VectorStoreOperationException: Collection already exists.`
Example:
```csharp
var vectorStore = new InMemoryVectorStore();
var def = new VectorStoreRecordDefinition
{
Properties = new List<VectorStoreRecordProperty>
{
new VectorStoreRecordKeyProperty("id", typeof(string)),
new VectorStoreRecordVectorProperty("vec", typeof(ReadOnlyMemory<float>))
}
};
var collection = …
```

.Net: Fix InMemory collection deletion.

---

dotnet/src/Extensions/Extensions.UnitTests/PromptTemplates/Handlebars/HandlebarsPromptTemplateFactoryTests.cs
dotnet/src/SemanticKernel.UnitTests/PromptTemplate/AggregatorPromptTemplateFactoryTests.cs
dotnet/src/SemanticKernel.UnitTests/PromptTemplate/KernelPromptTemplateFactoryTests.cs
dotnet/src/SemanticKernel.UnitTests/Utilities/AIConnectors/FunctionCallsProcessorTests.cs

.Net: Fix the unknow typo

---

dotnet/samples/Concepts/Agents/AzureAIAgent_FileManipulation.cs
dotnet/samples/Concepts/Agents/ChatCompletion_FunctionTermination.cs
dotnet/samples/Concepts/Agents/ChatCompletion_HistoryReducer.cs
dotnet/samples/Concepts/Agents/OpenAIAssistant_ChartMaker.cs
dotnet/samples/Concepts/Agents/OpenAIAssistant_FileManipulation.cs
dotnet/samples/Concepts/Agents/OpenAIAssistant_FunctionFilters.cs

Addressing Feedback from bugbash
Removing groupchat from samples that have a single agent and aren't demonstrating a groupchat concept

.Net: Removing groupchat from samples that have a single agent and aren't demonstrating a groupchat concept

---

python/samples/concepts/README.md
python/samples/concepts/agents/azure_ai_agent/azure_ai_agent_prompt_templating.py
python/semantic_kernel/agents/azure_ai/agent_thread_actions.py
python/semantic_kernel/agents/open_ai/assistant_thread_actions.py
python/tests/unit/agents/openai_assistant/test_assistant_thread_actions.py

In our AzureAIAgent and AssistantAgent thread actions, we're not passing the supplied args from the caller through to kernel function call invoke methods. 
This PR fixes that, and makes sure we pass kernel args all the way through the process, so any function calls can leverage the args.
- Adds a concept sample for AzureAIAgent showing how to prompt with different prompt templates.

Python: Pass kernel args through to kernel invoke function call for AzureAIAgent and AssistantAgent

---

.github/workflows/label-needs-port.yml

Fixes the needs port to label workflow to use env variables

use env variables for new issue

---

python/semantic_kernel/agents/azure_ai/azure_ai_agent.py
python/semantic_kernel/agents/open_ai/open_ai_assistant_agent.py

Now that we have a common agent invocation API, that uses threads, we will be deprecating the `add_chat_message` for the `AzureAIAgent` and `OpenAIAssistantAgent`. Add the deprecation decorator and message.
Add the deprecation decorator and message.

Python: Add deprecaton warning to add_chat_message for server agents

---

dotnet/samples/Concepts/Agents/AzureAIAgent_Streaming.cs
dotnet/samples/Concepts/Agents/OpenAIAssistant_Streaming.cs
dotnet/src/Agents/Abstractions/AgentInvokeOptions.cs
dotnet/src/Agents/AzureAI/AzureAIAgent.cs
dotnet/src/Agents/Core/ChatCompletionAgent.cs
dotnet/src/Agents/OpenAI/OpenAIAssistantAgent.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/InvokeConformance/ChatCompletionAgentInvokeTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/InvokeConformance/InvokeTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/InvokeStreamingConformance/InvokeStreamingTests.cs

A concern was raised bout confusion between OnNewMessage on the thread and on the invoke options, so renaming the invoke option callback to try and avoid confusion.
Rename OnNewMessage callback to OnIntermediateMessage

.Net: Rename OnNewMessage callback to OnIntermediateMessage

---

dotnet/src/Agents/AzureAI/AzureAIAgent.cs
dotnet/src/Agents/Bedrock/BedrockAgent.cs
dotnet/src/Agents/Core/ChatCompletionAgent.cs
dotnet/src/Agents/OpenAI/OpenAIAssistantAgent.cs

We should warm users of the timeframe at which obsoleted methods will be deleted.
#11315 
Add a date to the obsolete messages for obsolete methods on the agent implementations.

.Net: Add date to obsolete messages for when to expect these methods to be deleted.

---

python/samples/concepts/agents/openai_responses/responses_agent_message_callback.py
python/samples/concepts/agents/openai_responses/responses_agent_message_callback_streaming.py
python/samples/concepts/agents/openai_responses/responses_agent_plugins_streaming.py
python/samples/getting_started_with_agents/openai_responses/step7_responses_agent_structured_outputs.py

Fix some sample output strings for OpenAIResponsesAgent samples.
Fix some sample output strings for OpenAIResponsesAgent samples.

Python: Update sample output

---

dotnet/src/Connectors/Connectors.Memory.Sqlite/SqliteVectorStoreRecordCollection.cs

#11132
Fix bug in sqlite filter logic

.Net: Fix bug in sqlite filter logic

---

dotnet/src/Agents/Core/ChatHistoryAgent.cs

.Net: Mark ChatHistoryAgent as experimental

---

python/semantic_kernel/agents/open_ai/azure_assistant_agent.py

Add release_candidate decorator for AzureAssistantAgent.
Add release_candidate decorator for AzureAssistantAgent.

Python: Add release_candidate decorator

---

dotnet/src/Connectors/VectorData.Abstractions/VectorSearch/HybridSearchOptions.cs

#11270
Add skip validation for hybrid search options
Not adding for top since we have a parallel pr to remove top

.Net: Add skip validation for hybrid search options

---

python/samples/concepts/processes/plan_and_execute.py

The current version of the processes' "plan and execute" sample worked but it didn't format the output or intermediate output in a nice way. This PR improves the formatting of the output and thus the final answer.
Improve the sample.

Python: Improve plan and execute sample

---

python/semantic_kernel/connectors/ai/open_ai/services/_open_ai_realtime.py

Fix for how the openai realtime event type constructors deal with enums, fixes #11246

Python: fix for enum handling in openai event creation in realtime

---

dotnet/src/Connectors/Connectors.AzureCosmosDBNoSQL.UnitTests/AzureCosmosDBNoSQLKernelBuilderExtensionsTests.cs
dotnet/src/Connectors/Connectors.AzureCosmosDBNoSQL.UnitTests/AzureCosmosDBNoSQLServiceCollectionExtensionsTests.cs
dotnet/src/Connectors/Connectors.AzureCosmosDBNoSQL.UnitTests/AzureCosmosDBNoSQLVectorStoreRecordCollectionTests.cs
dotnet/src/Connectors/Connectors.AzureCosmosDBNoSQL.UnitTests/AzureCosmosDBNoSQLVectorStoreTests.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/AzureCosmosDBNoSQLVectorStoreRecordCollection.cs

Resolves: https://github.com/microsoft/semantic-kernel/issues/10351
Updated Cosmos NoSQL initialization logic with exception message about using `CosmosClientOptions.UseSystemTextJsonSerializerWithOptions` property.

.Net: [MEVD] Improved Cosmos NoSQL initialization logic

---

python/semantic_kernel/agents/chat_completion/chat_completion_agent.py
python/semantic_kernel/agents/open_ai/openai_responses_agent.py
python/semantic_kernel/agents/open_ai/responses_agent_thread_actions.py
python/tests/integration/agents/azureai_agent/test_azureai_agent_integration.py
python/tests/integration/agents/chat_completion_agent/test_chat_completion_agent_integration.py
python/tests/integration/agents/openai_assistant_agent/test_openai_assistant_agent_integration.py
python/tests/integration/agents/openai_responses_agent/test_openai_responses_agent_integration.py

Add ChatCompletionAgent integration tests. The last set of agent integration tests that aren't available right now. Additionally, as part of creating the tests, it was discovered that we're yielding FunctionCallContent and FunctionResultContent, when we shouldn't be. To handle those content types, one needs to use the `on_intermediate_message` callback. 
Adds ChatCompletionAgent integration tests. 
- Fix Responses Agent thread get_messages method to properly return input messages from the API.

Python: Add ChatCompletionAgent integration tests

---

dotnet/samples/Demos/ModelContextProtocolClientServer/MCPClient/Extensions/PromptResultExtensions.cs
dotnet/samples/Demos/ModelContextProtocolClientServer/MCPClient/Program.cs
dotnet/samples/Demos/ModelContextProtocolClientServer/MCPServer/Extensions/McpServerBuilderExtensions.cs
dotnet/samples/Demos/ModelContextProtocolClientServer/MCPServer/Program.cs
dotnet/samples/Demos/ModelContextProtocolClientServer/MCPServer/Prompts/PromptDefinition.cs
dotnet/samples/Demos/ModelContextProtocolClientServer/MCPServer/Prompts/getCurrentWeatherForCity.json

This PR changes the MCP prompt to be a little more useful so that it can be reused on the client side. Additionally, the prompt registration API is simplified and aligned with the resource and resource template registration APIs - `With*` extension methods. Lastly, it maps prompt messages to a list of chat message content that can be easily added to the chat history on the client side by a hosting app.
Contributes to: https://github.com/microsoft/semantic-kernel/issues/11199

.Net: Update MCP prompt sample

---

python/semantic_kernel/connectors/mcp.py

Resolves #11457
Fixed an issue where a `TypeError` would occur when the inputSchema of a tool listed from the MCP server did not include any required parameters.

Python: Fix `TypeError` when required is missing in MCP tool’s inputSchema

---

python/semantic_kernel/agents/open_ai/responses_agent_thread_actions.py
python/tests/integration/agents/agent_test_base.py
python/tests/integration/agents/azureai_agent/test_azureai_agent_integration.py
python/tests/integration/agents/chat_completion_agent/test_chat_completion_agent_integration.py
python/tests/integration/agents/conftest.py
python/tests/integration/agents/openai_assistant_agent/test_openai_assistant_agent_integration.py
python/tests/integration/agents/openai_responses_agent/test_openai_responses_agent_integration.py

The current integration tests for agents work fine; however, if any errors are encountered due to server-side hiccups, the instant failure cause the whole test run to fail. This PR creates an `agent_test_base` that provides some retry logic, as well as a standardized way for agent test classes to use the underlying methods/protocol. 
Improve the agent integration tests.
- The OpenAI Responses API is throwing 500s for file search right now. Adding `xfail` for the time being. Filed an [issue](https://github.com/openai/openai-python/issues/2298) on them.
- Handle errors when calling for a response for the OpenAI Responses API -- throw a specific agent except or content exception, if received from Azure OpenAI. 
- Removed the `OpenAIResponsesAgent` `invoke` and `invoke_stream` web_search …

Python: Improve agent integration tests

---

dotnet/Directory.Packages.props
dotnet/src/Agents/Bedrock/Extensions/BedrockAgentInvokeExtensions.cs
dotnet/src/Agents/UnitTests/Bedrock/BedrockAgentChannelTests.cs
dotnet/src/Agents/UnitTests/Bedrock/BedrockAgentTests.cs
dotnet/src/Connectors/Connectors.Amazon.UnitTests/Services/BedrockChatCompletionServiceTests.cs
dotnet/src/Connectors/Connectors.Amazon.UnitTests/Services/BedrockTextGenerationServiceTests.cs

Code fixes for https://github.com/microsoft/semantic-kernel/pull/11424

.Net: Bump AWSSDK to 4.0.0-preview.13 in /dotnet

---

python/samples/concepts/mcp/azure_ai_agent_with_mcp_plugin.py

This adds a sample using Azure AI Agents and the local Github MCP server as a plugin.
Partial for: #11463

Python: sample using GitHub MCP Server and Azure AI Agent

---

python/samples/concepts/README.md
python/samples/concepts/agents/azure_ai_agent/azure_ai_agent_truncation_strategy.py
python/semantic_kernel/agents/azure_ai/agent_thread_actions.py

We are not handling the AzureAIAgent truncation strategy object correctly in AgentThreadActions. Fix this and add a sample showing how to configure the object during agent invocation.
Bug fix and sample.

Python: Bug fix for azure ai agent truncate strategy. Add sample.

---

python/samples/demos/call_automation/call_automation.py

cleanup of the call automation sample
cleaner code and clearer seperation of debug and info logs.

Python: small code improvements in code of call automation sample

---

dotnet/samples/GettingStartedWithAgents/OpenAIResponse/Step02_ConversationState.cs
dotnet/src/Agents/OpenAI/Agents.OpenAI.csproj
dotnet/src/Agents/OpenAI/OpenAIResponseAgent.cs
dotnet/src/Agents/OpenAI/OpenAIResponseAgentThread.cs
dotnet/src/Agents/UnitTests/OpenAI/OpenAIResponseAgentThreadTests.cs

Response to this suggestion:
_Instead of having a StoreEnabled on the agentThread, consider supporting two thread types, e.g. ChatHistoryAgentThread and OpenAIResponseAgentThread._

.Net: Use ChatHistoryAgentThread with OpenAIResponseAgent

---

python/samples/concepts/mcp/README.md
python/samples/concepts/mcp/agent_with_mcp_plugin.py
python/samples/concepts/mcp/agent_with_mcp_prompt_sampling.py
python/samples/concepts/mcp/agent_with_mcp_sampling.py
python/samples/concepts/mcp/azure_ai_agent_with_local_server.py
python/samples/concepts/mcp/azure_ai_agent_with_mcp_plugin.py
python/samples/concepts/mcp/local_agent_with_local_server.py
python/samples/concepts/mcp/mcp_as_plugin.py
python/samples/demos/sk_mcp_server/mcp_server_with_prompts.py
python/samples/demos/sk_mcp_server/mcp_server_with_sampling.py
python/samples/demos/sk_mcp_server/sk_mcp_server.py
python/semantic_kernel/connectors/mcp.py
python/semantic_kernel/functions/kernel_function_decorator.py
python/semantic_kernel/functions/kernel_function_extension.py
python/semantic_kernel/functions/kernel_function_from_method.py
python/semantic_kernel/kernel.py
python/semantic_kernel/services/kernel_services_extension.py

Allow a list of prompts to be added and exposed with the MCP server setup.
This uses the built-in rendering types (all of them) to be used and exposed as prompts.
Closes: #11143

Python: add support for prompts and sample

---

dotnet/src/IntegrationTests/Data/BaseTextSearchTests.cs
dotnet/src/IntegrationTests/Plugins/Web/Brave/BraveTextSearchTests.cs
dotnet/src/IntegrationTests/TestSettings/BraveConfiguration.cs
dotnet/src/Plugins/Plugins.UnitTests/Web/Brave/BraveTextSearchTests.cs
dotnet/src/Plugins/Plugins.Web/Brave/BraveTextSearch.cs

1. Update BraveTextSearch to use latest `ITextSearch`
2. Add integration tests

.Net: Update BraveTextSearch to use new ITextSearch

---

dotnet/samples/Demos/ModelContextProtocolPlugin/Program.cs

Extremely high token consumption when running this demo: [https://github.com/microsoft/semantic-kernel/tree/main/dotnet/samples/Demos/ModelContextProtocolPlugin](https://github.com/microsoft/semantic-kernel/tree/main/dotnet/samples/Demos/ModelContextProtocolPlugin)
When calling the ChatCompletionAgent with the default 'false' value for RetainArgumentTypes, all arguments are converted to string values which causes some of the tool calls to fail. The agent then iterates through other tools, searching for a successful response. This results in 80-85k tokens being consumed where only 11-12k should be consumed.
This PR will update the ModelContextProtocolPlugin demo to re-use the configured PromptExecutionSettings object that includes the correct value for `RetainArgumentTypes`.

.Net: add 'RetainArgumentTypes' to agent arguments for ModelContextProtocolPlugin demo

---

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreRecordCollection.cs
dotnet/src/VectorDataIntegrationTests/VectorDataIntegrationTests/Filter/BasicFilterTests.cs
dotnet/src/VectorDataIntegrationTests/VectorDataIntegrationTests/Filter/BasicQueryTests.cs

When I introduced `BasicQueryTests` in #11112, the idea was that this class derives from `BasicFilterTests` and overrides method that gets the resuls to call `GetAsync` rather than `VectorizedSearchAsync`:
When @roji was working on `BasicFilterTests` in #11392 to extend them with the capability to use dynamic model for filtering, he wanted to remove the ordering that was introduced in `BasicQueryTests` https://github.com/microsoft/semantic-kernel/pull/11392#discussion_r2037066364
but it seems that by mistake @roji has also removed the call to `GetAsync`. So `BasicQueryTests` was testing exactly the same thing 
`BasicFilterTests` did:

.Net MEVD: fix two bugs

---

dotnet/samples/Concepts/FunctionCalling/MultipleFunctionsVsParameters.cs

The description of the parameter of `SearchByPurchaseOrder` method is incorrect. Update it to `PO` so the model can recognize the parameter correctly.

.Net: Update MultipleFunctionsVsParameters.cs to fix the parameter description in the SearchByPurchaseOrder function

---

dotnet/src/SemanticKernel.Abstractions/AbstractionsJsonContext.cs

Fixes the issue of function arguments serialization of SK functions created from functions of `M.E.AI.AIFunction` type.
Fixes: https://github.com/microsoft/semantic-kernel/issues/11600

.Net: Fix sk function arguments serialization

---

dotnet/nuget/nuget-package.props
dotnet/src/Connectors/Connectors.Google/Models/Gemini/GeminiChatMessageContent.cs

Changes from https://github.com/microsoft/semantic-kernel/pull/11236/files

.Net: Update GeminiChatMessageContent to support System.Text.Json deserialization when calledToolResult is null

---

dotnet/samples/Concepts/ChatCompletion/Google_GeminiStructuredOutputs.cs
dotnet/src/Connectors/Connectors.Google.UnitTests/Core/Gemini/GeminiRequestTests.cs
dotnet/src/Connectors/Connectors.Google/Core/Gemini/Models/GeminiRequest.cs

- Fix #11395 
AIJsonUtilities Schema generation does not generate the `type` for `enum` properties, this workaround became necessary to allow enums to be used with VertexAI/GoogleAI API's.
FYI @eiriktsarpalis

.Net: Fix Google Gemini Enums Schema definition

---

dotnet/src/Experimental/Process.Abstractions/KernelProcessEventData.cs
dotnet/src/Experimental/Process.Abstractions/Process.Abstractions.csproj

Processes Samples Step 04 doesn't work after latest serialization update in KernelProcessEventData
Fixes #11694

.Net: fixing KernelProcessEventData toObject

---

dotnet/src/SemanticKernel.Core/Memory/Mem0/Mem0Client.cs
dotnet/src/SemanticKernel.Core/Memory/Mem0/Mem0MemoryComponent.cs
dotnet/src/SemanticKernel.Core/Memory/Mem0/Mem0MemoryComponentOptions.cs
dotnet/src/SemanticKernel.UnitTests/Memory/Mem0MemoryComponentTests.cs

#10100
#10712
- Add unit tests for the mem0 memory component
- Allow context prompt to be configurable

.Net: Add unit tests for the mem0 component

---

python/semantic_kernel/agents/azure_ai/agent_thread_actions.py
python/semantic_kernel/agents/open_ai/assistant_thread_actions.py
python/tests/integration/agents/azureai_agent/test_azureai_agent_integration.py
python/tests/integration/agents/openai_assistant_agent/test_openai_assistant_agent_integration.py
python/tests/integration/agents/openai_responses_agent/test_openai_responses_agent_integration.py

We are currently not returning the thread id and run id from the Azure AI and Assistant agents. These properties will be useful for evaluation purposes.
Return the thread id and run id in the agent response metadata.

Python: Return thread id and run id in agent response metadata

---

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchFilterTranslator.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBFilterTranslator.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/AzureCosmosDBNoSqlFilterTranslator.cs
dotnet/src/Connectors/Connectors.Memory.Common/SqlFilterTranslator.cs
dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoDBFilterTranslator.cs
dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeFilterTranslator.cs
dotnet/src/Connectors/Connectors.Memory.Postgres/PostgresFilterTranslator.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantFilterTranslator.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisFilterTranslator.cs
dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerFilterTranslator.cs
dotnet/src/Connectors/Connectors.Memory.Sqlite/SqliteFilterTranslator.cs
dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateFilterTranslator.cs
dotnet/src/Connectors/VectorData.Abstractions/ConnectorSupport/Filter/FilterTranslationPreprocessor.cs
dotnet/src/Connectors/VectorData.Abstractions/ConnectorSupport/Filter/QueryParameterExpression.cs

This is a refactor-only change, with no functional changes. It extracts out all logic for identifying and processing captured variables ("parameters") out to a new FilterTranslationProcessor connectos support type in MEVD.
* Most databases don't support parameterization; for these we simply inline the captured variables. Connector translators see these as constants without ever having to know about captured variables etc.
* SQL databases do support parameterization. For these, the preprocessor transforms the captured variable (which is a complex tree construct) into a simple QueryParameterExpression, which can easily be pattern-matched in connector translator code.
This is preparatory work for #11673 (we need a centralized place to do this kind of thing).

.Net: Introduce a LINQ filter preprocessor in MEVD

---

dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromPrompt.cs
dotnet/src/SemanticKernel.Core/KernelExtensions.cs
dotnet/src/SemanticKernel.Core/Memory/MemoryBuilder.cs
dotnet/src/SemanticKernel.Core/Memory/SemanticTextMemory.cs

Core is very close to the code coverage threshold so excluding some functions from code coverage
1. CaptureUsageDetails
2. CreatePluginFromPromptDirectory no longer a recommended pattern
3. MemoryBuilder and SemanticTextMemory are being deprecated
Before
After

.Net: Exclude some code for which we don't need to add code coverage

---

dotnet/src/Agents/AzureAI/AzureAIAgent.cs
dotnet/src/Agents/Bedrock/Agents.Bedrock.csproj
dotnet/src/Agents/Bedrock/BedrockAgent.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/AgentThreadConformance/BedrockAgentThreadTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/AgentWithStatePartConformance/AgentWithStatePartTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/AgentWithStatePartConformance/BedrockAgentWithStatePartTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/BedrockAgentFixture.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/InvokeConformance/BedrockAgentInvokeTests.cs

#10100
#10712
- Add support to BedrockAgent for conversation state parts
- Fix issue in AzureAIAgent with instructions merging
- Add more integration tests

.Net: Update Bedrock Agent to support conversation state and improve tests.

---

dotnet/src/Connectors/Connectors.Memory.Chroma/README.md
dotnet/src/Connectors/Connectors.Memory.Kusto/README.md
dotnet/src/Connectors/Connectors.Memory.Milvus/README.md
dotnet/src/Connectors/Connectors.Memory.MongoDB/README.md
dotnet/src/Connectors/Connectors.Memory.Postgres/README.md
dotnet/src/Connectors/Connectors.Memory.Redis/README.md

We have some broken links in the readme's and they are still referring to memory store which is being replaced.
- Updated readme files to not advertise memory store anymore.
- Updated readme files to point to learn site docs.

.Net: Update vector store readme's

---

dotnet/src/IntegrationTests/Connectors/Memory/MongoDB/MongoDBVectorStoreFixture.cs
dotnet/src/IntegrationTests/Connectors/Memory/MongoDB/MongoDBVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/IntegrationTests.csproj

The docker container for mongo db is often not accessible when running the tests
- Switching to the mongo db test container to try and reduce the flakiness of the tests
- Adding retries

.Net: Try to reduce mongodb test flakiness

---

docs/decisions/0067-hybrid-search.md

The mongo link in one of the ADR's was gone, replaced.

replace mongo link

---

python/samples/getting_started_with_processes/README.md
python/semantic_kernel/processes/dapr_runtime/actors/process_actor.py
python/semantic_kernel/processes/dapr_runtime/dapr_kernel_process.py
python/semantic_kernel/processes/dapr_runtime/dapr_kernel_process_context.py
python/semantic_kernel/processes/local_runtime/local_kernel_process.py
python/semantic_kernel/processes/local_runtime/local_kernel_process_context.py
python/semantic_kernel/processes/local_runtime/local_process.py
python/tests/unit/processes/dapr_runtime/test_dapr_kernel_process.py
python/tests/unit/processes/dapr_runtime/test_dapr_kernel_process_context.py
python/tests/unit/processes/local_runtime/test_local_process.py

Today in Python processes the `max_supersteps` config is hidden from the caller. The internal execute method defaults the value to 100, and this doesn't allow for developers to leverage custom values depending on their use cases.
Provide a way for callers to pass in `max_supersteps` via the process runtime `start` method. 
- Update README
- Update unit tests accordingly.

Python: Support callers passing in max supersteps for processes

---

python/semantic_kernel/kernel.py
python/tests/unit/kernel/test_kernel.py

The existing implementation of `kernel.invoke_function_call(...)` stores mutable tool return values by reference. Subsequent mutations to the same in-memory state bleed into earlier chat messages, which corrupts conversation history and breaks reproducibility. By deep-copying the function result immediately after execution, we can guarantee an immutable snapshot of each tool's output at the time of invocation, which preserves previous tool invocations and removes unwanted side effects.
After `await stack(invocation_context)` in `kernel.invoke_function_call(...)`, we now have:
```python
if invocation_context.function_result and invocation_context.function_result.value is not None:
invocation_context.function_result.value = copy.deepcopy(
invocation_context.function_result.value
)
```
This …

Python: Deep-copy `function_result.value` in `invoke_function_call` to prevent state mutation

---

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchFilterTranslator.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBFilterTranslator.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/AzureCosmosDBNoSqlFilterTranslator.cs
dotnet/src/Connectors/Connectors.Memory.Common/SqlFilterTranslator.cs
dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoDBFilterTranslator.cs
dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeFilterTranslator.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantFilterTranslator.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisFilterTranslator.cs
dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateFilterTranslator.cs
dotnet/src/Connectors/VectorData.Abstractions/ConnectorSupport/Filter/FilterTranslationPreprocessor.cs
dotnet/src/VectorDataIntegrationTests/VectorDataIntegrationTests/Filter/BasicFilterTests.cs

.Net: Evaluate MemberAccess of constants in filter translators

---

dotnet/MEVD.slnf

This adds a [solution filter](https://learn.microsoft.com/en-us/visualstudio/msbuild/solution-filters?view=vs-2022) for MEVD only, including the connectors and test projects (unit and integration). This allows loading only MEVD-related projects, which makes working fast/easier.
Note that the IntegrationTests project is not included, since it also references lots of other, non-MEVD projects (that would defeat the purpose). Our plan is to move the MEVD tests from this project to the new ones, so this will go away on its own.

.Net: Add MEVD solution filter

---

dotnet/src/Connectors/VectorData.Abstractions/VectorSearch/IKeywordHybridSearch.cs
dotnet/src/Connectors/VectorData.Abstractions/VectorSearch/IVectorSearch.cs
dotnet/src/Connectors/VectorData.Abstractions/VectorSearch/IVectorizableTextSearch.cs
dotnet/src/Connectors/VectorData.Abstractions/VectorSearch/KeywordHybridSearchExtensions.cs
dotnet/src/Connectors/VectorData.Abstractions/VectorSearch/VectorSearchExtensions.cs
dotnet/src/Connectors/VectorData.Abstractions/VectorStorage/IVectorStore.cs
dotnet/src/Connectors/VectorData.Abstractions/VectorStorage/VectorStoreExtensions.cs
dotnet/src/Connectors/VectorData.Abstractions/VectorStorage/VectorStoreMetadata.cs
dotnet/src/Connectors/VectorData.Abstractions/VectorStorage/VectorStoreRecordCollectionMetadata.cs

Removed Experimental flag from GetService method as discussed during design review meeting.

.Net: [MEVD] Removed Experimental flag from GetService method

---

dotnet/src/Plugins/Plugins.Core/CodeInterpreter/SessionsPythonPlugin.cs

This PR refactors the `SessionsPythonPlugin` to use the `SendWithSuccessCheckAsync` extension methods to align the handling of HTTP requests with the other SK components. Additionally, it fixes minor logging-related issues and moves a private method down the plugin file for better readability.
Contributes to: https://github.com/microsoft/semantic-kernel/issues/10070

.Net: Use SendWithSuccessCheck extension methods

---

dotnet/src/Connectors/Connectors.AzureCosmosDBNoSQL.UnitTests/AzureCosmosDBNoSQLDynamicDataModelMapperTests.cs
dotnet/src/Connectors/Connectors.AzureCosmosDBNoSQL.UnitTests/AzureCosmosDBNoSQLVectorStoreRecordMapperTests.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/AzureCosmosDBMongoDBVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/AzureCosmosDBNoSQLDynamicDataModelMapper.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/AzureCosmosDBNoSQLVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/AzureCosmosDBNoSQLVectorStoreRecordMapper.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/ICosmosNoSQLMapper.cs
dotnet/src/Connectors/Connectors.Memory.InMemory/InMemoryVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoDBVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisHashSetVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStoreRecordCollection.cs
dotnet/src/Connectors/Connectors.MongoDB.UnitTests/MongoDBDynamicDataModelMapperTests.cs
dotnet/src/Connectors/Connectors.MongoDB.UnitTests/MongoDBVectorStoreRecordMapperTests.cs
dotnet/src/Connectors/VectorData.Abstractions/VectorStorage/VectorStoreCollection.cs
dotnet/src/InternalUtilities/connectors/Memory/MongoDB/IMongoDBMapper.cs
dotnet/src/InternalUtilities/connectors/Memory/MongoDB/MongoDBDynamicDataModelMapper.cs
dotnet/src/InternalUtilities/connectors/Memory/MongoDB/MongoDBVectorStoreRecordMapper.cs

* Add default non-concurrent implementations to VectorStoreCollection for GetAsync and DeleteAsync - but not for UpsertAsync. The reason is that when upserting, the provider (usually) needs to generate embeddings, and this is definitely not something that should happen separately for every record (IEmbeddingGenerators support batching, and a single call should be made for the vector property of all records).
* Some providers were actually implementing batched UpsertAsync this way - fixed them to generate embeddings once before upserting. This just aligns those providers to use the same techniques as other providers which support native batching.
Closes #11854

.Net: Remove concurrent "batching" implementations in MEVD

---

dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/AgentWithTextSearchBehaviorConformance/AgentWithTextSearchBehavior.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/AgentWithTextSearchBehaviorConformance/AzureAIAgentWithTextSearchBehaviorTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/AgentWithTextSearchBehaviorConformance/ChatCompletionAgentWithTextSearchBehaviorTests.cs
dotnet/src/IntegrationTests/Agents/CommonInterfaceConformance/AgentWithTextSearchBehaviorConformance/OpenAIAssistantAgentWithTextSearchBehaviorTests.cs
dotnet/src/SemanticKernel.Core/Data/TextSearchBehavior/TextSearchBehavior.cs
dotnet/src/SemanticKernel.Core/Data/TextSearchBehavior/TextSearchBehaviorOptions.cs
dotnet/src/SemanticKernel.Core/Data/TextSearchStore/TextSearchStore.cs
dotnet/src/SemanticKernel.UnitTests/Data/TextSearchBehaviorTests.cs

- Rename TextRagComponent to TextSearchBehavior
- Add Prompt tests
- Improve prompts

.Net: Rename TextRagComponent, add prompt tests and improve prompts.

---

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBMongoDB/CosmosMongoVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.AzureCosmosDBNoSQL/CosmosNoSqlVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.InMemory/InMemoryVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.Postgres/PostgresVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.Sqlite/SqliteVectorStore.cs
dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateVectorStore.cs

** NOTE: This PR is based on top of #11882, review last commit only **
Note that covariant return types are only supported in C# 9.0 and later, so there's `#if`s in place for .NET Framework.
Closes #11759

.Net: Add covariant return types to VectorStore.GetCollection() implementations

---

python/semantic_kernel/connectors/ai/open_ai/prompt_execution_settings/azure_chat_prompt_execution_settings.py
python/semantic_kernel/connectors/ai/open_ai/prompt_execution_settings/open_ai_prompt_execution_settings.py

SK'S `OpenAIChatPromptExecutions` do not allow one to configure the `extra_body` input to a chat completions create. This is something specified on the Azure OpenAI connector but not on OpenAI. Because there are also custom attributes as part of AOAI, we're providing a base class attribute, and we will keep the child class attribute as-is. 
Introduce the `extra_body` attribute on OpenAI Chat Prompt Execution Settings.
- Closes #11813

Python: Add extra_body attribute to OpenAI Chat settings

---

dotnet/samples/Demos/CodeInterpreterPlugin/Program.cs
dotnet/src/IntegrationTests/Plugins/Core/SessionsPythonPluginTests.cs
dotnet/src/Plugins/Plugins.Core/CodeInterpreter/SessionsPythonPlugin.cs
dotnet/src/Plugins/Plugins.UnitTests/Core/SessionsPythonPluginTests.cs
dotnet/src/Plugins/Plugins.UnitTests/Plugins.UnitTests.csproj

This PR:
1. Propagates the cancellation token from all kernel functions of the `SessionsPythonPlugin` plugin down to the APIs they call.  
2. Refactors the way the plugin adds headers to the request. Instead of adding them as default headers of the HTTP client, they are now added as request headers. The result is the same - the headers are sent each call of any kernel function of the plugin. This change may save time later by preventing bug troubleshooting if/when an HTTP client is injected into the plugin and it sets default headers to the client it does not own.
3. Replaces the usage of HTTP client methods for getting content, such as `ReadAsStringAsync`, with the SK wrappers `ReadAsStringWithExceptionMappingAsync` to align the plugin's behavior with that of other SK components. …

.Net: Add cancellation token & add headers to request

---

dotnet/src/Connectors/Connectors.Memory.Sqlite/SqliteCollection.cs
dotnet/src/Connectors/Connectors.Memory.Sqlite/SqliteCommandBuilder.cs
dotnet/src/Connectors/Connectors.Sqlite.UnitTests/SqliteCommandBuilderTests.cs
dotnet/src/VectorDataIntegrationTests/SqliteIntegrationTests/SqliteIntegrationTests.csproj
dotnet/src/VectorDataIntegrationTests/SqliteIntegrationTests/VectorSearch/SqliteVectorSearchWithFilterConformanceTests.cs
dotnet/src/VectorDataIntegrationTests/VectorDataIntegrationTests/Support/TestStore.cs
dotnet/src/VectorDataIntegrationTests/VectorDataIntegrationTests/VectorSearch/VectorSearchDistanceFunctionComplianceTests.cs
dotnet/src/VectorDataIntegrationTests/VectorDataIntegrationTests/VectorSearch/VectorSearchWithFilterConformanceTests.cs

Resolves: https://github.com/microsoft/semantic-kernel/issues/11655
This PR fixes incorrect SQLite filtering behavior for vector search operation by using Common Table Expression (CTE) for pre-filtering, since filtering within `JOIN` and `WHERE` is not currently supported in `sqlite-vec` extension (more information [here](https://github.com/asg017/sqlite-vec/issues/196)).
Also added base integration test to validate the behavior with vector search and filter and enabled it for SQLite.

.Net: [MEVD] Fixed SQLite filtering behavior

---

python/tests/integration/memory/memory_stores/test_milvus_memory_store.py

The Milvus memory store integration tests have been failing, blocking some PR merges.
Temporarily skipping the Milvus memory store integration test.

Python: Disable Milvus memory store integration tests

---

.github/.linkspector.yml

This PR excludes the `./dotnet/samples/` and `./python/samples/` folders from being inspected by the markdown link checker because some of the links become temporarily unavailable and block PRs.

Exclude python and net samples folders

---

dotnet/src/Connectors/Connectors.Memory.SqliteVec/SqliteCollection.cs

Resolves: https://github.com/microsoft/semantic-kernel/issues/11401
- Removed key `null` filtering for Upsert operations in SQLite connector. 
- Investigated all connectors and it looks like the filtering occurred only in SQLite connector.

.Net: [MEVD] Removed null key filtering for Upsert operations

---

.github/workflows/codeql-analysis.yml

Need to be able to trigger `https://github.com/microsoft/semantic-kernel/actions/workflows/codeql-analysis.yml` in order to verify a change to address a `Code QL` failure.
The `workflow_dispatch:` trigger must be in `main` in order to be used.

Ops: Update `Code QL` workflow for workflow dispatch

---

.github/workflows/codeql-analysis.yml
dotnet/samples/GettingStartedWithAgents/AzureAIAgent/Step08_AzureAIAgent_Declarative.cs
dotnet/samples/GettingStartedWithAgents/BedrockAgent/Step07_BedrockAgent_Declarative.cs
dotnet/samples/GettingStartedWithAgents/OpenAIAssistant/Step07_Assistant_Declarative.cs
dotnet/samples/GettingStartedWithAgents/Step09_Declarative.cs

CodeQL failures:
https://github.com/microsoft/semantic-kernel/actions/runs/14886865134/job/41808680816#step:4:2319
Method calls viewed as ambigious when invoked with empty collection expression "`[]`":
1. `Agent.InvokeAsync(string, AgentThread?, AgentInvokeOptions?, CancellationToken)'`
1. `Agent.InvokeAsync(ICollection<ChatMessageContent>, AgentThread?, AgentInvokeOptions?, CancellationToken)`
Passing workflow: https://github.com/microsoft/semantic-kernel/actions/runs/14890743858

.Net Agents - CodeQL Fix

---

dotnet/format.ps1

As a small improvement to the C# development life cycle, this scripts allows us to identify and correct quickly on branches any format warning that we might have missed.
This will format only the projects that had code changes during the development of your current branch compared to main, ignoring the ones that were untouched.
This was inspired in the current logic that exists in the pipeline, but could easily be ran locally for simplification and faster development.

.Net: Add format script helper

---

dotnet/src/SemanticKernel.Core/Data/TextSearchBehavior/TextSearchBehaviorOptions.cs
dotnet/src/SemanticKernel.UnitTests/Data/TextSearchBehaviorTests.cs

Replace text search behavior delegate options with Func

.Net: Replace text search behavior delegate options with Func

---

dotnet/src/Plugins/Plugins.Core/CodeInterpreter/SessionsPythonCodeExecutionResult.cs
dotnet/src/Plugins/Plugins.UnitTests/Core/SessionsPythonCodeExecutionResultTests.cs

This PR changes the format of Python code execution results from a string, which is the result of concatenating property values, to the product of serializing the result property values. The idea is that AI models can reason well about JSONs but may not reason as effectively over custom strings.

.Net: Serialize python code execution result

---

python/pyproject.toml
python/uv.lock

The last ONNX package version (1.22.0) only has Linux or MacOS available. Windows has not been published. The latest Win available package is 1.21.0. Pinning the Windows package version to 1.21.0 so that we don't break the CI/CD pipeline.
Pin Win package to 1.21.0 so that we don't block the CI pipeline.

Python: Pin ONNX Windows pkg to last available.

---

dotnet/src/Experimental/Process.Abstractions/Serialization/WorkflowSerializer.cs
dotnet/src/Experimental/Process.Core/FoundryProcessBuilder.cs
dotnet/src/Experimental/Process.Core/ProcessBuilder.cs
dotnet/src/Experimental/Process.Core/ProcessExporter.cs
dotnet/src/Experimental/Process.Core/Workflow/WorkflowBuilder.cs
dotnet/src/Experimental/Process.UnitTests/.editorconfig
dotnet/src/Experimental/Process.UnitTests/Process.UnitTests.csproj
dotnet/src/Experimental/Process.UnitTests/ProcessSerializationTests.cs
dotnet/src/Experimental/Process.UnitTests/Resources/combined-workflow.yaml
dotnet/src/Experimental/Process.UnitTests/Resources/dotnetOnlyWorkflow1.yaml
dotnet/src/Experimental/Process.UnitTests/Steps/AStep.cs
dotnet/src/Experimental/Process.UnitTests/Steps/BStep.cs
dotnet/src/Experimental/Process.UnitTests/Steps/CStep.cs
dotnet/src/Experimental/Process.UnitTests/Steps/CommonEvents.cs
dotnet/src/Experimental/Process.UnitTests/Steps/KickoffStep.cs
dotnet/src/Experimental/Process.UnitTests/Steps/ProductInfoProvider.cs

This PR contains a couple of improvements and tests for declarative processes:
1. Added parsing of workflow wrapper on top of non-wrapper declarative format.
2. Added a possibility to specify ID for declarative steps.
3. Fixed the registration of dotnet node by using node ID instead of agent ID.
4. Added unit tests to verify process import from YAML which contains both dotnet and declarative nodes and is compatible with VS Code extension.

.Net: [Feature Branch] Improvements and tests for declarative processes

---

dotnet/Directory.Packages.props
dotnet/samples/GettingStartedWithProcesses/Step04/SchemaGenerator.cs
dotnet/src/Connectors/Connectors.Google/Core/Gemini/Models/GeminiRequest.cs
dotnet/src/Connectors/Connectors.OpenAI.UnitTests/Core/OpenAIJsonSchemaTransformerTests.cs
dotnet/src/Connectors/Connectors.OpenAI/Helpers/OpenAIChatResponseFormatBuilder.cs
dotnet/src/InternalUtilities/src/Schema/KernelJsonSchemaBuilder.cs
dotnet/src/SemanticKernel.UnitTests/AI/ChatCompletion/AIFunctionKernelFunctionTests.cs

cc @RogerBarreto @stephentoub @jeffhandley

.Net: Update to latest version of MEAI and move away from deprecated schema APIs.

---

python/pyproject.toml
python/samples/concepts/mcp/agent_with_mcp_agent.py
python/samples/concepts/mcp/azure_ai_agent_with_local_server.py
python/semantic_kernel/connectors/mcp.py
python/semantic_kernel/utils/validation.py
python/tests/samples/test_concepts.py
python/tests/unit/connectors/memory/azure_cosmos_db/test_azure_cosmos_db_mongodb_collection.py
python/tests/unit/functions/test_kernel_function_metadata.py
python/uv.lock

Removes the two surpressed calls for extra info out of a MCP server, since they seemed to hang every now and then.
Updated the package version spec
Added one of the samples as a integration test
Added:
- load_tools flag on the constructor, default = true
- load_prompt flag on the constructor, default = true
- request_timeout param, optional, default None

Python: fixes and updates for MCP

---

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchCollection.cs
dotnet/src/Connectors/Connectors.Memory.CosmosMongoDB/CosmosMongoCollection.cs
dotnet/src/Connectors/Connectors.Memory.CosmosNoSql/CosmosNoSqlCollection.cs
dotnet/src/Connectors/Connectors.Memory.InMemory/InMemoryCollection.cs
dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoCollection.cs
dotnet/src/Connectors/Connectors.Memory.PgVector/PostgresCollection.cs
dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeCollection.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisHashSetCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonCollection.cs
dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerCollection.cs
dotnet/src/Connectors/Connectors.Memory.SqliteVec/SqliteCollection.cs
dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateCollection.cs

~**NOTE: This is based on top of #12081, review last commit only.**~
#11908 stopped passing dimensions to embedding generation (since that causes failures in some models), but left out SearchAsync. This PR completes that work.
Closes #11902

.Net: Stop setting dimensions when generating embeddings in SearchAsync 

---

python/pyproject.toml
python/uv.lock

Place upper-bound on azure-ai-projects until service is ready
Place upper-bound on azure-ai-projects until service is ready

Python: Place upper-bound on azure-ai-projects until service is ready

---

dotnet/src/Connectors/Connectors.CosmosMongoDB.UnitTests/CosmosMongoCollectionTests.cs
dotnet/src/Connectors/Connectors.CosmosNoSql.UnitTests/CosmosNoSqlCollectionTests.cs
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchCollection.cs
dotnet/src/Connectors/Connectors.Memory.CosmosMongoDB/CosmosMongoCollection.cs
dotnet/src/Connectors/Connectors.Memory.CosmosNoSql/CosmosNoSqlCollection.cs
dotnet/src/Connectors/Connectors.Memory.InMemory/InMemoryCollection.cs
dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoCollection.cs
dotnet/src/Connectors/Connectors.Memory.PgVector/PostgresCollection.cs
dotnet/src/Connectors/Connectors.Memory.PgVector/PostgresDbClient.cs
dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeCollection.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisCollectionSearchMapping.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisHashSetCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonCollection.cs
dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerCollection.cs
dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerCommandBuilder.cs
dotnet/src/Connectors/Connectors.Memory.SqliteVec/SqliteCollection.cs
dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateCollection.cs
dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateQueryBuilder.cs
dotnet/src/Connectors/Connectors.MongoDB.UnitTests/MongoCollectionTests.cs
dotnet/src/Connectors/Connectors.Redis.UnitTests/RedisCollectionSearchMappingTests.cs
dotnet/src/Connectors/Connectors.Weaviate.UnitTests/WeaviateQueryBuilderTests.cs
dotnet/src/Connectors/VectorData.Abstractions/ProviderServices/CollectionModel.cs
dotnet/src/Connectors/VectorData.Abstractions/VectorSearch/IVectorSearchable.cs
dotnet/src/Connectors/VectorData.Abstractions/VectorSearch/RecordSearchOptions.cs
dotnet/src/Connectors/VectorData.Abstractions/VectorStorage/VectorStoreCollection.cs
dotnet/src/SemanticKernel.AotTests/UnitTests/Search/MockVectorizableTextSearch.cs
dotnet/src/SemanticKernel.Core/Data/TextSearch/VectorStoreTextSearch.cs
dotnet/src/VectorDataIntegrationTests/VectorDataIntegrationTests/DependencyInjectionTests.cs

We currently have:
* RecordRetrievalOptions and FilteredRecordRetrievalOptions (for the GetAsync methods)
* RecordSearchOptions (for SearchAsync)
* HybridSearchOptions (for HybridSearchAsync)
As we're a bit inconsistent, we discussed several options:
* Add Record to the hybrid options (RecordHybridSearchOptions), this way all the options have Record in them
* @dmytrostruk suggested just removing Record altogether and have RetrievalOptions, SearchOptions and HybridSearchOptions. While I really like this, I kinda can't bring myself to have a type called SearchOptions (it just feels too short/general, too much potential of confusion/conflict).
* So I'm proposing here to keep HybridSearchOptions, and simply replace RecordSearchOptions with VectorSearchOptions, which seems very clear and …

.Net: Rename RecordSearchOptions -> VectorSearchOptions

---

.github/workflows/dotnet-format.yml
dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchCollection.cs
dotnet/src/Connectors/Connectors.Memory.CosmosMongoDB/CosmosMongoCollection.cs
dotnet/src/Connectors/Connectors.Memory.CosmosNoSql/CosmosNoSqlCollection.cs
dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoCollection.cs
dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeCollection.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisHashSetCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonCollection.cs
dotnet/src/Connectors/Connectors.Memory.SqliteVec/SqliteCollection.cs
dotnet/src/Connectors/Connectors.Memory.SqliteVec/SqliteModelBuilder.cs
dotnet/src/Connectors/Connectors.Memory.SqliteVec/SqlitePropertyMapping.cs
dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateCollection.cs
dotnet/src/Connectors/Connectors.SqliteVec.UnitTests/SqliteCollectionTests.cs
dotnet/src/Connectors/Connectors.SqliteVec.UnitTests/SqliteMapperTests.cs
dotnet/src/Connectors/Connectors.SqliteVec.UnitTests/SqliteVectorStoreTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/SqliteVec/SqliteVectorStoreRecordCollectionTests.cs
dotnet/src/VectorDataIntegrationTests/SqliteVecIntegrationTests/CRUD/SqliteBatchConformanceTests.cs
dotnet/src/VectorDataIntegrationTests/SqliteVecIntegrationTests/CRUD/SqliteRecordConformanceTests.cs
dotnet/src/VectorDataIntegrationTests/SqliteVecIntegrationTests/Filter/SqliteBasicFilterTests.cs
dotnet/src/VectorDataIntegrationTests/SqliteVecIntegrationTests/Filter/SqliteBasicQueryTests.cs

Like other relational databases, Sqlite does not support unsigned integer types ([Sqlite docs](https://sqlite.org/datatype3.html)):
> The value is a signed integer, stored in 0, 1, 2, 3, 4, 6, or 8 bytes depending on the magnitude of the value.
However, our Sqlite provider does allow ulong and ushort (but not uint for some reason), and even "supports" ulong as a key type.
This PR removes support for ulong and ushort. It also updates some docs and error messages now that dynamic support has been split out to a separate type (users can no longer e.g. instantiate `SqliteCollection<object, Dictionary<string, object?>>` directly).
Part of #11784

.Net: Remove unsigned type support from SqliteVec provider

---

dotnet/src/Connectors/Connectors.Memory.AzureAISearch/AzureAISearchCollection.cs
dotnet/src/Connectors/Connectors.Memory.CosmosMongoDB/CosmosMongoCollection.cs
dotnet/src/Connectors/Connectors.Memory.CosmosNoSql/CosmosNoSqlCollection.cs
dotnet/src/Connectors/Connectors.Memory.InMemory/InMemoryCollection.cs
dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoCollection.cs
dotnet/src/Connectors/Connectors.Memory.PgVector/PostgresCollection.cs
dotnet/src/Connectors/Connectors.Memory.PgVector/PostgresModelBuilder.cs
dotnet/src/Connectors/Connectors.Memory.Pinecone/PineconeCollection.cs
dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisFieldMapping.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisHashSetCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonCollection.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonDynamicModelBuilder.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisJsonModelBuilder.cs
dotnet/src/Connectors/Connectors.Memory.Redis/RedisModelBuilder.cs
dotnet/src/Connectors/Connectors.Memory.SqlServer/SqlServerCollection.cs
dotnet/src/Connectors/Connectors.Memory.SqliteVec/SqliteCollection.cs
dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateCollection.cs
dotnet/src/Connectors/VectorData.Abstractions/ProviderServices/CollectionModel.cs
dotnet/src/Connectors/VectorData.Abstractions/ProviderServices/CollectionModelBuilder.cs
dotnet/src/Connectors/VectorData.Abstractions/ProviderServices/VectorDataStrings.cs
dotnet/src/Connectors/VectorData.Abstractions/ProviderServices/VectorPropertyModel.cs
dotnet/src/Connectors/VectorData.Abstractions/ProviderServices/VectorPropertyModel{TInput}.cs
dotnet/src/Connectors/VectorData.UnitTests/CollectionModelBuilderTests.cs
dotnet/src/VectorDataIntegrationTests/VectorDataIntegrationTests/EmbeddingGenerationTests.cs

* An embedding generator now gets configured for all vector properties, including properties with natively supported types like `ReadOnlyMemory<float>`.
* We previously generated embeddings when a generator was configured on a property - that no longer makes sense as generators are always configured on properties (assuming there's a default one). Instead, we now simply check if the property's type is supported as native embedding type or not.
* The IncludeVectors check has also been updated accordingly.
Closes #11842

.Net: Support search-only embedding generation

---

dotnet/src/Connectors/Connectors.Memory.CosmosNoSql/CosmosNoSqlDynamicCollection.cs
dotnet/src/Connectors/Connectors.Memory.SqliteVec/SqliteMapper.cs
dotnet/src/Connectors/Connectors.Memory.Weaviate/WeaviateQueryBuilder.cs
dotnet/src/IntegrationTests/Connectors/Memory/AzureAISearch/AzureAISearchVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/CosmosMongoDB/CosmosMongoCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/CosmosNoSql/CosmosNoSqlCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/CosmosNoSql/CosmosNoSqlVectorStoreTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/MongoDB/MongoDBVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/PgVector/PostgresVectorStoreFixture.cs
dotnet/src/IntegrationTests/Connectors/Memory/PgVector/PostgresVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Qdrant/QdrantVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisHashSetVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Redis/RedisJsonVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/SqliteVec/SqliteVectorStoreFixture.cs
dotnet/src/IntegrationTests/Connectors/Memory/SqliteVec/SqliteVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/Weaviate/WeaviateVectorStoreRecordCollectionTests.cs
dotnet/src/IntegrationTests/Data/BaseTextSearchTests.cs

.Net: Fix integration test and bugs

---

dotnet/src/Connectors/VectorData.Abstractions/ProviderServices/CollectionModelBuilder.cs
dotnet/src/Connectors/VectorData.Abstractions/ProviderServices/VectorDataStrings.cs
dotnet/src/Connectors/VectorData.Abstractions/RecordDefinition/VectorStoreDataProperty.cs
dotnet/src/Connectors/VectorData.Abstractions/RecordDefinition/VectorStoreKeyProperty.cs
dotnet/src/Connectors/VectorData.Abstractions/RecordDefinition/VectorStoreProperty.cs
dotnet/src/Connectors/VectorData.Abstractions/RecordDefinition/VectorStoreVectorProperty.cs
dotnet/src/Connectors/VectorData.UnitTests/CollectionModelBuilderTests.cs

We currently always require the Type to be passed to property definitions. If POCO mapping is used (the common case), that Type must match the .NET property type and has no value - we can simply use the .NET property type and allow the user to not specify it in the definition.
This PR makes Type optional on the property definition, and throws only for dynamic mapping, where we have no .NET properties.

Allow omitting property type from definition

---

dotnet/src/Functions/Functions.UnitTests/OpenApi/Extensions/ApiManifestKernelExtensionsTests.cs

The unit tests for the API manifest have been temporarily disabled to prevent blocking the integration pipeline.

.Net: Disable Api Manifest unit tests

---

dotnet/src/VectorDataIntegrationTests/PgVectorIntegrationTests/PostgresEmbeddingTypeTests.cs

Fixing CodeQL build error:
```
PostgresEmbeddingTypeTests.cs(48,36): error CS0121: The call is ambiguous between the following methods or properties: 'BitArray.BitArray(bool[])' and 'BitArray.BitArray(BitArray)'
```

.Net: Fixing CodeQL failure

---

dotnet/src/InternalUtilities/samples/InternalUtilities/BaseTest.cs

We are seeing exceptions in some samples due to a bug in the `BaseTest.cs` module, that ignores the `modelName` parameter when creating a kernel with chat completion.
This PR ensures that the `modelName` parameter is consistently passed to the `AddChatCompletionToKernel` method.

.Net: Fix BaseTest

---

python/semantic_kernel/connectors/memory/qdrant.py
python/semantic_kernel/connectors/memory/redis.py
python/semantic_kernel/connectors/memory/weaviate.py
python/tests/unit/connectors/memory/test_qdrant.py
python/tests/unit/connectors/memory/test_redis_store.py

Update for Qdrant, Redis, Weaviate

Python: Update Qdrant, Redis, Weaviate

---

python/tests/unit/agents/openai_responses/test_openai_responses_thread_actions.py
python/uv.lock

OpenAI released a new python package (1.81.0) which has some updates to the underlying Pydantic models for the Responses API. We need to pull in a new change for `ResponseOutputItemDoneEvent`, `ResponseOutputItemAddedEvent`, and `ResponseTextDeltaEvent` for streaming invocation which now has `sequence_number` attribute. 
Bring in a change from OpenAI's Python SDK from v1.81.0 related to SK's OpenAIResponsesAgent.

Python: Add OpenAI's sequence_number attribute to unit tests based on their latest package

---

python/samples/getting_started_with_agents/multi_agent_orchestration/step4a_handoff_structured_inputs.py

It's unnecessary to use `KernelBaseModel` in the samples.
Switch to `BaseModel`.

Python: Use BaseModel instead of KernelBaseModel in samples

---

dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatClient_AutoFunctionChoiceBehaviorTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatClient_NoneFunctionChoiceBehaviorTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatClient_RequiredFunctionChoiceBehaviorTests.cs
dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAIChatClient_AutoFunctionChoiceBehaviorTests.cs
dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAIChatClient_NoneFunctionChoiceBehaviorTests.cs
dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAIChatClient_RequiredFunctionChoiceBehaviorTests.cs
dotnet/src/SemanticKernel.Abstractions/AI/ChatClient/KernelFunctionInvokingChatClient.cs
dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/AIFunctionKernelFunction.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/AutoFunctionChoiceBehavior.cs
dotnet/src/SemanticKernel.Abstractions/AI/FunctionChoiceBehaviors/RequiredFunctionChoiceBehavior.cs
dotnet/src/SemanticKernel.Abstractions/AI/PromptExecutionSettingsExtensions.cs
dotnet/src/SemanticKernel.UnitTests/AI/ChatCompletion/AIFunctionKernelFunctionTests.cs

.Net: Fixes MCP Behavior for AIFunction.AsKernelFunction() + Fix ensuring FunctionChoiceBehavior works correctly with IChatClients.

---

dotnet/src/Agents/Orchestration/Handoff/HandoffActor.cs

Handoff orchestration ending task prematurely
- Update description for _end-task_ function
- Ensure user input is published to all orchestration actors

.NET Agents - Update Handoff Orchestration

---

python/semantic_kernel/agents/agent.py
python/semantic_kernel/agents/autogen/autogen_conversable_agent.py
python/semantic_kernel/agents/azure_ai/azure_ai_agent.py
python/semantic_kernel/agents/bedrock/bedrock_agent.py
python/semantic_kernel/agents/chat_completion/chat_completion_agent.py
python/semantic_kernel/agents/copilot_studio/copilot_studio_agent.py
python/semantic_kernel/agents/open_ai/open_ai_assistant_agent.py
python/semantic_kernel/agents/open_ai/openai_responses_agent.py
python/tests/unit/agents/autogen_conversable_agent/test_autogen_conversable_agent.py

This PR relaxes the API signatures of all agent invocation methods (`get_response`, `invoke`, `invoke_stream`) by changing the `messages` parameter from keyword-only to positional-or-keyword. This enhances ergonomics and Pythonic usability by allowing callers to pass messages either positionally or as a keyword argument:
```python
agent.get_response("Why is the sky blue?")
agent.get_response(messages="Why is the sky blue?")
```
With our current use of **kwargs, it is possible to explicitly pass None for messages (like `agent.get_response(messages=None)`). However, this does not feel idiomatic in Python. If a caller wishes to invoke the agent on an existing thread (which already contains all relevant context), it is more natural and Pythonic to simply write:
```python
response = await …
```

Python: Relax Agent Invocation Methods to Allow Positional or Keyword Arguments for `messages`

---

.github/workflows/python-test-coverage-report.yml
.github/workflows/python-test-coverage.yml

Our Python test coverage workflow has been failing due to a breaking in the text format of the test coverage output: https://github.com/MishaKav/pytest-coverage-comment/issues/202.
This PR fixes the issue by switching to xml.

Python: Fix Python test coverage report workflow

---

dotnet/samples/Concepts/Agents/ChatCompletion_ContextualFunctionSelection.cs
dotnet/samples/Concepts/Concepts.csproj
dotnet/samples/Concepts/README.md
dotnet/src/SemanticKernel.Core/Functions/ContextualSelection/ContextualFunctionProvider.cs
dotnet/src/SemanticKernel.Core/Functions/ContextualSelection/ContextualFunctionProviderOptions.cs
dotnet/src/SemanticKernel.Core/Functions/ContextualSelection/FunctionStore.cs
dotnet/src/SemanticKernel.Core/Functions/ContextualSelection/FunctionStoreOptions.cs
dotnet/src/SemanticKernel.UnitTests/Functions/ContextualSelection/ContextualFunctionProviderTests.cs
dotnet/src/SemanticKernel.UnitTests/Functions/ContextualSelection/FunctionStoreTests.cs

This PR adds functionality that allows AI agents to advertise functions relevant to the current context, rather than advertising all available functions.
The functionality is implemented by two components:
- The `FunctionStore` class is responsible for the vectorization of functions, upserting them into the provided vector store, and performing vector searches. This class is internal at the moment as it's used only by the `ContextualFunctionProvider` class. Later, it might be promoted to public if required.
- The `ContextualFunctionProvider` class delegates function vectorization and persistence to the `FunctionStore`. It vectorizes the current context and delegates the vector search to the `FunctionStore` class again.
Logging will be added in follow-up PRs.
Contributes to: …

.Net: Contextual function provider

---

dotnet/src/InternalUtilities/src/Diagnostics/ActivityExtensions.cs
dotnet/src/SemanticKernel.Abstractions/Functions/KernelFunction.cs
python/semantic_kernel/filters/auto_function_invocation/auto_function_invocation_context.py
python/semantic_kernel/filters/kernel_filters_extension.py
python/semantic_kernel/functions/kernel_function.py
python/semantic_kernel/kernel.py
python/semantic_kernel/utils/telemetry/model_diagnostics/function_tracer.py
python/semantic_kernel/utils/telemetry/model_diagnostics/gen_ai_attributes.py

Closing #12262
This PR updates tracing support for function execution across both .NET and Python according to the latest OTel GenAI semantic conventions: https://opentelemetry.io/docs/specs/semconv/gen-ai/gen-ai-spans/#execute-tool-span

Python: Update kernel function span

---

dotnet/samples/Demos/ProcessFrameworkWithAspire/ProcessFramework.Aspire/ProcessFramework.Aspire.ProcessOrchestrator/Program.cs
dotnet/samples/GettingStartedWithProcesses/Step01/Step01_Processes.cs
dotnet/samples/GettingStartedWithProcesses/Step02/Processes/NewAccountCreationProcess.cs
dotnet/samples/GettingStartedWithProcesses/Step02/Processes/NewAccountVerificationProcess.cs
dotnet/samples/GettingStartedWithProcesses/Step02/Step02a_AccountOpening.cs
dotnet/samples/GettingStartedWithProcesses/Step02/Step02b_AccountOpening.cs
dotnet/samples/GettingStartedWithProcesses/Step03/Processes/FishAndChipsProcess.cs
dotnet/samples/GettingStartedWithProcesses/Step04/Step04_AgentOrchestration.cs
dotnet/src/Experimental/Process.Core/ProcessAgentBuilder.cs
dotnet/src/Experimental/Process.Core/ProcessFunctionTargetBuilder.cs
dotnet/src/Experimental/Process.Core/ProcessProxyBuilder.cs
dotnet/src/Experimental/Process.Core/ProcessStepBuilder.cs
dotnet/src/Experimental/Process.IntegrationTests.Resources/ProcessCycleTestResources.cs
dotnet/src/Experimental/Process.IntegrationTests.Shared/ProcessCloudEventsTests.cs
dotnet/src/Experimental/Process.IntegrationTests.Shared/ProcessCycleTests.cs
dotnet/src/Experimental/Process.IntegrationTests.Shared/ProcessTests.cs
dotnet/src/Experimental/Process.LocalRuntime/LocalStep.cs
dotnet/src/Experimental/Process.UnitTests/Runtime.Local/LocalProcessTests.cs
dotnet/src/Experimental/Process.Utilities.UnitTests/CloneTests.cs
dotnet/src/InternalUtilities/process/Abstractions/StepExtensions.cs

- Removing the use of TargetBuilder with multiple parameters in favor of using `process.ListenFor().AllOf()` or simple TargetBuilder
- updating samples and demos to make use of new approach
- changing exposed target builder with function and params to only expose use of function only, keeping function and param for internal use only since some SK Builders require use of piping data to specific params (example: agent step)
- Updating EdgeGroup logic to be compatible with steps that have multiple functions with multiple parameters. Current logic only supports steps with a single function with multiple parameters
- Adding UTs
- Improving unresolved param logic to support internal SK param types and custom param default values

.Net: Removing the use of TargetBuilder with multiple parameters in favor of using process.ListenFor().AllOf() or simple TargetBuilder

---

dotnet/src/IntegrationTests/Plugins/ContextualFunctionProviderTests.cs

Disable flaky integration test that is causing the build to fail.

.Net: disable integration test

---

python/semantic_kernel/connectors/ai/bedrock/README.md
python/semantic_kernel/connectors/ai/bedrock/services/bedrock_base.py
python/semantic_kernel/connectors/ai/bedrock/services/bedrock_chat_completion.py
python/semantic_kernel/connectors/ai/bedrock/services/bedrock_text_completion.py
python/semantic_kernel/connectors/ai/bedrock/services/bedrock_text_embedding.py
python/tests/unit/connectors/ai/bedrock/services/test_bedrock_chat_completion.py
python/tests/unit/connectors/ai/bedrock/services/test_bedrock_text_completion.py
python/tests/unit/connectors/ai/bedrock/services/test_bedrock_text_embedding_generation.py

Closing #10941 
To support more ways (via `model_id`, `inference_profile`, or `model arn`) to send requests to Bedrock models, we have removed the checks on whether a model supports certain features, i.e. streaming and embedding generation. This is because to check for if a model support certain features, we need the model id, but given the flexibility in specifying the target model, it's no longer possible to retrieve the model information realiably.

Python: Remove model info check in Bedrock connectors

---

python/semantic_kernel/functions/kernel_arguments.py
python/tests/unit/functions/test_kernel_arguments.py

`KernelArguments` extends the built-in `dict` by adding an `execution_settings` attribute.
However, when using the `|` and `|=` operators, only the `dict` part (excluding `execution_settings`) is merged, and the result becomes a plain `dict`.
This causes the `execution_settings` attribute to be lost and not updated.
- Implemented support for the `|` and `|=` operators to make it easier for users to merge `KernelArgument` objects.
- The right-hand or left-hand side of the operator can be either a `KernelArgument` or a `dict` (or any subclass of dict).
- When merging, both the `execution_settings` attribute and the rest of the `dict` data are merged individually, and the result is returned as a `KernelArgument`.
- As long as either side of the operator is a `KernelArgument`, the result will …

Python: Support `|` and `|=` operators for `KernelArgument`

---

python/semantic_kernel/connectors/ai/ollama/ollama_prompt_execution_settings.py

Ollama's execution settings currently only allow for `json` literal. We also want to support structured outputs for models that support it.
- Closes #12355
- Supersedes #12386

Python: Allow for structured outputs with Ollama

---

dotnet/SK-dotnet.slnx
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatClient_AutoFunctionChoiceBehaviorTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatClient_RequiredFunctionChoiceBehaviorTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatCompletion_AutoFunctionChoiceBehaviorTests.cs
dotnet/src/IntegrationTests/Connectors/AzureOpenAI/AzureOpenAIChatCompletion_RequiredFunctionChoiceBehaviorTests.cs

Fix integration test configuration where it fails (lags for too long) consistently in the backend for no reason when called in sequence with the same temperature setting.
Integration working as expected:
https://github.com/microsoft/semantic-kernel/actions/runs/15847106990/job/44671729845#logs

.Net:  Fix Integration Test Failure

---

dotnet/Directory.Packages.props
dotnet/src/VectorData/CosmosNoSql/CosmosNoSqlCollectionQueryBuilder.cs
dotnet/test/VectorData/CosmosNoSql.UnitTests/CosmosNoSqlCollectionQueryBuilderTests.cs

The FullTextScore syntax for CosmosNoSql changed after the feature went GA recently so we need to update to the latest SDK version and update the syntax.
#12545

.Net: Update CosmosNoSql to latest SDK and update FullTextScore syntax

---

dotnet/src/Agents/Core/ChatCompletionAgent.cs

.Net: Change ChatCompletionAgent to notify intermediate messages as soon as they are available.

---

dotnet/samples/Demos/A2AClientServer/README.md

.Net: Update README.md

---

.github/dependabot.yml

Seperate dotnet run to handle src and samples separately

---

python/semantic_kernel/agents/orchestration/agent_actor_base.py
python/semantic_kernel/agents/orchestration/group_chat.py
python/semantic_kernel/agents/orchestration/handoffs.py
python/semantic_kernel/agents/orchestration/magentic.py

Some agent threads don't support adding messages. An example of this is the copilot studio agent. 
In an agent orchestration, an agent may receive multiple messages before it is asked to generate a response. The currently approach in the orchestrations would add new messages to an agent thread whenever an agent receives a message, making the copilot studio agent not compatible with some orchestrations.
Instead of adding messages to the agent thread, this PR introduces a message cache to store messages temporarily before the agent is invoked.

Python: Use message cache in agent orchestrations

---

python/semantic_kernel/agents/orchestration/magentic.py
python/tests/unit/agents/orchestration/test_magentic.py
python/uv.lock

When using the magentic orchestration pattern, if the `max_round_count` is hit, the final result shows as:
```
Final result:
Max round count reached.
```
The interim messages do show as part of the `agent_response_callback`; however, not everyone may have that configured. We should return more meaningful results, even if partial. This PR updates to try and get a partial result if it exists. When one calls:
```python
value = await orchestration_result.get()
```
for the `step5_magentic.py` sample, with `max_round_count=1` they should receive the partial result:
```
Final result:
Based on the available data, here is a comparison of the estimated training and inference energy consumption for ResNet-50, BERT-base, and GPT-2, along with the associated CO₂ emissions when training on an Azure …
```

Python: Emit partial result for magentic pattern when retrieving final result, if available

---

dotnet/src/Connectors/Connectors.OpenAI.UnitTests/Extensions/ChatHistoryExtensionsTests.cs
dotnet/src/Connectors/Connectors.OpenAI.UnitTests/Settings/OpenAIPromptExecutionSettingsTests.cs
dotnet/src/Connectors/Connectors.OpenAI/Settings/OpenAIPromptExecutionSettings.cs
dotnet/src/IntegrationTests/Connectors/OpenAI/OpenAIChatClientTests.cs
dotnet/src/SemanticKernel.Abstractions/AI/ChatClient/ChatClientExtensions.cs
dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatClientChatCompletionService.cs
dotnet/src/SemanticKernel.Abstractions/AI/PromptExecutionSettings.cs
dotnet/src/SemanticKernel.UnitTests/AI/ChatCompletion/ChatClientChatCompletionServiceConversionTests.cs
dotnet/src/SemanticKernel.UnitTests/AI/PromptExecutionSettingsTests.cs

.Net: Add Support for {Azure}OpenAIPromptExecutionSettings.ChatSystem/DeveloperPrompt for ChatClients

---

python/semantic_kernel/agents/azure_ai/agent_content_generation.py
python/uv.lock

After the Azure AI Agent service went to GA, there were some updates in the underlying SDK. When there are azure_ai_search results while running the agent, they no longer show up as attributes related to the tool call. They are present in the dictionary, so our current code is failing when trying to access the attribute. This PR updates how we form the FunctionCallContent or FunctionResultContent for both azure_ai_search streaming and non-streaming.
Update how we form the FunctionCallContent or FunctionResultContent for both azure_ai_search streaming and non-streaming for the AzureAIAgent.
- Closes #12422

Python: Properly handle AzureAI Search results for AzureAIAgent

---

dotnet/src/SemanticKernel.Abstractions/Contents/ChatMessageContentExtensions.cs
dotnet/src/SemanticKernel.Abstractions/Contents/StreamingChatMessageContentExtensions.cs

Exposing valuable utilities to convert your existing SK types into MEAI primitives.
This can be particularly useful when you are working with SK types and need to convert them to MEAI primitives for custom scenarios or comparison/evaluation purposes.
CC: @shyamnamboodiripad

.Net: Exposing conversion helpers from SK Contents to MEAI Content primitives 

---

python/semantic_kernel/agents/orchestration/agent_actor_base.py
python/semantic_kernel/agents/orchestration/concurrent.py
python/semantic_kernel/agents/orchestration/group_chat.py
python/semantic_kernel/agents/orchestration/handoffs.py
python/semantic_kernel/agents/orchestration/magentic.py
python/semantic_kernel/agents/orchestration/orchestration_base.py
python/semantic_kernel/agents/orchestration/sequential.py
python/tests/integration/agents/openai_assistant_agent/test_openai_assistant_agent_integration.py
python/tests/unit/agents/orchestration/conftest.py
python/tests/unit/agents/orchestration/test_concurrent.py
python/tests/unit/agents/orchestration/test_group_chat.py
python/tests/unit/agents/orchestration/test_handoff.py
python/tests/unit/agents/orchestration/test_magentic.py
python/tests/unit/agents/orchestration/test_orchestration_base.py
python/tests/unit/agents/orchestration/test_sequential.py

Currently, exceptions that occur inside the orchestration actors are not properly surfaced to the caller as it happens. 
Fixes: https://github.com/microsoft/semantic-kernel/issues/12719
This PR addresses the issue by introducing a new exception_callback that is hidden from the user but will raise exceptions that occurs inside the orchestration actors to the caller.

Python: Improve orchestration exception handling

---

dotnet/src/Agents/Abstractions/Agent.cs

Error message confusing
Error message does not display thread type and instead displays the name of the generic parameter: 
`Microsoft.SemanticKernel.KernelException: OpenAIResponseAgent currently only supports agent threads of type TThreadType.`
(Customer reported an error using the erroneous error message.)

.Net Fix - Display thread type name in error message

---

dotnet/src/IntegrationTests/Connectors/Memory/CosmosMongoDB/CosmosMongoCollectionTests.cs
dotnet/src/IntegrationTests/Connectors/Memory/MongoDB/MongoDBVectorStoreRecordCollectionTests.cs

Two of the MongoDB tests intermittently fail when run on our CI (once they are enabled).
This is, I believe, because two different tests are using and setting up the same collection name.
Rename the Filter test to not use the Offset test collection name.

.Net: Ensure MongoDB filter/offset tests don't conflict

---

dotnet/global.json
dotnet/samples/GettingStarted/Step1_Create_Kernel.cs
dotnet/samples/GettingStarted/Step2_Add_Plugins.cs
dotnet/samples/GettingStarted/Step3_Yaml_Prompt.cs
dotnet/samples/GettingStarted/Step4_Dependency_Injection.cs
dotnet/samples/GettingStarted/Step5_Chat_Prompt.cs
dotnet/samples/GettingStarted/Step6_Responsible_AI.cs
dotnet/samples/GettingStarted/Step7_Observability.cs
dotnet/samples/GettingStarted/Step8_Pipelining.cs
dotnet/samples/GettingStarted/Step9_OpenAPI_Plugins.cs

This pull request updates the `GettingStarted` samples to replace the use of `AddOpenAIChatCompletion` with `AddOpenAIChatClient` for creating kernels, aligning the code with the newer `ChatClient` API. Additionally, it updates documentation and examples to reflect this change and introduces minor improvements to the dependency injection setup.

.Net: Update GettingStarted to use M.E.AI.ChatClient

---

python/semantic_kernel/agents/azure_ai/agent_content_generation.py
python/semantic_kernel/agents/azure_ai/agent_thread_actions.py
python/tests/unit/agents/azure_ai_agent/test_agent_content_generation.py

The same `agent_content_generation` method is used to handle both `bing_grounding` and `bing_custom_search` tool calls; however, the method expected that the dicts on the underlying types were named the same - which they aren't. They have their respective names, as shown above.
Fix Bing content generation based on the instance we're dealing with.
- Add unit tests.
- Closes #12746

Python: fix Bing grounding & custom search content generation

---

dotnet/samples/GettingStartedWithAgents/Orchestration/Step03_GroupChat.cs
dotnet/samples/GettingStartedWithAgents/Orchestration/Step03a_GroupChatWithHumanInTheLoop.cs
dotnet/samples/GettingStartedWithAgents/Orchestration/Step06_DifferentAgentTypes.cs
dotnet/src/Agents/Orchestration/AgentActor.cs
dotnet/src/Agents/Orchestration/GroupChat/RoundRobinGroupChatManager.cs
dotnet/src/Agents/Runtime/Core.Tests/AgentRuntimeExtensionsTests.cs
dotnet/src/Agents/Runtime/InProcess.Tests/PublishMessageTests.cs
dotnet/src/Agents/Runtime/InProcess/InProcessRuntime.cs

Fixes: https://github.com/microsoft/semantic-kernel/issues/12731
Fixes: https://github.com/microsoft/semantic-kernel/issues/12646
Fixes: https://github.com/microsoft/semantic-kernel/issues/12592
Fixes: https://github.com/microsoft/semantic-kernel/issues/12626
Orchestration not providing the expected result.
Undefined termination condition results in orchestration always running until the maximum number of turns.  This result in blank messages present in the history as the agents have no completed the task.
In addition, the orchestration result for the sample is not the last message (which is the default for `RoundRobinGroupChatManager`).  The result is always the writer output.
Also:
- Addresses bizarre issue in `AgentActor` where response variable assignment from function closure …

.Net Agent Orchestration - Fix GroupChat Samples

---

python/tests/integration/agents/azureai_agent/test_azureai_agent_integration.py

The AzureAI Agent code interpreter is failing when asking it to use the code interpreter to create bar charts. Updating the unit test so that it uses the code interpreter and doesn't fail/block.
Update integration test while trying to understand the root cause of the failure.

Python: AzureAI Agent int test update to pass

---

dotnet/src/Agents/Magentic/MagenticManagerActor.cs
dotnet/src/Agents/UnitTests/Magentic/MagenticOrchestrationTests.cs
python/semantic_kernel/agents/orchestration/magentic.py

Related to #12687
Related to #12656 
Currently, the Magentic orchestration returns a static message if the max reset limit or the max invocation limit is reached.
Return the last agent response if either of the limit is reached.

Python: .Net: Magentic orchestration to return the last agent message when limits reached

---

python/samples/getting_started_with_agents/openai_responses/README.md
python/semantic_kernel/agents/azure_ai/agent_thread_actions.py

When errors occur processing a run of an AzureAIAgent, we surface the error message but not the incomplete_details reason if it exists.
This PR adds handling for the incomplete details reason, if it exists, so it can be passed back via the error message.
- Closes #12752

Python: Add incomplete details reason to AzureAIAgent error message

---

python/samples/concepts/setup/chat_completion_services.py
python/semantic_kernel/connectors/ai/bedrock/README.md
python/semantic_kernel/connectors/ai/bedrock/bedrock_settings.py
python/semantic_kernel/connectors/ai/bedrock/services/bedrock_base.py
python/semantic_kernel/connectors/ai/bedrock/services/bedrock_chat_completion.py
python/semantic_kernel/connectors/ai/bedrock/services/bedrock_text_completion.py
python/semantic_kernel/connectors/ai/bedrock/services/bedrock_text_embedding.py
python/semantic_kernel/connectors/ai/bedrock/services/model_provider/bedrock_model_provider.py
python/tests/unit/connectors/ai/bedrock/conftest.py
python/tests/unit/connectors/ai/bedrock/services/test_bedrock_chat_completion.py
python/tests/unit/connectors/ai/bedrock/services/test_bedrock_text_completion.py
python/tests/unit/connectors/ai/bedrock/services/test_bedrock_text_embedding_generation.py

Fixes #12833 
Add an optional setting to the Bedrock AI connectors to allow users to specify the Bedrock model providers (i.e. amazon, anthropic, etc) so that they can use application inference profiles.

Python: Add bedrock model provider parameter

---

dotnet/test/VectorData/MongoDB.ConformanceTests/MongoDB.ConformanceTests.csproj
dotnet/test/VectorData/MongoDB.ConformanceTests/Support/MongoTestEnvironment.cs
dotnet/test/VectorData/MongoDB.ConformanceTests/Support/MongoTestStore.cs
dotnet/test/VectorData/VectorData.ConformanceTests/Support/TestStore.cs

We are running the SK tests in our https://github.com/mongodb-labs/ai-ml-pipeline-testing repo and would like to also be able to run them against live MongoDB Atlas clusters for further verification rather than just the Docker image.
The PR adjusts the vector data tests (only as per @roji recommendation) so that if an environment variable named `MONGODB__CONNECTIONURL` exists then that is used to connect to MongoDB rather than using TestContainers to fire up a Docker image of MongoDB Atlas.
Additionally to improve reliability it was found that we need to increase the number of attempts to wait for the data to be ready after creating an index. (Bumped from 20 to 200). We're going to look at adding index status helper methods in the C# Driver going forward for a better experience.
Once this …

.Net: Allow the MongoDB VectorData tests to run without an image

---

python/semantic_kernel/connectors/mcp.py
python/uv.lock

The parsing of tool call output was not working correctly, this fixes that.
Solves #12850

Python: fix parsing of types in mcp server

---

python/semantic_kernel/__init__.py

Bump Python version to 1.35.3 for a release
Bump Python version to 1.35.3 for a release

Python: Bump Python version to 1.35.3 for a release

---

dotnet/src/Functions/Functions.OpenApi/OpenApiKernelPluginFactory.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/OpenApiKernelPluginFactoryTests.cs
dotnet/src/Functions/Functions.UnitTests/OpenApi/TestPlugins/documentV2_0.json
dotnet/src/Functions/Functions.UnitTests/OpenApi/TestPlugins/documentV3_0.json
dotnet/src/Functions/Functions.UnitTests/OpenApi/TestPlugins/documentV3_1.yaml

This PR adds OpenAPI parameter description to its schema to provide more details to ai model about it.

.Net: Add OpenApi parameter description to its schema

---

dotnet/samples/GettingStartedWithAgents/OpenAIResponse/Step01_OpenAIResponseAgent.cs
dotnet/src/Agents/OpenAI/Extensions/ChatContentMessageExtensions.cs
dotnet/src/Agents/OpenAI/Extensions/KernelContentExtensions.cs
dotnet/src/Agents/UnitTests/OpenAI/Extensions/ChatContentMessageExtensionsTests.cs

.Net: Fix OpenAiResponseAgent chat message images removed by SK

---

dotnet/samples/GettingStartedWithAgents/OpenAIResponse/Step03_OpenAIResponseAgent_ReasoningModel.cs
dotnet/src/Agents/OpenAI/Internal/ResponseThreadActions.cs

.Net: Filter out reasoning response items during function calling

---

python/semantic_kernel/agents/open_ai/assistant_thread_actions.py

Current, while using an OpenAIAssistantAgent, we are returning code output via the on_intermediate_message callback. This shouldn't be happening right now, as all other agents return code via TextContent with a metadata `{"code": True}` key-value pair in the dictionary.
- Closes #12956

Python: Don't return code output via on_intermediate_msg callback

---

dotnet/src/VectorData/MongoDB/MongoCollection.cs

The ObjectID and Guid string support work in #12827 did not include support for the method overloads that take an IEnumerable of keys. I suspect this was due to merge/out of sync branches and was then missed with the tests being disabled (they now pass).
Adds the support for Guid and ObjectID keys to the GetAsync, DeleteAsync and UpdateAsync methods that take an IEnumerable.

.Net: Fix batch operation non-string keys with MongoDB
